### ISSUE TITLE
検索機能について要望

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#1017]
1. クエリをパーセントエンコードする
2. 検索でもWebSocketでリアルタイムに情報を取得できるように
3. クエリの拡充
  - and, or, -
  - user:<ユーザーID> = #155 
  - 日時指定`since:<Time>`,`until:<Time>`
  - filter:image
  - 正規表現

**Comment by syuilo** [comment]
正規表現は危険そう(サーバーの負荷的に)

**Comment by syuilo** [comment]
WebSocketについても厳しそう

**Comment by syuilo** [comment]
ポーリングなら出来そう

**Comment by syuilo** [comment]
~~クエリをパーセントエンコードするについてですが、
https://github.com/visionmedia/page.js/issues/187
の問題があるのであまり解決にはならなそう~~

**`?q=hoge`のような形で受け付けることで解決しました**
