### ISSUE TITLE
.config フォルダがあると設定作成に失敗する

### ISSUE THREAD

**Issue by otofune** [misskey-dev/misskey#1090]
それは無視して新たに生成した設定で上書きするのが好ましいと思う

**Comment by otofune** [comment]
コンテナに押し込めるときに npm run config をするためだけにホストに Node.js を入れさせたくないししたくなかったのでマウントで出来るようにするためにこれをどうにかする変更を入れてしまった (#1089, https://github.com/syuilo/misskey/pull/1089/commits/36987cc3cea9ed8beb543d8521f5d16c9fcf32ea)

**Comment by syuilo** [comment]
Resolved
