### ISSUE TITLE
引用構文

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#1153]
テキストを引用してきたことを示す構文を追加する

**Comment by syuilo** [comment]
行頭に > 付けるとか
でもそれだと複数行の引用では面倒になるなぁ

**Comment by syuilo** [comment]
"
text
"
とか

**Comment by tamaina** [comment]
">"の引用も欲しい

**Comment by acid-chicken** [comment]
@tamaina
こんな感じ？`^(>+)\s(.+)(?:\n\1\s(.+))*$`
