### ISSUE TITLE
リバーシの変則ルール

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#1200]
# ルール案一覧
* [x] 特殊マップ(黒白空穴)
* [x] 石が少ない方が勝ち
* [x] 石を挟んでなくても置ける
* [x] ループ
* [ ] 縦横の挟みでしかひっくり返せない or 斜めでしかひっくり返せない
* [ ] 一度石を置いたら二度とひっくり返せないマス
* [ ] 相手の石を破壊できるアイテム
* [ ] 3人以上が1つのゲームにでてくる
* [ ] ゲーム終了時にあるマスを取っていれば高得点
* [ ] 1ターンに石を2つ置く
* [ ] 置くと 勝ち/負け になるマス

**Comment by syuilo** [comment]
たとえマップが正方形でないとしてもプログラム上は正方形(マスが無い部分は「マス無し」という情報で埋める)として扱った方が楽そう

**Comment by AyaMorisawa** [comment]
3人以上が1つのゲームにでてくるみたいな変則ルールはどうですか

**Comment by syuilo** [comment]
考えたことはありますね

**Comment by AyaMorisawa** [comment]
実装つらそう

**Comment by syuilo** [comment]
ただプログラムが複雑になりそう

**Comment by AyaMorisawa** [comment]
ゲーム終了時にあるマスを取っていれば高得点みたいなのはどうでしょう

**Comment by syuilo** [comment]
おもしろそう

**Comment by AyaMorisawa** [comment]
石を挟んでなくても置くことはできるみたいなルールにするとゲーム性はどうなるのだろう

**Comment by syuilo** [comment]
囲碁みたいになりそう

**Comment by syuilo** [comment]
実装してみますか？

**Comment by syuilo** [comment]
今までの常識が通用しなくなることが予想される

**Comment by AyaMorisawa** [comment]
実装して遊びながらの方が考察は、はかどりそう

**Comment by AyaMorisawa** [comment]
1ターンに石を2つ置くルール

**Comment by syuilo** [comment]
置くと勝ちになるマス or 置くと負けになるマス
というのはどうでしょう

**Comment by syuilo** [comment]
どこでも置けるモード実装

**Comment by syuilo** [comment]
ローカルでやってみたけど意外と面白い

**Comment by syuilo** [comment]
囲碁っぽい

**Comment by syuilo** [comment]
マップの上下左右がループして繋がっているモードとかどうだろう

**Comment by syuilo** [comment]
単純な正方形や長方形のマップでそのモードを有効にした場合、**辺や隅という概念が消失する**ことになる

**Comment by syuilo** [comment]
複雑な形のマップでは上下左右がループしても辺や隅が残る可能性はある

**Comment by syuilo** [comment]
ループモード実装

**Comment by syuilo** [comment]
縦横/斜めとかよりももっと粒度を高めて、8方向個別に有効無効切り替えられるというのはどうだろう
例えば左と右上しかひっくり返せないとか
