### ISSUE TITLE
(モバイル)長いコンテンツが表示されたときのx方向のスクロール

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#127]
できないほうが操作性と見た目はいいと思います

----

* Firefox Beta
* モバイル版Misskey

**Comment by syuilo** [comment]
Fixed via https://github.com/syuilo/misskey/pull/143 thank you @tamaina

**Comment by syuilo** [comment]
Reverted via https://github.com/syuilo/misskey/commit/8107a6e5390f8cd1446e938207f7e5cd12087554
`overflow(-x|-y): hidden`を上位の要素に適用すると不具合が発生するので戻しました
折り返すように設定しているのに折り返されないのはレンダリングエンジンのバグな気がするのでどうしようもなさそう

**Comment by tamaina** [comment]
具体的にどこで不具合が起きていたか教えてください

**Comment by syuilo** [comment]
`position: sticky`が効かない

**Comment by tamaina** [comment]
タイムラインで？詳細画面で？

**Comment by syuilo** [comment]
前者

**Comment by tamaina** [comment]
**慌てて消してしまった**

> ホームで？詳細画面で？

詳細画面はそもそも表示方法が違いましたごめんなさい

これは謎

**Comment by syuilo** [comment]
上位に`overflow hidden`が指定されていると効かなくなるのは仕様なのかバグなのか不明

**Comment by tamaina** [comment]
ブラウザ依存のバグ可能性が高いです

**Comment by syuilo** [comment]
ふぅ～む

**Comment by tamaina** [comment]
対策してコンテンツははみ出ないはずなので`overflow(-x|-y): hidden`は必要ない

**Comment by syuilo** [comment]
長いURLがはみ出す場合が

**Comment by syuilo** [comment]
長いURLがはみ出す現象は(私は)iOSでのみ確認しています
CSSで折り返すように指定しているのでバグかと思われます

**Comment by tamaina** [comment]
`word-wrap`→`overflow-wrap`に

**Comment by tamaina** [comment]
https://codepen.io/nksm/post/overflow-position-sticky

**Comment by tamaina** [comment]
src/web/app/reset.styl:12ミスってる

**Comment by syuilo** [comment]
やっぱりはみ出しますね

**Comment by tamaina** [comment]
iPhoneじゃないのでなんとも...

**Comment by tamaina** [comment]
`word-break: break-all`してみる

**Comment by syuilo** [comment]
`word-break break-all`することで解決しました
