### ISSUE TITLE
Mastdon互換API

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#1280]
MastdonクライアントでMisskeyが利用できるようになる

**Comment by syuilo** [comment]
おそらくMisskeyの方が高機能なのでいくつかの情報は失われる
例えば、Misskeyはリアクションという概念があるが、Mastdonにはない(と思う)ので、全てのリアクション(もしくは特定のリアクション)は「いいね」のようなものに変換して表示されることになるだろう
逆にMastdonクライアントから「いいね」のようなアクションを起こすとしたらそれらは「:+1:」のようなリアクションに変換されるだろう

**Comment by syuilo** [comment]
投票機能はMastdonにはないのかな？
無かったとしたらそれも何らかの変換か非表示にせざるを得ない
まあ投稿の本文に「(投票)」みたいな感じで投票が本来添付されているということを示すだけでも十分だろう

**Comment by tamaina** [comment]
まとめてみた

# Mastodon(master)だけにある機能
* [CW](https://ja.mstdn.wiki/Content_Warning)
* [NSFW](https://ja.mstdn.wiki/NSFW)

# Misskeyだけにある機能
- 投票
  * friends.nicoには[アンケートとして実装されている](https://friends.nico/@aqz/99760016850542285)
- 位置情報の添付

# 機能の差異
- お気に入り と リアクション

# 気にしなくていい差異
- 文字数制限

# 完全に一致する機能

※実装の差異はあるかもしれない

- リポスト(Misskey) = ブースト(Mastodon)
- フォロー
- リプライ
- ミュート
- メディアの添付

**Comment by syuilo** [comment]
引用RepostもMastodonにはなさそう

**Comment by syuilo** [comment]
引用Repostは`hoge RP: @huga「piyo」`みたいなテキストに変換すれば良さそう

**Comment by syuilo** [comment]
CWとNSFWというのはMisskeyにも取り入れてもいいかもしれないですね

**Comment by syuilo** [comment]
仮に互換APIを実装したとしてもそれ以降常にMastodonに追従していかないといけなくなり保守が困難になりそうなので見送る

**Comment by acid-chicken** [comment]
将来的な互換APIを目標としたエンドポイント群を作成していきたい。
