### ISSUE TITLE
クラスタ数を制限できるように

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#1325]
デフォルト ... 全てのコアを使ってクラスタリングする
0 ... クラスタリングしない
n ... n個のコアを使ってクラスタリングする
-n ... n個のコアを残してクラスタリングする(例えば8コアあるPCで-2指定すると6コア使う)

**Comment by AyaMorisawa** [comment]
@syuilo already implemented?

**Comment by syuilo** [comment]
yeah. thx
