### ISSUE TITLE
常時的なプッシュ通知

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#135]
ブラウザを開いていなくても通知が送られてくるようにして

現状、PCのChrome,FirefoxとAndroidのChromeが対応済

例:Facebook

https://w3c.github.io/push-api/

----

* Chrome (on Android)
* モバイル版Misskey

**Comment by syuilo** [comment]
probably related to https://github.com/syuilo/misskey/issues/80

**Comment by syuilo** [comment]
やり方が分からない

**Comment by syuilo** [comment]
implemented
