### ISSUE TITLE
ソートにIDを使わない

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#1405]
代わりにcreatedAtを使う
ActivityPubのようにデータベースに挿入した順序が必ずしも投稿を作成した順序とは一致しない場合もあるため

**Comment by akihikodaki** [comment]
IDとcreatedAtを使う場面を分ける必要がある。例えば、タイムラインの構築はIDでやったほうが良い。そうすると、ストリーミングで受け取った順序とタイムラインでの表示順序を一致させることができる。
ただし、MongoDBのIDはかならずしも単調ではない (データベースに保存した時系列と一致しない) ことに注意する。クラスタ構成ではクラスタによってIDが前後する。そのため、順序を保証できるのは秒精度でしかない。

**Comment by syuilo** [comment]
ふぅ～～～～～～む
