### ISSUE TITLE
ドメイン部を含まないメンションが受信したインスタンスのアカウント宛と勘違いされる

### ISSUE THREAD

**Issue by unarist** [misskey-dev/misskey#1427]
同じインスタンス内のアカウントへのメンションはドメイン部を書かずに `@foo` と書くことが多いが、例えば `misskey.xyz` が `mastodon.social` からこれを受けとると、 `@foo@misskey.xyz` 宛のメンションとして通知が発生してしまう。クライアント側でのリンク化も同様。

**Comment by syuilo** [comment]
リモートの投稿内のメンションでホスト部分が省略されている場合、暗黙的にその投稿を行ったユーザーのホストが指定されているとみなした方が良さそうですね

**Comment by unarist** [comment]
改めて確認してみて、他所だとホスト部分込みでメンション書いてもHTML上では省略されるのを思いだしました…。

例えばMastodonではActivityPubのMentionタグを使ってこのあたりを判断していて、少なくとも通知に関しては https://www.w3.org/TR/activitystreams-vocabulary/#microsyntaxes で言及があります。

リンク化については、MastodonではMentionタグで指定されたactorのurlプロパティとhrefが一致するリンクを当該メンションとして扱い、WebUIでプロフィールを開くようにしていたのですが、Pleromaはactor.uriの方をhrefにしていたらしく、という話もあってうーん。

c.f. https://github.com/tootsuite/mastodon/issues/6839 https://github.com/tootsuite/mastodon/pull/6934

**Comment by syuilo** [comment]
Fixed
