### ISSUE TITLE
リモートユーザーの情報更新

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#1448]

**Comment by syuilo** [comment]
リモートユーザーに直近の情報取得日時を記録しておいて、APでそのユーザーに関わるアクティビティが届いたとき、そのユーザーの直近の情報取得日時が１日以上前なら新しい情報を持ってくるとか

**Comment by unarist** [comment]
Mastodonに関して言えば、プロフィールが更新されるとフォロワーに `Update<Person>` のアクティビティを配信するので、それを処理すればすぐに反映することができます。もっとも、直接のフォロー関係がないアカウントについてはやはり、こちらから取得する必要がありますが。
