### ISSUE TITLE
サムネイル画像のサイズのラインナップを固定しキャッシュする

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#1449]
実装に方法は以下の2つが考えられる

- 投稿時に全てのサイズのサムネイルを生成する
  * 送出が速い。しかし、一度に多くのCPU能力を要求され、また全く使われない画像も容量を消費する。
- キャッシュがあったらそれを返す。なければ生成し、その結果を返して保存する
  * 送出は遅い。しかし、CPU能力が最小限に済み、必要な画像だけ保存される。

**Comment by tamaina** [comment]
#1139

**Comment by syuilo** [comment]
サイズをpx指定するのではなくて ?thumbnail&size=icon みたいにして全部128pxくらいの大きさのサムネイル返すようにするとか良さそう

**Comment by syuilo** [comment]
そうすれば#1139を実装したのとほぼ同じ効果を得られる

**Comment by tamaina** [comment]
ラインナップの例としては…

1. 英単語
    * original : size指定なし
    * small | low | sIcon  :  size=64ぐらい
    * regular | LIcon : size=192ぐらい
    * medium |  : size=640ぐらい
    * veryLarge | veryHigh : size=1270ぐらい
    * サイズ | 解像度
    * iconとかじゃなくて汎用的な単語が良さそう。しかし実装者の好みによるものが大きいし、間違いじゃない。
2. 数値
    * 設定した数値以外受け付けないようにすればラインナップしたといえる

などでしょうか？

数値のほうがclientのコードをあまり変更しないでいいので楽そう
