### ISSUE TITLE
リモートユーザーのアカウントに対してはNotificationを生成しない

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#1455]
絶対に見られることはないので無駄

**Comment by tamaina** [comment]
Closeしていいかんじがする

**Comment by 4ioskd** [comment]
Is it solved?

**Comment by KisaragiEffective** [comment]
triage: おそらく解決済み。解決していない場合はre-openをお願いします。

**Comment by zyoshoka** [comment]
いや FTT 関係ないですね、自分が普通に duplicate してたかも（まあこれは close ということにしておきましょう）
