### ISSUE TITLE
【モバイル版】誕生日に10000年1月1日以降を設定して保存を押すと、固まって失敗する

### ISSUE THREAD

**Issue by ANNotunzdY** [misskey-dev/misskey#1477]
iOS 11.3 標準Safariにて確認

誕生日に10000年1月1日以降を設定した状態で「保存」を押すと、
「保存」ボタンが暗くなったまま、保存に失敗してしまいます。
![4b1101c9-17c1-4218-ab47-371096666ee9](https://user-images.githubusercontent.com/525548/38777724-f35735f4-40e7-11e8-9b13-50e77bce2475.png)

**Comment by syuilo** [comment]
ありがとうございます！

**Comment by rinsuki** [comment]
https://github.com/syuilo/misskey/pull/5174 で修正された
