### ISSUE TITLE
bull-board用のトークンのCookieにSecure属性が設定されていない

### ISSUE THREAD

**Issue by nexryai** [misskey-dev/misskey#15176]
### 💡 Summary

Bullのダッシュボードの認証用にログイン時にCookieが設定されているが、`Secure`や`SameSite`などの属性が設定されていない。
https://github.com/misskey-dev/misskey/blob/3c81926f71f04b43455dd6a5e6302eb2c35f58ba/packages/frontend/src/account.ts#L216  

### 🥰 Expected Behavior
 - `HttpOnly`以外のセキュリティ属性がCookieに設定される

### 🤬 Actual Behavior
セキュリティ関係の属性がデフォルトのままであり設定されていない。

### 💻 Frontend Environment

```markdown

```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service: OVH Cloud VPS
* Misskey: 2024.11.0
* Node: 公式Dockerイメージを使用
* PostgreSQL: 15
* Redis: 7
* OS and Architecture: Docker
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kakkokari-gtyih** [comment]
https://github.com/misskey-dev/misskey/security/advisories/new へどうぞ

**Comment by nexryai** [comment]
言葉足らずでしたら申し訳ないです、セキュリティ的には良くない状況であるもののIEなどMisskeyが動作しないような古いブラウザを除いた最近のブラウザであれば（少なくとも私の確認した範囲では）実際の影響はないという認識のため、公開Issueとして報告しました。
