### ISSUE TITLE
通知テキストの (0つのメディア) は省略したい

### ISSUE THREAD

**Issue by unarist** [misskey-dev/misskey#1520]
![image](https://user-images.githubusercontent.com/705555/39027990-8dffcff8-448f-11e8-9227-b4e1ed65a23f.png)

**Comment by rinsuki** [comment]
fixed in https://github.com/syuilo/misskey/commit/a16b96ccc02f86e2b9c8932de883db537b9ffc48 ?

**Comment by syuilo** [comment]
このIssueが立てられたのがそのコミットより後なので違いそう

**Comment by syuilo** [comment]
やっぱり解決してそう
