### ISSUE TITLE
時間を置いてタイムラインに再接続した場合、タイムラインを初期化する

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#1538]

**Comment by syuilo** [comment]
再接続したら、タイムラインの最も最新の投稿をひとつ取ってきて、それがメモリ上のタイムラインの最新と違っていたら取りこぼしが発生しているということなのでその時だけ読み込み直すとか

**Comment by syuilo** [comment]
タイムラインに限らずストリームに依存するコンポーネントは多いのでいっそ切断されたらダイアログ出してページ全体をリロードできるようにするとか
