### ISSUE TITLE
投票を他のMisskeyインスタンスに伝える

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#1555]

**Comment by mei23** [comment]
Question Activity などみつけた
https://www.w3.org/TR/activitystreams-vocabulary/#dfn-question
https://www.w3.org/TR/activitystreams-vocabulary/#questions

**Comment by mei23** [comment]
でもQuestion Activityコレジャナイ感がするわ

**Comment by mei23** [comment]
お一人様インスタンスで投票を作成すると、自分しか投票できないという悲しい状況になるみたい。

**Comment by acid-chicken** [comment]
Question Activity、割と近そうではある
