### ISSUE TITLE
ブラックモード

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#1563]
有機ELでは消費電力を下げることができる

**Comment by acid-chicken** [comment]
~~It seems already resolved.~~

**Comment by syuilo** [comment]
まだ手を付けてないですね

**Comment by syuilo** [comment]
ブラックとは rgb(0, 0, 0) を指しています

**Comment by acid-chicken** [comment]
~~ダークモードとは別でしたか、失礼。となると、bodyにfilterをかけるだけではダメ？~~ なるほど、背景を完全に#000000にするのですね。

**Comment by syuilo** [comment]
雑な実装ならそれでも良さそうだけどデザインとか考えるならちゃんとやった方が良さそう

**Comment by syuilo** [comment]
一番の問題は、私が有機ELを搭載したデバイスを持っていないため、モチベーションが上がらないこと

**Comment by acid-chicken** [comment]
早急に有機ELデバイスをギフトする必要がある。

**Comment by rinsuki** [comment]
related: #1999

**Comment by MeCSan** [comment]
たしか、次期iPhoneデバイスは全モデルなので、それに合わせれば…(あ、柑橘系です)
