### ISSUE TITLE
i18n: plurals handling

### ISSUE THREAD

**Issue by mkljczk** [misskey-dev/misskey#1573]
In some languages there are different ways to handle plurals, will Misskey i18n support them? For example, in Polish we have (char = znak):
1 znak
2-4, 22-24, 32-34 etc. znaki
5-21, 25-31 etc. znaków
English is simpler, we only have 1 char and 0 or 2-∞ chars…

**Comment by syuilo** [comment]
hmm....
Are there any good ideas?

**Comment by mkljczk** [comment]
Looks like i18n refactorization fixed it, I’ll check it when I get some internet connection on a computer 😆

**Comment by mkljczk** [comment]
Looks like it works, let me close this issue and create another one about pluralizing all the strings
