### ISSUE TITLE
人狼ゲーム

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#1606]
https://ja.wikipedia.org/wiki/%E6%B1%9D%E3%81%AF%E4%BA%BA%E7%8B%BC%E3%81%AA%E3%82%8A%E3%82%84%3F

**Comment by shironoir** [comment]
https://jinrou.uhyohyo.net/manual/about

**Comment by Sayamame-beans** [comment]
triage: 閉じます。実装したくなったら再openする感じでお願いします 🙏
