### ISSUE TITLE
投稿のwatchシステム

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#161]
* 投稿をいいねしたりrepostしたりするとその投稿がwatchされる
* watchしている投稿へのいいねやrepostや返信の通知は自分にも届く

**Comment by syuilo** [comment]
(将来的に)その投稿に返信やRPやリアクションしたときに自動でwatchするかどうかを設定できるようにもする

**Comment by tamaina** [comment]
ウォッチしている投稿が自分のか他人のかわかるようにしてほしい
