### ISSUE TITLE
外部インスタンスに対してフォロワー数を水増しする機能

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#1616]
inflated!

**Comment by Johann150** [comment]
I think hiding the follower count is more sensible (#7959).

**Comment by tamaina** [comment]
I don't know why you would want to hide your follower count, but I think it's more natural to hide the numbers when the following/followers visibility is hide.

**Comment by mei23** [comment]
https://github.com/misskey-dev/misskey/pull/7959 でフォロー数隠してるけどMastodonとか隠す前の値を採用し続けじゃうみたい。
結局なにか値を送らないと隠れなそうだけど0にするのもアレだから、なんか適当な値を送りたい。

**Comment by Johann150** [comment]
I know that Pleroma and Mastodon have similar features:
Mastodon: Preferences > Other > Hide your social graph
Pleroma: Profile > (Don't show who I'm following | Don't show follow count | Don't show who's following me | Don't show follower count)

I wonder how they implement it. https://github.com/mastodon/mastodon/issues/16382 seems interesting.

**Comment by syuilo** [comment]
このIssue自体は要らないと思うから閉じる
