### ISSUE TITLE
バッジ機能

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#1630]

**Comment by u1-liquid** [comment]
こんな感じかな
![image](https://user-images.githubusercontent.com/17376330/59254651-8f97f280-8c6b-11e9-95be-44ef9dca2a80.png)

**Comment by EbiseLutica** [comment]
ピン留めと独立しているべきという考えと、バッジのついているアカウントを今のピン留めユーザーの項目に表示させるべきという考えが個人的に交錯しています。

この機能自体凄く素晴らしいのですが、既存機能との兼ね合いについて、議論を重ねる必要がありそうですリ

**Comment by tamaina** [comment]
ロールで実現…した？
