### ISSUE TITLE
Incorrect escaping of &

### ISSUE THREAD

**Issue by l2dy** [misskey-dev/misskey#1666]
`` `"&amp;"` `` in notes is displayed as `"&"`.

**Comment by tamaina** [comment]
なんか直ってそう

**Comment by l2dy** [comment]
Not yet, see https://misskey.xyz/notes/5bf57f71e041e7002785a2cf.

**Comment by tamaina** [comment]
あーなるほど

```
`"&amp;"`
```

これですね

**Comment by l2dy** [comment]
> あーなるほど
> 
> ```
> `"&amp;"`
> ```
> 
> これですね

Yes, I have updated the issue description.
