### ISSUE TITLE
BioのTwitterアカウントのリンクを非表示にできるように

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#1669]

**Comment by syuilo** [comment]
むしろ表示するのを廃止した方がいいかも(連合できないし)
表示したい人は詳細情報のとこにリンク貼り付ければ良さそう

**Comment by u1-liquid** [comment]
> むしろ表示するのを廃止した方がいいかも(連合できないし)

v11では補足情報扱いされて連合されてたけど👀
