### ISSUE TITLE
Infinite load time

### ISSUE THREAD

**Issue by Phahou** [misskey-dev/misskey#1699]
I can't access the webpage of [misskey.xyz](https://misskey.xyz) with firefox in a normal tab window
in a private tab it works fine but idk why. The issue came to light at about Wednesdays I think.
The page only loads:
`/assets/desktop...` and `/api/meta`
with status 200
but then the loading circle just keeps spinning : /

**Comment by syuilo** [comment]
That’s Interesting. I will investigate it ASAP.
Thank you for your reporting!

**Comment by syuilo** [comment]
I can not reproduce this... 🤔

**Comment by Phahou** [comment]
I will check it later if it is only on my desktop PC as I have a laptop too.
Maybe it's only some cookie option
EDIT: Just cleared the cookies and it works again. Hm... mystical
