### ISSUE TITLE
Misskeyでメンションを書いてもActivityPub上のメンションにならない

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#1712]

**Comment by syuilo** [comment]
wtf

**Comment by rinsuki** [comment]
Mastodonでは:
DMでない場合: `cc`に配列でリプライ先と自分のfollowersを入れている
DMの場合: `to`に配列でリプライ先を入れている。ccは空
おまけとして `tag`に
```json
    {
      "type": "Mention",
      "href": "https://mstdn.rinsuki.net/users/rinsuki",
      "name": "@rinsuki"
    }
```
のようなものを入れている。

**Comment by rinsuki** [comment]
Misskeyではそもそも`tag`に入るのはhashtagだけだしto/ccは固定なようなので、ちゃんとメンションとかを見て判断するようにしないといけなさそう

https://github.com/syuilo/misskey/blob/4d914f5c0a89cfcc1a2eb674948cd9cb999965ca/src/remote/activitypub/renderer/note.ts#L55-L58
