### ISSUE TITLE
Misskeyの投稿埋め込み

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#1714]

**Comment by AyaMorisawa** [comment]
FYI: インスタンス運営者が独自で実装したやつ

https://misskey.io/notes/7vdqkvavg3

**Comment by kakkokari-gtyih** [comment]
埋め込み機能作ってみました（「…」から埋め込みコード発行、`/notes/:id/embed`で埋込用ページを表示）
いかがでしょう？

https://github.com/kakkokari-gtyih/misskey/commit/b8f9130386ca8f884ba55cb149c33ad8992d968d

![image](https://user-images.githubusercontent.com/67428053/230003260-ded56c50-99c8-4c44-83cf-3f4aa7fecb57.png)

![image](https://user-images.githubusercontent.com/67428053/230007496-46c427cc-ad49-42c9-b660-e258f3e1bc8e.png)

**Comment by acid-chicken** [comment]
Related to #9848
