### ISSUE TITLE
誰がどのリアクションを付けたのか見れるようにする

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#1725]

**Comment by syuilo** [comment]
probably related to https://github.com/syuilo/misskey/issues/303

**Comment by syuilo** [comment]
方針:
* リアクションアイコンを一定時間(1秒ほど)ホバーすると表示する
* ストリームで取得したリアクションイベントには、リアクションしたユーザーの情報があるので、それを使う
* そうでない投稿は、ホバー時にリアクション情報を取得する

複雑なところ:
* 「リアクションのユーザー情報」や「ストリーム由来のものかどうか」などの情報を保持する必要がある

未解決:
* モバイル版のUI

---

リアクションイベントを取得した投稿もホバー時にリアクション情報を取得するのでも良いかもしれない

**Comment by acid-chicken** [comment]
> リアクションイベントを取得した投稿もホバー時にリアクション情報を取得するのでも良いかもしれない

重そうだけど、可能ならこれが良さそう。

**Comment by syuilo** [comment]
若干無駄が増える場合があるけどコードが簡潔になる
