### ISSUE TITLE
連合ユーザーの投稿に対してActivityPubオブジェクトを要求されたら元のインスタンスにリダイレクトする

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#1727]

**Comment by syuilo** [comment]
必要？

**Comment by rinsuki** [comment]
あったほうがよさそう

**Comment by syuilo** [comment]
そのインスタンスのものではないオブジェクトの情報を問い合わせに行く場合ってあるかな？

**Comment by rinsuki** [comment]
Misskeyユーザーが「これMastodonでBoostしたい」と思ったときにMastodonの検索窓に投稿詳細URL を突っこむシチュとか

**Comment by rinsuki** [comment]
とはいっても現状だとMisskeyの投稿URLをMastodonの検索窓に入れても出てこないな(バグ?)

**Comment by syuilo** [comment]
ふぅ〜む
