### ISSUE TITLE
/@username へのリクエストでもAcceptヘッダーを見て必要に応じてActivityPubオブジェクトを返す

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#1731]

**Comment by syuilo** [comment]
要る？

**Comment by rinsuki** [comment]
検索窓に https://misskey.xyz/@syuilo などのURLを入れたときに出てほしいみたいなアレがあるのと #1730 で必要になった気がしないでもない

**Comment by unarist** [comment]
相手が知らないMisskeyアカウントにMention書かれたらfetchしようとしますね

**Comment by rinsuki** [comment]
(あとユーザーのAPubオブジェクトをcurlで取るためにわざわざユーザーIDを調べるのがだるい)

**Comment by syuilo** [comment]
なるほど
