### ISSUE TITLE
[localhost installation] Network Error on Sign Up

### ISSUE THREAD

**Issue by DeadSuperHero** [misskey-dev/misskey#1795]
(下に日本語訳があります)

----

Hi MissKey team!

I saw that most of the issues here are not in English, so I hope I'm not breaking any rules by filing an issue in English. If I am, I am sorry. 😛  

**Here is my problem:**

I have successfully installed MissKey to run locally on MacOSX, but when I attempt user registration, I see this:

![misskey](https://user-images.githubusercontent.com/401560/41930996-9002ef34-7931-11e8-8049-fe238fe768fc.jpg)

Attempting to register results in the error message `Account creation failed for some reason. Please try again.`

Is there a way to work around this issue, such as register a user account through the backend somehow? I'm testing out MissKey locally so that I can write a review about it in [We Distribute](https://medium.com/we-distribute)

----

MisskeyをMacOSXのローカルにインストールするのに成功しました。
しかしユーザー登録をしてみると次のように表示されました:

![misskey](https://user-images.githubusercontent.com/401560/41930996-9002ef34-7931-11e8-8049-fe238fe768fc.jpg)

登録しようとした結果 `Account creation failed for some reason. Please try again.` というエラーメッセージが表示されました。

この問題を対処する方法はありますか？例えば、(データベースなどをいじって)バックエンドからユーザーを登録するみたいなことはできますか？
Misskeyをローカルで動かしているのは、[We Distribute](https://medium.com/we-distribute)にレビューを書くためです。

**Comment by tamaina** [comment]
In my experience, this error occurs when Misskey cannot connect to MongoDB. Are the settings correct?

----

私の経験上、このエラーはMisskeyがMongoDBに接続できないときに発生します。設定は合っていますか？

**Comment by Johann150** [comment]
This issue is probably outdated, but you did not specify a Misskey version. Please check if this error still occurs, otherwise I'll close this issue.

**Comment by 4ioskd** [comment]
>In my experience, this error occurs when Misskey cannot connect to MongoDB. Are the settings correct?
https://github.com/misskey-dev/misskey/issues/1795#issuecomment-400609982

MongoDB is used in misskey V11 or V10. In addition, this issue is published in 2018.
I think this issue is outdated.
