### ISSUE TITLE
Enable sending Private Messages by pressing return/enter on keyboard

### ISSUE THREAD

**Issue by wakest** [misskey-dev/misskey#1804]
Enable sending messages by pressing return/enter on keyboard, you currently have to click the paper airplane button on the bottom right after every message you right which is non-standard in messaging apps.

noticed on misskey.xyz on version 1.0.6815

**Comment by AyaMorisawa** [comment]
Have you tried Ctrl+Enter?

**Comment by tamaina** [comment]
Messages can be sent by pressing `Ctrl`+`Enter` so far.  
How about implementing a option to send by pressing only `Enter`? @syuilo

**Comment by syuilo** [comment]
Yeah, I would like to implement the option to send by `Enter`.

**Comment by wakest** [comment]
maybe we should also add the keyboard shortcut at a tooltip so you can see what it is if you hover over the send button.
