### ISSUE TITLE
Delete button is not loading icon in Private Messages

### ISSUE THREAD

**Issue by wakest** [misskey-dev/misskey#1805]
delete button in messages is not loading icon
looks like its looking here for an icon that doesn't exist:
https://misskey.xyz/assets/desktop/messaging/delete.png

<img width="474" alt="screen shot 2018-06-27 at 9 10 15 pm" src="https://user-images.githubusercontent.com/7890201/41994448-be0ba042-7a4e-11e8-956f-f885a8f4c377.png">

noticed on misskey.xyz on version 1.0.6815

**Comment by AyaMorisawa** [comment]
#1928
