### ISSUE TITLE
Legacy keyId

### ISSUE THREAD

**Issue by Gargron** [misskey-dev/misskey#1828]
On line: https://github.com/syuilo/misskey/blob/master/src/remote/activitypub/request.ts#L40

The keyId uses the OStatus format acct:username@domain. This works with e.g. Mastodon, but in ActivityPub the preferred way is a resolveable ID, e.g. `https://example.com/actor/key` (it can refer to a key in a separate document or an actor with an embedded key)

**Comment by mei23** [comment]
Line moved to
https://github.com/syuilo/misskey/blob/c7c3f6999b40ec0a576c5537f02a8025ef7e6acd/src/remote/activitypub/request.ts#L35

**Comment by syuilo** [comment]
Fixed by @mei23
