### ISSUE TITLE
ActivityPubのTLへの反映が遅延する

### ISSUE THREAD

**Issue by xps2** [misskey-dev/misskey#1829]
A(Mastodon)<-->B(Misskey)
C(Mastodon)<-->B(Misskey)
が相互フォロー状態であるとする

Aが投稿(1)
->(BのTLに表示されない)
->Cが投稿(2)
->(1)がBのTLに表示
->Cが新たに投稿(3)
->(2)がBのTLに表示
…
のように一つずつ遅れて表示される。
(3)の投稿は新たにAまたはCが投稿や削除などを行わないとずっと出てこない
TLの流速が早いと気づかないかもしれない

**Comment by syuilo** [comment]
投稿だけではなくリアクションも一段階遅れて伝わってそう

**Comment by syuilo** [comment]
> 新たにAまたはCが投稿や削除などを行わないとずっと出てこない

誰かが何も投稿しなくても、一定時間(10秒くらい)経つと出てくる

**Comment by syuilo** [comment]
測定したところ、**16秒**だった。そしてそれはこれと一致する
https://github.com/syuilo/misskey/blob/e66d7babc5ae477d7a60628e5599f9c390426c81/src/queue/index.ts#L21

**Comment by syuilo** [comment]
でもそれは本来「ジョブが失敗したときに待機する時間」の設定なのでなぜこれが発動するのかはわからない

**Comment by syuilo** [comment]
ライブラリを bee-queue に変えたら直った
