### ISSUE TITLE
Misskey で投稿する際に使用できるコマンドのヘルプページが欲しい

### ISSUE THREAD

**Issue by Asteriskx** [misskey-dev/misskey#1858]
- Wiki に記載するのも有りかもしれないが、ユーザ的には Misskey 内の UI から
ヘルプ画面が見れるとうれしいかもです。

**Comment by AyaMorisawa** [comment]
Related to https://github.com/syuilo/misskey/issues/1809

**Comment by syuilo** [comment]
Done
