### ISSUE TITLE
管理者(Admin)(や権限をもったモデレーター)が自由にバッジを付けられる機能

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#1895]
#1893 #1630
ちなみに、Discordでは「役職」としてサーバー内のユーザーにバッジを付けることができ、モデレーションに関連する権限を役職ごとに付与することができる。

**Comment by acid-chicken** [comment]
Duplicate of #1630

**Comment by acid-chicken** [comment]
Issues are unified. If you want to discuss about this, please go to #1630.

**Comment by tamaina** [comment]
ロール機能前から言ってたよな〜と思ってIssueを探したけどもっとモデレーション上の要求みたいな感じだったのね
