### ISSUE TITLE
メモリリークがある可能性がある

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#1913]

**Comment by syuilo** [comment]
様々な操作をした上でヒープを比較したりして調査しているけど、あまり手がかりはない
強いて言うなら https://github.com/syuilo/misskey/blob/master/src/daemons/server-stats.ts
 が怪しい

**Comment by syuilo** [comment]
https://github.com/syuilo/misskey/blob/master/src/daemons/server-stats.ts でリークしている

**Comment by syuilo** [comment]
# 調査した結果
* 複数のヒープを採取して比較した
* 謎の object が大量にメモリ上に残存していることを確認
* これがメモリリークなのかどうかは判断できない(普通に使われている値の可能性もある)
* Node.js内部で使われているものなのかMisskeyコードに由来するものなのかは不明
* 上記の server-stats などのdaemon系を無効にしても発生する
* オブジェクトがどこに起因するのかや、具体的な中身などは確認できなかった

**Comment by syuilo** [comment]
「デーモン系の処理を無効 かつ どこからもリクエストが無い状態」で再度テストしてオブジェクトが増えるかどうか確認してみることにする

**Comment by syuilo** [comment]
リークが起きているとしたら、クラスターのマスタースレッドではなく、ワーカースレッドで起きていそうだということがわかった

**Comment by syuilo** [comment]
ワーカースレッドをインスペクトする方法がわからない

**Comment by syuilo** [comment]
できた

**Comment by syuilo** [comment]
MongoDB and/or Redisのコネクションプール辺りが怪しい

**Comment by syuilo** [comment]
もう一度調べたけど、**node.jsのインスペクタでMisskeyのプロセスを見ると、メモリを120MB使ってると表示されるのに、Linuxのtopコマンドでプロセスのメモリ使用率を見ると1.2GBってなってる**
謎

(ガベコレ発動させても、1.2GBから変化しない)

**Comment by syuilo** [comment]
つまりMisskeyにメモリリークがあるというよりnode自体にある...？？？

**Comment by syuilo** [comment]
ローカルでサイズの大きい画像を大量にアップロード(URLアップロードも)したりしたけどリークは無さそうだった

**Comment by syuilo** [comment]
デーモン系の処理を無効にした上で、

・投稿がされない状態でもリークするか
・アクセスが無い状態でもリークするか
・ローカルユーザーの投稿がされるとリークするのか
・リモートユーザーの投稿がされるとリークするのか
・ローカルユーザーの投稿がリモートに配信される過程でリークするのか
・画像のアップロードでリークするのか

あたりを確認していきたい

**Comment by marihachi** [comment]
関係がありそうなバグ見つけた
#2344

**Comment by syuilo** [comment]
コネクションが無限に増えても、ユーザーがブラウザを閉じたりページを再度読み込みしたりすれば全て切断されるので、メモリリークとは関係ないかもしれない

**Comment by marihachi** [comment]
そうなのか～

**Comment by syuilo** [comment]
謎

**Comment by syuilo** [comment]
ここの情報がいろいろ古すぎるので立て直す
