### ISSUE TITLE
タグサジェストの回転寿司化

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#1931]
WIP
サジェストが増えていくと投稿フォームが使いづらくなるため

**Comment by syuilo** [comment]
最近使った上位のタグだけ表示するつもりだったけどその処理を忘れて無限に表示されてしまっている

**Comment by acid-chicken** [comment]
俺は止まんねぇからよ、お前らが止まんねぇかぎり、その先に俺はいるぞ！

**Comment by acid-chicken** [comment]
やった(多分) #1939
