### ISSUE TITLE
サーバー管理者がユーザーのドライブ容量を変更できるようにしてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#1948]
# Summary
サーバー管理者は運営費を稼ぐことができ、ユーザーはドライブの容量を増やすことができる  
既にドライブの容量を使い切ったユーザーもいる

# Environment

**Comment by xps2** [comment]
機能に対して購入になるので、寄付ではなくなってしまう。
電気通信事業法やら特定商取引などの考慮が必要になってくる。

**Comment by tamaina** [comment]
法律に則った運用が求められるけれど、それでも利益があると判断する管理者(特に企業？)は居そう

**Comment by u1-liquid** [comment]
ロールでできるようになったかも
