### ISSUE TITLE
ImageMagickのインストールをオプションに

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#1953]
ImageMagick無しの場合、サムネイル生成や画像の色取得などはできなくなる

**Comment by acid-chicken** [comment]
付け加えて、EXIF削除等を別の手段で実装する必要がある？ (#106 を実装するなら)

**Comment by syuilo** [comment]
EXIFの削除はできなくなりそう

**Comment by syuilo** [comment]
ImageMagickは不要になった
