### ISSUE TITLE
リモートのノートのリンクがリンクにならない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#1954]
# Summary
リモートのノートのリンクがリンクにならない  

(例 https://misskey.xyz/notes/5b5237d44f50d70196d0ace9)

# Expected Behavior
(例)において`【Misskeyで投票を見る】`の部分はMisskey内でもリンクとして機能する

# Actual Behavior
(例)において`【Misskeyで投稿を見る】`に書式は何も付与されていない

# Steps to Reproduce
1. 外部のMisskeyインスタンスのユーザーで、こちらのインスタンスのユーザーからフォローされた状態で投票付きの投稿をする
2. こちらのインスタンスでリモートユーザーとしてその外部のインスタンスのアカウントの投稿を見る
3. `【Misskeyで投稿を見る】`がリンクになっているはずのところ、リンクになっていない。

# Environment
any

**Comment by syuilo** [comment]
Resolved
