### ISSUE TITLE
アプリ作成後のリダイレクト先が間違っている

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#1971]
# Summary
アプリ作成後のリダイレクト先が間違っている

# Expected Behavior
`/dev/apps/<appId?>`にいくのが望ましそう

# Actual Behavior
`/apps`にいく

# Steps to Reproduce
1. `/dev`にアクセスする
2. [アプリを管理]を選択
3. [アプリを作成]を選択
4. [アプリケーション名]入力欄に適当なアプリケーション名を記入する
5. [ID]入力欄に適当なIDを記入する
6. [アプリの概要]入力欄にアプリの簡単な説明を記入する
7. 必要に応じて[コールバックURL (オプション)]入力欄にMissskeyからコールバックを受けるURLを記入する
8. [権限]から必要な権限をリクエストする
9. [アプリ作成]を選択

# Environment
OS: Windows 10 Home Insiders Preview Build 17713.rs5_release.180706-1551
Browser: Firefox 62.0b10 (64 ビット)
Misskey: Desktop

**Comment by tamaina** [comment]
fixed at [fbf43c1450ecdf851e0549045854afda694ea85e]

**Comment by KisaragiEffective** [comment]
triage: `GET /dev` が現代のバージョン (2024.5.0) に存在しないので閉じます。もしこの症状が現在まで続いている場合は再openしてください
