### ISSUE TITLE
外部サービスのコンテンツの埋め込みをいきなり展開しない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#1978]
# Summary
Twitterの埋め込みが実装されましたが、Twitterの埋め込みの仕組みは少し重いです。
初期状態でサムネイルを表示し、クリックしたら埋め込みタグを代わりに挿入するようにすれば、重い埋め込みでも大丈夫だと思います

# Environment
any timelines without deck

**Comment by syuilo** [comment]
タイムライン上では埋め込みしないようにしました。
