### ISSUE TITLE
タイムラインのヘッダー部分の色分け

### ISSUE THREAD

**Issue by yarnaimo** [misskey-dev/misskey#1991]
![image](https://user-images.githubusercontent.com/9738886/43258325-5fe4dbd4-910d-11e8-949d-a856980b30f3.png)
![image](https://user-images.githubusercontent.com/9738886/43258988-bee93696-910f-11e8-9ed8-cb1cec20fb42.png)
このように色分けすると表示中のタイムラインが認識しやすくなると思います

**Comment by syuilo** [comment]
デザイン的には今の方が好みかな
