### ISSUE TITLE
通知をカスタマイズする機能

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#1992]
# Summary
投稿の自動ウォッチなどがあるため返信などの重要な通知が埋もれやすい  
Servive Worker Notification、通知ウィジェット、モバイルの通知ページ、Deckの通知カラムそれぞれでどの種類の通知を受け取るかカスタマイズする機能が欲しい

# Environment
every notification display component

**Comment by syuilo** [comment]
重要な通知というのは具体的にどういう通知を指しますか？

**Comment by syuilo** [comment]
通知は現在、重複するような形での通知は行われない(例えばメンションされつつリプライされた場合、リプライとしての通知のみ来る)ので、その仕組みと競合しそう

**Comment by tamaina** [comment]
* 投稿にも既読/未読フラグが付くようになった
* 「あなた宛て」「ダイレクト」タイムラインが実装された

ことで、通知に関する不満はかなり改善されてきたように思う

投稿のウォッチをしているときに、自分の投稿に対するものか他人の投稿に対するものかがわからないことについては、通知領域にタブを表示し「すべての通知を表示するタブ」「自分の投稿に対する通知を表示するタブ」「他人の投稿に対する通知を表示するタブ」を作ることで解決できる気がしてきた

**Comment by marihachi** [comment]
引用RNの通知を受け取るかどうかを切り替える機能が欲しくなった
通知をカスタマイズする機能が実装されることによって、これは解決されそうなので期待してる..

**Comment by syuilo** [comment]
実装された
