### ISSUE TITLE
ダークモードでリストのタイトルが黒色

### ISSUE THREAD

**Issue by nzws** [misskey-dev/misskey#1997]
# Summary
![image](https://user-images.githubusercontent.com/14953122/43264221-6897fca8-9120-11e8-9f4c-a664a3b5cab1.png)

# Expected Behavior
背景色に合わせて文字色を白色にする必要がある

# Actual Behavior
文字色が黒い

# Environment
desktop, dark mode

**Comment by syuilo** [comment]
注意: そのリストページはまもなく廃止される予定
