### ISSUE TITLE
Deckのタイムラインカラムを選択し、キーボードで操作できるようにする機能

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2005]
# Summary
数字キー(49-57, 48)でカラムを選択し、ホームタイムラインと同じキーボードショートカットを利用できるようにしてほしい

# Environment
deck

**Comment by syuilo** [comment]
* リアクションのショートカットと競合しそう
* 複雑なレイアウトだと各カラムに対応する数字を覚えるのは難しい(Misskeyは縦分割もできるため)
* 数字キーを使わなくても各カラムにフォーカスできるようになった

などの理由でこちらのIssueはCloseします。
