### ISSUE TITLE
アカウントの削除

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2017]
# Summary
ユーザーがユーザー自身でアカウントを削除できない

# Expected Behavior
ユーザーが自分自身でアカウントを削除できる  
アカウントが削除された際にリモートに対しても適切な処理をする(投稿の削除とアカウントのサスペンド)

# Actual Behavior
ユーザーが自分自身でアカウントを削除できない

# Steps to Reproduce
1. 設定ウィンドウなどからアカウントを削除する項目を探す
2. 見つからない
3. できない

# Environment
any

**Comment by syuilo** [comment]
フェデレーションはまだだった

**Comment by mei23** [comment]
#5165 でフェデレーションには削除を送るようになった
受信はまだ

**Comment by mei23** [comment]
元Issueにある要件は実装済み。

リモートから来た場合の削除はまだだけど
以下で管理することにしてこれはクローズでいいかなと。
https://github.com/misskey-dev/misskey/issues/5457
