### ISSUE TITLE
アプリの情報を更新できない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2022]
# Summary
アプリの情報を更新できない

# Expected Behavior
アプリ作成時の説明によれば、アプリの権限情報などは後程更新できると言っている

# Actual Behavior
アプリの情報を更新するような機能はどこにもない

# Steps to Reproduce
1. misskeyをプログラムから操作したいと思う
2. /devでアプリを作成する
3. アプリ作成時に登録した情報を変更したいと思う
4. 変更できない

# Environment
practically accessed from desktop

**Comment by KisaragiEffective** [comment]
triage: same as #1971
