### ISSUE TITLE
APIでの通信のみでアプリを作成できるようにしてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2025]
# Summary
MastodonではTwitterやMisskeyとは違い、APIの通信だけでアプリを作成できる機能がある(/api/v1/appsに{client_name(名前), redirect_uris(リダイレクトURL), scopes(権限)}をPOSTすると{client_id, client_secret}(MisskeyでいうところのAppSecret)が帰ってくる)  
インスタンスごとに/devにアクセス→アプリを作成の手順を踏む必要があるのはそのアプリが利用できるインスタンスを制限するということになるため、Misskeyもそのような/devを介さずにアプリを作成する機能を備えたほうがよさそう

# Environment

**Comment by tosuke** [comment]
https://misskey.xyz/docs/ja/api/endpoints/app/create

**Comment by tosuke** [comment]
app/createを認証不要で叩けるようになれば改善しそう
