### ISSUE TITLE
docs/translate.*.md に %i18n:foo% 形式の説明を追加

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#2027]
docs/translate.*.md に `%i18n:foo%` のように `i18n:` のあとに `@`がつかない形式の文字列についての記載がほしい

https://github.com/syuilo/misskey/pull/2024 みたいなPRが飛んでくるので

**Comment by syuilo** [comment]
リファクタリングされ、その独自構文が廃止されましたのでCloseします
