### ISSUE TITLE
Can't open messaging history/Inconsistent messaging history

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#2031]
# Summary
Messaging history is extremely fiddly. You need to open the messages tab, search the person you wish to read messages from and then read the messages, rather than just look at messaging history

# Expected Behavior
Messaging history should show up no matter if you just opened the website or not.

# Actual Behavior
Messaging history doesn't appear until you search the usernames of previous people you messaged and open them.

# Steps to Reproduce
1. Use latest branch
2. Open messaging history
3. If none, lookup username of person you've messaged, and then open the messaging history again.

# Environment
Messaging tab
Desktop, Firefox 58, Windows 10 x64

**Comment by syuilo** [comment]
[This commit](https://github.com/syuilo/misskey/commit/bffd7bbb3b4f952fd29ffee0c414a1c3c3202860) may fix this issue.

**Comment by ghost** [comment]
Fixed.
