### ISSUE TITLE
Edit post button

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#2040]
# Summary
Currently there is no way to edit a post. It would be really great to have an edit post button. Especially if you can't write (like me lol)

**Comment by AyaMorisawa** [comment]
We should consider following pseudo-edit button.

* Delete the post, and then open post-form with the deleted text.

FYI: https://misskey.xyz/notes/5be3c8754dc9770047d249c5

**Comment by tamaina** [comment]
NyaizeやMFMがあり、再投稿の際に単純に「コピー→削除→変だった部分を編集→投稿」という手順を踏めないのがつらいので、編集(というより再投稿？)機能はとても有用だと思う

**Comment by marihachi** [comment]
再投稿機能を実装するとすれば、アプリケーションレベルで
ノート削除→ノート投稿
のAPI呼び出しを組み合わせるとかになりそう。
でも、この場合はレートリミットに引っかかると消すだけ消して再投稿できない場合もある。
この点が問題になるようであれば、APIレベルで特別に実装しないといけないね。(けどそれはそれで投稿と再投稿合わせてレートリミットが実質2倍になったりしたりして？)

**Comment by tamaina** [comment]
再投稿できなくするのがレートリミットなので問題ではなさそう。

できるだけクライアント側だけで対処するのが簡単で良いと思います。(サーバー側の処理として投稿の生データを取得できるようにするのは必要だけど)

**Comment by tamaina** [comment]
そもそも、投稿がレートリミットで送れなくてさらにその投稿が消失したら悲しいと思う。再投稿でなかったとしても。

**Comment by marihachi** [comment]
これCloseでいいと思う
