### ISSUE TITLE
Deckのリストカラムの更新が行われない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2042]
# Summary
リストタイムラインの更新が行われない

# Expected Behavior
リストに登録したアカウントの最新の投稿が流れてくる

# Actual Behavior
リストを読み込んだ時点以降は流れてこない

# Steps to Reproduce
Deckでリストカラムを追加したり、ホームでリストタイムラインを開いたりする

# Environment
Operating System: Windows 10 Build 17723.rs5_release.180720-1452
Browser: Firefox 62.0b13, Chrome 67.0.3396.99（Official Build） （64 ビット）

**Comment by syuilo** [comment]
これと関係してそうな気もする
https://github.com/syuilo/misskey/issues/1808

**Comment by tamaina** [comment]
最初勘違いで適当なこと書いてた ごめんなさい

**Comment by tamaina** [comment]
最初に書いた事象とは別の事象かもしれない

**Comment by syuilo** [comment]
Thank you for your reporting @tamaina
