### ISSUE TITLE
本文を見ることができない投稿は非表示に

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2046]
# Summary
削除された投稿が表示されたところで大半のユーザーにとって邪魔なだけの存在になると思われるため`(この投稿は削除されました)`ではなく存在ごと消してほしい

# Environment
any

**Comment by syuilo** [comment]
存在ごと消すのはほぼ無理ですね

**Comment by syuilo** [comment]
これなら可能 https://github.com/syuilo/misskey/issues/1740

**Comment by syuilo** [comment]
削除された投稿を表示しないようにすることなら可能

**Comment by tamaina** [comment]
非表示って言う表現いいですね

**Comment by syuilo** [comment]
より具体的に言うと、削除された投稿をタイムラインに含めないようにしたり、アクセスできないようにしたり、削除された投稿に返信したりリアクションしたり出来ないようにすることは十分可能だと思われるので、ほぼ「存在ごと消えた」ような状態にすることができる

**Comment by tamaina** [comment]
自分が見ることができない投稿も同じようにしてほしい

**Comment by syuilo** [comment]
https://github.com/syuilo/misskey/issues/1562 ？

**Comment by syuilo** [comment]
Done
