### ISSUE TITLE
文字数の多い投稿でも画面を占領しないようにする

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#206]
400文字(追記: ←???)を超える投稿の場合フォントサイズを小さくしたり、省略したりなどする

**Comment by AyaMorisawa** [comment]
現状CW機能でどうにかなってる気がする

**Comment by mei23** [comment]
- 文字種によって half/full width があるので どのくらい幅を取るかの計算は難しい
- MFM等で拡大されている場合の計算も難しい
- 文字数が少なくても単純に改行が多い場合は専有してしまう

ので、単純に縦サイズ基準の方がいいと思う

**Comment by syuilo** [comment]
やった
