### ISSUE TITLE
Can't upload png images from mobile

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#2064]
# Summary
Uploading a png image from mobile results in a color-scaled image instead of the image actually uploading.

# Expected Behavior
Images should look as intended when uploaded, no matter the format

# Actual Behavior
Images get color scaled.

# Steps to Reproduce
1. Use Android browser
2. Upload image
3. Look at image

# Environment
Android 5.0.1 jellybean, chrome, brave and firefox.

**Comment by syuilo** [comment]
I can not reproduce the issue... 🤔

**Comment by ghost** [comment]
I haven't successfully reproduced the issue either. I've seen it happen a few times to my userbase but from what I know it's old OS with old browser.

**Comment by ghost** [comment]
Old OS, Android 5.0.1 jellybean
