### ISSUE TITLE
Remove gulp-util dependency, which is deprecated

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#2072]
# Summary
The software still uses gulp-util dependency, which is deprecated. 

Currently there is no way to update the dependency, as it is currently blocked by [gifsicle-bin](https://github.com/imagemin/gifsicle-bin), which itself hasn't yet been updated to reflect the changes. Until then, the library will stay.

When, however, the gifsicle library is updated to reflect the change, build should pass and updating to gulp 4.0.0 as well as removing gulp-util dependency should be possible.

More information: https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by syuilo** [comment]
Thanks reporting 🙏

**Comment by Johann150** [comment]
Fixed in d18291cf0c70757147d5307cdbc8bd70b1e4bbe2.
