### ISSUE TITLE
オセロに勝てない

### ISSUE THREAD

**Issue by 2vg** [misskey-dev/misskey#2075]
# Summary

頑張ってもオセロに勝てません
どうしたら勝てるようになりますか？
# Expected Behavior

真ん中に置くようにしたら勝てるらしい
# Actual Behavior

真ん中に置くようにしたのに負けた
# Steps to Reproduce
1. 真ん中に置くようにする
2. 負けそうになる
3. 負ける

# Environment

Windows 10, GoogleChromeにて確認

**Comment by AyaMorisawa** [comment]
I can not reproduce the issue... 🤔

**Comment by syuilo** [comment]
Closed as this is not a problem with Misskey.

**Comment by SanMurakami** [comment]
適当にやってたら勝てるよ
