### ISSUE TITLE
Enhance preference settings on the client

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#2092]
# Summary

The proposal for adding more options in the client.

For example:

* Automated note muting by regular expression.
* Automated NSFW when the author's name contains ":underage:".
* Automated CW when the actual height of the note is taller than the specified limit.

# Environment

the client (desktop/mobile)

**Comment by ghost** [comment]
Regexp filter would be actually pretty good. There's no fun in seeing the same threads bydaily.

I'd weigh in customization filters based on user name and other options. 

I don't see why adding these directly in the client would be any significant improvement.

A-la 4chan style, in short.

**Comment by LemmaEOF** [comment]
I think having a regex-based muted keyphrase system is a really good idea, but I don't really see why it should be in the client. Keeping it stored serverside means that you don't have to remake the whole list every time your browser forgets its cache or you sign in somewhere new.

**Comment by syuilo** [comment]
Perhaps this filtering will implemented on the client side, but since the settings are stored on the server, no information is lost if you delete the browser's cache.

**Comment by syuilo** [comment]
See: https://github.com/syuilo/misskey/issues/2687
