### ISSUE TITLE
:emoji:のサポート

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#21]

**Comment by AyaMorisawa** [comment]
Done by @otofune.

**Comment by syuilo** [comment]
ファイルサイズが大きくなりすぎるという問題が新たに見つかったためreopen

**Comment by otofune** [comment]
`api:rss`系と同じようにAPIを叩いていこうな :+1: ってやればよさそう、俺がやりますのでアサインしといてください

**Comment by syuilo** [comment]
それもリクエストがそれなりに発生しそうできつそう

**Comment by otofune** [comment]
確かに
辞書を小さくする (gemojiは無駄が多い、というかガッチリ情報がはいってるので最低限に) スクリプトとか書いてnpmパッケージを作れば神になるかもしれないしそういう方面も模索していく
