### ISSUE TITLE
メッセージを厳重に暗号化する機能

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2102]
# Summary
Signalほどではなくても安全にチャットできるようにしてほしい  
メッセージに暗号化がついていればダイレクトとメッセージとを差別化することができる

# Environment

**Comment by syuilo** [comment]
復号の鍵はどうするんだろう

**Comment by tamaina** [comment]
要らなくない？

**Comment by syuilo** [comment]
要望は多々あるから要らないことはなさそう

**Comment by syuilo** [comment]
でも不可能な気がする

**Comment by tamaina** [comment]
グループの連合のほうを先にやってほしく思う 
開発コスト的にMisskey標準で提供する必要はない気がしてる

**Comment by rinsuki** [comment]
鍵のやり取りが問題になるしMisskeyでこれやるよりかは Keybase連携 #4694 のほうがよさそう

**Comment by syuilo** [comment]
> でも不可能な気がする

こういうのがあるらしい
https://ja.m.wikipedia.org/wiki/%E3%82%A8%E3%83%B3%E3%83%89%E3%83%84%E3%83%BC%E3%82%A8%E3%83%B3%E3%83%89%E6%9A%97%E5%8F%B7%E5%8C%96
から不可能ではないのかも

**Comment by rinsuki** [comment]
不可能ではないけど現実的ではないというか。

1. 鍵のやりとりについて、公開鍵を渡すというと簡単に聞こえるがその公開鍵が本物かどうかはどうやって検証するのか。複数インスタンス上で交換すれば検証できそうだけど1インスタンスだけで検証するのは完璧とは言えなさそう
1. どこで暗号化/複合化するのか。クライアントでやると鍵保管が問題になるし、サーバーでやってもそれ意味ある…? みたいになってしまう (ドメイン失効したサーバーに悪意のある人間がロガー置いて収集するシチュを防ぐ効果しかなさそう、生きてるサーバーに連合から来るメッセージが読めるならAPIのレスポンスも見れるわけで)

**Comment by syuilo** [comment]
Mastodonではこの機能が検討されているっぽい。
↑の1と2の問題をどうやって解決するか気になる

**Comment by tamaina** [comment]
セキュアに会話したいなら、自分たちで管理しているインスタンス内もしくはインスタンス間で通信すればいい  
(VPNを使うとさらに安全そう)
