### ISSUE TITLE
クライアントのモバイル版/デスクトップ版の判断は画面幅を根拠にしてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2106]
# Summary
デスクトップでも狭い画面幅で使いたいときもあるが、現状のデスクトップ版では狭い画面幅では使い物にならない
結果はあまり変わらなそうなのでモバイルとデスクトップの判断は画面幅を根拠にしてもいいと思う  

# Environment
any

**Comment by syuilo** [comment]
ユーザーエージェントで判定するのはそのままで、それに加えあまりにも画面幅が狭い場合はユーザーエージェントがデスクトップでもモバイルにするのが良さそう
