### ISSUE TITLE
アイコンが丸にならないページがある

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#2117]
# Summary

![1aaf05d1-8670-4fe0-b09d-b0e394163733](https://user-images.githubusercontent.com/20679825/43759531-78897f2c-9a5a-11e8-854a-80f72b15a500.png)

# Expected Behavior

丸と角丸どちらでも表示可能

# Actual Behavior

常に角丸

# Steps to Reproduce

1. モバイルで
2. ユーザーページを
3. 開きます

# Environment

mobile

**Comment by tamaina** [comment]
mk-user-previewもですね  
Catの猫耳機能が付いてから違和感がありまくりですね
