### ISSUE TITLE
ログインしてない状態で開けるページがある

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#2124]
ログインしていない状態でアクセスが可能で、リダイレクトが発生しない。

* [ ] /deck
* [ ] /reversi
* [ ] /i/favorites
* [ ] /i/drive

**Comment by tamaina** [comment]
devも同様の処置を施した方がよさそう

**Comment by tamaina** [comment]
モバイルだともう少し増えそう

**Comment by xps2** [comment]
#1633

**Comment by SanMurakami** [comment]
もうこれ良いでしょ
