### ISSUE TITLE
NSFWを投稿フォームで付けられるようにしてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2145]
# Summary
特に投稿フォームにドロップして画像を添付した際、ドライブを開くのが手間なので、画像に対するNSFWを投稿フォームでも付けられるようにしてほしい

# Environment
any

**Comment by AyaMorisawa** [comment]
ref: https://misskey.xyz/notes/5c3740a1b46e6200334404ea
