### ISSUE TITLE
ユーザーページを開くと正常にページが表示されないことがある

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#2153]
# Summary

新しいタブでユーザーページを開く際等において現象を確認済み、原因は不明。

# Expected Behavior

ユーザーページが完全に表示される

# Actual Behavior

ユーザーページがユーザーアイコン等以外レンダリングされない

# Steps to Reproduce

不明

# Environment

browser

**Comment by futchitwo** [comment]
恐らく旧フロントエンドの問題なので閉じて問題ないと思います
