### ISSUE TITLE
管理画面からバージョンアップ

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#2168]

**Comment by syuilo** [comment]
不可能そう
Misskeyプロセスが複数のサーバーに分散されて運用されている場合があり、１つのプロセス(サーバー)をアップデートしたとしても他のサーバーに関しては知る由がないため他のサーバーはアップデートできません
複数のサーバーの中でバージョンがお互いに違うと何らかの不整合を引き起こす可能性がありそう
