### ISSUE TITLE
MastodonからDMを送るとフォロワー宛てで届く

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#2171]
# Summary
MastodonからDMを送るとフォロワー宛てで届く

# Expected Behavior
非公開で届く

# Actual Behavior
フォロワー宛てで届く

# Steps to Reproduce
1. MastodonからMisskeyユーザーにDM(ダイレクトでメンション付き)を送る

# Environment
v5.22.1

**Comment by syuilo** [comment]
Closed by 
https://github.com/syuilo/misskey/pull/2172
