### ISSUE TITLE
Streamlined moderation

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#2185]
# Summary
Currently the only "moderation" the program has is to suspend accounts by using SSH.

My suggestion is to make moderation streamlined for site moderators.

User posts should have a "report" button under them. A voting system is hence initiated under a page dedicated to moderation (misskey.xyz/reports). Every users begin with the voting power of 10; Users who frequently vote on things that do not pass or vote accurately lose their voting power or are banned from the system, while users who frequently vote right gain more.

If a post passes the 100 ratio, it's hidden and raised up to an actual site moderator, which will hencefort decide for which action is appropriate.

Verified users should be excluded from the system.

**Comment by Johann150** [comment]
Since we have a reporting functionality now I think this can be closed.
