### ISSUE TITLE
非adminが管理画面を開くとリダイレクトするように

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#2194]

**Comment by AyaMorisawa** [comment]
単純にリダイレクトするより、

* インスタンス管理者用にアカウントのadmin登録の方法を表示
* 一般ユーザー用にリダイレクトボタンを表示

みたいな感じにした方がよさそう？

**Comment by tamaina** [comment]
それはただのお馬鹿さんなのでは  
(そのケースを対策する必要はなさそう)

**Comment by syuilo** [comment]
実際にadminだけどadmin設定していないadminを見たことがある

**Comment by tamaina** [comment]
というか別にmark-adminについて書かない方がいいとは言ってない
あとその原因はセットアップガイド・運営ガイドのどちらにも管理画面について書かれていなかったからでは?

**Comment by Johann150** [comment]
Fixed by #8361.
