### ISSUE TITLE
リモートユーザーが自分にメンションしても通知されない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2223]
# Summary
@aqz@misskey.xyz が自分に対してのリプライだと認識されていないようで、通知が来ないため反応できない

# Expected Behavior
@aqz@misskey.xyz が含まれる投稿が通知される

# Actual Behavior
されない

# Steps to Reproduce
1. @aqz@misskey.xyzにフォローされたリモートアカウントで@aqz@misskey.xyzを含む投稿をする

# Environment
desktop, firefox latest

**Comment by syuilo** [comment]
プログラム上は全く問題ない(通知されるはず)ように見えるんだけど私も確認した
謎すぎる

**Comment by syuilo** [comment]
直った
