### ISSUE TITLE
鍵アカウントにしている時、フォロー承認時にそのユーザーをフォローするボタンがほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2230]
# Summary
鍵アカウントにする利点としてフォローバックしやすいというのがあるため

# Environment
desktop, mobile

**Comment by syuilo** [comment]
鍵アカウントに関わらず、フォローされたときに簡単にフォローバックできるようにフォロー通知にフォローバックボタンを追加するのが良さそう
