### ISSUE TITLE
リモートのNSFWが反映されない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2238]

**Comment by fuyutsuki** [comment]
@syuilo おっと失礼。やり直してみたら確かに再現できました、失礼しました。  
閲覧注意、となるはずの画像が表示されました。  
Pawoo:
![2](https://user-images.githubusercontent.com/16377174/44157337-2a2bb180-a0ed-11e8-88c7-aa8ff5e3a9ad.png)
misskey:
![default](https://user-images.githubusercontent.com/16377174/44157283-0e281000-a0ed-11e8-9930-deed2066926a.png)
