### ISSUE TITLE
YouTube等のURLの動画プレビューができなくなってる

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#2240]
# Summary
YouTube等のURLの動画再生ができなくなってる

# Expected Behavior
埋め込みプレイヤーが表示されて再生できる

# Actual Behavior
できない

# Steps to Reproduce
1. YouTubeのURLを貼る

# Environment
Windows 10, Firefox 61 / Chrome68

サーバー側からplayerで埋め込みURLが返ってくることを期待しているが
https://github.com/syuilo/misskey/blob/08b431723a3b6b48570dd65c43b1e23355b76e32/src/client/app/common/views/components/url-preview.vue#L163-L164
特にサーバー側は、YouTube等の埋め込みURLには対応してなさそう(player=null)

**Comment by acid-chicken** [comment]
実際にテストしてみたところ`twitter:player`はレスポンスに含まれているため、summalyのバグである可能性が高い。
```
➜ curl -LSs -w '\n' -- 'https://www.youtube.com/watch?v=jNQXAC9IVRw' | grep 'twitter:player'
      <meta name="twitter:player" content="https://www.youtube.com/embed/jNQXAC9IVRw">
      <meta name="twitter:player:width" content="480">
      <meta name="twitter:player:height" content="360">
```

**Comment by mei23** [comment]
ブラウザでそのURL踏むと`twitter:player`含まれてなさそうだわ

**Comment by acid-chicken** [comment]
原因が分かりましたので、summaly側にPRを投げてきます。
summalyでは`<meta property="twitter:player">`にマッチするcontentを採取していましたが、`<meta name="twitter:player">`も対象にするようにPRしました。

**Comment by mei23** [comment]
summaly更新してキャッシュ無効にしてもなおってなさそうだわ

**Comment by acid-chicken** [comment]
```
➜ curl -LSs -w '\n' -- 'https://www.youtube.com/watch?v=jNQXAC9IVRw' | grep 'twitter:player'      <meta name="twitter:player" content="https://www.youtube.com/embed/jNQXAC9IVRw">
      <meta name="twitter:player:width" content="480">
      <meta name="twitter:player:height" content="360">

➜ curl -LSs -w '\n' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0' -- 'https://www.youtube.com/watch?v=jNQXAC9IVRw' | grep 'twitter:player'

```
User-Agentが鍵になっていそう

**Comment by mei23** [comment]
summaly側でYouTubeはまだダメそうなのでIssuleだけたてたわ
https://github.com/syuilo/summaly/issues/124

**Comment by acid-chicken** [comment]
<https://github.com/syuilo/summaly/pull/124> を解決するPRを立てました <https://github.com/syuilo/summaly/pull/125>

**Comment by syuilo** [comment]
解決済み
