### ISSUE TITLE
通信制限モードの時にアイコン非設定のアカウントのアイコンが表示されない

### ISSUE THREAD

**Issue by trasta298** [misskey-dev/misskey#2257]
こんな感じに表示が崩れる
![screenshot_20180815-194850_chrome](https://user-images.githubusercontent.com/13024718/44181048-7f41e480-a13a-11e8-96e8-83e528949d3b.jpg)

**Comment by SanMurakami** [comment]
通信制限モードが消えたのでcloseで良さそう

**Comment by syuilo** [comment]
通信制限モードが消えたのはバグですね

**Comment by syuilo** [comment]
v12で通信制限モード廃止しようかな

**Comment by syuilo** [comment]
廃止しました
