### ISSUE TITLE
(API)クライアント登録時に指定するIDについて

### ISSUE THREAD

**Issue by tateisu** [misskey-dev/misskey#2273]
Misskeyのクライアント登録API app/create を呼び出す際、それまでタンスに登録されていないアプリIDを指定する必要があります。
一方で、アプリサーバを持たないアプリからタンスにクライアント登録を行う場合、アプリはインストールされた端末ごとにクライアントを登録することになります。

より正しい設計は、タンス側でIDを自動採番することです。そうでなければ、アプリ側は衝突がなくなるまでランダムなIDを生成してリトライしようとするでしょう。

そして、どちらにしてもNoteに含まれるapp IDはhuman readableな文字列ではなくなります。
NoteにはApplicationオブジェクト(ID、名前、アプリのWebサイトURLなどの属性)を持たせるべきです。

**Comment by syuilo** [comment]
ありがとうございます！
nameIdは廃止しようと思います。

**Comment by tateisu** [comment]
ログインなしで https://misskey.xyz/api/app/create に同じパラメータを指定して複数回呼び出すと
idとcreatedAtが異なるレスポンスが返ってきました。
開発者ツールでは重複禁止なように見えたが、実際にはnameIdは重複OKのようです。
よって複数の端末から個別にアプリ登録が行われた場合にも問題は発生しないのでした。
