### ISSUE TITLE
(API)外部タンスの情報を取得してローカルなIDを採番するAPI

### ISSUE THREAD

**Issue by tateisu** [misskey-dev/misskey#2274]
マルチインスタンス対応のアプリでは、あるタンスのユーザやノートを別のタンスから参照したくなることがあります。

- (ユーザに対して)別アカウントからフォロー
- (ユーザに対して)別アカウントからメッセージを送る
- (ノートに対して)別アカウントからリノート
- (ノートに対して)別アカウントから返信 (reply id)
- (ノートに対して)別アカウントからリアクション
- (ノートに対して)別アカウントからお気に入り

アクションを起こすクライアントが必要とするのは自タンス上のIDです。
タンスがリモートにあるユーザやノートの情報を取得して採番したIDを取得できないと、クライアントはそれらのアクションを行えません。

例えばマストドンでは以下のようなacctやURL

- @user@instance 
- http://instance/@user 
- https://mastodon.juggler.jp/@tateisu/100561488805176273 

を検索APIに渡すと、WebFingerなどを利用してユーザやトゥートを認識してローカルに取り込んでIDを採番して ユーザやトゥートのjsonレンダリング結果を返します。
( https://gist.github.com/okapies/60d62d0df0163bbfb4ab09c1766558e8 )
(既にローカルにある情報の場合はDBから検索するだけですませるようです)

(A)
汎用の検索APIに含める必要は特にないと思うのですが、
何らかの形(たとえば remote lookup APIなど？)で外部タンスのWebFingerから情報を引っ張ってこれるAPIがあれば、Misskeyのユーザはインスタンスの垣根を越えてアクションを行えるようになります。

(B)
また、Misskeyのユーザやノートについても WebFinger から情報を公開すれば、マストドンのユーザはMisskeyのユーザやノートに対して色々なアクションを行えるようになるはずです。

**Comment by tateisu** [comment]
リモートユーザに関しては https://misskey.xyz/api/users/show に username と host を渡せば 自タンスでのIDを採番してくれる模様。
Noteに関しても似たようなことが出来れば良いのだけど…

**Comment by mei23** [comment]
今のままNote URIを指定してローカルIDを採番するAPIを実装した場合
取得したNoteがDBのObjectID(到着日時基準)で採番される
→Web UIなどタイムラインをObjectIDでソートしていると、対象のものが全て直近の投稿扱いで出てきてしまいそう。（というかそうなった）

Web UIなどのタイムラインソート方法を先になおしたほうが良さそう
タイムラインをDate(作成日時基準)でソートする #2275 に関連
SnowflakeIDを実装して使用する #2497 に関連
