### ISSUE TITLE
管理画面のダッシュボードの統計をリアルタイムで更新

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#2316]
https://msky.cafe/notes/5b77a171a698a4002bc4b2cb

**Comment by AyaMorisawa** [comment]
統計流すためのstreamが要りそう

**Comment by acid-chicken** [comment]
リアルタイムで流れてそう？

**Comment by syuilo** [comment]
ポーリングなのでリアルタイムではないですが実用上はこれで問題なさそうですね
統計情報をリアルタイムで流すのはかなり負荷が高そうな気がしますし
