### ISSUE TITLE
ホワイトリスト連合

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#2318]
# Summary

# Environment

**Comment by 4ioskd** [comment]
管理者がActivityPubをオフにしたい場合、それは脱（非）中央集権型ネットワークを構築するmisskeyとは異なる考えに基づいたものですから、ActivityPubをオフにしたい管理者が自身の判断でコードをいじってオフにすればよいのではないかと思います。misskeyがこのオプションを設定する責務は無いように思えます。

追記：似たようなissue等をマストドンやPleromaで探しましたが、ActivityPubをオフにできるオプションに関する内容は見つかりませんでした。これが意味するところは、結局は管理者それぞれが判断して行えば良い、ということではないでしょうか。

**Comment by tamaina** [comment]
> それは脱（非）中央集権型ネットワークを構築するmisskeyとは…

いつからそう思っていた？…うんまあでも説明にガッツリそう書いてあったわ  
（私的にはクローズドな環境で使えてもよくない？と思っています）

ちなみにdefault.ymlでproxyに存在しないエンドポイントを指定すると配信やフォローができなくなる（配信できなくなるだけなので、ノートやユーザーを取得したりRenoteしたりはできそう）  
https://scrapbox.io/cookie-ramen/Misskey%E3%81%A7%E3%82%BD%E3%83%BC%E3%82%B9%E3%82%92%E5%A4%89%E6%9B%B4%E3%81%9B%E3%81%9A%E3%81%AB%E9%80%A3%E5%90%88%E3%82%92%E5%AE%8C%E5%85%A8%E7%84%A1%E5%8A%B9%E5%8C%96%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95

**Comment by yitsushi** [comment]
> 管理者がActivityPubをオフにしたい場合、それは脱（非）中央集権型ネットワークを構築するmisskeyとは異なる考えに基づいたものですから、ActivityPubをオフにしたい管理者が自身の判断でコードをいじってオフにすればよいのではないかと思います。misskeyがこのオプションを設定する責務は無いように思えます。
> 
> 追記：似たようなissue等をマストドンやPleromaで探しましたが、ActivityPubをオフにできるオプションに関する内容は見つかりませんでした。これが意味するところは、結局は管理者それぞれが判断して行えば良い、ということではないでしょうか。

Partially related (not disable only limit), Mastodon has a  "Limited Federation Mode". Mastodon will restrict federation to servers you have manually approved only, as well as disable all public pages and some REST APIs.

> This mode is intended for private use only, such as in academic instituations or internal company networks, as it effectively creates a data silo, which is contrary to Mastodon's mission of decentralization.

https://docs.joinmastodon.org/admin/config/#basic

**Comment by noellabo** [comment]
MastodonにはLIMITED_FEDERATION_MODEがあり、まったく連合しないとか、連合する相手をホワイトリスト指定するようにできますので、機能的には同等のものが提供されていると考えてよろしいかと思います。

学内ネットワークでの利用や、EUNOMIAなどの実験的プロジェクトでクローズド運用するなどの事例があります。

**Comment by noellabo** [comment]
あ、被ったw

**Comment by syuilo** [comment]
私もActivityPubを完全にオフにする機能を実装するというよりはホワイトリスト連合機能実装する感じで良いかなと思ってた
ホワイトリストにした上で何も指定しなければ実質的にActivityPubオフと同義にもなる

**Comment by KisaragiEffective** [comment]
https://m.tkngh.jp/notes/9vkf6ct1va890svj

**Comment by syuilo** [comment]
やるか
