### ISSUE TITLE
デッキ表示のカラム並べ替え時の挙動

### ISSUE THREAD

**Issue by ShinoharaTa** [misskey-dev/misskey#2322]
いまデッキ表示でカラムが以下のように並んでいるものを入れ替えるとき

COL-1，COL-2，COL-3，COL-4，COL-5

１を４の位置に変更しようとすると
**COL-4**，COL-2，COL-3，**COL-1**，COL-5となってしまう。（入れ替わる）

コレを
COL-2，COL-3，COL-1，COL-4，COL-5 とInsertしてほしい

**Comment by tamaina** [comment]
GitHubのバグによりRecloseします
