### ISSUE TITLE
ドライブで削除した画像が, フォトストリームでは表示されている

### ISSUE THREAD

**Issue by akawshi** [misskey-dev/misskey#2334]
タイトルどおり。ドライブで削除した画像が, ウィジェットのフォトストリームではずっと表示され続けている。PC

**Comment by syuilo** [comment]
ありがとうございます！
キャッシュが残っているのかもしれません

**Comment by tosuke** [comment]
閉じてもよさそう

**Comment by syuilo** [comment]
今確認したら削除されたファイルも返却するようになってたので修正
(もちろんキャッシュが残ってたのも原因のひとつだと思われる)
