### ISSUE TITLE
"Network error" on running Misskey on MongoDB 3.6.2

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#2337]
# Summary
Sign up impossible due to "Network error".

I don't know if it's a set up error or otherwise. 

# Expected Behavior
Sign up doable

# Actual Behavior
Can't sign up

# Steps to Reproduce
1. Install mongodb 3.6.2
2. Set up and start misskey
3. Profit

# Environment
Funtoo current

**Comment by syuilo** [comment]
I cannot reproduce this issue. What is your Misskey version?

**Comment by ghost** [comment]
Latest. I had never had the issue before so I'm wondering if it's an OS issue or well, software issue.

Seems like it's an OS issue.

**Comment by ghost** [comment]
Could it be linked to invalid SSL or no recaptcha?

**Comment by syuilo** [comment]
Yeah, To disable recaptcha, you need to comment out the recaptcha section in your configuration.

**Comment by syuilo** [comment]
And then you need to rebuild misskey

**Comment by ghost** [comment]
mmmmh odd.

I'll rebuild, but I did comment out recaptcha.
