### ISSUE TITLE
ビルドに設定ファイルを不要にする

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#2338]
# Summary

# Environment

**Comment by syuilo** [comment]
gulpではまだ必要だけどwebpackの方は不要になった

**Comment by xps2** [comment]
RepositoryとFeedbackのリンク、webpackで置き換えてたので効かなくなってる…

**Comment by syuilo** [comment]
やった
バグは後程修正

**Comment by xps2** [comment]
fa7c8cfe5bdf251b679ed6e87777cdd2ec7f600d
