### ISSUE TITLE
/dev/app/newで作成したアプリではミュート関連の操作はできない？

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2341]
# Summary
ソースを確認しただけで実装して確かめてみたわけではないが、エンドポイントの`kind`の値が、標準的なアカウント操作関連は`account-read``account-write`なのに対しミュート関連は`account/read``account/write`となっている。  
置換するコードは見つけられなかったが、仮にもしないとすれば[/dev/app/new](https://github.com/syuilo/misskey/blob/master/src/client/app/dev/views/new-app.vue)から作成したアプリはミュート関連の操作ができない(`account/read``account/write`のpermissionは付与されないため)。

これは仕様ですか？

# Environment

**Comment by syuilo** [comment]
ありがとうございます！ミスっぽいです

**Comment by tateisu** [comment]
'favorite-write' もないっぽいです

**Comment by tateisu** [comment]
パーミッション関連で問題を見つけた感じなので貼っておきます
https://misskey.xyz/notes/5b7aab7a403cad001f2bf161
https://misskey.xyz/notes/5b7aad63403cad001f2bf1e3

- 既知のパーミッションの一覧をどこかに定義しておくべきです。
- APIのコードで指定したパーミッションの文字列が既知のものかどうか、可能ならビルド時に分かるように工夫するべきです。でないとタイプミスを防止できません。
- アプリ登録時に未知のパーミッションを許可しないようにするべきです。でないと後から新しいパーミッションを作る時に、アプリがこっそり指定していた文字列と競合する可能性が出てきます。

**Comment by tateisu** [comment]
https://github.com/syuilo/misskey/blob/master/src/server/api/endpoints/following/requests/list.ts 
また新種のパーミッションを発見しました。
'following-read' となってますが、まず フォロリク申請を見れるのに適切な権限は 'following-write' であるべきだと思いますがどうでしょうか。

**Comment by tateisu** [comment]
```
kind: 'messaging-read'
kind: 'messaging-write',
kind: 'vote-write'
```

**Comment by tateisu** [comment]
お気に入り一覧の取得は favorites-read でした。 sの有無…

**Comment by tamaina** [comment]
v11で直そう

**Comment by tamaina** [comment]
> 'following-read' となってますが、まず フォロリク申請を見れるのに適切な権限は 'following-write' であるべきだと思いますがどうでしょうか。

そうでもなくない？

**Comment by tateisu** [comment]
フォローグラフはAPで公開されている情報なので認証なしでも読めますが、申請中のフォローリクエストはそうではありません。よりプライベートな情報です。

**Comment by tamaina** [comment]
フォロー申請がプライベートなものであることは同意しますが、かといってフォロー申請を**見る**ことに対するパーミッションを`following-write`にするのは分類としておかしいと思います。

フォロー申請の閲覧を`followrequest-read`、フォロー申請の承認/拒否操作を`followrequest-write`として分類しなおすべきだと思います。
