### ISSUE TITLE
(API) /api/app/create のレスポンスに appSecret が含まれない

### ISSUE THREAD

**Issue by tateisu** [misskey-dev/misskey#2343]
ログインなしで https://misskey.xyz/api/app/create を呼び出すとレスポンスに appSecret が含まれない問題。
認証セッションを開始できません

![image](https://user-images.githubusercontent.com/333944/44304753-e7ddcb00-a39f-11e8-85ba-6efe63d88485.png)

**Comment by tateisu** [comment]
https://github.com/syuilo/misskey/blob/master/src/server/api/endpoints/app/create.ts#L52
https://github.com/syuilo/misskey/blob/master/src/models/app.ts#L38

packを呼び出すときにオプションを指定していないのでsecretが除去されてる気がします
showの時にsecretを隠すのは妥当だと思いますが、createの時だけは除去したらマズい気が。

**Comment by tateisu** [comment]
https://github.com/syuilo/misskey/blob/master/src/server/api/endpoints/app/show.ts#L34 
https://github.com/syuilo/misskey/blob/master/src/server/api/endpoints/app/show.ts#L34

/api/app/show は
 「const isSecure = user != null && app == null;」と「ap.userId.equals(user._id)」がtrueの場合だけsecretをレンダリングするようになっていて
「アプリ作成は自動化できるけどsecretを見る条件は「ログイン済みユーザが作成したアプリかつログイン済みユーザがアプリを使わずに/api/app/show を呼び出した場合」に限られているようです。

現状ではクライアントから自動的にアプリ登録するのは困難だと思います。

**Comment by tateisu** [comment]
アプリサーバを用意して開発者のアクセストークンを保持する
・アプリはタンスのappSecretをアプリサーバに問い合わせる
・アプリサーバは開発者のアクセストークンを使って app/creaate とapp/show を行いappSecretを得る
・アプリサーバはappSeretをアプリに返す

…もうこんな方法しか思いつかないけど、これアプリサーバが攻撃されたら結局フリーダムにアプリを登録できるやつだからセキュリティが向上してるとは言い難いのではないか。アプリ内部にパスワードや秘密鍵を埋め込んでもせいぜい難読化しかできないのだから、第三者がアプリ内部の情報を使ってアプリサーバにアクセスすることは割と簡単にできる。

なお同様にappSecretをアプリ内に埋め込んだ場合もOSSではデバッガで変数を見たりrooted端末でオレオレ中間証明書を使い通信傍受するだけで読まれてしまう

**Comment by syuilo** [comment]
アプリ作成時にsecretを含めるようにしてみました

**Comment by tateisu** [comment]
ありがとうございます！

**Comment by tateisu** [comment]
試してみてsecretを得られるようになったのを確認しました。ありがとうございました
