### ISSUE TITLE
タイムラインの表示切り替えを何回もするとWebSocketのコネクションがその分だけ増える

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/misskey#2344]
# Summary
Misskeyを開いている1つのページから、タイムラインの表示切り替えを何回もすると
WebSocketのコネクションが**切断されることもなく**その分だけ増え続けます。
開発者ツールにてコネクションが増え続けることを確認できました。
メモリリークと関係がありそうです。

# Expected Behavior
最初に接続されたコネクションが再利用されることが望ましい。

# Actual Behavior
無限にコネクションが増える。

# Steps to Reproduce
1.ブラウザでMisskeyのトップページを表示(ホームTLを表示中)
2.少し待って、ローカルTLのタブをクリック
3.少し待って、ソーシャルTLのタブをクリック
4.少し待って、グローバルTLのタブをクリック
5. 2.から繰り返し

# Environment
Chrome 68.0.3440.106（Official Build） （64 ビット）
Windows 7 Home 64bit

**Comment by marihachi** [comment]
ここ怪しい
https://github.com/syuilo/misskey/blob/987799e9dbb2a5f708a7352ed79cada4d6814f28/src/client/app/common/scripts/streaming/global-timeline.ts#L29

**Comment by syuilo** [comment]
Good catch!
もしかしたらこの問題と関係あるかもしれない 
https://github.com/syuilo/misskey/issues/1808

**Comment by marihachi** [comment]
:heart:
