### ISSUE TITLE
リバーシで ai が固まる

### ISSUE THREAD

**Issue by elzup** [misskey-dev/misskey#2350]
# Summary 

下の状態のときに AI が次の手を打ってくれませんでした
時間的にはたぶん3分くらい放置しました

![misskey](https://user-images.githubusercontent.com/2284908/44308445-05875080-a3f1-11e8-86e1-ad00eb4b1ff7.png)

# Environment

> Google Chrome is up to date
Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by syuilo** [comment]
ありがとうございます！
藍はMisskeyの機能ではない(藍は https://github.com/syuilo/ai )のでこのIssueは閉じます。
もしかしたら通信が切断されたのかもしれません
