### ISSUE TITLE
(API) Is there "unrenote" API? 

### ISSUE THREAD

**Issue by tateisu** [misskey-dev/misskey#2353]
マストドンのunboost APIに相当するものを探しています。

- "note-write"権限が必要
- renoteされた元のnoteのIDを指定して
- 元のnoteに対して自分が行った引用なしrenoteを全て削除する

こんなAPIがあればrenote解除が容易だと思うのですが、相当するAPIはありませんでしょうか。

**Comment by syuilo** [comment]
対象のRenoteをnotes/deleteで削除すればRenote解除ということになる予定です。
現時点では、Renoteの解除というのは比較的複雑な処理のため実装できていません

**Comment by tateisu** [comment]
元のnoteのIDから自分が行ったrenoteのIDを知る方法はありますか？

**Comment by syuilo** [comment]
それはできないですね。データベース的にもその処理はきつそうです

**Comment by syuilo** [comment]
なのでRenote解除するとしても指定したRenoteだけで、自分の行ったある投稿に対するRenote全て解除、というのはできない予定です

**Comment by tamaina** [comment]
> 対象のRenoteをnotes/deleteで削除すればRenote解除

できるようになりました(https://github.com/syuilo/misskey/commit/a0f8c7e94ee2de826326a630c783d5c8c39825a7)

**Comment by tateisu** [comment]
欲しいのはrenoteされた元投稿のIDを指定して自分のrenoteを削除する機能なんですが、そのコミツトはコレじゃないと思います？

**Comment by tamaina** [comment]
そうです。提案されたAPIはこれじゃないです。  
しかし、そのRenote削除方法についても言及されているため進捗を追記しました。
