### ISSUE TITLE
ログイン時に二段階認証がわかりづらい

### ISSUE THREAD

**Issue by kazu0617** [misskey-dev/misskey#2355]
# Summary
タイトル通り。

![image](https://user-images.githubusercontent.com/6259214/44311035-33818a80-a41b-11e8-9886-6e1d00a1b57a.png)

![image](https://user-images.githubusercontent.com/6259214/44311043-4b590e80-a41b-11e8-89ec-6784f90580b0.png)

# Expected Behavior
ログイン時に二段階認証のウィンドウが出るが、それにタイトルが何も表示されない
携帯版だと完全に見えなくなる可能性も

# Actual Behavior
ログイン時の二段階認証ウィンドウに何かしらのタイトルを表示する

# Environment
Brouser: Google Chrome 68.0.3440.106 (モバイルはレスポンシブから確認)

[二段階認証],[2FA]か何か書いた方がよさげ？

**Comment by syuilo** [comment]
Resolved by https://github.com/syuilo/misskey/pull/3910
