### ISSUE TITLE
https://misskey.xyz/ is down

### ISSUE THREAD

**Issue by comradekingu** [misskey-dev/misskey#2361]
Error 502 Ray ID: 44d0362d2d3a4279 • 2018-08-19 22:56:07 UTC
Bad gateway

**Comment by syuilo** [comment]
Yeah, Misskey is under the DDoS attack.

Currently, the schedule for recovery is undecided.
We apologize for the inconvenience.

**Comment by syuilo** [comment]
Currently, the schedule for recovery is undecided.

**Comment by syuilo** [comment]
We apologize for the inconvenience.

**Comment by AyaMorisawa** [comment]
Fixed
