### ISSUE TITLE
アバターアイコン画像のデータサイズ

### ISSUE THREAD

**Issue by tateisu** [misskey-dev/misskey#2365]
UserエンティティのavatarUrlから渡されるアバターアイコン画像が重すぎる場合があります。

例
(6,047,537 バイト) https://s3.arkjp.net/misskey/drive/d46616f8-00ef-46c3-8099-105fe97418fc
(7,427,756 バイト) https://s3.arkjp.net/misskey/drive/1d4a4499-fd59-4dbb-b1fb-bd8ed4ef2cc2

**Comment by syuilo** [comment]
サムネイルを使うようにしてみます

**Comment by tateisu** [comment]
GIFなどはサムネイル画像が生成されないので重くなりうると思います。

アバターアイコン変更APIで、
- サムネイルのない
- 大きなデータ(20KB-50KBを超える)
は設定できないようにしてほしいです…
