### ISSUE TITLE
ホーム画面のナビゲーションの「開発者」のリンクが動作しない

### ISSUE THREAD

**Issue by qpwakaba** [misskey-dev/misskey#2367]
![image](https://user-images.githubusercontent.com/12168874/44335598-f7e4d000-a4af-11e8-9f40-5e9094c38fa8.png)
これの 開発者 の部分です。href属性が存在していないようです。

**Comment by acid-chicken** [comment]
おそらくconfigにおいて`url`を正しく設定できていません。
https://github.com/syuilo/misskey/blob/7bd33ecc72c7cbb53a15f3a74f7548564c75fa6b/src/config/types.ts#L23
https://github.com/syuilo/misskey/blob/7bd33ecc72c7cbb53a15f3a74f7548564c75fa6b/src/config/load.ts#L30-L33
(というかこれ、この順番でいいのだろうか……)
