### ISSUE TITLE
ユーザ名・パスワードペアによるログインができない

### ISSUE THREAD

**Issue by 10mocy** [misskey-dev/misskey#2384]
# Summary
- ユーザ名・パスワードペアによるログインができない

# Expected Behavior
- アカウント作成時、正常にアカウントが作成・データベースに記録され、ログインが可能となること
- 正常なユーザ名・パスワードペアでログインができ、「ホーム」画面に遷移されること

# Actual Behavior
- アカウント作成時に、400 Bad Request が返却され、正常にアカウントが作成できない
- 適切なユーザ名・パスワードを入力しているのにも関わらず、`400 Bad Request` が返却され、ログインができない

# Steps to Reproduce
## アカウント作成時
1. 非ログイン時に `/` へアクセス
2. 「新規登録」を押下
3. 「ユーザー名」「パスワード」「パスワード（再入力）」を入力
4. 「アカウント作成」を押下
5. `400 Bad Request` が返却され、アカウントが作成できない

## ログイン時
1. 非ログイン時に `/` へアクセス
2. 「ユーザー名」「パスワード」を入力
3. 「ログイン」を押下
5. `400 Bad Request` が返却され、ログインできない

# Environment
- misskey.xyz 
- 自インスタンス
  - OS: CentOS Linux release 7.5.1804 (Core)
  - リバースプロキシ : nginx 1.15.2
  - npm: 5.7.1
  - node: 10.8.0
- ブラウザ
  - Google Chrome: 68.0.3440.106 (Official Build) (64 ビット) (cohort: Stable)

**Comment by 10mocy** [comment]
`src/server/api/private/signup.ts` を弄って、ログにbodyを出力させたのですが、
```
  <-- POST /api/signup
{ username: 'nirot1r',
  password: '<password>',
  invitationCode: '',
  'g-recaptcha-response': null }
  --> POST /api/signup 400 10ms -
```
と表示されていました。
このあたりのデバッグ表示を確かめつつ探っていきます。

**Comment by 10mocy** [comment]
自環境でconfigファイルの設定を見直したところ、正常な動作を確認しました。
`400 Bad Request` を返す部分すべてに詳細なログを出力するようにしましたが、そこを走っていないため、原因は不明です。

**Comment by snowrx** [comment]
[7.1.2に含まれる](https://github.com/syuilo/misskey/commit/2c9bacfceade688865ad1e8533ca494dd34d0ee5)
[7.1.2より後](https://github.com/syuilo/misskey/commit/fd947407afb7a541a5cf21f5299fafb7e3afc44f)
クライアント側が7.1.2時点で動作し、usernameをx、passwordをyとしてPOSTしていますが、サーバサイドが7.1.2より後の操作でxとyを受け取れていないと思います。

**Comment by syuilo** [comment]
ローカルでは確認できなかった

**Comment by syuilo** [comment]
ご指摘のようにバージョンの不一致が原因である可能性が高いので一旦閉じます。まだ問題が発生するようでしたらReopenしますのでご報告ください。
