### ISSUE TITLE
言語が削除されるとMisskeyに接続できなくなる

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2392]
# Summary
https://misskey.jp/notes/5b7cf8ddbccfe8094d225aa1  
https://misskey.jp/notes/5b7cf93cbccfe8094d225aa5

# Environment

**Comment by syuilo** [comment]
言語を削除 というのはどういうことだろう

**Comment by acid-chicken** [comment]
ja-ksがja-KSにリネームされた影響で、Misskeyに接続できなくなるバグがあった。
