### ISSUE TITLE
GiphyからのGIFアニメ引用

### ISSUE THREAD

**Issue by argxentakato** [misskey-dev/misskey#2397]
## Giphyとは?
>  Giphy is an online database and search engine that allows users to search for and share short looping videos with no sound, that resemble animated GIF files. 

by Wikipedia

要はGIFアニメ共有サイトです。

## 導入するメリット
- Emojiよりも踏み込んだ感情を表現できる
- テキスト考えるのがだるくても投稿できる

## デメリット
- 荒しに使われるかも

**Comment by syuilo** [comment]
やろうかなあ

**Comment by rinsuki** [comment]
日本だと著作権的に微妙な気もする
