### ISSUE TITLE
Misskeyについてがリンク切れになっている

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#2418]
# Summary
Misskeyについて(docsへの言語別リンク)が、ロケール名が変わったことによりリンク切れになっている。
/docs/ja/about => /docs/ja-JP/about

# Expected Behavior
リンク先でドキュメントが表示される

# Actual Behavior
されない

# Steps to Reproduce
1. ホームでMisskeyについてをクリック

# Environment
Windows 10, Firefox 61

もともとドキュメントが提供されてない言語ではリンク切れになってそうなので、
サーバー側で存在する言語にルーティングしてあげたほうがいいのかもしれない。

**Comment by syuilo** [comment]
Fixed!
