### ISSUE TITLE
画像とSpotifyのプレビューがpostに含まれているとPaddingが大きすぎる値になる

### ISSUE THREAD

**Issue by xreiju** [misskey-dev/misskey#2421]
# Summary
画像とSpotifyのプレビューがpostに含まれているとPaddingが大きすぎる値になる

# Expected Behavior
もっと余白が狭いことを期待していました

# Actual Behavior
[この投稿](https://misskey.xyz/notes/5b7e2fa063c4a90036e9479d)のように、余白が非常に大きく見えます。

# Steps to Reproduce
1. [この](https://gist.github.com/xreiju/f1ed0977832f1bde2d5df546626d029c)プログラムで投稿する (画像一枚と、曲へのリンク(open.spotify.com)を貼っています)
2. TLや投稿ページなどで投稿を閲覧します
3. 曲へのリンクによって表示されるPlayerのPaddingが大きな値になっています

# Environment
PC版とモバイル版の両方で発生します

Google Chrome 68.0.3440.106 (Official Build) （64 ビット）
Safari バージョン12.0 (14606.1.36.1.3)
macOS Mojave バージョン 10.14 Beta (18A365a)

**Comment by acid-chicken** [comment]
paddingは問題ないことを確認しましたが、Spotifyのプレビュー自体がおかしくなっていますので、プレビューのバグである可能性が高いです。

**Comment by acid-chicken** [comment]
CSSセレクタを間違えておりました、申し訳ありません。
