### ISSUE TITLE
(API)フォローリクエスト却下APIの挙動が怪しい

### ISSUE THREAD

**Issue by tateisu** [misskey-dev/misskey#2422]
https://github.com/syuilo/misskey/blob/master/src/server/api/endpoints/following/requests/accept.ts は承認に成功すると空レスポンスが返りフォローリクエストはなくなりますが、

https://github.com/syuilo/misskey/blob/master/src/server/api/endpoints/following/requests/cancel.ts は
却下に成功しても申請した人のユーザ情報が返ってきて、一覧をリロードしてもフォローリクエストは残ったままです。

これでは却下したことにならないのではないでしょうか。

**Comment by syuilo** [comment]
ありがとうございます。
following/requests/cancel は、自分が作成したフォローリクエストを取りやめるAPIですが、フォローリクエストを拒否するAPIと間違ってはいませんか？

**Comment by tateisu** [comment]
なるほど失礼しました。
しかしそうだとするとなぜ成功レスポンスを返すのでしょうか…？

**Comment by tateisu** [comment]
reject の方は動作に問題ありませんでした。

**Comment by syuilo** [comment]
指定したユーザーへのフォローリクエストの存在チェックが抜けていました。修正します！

**Comment by tateisu** [comment]
チェックというか、deleteの「影響を受けた行の数」が0なら失敗レスポンスを返すと良い気がします
