### ISSUE TITLE
デック表示にて、タイトルをクリックで一番上に移動

### ISSUE THREAD

**Issue by ShinoharaTa** [misskey-dev/misskey#2447]
スクロールして他の人の投稿見ているときに新着がある場合は
デックのタイトル部分が赤く強調表示される

最新を表示しようとしたときにTweetDeckのクセでタイトルをクリックする
TweetDeckはカラムのリロードが走るのかな・・・？

もしかして、搭載済みで動かないのは私の環境だけかも・・・

**Comment by tamaina** [comment]
立案済み ( #1958 ) さらに近々実装予定 ( #2401 )です✨

**Comment by syuilo** [comment]
やった
