### ISSUE TITLE
Renoteの略称について

### ISSUE THREAD

**Issue by kazu0617** [misskey-dev/misskey#2452]
# Summary
Renoteの略称について、ここのIssueを見る限りでは"RP"といった名称と、"RN"といった名称が両方同じぐらいの割合で使われています。しかし、ソースコードを見る限りでは"RP"といった名称が使われていますが、"RN"といった名称は使われていません。
また、[joinmisskeyのページ](https://joinmisskey.github.io/ja/wiki/usage/interactions/)を参照する限りどちらが正しいのか判別できませんでした。
そのため、どちらが正しいのか整理したほうがいい気がしたので、建てた次第です。

**Comment by marihachi** [comment]
RepostからRenoteに名称が変わったとすれば、略称はRNじゃないですか

**Comment by kazu0617** [comment]
@marihachi 自分自身はそれに賛成していたりします

**Comment by syuilo** [comment]
RNにしました
