### ISSUE TITLE
ActivityPub用にMFMを変換する際、外部ユーザーへのメンションの<a href>にURLではなくURIを使っている

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#2467]
# Summary

ActivityPub用にMFMを変換する際、外部ユーザーへのメンションの`<a href>`にURLではなくURIを使っている。
MastodonなどではURIでもURLでも同じものを返してくれるので問題はないが、Misskeyの場合URIの方にアクセスするとActivityPubのオブジェクトしか返してくれないので、問題が発生する。

# Expected Behavior

外部ユーザーへのメンションの`<a href>`に(ある場合は)URLが使われる

# Actual Behavior

外部ユーザーへのメンションの`<a href>`に必ずURIが使われる

**Comment by syuilo** [comment]
外部ユーザーのURLって取得できましたっけ？

**Comment by syuilo** [comment]
具体的にはどのような問題が発生しますか？
MisskeyがURIの方にアクセスされたときActivityPubのオブジェクト以外も返すようにすることでも解決できますか？

**Comment by mei23** [comment]
> MisskeyがURIの方にアクセスされたときActivityPubのオブジェクト以外も返すようにすることでも解決できますか？

を既に行っているので

> MastodonなどではURIでもURLでも同じものを返してくれるので問題はないが、Misskeyの場合URIの方にアクセスするとActivityPubのオブジェクトしか返してくれないので、問題が発生する。

の問題はなくなっていると思います
