### ISSUE TITLE
検索構文でGoogle以外の検索エンジンを利用できるように

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2479]
# Summary
`hoge 検索:misskey`とするとMisskey、`fuga 検索:map`とするとマップサービス、というようにGoogle以外のいくつかの場所でも検索できるようになれば便利

# Environment

**Comment by Johann150** [comment]
I think also that Google should not be the default because it is bad for privacy.

**Comment by Johann150** [comment]
see https://github.com/misskey-dev/misskey/issues/8266#issuecomment-1050540457
