### ISSUE TITLE
ミュート機能

### ISSUE THREAD

**Issue by otofune** [misskey-dev/misskey#248]
もしくはブロック機能を。ミュートかブロック機能どちらかは快適な利用に必要だと思うけれど、ブロック機能よりかはミュート機能のほうがコミュニティーとしては優しいかなあと。

ミュート適用先は
- タイムライン
  + 一括取得
  + WebSocket
- 通知
  + 一括取得
  + WebSocket

…くらいでしょうか。

**Comment by syuilo** [comment]
ミュートしてたらフォローしている意味なくない？

**Comment by otofune** [comment]
フォローしている人間が単純に見ていて辛いのであれば、フォローしなければいいというのは正しいが、ミュート機能が欲しいというのはフォローしていない人間がタイムライン上に表示される事態、リプライツリーで見えること、リポストで表示されることを防ぎたいという意図からなので、フォローは関係ない

**Comment by syuilo** [comment]
なるほど～

**Comment by syuilo** [comment]
ミュート対象のユーザーの投稿への返信やRepostもミュートするには投稿の返信先の投稿者IDを非正規化することがほぼ必須になりそう
