### ISSUE TITLE
Federation with GNU/Social and Peertube.

### ISSUE THREAD

**Issue by skid9000** [misskey-dev/misskey#2493]
# Summary
Adding Federation support with GNU/Social and Peertube.

Right now when you try to see a GNU/Social profile from a misskey instance, it will return [a infinite loading screen
](https://puush.tuto-craft.com/6K257K.png) and when you check the server logs :

![](https://puush.tuto-craft.com/077l7Z.png)

When you try so see a Peertube profile, same loading screen but a different error in the logs :

![](https://puush.tuto-craft.com/5O398e.png)

# Environment

Tested on misskey.xyz and misskey.nsa.ovh with Firefox 61.0.2 on Windows 8.1

**Comment by mei23** [comment]
**GNU/Social** seem to not support ActivityPub.

_There are two federation protocol, ActivityPub and OStatus.
Misskey supports ActivityPub only.
GUN/Social supports OStatus only.
Mastodon supports both._

With **PeerTube**, 2nd WebFinger cause error
1. WebFinger acct:user@host => success
2. Fetch follower/following/outbox => success
3. WebFinger https://host/accounts/user => error

**Comment by lanodan** [comment]
It’s probably because you don’t webfinger with a ActivityPub actor URL. (if I understood your post well)

**Comment by mei23** [comment]
For PeerTube federation, fixed via #2530
Misskey no longer perform `WebFinger https://host/accounts/user`

**Comment by acid-chicken** [comment]
GNU social is now supporting ActivityPub!

**Comment by Johann150** [comment]
I don't think Misskey will support OStatus so I think this can be closed?
