### ISSUE TITLE
スマホの投稿フォームの入力がおかしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2504]
# Summaly
#2503 に関連しそう

1. 投稿を書く
2. 文章の途中を編集しようとして、入力を確定させ、編集したい箇所をタップ
3. 問題が発生する  
  - **Expected** 合わせた場所から編集が始まる
  - **Actual** 元いた場所から編集が始まってしまう

文章の最後から途中の例を示したが、文章の途中から最後に移動する時も同様の問題が発生する

Simejiのカーソル(← →)を利用してカーソルを送った場合は問題は発生しない

# Env
Android 6.0.1 Firefox (beta) latest Simeji(IME)

**Comment by syuilo** [comment]
Misskey以外のWebの入力フォームでは発生しませんか？

**Comment by tamaina** [comment]
はい、GitHubでは通常に編集できています
