### ISSUE TITLE
ドライブ→メニュー→[アバターに設定]するとファイル選択ウィンドウが出てくる

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2505]
# Summary

# Expected Behavior
選択したファイルをクロップする画面が出てくる

# Actual Behavior
ファイル選択ウィンドウが出てくる

# Steps to Reproduce
1. ドライブ
2. 右クリック
3. その他
4. アバターに設定

# Environment
Windows 10 Home Build 17728  
Firefox 62.0b20 (64bit)

**Comment by Hiramiya** [comment]
Verified and fixed in syuilo/misskey/pull/2509
Tested avatar updating, working correctly from drive menu, settings page and Home
