### ISSUE TITLE
モバイルでDMを送る際にユーザー追加ボタンを押しても無反応

### ISSUE THREAD

**Issue by kazu0617** [misskey-dev/misskey#2514]
# Summary
アンドロイド環境のWebApp上にて、DMを送る際に[+ユーザー追加]ボタンを押しても無反応

# Expected Behavior
1. 投稿画面を開く
2. 右下からDMにモードを変更
3. 現れた[+ユーザーを追加]をタップ
4. ユーザーを追加するためのダイアログが表示される
5. 追加して投稿できる

# Actual Behavior
1. 投稿画面を開く
2. 右下からDMにモードを変更
3. 現れた[+ユーザーを追加]をタップ
4. ユーザーを追加するためのダイアログが表示されない（無反応）

# Environment
OS: Android 8.0.0 / ASUS_Z01RD
Version: Chrome ver:68.0.3440.91

**Comment by syuilo** [comment]
ありがとうございます。
Android 持ってないので私は確認できませんでした

**Comment by SanMurakami** [comment]
複数のAndroid端末とエミュでテストしましたが再現せず。

**Comment by kazu0617** [comment]
何分去年なのでIssue建てた本人も試せる環境が存在しません…なので環境依存であれば閉じてもらって問題ないです、申し訳ないです（Z01RDに搭載されるAndroidのVersion自体、一つ上がっておりますしChromeも随時更新されておりますので同一環境が用意できなさそうです

**Comment by syuilo** [comment]
v12では処理が変わっているのでもうこの現象は発生しなさそう
