### ISSUE TITLE
Misskeyにもリモートフォローのボタンがほしい

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/misskey#2518]
# Summary
Mastodonにあるようなやつ

**Comment by tamaina** [comment]
登録しているインスタンスでもリモートフォローを開始できるボタンを付けてほしい

**Comment by ghost** [comment]
やらないならcloseすればいいのに

**Comment by syuilo** [comment]
Contributionは歓迎です

**Comment by AruMoon** [comment]
when it will be implemented?

**Comment by syuilo** [comment]
実装の予定は立っていません。(Contribution歓迎)
