### ISSUE TITLE
ActivityのactorにObjectを指定されてくるとホストの検証手段がない 

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#2529]
# Summary
#2528 関連
Activityのactorのように、PersonのURIが指定されてくる場所では
PersonのObject自体が添付されることも許容しているが
この場合、内容が正当なホストのものか検証する手段がない。
こちらから必ず取得しにいかないと検証できないため、PersonにObject指定は許容できなそう。

HTTP Signature があるが、検証前に公開鍵を設定出来てしまうので意味なさそう。

Activity受信時に、activity.actor にURIでなくてオブジェクトを指定されると
相手の名乗った情報(公開鍵を含む)を、そのまま登録できてしまう。
https://github.com/syuilo/misskey/blob/09f97bf7a7e0652fe7438e13164586ef4431cba6/src/queue/processors/http/process-inbox.ts#L37-L40
https://github.com/syuilo/misskey/blob/09f97bf7a7e0652fe7438e13164586ef4431cba6/src/queue/processors/http/process-inbox.ts#L47-L50

その後署名検証がその登録された鍵で行われる可能性がある
https://github.com/syuilo/misskey/blob/09f97bf7a7e0652fe7438e13164586ef4431cba6/src/queue/processors/http/process-inbox.ts#L58-L62

# Expected Behavior

# Actual Behavior

# Steps to Reproduce
1.
2.
3.

# Environment

**Comment by syuilo** [comment]
Resolved by @mei23
