### ISSUE TITLE
日誌

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2532]
# Summary
タイムラインのタイムマシンに代わるものとして？  
その日にのMisskeyについて様々な情報が表示されるページがあったらいいなと  

情報の例としては→

- その日のローカル/自分のタイムラインと投稿数
- 最も反応を得たローカル/リモート/自分の投稿
- 自分が反応した投稿一覧
- 自分がお気に入りした投稿一覧

名前はダイアリー*diary*かジャーナル*journal*?

# Environment

**Comment by marihachi** [comment]
その日の反響が大きかったノートをピックアップしてくれるとか良さそう

**Comment by syuilo** [comment]
とりあえず「その日の反響が大きかったノートをピックアップ」だけやります

**Comment by syuilo** [comment]
done
