### ISSUE TITLE
(API) プッシュ購読APIがサーバ公開鍵を返さない

### ISSUE THREAD

**Issue by tateisu** [misskey-dev/misskey#2541]
プッシュ購読APIはサーバ公開鍵を返さないので、プッシュを受け取ったendpointはそれが正しいサーバからのメッセージか悪意のある第三者からのメッセージかを区別できない

サーバ公開鍵はプッシュイベントのHTTPヘッダにも含まれるから不要と思われるかもしれないが、プッシュ購読APIが返すサーバ公開鍵と一致するか確認することでプッシュイベントの送信元が信頼できる相手かどうかの判断に使われる。

**Comment by syuilo** [comment]
その公開鍵というのはここで設定している鍵のことですか？
https://github.com/syuilo/misskey/blob/develop/.config/example.yml#L121

**Comment by tateisu** [comment]
多分それです。

swモジュールのことは全く分かりませんが、プッシュイベントのHTTPリクエストのAuthorization: WebPush (...) ヘッダの (...)部分にp256ecdsa=([^;\\s]+)  で渡されるECDSA公開鍵のことです。

で、これを「購読が成功した時」「既に購読が存在する時」の両方で返すようにしてほしいです。
VAPID KEYは情報漏洩の後などに変更されることがあり、アプリは最新のVAPIDキーを受け取った後にそれをアプリサーバに伝達する必要があります。
