### ISSUE TITLE
投稿ウィンドウをモーダルでなくす

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2552]
desktop

**Comment by tamaina** [comment]
新規投稿時に画像を指定するためのウィンドウではなく、前から開いていたウィンドウからドラッグしたいのです
現状、背景がブラックアウトして新規投稿ウィンドウしか操作できないので

**Comment by syuilo** [comment]
ドライブウィンドウからドラッグできた気がします

**Comment by syuilo** [comment]
ドライブウィンドウを開いている状態で投稿フォームにファイルをドラッグ&ドロップできることを確認しました

**Comment by syuilo** [comment]
ということは右上の新規投稿ボタンを押した場合のことですね

**Comment by tamaina** [comment]
ホームにも投稿フォームがあるんでしたね…
