### ISSUE TITLE
猫耳の有効化・無効化とアイコンの形のオプションを分けてほしい

### ISSUE THREAD

**Issue by kazu0617** [misskey-dev/misskey#2556]
# Summary
アイコンの形に関してのオプションと、猫耳のつき方に関して同期されている感じなので、新しく猫耳をつけるかどうかに関してのオプションを追加してほしい。

- [ ] 猫耳のアイコンの有効化・無効化オプションの追加
- [ ] 猫耳のつき方に関しての非同期化

# Environment
いらないと思うけど一応
- OS: Linux Mint 19 / Windows 10 / Android 8.0.0

**Comment by acid-chicken** [comment]
> アイコンの形に関してのオプションと、猫耳のつき方に関して同期されている感じ

FYI:これは角丸スタイルと、実装されている猫耳がデザイン上うまく合わなかったために起こっている問題です。将来的には角丸においても猫耳をつけられるようにしたいと考えています。

**Comment by acid-chicken** [comment]
@syuilo 可能であれば`cat`の固有機能としてしまいたい

**Comment by syuilo** [comment]
このIssueの旨が「猫耳の有効化・無効化とアイコンの形のオプションを分けてほしい」というものなので、それに関しては実装しない方針なのでCloseしました。

**Comment by kazu0617** [comment]
了解です
