### ISSUE TITLE
リストのタイトルを変更するAPIエンドポイントが欲しい

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/misskey#2583]
# Summary
エンドポイントのパスの案としては２つあります。

- users/lists/rename
- users/lists/update-title

簡単そうなのでPR飛ばすかも

**Comment by syuilo** [comment]
users/lists/update はどうでしょう

**Comment by marihachi** [comment]
エンドポイントを追加する時に、`src/server/api/endpoints` 以下にエンドポイントのファイルを追加する以外に必要な手順ってありますか？

**Comment by syuilo** [comment]
ないです！

**Comment by marihachi** [comment]
PR飛ばしました～
https://github.com/syuilo/misskey/pull/2585
