### ISSUE TITLE
リバーシのUI改善案

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#2594]
# Summary

- [ ] 石支配率をバー表示してほしい
- [ ] onmousedown後に取り消すことができるようにしてほしい
- [ ] 置ける場所をホバーすると、次の手番で置ける場所を別色で色付けしてほしい

# Environment

client

**Comment by acid-chicken** [comment]
石支配率については、flexで簡単に実装できそう。

**Comment by syuilo** [comment]
そういえば石支配率は昔はグラフで表示してましたね
