### ISSUE TITLE
開発ビルドの表示について

### ISSUE THREAD

**Issue by penginnu** [misskey-dev/misskey#2598]
適切な質問先がわからなかったのでissueにて失礼します。

セットアップガイド通りにセットアップをし、npm startで起動させたのですが、「開発者ビルドです。」と表示されました。
設定ファイルを見てもそのような設定がないのですが、通常のモードにするにはどうしたらよいのでしょうか？

**Comment by syuilo** [comment]
環境変数の NODE_ENV を production にしてビルドしてみてください！
