### ISSUE TITLE
preventCacheRemoteFiles: true の時にリモートアイコンが表示できなくなる

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#2600]
# Summary
preventCacheRemoteFiles: true の時に、Mastodonで A=>B=>A のようにアイコンを変更するとアイコンが（そのうち）表示できなくなる。

# Expected Behavior
表示できる

# Actual Behavior
できない

# Steps to Reproduce
- 以下の条件を満たしていると事象がわかりやすい
  - Mastodon側の画像サーバーにはキャッシュやCDNを使用してない状態
  - ブラウザのキャッシュは無効にしておく
  - 使用するファイルはアニメーションGIF

1. Misskey側では、preventCacheRemoteFiles: true にしておく
2. Mastodonの特定ユーザーをMisskeyからフォローしておく
3. Mastodonの特定ユーザーで、画像1をアイコンに設定する
4. Mastodonの特定ユーザーで、画像2をアイコンに設定する
5. Mastodonの特定ユーザーで、画像1を再度アイコンに設定する
→Misskey側でMastodon側の画像を参照した際に404になる

# Memo
以下のようなことが起きている
1. Mastodonで hash=x001の画像を001.gifで保存し、それをアイコンとする。
2. Misskeyは それを[hash=x001, url=001.gif]として記録して、リンクして使用する。
↓
3. Mastodonが hash=x002の画像を 002.gifで保存し、それをアイコンとする。この時点で001.gifは削除される。
4. Misskeyは それを[hash=x002, url=002.gif]として記録して、リンクして使用する。
↓
5. Mastodonが hash=x001の画像を 003.gifで保存し、それをアイコンとする。
6. Misskeyは hashが2のものと同じため [hash=x001, url=001.gif] のままurlは変えないままになる。
↓
001.gif もはや削除されているため表示できない。

なお、preventCacheRemoteFiles: false に後で変更しても、
同ハッシュのurlが更新されないのは変わらないため、
Mastodon側で何回変更してもなおらない。

**Comment by syuilo** [comment]
ありがとうございます！
(キャッシュしないで直リンクする)リモートのファイルは、「ハッシュが同じだけどURLが違う」ときはURLを更新するようにすれば解決しますかね

**Comment by mei23** [comment]
おそらく大丈夫だと思うわ
