### ISSUE TITLE
リストのリンクがおかしい

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#2603]
ホームやDeckの画面でメニューからリストを選択すると通常通りにアクセスできるが、リストをすでに開いた状態で別のリストを開くとリンクが壊れる

**例**
リストAを開いたとき
https://misskey.xyz/i/lists/aaaa~
リストBを開いたとき
https://misskey.xyz/i/lists/i/lists/bbbb~

**Comment by tamaina** [comment]
#1866 と同じですね
