### ISSUE TITLE
リモートフォローすると MongoError: E11000 duplicate key error index が発生する

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#2605]
# Summary
リモートフォロー（相手が鍵アカウントでない場合）すると

Acceptが返ってきた時に以下のエラーになる
```
misskey:activitypub Accept: https://リモート/users/ユーザー#accepts/follows/57 +0ms
{ MongoError: E11000 duplicate key error index: misskey.following.$followerId_1_followeeId_1 dup key: 
```

リモートフォロー(AからBにする場合)は

1. A => B: Follow Activity 送信
2. B => A: Accpet 返信

でというフローになるが

フォローのInsertを1でも2でも行っているため

#2604 もあるためリモートフォロー時は最初に(1で)フォロー済み状態にしないほうがよい。

# Expected Behavior

# Actual Behavior

# Steps to Reproduce
1.
2.
3.

# Environment

**Comment by syuilo** [comment]
Resolved by @mei23
