### ISSUE TITLE
アイコンにはjpegサムネイルではなく適切に縮小した元画像と同じ形式の画像を使用してほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2612]
# Summary
jpegに変換すると、透過が黒背景になったりアニメでなくなったりしてユーザーが意図しない表示になるため

# Environment

**Comment by SanMurakami** [comment]
これに伴って言えることは、アホみたいにファイルサイズがでかいGIF画像(解像度を下げても長さとか色の数で重い)をサムネイルに設定する人もいるので、サムネイルに設定できる元画像のファイルサイズの制限を設けるべきとかも考えたりする
元画像が3MBぐらいなら圧縮すれば動作に支障がないぐらいまで軽量化されるはずだし。

**Comment by tateisu** [comment]
GIFとかAPNGとか「適切に縮小」が困難な形式については「元画像の時点で100KBまで」などの制限をつけるべきだと思います。

関連 https://github.com/syuilo/misskey/issues/2365
