### ISSUE TITLE
mediaIds --> fileIds

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#2620]
投稿に画像や動画以外のファイルを添付できることを仕様として昇格させたいので、そのためにはプロパティ名が media のままだと不自然なので file にしたい

**Comment by syuilo** [comment]
引き続き以前のパラメータ名でも受け付けたりレスポンスの際にプロパティを複製すれば後方互換性を維持することができそう
ただいつまでもそれだと無駄なのでいつかはサポートを削除する必要がある

**Comment by tamaina** [comment]
mediaの意味としては「媒体」ぐらいの意味しかない(画像や動画に限定されない)ので変える必要はないと思う

**Comment by syuilo** [comment]
なるほど
でも media は複数形にできないので以前からちょっと不便な単語だと思っていたのでこの機会に変えたいというのもある

**Comment by tamaina** [comment]
言葉の意味が違うからとAPIを変えていたら色々もたないし非効率なので、やってほしくないです

**Comment by syuilo** [comment]
意味があっていないプロパティ名でやっていく方が非効率な気がする

**Comment by tosuke** [comment]
mediaはそもそも複数形
単数形はmedium

**Comment by syuilo** [comment]
medium はあんまり使われてるの見たことないですね
