### ISSUE TITLE
CI/CDの見直し

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#2621]
# Summary

現在misskeyはTravis CIを利用してビルドチェックおよびテストを行っていますが、これが設定されたのは約1年前になります。現在の開発プロセスを鑑みるに、これらの設定は少々現状のそれに見合わないような気がします。
そこで、CI/CDの見直しをディスカッションしたいと考えております。
よろしくお願いします。

**Comment by AyaMorisawa** [comment]
> 現在の開発プロセスを鑑みるに、これらの設定は少々現状のそれに見合わないような気がします

現在の開発プロセスに見合わない理由は何でしょうか。単に約1年前に設定されたという事実だけでは、開発プロセスに見合うかどうかの判断は不可能です。

> CI/CDの見直しをディスカッションしたいと考えております

建設的な議論を行うためには **具体的な見直し案** が必要です。 **具体的な見直し案** を新しいIssueとして作成してください。
