### ISSUE TITLE
Document federation info

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [misskey-dev/misskey#2650]
# Summary
Hi! I'm an english person who is very interested in the work you have done here. Specifically, I'm interested in how Misskey federates certain things. I would love to implement reactions and such in a fork of Mastodon or Pleroma. Unfortunately, I can't seem to find any documentation on how these objects are sent.

Would it be possible for a developer to inform me how I would go about recognizing a reaction sent to my service's /inbox?

**Comment by syuilo** [comment]
Currently, Misskey attaches reaction to the Like Activity. Property name is `_misskey_reaction`.
The property contains a string representing reaction. It is one of the following:
* `'like'`
* `'love'`
* `'laugh'`
* `'hmm'`
* `'surprise'`
* `'congrats'`
* `'angry'`
* `'confused'`
* `'rip'`
* `'pudding'`

**Comment by twilight-sparkle-irl** [comment]
Thank you! I still think a centralized document with the info on the extensions misskey uses for ActivityPub will be helpful, but this answers my question.

**Comment by ghost** [comment]
I have the same question. Will Misskey provide a detailed federation documentation?

One of my favorite service on Mastodon, [rss-to-activitypub](https://github.com/dariusk/rss-to-activitypub), cannot be handled in Misskey. If I want to follow an account on its server, it will stick in `Processing`.

Wish for your help and here is the reference issue: dariusk/rss-to-activitypub#42.
