### ISSUE TITLE
インスタンスのリモートフォローが進まない

### ISSUE THREAD

**Issue by penginnu** [misskey-dev/misskey#2674]
# Summary
一部を除いたインスタンスのリモートフォローが進まない。（承認待ちになる）

# Steps to Reproduce
全く不明です。基本的に標準のガイド通りかつ、すでにインスタンスを正常に運営している方のアドバイスを受けたうえで立てているので原因は不明です。

# Environment
- Misskey 8.33.1
- CF + nginx 使用
インスタンスは、https://misskey.saibou.work/ こちらになります。

**Comment by syuilo** [comment]
フォロー対象のアカウントは鍵アカウントではありませんか？

**Comment by penginnu** [comment]
対象は鍵アカウントではありません。
具体的に、フォローできたアカウントを挙げるならば
- @UN_NERV@unnerv.jp さん

できなかったアカウントを挙げるならば
- @syuilo@misskey.xyz さん
- @negao@misskey.site さん
などです。

**Comment by penginnu** [comment]
追記ですが、他インスタンスの投稿は取得できているようです。

**Comment by syuilo** [comment]
ありがとうございます。
挙げていただいたアカウントを見る限りMisskeyであることが関係してそう...？

**Comment by penginnu** [comment]
すみません書き忘れました。
@nullkal@mstdn.jp さんなどもフォローできないので、そこについては何とも言えない状況です。

**Comment by syuilo** [comment]
なるほどなるほど....

**Comment by penginnu** [comment]
上にも追記しましたが、Misskeyはv8.33.1です

**Comment by mei23** [comment]
たぶんネームサーバを今日CloudFlareのに切り替えたばかり？と思われるので
旧ネームサーバーを見てるインスタンスがまだダメなのかと思うわ。
最大2日くらいはかかるはず。

旧ネームサーバーを見ているインスタンスはオリジンサーバーを見る
↓
オリジンサーバーのSSL証明書はCloudFlare用のものに変更している？ので直アクセスには使えない
↓
一部インスタンスはアクセスできない
なのではと思うわ。

**Comment by mei23** [comment]
@penginnu 
やはり今CloudFlare の証明書が設定されているみたいで、
旧ネームサーバーを見てるインスタンスの直アクセスには使えないからだと思うわ。

すぐになおすには、
オリジンサーバーで昔使っていた証明書(Let's Encryptなど)があるならば、
一旦その証明書に戻せば直るはず。
（その後2日くらいまってCloudFlareの証明書を設定する）

**Comment by syuilo** [comment]
@mei23 めいめいさんありがとうございます。
Misskeyの問題ではないようですのでCloseします。
