### ISSUE TITLE
「ローカルのみ」の公開範囲がほしい 

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2683]
# Summary
インスタンス内のみで閲覧でき、リモートには一切流れない公開範囲があってもよさそう

# Environment

**Comment by tamaina** [comment]
このタイトル名の迷いですが、｢リモートに流さないようにして、さらに公開範囲を設定したい時がありそう｣……と思ったけど、せいぜい｢ホーム｣しか併用できる公開範囲がなかったのでやっぱりやめた、という感じです

**Comment by syuilo** [comment]
ローカルのpublicか、ローカルのhomeかは分けたいときあるかも
