### ISSUE TITLE
ナビゲーションバーの「ホーム」「デッキ」を並べ替えて表示してほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2719]
デスクトップで利用する際、ホームとデッキの両方を使うような使い方は少なそうなので、どちらを利用していたか記憶し、普段使っているものを常にナビゲーションバーの左端に表示するようにしたほうが便利そう

**Comment by syuilo** [comment]
デッキをデフォルトのUIとして使用するオプションを実装しました。
このオプションをオンにすると / にアクセスしたときデッキが表示されるようになり、ナビゲーションの並びもデッキが先頭にくるようになります。
