### ISSUE TITLE
ごみ箱

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#273]
・ごみ箱に入っているファイル・フォルダにはごみフラグを立てる(`is_trash`?)
・ファイル一覧・フォルダ一覧のAPIでそれらは弾く
・ごみ一覧を取得するAPIを作る

**Comment by AyaMorisawa** [comment]
ごみフラグ → `is_deleted`?
API → `delete`, `undelete`, `list`?

**Comment by syuilo** [comment]
`is_deleted`だとそのファイルが完全に削除されたことを示してしまう

**Comment by syuilo** [comment]
そもそもごみ箱機能の必要性があまりないかもしれない
