### ISSUE TITLE
MFM>構文のバグ

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2744]
## Case 1
```
> ねこです
> よろしくおねがいします
```

↓

![image](https://user-images.githubusercontent.com/7973572/45827451-6b892f80-bd31-11e8-8771-7751070bb77b.png)

◇ SCP-040-JP ©Ikr_4185 - このコンテンツは、[クリエイティブ・コモンズ 表示-継承3.0ライセンス](http://creativecommons.org/licenses/by-sa/3.0/deed.ja)の元で利用可能です。

## Case 2
```
Issue opened: <2744>
「MFM>構文のバグ」
https://github.com/syuilo/misskey/issues/2744
```

↓

![image](https://user-images.githubusercontent.com/7973572/45827608-bb67f680-bd31-11e8-8458-2db5296c936a.png)

## これってまさか
仕様なんですか？

**Comment by tamaina** [comment]
なおってない or また別のバグが発生したみたい？

```
> あふん
あああ
```

↓

![image](https://user-images.githubusercontent.com/7973572/46232662-d29a8a00-c3aa-11e8-8007-a7b7eb399c41.png)

2行目の「あああ」は引用が解除されるべき

**Comment by mei23** [comment]
@tamaina GitHubとかのMarkdownも同じ仕様みたい

> あふん
あああ

**Comment by syuilo** [comment]
はい。それは仕様です
