### ISSUE TITLE
メッセージ → トーク

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#2748]
ActivityPubのSpecified投稿と名称が被るため

**Comment by syuilo** [comment]
Done

**Comment by tamaina** [comment]
できてなさそう
https://github.com/syuilo/misskey/search?q=%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8&unscoped_q=%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8
