### ISSUE TITLE
@Reply behavior in ActivityPub addressed to IDN from Misskey is strange

### ISSUE THREAD

**Issue by h3zjp** [misskey-dev/misskey#2758]
Misskey から 国際化ドメイン名宛ての ActivityPub での @返信 の挙動がおかしいです。
普通のドメイン宛ての ActivityPub での @返信 なら問題ないです。

The behavior of @reply in ActivityPub addressed to internationalized domain name from Misskey is wrong.
@Reply with ActivityPub addressed to ordinary domain is fine.

**Comment by syuilo** [comment]
fixed!
