### ISSUE TITLE
メッセージごとに既読フラグを管理するのをやめる

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#276]

**Comment by AyaMorisawa** [comment]
代わりに最後にユーザーがメッセージを読んだ日時を記録する？

**Comment by syuilo** [comment]
そういう感じになりますね 日時というよりは最後に見たメッセージ(のID)を記録するかも

**Comment by AyaMorisawa** [comment]
`lastRead` ?

**Comment by syuilo** [comment]
既読コレクション(テーブル)が必要かも
* ユーザーID
* やり取り相手
* どこまで読んだか(メッセージID)

**Comment by syuilo** [comment]
うーんメッセージごとに既読フラグを管理した方が便利な気もしてきた

**Comment by syuilo** [comment]
そもそもなんで私はメッセージごとに既読フラグを管理するのをやめようと思ったんだろう

**Comment by syuilo** [comment]
こっちで実装はほぼ終わったけど、以前(メッセージごとに既読フラグを管理)よりかえって複雑になった気がするので

**Comment by otofune** [comment]
そもそも既読フラグをつける意義がないと思うんですが、あくまで僕の意見なのでsyuiloはどのように考えて既読フラグつけてますか

**Comment by syuilo** [comment]
ないと不便なので、そこにもう議論の余地はないと思っています

**Comment by syuilo** [comment]
フラグをひとつに纏める or それぞれで保持する

**Comment by otofune** [comment]
なるほど、プロジェクトリーダーが必要と思うならこのプロジェクトには必要なのだろう。roomにフラグをつけるという方向はどうですか。他人から既読状態が見られるのは無理だというならないですが。

**Comment by syuilo** [comment]
まあもちろん既読を通知するかどうかはユーザーが設定できるようにはします。
roomにフラグをつけるというのはよくわからないけど最後に見たメッセージのIDを記録する方式ということかな

**Comment by otofune** [comment]
既読通知設定ができるなら単に便利な機能で良いですね。そうですね、room の document に ユーザーID (ObjectId) 対 メッセージID (ObjectId) になっている object を突っ込む感じの。旧時代のlatestPostみたいに。

**Comment by syuilo** [comment]
なるほど〜、私の実装にほぼ相当しそうですね
これをpushしようかどうかずっと迷ってる(理由はさっき言ったようにかえって複雑になった気がしたから)

**Comment by otofune** [comment]
じゃあ、意見募集のために `improve_readflag` とか名付けて別のブランチとしてpushして、PRを作成しませんか
