### ISSUE TITLE
ミュートが効かない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2769]
# Summary
ローカルタイムラインで、ミュートしているユーザーの投稿が表示される。ただしストリームで流れてきたもののみ。

# Environment
misskey.xyz  
Windows 10  
Firefox 63.0b8 (64 ビット)

**Comment by syuilo** [comment]
これとは異なりそうですか？
https://github.com/syuilo/misskey/issues/1540

**Comment by tamaina** [comment]
これですね
