### ISSUE TITLE
ファイルをアップロードする前に、既にそのファイルがドライブ上に存在していないかチェックする

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#2773]
存在していたらそのファイルを取得する

see: 
https://qiita.com/minodisk/items/24e253bb9f2313621a6b

**Comment by sei0o** [comment]
/src/services/drive/add-file.ts を見るに、すでに実装されているように思えるのですが閉じ忘れでしょうか？

```ts
		// Check if there is a file with the same hash
		const much = await DriveFile.findOne({
			md5: hash,
			'metadata.userId': user._id,
			'metadata.deletedAt': { $exists: false }
		});

		if (much) {
			log(`file with same hash is found: ${much._id}`);
			return much;
		}
```

**Comment by syuilo** [comment]
このIssueで言っているのはクライアントサイドの方ですね。
現在の実装だと、いったんサーバーにファイルをアップロードしてみない限り同じファイルが存在しているかどうかわかりません

**Comment by sei0o** [comment]
そういうことでしたか、すみません :bowing_man: (git blameすればわかる話でした)

クライアントサイドでMD5を計算して一度それだけをサーバに投げて判定すれば通信量が節約できるということですね
