### ISSUE TITLE
Remove Google Captcha

### ISSUE THREAD

**Issue by DavidLibeau** [misskey-dev/misskey#2786]
# Summary

Is it possible to remove the use of Google captcha (anti robot detector)?
I've got blacklisted by Google so I can't use Misskey...
![screenshot_2018-09-30 misskey](https://user-images.githubusercontent.com/11574966/46250889-b814ef00-c444-11e8-8a2a-c8d470d1fb45.png)

# Environment

Various Firefox 62

**Comment by syuilo** [comment]
reCapture is optional per instance.
Please try to visit other instance :)
