### ISSUE TITLE
src/crypto_key.ccをTypeScriptに書き直してほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2789]
# Summary
`src/crypto_key.cc`は実装者の得意言語で書かれているが、これだけC++で書かれており、node-gypを導入しビルドする必要がある。これは、コードの保守性を悪くし、Missekeyの導入を難しくしているように思われる。

可能ならばこの関数をNodeのcryptoなどを利用してTypeScriptで書き直してほしい。

# Environment

**Comment by mei23** [comment]
Cで書かれていいるコードはRSA秘密鍵の生成など
↓
NodeのcryptoではRSA秘密鍵の生成はできなそう
↓
Pure JavaScriptな外部モジュールを使う必要がある(Cライブラリに依存すると結局gypがいるため)
↓
Pure JavaScriptなものはある
https://www.npmjs.com/package/node-rsa
https://www.npmjs.com/package/node-forge
↓
やってみるとけっこう遅い

Generate RSA 2048bit (ミリ秒)

| | Average | Max | Min |
|---|---:|---:|---:|
| 既存 | 220 | 509 | 35 |
| node-rsa | 8,437 | 32,557 | 1,444 |
| node-forge | 6,489 | 16,461 | 746 |

**Comment by acid-chicken** [comment]
`crypto_key.cc`をwast形式で書き直した場合、node-gypへの依存はなくなりかつ速度もそれなりのものが期待できるが保守性を向上させるといえるかが微妙なところ。

**Comment by syuilo** [comment]
たしかにここをJavaScriptにしたとしても、他にもnode-gypを使っているモジュールはあるので、結局node-gypに依存することになります。
node-gypを完全に排除した依存関係を保とうとするのは難しそう。

例えばAがあるバージョンからnode-gypを使うようになるかもしれないし、Aの代替となるモジュールが見当たらないかもしれないし、A自体がnode-gypを使ってなくてもAが依存するBがnode-gypを使ってるかもしれないし…など

**Comment by syuilo** [comment]
ただまあC言語よりはJavaScriptの方がメンテナンスしやすいので(１つの言語に統一されている方が開発者フレンドリー)、速度面がなんとかなればJavaScriptにするのも良さそうです。

**Comment by tosuke** [comment]
wasmで実装するというのはどうでしょうか

**Comment by tosuke** [comment]
暗号系のライブラリはあまり変えないほうがよい気がしますね(セキュリティ上の問題などもあるので)
