### ISSUE TITLE
configのポート構成あたりの説明がわかりにくい

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#2792]
# Summary
configのポート構成の説明がわかりにくいみたいです https://github.com/syuilo/misskey/issues/2791#issuecomment-425718146
```
# URL and Port settings overview
# e.g., If you want to realize following structure:
#
#               +--- https://example.com:123 ----------+
# +------+      |+-------------+      +---------------+|
# | User | ---> || Proxy (123) | ---> | Misskey (456) ||
# +------+      |+-------------+      +---------------+|
#               +--------------------------------------+
#
# You need to set 'https://example.com:123' to 'url' prop and
# You need to set 456 to 'port' prop.
#
# In other words, the 'url' prop should be the final accessible URL seen by a user.
# 'port' prop is a port that the Misskey server should actually listen
# on and it is not necessarily the port that a user accesses.

url: http://localhost/

# A port that your Misskey server should listen.
# This value is not a port to use when accessing with a browser.
port: 80
```
- urlにポートが必要と誤解する→実際はhttps && 443なので不要
- 123という表記で別のポート採番が必要と誤解する→実際は443で公開用ポートと同じなので気にしなくてよい
- 456が特権ポートなのでサンプルとしてよくない
- urlとportの既定値があまり使わなそうな値だったり、上の説明と対応してなかったりする。

また、リバースプロキシを使用する vs Misskeyが443をListenするの2パターンの構成が考えられるので、ややこしくなってそう。

# Environment

**Comment by mei23** [comment]
```
# URL and Port settings overview
# e.g., If you want to realize following structure:
#
#               +----- https://example.com/ ------------+
# +------+      |+-------------+      +----------------+|
# | User | ---> || Proxy (443) | ---> | Misskey (3000) ||
# +------+      |+-------------+      +----------------+|
#               +---------------------------------------+
#
# You need to set 'https://example.com/' to 'url' prop and
# You need to set 3000 to 'port' prop.
# You need comment out 'https' section.
#
# In other words, the 'url' prop should be the final accessible URL seen by a user.
# 'port' prop is a port that the Misskey server should actually listen
# on and it is not necessarily the port that a user accesses.

url: https://example.com/

# A port that your Misskey server should listen.
# This value is not a port to use when accessing with a browser.
port: 3000
```
などとすればわかりやすそうなものの、
この場合Reverse Proxy必須となるのでReverse Proxy(Nginx等)の手順についても補足が必要になりそう。

**Comment by xps2** [comment]
nginxとかのサンプルの設定もあった方がよいのかな

**Comment by mei23** [comment]
MastodonはガイドにNginxの設定があったり
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md#nginx-configuration
PleromaはNginxのサンプルが用意してあったり
https://git.pleroma.social/pleroma/pleroma/wikis/Pleroma%E3%81%AE%E5%85%A5%E3%82%8C%E6%96%B9#nginx
するみたいなのであってもよさそう

私はこんな感じだわ
https://github.com/mei23/memo/blob/master/misskey/Setup-Ubuntu1804-Quick.md#%E7%AE%A1%E7%90%86%E8%80%85%E3%83%A6%E3%83%BC%E3%82%B6%E3%81%A7nginx%E3%81%A8ssl%E8%A8%BC%E6%98%8E%E6%9B%B8%E3%82%92%E8%A8%AD%E5%AE%9A

**Comment by syuilo** [comment]
ありがとうございます！
私はnginxの知識全くないのでドキュメントは後回しになりそうです

**Comment by ycrack** [comment]
私もこの図見て、 🤔… → 😭なんぞこれ…
って試行錯誤しましたわ…

最終的にurl:をhttps://から初めて、port: 443にして、TLS設定するとうまく行きました。

しゅいろさんはどっちなんだろう…？ 🤔

**Comment by mei23** [comment]
ドキュメント修正しているのもう大丈夫そう
