### ISSUE TITLE
Report instance-wise options in the /api/meta

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#2794]
# Summary
This feature request is reporting instance-wise options in the `/api/meta`, such as:
```javascript
features: {
  "recaptcha": true,
  "elasticsearch": false,
  "twitter": false
}
```
# Use cases
* Some lists of Misskey instances can show the instance-wise options, just like [Pleroma instances and their features](https://distsn.org/pleroma-instances.html).
* Mr #2786 may search for the instance without reCAPTCHA,

# Environment
* Server/API

**Comment by tamaina** [comment]
[joinmisskey](https://joinmisskey.github.io/ja/wiki/instances/)でこのAPIに対応(かなりどうでもいい宣伝)
