### ISSUE TITLE
連合が絡むタイムラインでは日付区切りを表示しないようにする

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#2795]
# Summary
タイムラインで日付が変わった際に日付区切りのバーが挿入されるが、
ローカル, ローカルユーザー以外TLの(連合が絡むTL)では表示しないようにする。

ローカル, ローカルユーザー以外のTLでは、
連合から過去の投稿が到着(Renote/Replyなどにより)することがあり
その度に日付切り換えが表示されてしまうため。

![image](https://user-images.githubusercontent.com/30769358/46275612-86ad3800-c598-11e8-94c6-6332139afd19.png)

# Environment

**Comment by syuilo** [comment]
どちらかというと過去の投稿がタイムラインに表示されてしまうこと自体がバグなので、修正するとしたらそっちの方になりそうですね

**Comment by syuilo** [comment]
日付区切りがあった方が分かりやすそう

**Comment by mei23** [comment]
日付区切りはもう出ない
