### ISSUE TITLE
リストタイムラインを読み込めない (xyz)

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2806]
# Summary
**一部の**リストタイムラインを読み込めず、エラーが出る。ただしストリームから新たに流れてくる投稿は表示される。

一応issueに載せましたが、xyzの運用上の問題かもしれない

Deck  
![](https://s3.arkjp.net/misskey/drive/07b64b2d-954f-4f84-8036-6e4db76be058/image.png)

Home  
![image](https://user-images.githubusercontent.com/7973572/46401930-55b83900-c739-11e8-8238-69cdd6cbc777.png)

# Expected Behavior
投稿が表示される

# Actual Behavior
一部のリストタイムラインでエラー

# Steps to Reproduce
1. リストタイムラインを読む

# Environment
misskey.xyz (client ver 1.0.10062 (nighthike))  
自動更新を有効にしたFirefox Developer Edition 及び Google Chrome

**Comment by mei23** [comment]
APIからエラーメッセージが返ってきているかもしれないので、確認するといいかも

Chrome → 開発者ツール → Network → WS
→ Nameが `?i=!`で始まるのを選択
→ Frames 
→ リストタイムラインに切り換えたときに流れてくる`{"type":"api-res:`で始まるDataにエラーが書いてあるかも

または、「ストリーミングを経由したAPIリクエスト」を無効にして
開発者ツール → Network で user-list-timeline を確認したほうが楽かもしれないわ。

**Comment by tamaina** [comment]
詳細なエラーメッセージは後で送る予定でした、遅くなってすみません(´;ω;｀)

0.8131...が当該リクエストなのですが、`{e:{}}`という内容が送られてきているようです(^Д^)

![image](https://user-images.githubusercontent.com/7973572/46406541-dcbfde00-c746-11e8-8f2f-e2694b457455.png)

あと、1コメSS中の"Misskey"タイムラインは正常になりました。謎。

ちなみに、"aqz"のlistIdは`5b213a6f03b3244610a6dd8a`、"Misskey"のlistIdは`5b1a78bf2d60e21281f6fbdc`です。

**Comment by syuilo** [comment]
私もxyzで通知が読み込めないなどの問題が発生しました。エラーはクライアントからは分からず、レスポンスが返ってきていないようです。
何かデータベースに不整合が発生したのかもしれません。

**Comment by tamaina** [comment]
確かにそうかもしれません。  
直ったように見えた"Misskey"リストタイムラインを初期状態から遡ろうとすると`{e:{}}`が返ってきます。

**Comment by tamaina** [comment]
経過報告

https://misskey.xyz/@syuilo が表示されないことがわかりました。  
また、@syuiloが@syuiloにログインできなくなりました。

**Comment by syuilo** [comment]
fixed
