### ISSUE TITLE
Summaly非表示リンク構文`?[]()`では、リンクをホバーでsummalyをポップアップ表示するように

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2811]
# Summary
ちょうどWikipediaの記事リンクやMisskeyのメンションのように、リンク先の詳細をホバーでポップアップ表示するようにしてほしい

通常のリンク構文も非表示リンク構文と同じ扱いにするオプションがあってもいいかもしれない

# Environment
desktop

**Comment by tateisu** [comment]
モバイルには関係ない話だった＞ホバー

**Comment by tamaina** [comment]
Resolved with 892cb44
