### ISSUE TITLE
WebSocketの接続先URLに / を使用しないようにする

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#2833]
#2805 で BREAKING CHANGE を入れるなら、ついでにこれもやりたい。

# Summary
HomeStreamの接続先が`/`になっているが、
`/`はHTML出力用のパスと被っているため、フロントエンド側で制御がしづらい。

例えば、HTMLとストリーミング でProxy先や挙動を変更したりしたい時に
同じパス扱いになってしなまうので区別できなかったりする。

また、Streamのエンドポイントに規則性がないため「Streamへのリクエスト」という単位で分けづらい。
```
/
/hybrid-timeline
/drive
/messaging
/games/reversi
```

できれば`/streaming/...`のような特定のパス以下にまとめるなどしたい。

# Environment

**Comment by syuilo** [comment]
v10で個々のエンドポイントは無くなりひとつのストリームに集約されるので、`/streaming`だけで良さそうですね
