### ISSUE TITLE
ログインダイアログが崩れている

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2842]
# Summary

![image](https://user-images.githubusercontent.com/7973572/46579305-87871380-ca49-11e8-9afd-98bb5eb69593.png)

# Expected Behavior

# Actual Behavior

# Steps to Reproduce
1. ウェルカムページを開く
2. ログイン

# Environment
client 1.0.10090
Firefox, Edge

**Comment by SanMurakami** [comment]
Edge 44、Firefox 70で正常に動作していることを確認

**Comment by syuilo** [comment]
直ってそう
