### ISSUE TITLE
DBでエラーが発生するとAPIが返ってこなくなる

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#2852]
# Summary
APIのリクエスト内で、DBに繋がらない, DBクエリが誤っている などの理由でエラーが発生した場合
サーバー側では例外が発生しているにもかかわらず、クライアントには応答が返ってこなくなる。

DBクエリに限らず、API endpointsで使用されている
`export default (params: any, user: ILocalUser) => new Promise(async (res, rej) => {` 内で
awaitを使用しているコードが全て該当してそう。

ただのasyncにすれば思ったとおりに動きそう
https://github.com/mei23/misskey/commit/69d7d7af08a4d284d54986453ba1fdda2c14b75c

# Expected Behavior
DBエラー時に、APIリクエストが完了しエラーが返る。

# Actual Behavior
DBエラーが発生しても、APIがリクエスト中のままになる。

# Steps to Reproduce
1. アプリ実行
2. mondodをstop
3. notes/showなどAPIクエリ
4. サーバー側ではエラーが出ているが、クライアント側には返ってこないままになる

# Environment
curl => Misskey 9.7.1 などで検証

**Comment by mei23** [comment]
@syuilo Promiseが存在する理由は理解したわ。

`new Promise(async (res, rej) => { }` 内のawaitは厳密には`catch`で守る必要がある。

特に後続処理が必要ないならば`async`でよい
(既存の後続処理がないAPIで、「`async`が少数」「`Promise`が大多数」になっていたので・・・)

という認識でOKでしょうか？

**Comment by syuilo** [comment]
そうですね。
ただ async 方式と Promise 方式が混在しているのもあれなので、全部(後処理が無いやつも)Promiseに統一しようかなと思ったりしてます。

**Comment by mei23** [comment]
なるほど(しんどそうだわ)

**Comment by syuilo** [comment]
何かいいアイデアがあれば...

**Comment by mei23** [comment]
大量にあるDB系のawaitを全部守るのがしんどい気がしたけど
丸ごとtryで囲むとか
Promise直下にあまり処理を書かないようにすればいいだけな気もしたわ。
```ts
export default (params: any, user: ILocalUser) => new Promise((res, rej) => {
	const [ps, psErr] = getParams(meta, params);
	if (psErr) return rej(psErr);

	mainProcess(ps, user).then(r => res(r), e => rej(e));

	postProcess();
});

const mainProcess = async (ps: any, user: ILocalUser) => {
```

**Comment by syuilo** [comment]
なるほど～！

**Comment by syuilo** [comment]
修正されたと思います
