### ISSUE TITLE
インスタンスブロック

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2871]
# Summary
あるインスタンスが閉鎖したとき、善良な運営者は最初は410を出すでしょうが(この場合そのインスタンスとの通信はエラーにならないはずです)、いずれ410すら出さない虚無になると、エラーのキューの数は無限大に発散します。

これを防ぐために、指定したインスタンスとの通信を遮断する機能がほしいです。  
また、この機能は迷惑なインスタンスとの交流を断つことにも役立つでしょう。

# Environment

**Comment by mei23** [comment]
そもそも今はキューなど存在しない？！
8a57f490ceccb6e1e4099cc945fe80fd03906d52

**Comment by tamaina** [comment]
https://github.com/syuilo/misskey/blob/f243ce66e77d2a2eeee08d160b9d764c2d1084d5/src/queue/processors/http/deliver.ts
https://github.com/syuilo/misskey/blob/4b1886990f7de0a1b993b2f3f17c3ee99f78a5ec/src/queue/processors/http/process-inbox.ts
存在してそう

**Comment by syuilo** [comment]
今は無効になってますがそのうち復活することはありそう

**Comment by tamaina** [comment]
related to #3199

**Comment by tamaina** [comment]
インスタンスブロックは、悪意のあるインスタンスからのフォロー攻撃や治安の悪いインスタンスとコミュニケーションを断つことにも役立つ

**Comment by mei23** [comment]
Mastodonでは ドメインブロック (Domain blocks) と呼ばれている機能

**Comment by tamaina** [comment]
名前間違えてた

**Comment by mei23** [comment]
細かくはこうなっている
- Domain block => Silence (公開タイムラインから隠すだけ)
- Domain block => Suspend (いわゆるblock)

![image](https://user-images.githubusercontent.com/30769358/50219459-9fc4c880-03d2-11e9-9222-244fb2dc9fdb.png)

**Comment by ibrokemypie** [comment]
Itd be great to have multiple options for the admin the remove other instances from theirs
1: Defederation, no posts from the admins instance go to the defederated instance, and no posts, reactions, replies etc from the defederated instance reach the admins
2: Block, no interaction (notes, reacts, renotes, replies) from the blocked instance reach the admins instance. outgoing information is unaffected
3: Mute, posts from the muted instance do not show on any timelines except home timelines for local users who have followed users from the muted instance. Users not following users on the muted instance do not see any notes, replies etc from the muted instance.
4: Nsfw, all content from the instance is automatically tagged as nsfw
