### ISSUE TITLE
本文をTwEmojiに

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2872]
# Summary
Apple, Android, Microsoftと各環境ごとに絵文字の表示のされ方が違うため、TwEmojiを利用して統一した方がよいのではないか

…という意見をxyzのLTLで2回ほど見かけたのですがいかがでしょうか。

# Environment

**Comment by syuilo** [comment]
詳細求む

**Comment by tamaina** [comment]
ごめんまって

**Comment by tamaina** [comment]
かいた

**Comment by syuilo** [comment]
絵文字の表示が多少違っても特に問題はなさそうに思えます

**Comment by syuilo** [comment]
Done
