### ISSUE TITLE
おすすめユーザーでフォローするボタンが表示されない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2882]
# Summary

![image](https://user-images.githubusercontent.com/7973572/46730336-d095cc80-ccc2-11e8-8caf-4bd2bd0df137.png)

# Expected Behavior

# Actual Behavior

# Steps to Reproduce
1.
2.
3.

# Environment

**Comment by syuilo** [comment]
see
https://github.com/syuilo/misskey/pull/2828#discussion_r223296551
