### ISSUE TITLE
諸々のリクエストにプロキシを使えるようにする

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#2894]
# Summary

# Environment

**Comment by xps2** [comment]
うちのインスタンスでは、global-tuunel-ngで対応しているけど、
host名にポート番号が含まれてしまって、Mastodonのインスタンスに401返される問題が発生している。
とりあえずは、検証対象にhost外して対処しているけれども…
https://gitlab.com/misskey-tor/misskey/issues/5

**Comment by xps2** [comment]
https://github.com/syuilo/misskey/blob/35f91fa280243b748dd306439d22c081f2e9ad4f/src/remote/activitypub/request.ts#L25
がまだ対応していない

**Comment by xps2** [comment]
e1cc2394 でHostを入れるようになったので、https://github.com/syuilo/misskey/issues/2894#issuecomment-429393224 の問題は解消、global-tunnel-ngで問題なくなりました。
ただ、プロキシを使う場合には、DNSキャッシュされると非常に困るのでその部分は削除してます。
(名前解決はMisskeyではなく、プロキシサーバが行わなければならないので)

**Comment by mei23** [comment]
AP deliverだけが未対応でやりたいけどなかなかできない

Nodeでhttpsリクエストを出す方法はざっと2つ
1. `request` (proxy対応) - AP deliver以外はこれを使用
2. `https` (proxy非対応 (requestより低レイヤで処理)) - AP deliverはこれを使用

APにはHttpSignatureが必要、それに使ってるモジュールが`http-signature`
これがhttps`でRequestオブジェクトを作った後に使用する必要がある

`request`で`http-signature`が使えればいいものの
`request`はRequestオブジェクト生成後に処理を挟むことが出来ない
`request`には`http-signature`モジュールを呼び出す専用の機能があるが
`http-signature`自体の実装が古く少しヘッダを整形する必要があるため、そのまま呼び出して使用することが出来ない。

おそらく`http-signature`が
https://github.com/joyent/node-http-signature/pull/83 をマージしてくれればいいのだが
あまり保守されている様子がなく見込みがない。

対応するには、`http-signature`と`request`を両方forkする必要がある。
または、HTTP CONNECT に対応したProxy Clinetを書く必要がある。

**Comment by mei23** [comment]
AP request Proxy対応できそう

**Comment by acid-chicken** [comment]
Related to https://forum.fedeloper.jp/t/topic/68/5

**Comment by xps2** [comment]
プロキシではなくMisskey側で名前解決したら、Misskey側で名前解決できない場合は疎通不可能になるけどそのあたりはどうしているのだろうか。
そもそもプロキシ使うのは直接外に疎通不可能だったりする場合に使うものなので、名前解決はプロキシでするべきなのだけれど…

**Comment by mei23** [comment]
web-push がProxy使うっぽいわ
