### ISSUE TITLE
isSecure --> isNative

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#29]

**Comment by anatawa12** [comment]
全然情報もないですしstaleとして一旦クローズします

**Comment by saschanaz** [comment]
たぶんこの辺りの話かと（‘secure`と言っていますが実はログイントークンの話）

https://github.com/misskey-dev/misskey/blob/379ce0145b9d0b74334b35fa57f2ef87366388f2/packages/backend/src/server/api/ApiCallService.ts#L294-L296
