### ISSUE TITLE
デッキでユーザーや投稿を選択したときページに遷移しないようにする

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#2930]
設定で

* 今まで通りページ遷移する
* 新しい一時的なカラムを作りそこに表示する
* ウィンドウで表示する

を選択できるようにする

---

進捗

- [x] ユーザー
- [x] 投稿
- [x] ハッシュタグ

**Comment by tamaina** [comment]
カラムではなく、ウィンドウにして中央に表示してほしい

**Comment by tomocrafter** [comment]
TweetDeckのように画面を占領する感じにしてほしいです。
カラムでは情報量が制限されるし、尚且プロフィールを見ながら別のタイムラインを見ることなんてないかと。

**Comment by syuilo** [comment]
TweetDeckというのは使ったことがないので詳しい情報欲しいです

**Comment by syuilo** [comment]
とにかくページ遷移だけは避けたい

**Comment by tamaina** [comment]
TweetDeckはウィンドウと同じ感じ

![image](https://user-images.githubusercontent.com/7973572/47134335-3c8dbb80-d2e7-11e8-8875-4273d8c891fe.png)
![image](https://user-images.githubusercontent.com/7973572/47134345-431c3300-d2e7-11e8-9dfb-7ac661548dd4.png)

**Comment by syuilo** [comment]
@tamaina ありがとうございます🙏

**Comment by tomocrafter** [comment]
BetterTweetDeck使っているので予想してたのはこちらです。
背景が白っぽくなるのは(個人的に)目に悪いので暗くなったほうが好きです。
![image](https://user-images.githubusercontent.com/10905364/47136593-1835dd00-d2ef-11e8-8a55-12cc70aff1e6.png)

**Comment by tamaina** [comment]
背景を暗転させて操作可能にするかどうかは要検討ですね  
私は要らないと思いますが

**Comment by acid-chicken** [comment]
@tomocrafter @tamaina この件に関しては別のIssueに切り離したほうが良さそう。

**Comment by tamaina** [comment]
@acid-chicken そうですね  
まあとにかく"新しい一時的なカラムを作りそこに表示する"だけの実装にされるのは好ましくないと思います。この実装は使い勝手が最悪なので
