### ISSUE TITLE
Option to disable fuckadblock popup

### ISSUE THREAD

**Issue by incognico** [misskey-dev/misskey#2941]
# Summary
Requesting an option to disable fuckadblock popup

Maybe something like "don't show this again" checkbox in the popup or a setting in the options to disable the message. With a properly configured ad blocker its no issue, then the popup is just annoying.

**Comment by ghost** [comment]
I'd back this request frankly, as much as I understand it's usage.

**Comment by tamaina** [comment]
There was some problems caused by adblocker. Therefore, it cannot be guaranteed Misskey to run correctly with adblocker and there is fuckadblock on Misskey.

**Comment by AyaMorisawa** [comment]
fuckadblock popup is completely removed from Misskey.
