### ISSUE TITLE
設定のタブを階層化してほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2944]
# Summary
Misskeyは設定が多い割にはタブが1層しかないため、設定の全体が見通せず不便。  
設定のタブを階層化すれば目的の設定に早く到達できるようになると思う。

# Environment
desktop

**Comment by marihachi** [comment]
グループ分けの粒度が整えば、階層でなくても整理できそう

**Comment by tamaina** [comment]
現状でもカードによって階層化はできているけれど、例えばWebタブはスクロールしないと設定項目にたどり着けない。

カードのタイトルをリンクのリストとして表示するだけでも、例えば、joinmisskey等での操作説明が楽になる

さらに、テーマタブではdetails-summalyをタブにすれば多少ユーザーフレンドリーになりそう

**Comment by syuilo** [comment]
FYI: 新しいUIでは個々の設定ページの中に、さらにタブがあるようなものもある

**Comment by tamaina** [comment]
すみません

逆にわかりにくくなりました……

**Comment by tamaina** [comment]
2年前とはかなり事情は違いそう

**Comment by tamaina** [comment]
あ～、そんなに重大ではないし仕方ない部分が多そうなのでcloseしよう
