### ISSUE TITLE
タイムラインの投稿のフォーカスの解除をクリックでできるように

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2946]
# Summary
選択されている投稿をもう一度クリックすることでフォーカスを解除できるようにしてほしい

# Environment

**Comment by syuilo** [comment]
フォーカスはキーボード操作のためにあるのでわざわざクリックしてフォーカス解除したい場合があるのかしら (ESCキーでフォーカス解除できる)

**Comment by tamaina** [comment]
現状では**クリックしてフォーカスできる**ので、逆もできるほうがいいのでは

**Comment by syuilo** [comment]
投稿外の部分をクリックすることでもフォーカス解除できるのでやっぱり必要性なさそう

**Comment by tamaina** [comment]
Deckは余白が少ないのであまりよくない

**Comment by syuilo** [comment]
なるほど

**Comment by AyaMorisawa** [comment]
@tamaina そもそもフォーカスを解除したい理由ってなんですか？(クリック/キーボード限らず)

**Comment by tamaina** [comment]
@AyaMorisawa フォーカスの枠があると気になるのと、キーボードを誤って押下すると誤操作に至る恐れがあるからですね
