### ISSUE TITLE
モバイルでタイムラインの投稿のフォーカスはなぜ必要？

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2947]
# Summary
フォーカスは機能していないように思えるのですが、このギミックは必要なのでしょうか？

# Environment
mobile

**Comment by syuilo** [comment]
モバイルでもキーボード操作する場合があります。

**Comment by tamaina** [comment]
タップのみの操作では不要ですよね…

**Comment by syuilo** [comment]
はい

**Comment by tamaina** [comment]
キーボードが接続されていない状態で非表示にする、とかは考えていない感じですか？

**Comment by syuilo** [comment]
キーボードが接続されているか否かを判定することが可能ならそのようにしてもいいかもしれません

**Comment by acid-chicken** [comment]
Translations (#2954)
--

<dl><dt><q>モバイルでタイムラインの投稿のフォーカスはなぜ必要？</q></dt><dd>Why we need (a gimmick which can) focus posts on the timeline in mobile?</dd></dl>

<dl><dt><q>フォーカスは機能していないように思えるのですが、このギミックは必要なのでしょうか？</q></dt><dd>It seems that the (gimmick of) focus doesn't work, but is it necessary?</dd></dl>

<dl><dt><q>モバイルでもキーボード操作する場合があります。</q></dt><dd>There might be cases where that uses keyboard operation in mobile.</dd></dl>

<dl><dt><q>タップのみの操作では不要ですよね…</q></dt><dd>But we don't need it in mobile where that uses only touch operation, right?</dd></dl>

<dl><dt><q>はい</q></dt><dd>Yes.</dd></dl>

<dl><dt><q>キーボードが接続されていない状態で非表示にする、とかは考えていない感じですか？</q></dt><dd>
Do you have a plan, like, it's hidden if the state that the keyboard isn't connected?</dd></dl>

<dl><dt><q>キーボードが接続されているか否かを判定することが可能ならそのようにしてもいいかもしれません</q></dt><dd>It would be able to do what you want if we can judge whether the keyboard is connected.</dd></dl>
