### ISSUE TITLE
github-notifierにリプライでissueを建てられる機能

### ISSUE THREAD

**Issue by ha-dai** [misskey-dev/misskey#295]
- ハッシュタグを使うか否か
- タイトルだけか、内容も投稿できるようにするか
    - その場合、どうやって区別するか
- issueを建てたらナンバー或いはURLをリプライ
    - `[number](URL)`が好ましいかも

**Comment by AyaMorisawa** [comment]
* リプライのURLをIssueに含める
* リプライしたアカウントの名前をIssueに含める

**Comment by syuilo** [comment]
GitHub Notifierがこのリポジトリから切り離されました
