### ISSUE TITLE
検索で@user@host形式の文字列を入力した場合そのユーザーをフェッチしてユーザーページに移動する

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#2951]
# Summary

# Environment

**Comment by acid-chicken** [comment]
Translations (#2954)
--

<dl><dt><q>検索で@user@host形式の文字列を入力した場合そのユーザーをフェッチしてユーザーページに移動する</q></dt><dd>When a search (field) got text which is formatted as <code>@user@host</code>, fetch the (specified) user (data), and go to its page.</dd></dl>
