### ISSUE TITLE
画面を一番上までスクロールしてもタイトル通知が残り続ける

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#2958]
# Summary

# Expected Behavior

# Actual Behavior

# Steps to Reproduce
1.
2.
3.

# Environment

**Comment by acid-chicken** [comment]
Translations (#2954)
--

<dl><dt><q>スクロール位置が一番上でないときに来た投稿のタイトル通知について、画面を一番上までスクロールしても通知が残り続ける</q></dt><dd>A notification for the post which comes when the scroll position isn't the top (of the page) still stays after scrolling to the top.</dd></dl>
