### ISSUE TITLE
Consider using Dependabot instead of Greenkeeper

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#2966]
# Summary

I think *[Dependabot](https://dependabot.com/)* is more useful than *[Greenkeeper](https://greenkeeper.io/)*.

* Greenkeeper doesn't support `package-lock.json`, but Dependabot does. So we don't need ignoring `package-lock.json` no longer!
* Dependabot supports automated merging for security-patch update or minor update, if you want.
* Dependabot provides several scores (e.g. compatibility, semantic versioning stability).

**Comment by syuilo** [comment]
Done!
