### ISSUE TITLE
LTLを無効にしているときはLTLをウェルカムページに表示しないようにしてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#2970]

**Comment by mei23** [comment]
→ グローバル → ハイライト fallbackしていくとか
(でもグローバルはモデレーションとか効かないから表に出さないほうがいいかも)

**Comment by syuilo** [comment]
> ローカルタイムラインを無効にしているときはウェルカムページに表示しないようにしてほしい

なぜでしょう

**Comment by mei23** [comment]
LTLをなくしたいという管理者の意図に反する とか？

**Comment by mei23** [comment]
個人的には、登録前に紹介しているタイムラインがいざ登録してみると存在しないのがなんか気になる…

**Comment by syuilo** [comment]
なるほど

**Comment by syuilo** [comment]
グローバルはなんか違う気がするのでハイライトで良さそう

**Comment by tamaina** [comment]
Mastodonみたいに人気ユーザーを表示するのもありかなと、個人的には。

**Comment by tamaina** [comment]
GitHubのバグによりIssueインデックスではOpen扱いになってしまっているのでRecloseします
