### ISSUE TITLE
clean-remote-files 実行後、外部メディアが閲覧できなくなる

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#2991]
恐らく投稿のDBはアップデートされてないため、削除された外部メディアが全部表示できなくなります。
![image](https://user-images.githubusercontent.com/37681609/47345364-80b4fd80-d6e5-11e8-8def-2b4029476519.png)

**Comment by syuilo** [comment]
直リンクに切り替えた方が良いですかね

**Comment by SanMurakami** [comment]
> 直リンクに切り替えた方が良いですかね

そのほうがいいかも

**Comment by mei23** [comment]
リモートメディアの期限切れ削除(リモート用のドライブ容量超過削除時)の
直リンク切り換え自体機能(実装?)しててなさそう
