### ISSUE TITLE
GIF画像の挙動を変える

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#2996]
ユーザーのアバターやアップロードされたGIF画像を
過去1分の投稿やマウスホバーした際にGIF画像のアニメーションを行い
それ以外は最初のフレームだけ描画し軽量化する。

**Comment by mei23** [comment]
まず(アイコンor添付画像問わず)アニメーションGIFを上げられた場合に
static版(アニメーションしない版)を生成したげる機能が必要そう #2175

**Comment by SanMurakami** [comment]
![image](https://user-images.githubusercontent.com/37681609/126028013-4bd10475-94d8-40dc-91e8-660af68ee6b6.png)
ついてた
