### ISSUE TITLE
remove highlight.js

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3003]
# Summary
highlight.jsは[ここ](https://github.com/syuilo/misskey/blob/43b47c4494f3efee4a6c1cc0305dbe406747d3e5/src/client/app/mobile/views/components/drive.file-detail.vue#L149)**のみ**で使われているようだが、これを[これ](https://github.com/syuilo/misskey/blob/43b47c4494f3efee4a6c1cc0305dbe406747d3e5/src/mfm/parse/core/syntax-highlighter.ts)やその派生関数で置き換えることで[highlight.js由来のjs・css](https://github.com/syuilo/misskey/blob/43b47c4494f3efee4a6c1cc0305dbe406747d3e5/src/docs/base.pug#L10-L11)を削減でき、読み込みを少しだけ高速にすることができるようになると思う。

…まあそもそも**exif表示出来てない**っぽいんですけどね。

# Environment
mobile, desktop

**Comment by syuilo** [comment]
highlight.jsはドキュメントのシンタックスハイライトにも使われています。

**Comment by syuilo** [comment]
EXIFについては削除しました
