### ISSUE TITLE
Mastodon 2.6.0-rc2にMisskeyの投稿が届かない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3017]
原因不明

**Comment by ghost** [comment]
https://github.com/tootsuite/mastodon/pull/9116
これで直るらしいという情報がある。

**Comment by tamaina** [comment]
tootsuite/mastodon#9116 は tootsuite/mastodon#9114 と同じだった模様

**Comment by tamaina** [comment]
Misskey側のバグではなかった
