### ISSUE TITLE
投稿フォームに`Ctrl+V`でアップロードした画像に判別しやすい名前を付けてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3023]
# Summary
現状投稿フォームに貼り付けた画像は`image.ext`となりますが、よくこの機能を使うユーザーのドライブ内は`image.ext`ばかりになるので、アップロード日時などを名前にしてほしい

# Environment
desktop

**Comment by acid-chicken** [comment]
可能であれば、テンプレートを設定できるようにしたほうがベターかもしれない。

**Comment by AyaMorisawa** [comment]
Ctrl+V押した時点で名前を付けられるようになってほしい
