### ISSUE TITLE
viaの表示位置を改善する

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#3075]
# Summary
アプリから投稿するとviaが付くことがあるが

デスクトップ/デッキで、名前の表示欄がかなり狭くなってしまう。
![image](https://user-images.githubusercontent.com/30769358/47893728-de91d400-dea1-11e8-87e8-1b28eaaac4d2.png)

デスクトップ/非デッキで、投稿詳細を表示するとvia/mobile等が消えて情報が減ってしまう。
![image](https://user-images.githubusercontent.com/30769358/47893754-05e8a100-dea2-11e8-98f9-7e0b5937f041.png)
↓
![image](https://user-images.githubusercontent.com/30769358/47893791-36303f80-dea2-11e8-9dfe-c5b2154aff86.png)

を改善したい。

# Environment

**Comment by EbiseLutica** [comment]
こういう表示はいかがでしょうか

![image](https://user-images.githubusercontent.com/7106976/48174609-0bcffd80-e34c-11e8-95dd-0de727a11f99.png)

**Comment by syuilo** [comment]
それは投稿詳細ページでの表示でしょうか？

**Comment by EbiseLutica** [comment]
いえ、TLです
投稿詳細も統一したらどうかと

**Comment by syuilo** [comment]
非デッキでのTLでのvia表示は現在のままで特に不便はないので変えないで良いと思ってます
投稿詳細ならそんな感じで良いと思います！

**Comment by syuilo** [comment]
デッキTLもそんな感じで良いかも

**Comment by EbiseLutica** [comment]
デッキと投稿詳細の表示をこんな感じにしておきますね

**Comment by syuilo** [comment]
🙏

**Comment by EbiseLutica** [comment]
順番、どちらが適切でしょうか
![image](https://user-images.githubusercontent.com/7106976/48176060-e2b26b80-e351-11e8-9278-5b002e65df18.png)

**Comment by syuilo** [comment]
前者で良いと思います

**Comment by syuilo** [comment]
Done
