### ISSUE TITLE
Mastodonにカスタム絵文字を伝える

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#3104]
# Summary

# Environment

**Comment by mei23** [comment]
伝わるはずだわ

**Comment by syuilo** [comment]
むむ？なんか伝わってないみたいです

**Comment by syuilo** [comment]
あー、それかもしれません ＞ 50KB制限
ありがとうございました。

**Comment by tamaina** [comment]
Aiちゃん画像は100kbを超えてしまっているようです。

https://misskey.tmin.ml/notes/5bdf166fdba6732df611ab3b
[これ](https://joinmisskey.github.io/files/images/icons/icon.png)は11kb台だからMastodonの各インスタンスで見られますね。
→ https://mstdn.jp/web/statuses/101013712340176401

**Comment by tamaina** [comment]
50kb制限を設けるほうがよさそうです
