### ISSUE TITLE
docker-compose.yml with config and prebuild image?

### ISSUE THREAD

**Issue by pwFoo** [misskey-dev/misskey#3108]
There should be a official docker image in docker hub referenced in docker-compose.yml with config files in volumes ready to start. 

Haven't found a volume / reference for default.yml. No volumes in "web" service.

**Comment by pwFoo** [comment]
Maybe set config parameters by environment variables in docker-compose.yml?

**Comment by khws4v1** [comment]
Misskey uses `.config/default.yml` as its configuration.  
In addition, you need to rebuild to apply configuration to Misskey.

It is impossible to use prebuilt image or set configuration with environment variables unless you change Misskey's source code.
