### ISSUE TITLE
Events / calendar & private groups

### ISSUE THREAD

**Issue by pwFoo** [misskey-dev/misskey#3110]
Two features I miss in most networks (mastodon, pleroma, ...) and isn't integrated with an nice ui in others (hubzilla, friendica).

**events / calendar**
Invite (local?) users to events and filter / show events the current user is invited or public available events.

**private groups**
A way to communicate with teams / department / group of friends by private posts like direct messages, but with a simple ui to set the group as recipient (or mention groups?). A group should be created and users added (by group "owner") and all members should use the group name (?) as contact /mention.

**Comment by AyaMorisawa** [comment]
This issue contains two independent issues. Please refer #3217 and #3218 for the individual issues.

**Comment by pwFoo** [comment]
@AyaMorisawa Thanks!!!
