### ISSUE TITLE
github連携できない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3115]
送ってるコールバックURLが違うらしくてたぶん原因は下の:8089
https://github.com/syuilo/misskey/blob/8646a9c49c708cd502904b450e16b405118312e3/src/server/api/service/github.ts#L125

**Comment by tamaina** [comment]
@acid_chicken

**Comment by tamaina** [comment]
l112も同じだ

**Comment by acid-chicken** [comment]
@tamaina Thank you and I'm sorry!
