### ISSUE TITLE
日本語(やほかの言語)での絵文字サジェスト

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3123]
# Summary
現状絵文字サジェストにおいて、絵文字は英語(英単語)でしか検索できず、英語が堪能でない人にとって絵文字サジェストはほぼ役に立ってなさそう  
英語以外での絵文字サジェストがあると便利

# Environment

**Comment by tateisu** [comment]
絵文字ピッカーを用意した方が良いのでは…

**Comment by tateisu** [comment]
ちなみにSTも最初は入力補完だけだったんですが、ピッカーを開くボタンを用意しろという要望がついて結局ボタンを増やしました

**Comment by tamaina** [comment]
絵文字サジェストが便利な場合もありそう

日本語用辞書で使えそうなのあった  
https://github.com/peaceiris/emoji-ime-dictionary

**Comment by acid-chicken** [comment]
クライアントの総サイズがどエラいことになりそう

**Comment by acid-chicken** [comment]
いや、すでにどエラいか……

**Comment by syuilo** [comment]
OSやIMEで日本語で絵文字サジェストしてくれるのでMisskeyでそこまでする必要なさそう

**Comment by tamaina** [comment]
なるほど

**Comment by tamaina** [comment]
UX的にやっぱりほしい

**Comment by 1STEP621** [comment]
Done in #12855？
