### ISSUE TITLE
configのインスタンス設定を可能な限り管理画面で設定できるようにDBで保存するようにしてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3128]
Configファイルで設定するよりGUIで設定できたほうが、再起動しなくていいし記入ミスの恐れが少ないため管理の難易度が下がると思う

インスタンス設定は、Configファイルへの接続に関する最低限の記述を残して可能な限り管理画面で操作できるようDBで管理してほしい

**Comment by syuilo** [comment]
完了
