### ISSUE TITLE
drive/folders/delete はまだstableではない可能性がある

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/misskey#3139]
# Summary
挙動が変わる可能性があるのではないかと思います

**Comment by syuilo** [comment]
stableです

**Comment by marihachi** [comment]
フォルダ内の中にあるファイルもまとめて削除する、という仕様に変更する可能性はありませんか？

それが即時削除でなくても、キューに積んで時間を掛けて削除するなら可能だと考えます。

**Comment by syuilo** [comment]
そうするようにした場合でも互換性を保つことはできそうです 例えば force フラグを要求するなど
