### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by incognico** [misskey-dev/misskey#3141]
![image](https://user-images.githubusercontent.com/2098066/48058793-a3501780-e1b7-11e8-8412-c8f392afa740.png)

```
/**!
 * Sortable
 * @author	RubaXa   <trash@rubaxa.org>
 * @license MIT
 */
[...][n("fa",{attrs:{icon:["far","trash-alt"]}}),e._v(" キャッシュ")],1),n("section",[n("ui-button",{on:{click:e.clean}},[e._v("クリーンアップ")]),n("div",{staticClass:"none ui info warn"},[n("p",[n("fa",{attrs:{icon:"exclamation-triangle"}}),e._v("Der Cache deines Benutzerkontos (Info, Beiträge, Antworten, Direktnachrichten, Einstellungen), die lokal im Browser gespeichert sind werden gelöscht.
```

Not sure if the infinite loading is because the proxy I'm behind blocks something (very possible) but I also saw this warning in the console. It's because it uses a (german) translation string which includes brackets () who seem to be problematic (Uncaught SyntaxError: Invalid or unexpected token)

**Comment by syuilo** [comment]
Thank you for reporting!
I will fix it asap.
