### ISSUE TITLE
Default language

### ISSUE THREAD

**Issue by incognico** [misskey-dev/misskey#3143]
**See second comment for better solution.**

It would be cool to be able to set the instance language globally to english (for all users - well if they don't override it in options) and for logged out visitors.

Or alternatively be able to set a global instance language and allowed languages (whitelist) which get displayed when the browser sends the language string.

Or even better only allow displaying of languages who have >95% translations available (which currently would be en and jp).

This is because most translations are very incomplete and would display Japanese strings. For example going to missekey with a de-DE browser would pretty much display almost everything in Japanese, but for German (or even all non-Japanese) users English would be at least understandable.

I thought for my instance it would be good if I could set the global language to english but have it displayed in japanese if someone with jp-JP browser visits it. The other languages don't really matter currently.

**Comment by incognico** [comment]
Or just an option that allows to change which language to fallback to if there are no translations available. EN|JP switch. Like lang setting Automatic (Fallback to JP) and Automatic (Fallback to EN).

**Comment by tamaina** [comment]
There is many Japanese people who dislike English, so I don't think make default lang en is the best solution.

**Comment by mei23** [comment]
First of all, Misskey's default(fallback) language is english.
But, non translated part in each language file may appears as japanese.

**Comment by incognico** [comment]
For my instance I just removed the locales who are not >95% translated so it automatically will use English and not the locale with Japanese strings. It's a good workaround.

**Comment by Johann150** [comment]
It is currently implemented so that Misskey tries to use your locale, then fall back to English, and then fall back to Japanese because that is the only locale guaranteed to exist. https://github.com/misskey-dev/misskey/blob/6319dd1bfb5a67945a5f61f254d69cac8df26829/locales/index.js#L61-L64
