### ISSUE TITLE
インスタンスの言語を設定しても /api/v1/instance に反映されない

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#3148]
# Summary
管理者画面の「インスタンスの設定言語」を設定しても /api/v1/instance の languages フィールドに反映されない。/api/meta の langs フィールドには正常に反映される。

# Expected Behavior
* /api/v1/instance の languages フィールドが `["de", "ar"]` になってほしい。

# Actual Behavior
* /api/v1/instance の languages フィールドが `["ja"]` になる。
* /api/meta の langs フィールドは `["de","ar"]` になり、正しい。

# Steps to Reproduce
1. 管理者画面の「インスタンスの対象言語」に「de ar」と入力し、「保存」ボタンを押す。
2. https://7.distsn.org/api/v1/instance をブラウザで開き、JSONを読む。

# Environment
Server: 10.44.0

**Comment by syuilo** [comment]
こちらでは再現できませんでした
キャッシュの関係かも？

**Comment by ghost** [comment]
ところで `default.yml` を書き換えて再起動したところ、`/api/v1/instance` が Internal Server Error になってしまいました。`sudo journalctl -u misskey` のログは以下です。
```
Nov 07 20:49:30 ik1-312-16250 misskey[15856]:   <-- GET /api/v1/instance
Nov 07 20:49:30 ik1-312-16250 misskey[15856]:   xxx GET /api/v1/instance 500 14ms -
Nov 07 20:49:30 ik1-312-16250 misskey[15856]:   TypeError: Cannot read property 'email' of undefined
Nov 07 20:49:30 ik1-312-16250 misskey[15856]:       at router.get (/home/misskey/misskey/built/server/api/mastodon.js:46:44)
Nov 07 20:49:30 ik1-312-16250 misskey[15856]:       at process.internalTickCallback (internal/process/next_tick.js:77:7)
```
管理者画面で「管理者の連絡先」のメールアドレスを設定しても同じです。関係があるのでしょうか？

**Comment by syuilo** [comment]
default.yml にメンテナ情報はどのように設定していましたか？

**Comment by ghost** [comment]
あっ！！！ `NODE_ENV=production npm run clean` したら直りました！！！

**Comment by ghost** [comment]
インスタンスの言語も反映されています！

**Comment by ghost** [comment]
お騒がせしました...
