### ISSUE TITLE
必要のない箇所ではmetaでAdmin用情報を返さないようにする

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#3166]
# Summary
Adminユーザーがmetaを取得する際は常に(/admin以外の場所でも)
(reCAPTCHA/Twitter/GitHubのsecretを含む)Admin用の情報が返ってくるが
必要のない箇所では返さないようにしたい。

通常暗号化はされているが常にばらまきたくもないため。

# Environment

**Comment by tamaina** [comment]
(admin用画面であっても

**Comment by mei23** [comment]
v12では返さなくなってる

**Comment by mei23** [comment]
これ実はアウトだった
