### ISSUE TITLE
アイコン(アバター)画像を常に正方形に切り取るようにしてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3167]
# Summary
アイコン(アバター)画像が正方形でないとその表示に不具合が発生するかもしれないため

# Environment

**Comment by marihachi** [comment]
正方形でないときはそもそも「クロップしない」が無効化されている方が自然だと思います

**Comment by syuilo** [comment]
Edgeはクロップ対応してないのでクロップしない機能を無効化するとまずそう

**Comment by tamaina** [comment]
cropperjs https://fengyuanchen.github.io/cropperjs/ ~~なら~~はEdgeでも使えてい~~そうだし導入も簡単そう~~る

**Comment by tamaina** [comment]
EdgeHTMLもバージョンごとに進歩しているので、Edgeの新しいバージョンでは動く可能性がある(お節介ではあると思いますが)  
(それともライブラリ以外の場所に原因があるのかしら)

**Comment by marihachi** [comment]
せめて対応できるとすれば
### クロップに対応していない環境の場合
クロップ画面を表示せずそのまま設定。
(この場合は残念ながら正方形でない画像が設定される場合があります)
### クロップに対応している環境の場合
クロップ画面を表示して且つ、元が正方形でないときは「クロップしない」を無効化してクロップを強制する。

**Comment by tamaina** [comment]
あとはvue-cropperjsの不具合修正を依頼するとか

**Comment by tamaina** [comment]
https://agontuk.github.io/vue-cropperjs/ デモページでそもそもエラーが出てくるので

**Comment by tamaina** [comment]
またはcropperjsを利用して自前で実装してもいいのかもしれない(vueよくわからないので可能かどうかわかりませんが…)
