### ISSUE TITLE
プロフィールが保存できないユーザーがいる

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#3168]
# Summary

プロフィール保存時にユーザーによっては`isBot: null`で送られて
`{"error":{"code":"INVALID_PARAM","param":"isBot","reason":"must-be-not-null"}}` で保存できない

# Expected Behavior
保存できる

# Actual Behavior
保存できない

# Steps to Reproduce
1. デスクトップでプロフィール保存をする

# Environment
Misskey Desktop / Firefox

**Comment by syuilo** [comment]
直しましたがなぜ`isBot`がnullになることがあるのかは謎
