### ISSUE TITLE
言語ごとにスクリプトを生成するのをやめる

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#3172]
後からクライアントサイドで任意の言語ファイルをサーバーから読み込むようにするとか

**Comment by marihachi** [comment]
cool

**Comment by syuilo** [comment]
言語ごとにスクリプトを生成するのをやめようと思ったのは主にコードの複雑性を下げる目的だったけど、後から言語を読み込むようにする仕組みを作るのもそれはそれでコードが複雑になりそう

**Comment by syuilo** [comment]
例えばファイル読み込みは非同期なのでそれまでメイン処理の開始を待たなければならなかったり、言語ファイルをローカルストレージにキャッシュする仕組みを作ったり、言語切り替えの仕組みを作ったり、キャッシュされた言語ファイルを最新のものに更新する仕組みを作ったり、などなど

**Comment by marihachi** [comment]
言語切替のコストが下がる

**Comment by syuilo** [comment]
スクリプトを複数の言語でビルドするのはメモリが足りなくなったためやむを得ず(？)実装しました
