### ISSUE TITLE
ActivityPub以外のプロトコルでの連合

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3208]
ActivityPub以外で連合を実装すれば、ActivityPub固有の性質によって不可能だった機能が実装できる可能性が広がる。

ただし、プロトコルによって長所と短所があるため(ActivityPubでしかできないこともあるかもしれない)、深く検討して選択していくことが重要だと思う。

有力な案としてはYayaka Protocolが挙げられそう。

**Comment by AyaMorisawa** [comment]
メンテナンスコストが増えそう(率直な気持ち)
