### ISSUE TITLE
サーバーからの新着情報を強制表示する

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3212]
# Summary
misskey.xyzを見ている限りでは、ブロードキャストウィジェットはインスタンスからのお知らせをユーザーに伝達するには不十分なようです。

サーバーからの新着情報を(既読を管理しながら)Misskey起動時に強制表示するようにできれば確実に伝達できると思います。

# Environment

**Comment by tamaina** [comment]
#1884

**Comment by syuilo** [comment]
1884とは若干趣旨が異なっているようです
そしてこのIssueはv12で実装されます

**Comment by EbiseLutica** [comment]
Groundpolis （私のフォーク）でこういうUIを試験実装しています

未読通知があるときのみタイムライン上部に固定表示される仕様です。読んだ後でも依然としてお知らせページで確認できます
https://s3.arkjp.net/misskey/fa1eae1c-70e9-461a-9ace-c99071a6a51d.mp4

とりあえずこの部分だけ抜いたものを後々PR送ります

**Comment by tamaina** [comment]
インジケーターがあるからそれでいいように思えるけど、アップデートのお知らせのように固定表示してもいい感じはある

**Comment by syuilo** [comment]
画面上部にバーのように一行程度のテキストを表示できるようにしようと思う

**Comment by syuilo** [comment]
done
