### ISSUE TITLE
リモートのカスタム絵文字をキャッシュする

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#3214]
# Summary
リモートのカスタム絵文字は現状直リンだが、
添付メディアでやっているのと同じように 取得してローカルでキャッシュするようにする。

# Environment

**Comment by SanMurakami** [comment]
@syuilo これ欲しい

**Comment by SanMurakami** [comment]
今はプロキシという仕組みがあるのでそっちの方がよさそう

**Comment by KisaragiEffective** [comment]
related: #3613 
(ところでこれ生きてますか？実装されてそうな気がする)
