### ISSUE TITLE
特定ユーザーに紐付かないファイルを保存できる機能

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#3215]
# Summary
現状、インスタンスのバナーファイル, カスタム絵文字ファイル などは
別途アップロードしたり特定ユーザーでアップロードしたりしているが、
ドライブの仕組み(DBやオブジェクトストレージ)を利用するなどして
ユーザーに紐付かないインスタンス所有のファイルとして保存できる機能がほしい。

また、#3214 などにも特定ユーザーに紐付かないドライブ領域が必要そう。

# Environment

**Comment by syuilo** [comment]
できるようになりました

**Comment by syuilo** [comment]
v12では、他のインスタンスからコピーした絵文字はこの方法で保存されます
