### ISSUE TITLE
Private groups

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#3218]
> A way to communicate with teams / department / group of friends by private posts like direct messages, but with a simple ui to set the group as recipient (or mention groups?). A group should be created and users added (by group "owner") and all members should use the group name (?) as contact /mention.

_Originally posted by @pwFoo in https://github.com/syuilo/misskey/issues/3110#issue-377169054_

**Comment by acid-chicken** [comment]
How about fedi?

**Comment by syuilo** [comment]
> How about fedi?

coming soon

**Comment by acid-chicken** [comment]
Friendica のアレもあるので可能であれば確認して欲しいです

**Comment by syuilo** [comment]
Friendica のアレって何でしょう

**Comment by acid-chicken** [comment]
w3c/activitypub#328 など
