### ISSUE TITLE
Admin Network traffic graph broken since some versions

### ISSUE THREAD

**Issue by incognico** [misskey-dev/misskey#3232]
Admin Network traffic graph broken.

It used to work, after some updated it still worked but the graph was all flat and now it does not work anymore and both in/out show "?"

OS: FreeBSD

**Comment by incognico** [comment]
![image](https://user-images.githubusercontent.com/2098066/48476423-4a0f6600-e7ff-11e8-9e37-5d82799e9a10.png)
![image](https://user-images.githubusercontent.com/2098066/48476446-5c899f80-e7ff-11e8-928a-9349a1ece382.png)

**Comment by Johann150** [comment]
Since https://github.com/misskey-dev/misskey/pull/8253/commits/ac3354d957be45f45d14275bf3fb11820b30b011 the network chart has been removed.
