### ISSUE TITLE
ロゴや絵などはAGPLではないライセンスにしてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3235]
# Summary
ロゴや絵などの資源はプログラムではないし、GPLは全てに汚染して容易に利用できないため、Creative Commonsなどほかのライセンスを適用してほしい

# Environment

**Comment by ghost** [comment]
派生したソフトウェアに自由を強制するというAGPLのコンセプトを私は支持する。「汚染」は不当な制約ではなく、自由のために必要なものだ。

**Comment by ghost** [comment]
ところで、Creative Commons のどのフレーバーを採用すべきか意見があるだろうか？ 私は CC0 を推したい。よく見られる BY-SA は私には自意識過剰に思える。

**Comment by tamaina** [comment]
何はともあれ、ロゴを利用しただけでソースコードを公開させることは避けたい

joinmisskeyで資源を別ライセンスで公開することで対処しますが良いですか @syuilo

**Comment by tamaina** [comment]
適用するライセンスについては、CC BYあたりがちょうどいいかと思いますがどうでしょう？  
(「Misskey」「Mi」ロゴはそれ自体が著作権表示になり得るので余分な表記は不要)

公開するものに関しては、最初はロゴ(「Misskey」「Mi」)のみで、将来的に"藍"の服装・キャラクター設定を加えたい

**Comment by syuilo** [comment]
それで良さそうです

**Comment by tamaina** [comment]
資源用リポジトリとして [joinmisskey/mk-assets](https://github.com/joinmisskey/mk-assets) を作ったのでこちらでやっていこうと思います
