### ISSUE TITLE
削除された投稿を表示し続けるオプション

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#3246]
ページを再読み込みするまで画面上に残るようにする
削除されたことが分かるように、投稿に「削除済み」と表示するようにする

**Comment by syuilo** [comment]
これを実装したらこの問題が解決しますね
https://github.com/syuilo/misskey/issues/2948

**Comment by AyaMorisawa** [comment]
オプションとして実装した場合は、オプションが無効のとき解決していないので注意
