### ISSUE TITLE
Are there any ways to add translations and apply right now on the local server?

### ISSUE THREAD

**Issue by Never2333** [misskey-dev/misskey#3249]

**Comment by incognico** [comment]
It's best to translate at https://crowdin.com/project/misskey (you can sign in with github). Translations are merged in on almost a daily basis.

**Comment by Never2333** [comment]
Yes I know, but it can not apply very fast. Need to be approved.

**Comment by Never2333** [comment]
By the way, edit I am going to translate file? such as zh-CN.yml?

**Comment by acid-chicken** [comment]
How about self-applying PR patches?

Example:
```
curl -LSs https://github.com/syuilo/misskey/pull/`curl -LSs https://api.github.com/repos/syuilo/misskey/pulls|jq 'map(select(.title=="New Crowdin translations"))|.[].number'|head -n1`.patch|git am
```

**Comment by Never2333** [comment]
[root@izj6cb7o9hu1q9z6pz4jswz misskey]# curl -LSs https://github.com/syuilo/misskey/pull/3250.patch | git am
Applying: New translations ja-JP.yml (Chinese Simplified)
error: patch failed: locales/zh-CN.yml:137
error: locales/zh-CN.yml: patch does not apply
Patch failed at 0001 New translations ja-JP.yml (Chinese Simplified)
The copy of the patch that failed is found in:
   /root/misskey/.git/rebase-apply/patch
When you have resolved this problem, run "git am --resolved".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

Said that...

**Comment by acid-chicken** [comment]
Uh-oh, please retry with these commands.
```
git am --abort
curl -LSs https://github.com/syuilo/misskey/compare/master...develop.patch | git am
curl -LSs https://github.com/syuilo/misskey/pull/`curl -LSs https://api.github.com/repos/syuilo/misskey/pulls | jq 'map(select(.title == "New Crowdin translations"))|.[].number' | head -n1`.patch | git am
```

**Comment by Never2333** [comment]
@syuilo But how to change language?

**Comment by syuilo** [comment]
It will be fixed in the next release. Thank you guys!
