### ISSUE TITLE
自動的な翻訳キャッシュ(LocalStorageのlocaleフィールド)の更新

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3256]
# Summary
バージョンが更新されてもlocaleフィールドは自動的に更新されないようだが(もしかしたらバグ？)、自動的にアップデートするようにしてほしい。

# Environment
Firefox/Chrome on Windows/Android

**Comment by mei23** [comment]
- バージョンが上がってもlocaleが更新されない
- 設定で言語を切り替えてもlocaleが更新されない

みたい、LocalStorageのlocaleを削除しないとダメっぽいわ
