### ISSUE TITLE
言語設定をサーバー側で保存する

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#327]

**Comment by syuilo** [comment]
言語設定を取得するにはサーバーから情報を受け取る必要がありますが、サーバーにアクセスするのはscriptが読み込まれてからなので無理そう

**Comment by AyaMorisawa** [comment]
ユーザーが言語をクライアントで設定できるようにするのは

**Comment by syuilo** [comment]
それはCookieやLocalStorageを用いれば可能ですね

**Comment by AyaMorisawa** [comment]
デフォルトの言語が予め設定してあって後から変更可能みたいな形にするのは

**Comment by syuilo** [comment]
そうする予定です

**Comment by syuilo** [comment]
でもそれをクライアントから知る方法はない

**Comment by syuilo** [comment]
キャッシュするくらいしか

**Comment by acid-chicken** [comment]
Reopened by #3446.
