### ISSUE TITLE
Add visual indication after (remote) following someone

### ISSUE THREAD

**Issue by incognico** [misskey-dev/misskey#3278]
1. Remote follow someone
2. Misskey follow popup opens
3. Click on follow
3.1 The person is followed or the follow is requested but there is no visual indication that it happened, it still shows "+Follow"
3.2 Pressing F5 correctly updates the window and now you see the person is followed and it says "-Unfollow"

Visual indication or reload/update of the follow button should happen right after the click, F5 of the popup windows should not be needed.

**Comment by tamaina** [comment]
なってる（んだけど何故か反映されない時があるような気がする

**Comment by tamaina** [comment]
（というかフォローポップアップがあった時代があるのか
