### ISSUE TITLE
Remote follow?

### ISSUE THREAD

**Issue by incognico** [misskey-dev/misskey#3292]
When browsing foreign misskey instances there is no way to follow people or to interact with their toots?

**Comment by tamaina** [comment]
There is no way to interact with remote notes in original instances (→ #2217  )......but.......remote follow button should be implemented......oh!? why @syuilo deleted "remote follow" button!?

**Comment by tamaina** [comment]
relate to #2518

**Comment by Johann150** [comment]
i think this is also related to #3957
