### ISSUE TITLE
投稿のプレビュー機能

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#330]
主にデバッグ用に

**Comment by syuilo** [comment]
need details

**Comment by AyaMorisawa** [comment]
Misskey Text Analyzerを適用した後どうなるかを表示

**Comment by SanMurakami** [comment]
https://github.com/syuilo/misskey/pull/5207#issuecomment-515415356

**Comment by syuilo** [comment]
前あったように専用のプレビューページを作る可能性はある

**Comment by Johann150** [comment]
I think this was solved by #7596 ?
