### ISSUE TITLE
Embed player whitelist management by instance or user

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#3300]
# Summary

> どうでもいいけどFC2動画のサムネは表示しにゃいようにしてほしい
> [&mdash;](https://misskey.xyz/notes/5befc089b8b3010037cc03d8) [はたすす (@htss)](https://misskey.xyz/@htss)

Whether the embed player whitelist can be managed by instance or user.

https://github.com/syuilo/misskey/blob/35db61f1b4f00640f26d31135b91d42543795825/src/client/app/common/views/components/url-preview.vue#L31-L108

**Comment by mei23** [comment]
ここで言われているサムネイルは、通常のカードに表示されるサムネイルのことで
埋め込みビデオプレイヤーの画面のことではないのではと思います。

なので、埋め込みプレイヤーではなく
URLプレビュー自体を表示するかどうかのオプションやホワイト/ブラックリストが必要なのではと。
