### ISSUE TITLE
そのユーザーが投稿した画像をすべて閲覧注意にするモデレーション機能

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3301]
# Summary
画像に閲覧注意を付けるようにお願いしても付けてくれない人がいるため、モデレーターが強制的に付ける。  
閲覧注意とは違った表現にすると良いと思う(そうでないと閲覧注意を能動的に付けるユーザーが減るし、制裁を受けていることが判別できない)。

# Environment

**Comment by tamaina** [comment]
過去の投稿にさかのぼって閲覧注意を付けられるとなおありがたい

**Comment by tamaina** [comment]
あと、リモートのユーザーに対してお願いすることはあまりできないのでそのためにも必要そう

**Comment by syuilo** [comment]
ロールできたことだしやるか

**Comment by syuilo** [comment]
画像に閲覧注意を付けるようにお願いしても付けてくれない人は凍結でも良いんじゃねと思った
