### ISSUE TITLE
Could you please add Chinese translation?

### ISSUE THREAD

**Issue by Never2333** [misskey-dev/misskey#3304]
@syuilo We finished it just now! Thank you!

**Comment by syuilo** [comment]
Merged! In the next release, the Chinese translations will appear. Thank you for your contributing!!

**Comment by acid-chicken** [comment]
@Never2333 Thank you for your great work!

**Comment by Never2333** [comment]
@syuilo That is awesome! Thank you!

**Comment by Never2333** [comment]
@acid-chicken You are welcome. xD
