### ISSUE TITLE
検索機能が利用できないときはUI上で検索をなかったことにする

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3307]
# Summary
検索機能が利用できなければ、デスクトップでは検索バー、モバイルではメニューから検索の項目を消去してもよさそう

# Environment
client

**Comment by AyaMorisawa** [comment]
elasticsearchが無効でもハッシュタグ検索は可能なので、ハッシュタグ検索のみできることを表示したほうがよさそう

https://github.com/syuilo/misskey/pull/3309#issuecomment-439694102

**Comment by tamaina** [comment]
https://github.com/syuilo/misskey/pull/3309#issuecomment-439694102

**Comment by tamaina** [comment]
語句検索がないときの検索フォームの機能がハッシュタグ検索のみなら"ハッシュタグ検索専用フォーム"にしてしまえばいいけれど、ユーザー検索ができるようになると(なってほしい)説明が長くなったりトグル用のボタンを付けなければならなくなるので、それよりは現状のように語句検索をしたとき語句検索が使えないことを表示した方がUX的に良いはず
