### ISSUE TITLE
Search feature is turned off in the settings for this instance

### ISSUE THREAD

**Issue by oniyakun** [misskey-dev/misskey#3312]
# Summary

It shows up `Search feature is turned off in the settings for this instance` when I tried to search in my instance, but I can't find any settings about search feature.
# Expected Behavior

Search feature should be running
# Actual Behavior

`Search feature is turned off in the settings for this instance`
# Steps to Reproduce
1.Click search box
2.Search something
3.`Search feature is turned off in the settings for this instance`

# Environment

Centos7

Chrome in Windows 10

**Comment by AyaMorisawa** [comment]
You have to setup elasticsearch and enable it in Misskey configuration.

**Comment by oniyakun** [comment]
Is that the only way?

Elasticsearch looks very expensive

**Comment by Johann150** [comment]
Elasticsearch has been made optional a while ago.
