### ISSUE TITLE
ユーザーサジェストが消えない

### ISSUE THREAD

**Issue by ne-moni** [misskey-dev/misskey#3328]
# Summary
PC版モバイル版ページともに投稿時のユーザーサジェストが消えずそのまま残る
参考：[PC版](https://misskey.m544.net/notes/5bf17f192ab25d76b5bafbd0)，[モバイル版](https://misskey.m544.net/notes/5bf2b6dc9153706140ce1487)

# Environment
PC版：Windows 10 Home 1803 / Google Chrome 70.0.3538.102
モバイル版：Android 8.0.0 (SHV40_U) / Chrome 70.0.3538.80

**Comment by tateisu** [comment]
私の場合は絵文字サジェストでしたけど、二つ表示されて、片方は何しても消えない状態に陥ると思います。表示する前に既に既存のポップアップが出ているか確認するべきかなあ

**Comment by mei23** [comment]
ビルド直後など、サジェストのAPIリクエストが遅延すると起きやすい

投稿欄に`@a @b `を入力するとして
1. `@a`まで入力する
2. `@a`のサジェストが上がってくる前に続けて` @b`を入力する
3. `@a`と`@b`の両方のサジェストが上がってしまう
4. その後片方のサジェストは閉じないままになる

**Comment by syuilo** [comment]
おそらく解決しました(再発したらReopenしてください)
