### ISSUE TITLE
数式構文が含まれている投稿がリモートのMisskeyでは表示されない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3329]
# Summary

# Expected Behavior

# Actual Behavior

# Steps to Reproduce
1.
2.
3.

# Environment

**Comment by mei23** [comment]
問題ないはずだわ
構文がかわってるバージョンまたがってるとか？
https://github.com/syuilo/misskey/pull/3280

**Comment by syuilo** [comment]
Misskey同士では投稿内容をHTMLに変換したりせず直接やりとりするため、数式が表示できないといったことはないとお思います。めいめいの言うようにバージョンが異なっていることが原因だと思われます。
引き続き問題が確認できる場合はReopenします。

**Comment by incognico** [comment]
https://www.npmjs.com/package/svgo ?

**Comment by tamaina** [comment]
xyzからリモートに投稿が伝わっていないのを見間違えた

(数式構文のせいではないことは判明したのに、私はなぜこのissueを立てた(閉じ忘れた？)んだろう…)

**Comment by tamaina** [comment]
謎のissueを投稿して本当に申し訳ありませんでした。
