### ISSUE TITLE
JavaScript-free "lite" client

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#3340]
# Issue
Most browsers have javascript. However, some users, especially power users, prefer to disable it. It's absolutely unessential to get a javascript-free client, however it's something that I feel could and probably should be added.

# Proposition
Making a "lite" client using older rendering methods by making the server parse the page directly. I would be willing to get to work on this if the proposition is accepted as I currently have the time to currently work on such a project. I suppose it's a pretty large undertaking. 

I have no idea if this was already proposed, i can't read japanese lol

**Comment by acid-chicken** [comment]
@gutfuckllc Do you have any idea of how to implement a client which won't use JavaScript? I'm interested in that.

**Comment by marihachi** [comment]
@acid-chicken 
思いつくのはこんな方法ですね
- formタグでsubmitとかaタグでページ遷移をしてタイムラインを再取得(ページ全体再取得)
- formタグのsubmitでノートを作成、ページ遷移

UXはかなり乏しくなりそうです。
リアルタイム性に関しては全く無くなってしまうと思います。。

**Comment by incognico** [comment]
Not sure how I feel about that as misskey basically is Javascript only. Maybe when the mastodon compatibility API is complete you could use other front ends by that API?

**Comment by acid-chicken** [comment]
@incognico Yes, but the Mastodon Compatible API won't provide the all of the Misskey features. If we'll make another lite, full compatible with Misskey client, we'll have to use Misskey API.

**Comment by tamaina** [comment]
Mastodon互換であれMisskeyオリジナルであれ、APIを利用するにはJavaScriptで呼び出すことが必要なので、JavaScript-freeを達成できない。

JavaScriptを利用しないWebクライアントとはつまり、Propositionに書かれている通り完全なサーバーサイドレンダリングのクライアントだ。

これはMisskeyクライアントのSPA思想にもちろん逆行する。SPAでないMisskeyは、もはやMisskeyではない(しゅいろがサーバーサイドレンダリングに戻すというのなら別だが)。  
つまり、この提案を実装するなら、一からFediverse実装を作り直した方が良いと思う。

更に言えば、「クライアントからJavaScriptを排除し完全なサーバーサイドクライアントにすれば、それが"lite"である」と言い切ることはできないと思う。

Webサイトにおいて"lite"を実現するには、一般的に、通信量と描画のためのブラウザの計算量を削減しサーバーの応答速度を改良する。サーバーの応答速度の改良にはあまり苦労することはないだろう。しかし、クライアントサイドでは問題が多い。多く移動を行えば、HTMLをやり取りするために通信量が増えるだろう。Misskeyのスクリプトサイズは最近分割され、またサイズも削減されたため、通信量は減っている。ブラウザはURLを移動する度にページを一から描き直す。SPAはその重い描画更新をなくして速やかに表示を更新するという考え方を持つ。もしMisskeyのリッチなUIを大幅に簡素にするならそれはMisskeyではないし、多くの"重い"と感じる挙動はCSSやvueの問題であり、JavaScript自体が悪いわけではない。

今のWeb標準の範囲で言えば、現代的なWebを体験するためには――ことMisskeyのようなサービスに関しては――JavaScriptによるサポートが不可欠だ。JavaScriptには確かに悪いところもあるが、それ以上のメリットがあるし、規格や実装には改良が重ねられている。今必要なのは、JavaScriptを無効にする人に対応してJavaScript-freeクライアントを作成することではなく、そのような人達に対しJavaScriptを有効にさせるよう働きかけることだ。

[English version by Google Translation](https://translate.google.com/#ja/en/Mastodon%E4%BA%92%E6%8F%9B%E3%81%A7%E3%81%82%E3%82%8CMisskey%E3%82%AA%E3%83%AA%E3%82%B8%E3%83%8A%E3%83%AB%E3%81%A7%E3%81%82%E3%82%8C%E3%80%81API%E3%82%92%E5%88%A9%E7%94%A8%E3%81%99%E3%82%8B%E3%81%AB%E3%81%AFJavaScript%E3%81%A7%E5%91%BC%E3%81%B3%E5%87%BA%E3%81%99%E3%81%93%E3%81%A8%E3%81%8C%E5%BF%85%E8%A6%81%E3%81%AA%E3%81%AE%E3%81%A7%E3%80%81JavaScript-free%E3%82%92%E9%81%94%E6%88%90%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84%E3%80%82%0A%0AJavaScript%E3%82%92%E5%88%A9%E7%94%A8%E3%81%97%E3%81%AA%E3%81%84Web%E3%82%AF%E3%83%A9%E3%82%A4%E3%82%A2%E3%83%B3%E3%83%88%E3%81%A8%E3%81%AF%E3%81%A4%E3%81%BE%E3%82%8A%E3%80%81Proposition%E3%81%AB%E6%9B%B8%E3%81%8B%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B%E9%80%9A%E3%82%8A%E5%AE%8C%E5%85%A8%E3%81%AA%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%82%B5%E3%82%A4%E3%83%89%E3%83%AC%E3%83%B3%E3%83%80%E3%83%AA%E3%83%B3%E3%82%B0%E3%81%AE%E3%82%AF%E3%83%A9%E3%82%A4%E3%82%A2%E3%83%B3%E3%83%88%E3%81%A0%E3%80%82%0A%0A%E3%81%93%E3%82%8C%E3%81%AFMisskey%E3%82%AF%E3%83%A9%E3%82%A4%E3%82%A2%E3%83%B3%E3%83%88%E3%81%AESPA%E6%80%9D%E6%83%B3%E3%81%AB%E3%82%82%E3%81%A1%E3%82%8D%E3%82%93%E9%80%86%E8%A1%8C%E3%81%99%E3%82%8B%E3%80%82SPA%E3%81%A7%E3%81%AA%E3%81%84Misskey%E3%81%AF%E3%80%81%E3%82%82%E3%81%AF%E3%82%84Misskey%E3%81%A7%E3%81%AF%E3%81%AA%E3%81%84(%E3%81%97%E3%82%85%E3%81%84%E3%82%8D%E3%81%8C%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%82%B5%E3%82%A4%E3%83%89%E3%83%AC%E3%83%B3%E3%83%80%E3%83%AA%E3%83%B3%E3%82%B0%E3%81%AB%E6%88%BB%E3%81%99%E3%81%A8%E3%81%84%E3%81%86%E3%81%AE%E3%81%AA%E3%82%89%E5%88%A5%E3%81%A0%E3%81%8C)%E3%80%82%0A%E3%81%A4%E3%81%BE%E3%82%8A%E3%80%81%E3%81%93%E3%81%AE%E6%8F%90%E6%A1%88%E3%82%92%E5%AE%9F%E8%A3%85%E3%81%99%E3%82%8B%E3%81%AA%E3%82%89%E3%80%81%E4%B8%80%E3%81%8B%E3%82%89Fediverse%E5%AE%9F%E8%A3%85%E3%82%92%E4%BD%9C%E3%82%8A%E7%9B%B4%E3%81%97%E3%81%9F%E6%96%B9%E3%81%8C%E8%89%AF%E3%81%84%E3%81%A8%E6%80%9D%E3%81%86%E3%80%82%0A%0A%E6%9B%B4%E3%81%AB%E8%A8%80%E3%81%88%E3%81%B0%E3%80%81%E3%80%8C%E3%82%AF%E3%83%A9%E3%82%A4%E3%82%A2%E3%83%B3%E3%83%88%E3%81%8B%E3%82%89JavaScript%E3%82%92%E6%8E%92%E9%99%A4%E3%81%97%E5%AE%8C%E5%85%A8%E3%81%AA%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%82%B5%E3%82%A4%E3%83%89%E3%82%AF%E3%83%A9%E3%82%A4%E3%82%A2%E3%83%B3%E3%83%88%E3%81%AB%E3%81%99%E3%82%8C%E3%81%B0%E3%80%81%E3%81%9D%E3%82%8C%E3%81%8C%22lite%22%E3%81%A7%E3%81%82%E3%82%8B%E3%80%8D%E3%81%A8%E8%A8%80%E3%81%84%E5%88%87%E3%82%8B%E3%81%93%E3%81%A8%E3%81%AF%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84%E3%81%A8%E6%80%9D%E3%81%86%E3%80%82%0A%0AWeb%E3%82%B5%E3%82%A4%E3%83%88%E3%81%AB%E3%81%8A%E3%81%84%E3%81%A6%22lite%22%E3%82%92%E5%AE%9F%E7%8F%BE%E3%81%99%E3%82%8B%E3%81%AB%E3%81%AF%E3%80%81%E4%B8%80%E8%88%AC%E7%9A%84%E3%81%AB%E3%80%81%E9%80%9A%E4%BF%A1%E9%87%8F%E3%81%A8%E6%8F%8F%E7%94%BB%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6%E3%81%AE%E8%A8%88%E7%AE%97%E9%87%8F%E3%82%92%E5%89%8A%E6%B8%9B%E3%81%97%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%81%AE%E5%BF%9C%E7%AD%94%E9%80%9F%E5%BA%A6%E3%82%92%E6%94%B9%E8%89%AF%E3%81%99%E3%82%8B%E3%80%82%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%81%AE%E5%BF%9C%E7%AD%94%E9%80%9F%E5%BA%A6%E3%81%AE%E6%94%B9%E8%89%AF%E3%81%AB%E3%81%AF%E3%81%82%E3%81%BE%E3%82%8A%E8%8B%A6%E5%8A%B4%E3%81%99%E3%82%8B%E3%81%93%E3%81%A8%E3%81%AF%E3%81%AA%E3%81%84%E3%81%A0%E3%82%8D%E3%81%86%E3%80%82%E3%81%97%E3%81%8B%E3%81%97%E3%80%81%E3%82%AF%E3%83%A9%E3%82%A4%E3%82%A2%E3%83%B3%E3%83%88%E3%82%B5%E3%82%A4%E3%83%89%E3%81%A7%E3%81%AF%E5%95%8F%E9%A1%8C%E3%81%8C%E5%A4%9A%E3%81%84%E3%80%82%E5%A4%9A%E3%81%8F%E7%A7%BB%E5%8B%95%E3%82%92%E8%A1%8C%E3%81%88%E3%81%B0%E3%80%81HTML%E3%82%92%E3%82%84%E3%82%8A%E5%8F%96%E3%82%8A%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AB%E9%80%9A%E4%BF%A1%E9%87%8F%E3%81%8C%E5%A2%97%E3%81%88%E3%82%8B%E3%81%A0%E3%82%8D%E3%81%86%E3%80%82Misskey%E3%81%AE%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%88%E3%82%B5%E3%82%A4%E3%82%BA%E3%81%AF%E6%9C%80%E8%BF%91%E5%88%86%E5%89%B2%E3%81%95%E3%82%8C%E3%80%81%E3%81%BE%E3%81%9F%E3%82%B5%E3%82%A4%E3%82%BA%E3%82%82%E5%89%8A%E6%B8%9B%E3%81%95%E3%82%8C%E3%81%9F%E3%81%9F%E3%82%81%E3%80%81%E9%80%9A%E4%BF%A1%E9%87%8F%E3%81%AF%E6%B8%9B%E3%81%A3%E3%81%A6%E3%81%84%E3%82%8B%E3%80%82%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6%E3%81%AFURL%E3%82%92%E7%A7%BB%E5%8B%95%E3%81%99%E3%82%8B%E5%BA%A6%E3%81%AB%E3%83%9A%E3%83%BC%E3%82%B8%E3%82%92%E4%B8%80%E3%81%8B%E3%82%89%E6%8F%8F%E3%81%8D%E7%9B%B4%E3%81%99%E3%80%82SPA%E3%81%AF%E3%81%9D%E3%81%AE%E9%87%8D%E3%81%84%E6%8F%8F%E7%94%BB%E6%9B%B4%E6%96%B0%E3%82%92%E3%81%AA%E3%81%8F%E3%81%97%E3%81%A6%E9%80%9F%E3%82%84%E3%81%8B%E3%81%AB%E8%A1%A8%E7%A4%BA%E3%82%92%E6%9B%B4%E6%96%B0%E3%81%99%E3%82%8B%E3%81%A8%E3%81%84%E3%81%86%E8%80%83%E3%81%88%E6%96%B9%E3%82%92%E6%8C%81%E3%81%A4%E3%80%82%E3%82%82%E3%81%97Misskey%E3%81%AE%E3%83%AA%E3%83%83%E3%83%81%E3%81%AAUI%E3%82%92%E5%A4%A7%E5%B9%85%E3%81%AB%E7%B0%A1%E7%B4%A0%E3%81%AB%E3%81%99%E3%82%8B%E3%81%AA%E3%82%89%E3%81%9D%E3%82%8C%E3%81%AFMisskey%E3%81%A7%E3%81%AF%E3%81%AA%E3%81%84%E3%81%97%E3%80%81%E5%A4%9A%E3%81%8F%E3%81%AE%22%E9%87%8D%E3%81%84%22%E3%81%A8%E6%84%9F%E3%81%98%E3%82%8B%E6%8C%99%E5%8B%95%E3%81%AFCSS%E3%82%84vue%E3%81%AE%E5%95%8F%E9%A1%8C%E3%81%A7%E3%81%82%E3%82%8A%E3%80%81JavaScript%E8%87%AA%E4%BD%93%E3%81%8C%E6%82%AA%E3%81%84%E3%82%8F%E3%81%91%E3%81%A7%E3%81%AF%E3%81%AA%E3%81%84%E3%80%82%0A%0A%E4%BB%8A%E3%81%AEWeb%E6%A8%99%E6%BA%96%E3%81%AE%E7%AF%84%E5%9B%B2%E3%81%A7%E8%A8%80%E3%81%88%E3%81%B0%E3%80%81%E7%8F%BE%E4%BB%A3%E7%9A%84%E3%81%AAWeb%E3%82%92%E4%BD%93%E9%A8%93%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AB%E3%81%AF%E2%80%95%E2%80%95%E3%81%93%E3%81%A8Misskey%E3%81%AE%E3%82%88%E3%81%86%E3%81%AA%E3%82%B5%E3%83%BC%E3%83%93%E3%82%B9%E3%81%AB%E9%96%A2%E3%81%97%E3%81%A6%E3%81%AF%E2%80%95%E2%80%95JavaScript%E3%81%AB%E3%82%88%E3%82%8B%E3%82%B5%E3%83%9D%E3%83%BC%E3%83%88%E3%81%8C%E4%B8%8D%E5%8F%AF%E6%AC%A0%E3%81%A0%E3%80%82JavaScript%E3%81%AB%E3%81%AF%E7%A2%BA%E3%81%8B%E3%81%AB%E6%82%AA%E3%81%84%E3%81%A8%E3%81%93%E3%82%8D%E3%82%82%E3%81%82%E3%82%8B%E3%81%8C%E3%80%81%E3%81%9D%E3%82%8C%E4%BB%A5%E4%B8%8A%E3%81%AE%E3%83%A1%E3%83%AA%E3%83%83%E3%83%88%E3%81%8C%E3%81%82%E3%82%8B%E3%81%97%E3%80%81%E8%A6%8F%E6%A0%BC%E3%82%84%E5%AE%9F%E8%A3%85%E3%81%AB%E3%81%AF%E6%94%B9%E8%89%AF%E3%81%8C%E9%87%8D%E3%81%AD%E3%82%89%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B%E3%80%82%E4%BB%8A%E5%BF%85%E8%A6%81%E3%81%AA%E3%81%AE%E3%81%AF%E3%80%81JavaScript%E3%82%92%E7%84%A1%E5%8A%B9%E3%81%AB%E3%81%99%E3%82%8B%E4%BA%BA%E3%81%AB%E5%AF%BE%E5%BF%9C%E3%81%97%E3%81%A6JavaScript-free%E3%82%AF%E3%83%A9%E3%82%A4%E3%82%A2%E3%83%B3%E3%83%88%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B%E3%81%93%E3%81%A8%E3%81%A7%E3%81%AF%E3%81%AA%E3%81%8F%E3%80%81%E3%81%9D%E3%81%AE%E3%82%88%E3%81%86%E3%81%AA%E4%BA%BA%E9%81%94%E3%81%AB%E5%AF%BE%E3%81%97JavaScript%E3%82%92%E6%9C%89%E5%8A%B9%E3%81%AB%E3%81%95%E3%81%9B%E3%82%8B%E3%82%88%E3%81%86%E5%83%8D%E3%81%8D%E3%81%8B%E3%81%91%E3%82%8B%E3%81%93%E3%81%A8%E3%81%A0%E3%80%82)

**Comment by syuilo** [comment]
@gutfuckllc Thank you for your proposition. I understand your idea, but it's not something we should support officially.

> However, some users, especially power users, prefer to disable it.

I don't think we should spend time on supporting those users. Even if you implement it, we should review, test and maintain your code. We have a lot of other tasks to do.

> I suppose it's a pretty large undertaking.

As you guess, it's too complex. If you truly want to implement it, please create a new client as a third-party application.

> I have no idea if this was already proposed, i can't read japanese lol

lol

----

This comment is co-authored by @AyaMorisawa

**Comment by syuilo** [comment]
Thanks anyway :)
