### ISSUE TITLE
i18n変換ミス(DevTools)

### ISSUE THREAD

**Issue by tearaikazuki** [misskey-dev/misskey#3345]
# Summary

<img width="331" alt="2018-11-20 19 29 41" src="https://user-images.githubusercontent.com/19515213/48767786-d5ef2980-ecfa-11e8-9eaf-7a38a3217f20.png">

# Expected Behavior

# Actual Behavior

# Steps to Reproduce
1.
2.
3.

# Environment

**Comment by incognico** [comment]
There is more: https://github.com/syuilo/misskey/search?q=%25i18n&unscoped_q=%25i18n
