### ISSUE TITLE
変換ミス(通知)

### ISSUE THREAD

**Issue by tearaikazuki** [misskey-dev/misskey#3346]
# Summary

<img width="700" alt="2018-11-20 19 38 23" src="https://user-images.githubusercontent.com/19515213/48768212-eeac0f00-ecfb-11e8-866c-1444cf229de4.png">  

`mark-as-read-all-unread-notes`

# Expected Behavior

# Actual Behavior

# Steps to Reproduce
1.
2.
3.

# Environment

**Comment by AyaMorisawa** [comment]
Fixed in https://github.com/syuilo/misskey/pull/3734
