### ISSUE TITLE
Mastodonアカウント連携

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3358]
# Summary
Twitter, GitHub, Discordに続いてMastodonインスタンスと接続する機能がほしい

# Environment

**Comment by acid-chicken** [comment]
Related to #66

**Comment by 4ioskd** [comment]
See https://github.com/misskey-dev/misskey/issues/66#issuecomment-1042936651
そもそもMastodonサーバーとmisskeyインスタンスが接続できると、様々な問題が生じるのは想像に固くない。

**Comment by tamaina** [comment]
どんな問題ですか？

**Comment by 4ioskd** [comment]
・各マストドンサーバーおよびmisskeyインスタンスは、それら全てが最新リリース版を追従していないので、連携できるアカウントとできないアカウントが発生する
・マストドンのアカウントと連携するためには、マストドン側（オイゲン氏やマストドンのコントリビューター達）との調整が必要になりそう
・そもそもマストドンアカウントとmisskeyを連携する必要性が分からない。マストドンはマストドン、misskeyはmisskeyで良いのでは。

**Comment by tamaina** [comment]
> ・各マストドンサーバーおよびmisskeyインスタンスは、それら全てが最新リリース版を追従していないので、連携できるアカウントとできないアカウントが発生する
> ・マストドンのアカウントと連携するためには、マストドン側（オイゲン氏やマストドンのコントリビューター達）との調整が必要になりそう

認証のシステムはbot用のものを使えばいいのでこのような問題ない

> ・そもそもマストドンアカウントとmisskeyを連携する必要性が分からない。

わかる

**Comment by 4ioskd** [comment]
>そもそもマストドンアカウントとmisskeyを連携する必要性が分からない。
>わかる

closeしてもYOSASOU
