### ISSUE TITLE
The `vips` apk package is needed in the Dockerfile to build the misskey Docker image

### ISSUE THREAD

**Issue by 0x0f0f0f** [misskey-dev/misskey#3360]
# Summary

The Docker image gets compiled but Misskey crashes at runtime because it is searching for libvips.so inside of the Docker container.

Running `echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && apk add vips` inside the Docker container fixed the issue and Misskey started running properly.

# Expected Behavior

The app should build and run normally.

# Actual Behavior

Got a NodeJS runtime error because libvips was missing.

# Steps to Reproduce
1. Clone git repository 
2. Configure App (Following https://github.com/syuilo/misskey/blob/develop/docs/docker.en.md )
3. Run `docker-compose up`

# Environment

Running on Alpine Linux aarch64 host and official Alpine Dockerfile.

**Comment by KisaragiEffective** [comment]
fixed by #7249
