### ISSUE TITLE
Failed to execute operation: Bad message

### ISSUE THREAD

**Issue by Never2333** [misskey-dev/misskey#3363]
When I tried to install Misskey on another VPS, it said that:

--------↓ Build environment--------
[root@host misskey]# NODE_ENV=production npm run build
> misskey@10.56.2 build /root/misskey
> webpack && gulp build
[09:42:36] Finished 'locales' after 5.43 s
[09:42:36] Finished 'build:copy' after 4.41 s
src/index.ts(202,10): error TS6133: 'checkMongoDB' is declared but its value is never read.
TypeScript: 1 semantic error
TypeScript: emit succeeded (with errors)
(a part of npm run build)

--------↓ Tried to enable Misskey--------
[root@host misskey]# systemctl enable misskey
Failed to execute operation: Bad message

The website can open and sign up, but cannot log in.
Could you please help me? Thank you.

**Comment by Johann150** [comment]
Since this issue is for 2 major versions ago, I assume this is outdated.
