### ISSUE TITLE
Dockerでmisskeyインスタンスを建てた際、新規登録フォームが描画されない

### ISSUE THREAD

**Issue by argxentakato** [misskey-dev/misskey#3377]
Dockerで建てたMisskeyインスタンスで新規登録を行おうとしても、以下の画像のようにフォームが描画されないため、新規登録を行うことができません。

![0f9ae286-bb72-40b9-88fd-7890a1d7259a](https://user-images.githubusercontent.com/14871483/48885112-6c8e2880-ee6a-11e8-84b6-2c5009370ed5.png)

様々な人からの助言によると、どうやらデータベース周りの不具合のようです。

**Comment by khws4v1** [comment]
`docker-compose`はサービス名がホスト名になります。
参考: http://docs.docker.jp/compose/networking.html

Misskeyの`docker-compose.yml`はMongoDBを内部のネットワーク(`internal-network`)に接続するようにしているので、`.config/default.yml`に記述しているMongoDBのホスト名を`localhost`**ではなく**`mongo`にする必要があります。

```diff
 mongodb:
-  host: localhost
+  host: mongo
   port: 27017
   db: misskey
   user: example-misskey-user
   pass: example-misskey-pass
```

**Comment by argxentakato** [comment]
すみません、どうやら私の知識不足だったみたいですね…

指事された通りにdocker-compose.ymlを編集したところ、無事に新規登録フォームが表示されるようになりました。ありがとうございます。
