### ISSUE TITLE
「内容を隠す」を使った投稿を引用リノートして削除しても、表示されたままになる

### ISSUE THREAD

**Issue by m-hayabusa** [misskey-dev/misskey#3388]
# Summary

「内容を隠す」を使った投稿を引用リノートして削除すると、内容が隠れない状態で表示されたままになる

# Expected Behavior

(リロードしなくても)表示されなくなるべき

# Actual Behavior

リロードしないと(コメント無しの)リノートとして表示されたままになり、さらに内容が隠れていない

# Steps to Reproduce
1.  「内容を隠す」を有効にしてノートを投稿
2. 1.の投稿を引用リノートする
3. 2.の投稿を削除する

# Environment
v2.0.12036 desktop, mobile

**Comment by tamaina** [comment]
今はさすがに消えるんじゃないかしら…

**Comment by m-hayabusa** [comment]
どこかのタイミングで修正されているので閉じておきます (もはや全て書き替わっているのでは？)
