### ISSUE TITLE
シンタックスハイライトは先頭以外に数字を含むメソッド名を認識できない

### ISSUE THREAD

**Issue by tateisu** [misskey-dev/misskey#3390]
MFMのコードのシンタックスハイライトは、先頭以外に数字を含むメソッド名を認識できずにプロパティの色で表示する

例 obj.method123() 

# Expected Behavior
先頭以外に数字を含む識別子をメソッド名として認識する

**Comment by AyaMorisawa** [comment]
現行のシンタックスハイライトは「お気持ち」程度の能力しか備えていない。

「まともな」パーサーが欲しいなら各プログラミング言語に対応した外部ライブラリに頼るのが無難そう。

**Comment by tateisu** [comment]
これは構造的な限界などではなく、ただ正規表現を少しいじるだけのやつです
