### ISSUE TITLE
アバター/バナークリックで編集が効かなくなっている

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#3396]
# Summary
自分のアバター/バナークリックで編集画面が出てこなくなっている

# Expected Behavior
自分のアバター/バナークリックで編集画面が出てくる

# Actual Behavior
出てこない

# Steps to Reproduce
1. Desktop/ホームで自分のアバター/バナーをクリック

# Environment
Desktop / Firefox

**Comment by acid-chicken** [comment]
Maybe related to #3258
