### ISSUE TITLE
settings birthday field display problem

### ISSUE THREAD

**Issue by pwFoo** [misskey-dev/misskey#3398]
# Summary
birthday field in settings view / text align problem with desktop and mobile

## desktop

![image](https://user-images.githubusercontent.com/333408/48970625-d5aea100-f00e-11e8-8760-84420dcd6501.png)

## mobile 

![image](https://user-images.githubusercontent.com/333408/48970642-15758880-f00f-11e8-9a0b-30ef0749f6d9.png)

**Comment by AyaMorisawa** [comment]
Related to #3162

**Comment by tamaina** [comment]
Related to #3696
