### ISSUE TITLE
オンラインユーザーの表示

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#340]

**Comment by syuilo** [comment]
クライアントはストリームに定期的にメッセージを送って、メッセージが来たら`is_online`フラグを`true`にして、メッセージが来なくなったら`false`にするとか

**Comment by AyaMorisawa** [comment]
メッセージを送る間隔は？

**Comment by syuilo** [comment]
5秒くらい？

**Comment by syuilo** [comment]
もしくはストリームの接続と切断を監視する方法もあるけど、複数接続して来た場合などの対応が厄介

**Comment by syuilo** [comment]
例えば二つのコネクションで接続してきてそれらは次のようなタイムラインだとする
```
(時間 ->)
A: <--------------->
B:           <------------------>
```
1. この場合まずAの接続で`is_online`は`true`になります
2. 次にBの接続でも`is_online`は`true`になります(変わらず)
3. Aの切断で`is_online`は`false`になります
4. 最後に、Bの切断で`is_online`は`false`になります(変わらず)

3の時点ではまだユーザーはオンラインなのにも関わらず`is_online`は`false`になってしまっています

**Comment by syuilo** [comment]
この問題を回避するには、現在確立している接続の数をどこかに記憶しておいて、接続時にそれをインクリメント、切断時にデクリメントし、`is_online`イコール「確立している接続の数>0」とすれば良いです

**Comment by syuilo** [comment]
さっきの例だと

0. カウントは0(`is_online` = `false`)
1. Aの接続でカウントは1になります(`is_online` = `true`)
2. Bの接続でカウントは2になります(`is_online` = `true`)
3. Aの切断でカウントは1になります(`is_online` = `true`)
4. Bの切断でカウントは0になります(`is_online` = `false`)

**Comment by syuilo** [comment]
そのカウントを保持しておくのはデータベース以外には無いのでデータベース

**Comment by AyaMorisawa** [comment]
カウントせずに切断された時点で他に接続があるかを探索するのは？

**Comment by syuilo** [comment]
複数クラスタ(or/andサーバー)があることを考えるとそれは厳しそう

**Comment by syuilo** [comment]
でもそんな機構を実装するより単にポーリング法でやった方が良さそう

**Comment by syuilo** [comment]
FYI: オンラインユーザー数表示は実装した

**Comment by 4ioskd** [comment]
Displaying user online status is solved by this commit https://github.com/misskey-dev/misskey/commit/68571d8f577e0a9eb8679e8dd30e11d8b1709340
Related to #7422
