### ISSUE TITLE
メモリ容量の認識がおかしい

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#3409]
# Summary
![](https://s3.arkjp.net/files/0ace4e81-bf6a-450a-b693-19b79508999a.png)

**Comment by AyaMorisawa** [comment]
ターミナルで
```
export LC_ALL=C; free -b ; unset LC_ALL
```
と入力すると、
```
             total       used       free     shared    buffers     cached
Mem:   1676422348815827468288  936755200   11292672  620691456 8835600384
-/+ buffers/cache: 637117644810393047040
Swap:   1022357504     196608 1022160896
```
と表示される。

**Comment by AyaMorisawa** [comment]
ターミナルで
```
free -g
```
と入力すると、
```
             total       used       free     shared    buffers     cached
Mem:            15         14          1          0          0          8
-/+ buffers/cache:          5          9
Swap:            0          0          0
```
と表示される。

**Comment by AyaMorisawa** [comment]
原因はsysteminformationパッケージであることが判明。

https://github.com/sebhildebrandt/systeminformation/blob/2bf55c48df5fed8aa351c3b5c6d9278c127b8dd1/lib/memory.js#L116-L117

`free -b` の結果の `total` と `used` の値が隣接しているケースが考慮されていない。

**Comment by acid-chicken** [comment]
Should we make a patch for `systeminformation`?

**Comment by AyaMorisawa** [comment]
Misskey開発者がとれる行動:
* 代替パッケージを探す
* `systeminformation` を修正する
* 全て自前で実装する

**Comment by tateisu** [comment]
free -bw でワイド表示するとどうなりますか

**Comment by SanMurakami** [comment]
> free -bw でワイド表示するとどうなりますか

![image](https://user-images.githubusercontent.com/37681609/49019768-0db21180-f1d2-11e8-96f3-70efbbb5b318.png)

**Comment by tateisu** [comment]
RAM 16GBのマシンでBusyBox動かすなんて想定されてなかったんだろうな…

**Comment by SanMurakami** [comment]
じゃあ8GBにしますか

**Comment by tateisu** [comment]
それで直るなら、後はsysteminformationパッケージにissue投げて終わり、でも別に良さそうな気はします

**Comment by acid-chicken** [comment]
The `systeminformation` can't fix this problem.

**Comment by tateisu** [comment]
別に systeminformation 側で /proc/meminfo 読んでもらってもいいので、原理的に不可能という話は全くありません

**Comment by tateisu** [comment]
https://bugs.busybox.net/show_bug.cgi?id=11521

**Comment by AyaMorisawa** [comment]
Misskey側では、Dockerfileの構成を変更することにより解決
