### ISSUE TITLE
アバターとバナーアイコンが未設定になってしまうことがある

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#3421]
# Summary
リモートでアバター画像などが表示されなくなってしまうことがある

DB上でusersコレクションの値が以下になってしまうことがあり
```
avatarId: nullになってしまう
avatarColor: 問題なし
avatarUrl: 問題なし
bannerId: nullになってしまう
bannerColor: 問題なし
bannerUrl: 問題なし
```

これが起きると、avatarIdを元にアバターURLを生成しているActivityPubでiconがnullになってしまう。
そして、画像のキャッシュが切れたタイミングでリモートでアバターが表示されなくなってしまう。

API`i/update`あたりで`avatarId: null`を送ってしまう箇所がある？

# Expected Behavior

# Actual Behavior

# Steps to Reproduce
1.
2.
3.

# Environment

**Comment by mei23** [comment]
ちなみに今
`@syuilo@misskey.xyz`も`@acid_chicken@misskey.xyz`も、外からはアバター未設定の状態になってるわ。

**Comment by acid-chicken** [comment]
https://github.com/syuilo/misskey/blob/9b94ddff0afe75f3a2db991131935e698887384f/src/server/api/endpoints/i/update.ts#L126-L128

を

```ts
if (ps.avatarId) updates.avatarId = ps.avatarId; 
if (ps.bannerId) updates.bannerId = ps.bannerId; 
if (ps.wallpaperId) updates.wallpaperId = ps.wallpaperId;
```

としたほうがいいかもしれないのだわ。

**Comment by mei23** [comment]
いまのところアバター削除自体ちゃんと実装されてなさそう
(`i/update`で`avatarId: null`を指定しても完全に未指定にはできない)なので、
API側でnullを受け取っても何もしないようにするでもいいかも。

**Comment by mei23** [comment]
@acid-chicken profile-editorにアイコンを削除する機能がない→nullを送るはありあえない
なのでとりあえずそれでいいかもだわ
