### ISSUE TITLE
api / admin documentation?

### ISSUE THREAD

**Issue by pwFoo** [misskey-dev/misskey#3422]
Mastodon has a good api / admin / features documentation  and some examples. 

What's about misskey documentation and examples?

**Comment by tamaina** [comment]
There is no one who don't welcome good documents about Misskey. However, developing ones is too time-consuming. We are welcome you to translate and add articles, examples and screenshots on Misskey's 'docs' and joinmosskey wiki.

**Comment by Johann150** [comment]
Please refer to the https://github.com/misskey-dev/misskey-hub repository for checking or creating Misskey documentation.
