### ISSUE TITLE
メモリがもりもりしておる

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#3437]
![image](https://user-images.githubusercontent.com/37681609/49242216-94beee00-f44d-11e8-9a23-05af903b7b5e.png)
![image](https://user-images.githubusercontent.com/37681609/49242248-a1dbdd00-f44d-11e8-8930-21f5222ac232.png)

**Comment by tamaina** [comment]
#1913 ?

**Comment by SanMurakami** [comment]
> #1913 ?

いいえ
実際のメモリ状態と表示が違う

**Comment by acid-chicken** [comment]
> もう一度調べたけど、**node.jsのインスペクタでMisskeyのプロセスを見ると、メモリを120MB使ってると表示されるのに、Linuxのtopコマンドでプロセスのメモリ使用率を見ると1.2GBってなってる**
> 謎
> 
> (ガベコレ発動させても、1.2GBから変化しない)
&mdash; https://github.com/syuilo/misskey/issues/1913#issuecomment-407774998

**Comment by mei23** [comment]
> 実際のメモリ状態と表示が違う

たぶんそれぞれメモリのカウント方法が違うせいです。
Misskey の`Used`は、`Active`というものをカウントしていますが
freeコマンドの出力には直接対応する値がないと思います。

**Comment by khws4v1** [comment]
これもしかしたらsysteminformationパッケージの問題かもしれません。
Misskeyのコードはこうなっていています。
https://github.com/syuilo/misskey/blob/5e0f5c31e72fc5e6af1a96b46052cfb57508d436/src/daemons/server-stats.ts#L57-L66
activeにはbuffers/cacheは含まれない(=ファイルページは含まれない)とあるのですが、なぜか含まれてしまっているようです。
https://www.npmjs.com/package/systeminformation

試しに以下のコマンドでファイルページを開放してみたところ、Misskeyから見えるメモリ使用量が大幅に減りました。
`# echo 1 > /proc/sys/vm/drop_caches`

**Comment by SanMurakami** [comment]
これもうFixでいいと思う
