### ISSUE TITLE
CW指定されてないのに常にCWで隠される場合がある

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#3439]
Pleromaユーザーで起こりやすいみたい

**Comment by tateisu** [comment]
空CWはMisskeyからMastodonに流れて来た時にCWが外れてしまいます。
外部に流すときにCWのままにしたいなら、何かテキストを補う必要があります。

**Comment by mei23** [comment]
ダミーテキスト`U+200B`でも大丈夫っぽい
