### ISSUE TITLE
言語設定をサーバー側で保存する

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3446]
# Summary
クライアントはこれをしても意味がないが、Eメールやプッシュ通知の言語を変更することができる

# Environment

**Comment by AyaMorisawa** [comment]
this reminds me of #327

**Comment by acid-chicken** [comment]
> this reminds me of #327

OK, they have the same title, so I reopened #327.

**Comment by acid-chicken** [comment]
Duplicate of #327
