### ISSUE TITLE
Custom Emojis + Hashtags in post annotations

### ISSUE THREAD

**Issue by incognico** [misskey-dev/misskey#3454]
Custom Emojis or Hashtags in post annotations do not work.

![image](https://user-images.githubusercontent.com/2098066/49318348-76fa9300-f4f8-11e8-8752-412e5389079a.png)

**Comment by incognico** [comment]
Speaking about this, custom emojis are not supported in nicknames too, this works on mastodon appearantly.

Same with the notification panels. 

In nicknames mastodon resizes them to a smaller size too so that it fits the text.

**Comment by incognico** [comment]
For reference:
![image](https://user-images.githubusercontent.com/2098066/49319132-a068ee00-f4fb-11e8-8bef-fd07f087479d.png)
![image](https://user-images.githubusercontent.com/2098066/49319139-ae1e7380-f4fb-11e8-8622-879ed420579d.png)

**Comment by syuilo** [comment]
Related to https://github.com/syuilo/misskey/issues/1826

**Comment by incognico** [comment]
Also custom emojis are not working in Talk with a popped out window.

**Comment by syuilo** [comment]
done
