### ISSUE TITLE
トレンドウィジットが動かない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#3460]
# Summary
![image](https://user-images.githubusercontent.com/30769358/49327809-54748280-f5a9-11e8-875d-b0a643dc5e13.png)

APIリクエストは404だし、新規ユーザーに自動追加もされないウィジットなので
これはもう廃止された？

# Expected Behavior

# Actual Behavior

# Steps to Reproduce
1.
2.
3.

# Environment
Desktop

**Comment by syuilo** [comment]
廃止しようと思います

**Comment by acid-chicken** [comment]
API エンドポイントも死んでるし、さっさと廃止しましょ。
