### ISSUE TITLE
外部ユーザーレコメンデーション使用時にユーザーツールチップが上がってこない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#3461]
# Summary
おすすめユーザーで外部ユーザーレコメンデーションを使用している時に
ローカルエンジンだと上がってくるユーザーのツールチップが上がってこない。

ローカルエンジンだと上がってくるこれが上がってこない
![image](https://user-images.githubusercontent.com/30769358/49328709-8e995080-f5b8-11e8-801a-6a2c7844e700.png)

# Expected Behavior

# Actual Behavior

# Steps to Reproduce
1.
2.
3.

# Environment

**Comment by tamaina** [comment]
仕様かと思ってた

**Comment by mei23** [comment]
あきらめて仕様になってたのかもだわ
