### ISSUE TITLE
引用のURLについて、リモートの投稿を引用した場合、ActivityPubで配信する際は(自インスタンスではなく)オリジナルのURLを挿入する

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3468]
# Summary
おそらく現状の自インスタンスの投稿URLを挿入する仕様は、他インスタンスに対して不親切なため

# Environment

**Comment by mei23** [comment]
NoteのWeb用URL (AP用ではなく) は、AP では`Note.url`になっているぽいが
Misskeyでは保存してないのでまずそれをやる必要あり。

**Comment by mei23** [comment]
AP用のURLでもWeb用にHTMLを出力してくれることが多そうだけど、すべての実装でそうかはわからない。

**Comment by mei23** [comment]
Mastodon / Misskey / Pleroma で見たところ AP用のURLにアクセスしても、Web用のURLにリダイレクトしてくれたりHTMLを提供してくれたりするみたいなので、妥協してAP用URL送るだけでいいかも。
