### ISSUE TITLE
アクティビティ ウィジットがうまいこと動いてなさそう

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#3484]
# Summary
右上 (最古？) が6月で
![image](https://user-images.githubusercontent.com/30769358/49381042-66dfef00-f756-11e8-8e84-9a2615449240.png)

左下 (最新？) が11月ぽいが
![image](https://user-images.githubusercontent.com/30769358/49381064-76f7ce80-f756-11e8-9e1c-2be4725f176a.png)

なんか最近カウントされてなさそう

# Expected Behavior
わからん

# Actual Behavior

# Steps to Reproduce
1.
2.
3.

# Environment

**Comment by u1-liquid** [comment]
カウントされない問題の方はよく分からないけど表示の問題は eb8ef35122e1bab7e9f289f3e6d5d682957f3d98 #5200 で改善されました
日付がごちゃごちゃだったので誤解されたのかも

**Comment by mei23** [comment]
0月開始で、一番下の日付が1列ずつズレてた。
なおってるみたい。
