### ISSUE TITLE
MFM: 斜体構文

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3486]
# Summary
Markdownと同じように`*…*`で斜体にできるようにしてほしい
*斜体*は使わないように思えるが、使う場面はともかく、とりあえず使う人は使うので使えるようにしてほしい

# Environment

**Comment by marihachi** [comment]
`*`って単純であるが故に他のことでも割と使うので、他のパターンにしたほうが良いかも

**Comment by tamaina** [comment]
普通のMarkdownだと ***これ*** ができるけど、MFMだとBigになっちゃいますね

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/49416571-c58c8380-f7bd-11e8-8de9-503d0f34e168.png)

**Comment by marihachi** [comment]
前提としてMarkdownに準拠しようとはしてないと思います
