### ISSUE TITLE
MFMにおけるタグ構文

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#3495]
# Summary

MFM上では

* 完全な木構造が保証され (HTMLではこれが厳密に保証されない)
* タグには属性が付かない

ので、

```html
<name>{{inner}}</name>
```

といった冗長な表記よりも、

```html
<name {{inner}}>
```

といった表記の方が単純で良さそう。

**Comment by acid-chicken** [comment]
TeXなどで見られる `{}` であったり、あるいは `()` や `[]` などでも良さそう。

**Comment by marihachi** [comment]
`()`は文章で普通に使われるね

**Comment by marihachi** [comment]
`**abc**`のように同じ記号を2つ重ねるのは、誤認識を防げるので良い
あ、別に同じ記号じゃなくてもいいか

**Comment by tamaina** [comment]
{{二重波括弧}}のサポートはそこそこポピュラーで良いかもしれない

**Comment by syuilo** [comment]
このIssueと関連するかは不明ですが以前 bbcode なるもののサポートを要望されたことがあります

**Comment by acid-chicken** [comment]
bbcodeは結局冗長であることには変わらなさそう
