### ISSUE TITLE
アバターの固定URL機能

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#350]
ユーザーが自分のサイトなどで自分のアバターを表示するのに役立つ

**Comment by AyaMorisawa** [comment]
どのようなURLに

**Comment by syuilo** [comment]
ふぅ〜む

**Comment by SanMurakami** [comment]
オブジェクトストレージを使うようになった今ではこれは難しそう
（サーバー側とCDNのキャッシュをパージする必要があるので）

**Comment by rinsuki** [comment]
サーバーでリダイレクトするだけでも便利そう

**Comment by SanMurakami** [comment]
> サーバーでリダイレクトするだけでも便利そう

リダイレクトというよりリライト？

**Comment by tamaina** [comment]
/avatar/:userIdじゃだめなの

**Comment by syuilo** [comment]
それだとメンションからユーザーIDを取得するためにフェッチが発生しそう

**Comment by tamaina** [comment]
@:usernameも受け付けるようにすれば（適当）

**Comment by rinsuki** [comment]
というか /avatar/ って生成されたランダムアイコン取る用じゃないんだっけ

**Comment by tamaina** [comment]
現状そうなんだけど、ランダムアイコンはアバター未設定時にしか表示しないので設定されている際は設定されたものを返すようにしてもいいんじゃないかと思った
