### ISSUE TITLE
ハッシュタグのサジェストが投稿フォームの外にある

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#3505]
# Summary
![screenshot_2018-12-05_18-51-59](https://user-images.githubusercontent.com/10798641/49505327-dcff6580-f8be-11e8-9b18-7c2275659097.png)

# Environment
mobile

**Comment by 4ioskd** [comment]
現在は投稿フォームの内側でサジェストがあったはず（間違ってたらすみません）。
