### ISSUE TITLE
MongoDB使いたくない

### ISSUE THREAD

**Issue by n4tkk** [misskey-dev/misskey#3510]
MongoDBはバックアップが難しい(ローカルにとる場合はフルバックアップでしか取れないし、オンラインバックアップを取ろうと思うとクラウド使わないといけない&従量で結構コストかかる。enterpriseライセンス購入してオンプレに置くこともできるけど、コスト的に現実的ではない)

なのでpostgresqlとかmysqlとかoracleとか、mongodb以外のものも使えるようにして欲しい

**Comment by YuzuRyo61** [comment]
Raspberry Piを使ってMisskeyビルドを試みましたが、MongoDB関係で問題が浮き彫りになり
（aptリポジトリが2.6とかで新しいバージョンがなかったり、ビルドが困難だったり等）、
Raspberry PiでMisskey運用は現実的ではないという結論になりました。

ですので、他のデータベースシステムを使えるようにするべきではないかと思います。

**Comment by tamaina** [comment]
Raspberry Piで動作するかどうかを念頭に置いてMisskeyが作られているわけではないので…  
(というかラズパイだと今のMisskeyを運用する上ではスペック不足な気がする)

しかしそれを除いても、MongoDB以外のデータベースを比較して移行を考えることはとても有意義だと私は考えます。

**Comment by acid-chicken** [comment]
> MongoDB関係で問題が浮き彫りになり

APTの問題であって、Misskeyの問題ではないように思いますが。

>  Raspberry PiでMisskey運用は現実的ではないという結論になりました。

Arch Linux上で問題なく動くことが確認されています。
