### ISSUE TITLE
CIでlintを実行する

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#3520]
詳しそうな人 → @acid-chicken

**Comment by acid-chicken** [comment]
Lintの性質上、CircleCIと分離した方が良さそうと判断しました。ある程度できてきたらまた報告します。

**Comment by acid-chicken** [comment]
@syuilo 直接developへpushされることを想定する設計だと工数が増えそうなのでPRオンリーでロックしてもらえたりしませんか。

**Comment by syuilo** [comment]
どうすれば設定できますか？

**Comment by acid-chicken** [comment]
以前かけていたブランチプロテクションでかけられます。ついでにWIPのステータスだけ必須にしてもらえると助かります。

**Comment by syuilo** [comment]
たぶんできました

**Comment by acid-chicken** [comment]
ありがとうございます :pray:

**Comment by syuilo** [comment]
> @syuilo 直接developへpushされることを想定する設計だと工数が増えそうなのでPRオンリーでロックしてもらえたりしませんか。

細かな調整でもブランチ作成+PR+レビューという段階を踏まないといけなくなるとかなり開発のモチベが低下してしまうことがわかったので戻します

**Comment by acid-chicken** [comment]
色々した結果、自作よりも [Codacy](https://www.codacy.com/) を使うのが最適解だろうという結論に至りました。
