### ISSUE TITLE
数式に文法エラーがあるとき、数式のソースをそのまま表示する

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#3524]

**Comment by wasanpuzzl** [comment]
ああ＾〜いいっすね＾〜
コレ関連で既出かもですが、MFM数式構文の\\( と \\) が、
マストドン等の他鯖に送られるときに消えてしまっているのか、
同様の数式構文を持つ鯖 https://mathstodon.xyz/@unknown/101187778420047822
のリプライが https://mathstodon.xyz/api/v1/statuses/101187848477276267
のように認識されるため、ミスキー側では大丈夫ですが一部マストドン側が困るかもと思いました。
この数式構文の↑の鯖だけの問題とも思いますが、はじめましての書き込みテストレベルでスイマセン

**Comment by acid-chicken** [comment]
@shinshuxus ご意見をいただけるのはありがたいですが、一部の方に不快感を与えかねないセンシティブな表現を用いるのはご遠慮下さい。いくらMisskeyの治安がよろしくなかったとしても、ここはGitHubという別のプラットフォーム上です。
