### ISSUE TITLE
[MFM] 数式構文のAP向けHTMLを改善する

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3525]
# Summary
https://github.com/syuilo/misskey/issues/3524#issuecomment-444849236

中身を&lt;code&gt;タグで囲って渡すだけなのは少し雑すぎると思うので改善したほうがよさそう

\\(…\\)を、平文そのままもしくは&lt;span&gt;タグで囲って送信するなど

# Environment

**Comment by mei23** [comment]
数式はもうない
