### ISSUE TITLE
/admin へアクセスすると管理者・モデレーターでなくても管理画面が開けてしまう

### ISSUE THREAD

**Issue by YuzuRyo61** [misskey-dev/misskey#3526]
# Summary
Misskeyのインスタンスで/admin（例：```https://misskey.xyz/admin```）へ行くと管理者・モデレーター権限がなくても管理画面の表示ができてしまう。

# Expected Behavior
管理者・モデレーター権限がないアカウントで/adminへアクセスする。

ただし、一部内容は表示されない。（ブラウザのコンソールでエラーが出ている）

# Environment
- misskey server - yuzulia.xyz : v10.61.0
- node.js(yuzulia.xyz) : v10.14.1
- misskey server - misskey.xyz : v10.62.0
- node.js(misskey.xyz) : v11.3.0

**Comment by acid-chicken** [comment]
現状バグとは言えないような扱いになっています。
FYI: #3331

**Comment by tamaina** [comment]
#2194 ?

**Comment by mei23** [comment]
- 最初のダッシュボードが見れるのはぎりぎり仕様
  (これがどうはかともかく)
- ダッシュボード以外のどうせ動かないメニューが見れるのはバグ
  (管理画面リニューアル前は見れなかった)

という認識だわ

**Comment by CGsama** [comment]
v12 -> e.g. https://misskey.io/admin/security
