### ISSUE TITLE
ハッシュタグの長さを制限する

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3529]
# Summary
あまりに長すぎるタグを作成できてしまうのはよくない

# Environment

**Comment by AyaMorisawa** [comment]
@tamaina 「あまりに長すぎるタグを作成できてしまうのはよくない」と考える理由はなんですか？

**Comment by mei23** [comment]
すでに100文字を超える場合はハッシュタグにしない制御があったみたい
(リンクにはなるが、ハッシュタグとして登録はされないのでハッシュタグ検索等には出てこない)
https://github.com/syuilo/misskey/blob/96571866a3626e823ad3efe82f2ef1e0deba3f26/src/services/note/create.ts#L469-L473

**Comment by tamaina** [comment]
@ayamorisawa
画面設計があまりに長いハッシュタグに対応していないし、する必要もない

あと内部処理的にも良いことはなさそう
