### ISSUE TITLE
日本語だとCWの文字数表示が機能しない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3544]
# Summary
![image](https://s3.arkjp.net/files/0f115c97-493c-4c58-9dcb-95bcf7ffc0c2.png)

# Expected Behavior

# Actual Behavior

# Steps to Reproduce
1.
2.
3.

# Environment
Win 10 Home Build 18290 / Firefox 65.0b2 (64 ビット)

**Comment by mei23** [comment]
そんなことなさそう
![image](https://user-images.githubusercontent.com/30769358/49683597-2217d780-fb0b-11e8-82a9-9af3d417e2cc.png)

**Comment by mei23** [comment]
あ、Chrome 71だめだったわ

**Comment by tamaina** [comment]
なんでアップデートに失敗したんだろう
