### ISSUE TITLE
特定のユーザーからのフォロー申請が承認ができない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3545]
`@aqz@misskey.xyz` が受けた`@vaginaplant@3.distsn.org` からのフォロー申請を承認できない(拒否はできる)

**Comment by mei23** [comment]
これが起きてるかもだわ

Following と FollowRequest 両方にレコードが存在する状態になってしまうことがあり
鍵垢の人がフォローリクエストを受けても承認できなくなってしまうことがあるようです。

- フォロー許可しようとする → Following.insert で duplicate が発生してしまって完了しない
- 申請キャンセルする → FollowRequest レコードを消すだけなので解決しない

でユーザーだけではどうしようもできなくなってしまう。
