### ISSUE TITLE
リモートフォローページでフォロー状態が変わらない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3572]
# Summary
リモートフォローページ(`/authorize-follow?acct=...`)でフォローボタンを押しても、フォロー状態が戻ったように表示される(フォローは完了しているようだ)  
~~また、既にフォローしているユーザーでもフォローされていないような表示になる~~間違いだった

# Expected Behavior
赤く塗りつぶされて「- フォロー中」となる

# Actual Behavior
元に戻って「+ フォロー」と表示されている

# Steps to Reproduce
1. リモートフォローページにアクセス
2. フォローボタンを押下

# Environment
firefox 65.0b2 (64 ビット) win10

**Comment by tamaina** [comment]
こんなページあった？

**Comment by zyoshoka** [comment]
`/authorize-follow?acct=...` 自体はありますけど、この挙動は再現できませんね

**Comment by anatawa12** [comment]
v11 時代は `/authorize-follow` にフォローするボタンがある画面が割り当てられていたが、v12のタイミングで現行のダイアログが出る形に置き換えられたため、該当する挙動が存在しないとしてcloseします。

https://github.com/misskey-dev/misskey/blob/02bde5150e3765b96ac09554bc7ba381f495ba49/src/client/app/mobile/script.ts#L177
https://github.com/misskey-dev/misskey/blob/f6154dc0af1a0d65819e87240f4385f9573095cb/src/client/pages/follow.vue
