### ISSUE TITLE
Discussion: Logo

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#3575]
# Summary

> Misskeyロゴ募集中
[&mdash;](https://misskey.xyz/notes/5c0c998527a9cf002777ed5c) @syuilo

Any proposals are welcome! **Note that one proposal can have one logo only.**

If you find a nice logo proposal, add ":+1:" reaction to the proposal comment.

**Comment by acid-chicken** [comment]
My proposal #<span></span>1

![](https://s3.arkjp.net/files/56ae7587-e3fb-4e08-8e4e-05c1b150aed4.png)

**Comment by acid-chicken** [comment]
My proposal #<span></span>2

![](https://s3.arkjp.net/files/0e708a4f-2ed8-4587-afd8-07d30ffc372e.png)

**Comment by acid-chicken** [comment]
My proposal #<span></span>3

![](https://s3.arkjp.net/files/0c8a8bbc-7d94-414d-a928-6388a594ab55.png)

**Comment by tamaina** [comment]
#1711 は彼に依頼してロゴを作る話、 #3400 は現状のロゴの微弱な修正なので関係なさそう

**Comment by acid-chicken** [comment]
#1711 も同じく新ロゴを作りたいという話であり、また、#3400 でも修正しきれなかった問題が現状のロゴにあることも追ってFYIしたいので関係ないことはない。

**Comment by tamaina** [comment]
文字ベースの横長のものより単純なエンブレムやマークのようなものが必要とされていそう  
結構難しいけど

**Comment by tamaina** [comment]
#3400 は単にデザインの意図していなかったゴミを除去するためのPR。誤解しないでほしい。

**Comment by acid-chicken** [comment]
つまり「デザインの意図していなかったゴミ」はまだ残っていてもそれは問題ないという意味ですか？

**Comment by tamaina** [comment]
まさか直ってない？

**Comment by acid-chicken** [comment]
はい

> Misskeyのyなんかおかしくね？
> ![](https://s3.arkjp.net/files/9e87bfe2-bb49-43b1-86b7-b60a3844e46e.png)
[&mdash;](https://misskey.xyz/notes/5c0c973bd62a640028ebeab6) @acid-chicken

**Comment by tamaina** [comment]
その部分を #3400 で直したとは言っていない。PRの会話を最後まで読めばわかるはず。

**Comment by acid-chicken** [comment]
> 形状がおかしかったのを修正

↓

> 完了した(と思う)

↓

> (merged)

↓

Misskeyのyなんかおかしくね？

**Comment by tamaina** [comment]
もう既に言ったことももう一度言うが、

- 現ロゴについての問題はこのissueとは関係ないので、 #3400 も関係ない
- #3400 はhttps://github.com/syuilo/misskey/pull/3400#issue-233337041で指摘した部分だけを修正する話で、 #3400 は「y」を修正していない。#3400 がもしIssueなら関係あると言えるが、#3400 はPRなのでこれは別の問題。そもそも私は「y」の問題をここで指摘されるまで気づいていなかった。
- 「y」がおかしいのはillustratorの再現のせいではないだろうか。または私が認識していない他のバージョンのファイルではないだろうか。[このファイル](https://raw.githubusercontent.com/joinmisskey/mk-assets/master/icons/misskey.svg)はinkscapeで次のように表示されている。
![image](https://user-images.githubusercontent.com/7973572/49696375-89598880-fbec-11e8-8f73-5b8123f47fd7.png)

- #1711 は「彼が」Misskeyのロゴを作ることが主題。このissueの意図するところとはまったく違う。

**Comment by acid-chicken** [comment]
@tamaina 消しました。オフトピが長くなりすぎているので、日が変わったら一掃してもいいですか。

**Comment by tamaina** [comment]
@acid-chicken 一掃どうぞ
