### ISSUE TITLE
暴れ回るティラノサウルスを配置できる機能

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#3576]
# Summary

# Environment

**Comment by acid-chicken** [comment]
マジレスすると著作権的なアレがあるので、藍ちゃんを汎用3Dデータとしてモデリングして、ティラノサウルスのように暴れ回らせるのが実装方法としては現実的そう。

**Comment by syuilo** [comment]
Implemented

``` md
***<spin alternate><jump><spin left>🦕</spin></jump></spin>***
```

**Comment by acid-chicken** [comment]
ティラノサウルスじゃなくてブロントサウルスを間違って暴れ回らせてしまった。 https://misskey.m544.net/notes/5c52c5bcc9c42454158a188c

**Comment by EbiseLutica** [comment]
上の例は、プラットフォーム依存サウルスになりかねないと思われる

これならtwemojiで問題なくティラノサウルスが暴れるのでは(そもそも初期実装と絵文字が違う)
`***<spin alternate><jump><spin left>🦖</spin></jump></spin>***`

**Comment by mei23** [comment]
🦖 は、絵文字自体が U+1F996 T-Rex = ティラノサウルス
という定義なのでどの環境でも問題ないはず

**Comment by tosuke** [comment]
表示できなくなったしReopenするべきでは

**Comment by tosuke** [comment]
関連 https://github.com/syuilo/misskey/issues/4080
