### ISSUE TITLE
Make video preview better

### ISSUE THREAD

**Issue by incognico** [misskey-dev/misskey#3579]
webm/mp4 currently:
![image](https://user-images.githubusercontent.com/2098066/49703502-25dc5480-fc06-11e8-955b-237a9281c8ee.png)

nsfw currently:
![image](https://user-images.githubusercontent.com/2098066/49703511-31c81680-fc06-11e8-9d47-154ab17f9c80.png)

what about like this for webm/mp4?:
![image](https://user-images.githubusercontent.com/2098066/49703515-3bea1500-fc06-11e8-861b-5b895f4ad32a.png)

**Comment by KisaragiEffective** [comment]
The render result shows that attached video is renderered some background and is not transparent anymore.
Please let us know to re-open this issue if your intention is not that.

![image](https://github.com/misskey-dev/misskey/assets/48310258/98a0f767-d4f8-46f7-918d-57533114597d)
