### ISSUE TITLE
「お探しのページは見つかりませんでした」ページ

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#3581]
マストドンの台パン象が出てくるページみたいに、ないページにはないよ！ってちゃんと表示させたい

藍ちゃがバンバンしてたら可愛いかも:heart:

**Comment by acid-chicken** [comment]
Maybe related to #128

**Comment by syuilo** [comment]
私もこれ実装したいのは山々なんですが、困ってる藍ちゃ(もしくはおっしゃるように台パン)のイラストが無いため実装できずにいます

**Comment by acid-chicken** [comment]
とりあえず仮でいいので404ページぐらいは作りませんか

**Comment by EbiseLutica** [comment]
個人的にねしおさんのこれが
<img src="https://ai.misskey.xyz/aiart/6.jpg" alt="藍ちゃ可愛いよぉぉぉぉぉぉぉぉ" width="320"/>

**Comment by acid-chicken** [comment]
ここをなんとかしたい

https://github.com/syuilo/misskey/blob/653ec0cbb0cb1a14d0f48b4d10b91007e8876be8/src/server/web/index.ts#L121-L127

**Comment by syuilo** [comment]
サーバーサイドは弄らなくて良いんじゃないかしら

**Comment by tateisu** [comment]
マストドンのエラーページのあの台ばんばん、「アニメーションするページを嫌う人」には不評だったりします。光過敏（と書くとポケモンのピカピカみたいなのを想像しますが、英語だと Photosensitive epilepsy で強い光とは限りません）の一種らしいです。
