### ISSUE TITLE
外部インスタンスのカスタム絵文字を管理する機能

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3613]
# Summary

# Environment

**Comment by Johann150** [comment]
Is this already implemented with the current ability to import custom emoji from other instances or were you thinking of something more?

**Comment by KisaragiEffective** [comment]
related: #7717 #13937

**Comment by Sayamame-beans** [comment]
also related: #10857

relatedの3つでカバー出来ていそうなのでCloseします
