### ISSUE TITLE
縦方向に長いノートには「もっと見る」ボタンを付けるオプション

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/misskey#3620]
# Summary
画面を覆うくらいのノートが出ると困る
それが解決できれば良い

**Comment by marihachi** [comment]
デスクトップだけで良いのでやっていってほしいなあ

**Comment by tamaina** [comment]
私の好みとしては、タイムラインをタイムラインとして使いたいので、そこまで長い投稿であればタイムライン上ではなく投稿詳細画面で読むようにして、「続きを読む」などと書いて省略するほうが無難だと思っている

**Comment by marihachi** [comment]
"続きを読む"も良いかもね

**Comment by mei23** [comment]
長い部分の読み込み自体をやめるのはできなくて、隠した上でスクロールバーを出すか出さないかになるので、スクロールバーなくしてもさほど違いがないのではと思う。

> 「続きを読む」

投稿詳細へ行くリンクは既に右上にもあるのでどうするか。これがあると結局スペース増えちゃう。

> タイムラインをタイムラインとして使いたいので

スクロールバーがあるとタイムラインがタイムラインとして使えないという意図がわからない。

**Comment by syuilo** [comment]
デスクトップでもスクロールがネストすると若干使いずらいと思うので、長い投稿は折りたたんで下部に「もっと見る」のような控えめな(見た目的にはリンクのような)ボタンを置いて、それをクリックすることで全部展開されるみたいな感じが良さそうに思いますがどうでしょうか

**Comment by mei23** [comment]
もっと見るの方は難しいように思える

もっと見るボタン: 出すか出さないかを判定するために事前にどのくらいの幅を取るか計算しないといけないはず
(文字幅, 改行, MFM, リンク, URLプレビュー, 引用した他の投稿 ...) などの要素があるので大変

スクロールバー: 表示後にブラウザが出すか出さないかを決めてくれるので簡単

**Comment by marihachi** [comment]
とりあえず、「文字数が一定以上もしくは改行が一定以上」とか簡易的なものでいいと思う

厳密に領域のサイズを計算するのは難しいかもしれないけど、そこまでの精度は必須ではないですよ

**Comment by tamaina** [comment]
@mei23 
- 投稿詳細へのリンクを増やすのは差し引きでスペースが減っているので問題ないと思うんですが
- まあ確かに使えないことはないですが、スクロールでのネストを行うと投稿の羅列という機能性が損なわれると考えています

**Comment by syuilo** [comment]
投稿詳細へのリンクを増やすのはうーん

**Comment by marihachi** [comment]
> デスクトップでもスクロールがネストすると若干使いずらいと思うので

スクロールバーについてはこの問題があるので、ボタンのほうが良いと思う

**Comment by mei23** [comment]
デスクトップブラウザのホイールスクロールは意外と賢くて
サブ領域で一旦静止しないとサブ領域のスクロールには入らないらしく
サブ領域に捕まって全体のスクロールが止まってしまうようなことはなかったわ。

**Comment by mei23** [comment]
モバイルでスクロールがダメな理由はわからないけど
(スクロール領域で画面が埋まると掴む場所がなくなってしまう？)
そうだとしても、左側のアバターの領域は埋まらないのでまだ掴めるはず。
ちょっといじりづらくなるけど、そこはオプションで選ぶ形なのであってもいいのではないかと思う。

**Comment by tamaina** [comment]
返信などの~~note-sub~~note-preview部は全文を見ながら書きたいのでスクロールにするほうが良いと思う

**Comment by mei23** [comment]
スクロールにすると全文は見えない
投稿フォームあげちゃうとスクロールできない

**Comment by syuilo** [comment]
[全文を見る] -> 投稿詳細画面で表示
したい場合がなさそう

**Comment by tamaina** [comment]
[全文を見る] -> その場で展開  
はしたくない

**Comment by tamaina** [comment]
~~note-sub~~note-previewは現状が酷いので改良したいと思っただけです  

> スクロールにすると全文は見えない
> 投稿フォームあげちゃうとスクロールできない

flexレイアウトにすればスクロールで全文見えるし、スクロールできると思っているんですがどうでしょう

**Comment by tamaina** [comment]
note-subじゃなかった、note-previewだった  
ごめんなさい

**Comment by syuilo** [comment]
やってみた
