### ISSUE TITLE
Pluralize strings

### ISSUE THREAD

**Issue by mkljczk** [misskey-dev/misskey#3623]
After i18n refactoring (#3165), #1573 is fixed, so Misskey can start making use of [plural handling](http://kazupon.github.io/vue-i18n/guide/pluralization.html) supported by vue-i18n. Of course, it would also require to make use of string interpolation. I would take care of it, but I don’t have enough time :/

**Comment by AyaMorisawa** [comment]
Related to #329

**Comment by mkljczk** [comment]
I can implement it if I’d find some time

**Comment by 4ioskd** [comment]
Robflop commented below
See https://github.com/misskey-dev/misskey/issues/329#issuecomment-1040592758
