### ISSUE TITLE
デッキのカラム幅が変化したとき、全体を再描画するかメディアビューの高さを計算し直す

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3633]
# Summary
メディアビューの高さはjavascriptで計算してpx数を決めているため、デッキのカラム幅が狭まったときに以下の画像のように突き出してしまう

![image](https://user-images.githubusercontent.com/7973572/50052043-ea3f0e80-0160-11e9-8e38-6a85c3d0b09c.png)

# Environment

**Comment by syuilo** [comment]
ちなみにSafariのバグのためにそうしています

**Comment by tamaina** [comment]
@acid-chicken それはSafariではバグらないの?

**Comment by acid-chicken** [comment]
ツイキャス（縦横比情報と実際のサイズが違うのが原因：#2610）以外では現状そういったものは確認されていない。

**Comment by tamaina** [comment]
中身がGridレイアウトだとバグるみたいなのはあるかもしれないし、一度試してみないとわからなさそう

**Comment by tamaina** [comment]
これってどうなんだろ

**Comment by acid-chicken** [comment]
~~CSS Containment 使ったらもはや起こり得ないのではと思ってるけどどう~~ 別の話と勘違いしてた

**Comment by acid-chicken** [comment]
閑話休題、現在は [`aspect-ratio`](https://caniuse.com/mdn-css_properties_aspect-ratio) が使えるから CSS でシンプルに完結できそう

**Comment by tamaina** [comment]
解決済み

**Comment by tamaina** [comment]
新しい計算については https://github.com/misskey-dev/misskey/issues/11004 あたりで
