### ISSUE TITLE
URLプレビューが返ってこないURLがある

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#3642]
# Summary
URLプレビュー `/url` で`https://www.aozora.gr.jp/` のURLを指定すると
応答が返ってこなくてプレビューができない。

例) https://misskey.xyz/notes/5c171a0c564d450028e24232

# Expected Behavior
応答が返ってくる

# Actual Behavior
返ってこない

# Steps to Reproduce
1. URLを投稿する

# Environment
Windows 10 / Firefox 64
Windows 10 / Chrome 71

**Comment by acid-chicken** [comment]
多分プレビュー先のサイトがContent-Typeを返してないのが原因

**Comment by mei23** [comment]
返してるぽい

**Comment by acid-chicken** [comment]
返ってきました、すみません

**Comment by mei23** [comment]
今はできるみたい、再現手順も忘れたのでClose
