### ISSUE TITLE
リストを正しく表示できない

### ISSUE THREAD

**Issue by Raclett3** [misskey-dev/misskey#3647]
# Summary
リストを選択しても404が表示されます。

# Expected Behavior
リストは表示されるべきです。

# Actual Behavior
リストの選択は私に404を取得させます。

# Steps to Reproduce
1. 右上からリストを選択します
2. リストの一覧から一つ選択します。
3. 404が見られます。

# Environment
Google Chrome最新版で発生しています。

**Comment by syuilo** [comment]
ありがとうございます。
このIssueと同一でしょうか https://github.com/syuilo/misskey/issues/3291

**Comment by Raclett3** [comment]
そうですね、おそらく404が表示されるようになって動作が変わっただけかと思います。
