### ISSUE TITLE
Add as Admin

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3651]
Hey, I just set up an instance following the guide and made an account on it, the first account, however I dont seem to be admin, or if I am, I cant find out how to do anything. How does making announcements work? And how can I had some instance information/rules?

**Comment by acid-chicken** [comment]
Please try these steps.

1. Execute `node cli/mark-admin.js your_username` at the root directory of your misskey sources.
2. Open <https://your.instance.domain.example.com/admin>.
