### ISSUE TITLE
フォローできないMisskeyインスタンスがある

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#3656]
boopsnoot.gq

このインスタンスからフォローできないしこのインスタンスのユーザーを他のインスタンスからフォローできない(ユーザー情報の取得はできる)

**Comment by mei23** [comment]
たぶん https://github.com/syuilo/misskey/issues/3653 の `signature verification failed`のせい。
ProxyでHostヘッダなんかを書き換えてしまってHTTP Signatureの検証エラーになっているとか。

**Comment by syuilo** [comment]
なるほど。ありがとうございます！
