### ISSUE TITLE
Sort options on drive page of admin are in japanese

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3664]
# Summary
Sort options on drive page of admin are in japanese

# Expected Behavior

Sort options in english

# Actual Behavior

![](https://user-images.githubusercontent.com/7827846/50167229-d6e89a80-033c-11e9-895e-dcc9822bfbb9.png)

**Comment by syuilo** [comment]
It is simply untranslated, not a bug. Please wait until translation is added by translator. Thanks anyway :)
