### ISSUE TITLE
Clicking User Links from Pleroma Leads to  User Json

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3665]
# Summary
Not sure whether this is a bug with pleroma or with misskey, though I assume misskey as it works fine on both pleroma and mastodon.
When you click this button
<img width="47" alt="image" src="https://user-images.githubusercontent.com/7827846/50168208-fb457680-033e-11e9-9a27-b0524f457376.png">
on the profile of a misskey user, from pleromafe, it leads to instanceurl/users/userid which prompts the browser to download the user's json, rather that leading to instanceurl/username which would show their profile

# Expected Behavior

direct to instanceurl/@username

# Actual Behavior

direct to a json download at instanceurl/users/userid

# Steps to Reproduce
1. Find a misskey user on pleroma
2. Open their profile
3. Click the external link button

# Environment

firefox, macos

**Comment by mei23** [comment]
日本語でごめんなさい

現在、User (ActiviyPub Person) として2種類のURLを提示していて
```
id: 'https://example.com/users/ObjectID', # For ActiviyPub application/activity+json
url: 'https://example.com/@USER', # For Web text/html
```
PleromaがWeb参照時に2番めのURLを優先して使ってくれれば解決で、
MastodonでもたぶんそれをしてるのでPleromaにそうしてもらうのが一番手っ取り早いと思います。

**Redirectについて**

確かに、Mastodonでは`id`にアクセスした際に、Accpetヘッダを見てWeb用ならば`url`の方にRedirectしてくれるのですが、これはCDN等のCache機構を考慮するとすんなり実装してしまうのは難しいです。

AcceptヘッダによってRedirectを行うと、同一URIで違うコンテンツ(Redirect or JSON)を返すことになるのですが、これをCDN等のCacheを通した際に正しく動作させるには、CDNがAcceptヘッダによってCacheを分けてくれる必要があります。

一応ResponseのVaryヘッダによってキャッシュを分けるという規格はあって、MisskeyもVaryヘッダを正確に返してはいるのですが、必ずしもCDNがVaryヘッダによってキャッシュを分けてくれる保証はないので、すんなりリダイレクトを実装できないところです。

- MisskeyインスタンスはCDNを使っているところが多い。
- Mastodon => Misskey で起きる問題 #2734 があるのでキャッシュ出来ることを捨てにくい。

といった事情もあります。

**Comment by mei23** [comment]
> Mastodon => Misskey で起きる問題 #2734 があるのでキャッシュ出来ることを捨てにくい。

だいぶ改善しているので対応しても大丈夫かも
