### ISSUE TITLE
Instance Silence

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3672]
# Summary

there are many instances that are undesirable to have on the main timelines for reasons such as going against the rules of your instance or refusing to cw nsfw content. Pleroma and Mastodon allow you to silence instances, preventing them from showing in any timelines to anyone except people who have explicitly followed them.
The both deals with noxious instances in the timeline as well as gets around censorship worries as they are still accessible by people who want to access them.

**Comment by mei23** [comment]
- The **admin** can silence specific instances.
- The note of silenced instance will not appear in **local/global/hashtag** timelines.

という仕様

![image](https://user-images.githubusercontent.com/30769358/50219071-5aec6200-03d1-11e9-91d7-36eefa0ce8e7.png)

**Comment by mei23** [comment]
Related server-side instance moderation
Instance bloking #2871

**Comment by kakkokari-gtyih** [comment]
Done in #12031
