### ISSUE TITLE
公開RSSフィードが欲しい

### ISSUE THREAD

**Issue by ne-moni** [misskey-dev/misskey#3689]
# Summary
具体的にはmstdnにあるatomフィードのようなものが欲しい
( https://[インスタンス名]/@[ユーザー名].atom でアクセスできる)

これを活用してIFTTT等で利用したい

**Comment by syuilo** [comment]
Maybe related to 
https://github.com/syuilo/misskey/issues/1509

**Comment by ne-moni** [comment]
あったんですね…了解です
