### ISSUE TITLE
Created Notes Dont Reach Pleroma Instances

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3690]
# Summary

Console often outputs ``500 Internal Server Error`` for a growing number of pleroma instances

# Expected Behavior

No error

# Actual Behavior

<img width="670" alt="image" src="https://user-images.githubusercontent.com/7827846/50262828-2e832500-0467-11e9-9e10-8f171d385d62.png">

# Steps to Reproduce
1. Follow people on pleroma instances
2. Have people on pleroma instances follow you
3. Post (not sure, maybe when they post, or maybe just random?)

# Environment

misskey console log

**Comment by ibrokemypie** [comment]
Seems to occur every time I post with an error for each person on a pleroma instance that follows me

**Comment by ibrokemypie** [comment]
I think this is causing posts to not show up on pleroma instance timelines unless they are tagging people.

**Comment by mei23** [comment]
> why isn't misskey using the sharedinbox?

Probably a bug, thanks. #3709

Misskey does not use`acct:`as the keyId now.

**Comment by mei23** [comment]
Oct 14 ～ Nov 19 の間のどこからか動かなくなっている

**Comment by kaniini** [comment]
Federation between misskey.xyz and pleroma.site seems to be operating normally.

Could you try to send me a message from your misskey instance to @kaniini@pleroma.dereferenced.org?  I have logging enabled, so if there is a failure it will tell us what is wrong with the AP message.

**Comment by ibrokemypie** [comment]
> Federation between misskey.xyz and pleroma.site seems to be operating normally.
> 
> Could you try to send me a message from your misskey instance to @[kaniini@pleroma.dereferenced.org](mailto:kaniini@pleroma.dereferenced.org)? I have logging enabled, so if there is a failure it will tell us what is wrong with the AP message.

have done, however it seems that messages that mention users work relatively normally
ie: they show up on pleroma feeds
it is the notes that dont mention users that dont work, eg if you were to follow me and then I made a note without any mentions

creating that note made all the usual errors for each of my followers but not for you

**Comment by kaniini** [comment]
Okay.  What is your user@domain?  I'll follow.

**Comment by ibrokemypie** [comment]
@ibrokemypie@boopsnoot.gq

**Comment by ibrokemypie** [comment]
there we go, just posted "test message" and you got the error too
<img width="802" alt="image" src="https://user-images.githubusercontent.com/7827846/50344350-bdcf2c00-057e-11e9-9049-6444ffd6f605.png">

**Comment by kaniini** [comment]
Send me another test message please.

**Comment by kaniini** [comment]
Okay, going to enable some more debug, stand by... I suspect this has to do with not properly respecting sharedInbox though.

**Comment by kaniini** [comment]
Please send a new test message...

**Comment by kaniini** [comment]
So basically once #3709 is fixed, this issue will also be fixed.  Best of luck.

**Comment by syuilo** [comment]
Fixed. Thank you guys!

**Comment by mei23** [comment]
It will take up to 24 hours to be repaired after the update.
