### ISSUE TITLE
リスト詳細を開いて閉じた後に別のリスト詳細が開けない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#3692]
# Summary
リスト詳細 (ユーザーがならんでいるウィンドウ) を開いて閉じた後に
リストから詳細を開くができなくなる

# Expected Behavior
詳細が開ける

# Actual Behavior
開けない

# Steps to Reproduce
1. リストを2つ以上作成しておく
2. 設定→リストでリストウィンドウを表示する
3. 一覧からどれかリストを選択して詳細ウィンドウを開く
4. 開いた詳細ウィンドウを閉じる
5. リストウィンドウでどれかのリストを選択しても詳細が開けない

# Environment
Windows 10 / Desktop / Firefox 64
Windows 10 / Desktop / Chrome 71

**Comment by syuilo** [comment]
Fixed
