### ISSUE TITLE
"Birthday" Overlaps the Date Picker

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3696]
# Summary

<img width="426" alt="image" src="https://user-images.githubusercontent.com/7827846/50271456-ea088100-0488-11e9-8bb8-700a67c47955.png">
the label overlaps the date picker

# Expected Behavior

Both are readable

# Environment

firefox, macos

**Comment by tamaina** [comment]
いくつか同じ内容のissueが立っていたような気がする
