### ISSUE TITLE
Some Users Never Show Posts

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3702]
# Summary

I followed this user yesterady (https://mastodon.social/@TootTime), which posts ever hour, however the posts never show in the timeline and the user's page on my instance (https://boopsnoot.gq/@TootTime@mastodon.social) also shows no posts

# Expected Behavior

Posts show on user page and timelines

# Actual Behavior

No posts shown annywhere

# Steps to Reproduce
1. Follow user
2. Wait

# Environment

macos,firefox

**Comment by mei23** [comment]
It seems to be solved now.
May take up to 24 hours after fix nginx configuration.
(By account information cache of the remote instance)
