### ISSUE TITLE
Cannot Sign Out

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3707]
# Summary

When using two browsers, it is impossible to sing out on one.

# Expected Behavior

Sign out on second browser when clicking the log out button

# Actual Behavior

Logs out, goes to welcome screen, then refreshes and is logged back in

# Steps to Reproduce
1. Log in on firefox
2. Log in on chrome
3. Attempt to log out on chrome

# Environment

Firefox and Google Chrome on macOS

**Comment by tateisu** [comment]
モバイルのChromeではクッキーを個別に削除できないので深刻

**Comment by Johann150** [comment]
I can not reproduce this issue in Firefox or Edge with Misskey 12.103.1. I assume it was fixed.
