### ISSUE TITLE
Option to show replies in timelines

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3712]
# Summary

Currently it seems that replies do not show in the global timeline and there is no option for them to do so. It would be helpful and appreciated to have a toggle to be able to see them in the global timeline, as without that you miss conversations that are not on your local instance unless you follow all people involved.

**Comment by ibrokemypie** [comment]
i think this is actually a backend/api change rather than front end as it occurs in apps too such as subwaytooter

**Comment by ibrokemypie** [comment]
eg.
![image](https://user-images.githubusercontent.com/7827846/50642018-085c9980-0fbe-11e9-8be4-64860107e635.png)


applicable for each timeline

**Comment by rrrakyah** [comment]
Have there been any updates on this? This is something that has been bothering me for a while now. Is it somehow possible now to see everyones replies to notes as seperate notes on the timeline?

**Comment by Johann150** [comment]
You can use an antenna showing all notes from users you follow and enable "include replies" to achieve similar behaviour for the home timeline.

**Comment by ghost** [comment]
the antenna workaround is very annoying if you have a proxy account set, and there doesn't seem to be a way to remove proxy accounts. i hope this gets added soon.
