### ISSUE TITLE
モバイルで絵文字のサジェストが更新されない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3726]
# Summary
モバイルでテキストを入力しても絵文字サジェストがカスタム絵文字を一覧したまま更新されない

コンソールにエラーなどは特にみあたらない  
「モバイル」で「絵文字」のサジェストという条件だけで発生するみたい

# Expected Behavior
入力するとその文字列に適合した絵文字が表示される

# Actual Behavior
カスタム絵文字の一覧を表示したまま変わらない

# Steps to Reproduce
misskey.xyzで新規投稿フォームを開いて

1. :
2. a
3. i

# Environment
Firefox Beta latest & Chrome latest on Android 8.0.0

**Comment by tamaina** [comment]
英語苦手だから許して

**Comment by AyaMorisawa** [comment]
> 「モバイル」で「絵文字」のサジェストという条件だけで発生するみたい

@tamaina モバイルでユーザーのサジェストは更新されるということですか？

**Comment by tamaina** [comment]
@AyaMorisawa そうです

**Comment by syuilo** [comment]
iOSで確認したみたところ再現できませんでした

**Comment by AyaMorisawa** [comment]
環境固有の問題である可能性が高そうですね。

@aqz Environmentの欄のバージョンは`latest`ではなく、絶対的なバージョン文字列を書いてくださると嬉しいです。それと、IMEなど関連しそうなソフトウェアの情報を提供してくださると解決に役立つかもしれません。

**Comment by tamaina** [comment]
環境固有の問題そうですね  
Firefoxのレスポンシブデザインモードでは正常に動作しました

**Comment by tamaina** [comment]
ブラウザは自動更新されるのでバージョンはlatestと書いても変わりないように思うのですが…

IMEはGboardです
