### ISSUE TITLE
Hide Admin Title

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3760]
# Summary

The admin title may not be wanted by admin users, or at least not visible to non admin users on the instance as it can change the way people interact, especially branding it on every note. You could make a separate admin account and have your normal account as a user account, however having to relog every time you access the admin console is a massive pain, especially with #3707

It would be nice for admin users to have an option to hide the admin title on posts and profile
![image](https://user-images.githubusercontent.com/7827846/50452114-46d5d100-098c-11e9-8b26-05dd80103eb7.png)

# Environment

**Comment by Johann150** [comment]
Currently admin status is only displayed on the profile page. Having separate accounts should also be easier with the account menu that was introduced in v12. So I would consider this fixed. If this is not the case I am sorry, and please feel free to reopen.
