### ISSUE TITLE
Setting for force mobile view

### ISSUE THREAD

**Issue by sftblw** [misskey-dev/misskey#3778]
# Summary
Sometimes I need to use mobile view on desktop. especially I use small firefox addon which opens specific sites on sidebar. on this case desktop version of UI breaks because of narrow width.

It would be great if it is able to set force to use mobile version of UI.

モバイルの画面の使うか使わないかを設定で強制的にセットできる機能がいればいいかとおもいます。

# Environment

don't care

**Comment by syuilo** [comment]
Related to https://github.com/syuilo/misskey/issues/2106

**Comment by tamaina** [comment]
> Related to #2106

#2106 にはそんなに関連してない気がする  
#4552 にはすごく関連してると思う

**Comment by sftblw** [comment]
fixed by #4549 , see #4552
