### ISSUE TITLE
Cant Follow Pixelfed Users

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3781]
# Summary

Attempting to follow a user from pixelfed  just says processing on client side and deliver failed: 500 Internal Server Error to=https://pixelfed.social/users/ibrokemypie/inbox on the server side

# Expected Behavior

follow user

# Actual Behavior

deliver failed: 500 Internal Server Error to=https://pixelfed.social/users/ibrokemypie/inbox

# Steps to Reproduce
1. attempt to follow a pixelfed user

# Environment

**Comment by mei23** [comment]
```
$ curl -v -H 'Accept: application/jrd+json, application/json' https://pixelfed.social/.well-known/webfinger?resource=acct:ibrokemypie@pixelfed.social

HTTP/1.1 403 Forbidden
<title>Attention Required! | Cloudflare</title>
```
CloudFlare's CAPTCHA page seems to appear.
It seems to be a unique problem of pixelfed.social.
I think that it is not a problem of Misskey or pixelfed software.

**Comment by dansup** [comment]
@ibrokemypie This has been [fixed](https://mstdn.io/@pixelfed/101322703920374567).

**Comment by ibrokemypie** [comment]
thanks!
still getting ``deliver failed: 500 Internal Server Error to=https://pixelfed.social/users/ibrokemypie/inbox`` from my server though... @dansup
