### ISSUE TITLE
ドライブのファイルのキャプチャ

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3785]
# Summary
投稿のようにドライブのファイルをキャプチャしてNSFWや削除を監視できるとよさそう

# Environment

**Comment by SanMurakami** [comment]
ファイルのURLから検索して削除する機能とかもあればうれしいです。

**Comment by syuilo** [comment]
ファイル情報が更新されたらそのファイルが添付された投稿に対して fileUpdated イベントなどを発行すれば良さそう

**Comment by tamaina** [comment]
実装されている
