### ISSUE TITLE
Renote and Reply Count in Note Object

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3786]
# Summary

The API currently does not provide a count of renotes or a count of replies in the note object, two things that would be very helpful for clients.

# Environment

**Comment by tamaina** [comment]
`renoteCount`、`reactionCounts`として存在しているはずですが…

**Comment by ibrokemypie** [comment]
reactionCounts exists, but not renoteCount or replyCount, at least according to the documentation

**Comment by tamaina** [comment]
Oops, sorry, but `replyCount` also exists.

**Comment by mei23** [comment]
reactionCounts: implimented, **returns undefined when 0**, documented
renoteCount: implimented, **returns undefined when 0**, **undocumented**
repliesCount: implimented, **returns undefined when 0**, **undocumented**

**Comment by ibrokemypie** [comment]
where is this documented? maybe this is a documentation issue then as it does not show that here
https://boopsnoot.gq/docs/en-US/api/entities/note

**Comment by tamaina** [comment]
renoteCountとrepliesCountは後から追加されたので、Documentationには書かれていないのかもしれません。  

APIの挙動は設定画面(`/i/settings`) > API > APIコンソールで、直接リクエストを送信して確認することができます。

できることなら、undefinedよりは0を返してくれた方が都合がよさそうですが…。

**Comment by tamaina** [comment]
Related to #3422

**Comment by mei23** [comment]
> できることなら、undefinedよりは0を返してくれた方が都合がよさそうですが…。

ここのoptionalこっそりtrueにしちゃえばいいんじゃねとか思ってたわ
https://github.com/syuilo/misskey/blob/8823a6c1a1ffebe96c3646896ae84cfc91eeadf4/src/docs/api/entities/note.yaml#L78-L82

**Comment by ibrokemypie** [comment]
Actually, there still doesnt seem to be a renote count in the code either
