### ISSUE TITLE
API Endpoint for Locked Accounts

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3797]
# Summary

There is currently no way to determine whether an account is locked (needs follows to be accepted) from the api.
Adding a boolean isLocked to the user object would solve this

# Environment

**Comment by tamaina** [comment]
isSuspended として存在するはずです

またundefinedになってる感じでしょうか…

**Comment by mei23** [comment]
> isSuspended として存在するはずです

鍵垢のことなのでisLockedの方だと思う

**Comment by tamaina** [comment]
あっ、そうでしたね…

**Comment by tamaina** [comment]
でもisLockedも存在してますね

**Comment by ibrokemypie** [comment]
oops, sorry!
