### ISSUE TITLE
リアクションの絵文字が文字化けする

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#380]
絵文字を表示できない環境があるみたいなので代替画像の表示などで対応できないかな

**Comment by otofune** [comment]
後々絵文字対応するのも考えてtwemoji読み込んでしまうとか (通信容量的な問題があるのでoptionalで読み込めるようにしたら丸そう)

**Comment by syuilo** [comment]
twemoji?

**Comment by AyaMorisawa** [comment]
https://github.com/twitter/twemoji ?

**Comment by otofune** [comment]
せやで

**Comment by syuilo** [comment]
暫定的に絵文字で表示してるだけで将来的には画像にする予定だった

**Comment by syuilo** [comment]
やる
