### ISSUE TITLE
Misskeyの新規登録のところから、申請フォームにアクセスできない

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/misskey#3801]
# Summary
Misskeyインスタンスが招待制のとき、新規登録のところから申請フォームにアクセスできない
https://docs.google.com/forms/d/e/1FAIpQLSdXmwbr8do-PBeQCk2RjI2a31JZ_LwOGcSCq0JGpU3Aaq2xnw/viewform
https://misskey.xyz/notes/5c281d59370c7b0027a97fce

問い合わせのハードルはある程度あるので、手軽に申請可能にするためにも申請フォームへのリンクはあったほうが良い

**Comment by acid-chicken** [comment]
「招待制の時はリンクなどのカスタムメッセージを設定できるようにする」ということでしょうか？

**Comment by EbiseLutica** [comment]
抽象的には、そういった感じがよろしいです

**Comment by marihachi** [comment]
現在、管理人へのメールのリンクが貼ってある部分を
- 今まで通りのメールのリンク
- 投稿フォームなどの任意のURL

を管理者が選んで設定できれば良いと思う。

**Comment by EbiseLutica** [comment]
招待メッセージでHTMLサポートするのが良さそうに見える
