### ISSUE TITLE
Follow Request field for /users/relation

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3802]
# Summary
It would be very helpful to be able to determine whether the user has requested to follow a given user in the /user/relation api endpoint
this would be false unless both the user being queried has a locked (follow by request only) account and the user querying (from the i parameter) has sent a follow request already

**Comment by ibrokemypie** [comment]
having both would be even better!

**Comment by syuilo** [comment]
It has already been implemented. Is not included in the response?

**Comment by ibrokemypie** [comment]
ah sorry yes, wasnt in the docs

**Comment by syuilo** [comment]
Misskey's documentation is not enough. sorry
