### ISSUE TITLE
公開範囲:ダイレクトの挙動

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#3803]
現状 公開範囲:ダイレクト な投稿において、ユーザー指定しない場合エラーになる仕様ですが、

これを、ユーザーの明示的指定がない場合、投稿内にメンションがあればそれを、なければ自分を暗黙的に指定するような仕様にするのはどうでしょう。

**Comment by syuilo** [comment]
> 投稿内にメンションがあればそれを

これは既にそうなっていると思います

**Comment by EbiseLutica** [comment]
確認不足でしたがそのとおりでしたね。未指定の場合自分を指定するような仕様についてはいかがでしょうか...

**Comment by mei23** [comment]
非公開を廃止したが、ダイレクトは誰も指定してないとエラーになるのでそのままでは非公開の代わりにはならない。
→ エラーにならないようにする or 未指定の場合には暗黙的に自分を指定するようにする

みたいな話かも？

**Comment by EbiseLutica** [comment]
まさにそのとおりです

**Comment by tamaina** [comment]
ダイレクトで公開先ユーザーが未指定の場合クライアント側でインフォメーションを出すようにして、APIはエラーを出さないようにすればよさそう  
公開先に自分を追加する処理は特に要らない気がする(というか、そうするとその投稿がいちいち「メッセージ」に出現するようになってしまう)

このときインフォメーションが次回以降出ないようにするチェックボックスが付いていると、うざく思われなくて良いと思う

**Comment by EbiseLutica** [comment]
API的に不可能なもの、現状でも技術的に相手が存在しないダイレクトは自分しか見れない仕様なのでしょうか？そうであればtamainaさんの提案が最適な気もします

**Comment by tamaina** [comment]
> API的に不可能なもの、現状でも技術的に相手が存在しないダイレクトは自分しか見れない仕様

API的に不可能なのでわからないけれど、多分そうなってるような気がする

**Comment by mei23** [comment]
以前は非公開という専用の公開範囲があったため
非公開と区別するためにダイレクトで宛先があるかチェックしてたような感じだと思うので
非公開がないならばもうチェックしなくていいと思います。
(チェックをしないようにすれば以前あった非公開と同等になる)
