### ISSUE TITLE
Remote Notes dont show reply/react/renote count

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3805]
# Summary

Notes from remote users dont show their reaction, reply or renote counts in the api, they are always undefined/0

# Expected Behavior

Show appropriate counts

# Actual Behavior

Always undefined

# Steps to Reproduce
1.
2.
3.

# Environment

**Comment by mei23** [comment]
Localからその投稿に Renote/Reaction された分は正常にカウントされます。

それ以外の値は、ActicityPub経由でカウントを取得する手段がないので不可能です。
Remote=>Remote で Renote/Reaction された際には、こちらで知る術がないのでインクリメント不可能です。

**Comment by tamaina** [comment]
#2448 と同じような感じ？

**Comment by futchitwo** [comment]
Has this Issue already been resolved?

**Comment by robflop** [comment]
i do not see the issue on version 12.108.1
