### ISSUE TITLE
Renote数の表示を復活させてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#3807]
# Summary
再共有(ブースト)機能はマイクロブログSNS基本的な機能の一つで、その数を計測できないというのは特にSNSを戦略的に統計に基づいて利用している人にとっては困ることだと思います。

https://misskey.xyz/notes/5c28ccae2a769b0027492d79

# Environment

**Comment by tamaina** [comment]
どのような投稿がどのくらいRenoteされたかを考えながら運用する、という感じですね

**Comment by acid-chicken** [comment]
連合間でしばしば数字が噛み合わないのでそもそも参考にならないかと。

**Comment by syuilo** [comment]
Reverted by https://github.com/syuilo/misskey/commit/c5dc25cb9e3bf43b6d667e72651e0fb6ce107d82
