### ISSUE TITLE
Notification Websocket Stream

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3823]
# Summary

Currently as far as I can tell notifications are not available on any of the websocket streams, but making notifications available would be one of the best uses for websockets, allowing apps to provide users with their notifications in real time without requiring polling an api end point forever.
It would be great to have a notification stream that just emits notification objects for the authenticated user as they come in, a real time version of api/i/notifications

# Environment

**Comment by tamaina** [comment]
ない時期なんてあったのか
