### ISSUE TITLE
Visibility Not Kept When Replying

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3827]
# Summary

If you reply to a post with non-default visibility, such as direct or followers only, your new post should copy the visibility of the post you are replying to by default. If replying to a direct post, the "to" parameter should be filled as well

# Expected Behavior

Replies keep original visibility and if are replies to direct, fill in the "to"

# Actual Behavior

Visibility defaults to public instead

# Steps to Reproduce
1. Receive a direct status
2. Click reply
3.

# Environment

**Comment by mei23** [comment]
ダイレクトとかのときだけ効かない

**Comment by motherfogger** [comment]
(noob question) I've tried to reply to a `https://mastodon.social/@tom79/101359453831240906` post using  `@acebesmonte@misskey.xyz` is this allowed?

The popup page loads forever.

```https://misskey.xyz/authorize-follow?acct=https%3A%2F%2Fmastodon.social%2Fusers%2Ftom79%2Fstatuses%2F101359453831240906```
