### ISSUE TITLE
投票ウィジェットに当該投票へのリンクを表示

### ISSUE THREAD

**Issue by ha-dai** [misskey-dev/misskey#383]
おすすめ投票ウィジェットにおいて、その投票(ポスト)に対するリンクを表示するか、遷移できるようにしてほしいです。
※トレンドウィジェットのように本文にaリンク等

**Comment by AyaMorisawa** [comment]
duplicate of #338

**Comment by ha-dai** [comment]
すみません。
検索が甘かったです。
