### ISSUE TITLE
ui-input bug on Safari

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#3839]
# Summary

幅が倍ぐらいありそう。

![](https://user-images.githubusercontent.com/20679825/50732603-b7b58e00-11c1-11e9-915d-3ab3a8a5615c.png)
![](https://user-images.githubusercontent.com/20679825/50732607-c8660400-11c1-11e9-8fe4-5acf9cfbe0dd.png)
![](https://user-images.githubusercontent.com/20679825/50732610-ce5be500-11c1-11e9-9930-ccd880c32775.png)

**Comment by acid-chicken** [comment]
恐らく原因はココ（なぜかviewportの幅が双方のpaddingに入っている）

https://github.com/syuilo/misskey/blob/e0b107a3a0faeb4fe2aaf8883fcef1e3abee7e49/src/client/app/common/views/components/ui/input.vue#L163-L175

**Comment by acid-chicken** [comment]
解決方法が分からない

**Comment by syuilo** [comment]
謎

**Comment by acid-chicken** [comment]
これVue.jsかWebKitのどちらかのバグだと思うんですけど、どちらに報告した方がいいんでしょうか……

**Comment by syuilo** [comment]
ログインフォームをダイアログにすることにより回避
