### ISSUE TITLE
Moderation Features

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3860]
# Summary

To describe the moderation features of misskey as lacking would be a major understatement. Currently there is very little that can be done on any front, and very little feedback from misskey.
I have a number of things that I believe would greatly benefit the moderation potential of misskey, and can be implemented separately.

1. Improve feedback for moderator appointment. Currently you can add a moderator by typing in their handle and clicking a button. There is no feedback, no lsit of current moderators and no way to remove moderators.
2. Improve feedback for current suspension system. Similarly to appointing moderators, you can currently suspend users by typing their handle and clicking a button, however there is no list of suspended users that may be reviewed or easy way to unsuspend people without directly looking them up. There is not even a way to determine the suspended status of an individual user.
3. Improve moderation interface. Currently moderators can delete messages and from the misskey interface, but that is it. There should be a way in the misskey interface for moderators to take actions on specific users. By adding buttons for each action to the three dots menu on user profiles, which currently only contains "add to a list", moderation would be much more viable.
4. Increase user action verbosity. Currently the only action is "suspend" which in addition to being unclear (I am still not really sure what exactly it does), it doesnt cover all cases. There should be a number of options including the following:
* Mark all media as NSFW, this would automatically override the user's decisions and mark every piece of media they upload as NSFW.
* Hide from public timelines, this would prevent the user's posts from showing on the local and federated timelines, allowing their followers to still see them on the home timeline, but hiding their posts from non followers
* Ban, prevent all interaction to and from this user. Dont show their posts on any timelines, dont mirror their account, dont allow the user to react, reply, renote etc any user's posts, nor allow any user to do any of these tho theirs.

As part of 3, these actions and actions to undo them should be available within misskey itself for moderators.

Later down the track a report and moderation queue system would also be greatly appreciated.

**Comment by tamaina** [comment]
Please create issues separately.
