### ISSUE TITLE
Search Query Input Broken

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3862]
# Summary

When changing the search query input, it starts reverting and replaying changes or parts of the changes you made to it, on its own

# Expected Behavior

Input field works normally

# Actual Behavior

![screen recording 2019-01-09 at 9 16 32 pm 2019-01-09 21_18_48](https://user-images.githubusercontent.com/7827846/50893089-2dd12380-1454-11e9-8723-bd0c7143a324.gif)

# Steps to Reproduce
1.
2.
3.

# Environment

Desktop, Iridium (chromium fork), macOS

**Comment by AyaMorisawa** [comment]
* クライアント **から** 受け取ったデータをサーバー **が** エコーバックして、
* サーバー **から** 受け取ったデータをクライアント **が** エコーバックしてるので、

無限ループになってる

**Comment by AyaMorisawa** [comment]
ローカルで検証する場合はclientSettingUpdatedのpublishMainStreamを100msくらい遅延させたら再現しやすそう

**Comment by acid-chicken** [comment]
なんでこんな仕様になってるんですか……

**Comment by Golutazem** [comment]
This problem occurs in both Firefox and Chromium WebKit based browsers.

**Comment by u1-liquid** [comment]
保存ボタンなしで入力受ける次第アップデートしてるinput boxすべてに起こりうる問題だと思います。

>サーバー から 受け取ったデータをクライアント が エコーバックしてる

この動作別に要らないと思いますがどうでしょうか

**Comment by AyaMorisawa** [comment]
> この動作別に要らないと思いますがどうでしょうか

要らないと思います。本来、サーバーへの送信はユーザーが入力したときのみで十分なので、単なる実装ミスによる不具合っぽさがあります。
