### ISSUE TITLE
IP BANを行う機能

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#3864]
スパムが増えてきたため、IP BANをする必要が出てきました。

**Comment by mei23** [comment]
ログイン時のIPアドレス等は記録しているものの、それを管理者が利用できるAPI/コマンド/管理画面などはない模様。

**Comment by acid-chicken** [comment]
Off Topic: これに反対するつもりはないですが、運用者以外の管理者もIPアドレス等が見えるようになってしまうので、プライバシーポリシーがない状態で実装を進めても大丈夫なのかなというのはあります。

**Comment by mei23** [comment]
> 運用者以外の管理者

Misskeyのモデレーター？Misskeyの管理者？

**Comment by mei23** [comment]
コマンドでIPアドレス見れて (サーバー管理している人しか見れない)、BANはWebサーバーとかでもいいと思う。

**Comment by tateisu** [comment]
IPアドレスは範囲指定とかしたくなるものなので、BANそのものは実装しない方がいいと思いますわ

**Comment by mei23** [comment]
IPアドレスは (koa-routerの機能で) 取得してはいるものの、たぶん偽装可能なのであまり保証できない感じで。

**Comment by tateisu** [comment]
悪用する人が色々工夫したらソレじゃ足りなくなるのは仕方ないけど、
カジュアルな悪用をある程度まで防止できるなら十分に有用だと思います。

**Comment by mei23** [comment]
とりあえずサーバー管理者だけがコマンドで参照できるようにする #3870
で、プライバシー部分の参照権限は変わらず、必要な情報は得ることは出来ると思うので (とりあえずこれで) どうかなと。

**Comment by SanMurakami** [comment]
あとCloudFlareを経由している場合はRayIDも保存するようにすると完璧かも？

**Comment by mei23** [comment]
サインイン試行時の全リクエストヘッダが保存されているので、CloudFlareの`cf-ray`も既に保存済みです

**Comment by SanMurakami** [comment]
これに付随してる事で見つけたんですが、サインイン履歴のIP全部CloudFlareのでユーザーの履歴じゃないんですよね
CF-Connecting-IPが含まれている場合はそっちを優先して拾う方がいいかも。

![image](https://user-images.githubusercontent.com/37681609/51051921-88b37800-1618-11e9-863f-7bd2fc6a5376.png)

**Comment by tamaina** [comment]
やっぱ欲しくない？

**Comment by tamaina** [comment]
（間違ってBANされたときの異議申し立てを簡単に行う機能もつけたい）
