### ISSUE TITLE
Polls dont Federate

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3885]
# Summary

When creating a poll it doesnt show on other misskey instances

# Expected Behavior

Poll shows as normal on other misskey instances

# Actual Behavior

Note instead has a link to the original post on the original instance

# Steps to Reproduce
1. Create a poll
2. View it from another misskey instance

# Environment

**Comment by ibrokemypie** [comment]
eg 
![image](https://user-images.githubusercontent.com/7827846/51087972-4328b380-17ae-11e9-9d98-45d5ae51fa6b.png)

**Comment by mei23** [comment]
Related to #1555
