### ISSUE TITLE
凍結されたアカウントでUIを開くと無限リロードが発生する

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#3897]
https://twitter.com/acid_chicken/status/1085410926487109632

**Comment by vandojapan** [comment]
PCでも再現

**Comment by syuilo** [comment]
ローカルではデスクトップもモバイルも再現できなかった

**Comment by acid-chicken** [comment]
キャッシュかストレージが絡んでそう？

**Comment by syuilo** [comment]
推測だけどクッキーが絡んでそう
最近のMisskeyではクッキーを使わないけど、昔のMisskeyではクッキーを一部使ってた
クッキーが残ってる場合それでサインインしようと試みるので、無限ループするのだと思う
最近Misskeyを始めた人ならクッキーはそもそも無いので無限ループしないのかも

**Comment by vandojapan** [comment]
キャッシュ削除でも変化なし。
Cookie削除で脱出

**Comment by tamaina** [comment]
最近報告がないのでclose
