### ISSUE TITLE
機械学習でNSFWを自動で判定

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#3905]
https://github.com/infinitered/nsfwjs

**Comment by syuilo** [comment]
TensorFlowを使っていい感じにできないか考えてる

**Comment by acid-chicken** [comment]
https://github.com/infinitered/nsfwjs

**Comment by syuilo** [comment]
わー、結構な精度ですねそれは
情報ありがとうございます

**Comment by syuilo** [comment]
モデルの用意が面倒そう

**Comment by Johann150** [comment]
I think users should be able to choose if something should be NSFW or not. If you do not like the choices a user makes you can unfollow them.
It might also be a good idea if Moderators or Admins are able to force all posts of a user to be NSFW. Technically already possible by using `user_profile.alwaysMarkNsfw` through the database, which would work for a remote user I think?
But local users would be able to overwrite it in their own settings, so they might have to be suspended instead.

**Comment by syuilo** [comment]
This purpose is not for user convenience, but for moderation.
It helps detect when illegal pornography has been posted.

**Comment by 4ioskd** [comment]
あくまで参考として。

もうどなたか忘れてしまいましたが、かなり前にとあるfediソフトウェアの開発者（自分のインスタンスを持っている）とそのソフトウェアを利用しているインスタンスの管理人が機械学習によるNSFWの自動判定について話し合ってて、前提としては「各インスタンスの管理人が独自に判断してそれを実装すべき」でした。NSFW判定向けの良い機械学習モデルはこれがいいんじゃないか、あれがいいんじゃないかと話してましたが、結局fediソフトウェアの開発者はそのソフトウェア自体には導入しなかったようです。

このNSFWの機械学習による判定というのは、ソフトウェア自体に導入するとちょっと中央集権的であり、各インスタンス管理者にその裁量を委ねた方が非中央集権型のFediには合っているのだろうなぁ、と考えました。

**Comment by syuilo** [comment]
自前で実装できるインスタンス管理者はかなり限られるのではないかしら
あとopt-inだしモデルを挿げ替えることも簡単だから個人的には中央集権的な気はしていない

**Comment by tamaina** [comment]
nsfwjsやTensorFlowはオープンソースを志向して作られたものだし、外部と通信を行わない。仕組み自体はまったく中央集権ではない。

たしかにモデルについては同一のものを手元で再生成することはできないが、技術や法律上の制約という面が大きいし、自分で作ることもできるので、これをただちに中央集権的と言うことはできないと思う。

個人的感想: 自分が知らない技術についてよく調べもせずに中央集権的とレッテルを貼られるのは、たまったものではない。

**Comment by 4ioskd** [comment]
opt-inでモデルを挿げ替えることも簡単なようにしているのならば、それは良いことかと思います。もちろん、その機械学習のモデルがオープンソースで、外部と通信をしないのは知っています。

NSFW（Not Safe For Work）への解釈というのは、百人いれば百通りある考え方や価値観で分かれるため、それに対してMisskeyというかしゅいろ氏個人が解釈したNSFWへの考えに基づいたモデルが、海外の人はおろか日本のMisskeyのインスタンス管理者やユーザーの多くに受け入れられるかというと、、かなり難しい気がします。そういったモデルを各インスタンス管理者がopt-inでモデルを挿げ替えることができたとしても、外部プラグインではなくMisskey自体に仕込むのはどうなのだろう。300以上あるMisskeyインスタンスへの「中央集権的な、NSFWへの価値観の強制」であるとか「TwitterやYoutubeの誤Banのように誤まった判定をされた」等、ポジティブな反応よりもネガティブな反応をされて、その対応に時間を割くことになりそうな気がします。

結局、各インスタンスの管理者の技量の有る無しに関わらず、こういった人の価値観や考え方に関わるセンシティブな問題にはあまり干渉すべきではなく、各インスタンス管理者に委ねるのが良いのかなぁ、と思います。しゅいろ氏のモデルをMisskeyに仕込まず、個人のライブラリで何らかの形で公開するなら全然問題ないかと。

**Comment by syuilo** [comment]
これはユーザーのためというよりはモデレーションのための機能なので、ユーザーからは専らネガティブな反応をされると思います。
何がNSFWに該当するかは人によると思いますが、無修正の性器が写っているようなものはポルノであるとほとんどの人は認識すると思うので、そのように判定されたものに限って処理をするオプションを実装すると良いかもしれまぜん。

**Comment by 4ioskd** [comment]
うーん。ネガティブな反応されるでしょうし、かなり反発が予想されますね。多分それが恐くて、どのFediソフトウェアもNSFWの自動判定を採用したり等、積極的なモデレーション対策をソフトウェア側でしないのでしょう。例えばLemmyがユーザー間での揉めごとを減らしたり、モデレーションの負荷を少なくするためにフォーレターワード（F○CKとかSH○Tとか）等が含まれた投稿を自動的に投稿させない仕組みを取り入れたのですが「言論の自由への侵害だ」として、かなり揉めまして。結果としてLennyというハードフォークが一つ生まれてしまいました。

>無修正の性器が写っているようなものはポルノであるとほとんどの人は認識すると思うので、そのように判定されたものに限って処理をするオプションを実装する

ですね。「ほとんど」の人はそう思うと思います。ここが人のNSFWへの価値観や考え方の難しい所です。例えば性産業をテーマとしたインスタンス（最近までマストドンにありましたよね）のインスタンス管理者やユーザーであるとか、そもそもヌード目的のインスタンス管理者であるとか、そういう方からするとこのモデルは心外でしょう。そしてオプションを実装すると、あれも入れてこれも入れて、と恐らくキリがありません。

先に上げたLemmyの事例のように、何かの「自由」を制限することによるソフトウェア開発者への代償はFediverseではとてつもなく大きいです。それはこの空間が「自由」で「多様」で「開かれた」ものであることをFediverseの人が大切にしているからだと思います。

**Comment by tamaina** [comment]
> 性産業をテーマとしたインスタンス（最近までマストドンにありましたよね）のインスタンス管理者やユーザーであるとか、そもそもヌード目的のインスタンス管理者であるとか

その場合は機能をオフにしておけばええやん

**Comment by itiradi** [comment]
Winny事件とか（広くは無限アラート事件とか）そうだけど、「自由で開かれた」ないし「非中央集権的な」ソフトウェアが悪用された時に日本でその開発者や自由が誰かによって正しく守られるかどうかは疑わしい気がするし、それに「犯罪発生の抑止策を打っていた」という口実が付けられるような機能を設けることは一種の必要悪に該当するのではないかと思う

**Comment by tamaina** [comment]
@4ioskd は外人の意見を代弁しているだけ(と私は認識している)。

外人はWinny事件など日本の警察や司法の事情を知らないし、そういう規制の脅威はあまり感じたことがないのではないかしら。もしくは自由やプライバシーのためなら捕まってもいいと思っているとか。

**Comment by syuilo** [comment]
PR #8840 に関して言えば、
- 機能の趣旨を、「ポルノの可能性が高いファイルを内部的にフラグ設定する」という方向に寄せてみた
  - NSFW(sensitive)というのは幅が広いため、法的に問題のある可能性の高いポルノに絞る方向に
  - 強制的にNSFW設定したりはデフォルトでは行わない
  - またNSFW設定したとしてもユーザーが解除できないといったことは無くなった
- ユーザーが望めば、自動でNSFW設定する機能をオンにすることもできる

↑などの変更を行ってよりソフトにしてみた

**Comment by syuilo** [comment]
私は複数のMisskeyインスタンスで児童ポルノがアップロードされているのを見てきているから危機感が他の人より高いかも
Misskeyがそういう理由で使われるソフトウェアになってほしくないみたいな

**Comment by 4ioskd** [comment]
しゅいろ氏、色々と対応ありがとうございます。

ようやくこの機能の実装のモチベーションとして、児童ポルノを中心とした猥褻物のMisskey上での陳列へのモデレーションを強化したい、ということ（これで合ってますかね？）だと理解しました。基本的に児童ポルノを中心とした対策なのであれば、それは説明がしっかりしていれば国や人を問わず広く理解してもらえるかと思いますし、 https://github.com/misskey-dev/misskey/issues/3905#issuecomment-1166548264 のように対応して頂いた結果、選択の幅が広くなりましたし、問題ないかと思います。また、わが国を取り巻く種々の現状や日本におけるMisskeyの現状を踏まえれば、導入はやむをえないと判断しました。

ちなみに「NSFW」という言葉は人によっては解釈がかなり変わってきて誤解を生む恐れがあるので、例えばNSFWフラグだとかこのIssueのタイトルにあるNSFWという言葉は「ポルノ」や「猥褻物」に変更したらどうでしょうか。
