### ISSUE TITLE
Stream経由のAPIリクエスト利用時にクラスタ化の恩恵が受けられない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#3911]
# Summary
APIリクエストをStream経由で行うオプションがありデフォルトで有効なのですが
これが利用されている場合、特定の人のAPIリクエストは常に同じWorkerプロセスで実行されてしまい
クラスタ化の恩恵を受けられないみたいです。

# Detail
Misskeyには論理CPUの数だけWorkerプロセスを立ち上げて分散処理する仕組みがある。
↓
通常のHTTPリクエストが来た場合は、NodeがリクエストをWorkerプロセスに振り分けるため分散処理が実現する。
↓
しかし、Stream経由のAPIリクエストを利用されている場合
必ずStreamでつながっているWorkerでAPIリクエストが実行されることになるため
(特定のユーザー観点で見た場合には) 分散処理にならない。
↓
さらに、投稿処理を行った場合AP配信も同じWorker実行されるため
特定のプロセスだけに処理が集中する。

## 考えられる影響
特に複数のAPIリクエストを出した場合には、特定のプロセスだけに処理が集中して重くなるため
当人や同じプロセスのStreamにぶら下がっている人達が重いと感じることがあるのかもしれない。

またフォロワーの多い人のAP配信などは結構重かったりするため
そういう人と同じプロセスにぶら下がっている人は「今日は重いな」などと思うのかもしれない。

# 結果的に
「Stream経由のAPIリクエスト」で期待されているリクエストオーバーヘッドの軽減効果は
HTTP Keep-Alive や HTTP/2の多重化などで担保できているのではと思われるので
あえてデメリットのある「Stream経由のAPIリクエスト」を利用しなくてもいいのかもしれない。

**Comment by syuilo** [comment]
ありがとうございます！
仰る通りだと思うのでデフォルトで無効もしくはオプションの廃止をしたいと思います。

**Comment by syuilo** [comment]
廃止しました。
