### ISSUE TITLE
Content Warnings not kept when replying

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3914]
# Summary

Was added then reverted here.
https://github.com/syuilo/misskey/commit/f433182c4cd449a08eb436df30bee731345240c1
I agree an option is the best way, however having it entirely disabled is potentially harmful as the entire purpose of content warnings is to allow other users to decide if they wish to see content contained and described in the warning. Replies to something are generally of the same topic, replying to the content that required the content warning to begin with, so it makes sense to apply the same content warning as the instances where this is not the case would be exceptions rather than the norm.
Content warnings are copied over in other AP servers, and it would make sense for a user to expect it to be done and thus not think about it, resulting in untagged content that should be tagged, which can be very harmful to people.

**Comment by acid-chicken** [comment]
@ibrokemypie Thank you for notifying us.

I'm going to work for it soon.

> やっておきます。
> _Originally posted by @acid-chicken in https://github.com/syuilo/misskey/commit/f433182c4cd449a08eb436df30bee731345240c1#commitcomment-31945149_
