### ISSUE TITLE
AP配信時のリモートユーザーメンションを自インスタンスのリンクにしない

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#3936]
# Summary

**Comment by mei23** [comment]
@acid-chicken これ何故に？
Mastodonでメンションをプレビューカード展開させたくないとかです？

**Comment by acid-chicken** [comment]
あまり自インスタンスのリンクであるかのように扱って欲しくない感じがあります。

**Comment by mei23** [comment]
> AP配信時のリモートユーザーメンションを自インスタンスのリンクにしない

そもそもこうはなってない気がする。

**Comment by mei23** [comment]
APはちゃんと該当リモートインスタンスのリンクとして送っている
APIからクライアントに送る時はリンクではない
`自インスタンス/@user@remote`リンクにしてるのはクライアントだと思う

**Comment by acid-chicken** [comment]
色々検証しましたが、これはMisskeyの問題ではなさそうです。失礼しました。
