### ISSUE TITLE
非ログイン時における投稿に対するアクション

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#3957]
# Summary

非ログイン時に投稿に対してRenoteなどのアクションを行おうとした際、

* 新規登録
* ログイン
* WebFingerに基づくリモートアクション

の三択に誘導するモーダルを表示したほうが良い。

**Comment by acid-chicken** [comment]
Adding bug

**Comment by mei23** [comment]
そもそも非ログイン時に
![image](https://user-images.githubusercontent.com/30769358/61556068-d6afa980-aa9b-11e9-8d9e-0398f37e494b.png)
出てくるの変だから隠しちゃおう (…はエラーになるし)

**Comment by acid-chicken** [comment]
それは分散型 SNS 的にどうなの

**Comment by mei23** [comment]
右にStartとかいう誘導あるし
ローカルのみ投稿かもしれないし分散SNSなんて知らない

**Comment by acid-chicken** [comment]
えぇ……

**Comment by syuilo** [comment]
> 非ログイン時に投稿に対してRenoteなどのアクションを行おうとした際、
> 
> * 新規登録
> * ログイン
> * WebFingerに基づくリモートアクション
> 
> の三択に誘導するモーダルを表示したほうが良い。

これが良いように思います

**Comment by mei23** [comment]
このTODOは残しといておいていいけど、
実装するまでの間はコントロールを表示しておくのは変なので消しちゃおうみたいな感じだわ

**Comment by u1-liquid** [comment]
> 右にStartとかいう誘導あるし


モバイル版では誘導のものは見当たりませんね

**Comment by mei23** [comment]
- 新規登録
- ログイン
- WebFingerに基づくリモートアクション

3択を経て投稿表示画面に戻ってくるのを実装するのは結構大変でなかなか実装されないと思うので
コントロールが出てきちゃうの自体はバグとして別にするべきと思うのだわ

**Comment by acid-chicken** [comment]
モーダルでいいんじゃないですかね

**Comment by mei23** [comment]
だから

> このTODOは残しといておいていいけど、
> 実装するまでの間はコントロールを表示しておくのは変なので消しちゃおうみたいな感じだわ

だって

**Comment by mei23** [comment]
モーダルにするなとは言ってない
ここでチャットをするからいけない

**Comment by mei23** [comment]
バグフラグを付けるなら
「非ログイン状態にもかわからずアクションができるコントロールが表示されて
実行しても結局エラーになる」とかいう説明くらいつけるべき
それについて言及しただけだわ

**Comment by acid-chicken** [comment]
> 3択を経て投稿表示画面に戻ってくるのを実装するのは結構大変

はモーダルにしちゃえばあとは非ログイン時のトップのコンポーネントと WebAuthn の *OR* コンポーネントなりをそのまま組み合わせてしまえばそんなに大変でないと思うので、一時的に消さずとも工数かけずにそのまま実装できるのではないかという話です。
まあ誰もやるつもりないみたいな感じであれば消してしまってもいいかもしれないですが。

**Comment by syuilo** [comment]
「ログインしてください」を表示するくらいならそんなに大変ではないと思うのでとりあえずそうするようにします

**Comment by tamaina** [comment]
> WebFingerに基づくリモートアクション

自分のユーザーネームを入力するのはイケてないので、投稿URLをコピーするボタンを付けるのでもいいと思った (like #8194)

> 3択を経て投稿表示画面に戻ってくるのを実装するのは結構大変
> https://github.com/misskey-dev/misskey/issues/3957#issuecomment-513328913

（発火元のノートURLを把握できれば）新規登録とログインのダイアログは簡単だと思う、ログイン時リダイレクト&unisonReload発火しちゃえばいい

**Comment by Sayamame-beans** [comment]
triage: 解決済みと考えられるが、13089でさらなる改善がされるようなのでopenのままに
