### ISSUE TITLE
SinceId parameter of timeline api has different casing

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3966]
# Summary

All other parameters have camelcase eg untilId, but SinceId has title case.

# Expected Behavior

instead named sinceId

# Actual Behavior

named SinceId

**Comment by acid-chicken** [comment]
I'm sorry but I can't find it.

<img width="288" alt="image" src="https://user-images.githubusercontent.com/20679825/51586235-c1f4bd80-1f1f-11e9-9d03-a0daa9792658.png">

**Comment by ibrokemypie** [comment]
https://translate.googleusercontent.com/translate_c?depth=2&rurl=translate.google.com&sl=ja&sp=nmt4&tl=en&u=https://boopsnoot.gq/docs/ja-JP/api/endpoints/notes/timeline&xid=17259,15700021,15700124,15700186,15700191,15700201,15700237,15700242,15700248&usg=ALkJrhizvUqbtsHOBEvUFkPkGrtoCyoUpg
