### ISSUE TITLE
using a CW doesnt hide contained images on other platforms

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3968]
# Summary

When you hide a status with a CW any attached images still show on mastodon/pleroma

# Expected Behavior

The image is hidden/marked nsfw

# Actual Behavior

Image is still visible

# Steps to Reproduce
1. create a post with an image
2. add a content warning
3. view on other pleroma/misskey instance

# Environment

**Comment by mei23** [comment]
Misskey UI (なおSubwayTooterも)
- CW
  - Body
  - Medias

Mastodon UI
- CW
  - Body
- Medias

なので、CWを付けてNSFWを付けない場合
Misskeyで隠れてもMastodonなどに行くと隠れない問題がある

CWの外にMediasがあるMastodonがちょっと変といえば変だけど
Mastodonは後にはCWを付けるとMediasもNSFWになるようにして対応しているはず

なお、CW付けてNSFWを付けない場合は
MisskeyでもWelcomeページの最近の画像にばっちり出てきちゃうという問題があり (v10時点で)
(v11はそもそもexcludeNsfwが効かない問題(#5287)があるので気づきにくいけどだわ)

**Comment by acid-chicken** [comment]
Related to tootsuite/mastodon#1010
