### ISSUE TITLE
optionally treat short silent videos as gifs

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3969]
# Summary

Many other instances replace gifs with short silent webms or mp4s as they save the same purpose but use a lot less space. On these other services the silent webm/mp4s are autoplayed (or played on hover) and looped like a gif is. It would be great if misskey did the same

# Environment

**Comment by tamaina** [comment]
「short silent video」を検出・定義するのがややこしい（議論になりそう）

**Comment by acid-chicken** [comment]
> 「short silent video」を検出・定義するのがややこしい（議論になりそう）

あまりややこしさのイメージが湧かないんだけどどこら辺が懸念点？

**Comment by tamaina** [comment]
検出するのは簡単だわね

定義（「何秒にするか」）をどうしようかなと

**Comment by acid-chicken** [comment]
> 検出するのは簡単だわね
> 
> 
> 
> 定義（「何秒にするか」）をどうしようかなと

他プラットフォームだと

Twitter: 旧仕様だと 7 秒以下（現仕様は全てループ対象）
Mastodon: オーディオチャンネルがない動画全て

といったところかしら

**Comment by rinsuki** [comment]
オーディオチャンネルがない動画全てでいいんじゃないかという気がする

**Comment by tamaina** [comment]
あまりにもクソ長いとサーバーのリソースが厳しい気がする
（Twitterに倣って(??)140秒とかにするか）

**Comment by acid-chicken** [comment]
> あまりにもクソ長いとサーバーのリソースが厳しい気がする
> （Twitterに倣って(??)140秒とかにするか）

どういうこと？（これってリソースには直接影響を及ぼさなくない？）

**Comment by tamaina** [comment]
あー、別に変換しなくていいか

（じゃあクライアント側でどうやって検出するの）

**Comment by acid-chicken** [comment]
> あー、別に変換しなくていいか
> 
> （じゃあクライアント側でどうやって検出するの）

`HTMLMediaElement#loop = !HTMLMediaElement#audioTracks.length` で終わりそう

**Comment by tamaina** [comment]
https://developer.mozilla.org/ja/docs/Web/API/HTMLMediaElement/audioTracks これか

**Comment by saschanaz** [comment]
tracks APIのブラウザサポートほぼ全滅ですのでサーバー側で確認する必要がありそうです

**Comment by acid-chicken** [comment]
> tracks APIのブラウザサポートほぼ全滅ですのでサーバー側で確認する必要がありそうです

できそうじゃね https://codepen.io/acid-chicken/pen/RwvMrmM
