### ISSUE TITLE
フォロワー向けのメンション付き投稿がフォロワー以外のメンション先から見えない

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#3973]
# Summary

フォロワー向けのメンション投稿の存在がメンションタイムラインから見えてしまう。

# Expected Behavior

![image](https://user-images.githubusercontent.com/20679825/51609422-7103ba00-1f5d-11e9-9a11-f95b678f5a6a.png)

# Actual Behavior

![image](https://user-images.githubusercontent.com/20679825/51609356-431e7580-1f5d-11e9-890e-261b72c6381c.png)

# Steps to Reproduce

1. 公開範囲を `followers` にして公開範囲から外れる相手に対してメンションした投稿をポストする。
2. メンション先のアカウントからメンションタイムラインを見る。
3. こっそりメンションしたことがバレる。

**Comment by rinsuki** [comment]
Mastodonではfollowers onlyで投稿しても投稿内でメンションを付けた相手には見えるので、互換性を考えるとこの挙動+投稿内容が見える挙動のほうがいいのではという気がする

**Comment by mei23** [comment]
そういえばそう
より狭い公開範囲の「ダイレクト」ではメンションされれば参照できるので
それより広い「フォロワー」でメンション時に見えないのも変

**Comment by mei23** [comment]
フォロワー限定へのリプライは自動でフォロワー限定になるものの、
リプライしたにも関わらず、自分のフォロワーじゃないので意図せず届いてないとかもまずそう。
自分のフォロワーかどうか確認して返信する人はいないだろうし、
現状、UIからある人が自分をフォローしているかどうか確認する術がない。

**Comment by syuilo** [comment]
> リプライ飛ばせばフォロワーじゃなくても見れるように

これはその仕様で良いと思いますが、メンションは意図せず相手に見えてしまうケースが多いように感じたのでメンションしたとしてもそのユーザーがフォロワーでなければ見れない方が良さそう

**Comment by acid-chicken** [comment]
わざわざメンションつけてまでかげごとを叩くことってありますかね？

**Comment by syuilo** [comment]
運営者としてよく経験しました

**Comment by tamaina** [comment]
**それはそうと、** #4033 がマージされたのでこのissueは閉じてもよさそう

**Comment by syuilo** [comment]
v11ではメンションしても閲覧可能ユーザーに含めなくなる予定

**Comment by tamaina** [comment]
なるほど

**Comment by syuilo** [comment]
少なくともサーバーサイドでやることではなさそう

**Comment by tamaina** [comment]
んー、それにしたって、わざわざメンションしているなら閲覧可能ユーザーに含められたほうがいいと思うけれど...

**Comment by tamaina** [comment]
> v11ではメンションしても閲覧可能ユーザーに含めなくなる予定

なっているのでclose
