### ISSUE TITLE
disable convert 'na' to 'nya' in search box on Cat mode

### ISSUE THREAD

**Issue by miyacorata** [misskey-dev/misskey#3974]
# Summary

Even if the user is a cat, it is desirable not to convert sentences entered in the search box.

Currently, for example, when "コナミ"(konami) is input, it is converted to "コニャミ"(konyami).

# Environment

Misskey 10.78.5
Windows 10 (1803)
Chrome 71.0.3578.98

**Comment by 4ioskd** [comment]
i don't know which commit and pull reqeust solves this issue.
but you can type 'na' in search box. not 'nya" .

**Comment by KisaragiEffective** [comment]
Seems resolved in latest version.
