### ISSUE TITLE
report  maxNoteTextLength in /api/v1/instance

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3984]
# Summary

Currently /api/v1/instance doesnt contain the maximum note character count, it would be helpful for clients and libraries if it did. This would reduce client code complexity and number of requests required when dealing with misskey and other backends such as pleroma which currently reports it as "max_toot_chars"

# Environment

**Comment by acid-chicken** [comment]
Mastodon Compatible API is dead.
