### ISSUE TITLE
cant follow pixelfed users

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3996]
# Summary

it is impossible to follow pixelfed (or maybe just pixelfed.social?) users

# Expected Behavior

follow user

# Actual Behavior

user not followed and ``deliver failed: 500 Internal Server Error to=https://pixelfed.social/users/user/inbox`` in server log

# Steps to Reproduce
1. open a pixelfed user from your instance
2. click follow
3.

# Environment

**Comment by mei23** [comment]
In my case
`misskey:activitypub:deliver https://pixelfed.social/users/:user/inbox --> 404`
got 404 instead of 500

**Comment by Johann150** [comment]
I'm not sure if this has already been fixed before, but it definitely works with #8635 applied.

**Comment by mei23** [comment]
Maybe it's already fixed.
It worked at least on 12.110.1.
