### ISSUE TITLE
Packedなobjectのtype定義を用意して使用する

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4018]
# Summary
現状、Pack (API向けにNote等のEntitiyを返している部分) はanyで回しているが
これをIPackedNoteのような専用のtypeにする。
→ そのtypeはAPIドキュメントに記述するEntityと一緒になるので、APIドキュメント保守しやすくなることを期待。

現状、PackではDBのModelから不要なものを削除しているが、
これを必要なプロパティのみIPackedNoteのようなものにコピーするようにする。
→ 不要なものを削除するという方法だと、消し忘れた時に漏洩するリスクがある。
→ 不要なものを削除→条件に一致しない場合は削除→NOTやORだらけになって感覚的にわかりづらくなる。

# Environment

**Comment by acid-chicken** [comment]
Related to #3622

**Comment by acid-chicken** [comment]
現状DBのインターフェースに刺さってる子達の名前を`IHoge`から`IHogeModel`に改名して、`IHoge`をPackedなインターフェースに置き換えるのはどうでしょうか。

**Comment by syuilo** [comment]
一度Packしたものはすぐレスポンスとして返す場合がほとんどで、サーバー内でPackしたものの型情報を参照することはDBから取得した生の状態のものと比べると少ないので、型を定義するとしたらめいめいが言及したように新たに IPackedNote のようにするのがいいと思ってます

**Comment by acid-chicken** [comment]
ではその方向で。
