### ISSUE TITLE
サイレンスの実装

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#4021]
サイレンスはログイン、自分のプロフィールの編集、他のユーザーへのリアクション等はできるが、投稿とファイルのアップロードはできない。

**Comment by vandojapan** [comment]
サイレンスは強制鍵ノート(LTL,STL非表示)、リアクション可能で、凍結を閲覧、アカウント設定のみ、リアクション不可にすればよいのでは。
いきなり凍結されては、フォローリストのエクスポート諸々ができなくなってしまいます。
~~そもそもインターネットやめたほうがいいですが~~

**Comment by syuilo** [comment]
そのユーザーが強制鍵かどうか/リアクション可能かどうか/投稿可能かどうか などを個別に設定できるのが良さそう

**Comment by syuilo** [comment]
Related to https://github.com/syuilo/misskey/issues/3068

**Comment by acid-chicken** [comment]
> そのユーザーが強制鍵かどうか/リアクション可能かどうか/投稿可能かどうか などを個別に設定できるのが良さそう

はいいんです？
