### ISSUE TITLE
処罰に関するデータを格納するコレクションを作る

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#4026]
現状、凍結などの情報は各ユーザーの属性として保持されているが、

* #3864
* #4021
* #4022

などを実装する際に、Punishmentsコレクションがあると良さそう。

* 対象ユーザー
* 処罰の種類
* 理由
* 処罰内容の開始日時
* 処罰内容の終了日時
* 処罰を行った人
* 処罰を行った日時

などの情報をもたせると良さそう。

**Comment by AyaMorisawa** [comment]
期間の情報(無期限も含む)を保持していくことで、処罰の履歴が残るという点でもあった方が良さそう。

**Comment by tamaina** [comment]
モデログを実装済
