### ISSUE TITLE
public以外の投稿を参照している場合はローカルタイムラインに出さないようにする

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4062]
# Summary
現状、Renote, Reply, Quote先が非publicであっても、publicでpostすればローカル/グローバルTLに表示されるが、
元の公開範囲を尊重していないし、これを利用することによりサイレンスを破れてしまう。

1. public の Renote/Reply/Quote先 が public以外 だったら、ローカル/グローバルに表示しない
2. public の Renote/Reply/Quote先 が public以外 だったら、public => homeにしてしまう

みたいな対応がしたい

また、Renote, Reply が ローカルに表示されないMastodonではこの問題が起きないので
Renote, Reply を ローカルに表示しなくするという方法もありそう。

# Environment

**Comment by syuilo** [comment]
なるほど。MastodonではRenoteやReplyがローカルに表示されないのは知らなかったです。それもいいかもしれませんね

**Comment by syuilo** [comment]
とりあえずは
public の Renote/Reply/Quote先 が public以外 だったら、public => homeにしてしまう
をしたいと思います
