### ISSUE TITLE
Video Thumbnails dont work

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#4065]
# Summary

Video thumbnails do not work. They video shows as black in misskey and the thumbnail url leads to the video itself

# Expected Behavior

Create thumbnail from first frame of video and have thumbnail endpoint point to that

# Actual Behavior

Thumbnail endpoint points to video

# Steps to Reproduce
1.
2.
3.

# Environment

**Comment by acid-chicken** [comment]
Related to #3909
