### ISSUE TITLE
Import emoji from url or file

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#4083]
# Summary

Sometimes you want to add a whole lot of emoji, and rather than doing it by hand it would be easier to have a file that has the emoji name and url for each new emoji on separate lines.
Being able to upload a file laid out in such a way, and to import the same formatted file from a url, would be very nice

# Environment

**Comment by Johann150** [comment]
I think importing emoji from a file is possible since 7e5e763584acd80b1baef6af2d20621c89fa0af9. I think if we document the format a bit better (probably misskey-hub) this issue can be closed.

**Comment by Johann150** [comment]
The format has been documented in https://github.com/misskey-dev/misskey-hub/commit/afb3fa53c50c6803e67e6f39adeb95429c75953f. Please refer to there for instructions on batch-importing emojis from a file.
