### ISSUE TITLE
トークで最新の投稿が隠れてしまう

### ISSUE THREAD

**Issue by argxentakato** [misskey-dev/misskey#4092]
このように表示されるが
![screenshot_2019-02-02 misskey](https://user-images.githubusercontent.com/14871483/52163236-b2952180-2722-11e9-8ced-270d14773cf7.png)

本来はもっと表示しなければならない。
![screenshot_2019-02-02 misskey 1](https://user-images.githubusercontent.com/14871483/52163235-b2952180-2722-11e9-8faa-77f769fc16f2.png)

**Comment by syuilo** [comment]
ブラウザはなんですか？

**Comment by argxentakato** [comment]
Firefox developer edition 66.0b3です

**Comment by EbiseLutica** [comment]
Firefoxにおいて既知の不具合ぽい　以前から起きてる

**Comment by rinsuki** [comment]
`/i/messaging/username` だと再現しない
