### ISSUE TITLE
setupドキュメントの通りに構築すると謎ユーザーが作成されてしまう

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4093]
# Summary
[docs/setup.ja.md](https://github.com/syuilo/misskey/blob/aa47b6732d379079b313497d3894ee09f1dc9169/docs/setup.ja.md) の通りに
> db.users.save( {dummy:"dummy"} ) ダミーデータを書き込みDBを初期化

を行うと謎ユーザーが作成されてしまう。

![image](https://user-images.githubusercontent.com/30769358/52163385-add16d00-2724-11e9-82a5-466c167318a7.png)

ダミーデータの書き込み自体行わなくても何の問題もないはず

# Expected Behavior
謎ユーザーは作成されず出てこない

# Actual Behavior
ユーザー一覧に`undefined`というユーザーが出てきてしまう

# Steps to Reproduce
1. setupドキュメントの通りに
    > db.users.save( {dummy:"dummy"} ) ダミーデータを書き込みDBを初期化`

    を実施して構築
2. 構築後、管理画面→ユーザーへ行き`ローカル`でフィルタする
3. `undefined`というユーザーが出てきてしまう

# Environment

**Comment by mei23** [comment]
ダミーデータ入れなくても問題なくユーザー作成できて動きますね

**Comment by mei23** [comment]
そこのMongoDBの部分の手順自体、いろいろ気になるところが
- `ルートで:`とはOSのrootなのこと？OSのユーザーは関係ないのでは
- adminユーザーを作ったり、できれば認証を有効にしたりしなくていいのか
- createUserの前にadminで認証しなくていいのか

**Comment by acid-chicken** [comment]
（今までダミーデータ作ったことなかったので内心驚いてます。というかCIダミーデータ作成してないような………？）

**Comment by argxentakato** [comment]
実際のところ、dockerではこの手順は実行されていないはずです。何か影響があるのか今一つわかりませんね。

**Comment by syuilo** [comment]
謎ユーザーが作成されると、autoAdmin機能(初めて作ったアカウントを自動でアドミン設定にする機能)が発動しなさそうですね
