### ISSUE TITLE
ユーザーごとにメールアドレスを付与

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#410]

**Comment by otofune** [comment]
- SMTPという仕組みでインターネットメールは出来てるのでそれをどうにかNode.jsで実現するかメールサーバー使うか (Node.jsで実現したい)
- MXレコード設定が必要な旨をドキュメントに記す
- メールデータベースのスキーマ制定
- OP25Bのため追加機能とするほうが良いと思う
- 運用の問題として25ポート待受が必要なのでLinuxではrootで動作させるか、ポートフォワード機能を利用するか、capability機能を使う必要がありしんどいかも  
参考: http://nojima.hatenablog.com/entry/2016/12/03/000000

**Comment by syuilo** [comment]
ありがとうございます🍮
私もできればNodeで完結させたいけどSMTPもといEメールの知識が乏しいのが問題
