### ISSUE TITLE
[MFM] 文字を隠す機能

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#4106]
Discord に最近追加された `|| lorem ipsum ||` 記法のように、部分的に文字列を隠す機能

CWと機能被るかもしれないけど

**Comment by rinsuki** [comment]
リモートで反映されないことを考えるとCW一本にしたほうがいい気がする(それを言うなら`~~`記法も廃止するべきだけど)

**Comment by EbiseLutica** [comment]
多分いらない
