### ISSUE TITLE
APNGがアニメーションしなくなってしまう

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4108]
# Summary
PNGについてはweb公開用やthumbnail用に、リサイズ/メタデータ削除等の処理を行っているが
そのタイミングでAPNGのアニメーションがなくなってしまう。

# Expected Behavior
少なくともweb公開用はアニメーション保持してほしい

# Actual Behavior
アニメーションしなくなってしまう

# Steps to Reproduce
1. APNGをアップロード
2. 投稿してサムネイルや拡大画像を閲覧する

# Environment

**Comment by syuilo** [comment]
Fixed

**Comment by mei23** [comment]
なおしてないはず

**Comment by syuilo** [comment]
Fixed

**Comment by mei23** [comment]
10677b57d444c45696bd99bb021ca5ddce1a511f

MINE type が `image/png` => `image/apng` になるのは大丈夫なのかしら
https://github.com/syuilo/misskey/issues/4728#issuecomment-501952347

**Comment by mei23** [comment]
`image/png`直指定でなんかしてるところがあるみたい

**Comment by acid-chicken** [comment]
`image/apng` がそもそもアウトでは

**Comment by mei23** [comment]
APNG自体対応してない場合はPNGとして扱える構造だったと思うので
互換を考えると表に出すのは`image/png`でよさそう
