### ISSUE TITLE
アイコンやカスタム絵文字のgifを再生しないオプション

### ISSUE THREAD

**Issue by ne-moni** [misskey-dev/misskey#4112]
# Summary
激しい点滅を伴うものもあるため
「投稿内の動きのあるテキストを無効にする」オプションとは別で実装してほしい

**Comment by syuilo** [comment]
Related to https://github.com/syuilo/misskey/issues/2175

**Comment by mei23** [comment]
対象としたい今アニメーションする画像
- 投稿画像のアニメーションGIF
- アバターのアニメーションGIF
- カスタム絵文字のAPNG

画像を保存する時にアニメーションしない版も作って使用する方法で実装していったもののイマイチ
- 過去に保存した画像に対応できない、過去に保存した画像と同じハッシュの画像にも対応できない
- カスタム絵文字のAPNGは保存を経ないので対応できない
- 直リンモードで効かない

なので以下のような方法が取れないかと検討
1. 画像のURLを指定するとアニメーションの場合は停止して送り出してくれるAPIを実装してそれを利用する
2. またはそんなクラウドサービスを探す

**Comment by mei23** [comment]
まだ抜けがある…
- リプライ先投稿
- ストリーミングで配信された時
