### ISSUE TITLE
フォロー/ブロック/ミュートのエクスポート機能

### ISSUE THREAD

**Issue by vandojapan** [misskey-dev/misskey#4151]
# Summary

フォロー/ブロック/ミュートをCSVでエクスポートしたい。
# Environment

Google Chrome 72.0.3626.81
Windows 10 Pro

**Comment by acid-chicken** [comment]
> CSVでエクスポートしたい。

27d16c6a120d05e69eb069035a851c48c44548c5 で実装されたのはJSON形式。

**Comment by syuilo** [comment]
json形式ではないです

**Comment by acid-chicken** [comment]
https://github.com/syuilo/misskey/blob/27d16c6a120d05e69eb069035a851c48c44548c5/src/queue/processors/export-mute.ts#L84

えっこれJSONじゃないの

**Comment by syuilo** [comment]
拡張子のミスで、中身はCSVです
拡張子はその後のコミットで修正しました

**Comment by acid-chicken** [comment]
理解しました。
