### ISSUE TITLE
ジョブキューが有効だと挙動がおかしくなる

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4156]
極端に重くなったり

**Comment by syuilo** [comment]
おそらく複数のサーバーでクラスタリングしてる場合にひとつのジョブを複数のサーバーで捌いてしまうからだと思われる

**Comment by syuilo** [comment]
いやそんなことないかも

**Comment by syuilo** [comment]
キューが詰まってる可能性がある

**Comment by mei23** [comment]
1サーバー (Master 1プロセス, Worker複数プロセス) でもキューが詰まる

**Comment by mei23** [comment]
おかしくなると
1サーバー (Master 1プロセス, Worker 1プロセス) でもキューが動かなくなってしまって
キューを無効にするしかなくなるみたい

**Comment by acid-chicken** [comment]
原因わかるまでとりあえず強制無効にした方がいいかもしれませんね……。

**Comment by syuilo** [comment]
Fixed
