### ISSUE TITLE
ドライブ内でファイルを指定の場所に移動できるオプション

### ISSUE THREAD

**Issue by ne-moni** [misskey-dev/misskey#4161]
# Summary
OnedriveやGoogleDriveにあるようなもの
出来れば個別選択だけでなくCtrlキー等を使った複数ファイルの移動にも対応していただきたい

ファイルを右クリックして出てきたメニューから「移動」を選択、
表示されたドライブ内の階層から移動先のフォルダを確定するとファイルが移動される

**Comment by 4ioskd** [comment]
Duplicate of https://github.com/misskey-dev/misskey/issues/7719

ドライブがmisskeyの主要機能の一つであるなら、廃止された複数ファイルの選択機能だけでなく、ドライブの機能を増やすことは大事なことのように思えます。

**Comment by tamaina** [comment]
Duplicateではない

**Comment by 4ioskd** [comment]
ふむ...これは勘違いしました。失礼。
