### ISSUE TITLE
configのdriveのチェック仕様が変更されている

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4180]
# Summary
#4170 で configのdriveの項が必須としてチェック＆取得するように変更されているが、
以前はoptionalであり実装自体も互換性を維持する形になっているので
この変更が適用されると動かないconfigが存在する可能性がある。

互換性を維持してoptionalのままにするか、CHANGELOGに記載する等が必要。

# Expected Behavior

# Actual Behavior

# Steps to Reproduce

1.
2.
3.

# Environment

**Comment by syuilo** [comment]
#4170に関するコミットをRevertしました。

**Comment by acid-chicken** [comment]
あとで私が書き直してもよろしいですか？

**Comment by syuilo** [comment]
ごめんなさいインターネット回線が遅くてまだプッシュできてませんでした

**Comment by acid-chicken** [comment]
ごめんなさい、 bf964ee969abe27ba26432addf53d78add1e176b とコンフリクトするかも。

**Comment by syuilo** [comment]
> あとで私が書き直してもよろしいですか？

ありがとうございます。ではお願いできますか＞＜
