### ISSUE TITLE
リアクションが付いた時のエフェクトが消えている

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4186]
アイコンが上昇するエフェクト

**Comment by mei23** [comment]
たぶん、新規出現時だけダメですね (カウントアップなどはOK)

旧: リアクションが出現してなくても、常に10個分のリアクション数をwatchしてanimeしていた
新: 出現済みのリアクションの数をwatchしてanimeしている

このあたりで新規出現時にもanimeできるようにしたりすれば良さそう
https://github.com/syuilo/misskey/blob/72b85fc09fe9ef65f30abb4d7096c009bd8e09a7/src/client/app/common/views/components/reactions-viewer.reaction.vue
