### ISSUE TITLE
リアクション表示の順序がおかしい

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4188]
# Summary

# Expected Behavior

# Actual Behavior

# Steps to Reproduce

1.
2.
3.

# Environment

**Comment by acid-chicken** [comment]
どんな感じですか？

**Comment by syuilo** [comment]
👍❤️
と表示されるべきところ
❤️👍
となる

**Comment by mei23** [comment]
たぶん、リファクタでされた順 (DBにキーが登録された順) で表示されるようになってますね

**Comment by acid-chicken** [comment]
（Streamでリアクションが増えることで押し間違えるといったようなことが起こりにくくなると考えるとそっちの挙動のほうがいいかもしれませんね。）

**Comment by syuilo** [comment]
とりあえずこのままで
