### ISSUE TITLE
The game page shows string IDs instead of the local strings when opened in a new browser.

### ISSUE THREAD

**Issue by fz0000** [misskey-dev/misskey#4189]
# Summary
The game page shows string IDs instead of the local strings when first opened.

# Steps to Reproduce

1. Open Chrome browser and go to Ai's personal page(https://misskey.xyz/@ai).
2. Find a game note which is posted by Ai.
3. Click "観戦する" to open the game and copy the url. (e.g. https://misskey.xyz/games/reversi/5c5cf1a816bd230028be18b5)
4. Clear the cache and cookies if needed.
5. Close all tabs and re-launch the browser.
6. Input the game url to go to the game.
7. Check the strings on the page.

# Expected Behavior
The page should be localized correctly.

# Actual Behavior
The strings on the page are string IDs. Please refer to the screenshot below:

![game](https://user-images.githubusercontent.com/5061311/52473989-2c6d5500-2bd2-11e9-94c0-7382d0ac28ba.PNG)

# Environment
OS: Windows 10 x64 CHS RS4 build 1803.
Browser: Chrome 72.0.3626.96

# Additional Infomation

1. This issue does **not** occur on Edge and Firefox.
2. Reloading the page will resolve the problem.

**Comment by acid-chicken** [comment]
@fz0000 Good catch! Thank you for reporting this problem to us.

Memo
--

> 4. Clear the cache and cookies if needed.

Misskey localization data was deleted at the above step.

> 6. Input the game url to go to the game.

Oh no, it seems a Chrome bug!

**Comment by fz0000** [comment]
Additional Infomation:
It seems that this issue will occur on any page on Chrome:

Steps:
1. Log in.
2. Clear cache files (no need to clear cookies).
3. Close and re-open Chrome.
4. Go to https://misskey.xyz

<img width="932" alt="string_id" src="https://user-images.githubusercontent.com/5061311/53356169-c28cd380-3965-11e9-98d9-5c94e453b949.png">

**Comment by fz0000** [comment]
This issue seems to have been fixed? The web pages is loaded correctly now.
