### ISSUE TITLE
User specific Instance Blocking

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#4190]
# Summary

One feature that has come up on my instance recently is the lack of per user instance blocking. Other backends provide users with the ability to block specific instances from showing on any timelines  for them without the instance they are on blocking it entirely. This is favourable as often an instance may not break any of the local instances rules and may be acceptable to the majority of users, but harmful for specific users.

**Comment by Johann150** [comment]
fixed by #7712
