### ISSUE TITLE
ドキュメントの分離

### ISSUE THREAD

**Issue by argxentakato** [misskey-dev/misskey#4222]
# Summary
なにかしらの拍子で頻繁にドキュメントが閲覧不可能になってしまうので、クライアント開発の難易度が高い。API blueprintやWikiなどを用いて、インスタンスと完全に分離し、別に管理するべきだと考える。

## メリット
- インスタンス本体が落ちても、ドキュメントを閲覧できる
- コード量を削減できる
- ビルド時の負担を減らせるかもしれない(?)

## デメリット
- めんどうくさい
- どこでホスティングするか検討しなければならない
- ドキュメントの更新がmisskeyの変更に追いつけないかもしれない

**Comment by tamaina** [comment]
~~ドキュメント分離のせいでドキュメントの参照が切れたパターンが多いんだけどまあいいや~~
