### ISSUE TITLE
serviceWorker cannot be enabled

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#4223]
# Summary

if you follow the instructions in the default config file, generating vapid key and filling in the config file options, then check the instance panel in admin, you see serviceworker is disabled. ticking to enable then pressing save just keeps it as disabled. as such, serviceworker is broken/unusable

# Expected Behavior

serviceworker can be enabled

# Actual Behavior

serviceworker cant be enabled

# Steps to Reproduce

1. generate and paste vapid keys
2. restart
3. tick enable for serviceworker in instance admin panel

# Environment

**Comment by syuilo** [comment]
Fixed
