### ISSUE TITLE
DB キューがほしい

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#4232]
原因不明ですが、最近MongoDBのCPU使用率がすごい事になって、DBがフリーズしているとMisskey全体がフリーズしてしまうため、表面上はDBに記録したように見せて各インスタンスに投稿データを送信し、実際はDBへの保存はできるタイミングでする機能がほしい。

**Comment by SanMurakami** [comment]
![putty_2019-02-13_03-55-55](https://user-images.githubusercontent.com/37681609/52661240-f4a13d00-2f44-11e9-950b-5c5059d5f7cc.png)

**Comment by syuilo** [comment]
難しいし最近ではCPU使用率がすごい事になることなさそうなので見送り
