### ISSUE TITLE
リストのインポートとエクスポート

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4259]
# Summary

**Comment by syuilo** [comment]
Mastodonがどういう形式でエクスポートするのか知りたい
(いろいろ試したけど中身が空のファイルしかダウンロードされない)

**Comment by mei23** [comment]
> (いろいろ試したけど中身が空のファイルしかダウンロードされない)

それだわ

**Comment by mei23** [comment]
> Mastodonがどういう形式でエクスポートするのか知りたい
> (いろいろ試したけど中身が空のファイルしかダウンロードされない)

Mastodon (v2.7.4 ?) でなおってました

**Comment by ghost** [comment]
See also #1736

**Comment by syuilo** [comment]
エクスポートはできるようになりました

**Comment by syuilo** [comment]
インポートもできるようになった
