### ISSUE TITLE
/deck のURLを直接叩くと404

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4267]
# Summary
/deck のURLをアドレスバー等に入れてアクセスすると404になる

# Expected Behavior
deckが表示される

# Actual Behavior
Not foundになる

# Steps to Reproduce
1.
2.
3.

# Environment
Desktop, 10.85.0, Windows 10, Firefox 65

**Comment by syuilo** [comment]
ダークモードみたいに、デッキかそうでないかを切り替えるようなシステムになった

**Comment by mei23** [comment]
えぇ…

**Comment by mei23** [comment]
飛ばしちゃうしかない…
