### ISSUE TITLE
ナビゲーションバーを横にしてるとデッキに行けない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4268]
# Summary
ナビゲーションバーを横にしているとデッキに遷移できずにNot foundになる

なお、ハイライトボタンもない

# Expected Behavior
デッキに遷移できる

# Actual Behavior
Not found画面になる

# Steps to Reproduce
1. Desktopでナビゲーションバーの位置を左か右にする
2. デッキボタンを押す
3. Not found画面になる

# Environment
Desktop / 10.85.0 / Windows 10 / Firefox 65

**Comment by syuilo** [comment]
修正しました
