### ISSUE TITLE
デッキでカラムをドラッグできなくなっている

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4273]
# Summary

# Expected Behavior

# Actual Behavior

# Steps to Reproduce

1.
2.
3.

# Environment

**Comment by mei23** [comment]
Windows 10 / Firefox 65 => OK
Windows 10 / Chrome 71 => NG

**Comment by acid-chicken** [comment]
@syuilo Environment 書いてほしいです。

**Comment by mei23** [comment]
Windows 10 / Firefox 65 => ドラッグできるが、読み込み直すまで反映されない
Windows 10 / Chrome 72 => ドラッグできない、読み込み直しても変わらない
みたい

**Comment by argxentakato** [comment]
Linux 4.19.31-1-lts / Awesome WM / Firefox 67でも同様の現象を確認。やはり、再読みこみするまで反映されない。

**Comment by rinsuki** [comment]
macOS 10.14.4 / Firefox 67.0b17 (Developer Edition) で読み込み直すまで変わらないのを確認
![out](https://user-images.githubusercontent.com/6533808/57294222-eefd6280-7101-11e9-945f-1d673452b19f.gif)
