### ISSUE TITLE
[misskey.xyz] specific: local timeline is [disabled]

### ISSUE THREAD

**Issue by marek-lach** [misskey-dev/misskey#4275]
# Summary
Observed this on the misskey.xyz since a few days (few Misskey versions ago). The message that Local timeline is down means that it has been optionally disabled.
<img width="1280" alt="screenshot 2019-02-15 at 14 04 05" src="https://user-images.githubusercontent.com/45913977/52858590-d5640480-312a-11e9-9e0e-6f6126bcd756.png">

# Expected Behavior

Loads 'Local' timeline as well as it does the others.

# Actual Behavior

Cannot connect to local timeline. Best visible in the 'Deck' view. This issue seems to not affect http://misskey.m544.net instance for example.

# Steps to Reproduce

1. Login to misskey.xyz
2. Switch to deck view
3. Local timeline has trouble to connect? (It has been optionally disabled by the admin).

# Environment

OSX 10.14, Firefox 66b7. Observed since about Misskey 10.84 or so?

**Comment by EbiseLutica** [comment]
Just to be sure, misskey has a feature to disable local-timeline. Now misskey.xyz disables it by the admin.

However, I think "Someting happened :(" message at this context is not kind for end-user. Therefore, app should display a message like "Local-timeline is disabled now" when the timeline is disabled.

**Comment by acid-chicken** [comment]
@Xeltica Yes, you are right. So I'll make this message better.

**Comment by marek-lach** [comment]
I understand now, thank you for explaining this. Feel free to close this issue now as resolved, whenever you wish.
