### ISSUE TITLE
インスタンスとサーバーの表記ゆれを統一する

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#4285]
# Summary

どちらに合わせますか。

**Comment by mei23** [comment]
「サーバー」を使用している箇所は、ほぼインスタンスのサーバーノードのうちの1つという意味で使われているので、現状ほぼ「インスタンス」に統一されている気がする。

**Comment by acid-chicken** [comment]
これとかは正しい用法ですか？

https://github.com/syuilo/misskey/blob/b6c86e284584ba174bc80d29de019e4213582860/locales/ja-JP.yml#L951

**Comment by mei23** [comment]
@acid-chicken そこも含めて数カ所は変なところ (インスタンスの意味でサーバーになってる) はあると思う

**Comment by acid-chicken** [comment]
そこら辺統一したい。

**Comment by mei23** [comment]
インスタンスの意味でサーバーを使っている場所が1か2箇所ある程度に見えるので
そこだけインスタンスに寄せてしまえばいいのではと思ってます。
