### ISSUE TITLE
デッキ使用中にホーム扱いで開かれた時にタイムラインボタン等がない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4292]
# Summary
デッキ使用中に別タブでユーザーページ等を開いたときにはデッキにしないように #4291
の状態で「タイムライン」ボタンがなかったり、切り替えリンクの先がホームだったりする。

# Expected Behavior
「タイムライン」ボタンがある
切り替え先が「デッキ」

# Actual Behavior
「タイムライン」ボタンがない
切り替え先が「ホーム」

# Steps to Reproduce
1. デッキにする
2. ユーザーリンク等を別タブで開く

# Environment
デッキ

**Comment by syuilo** [comment]
やっぱりデッキ状態でも / に戻るときのためにタイムラインボタン表示しませんか？

**Comment by mei23** [comment]
> やっぱりデッキ状態でも / に戻るときのためにタイムラインボタン表示しませんか？

その部分はそれでもいいと思います
