### ISSUE TITLE
リモートのフォロワー数や投稿数などの情報は採用しない

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4299]
代わりにローカル内の実際の値にする
正確とは限らないし、実際に自インスタンスでそれだけのフォロワーが居たりするわけではなくソート時におかしな結果になるため。

**Comment by syuilo** [comment]
別のプロパティに保存しといて、それをユーザーページとかで参考までに表示する程度なら良いかもしれない

**Comment by ghost** [comment]
I want this feature because want to see the remote user's follow and follower... :(

> NOTE: What I want to do is to discover new users through the follow and followers of remote users.
