### ISSUE TITLE
デッキ使用中に / 以外でリロードした際にホームモードになる

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4300]
新規タブで開かれたのかリロードされたのか判別する方法が無さそうなので解決は難しそう

**Comment by mei23** [comment]
あるっぽい
`window.performance.navigation.type`
https://developer.mozilla.org/ja/docs/Web/API/Navigation_timing_API

**Comment by mei23** [comment]
今のモード切替時の動作もリロードになっちゃうので単純じゃなさそう

**Comment by mei23** [comment]
いけたかも
