### ISSUE TITLE
developでビルドすると動かない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4309]
# Summary
developでビルドするとassetsが読み込めずページが表示されない

# Expected Behavior
表示される

# Actual Behavior
表示されない
# Steps to Reproduce
1. `npm run clean` `npm run build` `npm run start`
2. ブラウザで開く
3. desktop~.js の読み込みが404になりページが表示されない

# Environment
10.87.2
Firefox, Chrome

**Comment by acid-chicken** [comment]
てか生成されてますかねこれ……。

**Comment by acid-chicken** [comment]
![image](https://user-images.githubusercontent.com/20679825/52930738-faf04880-338c-11e9-9c3a-e89d7873f763.png)
過度にclientVersionを廃止しすぎている。
