### ISSUE TITLE
Fallback strings are not displayed in the header of main page.

### ISSUE THREAD

**Issue by fz0000** [misskey-dev/misskey#4312]
# Summary
Fallback strings are not displayed in header of the main page.
# Steps to Reproduce

1. Set the language of the browsder to non-japanese.
2. Open https://misskey.xyz/
3. Check the strings on the header of the web page.

# Expected Behavior
It should show the fallback strings.
(The fallback language is en-US. And this issue will occur if there is no translated string in en-US.yml. Could we update the related code in boot.js to show the original japanese strings when there is no english strings? Or just use ja-JP as the fallback language...)

# Actual Behavior
It shows the string ID.
![header](https://user-images.githubusercontent.com/5061311/52930864-20795400-3385-11e9-8732-c3b2507f265f.jpg)

# Environment

**Comment by acid-chicken** [comment]
Related to #4109

**Comment by fz0000** [comment]
Oh thanks. Will wait for it to be merged.

**Comment by syuilo** [comment]
Fixed. Thank you guys
