### ISSUE TITLE
検索結果に鍵付き投稿が表示される

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#4320]
[参考](https://misskey.xyz/notes/5c6b90d54f5f56002736ee4f)

![image](https://user-images.githubusercontent.com/7106976/52993091-3efb5000-3456-11e9-9b9e-c3eae24b46fe.png)

**Comment by acid-chicken** [comment]
Seems duplicate of #1700.

**Comment by EbiseLutica** [comment]
#1700 と完全に重複していますね。閉じます。
