### ISSUE TITLE
.m4a オーディオファイルが動画プレイヤーを使って表示される

### ISSUE THREAD

**Issue by m-hayabusa** [misskey-dev/misskey#4324]
# Summary

`.m4a` (MP4コンテナにオーディオのみの) ファイルが動画ファイルとして扱われる
(動画ファイルに音声のみが含まれている(=動画が含まれていない)場合にオーディオとして取り扱うべき？)

# Expected Behavior

`.m4a` ファイルは、他の音楽ファイルと同じように音声として表示されるべき

# Actual Behavior

`.m4a` ファイルは動画(`video/mp4`)として認識されるため、(タイムライン上などで)動画として表示される

# Steps to Reproduce

1. [m4aのオーディオファイル](https://objects.misskey.mewl.me/files/170cd91f-9710-4ea1-822d-e8f494e09d30.m4a)を作る
2. Misskey Driveへアップロード、ノートに添付して投稿する
3. その投稿を見る もしくは Misskey Driveでホバーするなどしてファイルタイプを確認する

# Environment

Misskey 10.82.2

**Comment by mei23** [comment]
@acid-chicken Sub-typeを見て判別しようとしてると思われますが、それでは無理と思います。

まず`m4a`と呼ばれるものとして2種類あると思われます

A. m4aコンテナのファイル (Sub-type: M4A)
![image](https://user-images.githubusercontent.com/30769358/53061505-33189800-3501-11e9-91a7-e20a45628799.png)

B. mp4コンテナにオーディオのみ (Sub-type: mp42) 本当はm4aではない
![image](https://user-images.githubusercontent.com/30769358/53061474-1bd9aa80-3501-11e9-97ac-6d65eb3fce61.png)

今回上で挙げられているものはBのものになります

A. m4aコンテナのファイルに関しては、audioとして認識されています。
B. mp4コンテナのファイルに関しては、videoとして認識されています。
(Sub-typeはあくまでもvideoであるため MIME-type 上はこれでValied)

Bを判別しようとすると、先頭12バイトのSub-typeの判定では無理と思います。
また、格納する情報として`MIME-type`以外に`audio or video どっちとして扱いたいか`の情報が必要になります。

**Comment by mei23** [comment]
たぶん正しくはこう

### Summary
videoとaudio双方を含められるコンテナを使用している場合、コンテナにvideoが含まれてなくても常に動画として扱われる。

### Expected Behavior
videoが含まれていなくてaudioのみならば音声として扱って欲しい。(最終的にクライアントでは音声プレイヤーにしたい)

### Actual Behavior
videoとaudio双方を含められるコンテナを使用している場合、コンテナにvideoが含まれてなくても常に動画として扱われる。
