### ISSUE TITLE
公開範囲がホームの投稿はハイライトに載せない

### ISSUE THREAD

**Issue by Simirall** [misskey-dev/misskey#4325]
# Summary

**Comment by syuilo** [comment]
フォロワーのみの公開範囲を除外するだけで良さそう

**Comment by Simirall** [comment]
ホーム投稿はフォロワーのTLに流したいのに付ける（と思われる）やつだから全員が見れるハイライトに載せるのは微妙とおもった

**Comment by syuilo** [comment]
フォロワーのTLに流したいときはフォロワー限定を使うはず

**Comment by acid-chicken** [comment]
ホームにしているのはLTLに流したくない的な意図で使うことが多いと思うので、LTLに近い気がするハイライトにも載せない方が良さそうではある。

**Comment by syuilo** [comment]
LTLの話題には合わなそうだからホーム指定する、というような意図で使われることが多いと思うので、ハイライトは掲載までにラグがあってある一定の話題で占められることはほとんどないと思われることから、ホーム投稿があっても不自然ではないと感じる
この投稿を公にしたくないという意図ならフォロワーやダイレクト指定などすると思うので、ホーム指定するときは「公にしたくない」という意図はそこまでない気がする

**Comment by Simirall** [comment]
ホーム投稿は投稿者に興味関心があるユーザーが見る（フォローするorプロフィールにアクセスするorリストに追加する）投稿だと思ったのでその投稿者への興味関心に関係なく表示されるハイライトとは合わないと感じた

**Comment by acid-chicken** [comment]
センシティブな投稿をホームで配信しているユーザーがいたとき、それをハイライトで観測できるようにすると一部の人間を不快にさせかねないという不具合が確認された。

**Comment by syuilo** [comment]
センシティブな投稿を全体公開で投稿するユーザーもいるだろうからそれはまた別の(CWやNSFWを活用しない、又はそれらが付いた投稿をハイライトに載せない)問題かも

**Comment by acid-chicken** [comment]
センシティブな内容を投稿する前提でアカウント運用をすると決めているユーザーに公開範囲のデフォルト変更に加えて毎回CWつけろというのは少し酷な要求な気がする。
公開で投稿する人は（当然運用者の方針によって多少変わってくるとは思うが）サイレンスなどの制裁を受けそう。

**Comment by Simirall** [comment]
そういえばサイレンスもホーム投稿だからハイライトに載る可能性あるのかな

**Comment by syuilo** [comment]
サイレンスされてるユーザーの投稿がハイライトに載るのも不自然なように感じるし、たとえサイレンスでもそれだけリアクションやRenoteされるなら価値のある投稿の可能性が高いのでハイライトに載せても良いようにも感じる

**Comment by acid-chicken** [comment]
それサイレンスの意味あるんですか……？

**Comment by syuilo** [comment]
LTLに流れないので意味ありそう

**Comment by khws4v1** [comment]
横から失礼します。

公開範囲をホームに設定するとき、UIには

![_026](https://user-images.githubusercontent.com/11152868/53170455-779c5480-3623-11e9-8bba-1950a6d0922b.png)
> ホームタイムラインにのみ公開

と表示されています。  
それにも関わらずハイライトに掲載してしまうのは、ユーザーにとって予期しない動作ではありませんか？

**Comment by Simirall** [comment]
RNとかリアクションが多い＝価値のある投稿というのは必ずしもそうではなさそう（このコメントは特定の投稿を示唆しているものとは言っていません😇）

**Comment by acid-chicken** [comment]
例えばNSFW投稿であったり、意図的なリアクション水増しステマなどがサイレンスによる制裁を受けてもハイライトに掲載される可能性が十分にあるわけで、いちいちモデレーターが投稿を対処したりするのも面倒そう。

**Comment by syuilo** [comment]
RNとかリアクションが多い＝価値のある投稿というのは必ずしもそうではない
というのは公開範囲に関係ないことなので、ハイライト機能そのもののIssueになりそう。

**Comment by mei23** [comment]
> サイレンス

その人が意図して見ようとしなければ見れないというレベルになってる
(じゃあハイライトにも載せない方がいい気がするわ)

**Comment by syuilo** [comment]
「ホームタイムラインのみに公開」というのは文章の誤りで、実際には「LTLに公開しない」という意味ですね(ユーザーページや検索にも表示されるので)

**Comment by syuilo** [comment]
(あとリストにも表示されたはず)

**Comment by syuilo** [comment]
ではホーム指定の投稿はハイライトから除外するので良さそうですが、センシティブな内容の投稿がハイライトに載ってしまう問題は残ったままですね それは別に考えましょう

**Comment by acid-chicken** [comment]
（New Issue: モデレーターが投稿の評価値を編集する機能とか？）

**Comment by syuilo** [comment]
そのユーザーをサイレンスにするだけで良さそうかも

**Comment by acid-chicken** [comment]
それはそう
