### ISSUE TITLE
Viewing Profiles in Deck Shows Wrong Posts

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#4333]
# Summary

When you open a user in the dock, then open another user, the posts of the second user are all replaced with the posts of the first

# Expected Behavior
show the posts of the second user

# Actual Behavior

the posts of the first user stay

# Steps to Reproduce

1. enter deck view tih transitions disabled
2. click one user
3. click a second user

# Environment

**Comment by mei23** [comment]
Activity と Photos も該当していて直ってないようにも見える
