### ISSUE TITLE
Lookup User in admin page Doesnt Work for Admins

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#4334]
# Summary

If you use the lookup user button it fails to display any information for users marked as admin, though works normally for other users

# Expected Behavior

Display user details

# Actual Behavior

simply clears the field

# Steps to Reproduce

1. make a user admin
2. type their user and click lookup user
3.

# Environment

**Comment by Johann150** [comment]
I can't reproduce this. I assume it has been fixed.
