### ISSUE TITLE
デッキモードのプロフィール表示バグ

### ISSUE THREAD

**Issue by S4WA** [misskey-dev/misskey#4340]
# Summary
デッキモードにてユーザーのプロフィールを連続で見たとき、アクティビティや画像が前のユーザーのもののまま表示される
![image](https://user-images.githubusercontent.com/24929259/53150902-12ca0580-35f5-11e9-8fab-ebc5fc3d4634.png)

# Steps to Reproduce

1. 適当なユーザーのプロフィールを開く
2. 1番とは違う別のユーザーのプロフィールを開く

**Comment by fz0000** [comment]
By the way, it may be a browser-independent issue. Occurs on both Chrome and Firefox.

Trying to record a video here :
![change_profile](https://user-images.githubusercontent.com/5061311/53163878-000dfb80-360a-11e9-994f-0940c3442254.gif)

**Comment by syuilo** [comment]
Thank you guys. I will fix this issue asap!
