### ISSUE TITLE
Unit Test for ActivityPub

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#4343]
# Summary

CI上で複数のサーバーを立てて正しく通信が行えるかテストする。可能であれば他のActivityPub対応サービスとの通信もテストしたい。

**Comment by acid-chicken** [comment]
Closed by #4206.

**Comment by syuilo** [comment]
なんでcloseされたんだろう

**Comment by acid-chicken** [comment]
ごめんなさい、私がやってもどうせやっても採用されないオチが見えているので……。かといって面倒と言われて他の人もやらないと思うので、立てっぱなしにしたところでIssue一覧の見通しが悪くなるだけ。

**Comment by syuilo** [comment]
そんなこと言ったらなにもできなくなる

**Comment by acid-chicken** [comment]
かといって私以外の誰かがすぐやるわけにはならなさそう。Issue一覧現状すごく見通しが悪いので、本当に必要な部分だけOpenしておきたい。

**Comment by syuilo** [comment]
このIssueはいまあるIssueの中でも重要度が高いと思われるので開いておく価値はありそう
