### ISSUE TITLE
ユーザーページのコンポーネントの統一

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4346]
# Summary
ユーザーページの「アクティビティ」「フォト 」が、場所によって名前や順番が違うのでそろえたい

ホーム
![image](https://user-images.githubusercontent.com/30769358/53217528-a524e480-369b-11e9-8fdd-12aed4344a19.png)

デッキ
![image](https://user-images.githubusercontent.com/30769358/53217539-aa822f00-369b-11e9-9e58-2f949e60b028.png)

モバイル
![image](https://user-images.githubusercontent.com/30769358/53217542-ac4bf280-369b-11e9-9a68-4c5b7e9c327a.png)

**Comment by tamaina** [comment]
GitHubのバグによりRecloseします
