### ISSUE TITLE
Use original file name when download from Misskey drive

### ISSUE THREAD

**Issue by fz0000** [misskey-dev/misskey#4349]
# Summary

The file uploaded to the misskey drive seems to be renamed to a GUID string (e.g. https://pd2.arkjp.net/misskey/drive/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.zip).

Could we use its original name? For example, save the file as`/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/original_name.zip`

**Comment by fz0000** [comment]
Ah... there may be another problem if use the original name: the avatar is also saved in the misskey drive. So renaming the file on the drive may cause some problems...
Maybe a better way is to use dynamic url?

**Comment by SanMurakami** [comment]
It's not recommended to create subdirectories because this method can cause problems with file systems with subdirectory restrictions, such as ex4 directories.
Also, it was previously stored in such a format, but it was abolished because the official server, misskey.xyz, had a problem with the subdirectory.

**Comment by tamaina** [comment]
I think that renaming is inevitable when saving to Misskey server. However, if you use the `download` attribute of the a element in the user interface, you can save it to your computer with the same file name as the original file name. Can you solve your problem with that?

**Comment by fz0000** [comment]
Yes. It's reasonable to use a fixed url for the file on the drive, of course. But it will be very helpful if user don't need to manually rename the file after downloaded.

**Comment by mei23** [comment]
#4523 はオブジェクトストレージ利用時に対応していないので解決してない
