### ISSUE TITLE
プロフィール変更ができない

### ISSUE THREAD

**Issue by S4WA** [misskey-dev/misskey#4356]
![image](https://user-images.githubusercontent.com/24929259/53282760-bfd08980-377f-11e9-9702-9fa25f3f2567.png)

**Comment by acid-chicken** [comment]
@S4WA Could you provide us the reproduce steps?

**Comment by S4WA** [comment]
@acid-chicken 
設定 -> プロフィール -> どこかしらに変更を加え保存
![image](https://user-images.githubusercontent.com/24929259/53283118-c0b7ea00-3784-11e9-911c-7caa87f62dd3.png)

**Comment by S4WA** [comment]
名前、アイコン、バナー、言語は問題なく変えれます

**Comment by mei23** [comment]
このへん
https://github.com/syuilo/misskey/blob/7dd4180fba5a4e3de19e221d206f187fd8e3dfda/src/server/api/endpoints/i/update.ts#L197-L198
https://github.com/syuilo/misskey/blob/7dd4180fba5a4e3de19e221d206f187fd8e3dfda/src/server/api/endpoints/i/update.ts#L212-L213
https://github.com/syuilo/misskey/blob/7dd4180fba5a4e3de19e221d206f187fd8e3dfda/src/server/api/endpoints/i/update.ts#L230-L231

**Comment by acid-chicken** [comment]
@mei23 そこでなぜ途中でundefinedが挟まるのかわからないので片っ端から回ってるところです。

**Comment by mei23** [comment]
@acid-chicken metadataはたまにないですね、昔の何かか データが壊れているのか
とりあえずmetadata, properties はチェックして避けちゃえばいいのではと

**Comment by acid-chicken** [comment]
`properties` はコード読む限りでは必ず存在するみたいです。

**Comment by mei23** [comment]
`metadata` もコード読む限りでは必ず存在するんですよね

**Comment by acid-chicken** [comment]
いえ、`metadata` は Insert に失敗する可能性があるので必ずしも存在するとは言い切れないです。

**Comment by mei23** [comment]
Insertに失敗したならDriveFileもないのではと

**Comment by acid-chicken** [comment]
それもそうか……

**Comment by syuilo** [comment]
ファイル削除したときにmetadetaが消された気がします。

**Comment by acid-chicken** [comment]
可能なら型情報修正して欲しいです。

**Comment by mei23** [comment]
deleteこのあたり
https://github.com/syuilo/misskey/blob/0709cac97f9bab0dc4b9e9b23005248a81505a73/src/services/drive/delete-file.ts#L39%E3%83%BCL53
