### ISSUE TITLE
RSSウィジェットのデフォルトをYahooニュースから変更する提案

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#4362]
現在、MisskeyのRSSウィジェットのデフォルトはYahooニュースです。しかし、Yahooニュースは、国会議員の不祥事の記事のタイトルについて、与党議員の党名を表記せず、野党議員の党名は表記しているという疑惑がもたれています。([議員不祥事「自民は党名抜き、立憲民主なら党名あり」、Yahoo!ニュース見出しの怪](https://buzzap.jp/news/20190221-yahoo-news-topics-ldp-cdp/)) このことから、MisskeyのRSSウィジェットのデフォルトを、Yahooニュースから別のものに変更することを提案します。

代替のRSSフィードとして、[AFPBBニュース](http://www.afpbb.com/list/info/rss/) (`http://feeds.afpbb.com/rss/afpbb/afpbbnews`) を推薦します。

**Comment by syuilo** [comment]
私も以前から、特にコメント欄が俗に言うネトウヨ的な意見が多く適切ではないと感じていたので賛成です
