### ISSUE TITLE
Question: MFMの[]または【】を使った投稿をMisskey以外から見たときの改行の仕様

### ISSUE THREAD

**Issue by khws4v1** [misskey-dev/misskey#4373]
MFMで`[]`または`【】`を使うことで見出しをつける構文がありますが、それを使った投稿をMisskey以外から見たときの改行に関して質問です。

まず、Misskey(10.90.2)でそれを使った投稿を見ると次のようになります。

MFM:
```
テスト投稿1
[テスト投稿2]
テスト投稿3
```

見た目:
![Misskeyでのスクリーンショット](https://user-images.githubusercontent.com/11152868/53410577-9590fd00-3a07-11e9-8c28-95ab98bdf17d.png)

AST in MFM Playground:

```
[
  {
    node: {
      type: 'text',
      props: {
        text: 'テスト投稿1\n',
      },
    },
    children: [],
  },
  {
    node: {
      type: 'title',
      props: {},
    },
    children: [
      {
        node: {
          type: 'text',
          props: {
            text: 'テスト投稿2',
          },
        },
        children: [],
      },
    ],
  },
  {
    node: {
      type: 'text',
      props: {
        text: 'テスト投稿3',
      },
    },
    children: [],
  },
]
```

そして、この投稿をMastodon(v2.7.3)から見るとこのようになります:

![Mastodonでのスクリーンショット](https://user-images.githubusercontent.com/11152868/53410851-4d260f00-3a08-11e9-82c2-8f9e8c0f82f9.png)

「テスト投稿1」と「テスト投稿2」の間に空行があり、「テスト投稿2」と「テスト投稿3」の間に改行がありません。  
これはMisskeyでの見た目と大きく違います。

質問は以下の2点です。

1. Misskey以外から投稿がこのように見えてしまうのは仕様ですか？
2. 現在のMisskeyに「テスト投稿2」と「テスト投稿3」の間で改行させる方法はありますか？

**Comment by syuilo** [comment]
1. これは想定していない動作です。
2. workaroundがあるかは分かりませんが、上述のようにバグなのでまもなく修正されると思います。

**Comment by syuilo** [comment]
どちらかというとMastodonサイドの問題かも

**Comment by tamaina** [comment]
Misskeyから送出されるcontentは以下の通りです(これは /src/mfm/toHtml.ts のtoHtmlを実行結果です):

```
<p><span>テスト投稿1<br></span><h1><span>テスト投稿2</span></h1><span>テスト投稿3</span></p>
```

しかし、Mastodon側のDOMはこんな感じに描画されています: 
![image](https://user-images.githubusercontent.com/7973572/54355454-7d261100-469c-11e9-9752-100dd9754cca.png)

Mastodon側で`h1`を表示するときに問題がありそう?

**Comment by rinsuki** [comment]
HTMLのサニタイズの時に消えてるだけでは

**Comment by EbiseLutica** [comment]
構文ごと消えたので閉じます
