### ISSUE TITLE
リモートとローカルでストレージの保存先を分けれるように

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#4376]
アクセス頻度の高いリモートのファイルキャッシュをローカルのminioに
アクセス頻度は低いが、長期間安全に保存したいファイルはAWSに

ということが出来るようにしたい
というのも、AWSはファイル生成する度にコストが掛かるので、コストが掛からないminioやWasabiにやらせたいが、この２つは冗長性が心配。

**Comment by tamaina** [comment]
めいすきーでやってるらしい

**Comment by u1-liquid** [comment]
最近実装されたMediaProxyで処理できそう

**Comment by mei23** [comment]
> めいすきーでやってるらしい

v11オブジェクトストレージの設定が管理画面のUIで、でいろいろやるとUIがくどくなるので及び腰…
今の管理画面の権限構造だとモデレーターもオブジェクトストレージのkeyとか見れちゃうし
オブジェクトストレージ設定はconfigファイルでもいいかな…と

**Comment by SanMurakami** [comment]
全然関係ないですけど

> 今の管理画面の権限構造だとモデレーターもオブジェクトストレージのkeyとか見れちゃうし

ちょうどこれ困ってたので、できれば管理画面からは外してくれたら助かりますね

**Comment by SanMurakami** [comment]
Proxy導入されたのでこれはCloseします
必要であればReOpenしてください
