### ISSUE TITLE
Widget: Feedly

### ISSUE THREAD

**Issue by OldBigBuddha** [misskey-dev/misskey#4379]
# Summary

- RSSをFeedlyで管理しているので、Misskey上でFeedlyが見れるようにしてほしいです。
- I want a widget of Feedly, because I manage my RSS with Feedly.

# Link
[The feedly Cloud API](https://developer.feedly.com/)

**Comment by Johann150** [comment]
I think the RSS feed widget is enough. Implementing Feedly separately would add too much complexity to Misskey in my opinion.
