### ISSUE TITLE
Blank CW field results in empty CW text

### ISSUE THREAD

**Issue by natarii** [misskey-dev/misskey#4383]
# Summary

Enabling the CW field on the post dialog, but not entering CW text, results in an empty CW

# Expected Behavior

The post is submitted without CW, or the user is prompted to enter CW text

# Actual Behavior

The post is submitted with an empty CW

# Steps to Reproduce

1. Open the compose post dialog
2. Enable the CW field
3. Do not enter any CW text
4. Enter some post text and submit

![screenshot_2019-02-27_20-48-35](https://user-images.githubusercontent.com/18756729/53535560-40b9b900-3ad1-11e9-9a9e-8dae8fc2c9bc.png)
![screenshot_2019-02-27_20-49-16](https://user-images.githubusercontent.com/18756729/53535562-43b4a980-3ad1-11e9-9bae-e8a60339615a.png)

**Comment by mei23** [comment]
Probably this is such a design

> prompted to enter CW text

Annotations are indicated as optional in placeholder.

> The post is submitted without CW

Probably this is Mastodon's UI spec.
But, the spec that CW is ignored for empty annotations seems strange.

**Comment by zyoshoka** [comment]
Blanking CW field is prohibited in #12217.
