### ISSUE TITLE
デッキ/モバイルのユーザーページでユーザーを切り替えても前の人の情報が残る

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4390]
# Summary
デッキ / モバイル のユーザーページでユーザーを切り替えても
アイコン / 名前 / 自己紹介 が以前表示していた人のままになる

Related #1537

# Expected Behavior

# Actual Behavior

# Steps to Reproduce

1.
2.
3.

# Environment

**Comment by tamaina** [comment]
デッキ限定ですが再発してませんかね これ

@ Firefox 68.0b2 (64 ビット) / Misskey 11.18.0
