### ISSUE TITLE
Add Czech (cs) language to Crowdin

### ISSUE THREAD

**Issue by Aditoo17** [misskey-dev/misskey#4399]
Hi, could you please add Czech ("cs" or"cs-CZ") locale to Crowdin? Thank you!

**Comment by StorytellerCZ** [comment]
Feel free to ping me when the settings are done and I will start translating. :+1:

**Comment by acid-chicken** [comment]
@syuilo Just check here!
![image](https://user-images.githubusercontent.com/20679825/53683790-4ec53f00-3d48-11e9-9e22-202dd8c9f066.png)

**Comment by syuilo** [comment]
Added 🎉 
https://crowdin.com/project/misskey/cs#

**Comment by Aditoo17** [comment]
@StorytellerCZ The translation is ready!
