### ISSUE TITLE
Update poll federation

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#4407]
# Summary

From tootsuite/mastodon#10111 and #3940.

Working at `poll` branch.

**Comment by acid-chicken** [comment]
Memo: have to support `anyOf` choices.

**Comment by Gargron** [comment]
- `anyOf` (multiple-choice)
- `endTime` (expiration date) (`closed` when already expired)
- For each item in `oneOf`/`anyOf`, you can add `replies: { type: 'Collection', totalItems: 123 }` instead of (or additionally to) `_misskey_votes`

**Comment by acid-chicken** [comment]
@Gargron Thank you for the useful info!

**Comment by Gargron** [comment]
@acid-chicken Perhaps you can help me answer these?

https://github.com/tootsuite/mastodon/pull/10111#discussion_r261871048
https://github.com/tootsuite/mastodon/pull/10111#discussion_r261870760

**Comment by Gargron** [comment]
I have another request... Could you use `name` to federate poll votes instead of `content` (or `_misskey_content`?), so we can avoid HTML and also differentiate between normal replies and votes easier

**Comment by acid-chicken** [comment]
@Gargron Misskey will start using `name` property when #4409 is merged!
