### ISSUE TITLE
URLプレビューの「プレイヤーを開く」の範囲が狭いので広げてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#4410]
# Summary
埋め込み表示が可能なURLのプレビューの場合、サムネイル部をクリックすると埋め込みに切り替わり、article部をクリックすると移動するが、この挙動は少々分かりにくい気がする。

URLプレビュー全体を埋め込みのトリガーにするようにするか、サムネイルとarticleを上下に配置してサムネイル部を大きくすることで対処してもいいかもしれない。

**Comment by tamaina** [comment]
そう？

**Comment by mei23** [comment]
てゆうかサムネイルがないとプレイヤーを開く手段がないのをどうにか

**Comment by tamaina** [comment]
あ、確かにそうかも

**Comment by tamaina** [comment]
そもそもTL上の埋め込み使う？？
（ウィンドウで表示するオプションほしい）

**Comment by tamaina** [comment]
> サムネイルがない

コンテキストメニューで開ければいいと私は思う
