### ISSUE TITLE
ユーザーサジェストで表示名が変わらない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4415]
# Summary
ユーザーサジェストでがあるとことでユーザー名を入力していくと
候補のユーザーが変わっても表示名の部分だけがそのままになってしまう
![image](https://user-images.githubusercontent.com/30769358/53753755-5c6bf780-3ef5-11e9-906b-1ecc5b988ee3.png)
![image](https://user-images.githubusercontent.com/30769358/53753769-655cc900-3ef5-11e9-865a-c0863a5d3489.png)

# Expected Behavior

# Actual Behavior

# Steps to Reproduce

1.
2.
3.

# Environment

**Comment by acid-chicken** [comment]
![60830BFF-3047-48EB-8B0E-343AACAE2BF2](https://user-images.githubusercontent.com/20679825/56708121-86ec6b00-6756-11e9-82e7-5eb00a85ceb5.png)
![C9B0DB62-B9FE-449F-9C48-AD2762408832](https://user-images.githubusercontent.com/20679825/56708130-91a70000-6756-11e9-8d1f-125bf3a19767.png)
