### ISSUE TITLE
URLに日本語を含んでいた場合、正しくURLが解析されない。

### ISSUE THREAD

**Issue by ouvill** [misskey-dev/misskey#4430]
# Summary

URLに日本語を含んでいた場合、正しくURLが解析されない。

以下のURLを投稿した時、日本語部分がURLとして認識されなかった。
> https://ja.softether.org/1-features/1._極めて強力な_VPN_接続性

……そもそも日本語URLを使用しているサイトが滅べばいいのだけど

# Expected Behavior

![screenshot from 2019-03-07 00-18-11](https://user-images.githubusercontent.com/12369770/53892077-f60ae480-406e-11e9-862b-a09155fed2c1.png)

日本語のURLも正しく認識されるべき。
投稿時に URL を以下のようにURLエンコードしておくと、正常にURLとして認識された。

https://ja.softether.org/1-features/1._%E6%A5%B5%E3%82%81%E3%81%A6%E5%BC%B7%E5%8A%9B%E3%81%AA_VPN_%E6%8E%A5%E7%B6%9A%E6%80%A7

投稿結果が上記画像。

# Actual Behavior

![screenshot from 2019-03-07 00-18-05](https://user-images.githubusercontent.com/12369770/53892047-e7bcc880-406e-11e9-8ba3-ac54e0b0e2d3.png)

日本語部分がURLとして認識されていない。

# Steps to Reproduce

1. URLエンコードされていない日本語URL を含んだ投稿をする

# Environment

- OS: Ubuntu 18.10
- Browser: Vivaldi 2.3.1440.60 (Stable channel) (64-bit)
- Misskey 10.91.2

**Comment by syuilo** [comment]
URLに日本語は使えないので一応これで正しい挙動ですね

**Comment by ouvill** [comment]
日本語を含んだ URL を使用しているサイトを呪うことにします。

**Comment by acid-chicken** [comment]
Markdownなどのように`<`〜`>`で囲ったら日本語URLも許容するのはどうですか。

**Comment by tamaina** [comment]
`<…>`も良いですが、MFMにはタグ構文があるのですこし好ましくない気がします(パーシング的には問題ない...?)。

`[](https://ja.softether.org/1-features/1._極めて強力な_VPN_接続性)`のように、リンク構文を用いることができるようにすればいいのではないでしょうか。「`[]()`の`()`内は日本語テキストでもURLと認識するように」し、「`[]`内が空白でもURLこの構文であると認識して、この場合はURLを表示する」のようにする感じで。

**Comment by acid-chicken** [comment]
`/^<https?://.*?>/g`のような判定にしてやるとおそらくパースの方は大丈夫だと思います。Markdownをいまだに名乗っている節もありますし、歩み寄れるところは歩み寄っていった方が良いでしょう。
