### ISSUE TITLE
Add Traditional Chinese language to Crowdin

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#4432]
# Summary

@syuilo よろしくお願いします。

FYI: https://imastodon.net/@yoka/101704535503707642

**Comment by acid-chicken** [comment]
> 繁体字でも台湾と香港マカオで違いますので、将来的に両方対応したほうが望ましいですね。

ということらしいので、zh-CN zh-SG zh-HK zh-MO zh-TW のような感じで分けていただけると助かります。

**Comment by syuilo** [comment]
とりあえず繁体字を追加しました
🙏
