### ISSUE TITLE
その投稿をRenoteしたユーザー一覧を表示

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4438]
# Summary

**Comment by Johann150** [comment]
I think something like the reaction viewer could be used for this. Would also be nice if it shows if you already renoted at least once by changing the colour, like for reactions.

**Comment by Johann150** [comment]
Would it be okay to add a value `hasShared` which is `true` if a note was boosted to `api/notes/show` endpoint? It would be similar to `myReaction`, and could be used to change the colour of the renote button if a user renoted (or quoted) a note before.
