### ISSUE TITLE
deliverキューが詰まりまくる

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4449]
## Summary
並列度がデフォルトの1のままなので運用環境だと普通に詰まりまくる
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueprocess

## Steps to Reproduce
1.
2.
3.

**Comment by mei23** [comment]
https://github.com/syuilo/misskey/blob/5f4a52574f9e023e10b447c41e886ccec7268642/src/queue/index.ts#L121-L122
16と4 だと普通に詰まったので、~~256~~128 と4とかにしてみている。

値を調整する機能と現在のキューの状態を見る機能がほしいかも

**Comment by mei23** [comment]
キューがactive状態のままスレッドを埋め尽くして動かなくなってしまうみたい

**Comment by mei23** [comment]
Promise resolve してないところがあったので active のままになっていたみたい
修正したら active たまらなくなりました
https://github.com/mei23/misskey/commit/ce65b733bd47cddd118870686d86aa49cf1a279c

**Comment by syuilo** [comment]
修正しました 🙏

**Comment by mei23** [comment]
もう lifo もいらないと思います

APの送信順が変わるとちょっと影響がありそう。
絶対に終わらないactiveでキューがあふれて動かなくなるので lifo にしても変わらない。
というのもあり。
