### ISSUE TITLE
Chat/messenger in pipeline?

### ISSUE THREAD

**Issue by JLKM** [misskey-dev/misskey#4465]
## Is there any chance, Misskey would at some time incorporate a (local) chat/messenger feature?

It's absolutely amazing, that Misskey offers a self-hosted fediverse/ActivityPub server built on NoSQL (MongoDB), Node.js and Vue.js. This is a clean cut in my view compared to all the Ruby-PostgreSQL or PHP-PostgreSQL solutions (with typically a lot more dependencies) out there.

Furthermore: Specs seem to be awesome, and configurability is made really user friendly.

But why not also catch in on the local chat function found in f.ex. Pleroma? And if it's too much work: Would it be possible to integrate Misskey with another tool for this task?

**Comment by syuilo** [comment]
Thank you!
Misskey already has the Messaging feature.
![66E0814D-4AE6-4EF8-A4E5-1658DA0CB2CE](https://user-images.githubusercontent.com/4439005/54087367-7003dc00-4395-11e9-8385-1db2c1bd144c.jpeg)

**Comment by JLKM** [comment]
Dooh. I even searched pretty much without finding this documented...

Now it's my turn to say thank you. Both for the good news and the fast answer.

This only underlines, that Misskey is really cool. So cool, that it deserves to go worldwide asap.

Perhaps some more documentation in english would make that happen in a fairly short time.

Keep up the good work. I'm looking forward to setting Misskey up on my Ubuntu 18.04 LTS server.

**Comment by xeruf** [comment]
Yeah I searched through the website for a while and did not find it documented - @syuilo is it documented somwhere?

Btw, is there a possibility of integrating it with XMPP (rather than an I assume homegrown closed protocol)?
