### ISSUE TITLE
ジョブキューのチャートを更新するときに現在のジョブ数を取得するのではなく前回の更新時からのイベントを受信しておきメモリにカウントを保持しておいてそれを利用する

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4470]
## Summary

より正確な数を取得するため

**Comment by mei23** [comment]
「現在Activeなジョブ数 (count)」と「単位時間あたりにActiveになったジョブ数 (count/T sec)」
は違う概念なので代替えにはならないのではと思います。
「単位時間あたりのActiveになったジョブ数」では来客数的なのはわかりますが
滞留しているかがわからないので「現在Activeなジョブ数」も必要だと思います。

また「現在Activeなジョブ数 (count)」と「単位時間あたりにActiveになったジョブ数 (count/T sec)」は単位の次元?も違うので、同じグラフに入れてしまうのも少し変な気がします。

つまり「現在Activeなジョブ数 (count)」は残して
「単位時間あたりにActiveになったジョブ数 (count/T sec)」は別枠の集計としたほうがいいのではと思います。

**Comment by mei23** [comment]
おそらくここで欲しいと思っている値は「Activeなジョブ数の単位時間あたりの平均値 (count) 」で
それは
「単位時間あたりにActiveになった数 (count/T)」x「単位時間あたりに処理されたジョブの所要時間の平均(T)」で求まるのではと思われます（たしか）。

でもこれ取得できなそう…
