### ISSUE TITLE
ライトモードではライトなprismjsテーマに切り替えてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#4473]
## Summary
現状はライトモードでもダークモードでもprism.jsのテーマはokadiaから切り替わらない。これだとライトモードだとちょっと目に悪いことになっているので、prism.jsのテーマもライトなものに切り替えるようにしてほしい。

Misskeyテーマに読み込むprism.jsテーマを定義できるようにするとなお良い感じかもしれない。

現状  
![image](https://user-images.githubusercontent.com/7973572/54128519-9dad5b80-444f-11e9-996b-5a9d4a68cd8a.png)

**Comment by tamaina** [comment]
@kakkokari-gtyih

**Comment by kakkokari-gtyih** [comment]
> prism.jsのテーマもライトなものに切り替えるようにしてほしい

やるか

> Misskeyテーマに読み込むprism.jsテーマを定義できるようにするとなお良い感じかもしれない。

これ以上バンドルサイズをデカくしてまでやることじゃないなと思ったのでこれはなしで良い気が

**Comment by kakkokari-gtyih** [comment]
> これ以上バンドルサイズをデカくしてまで（全プリセットテーマをバンドルしてまで）やることじゃないなと思ったのでこれはなしで良い気が

バンドルするだけで読み込まれはしないからいい説はある
