### ISSUE TITLE
エクスポートした投稿が途中から破損している

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#4480]
![image](https://user-images.githubusercontent.com/20679825/54175197-3f26c280-44cd-11e9-80d2-4248b92e412d.png)

**Comment by KisaragiEffective** [comment]
triage: 3月に主運用アカウントで取得した投稿エクスポート (約2.5万レコード) は破損していなかったので閉じます。もし再発するようであれば開き直してください。
