### ISSUE TITLE
アカウント作成にメールアドレス必須にするオプション

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4492]

**Comment by syuilo** [comment]
yaruka

**Comment by syuilo** [comment]
同じ人が複数アカウントを作成する場合があるので、同じメールアドレスを重複して登録することもできるようにするか？

**Comment by YuzuRyo61** [comment]
> 同じ人が複数アカウントを作成する場合があるので、同じメールアドレスを重複して登録することもできるようにするか？

スパムの懸念も否めない気がする

**Comment by syuilo** [comment]
ふーむ

**Comment by syuilo** [comment]
まあ実質同じメールアドレスだけど無制限で文字列にバリエーション持たせられるメールサービスもあるので、同じメールアドレス付加にしたとしてもスパム的な観点からは特に変わらない気がする

**Comment by rinsuki** [comment]
メールアドレスuniqueじゃないとパスワードとユーザー名を忘れた救いようのない人が救えたりログインにメールアドレス使えたりして便利かもしれない
後からunique付けるのと後からunique外すのなら後者の方が簡単だし
どうせメールアドレスは無限に生やせるのでuniqueにしてもそんなに不便にはならなさそう

**Comment by syuilo** [comment]
メアドが正しいかどうかの情報の(一時的)保持はredis使うと楽かも
