### ISSUE TITLE
投稿に添付できるファイル数の制限を緩和

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4502]
## Summary

具体的にどれくらいにするかは未定

**Comment by mei23** [comment]
Pleromaで10枚とか61枚とか送ってくるインスタンスがあるのは確認
ただ、Mastodonは5枚以上メディアを送っても表示してくれないみたい

**Comment by rinsuki** [comment]
PleromaがMastodonと話せるようになった当時あたりの記憶では、WebUIでは4枚しか表示されないけどAPI上はそれ以上来るので、クライアントアプリで決め打ちしてなければ5枚目以降も表示される(今でもそうかは知らない)

**Comment by tamaina** [comment]
文字数と同じでインスタンスごとに設定できるようにするのはどうでしょう？

**Comment by mei23** [comment]
今MastodonはAPIでも4件までぽい
ただ枚数多いとかなり時間がかかるので取得自体はしてるのかも

**Comment by syuilo** [comment]
緩和して欲しいという声が体感的に多くなってきた

**Comment by mei23** [comment]
8ぐらいならあまり大きくUI修正しなくても大丈夫

**Comment by EbiseLutica** [comment]
8超えたら詳細ページでリストとして出すとかでどうかな

**Comment by KisaragiEffective** [comment]
triage: resolved by e3a5584d0ab9b1b75b254070ac471c2d9830020f (based on #8062) ?

**Comment by Sayamame-beans** [comment]
当時4個までだったものが16個に増加しているので、解決済みと捉えて良いように思います。(更に緩めたい場合は再issueで良いかと?)

**Comment by KisaragiEffective** [comment]
ということで close します
