### ISSUE TITLE
投稿に大量にメディアが添付されていると表示が小さくなる

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4503]
## Summary
投稿に大量にメディアが添付されているとメディアリストが横長になり、表示部分が小さくなってしまう
![image](https://user-images.githubusercontent.com/30769358/54413660-d1330300-4739-11e9-8682-f61823df5fd5.png)

## Steps to Reproduce

1.
2.
3.

**Comment by mei23** [comment]
-v11 UIの話なので、まだ起きるならReopenしてください。

**Comment by syuilo** [comment]
特に改修した覚えがないから現在でも発生しそう
