### ISSUE TITLE
next / prev link in media viewer

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4511]
## Summary
メディア (画像, media, image) を 表示した時に
進む (next, forward, 次), 戻る (prev, back, 前) リンクが欲しい

**Comment by mei23** [comment]
imageとvideoビューワが別になってるとか、mobileにはvideoビューワがないとかで
まずビューワーを統合しないといけなくてだいぶ面倒そう。誰か作って欲しい。

**Comment by pwFoo** [comment]
Image prev / next and additional slideshow Feature?
