### ISSUE TITLE
メンションのサジェストが表示されない？

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#4514]
検索欄や投稿欄で「@」から始めた時のサジェストが一切表示されない

APIが返してくる値が無っぽい？

Misskey: 10.95.0
Instance: misskey.xyz
OS: macOS 10.14
Browser: Chrome 72.0.3626.121

**Comment by mei23** [comment]
developでは修正済みです
https://github.com/syuilo/misskey/pull/4505

**Comment by EbiseLutica** [comment]
オッケーです　閉じちゃいます
