### ISSUE TITLE
自由なリアクション

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#4516]
## Summary
リアクションを10個に制限せず、インスタンスのカスタム絵文字を含め、絵文字ピッカーの中から自由に付加できるようにしてほしい

- misskey.m544.netには絵文字を自由につけられる改造が施されている

**Comment by syuilo** [comment]
前に行ったアンケートでは種類にある程度縛りがあるから面白いとの意見の方が多かった

**Comment by mei23** [comment]
> ある程度縛りがあるから面白い

~~面白いは主観だし実証した上での意見でもないし~~

AP受信とAPIまではなんでもできるようにして、UIで簡単に追加できるのは絞るとかインスタンス設定にするとか…

**Comment by mei23** [comment]
たいていの機能はアンケート取ったら現状維持に動くと思う
擬態寿司もMFM系もアンケートなんかとらずに実装しているけど
実装前にアンケート取ったら別にいらないになるはず

**Comment by mei23** [comment]
> 絵文字ピッカーの中から自由に付加で

#4517 は「絵文字ピッカーから自由に」まではしてなくて、ユーザーが指定すれば絵文字なら追加できるになってます

**Comment by syuilo** [comment]
インスタンス設定で無効にしたらAPIやAP受信でも無効にしたい

**Comment by mei23** [comment]
> インスタンス設定で無効

10個以外を許可する / 許可しない という切り替えです？
許可してなかった場合のフォールバックは何に？ (現状の👍はやめて⭐にしたい)

**Comment by syuilo** [comment]
> 10個以外を許可する / 許可しない という切り替えです？

そうですね、(今まで通りか、任意の絵文字をリアクションとして許可するか)
フォールバックは👍と考えてました(ActivityPub上では Like としてくる以上、⭐️ よりも 👍 の方が合ってそうだと思った) これに関しては別のIssueで良さそう

**Comment by tamaina** [comment]
リアクションのフォールバックを⭐にすることについては、「付けられないリアクションが付くことで混乱を招く」というような理由で一度却下された記憶があります（プリンになった）。  
該当issueがなぜか見つけられない…

**Comment by syuilo** [comment]
> 付けられないリアクションが付くことで混乱を招く

はい、それもフォールバックを⭐️にしない理由の一つですね

**Comment by mei23** [comment]
付けられないリアクションが付けられるから面白いのに (主観)
