### ISSUE TITLE
リアクションのフォールバックを👍ではなくす

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4518]
## Summary
Mastodon, Pleroma等の リアクションの種類という概念がないインスタンスからの反応は
👍になるが、相手が意図して肯定のリアクションを送ったわけではないので
あまり意図を持たないリアクション (そのまま⭐とか) にフォールバックさせたい。

悲しい話題に対して👍になってしまうのはちょっとまずそう。

https://github.com/syuilo/misskey/issues/4516#issuecomment-473615750 あたりより

**Comment by acid-chicken** [comment]
Resolved at 08c176e549e6ba2fc1a4cbbf4b09c7d0226c7f13.
