### ISSUE TITLE
PostgreSQLにする

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4534]
## Summary

* MongoDBでしか出来ないようなことはほとんどしていない
* Misskeyで扱うほとんどのデータはきっちりとスキーマが決まっていてリレーショナルなので、リレーショナルデータベースの方が都合が良い
* 親レコードが削除されたら子レコードも自動的に削除、とかできるので削除系の処理の実装が簡単になりそう
* プログラム上でObjectIDをいちいち変換するのがめんどい
* MongoDBはPostgreSQLと比較するとメジャーでない

Related to #3510, #4203

Working on https://github.com/syuilo/misskey/tree/pg

## メモ
* インスタンスをブロックしているかどうかはインスタンステーブルには保存しないでinstanceBlockingなどのテーブルに別途保存する
* オブジェクトストレージを使用しない場合、ファイルをデータベースに保存するのはやめてサーバーのファイルシステム上に保存するようにする
* Metaに投稿数などを保存するのをやめる(必要ならその都度カウントする)
* MongoDBでは重複レコードエラーは e.code === 11000 で判別できたけどPostgreSQLの場合どうなるのか
* 壁紙設定はクライアントの設定に移動
* getDriveFileUrl --> getThumbnailUrl に
* pinnedNoteIds は廃止して userNotePinings といったテーブルを作る
* 正規表現検索をする方法
* 配列に値を追加する方法
* simple-array ではなく array: true を使用
* 投稿に _files として添付ファイルを非正規化するのをやめる
  * というか isAttachingSensitiveFiles と attachedFileTypes みたいな非正規化プロパティに分解する
* _reply _renote _user といった非正規化プロパティも replyUserId replyUserHost renoteUserId renoteUserHost userHost userInbox みたいに分割
* ホームのカスタマイズ情報をサーバーに保存するのをやめる

**Comment by acid-chicken** [comment]
大変そう。手伝えることがあったら言ってください。

**Comment by syuilo** [comment]
ありがとうございます！
一部で行っている複雑なクエリをPostgreSQLで実現できるかなど分からない部分もありますが頑張ります

**Comment by acid-chicken** [comment]
ちなみに何を使うとかいう具体的な方針は決まってたりしますか？

**Comment by syuilo** [comment]
PostgreSQLの具体的なバージョンはまだ未定ですがORMはtypeormの予定です

**Comment by syuilo** [comment]
pgブランチ作りました。
まずモデル定義(src/models)をtypeormを使用したものに書き換えていく必要があります。[例はここら辺に](https://github.com/typeorm/typeorm#column-data-types)
時間のある方はこの作業に参加していただけると助かります

**Comment by syuilo** [comment]
外部キー制約って配列には適用できない...？
例えば投稿の添付された複数のファイルを表す`fileIds`とか

**Comment by syuilo** [comment]
noteFileAttachment といった別のテーブル作るしかないか

**Comment by syuilo** [comment]
renoteCount とか repliesCount とか reactionCounts とか保存すべき？
これらのカラムはすべて非正規化されてるようなもので、これらが無くても理論的にはその投稿のRenote数や返信数やリアクション数は取得できる

**Comment by syuilo** [comment]
とりあえず無くしといてパフォーマンス上の問題があるようなら非正規化でも良いかもしれないけど後から設計を変えるのもそれはそれで面倒

**Comment by syuilo** [comment]
visibleUserIds も外部キーの配列だけど、さすがにこれのためだけにテーブル作るのはなんかアレ
不通に数値(ID)の配列として保存するか...

**Comment by syuilo** [comment]
んーでも、自分宛てのダイレクト投稿を一覧取得するケースもあるか...

**Comment by mei23** [comment]
> renoteCount とか repliesCount とか reactionCounts とか保存すべき？

renoteCount (APIではnumber) 保存する
repliesCount (APIではnumber) 保存する
reactionCounts (APIではObject) 必ずNoteReactionsみたいなテーブルを見るとおもうので保存しない
とか？

**Comment by syuilo** [comment]
ありがとうございます

> 必ずNoteReactionsみたいなテーブルを見るとおもう

んー、そんなことないかも

**Comment by mei23** [comment]
> んー、そんなことないかも

JSON? 今みたいに`NoteReaction`を使うのかと…
あれ、今`NoteReaction`insertしかしてない

**Comment by syuilo** [comment]
typeormはやめてsequelize-typescriptにします

**Comment by acid-chicken** [comment]
TypeORM 評判悪いと聞いていたので正直ほっとしました。

**Comment by syuilo** [comment]
個々のIDが変わっても問題ないならばマイグレ用意することはできる
ただ大変という問題はあるけど

**Comment by syuilo** [comment]
ユーザーに関しては、IDが比較可能である必要はない(ランダムな文字列で問題ない)ため、マイグレの際は以前のObjectIDをそのまま引き継ぐことが可能そう

**Comment by mei23** [comment]
現在のIDについては
https://docs.mongodb.com/manual/reference/method/ObjectId/

日付が含まれているものの、生成時期を考えると (上位4ビットが0になった時期がないので)
事実上固定長 (24文字hex文字列) なので比較可能だと思います。

また、現在のIDは上位の方のビットが0101までのIDが採番されているので
新たに1xxxなど最上位ビットが埋まっているIDなどを採番すれば重複することもないのではと思います。

**Comment by tamaina** [comment]
そういえば: PostgreSQLになったらElasticSearchではなくなる？

**Comment by syuilo** [comment]
sequelize-typescript は ActiveRecord しかできなくて微妙

**Comment by acid-chicken** [comment]
PeerTube の開発者の方々にお伺いをたてるのも手かと。

**Comment by syuilo** [comment]
Misskeyはデータベースから取得したレコードはすぐレスポンスとして返す場合がほとんど(いじくったりしない)ので、レコード自体にメソッドがあっても意味ないし、いちいちインスタンス化するコストもかかる
ORMによっては取得時にインスタンス化しないオプションを提供するものもあるけど、ほぼすべての find 時にそのオプションを true にするのは面倒すぎる

**Comment by syuilo** [comment]
とりあえず sequelize の線は消えそう

**Comment by syuilo** [comment]
> PostgreSQLになったらElasticSearchではなくなる？

MastodonはPostgreSQLだけどElasticSearchを必要としていることからMisskeyでも引き続き必要になりそう

**Comment by syuilo** [comment]
TypeORMに戻る

**Comment by syuilo** [comment]
10%くらい終わった

**Comment by syuilo** [comment]
v10時点でのデータベースの設計や命名などで気になっている点がある方は今のうちに言っておいてください

**Comment by syuilo** [comment]
20%くらい終わった

**Comment by syuilo** [comment]
ついでに #4018 もやる

**Comment by syuilo** [comment]
型定義は作らないかもしれないけど、「不要な値を削除」方式ではなくこんな感じに「必要な値をコピー」する感じ
https://github.com/syuilo/misskey/blob/578143096f1accdc7e23a72b2cbe76768969d1f4/src/models/repositories/user.ts#L48-L84

**Comment by syuilo** [comment]
型定義作るとしたら、せっかく作っても型定義とドキュメントが一致していないということが起こり得るので、ドキュメントから型定義を自動生成するようにする
それなら型定義とドキュメントが必ず一致することが保証される

**Comment by syuilo** [comment]
今はAPIのパラメータの型情報はドキュメント(cafy定義)から自動生成している状態なのでそれと同じ感じで

**Comment by mei23** [comment]
modelのリファクタ系`develop`とか`v10なんたら`とかのブランチにマージしておきたい気がします

**Comment by mei23** [comment]
↑今はmodel配下のマッピングの差分がわからなくなってしまったので

**Comment by syuilo** [comment]
今まで models にあったものは models/entities と models/repositories に分割されました
entiriesにはスキーマ定義だけあって、repositoriesにはそのスキーマに属するメソッドが定義されます

例えば今までこのように書いていたものはこうなります

before
``` ts
import Note, { INote, pack } from './models/note';

const foo: INote = bar();
const note = Note.findOne({ _id: x });
return pack(note);
```

after
``` ts
import { Note } from './models/entities/note';
import { Notes } from './models';

const foo: Note = bar();
const note = Notes.findOne(x);
return Notes.pack(note);
```

**Comment by syuilo** [comment]
entity と repository を区別するために、上の例にあるように repository の方は複数形になってます
Note が entity で Notes が NoteのRepostiry

**Comment by syuilo** [comment]
entity は、上述のようにスキーマ定義であってメソッドなどは何も持ってないので、コード上で entity を使うのは型注釈のためだけになると思います
repository は実際にデータベースからデータを持ってきたり更新したりなどのいろいろなメソッドを持っているので頻繁に使います

**Comment by syuilo** [comment]
30%くらい終わった

**Comment by syuilo** [comment]
各種IDに[ULID](
https://github.com/ulid/spec)を使おうと思うんですけどどう思いますか？
IDが数値だと、例えばアクセスされたURLに含まれているIDを元にデータベースに問い合わせるようなシナリオで、プログラム上でいちいち文字列から数値に変換する必要があってめんどい

**Comment by mei23** [comment]
@syuilo 
`noteId`とか`userId`でもULIDにして、既存IDとの連続性とかは考慮しない感じでしょうか？

**Comment by syuilo** [comment]
う～～～む

**Comment by syuilo** [comment]
ランダムではないので連続性は保たれそう

**Comment by syuilo** [comment]
ちゃんと元の順番通りinsertしていけば

**Comment by syuilo** [comment]
ULIDほどのユニークさは求めてないのでULIDをちょっと改造したものになりそう

**Comment by mei23** [comment]
そもそも`noteId`とか`userId`って (同じIDで) 移行しますか？
Hex 24文字 => Base32 26文字 にするということは移行なしですかね？

**Comment by syuilo** [comment]
IDは変わると考えてます

**Comment by mei23** [comment]
ID変えてしまうとユーザー移行が難しくなるのではと思います (AP的に)

**Comment by syuilo** [comment]
こまこまのこまり

**Comment by mei23** [comment]
- (固定値1 1bit) + (Timestamp 47bits UNIX ms) + Random 48bits = 96bits (12Bytes, 24 Hex chars)
- エンコードはHex

にすれば旧IDと重複しないので旧IDがそのまま使えて
順番も旧ID→新IDとつながると思います

**Comment by fz0000** [comment]
So is there any plan to support other databases?
Database server is much cheaper than VPS. But not all ISPs provide MongoDB(or even PostgreSQL)... (MySQL and MS SQL Server are most widely used) If I were building my own site, I would like to just buy a database server instead of a VPS that I need to install MondoDB myself. 😄

**Comment by syuilo** [comment]
Support is difficult because MySQL doesn't support arrays or JSON columns.
