### ISSUE TITLE
管理画面のグラフでドライブ容量の推移などがわからない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4535]
## Summary
![image](https://user-images.githubusercontent.com/30769358/54603196-0f585b80-4a87-11e9-9c6f-aa6e43969597.png)

## Expected Behavior
最低値は0でy軸の値も変わる

## Actual Behavior
y軸の値がほとんど同じでわからない

## Steps to Reproduce

1. ドライブ使用量の積算→Localのみグラフ表示
2.
3.

**Comment by syuilo** [comment]
最低値が0だとほぼ横に一直線の線が描かれるだけになってしまってそれはそれでわからなさそう

**Comment by mei23** [comment]
じゃあy軸とポップアップだけでも
あと、1時間毎グラフなのにポップアップが常に日単位だったりもする

**Comment by mei23** [comment]
-v11 UIなので該当しないはず
