### ISSUE TITLE
png以外の形式のカスタム絵文字がMastodonに伝わらない問題

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#4541]
## Summary
Mastodon（などのほかのソフトウェア）側で対処してもらうようにリクエストするか、Misskeyでpngに変換したものをリモートに渡すか。もしくはその両方？

通信量や表示的にメリットのあるSVGはせめて対応してほしい。複雑でないシェイプのカスタム絵文字をSVGにするのが有益なことは、どのソフトウェアでも共通なはず。

**Comment by acid-chicken** [comment]
Mastodon で対処してもらいたい。この前 WebP の対応をお願いしたらしてくれたので SVG もいけるかもしれない。

**Comment by tamaina** [comment]
Ah~ tootsuite/mastodon#9253

**Comment by mei23** [comment]
今APでカスタム絵文字送る時に常に`image/png`にしてるという問題があるはず

**Comment by tamaina** [comment]
なんですって～()

**Comment by acid-chicken** [comment]
![image](https://user-images.githubusercontent.com/20679825/54689756-78ad9c80-4b63-11e9-9cf5-fcbbe547b8b9.png)
![image](https://user-images.githubusercontent.com/20679825/54689790-82370480-4b63-11e9-98ba-2e304069cdf7.png)

~~Content-Type さえ正しくすれば SVG でも伝搬するようです。~~

誤りで、キャッシュ周りの影響でそう見えているだけでした。すみません。

**Comment by mei23** [comment]
> Content-Type さえ正しくすれば SVG でも伝搬するようです。

みれない (svg, Misskey => Mastodon)、どのパターンのことだわ？

**Comment by acid-chicken** [comment]
キャッシュ周りの影響と書きましたが、どうも最初に PNG で伝搬させた後 SVG で伝搬させると SVG 未対応のところだけ PNG のままで残るみたいなので、フォールバックに使えるかもしれない。

**Comment by acid-chicken** [comment]
現実的な手段として、PNG の絵文字情報だけ入れたブツだけなんとかして送りつけて（公開先なし投稿など？）その後本番を送るとかになるかも。

**Comment by tamaina** [comment]
- svgは解決した
- 絵文字に適用される画像がwebpublicになるのでファイルが圧縮されて表示される可能性が高くなるかも？

webpublicが2048x2048なので微妙ではある（いっそのことwebpにしてサムネイルサイズにしたい（アルファチャンネルは保持される））

**Comment by tamaina** [comment]
「png以外の」は達成されているのでcloseするか
