### ISSUE TITLE
リアクションピッカーの絵文字サジェストをマウスで選択するとリアクションされない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4567]
## Summary
リアクションピッカーの絵文字サジェストをマウスで選択するとリアクションされない

## Expected Behavior
`:絵文字:`が入力されたタイミングでリアクションがされる

## Actual Behavior
リアクションされない

## Steps to Reproduce
1. リアクションピッカーを開く
2. テキストボックスにフォーカス
3. `:なんたら`と入力して絵文字サジェストを開く
4. 絵文字サジェストをマウスクリックで選択する

## Environment
Deskstop

**Comment by tamaina** [comment]
バグなの？

**Comment by mei23** [comment]
有効な絵文字が入力されたタイミングでリアクションされるように意図してたからバグだと思うわ

**Comment by tamaina** [comment]
なるほど

**Comment by mei23** [comment]
これ誰かが直していたのと、今v12このにこの機能はないはず。
