### ISSUE TITLE
「UIの動きを減らす」をはじめから有効に

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#4591]
## Summary
MisskeyのWeb UIが重いという意見が見受けられますが、「UIの動きを減らす」を有効にしておけば少しも重くないと思います。

「UIの動きを減らす」をオプトアウトに（=UIのアニメーションの多くをオプトインに）すれば使ってもらいやすくなるのではないかと思います。

**Comment by acid-chicken** [comment]
「重い時は『UIの動きを減らす』をオンにしてみましょう。」などと common/views/widgets/tips.vue に書くぐらいで大丈夫だと思います。

**Comment by mei23** [comment]
TLの初回表示でアニメーションするのやめたい…

**Comment by tamaina** [comment]
wontfixなのにcloseされてない謎
