### ISSUE TITLE
フォロー / フォロワー リストでdescriptionにブロック要素のMFMが含まれていると省略が変になる

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4596]
## Summary
![image](https://user-images.githubusercontent.com/30769358/55227489-f4da6b00-525a-11e9-86c9-3a30d37617eb.png)

## Expected Behavior
常に1行で省略表示

## Actual Behavior
複数行になって省略されなくなってしまう

## Steps to Reproduce
1. descriptionにMFMタイトル構文などを含むユーザーを含む、フォロー / フォロワーリストを表示

## Environment
Desktop, Firefox / Chrome

**Comment by tamaina** [comment]
exploreも同じ感じになってそう
