### ISSUE TITLE
モバイルでpostするとTLに投稿が2つ表示される

### ISSUE THREAD

**Issue by sisi** [misskey-dev/misskey#4598]
# Summary
タイトルのとおりです
# Environment
iPhone7, Safari Chrome 両方で確認済み

![1](https://d2zoeobnny43zx.cloudfront.net/media_attachments/files/008/656/977/original/3f6d6929866187ab.png "1")
![2](https://d2zoeobnny43zx.cloudfront.net/media_attachments/files/008/656/962/original/8fe5107a1d2a7345.png "2")
![3](https://d2zoeobnny43zx.cloudfront.net/media_attachments/files/008/656/961/original/de13f92eac5e60e3.png "3")

**Comment by mei23** [comment]
https://github.com/syuilo/misskey/issues/4613
が起きるとホームに自分の投稿が2つずつ表示されてしまうので、これのせいかもしれない。

**Comment by mei23** [comment]
アカウントの フォロー / フォロワー 一覧に本人が含まれていたので、ほぼこれが原因ぽい。

**Comment by sisi** [comment]
自分でも確認したところその可能性が高いですね。
#4613 これが修正できれば解決すると思われるのでCloseしておきます～！
