### ISSUE TITLE
desktopでnewer-indicatorが意味をなしていない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#4609]
## Summary
newer-indicatorがナビゲーションバーに隠れているし、ナビゲーションバーが横にあってもstickyが効かない

## Expected Behavior
newer-indicatorがスクロールしても上部に見えたままになる

## Actual Behavior
newer-indicatorは固定されたまま

## Steps to Reproduce

1. 
2.
3.

## Environment
Misskey 7987bb491c67af8a5853628928665792891bd04a  
Firefox latest & Chrome latest

**Comment by anatawa12** [comment]
newer-indicator が最新版では存在しない模様なためcloseします。別名で存在する場合にはreopnお願いします。
