### ISSUE TITLE
ホームモードのときはデッキの設定を隠すように、デッキモードのときはホームの設定を隠すように

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#4612]
## Summary
ユーザーが混乱するため

また、デッキ/ホーム専用の設定はカードを別にして整理したい

**Comment by acid-chicken** [comment]
「あれ、こんな設定あったっけ？」となりそうなので折りたたむ程度にしたい。

**Comment by tamaina** [comment]
GitHubのバグによりRecloseします
