### ISSUE TITLE
nyaizeをクライアントサイドでするようにしてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#4615]
## Summary
そもそも、なぜサーバーサイドでやろうと思ったのですか？

Related to #3081 #2280

**Comment by syuilo** [comment]
クライアントサイドだとnyaizeするかどうかがクライアントに委ねられてしまう

**Comment by acid-chicken** [comment]
それだとMastodon等でnyaizeされなくないですか？

**Comment by tamaina** [comment]
> クライアントサイドだとnyaizeするかどうかがクライアントに委ねられてしまう

困ることはありますか？

**Comment by syuilo** [comment]
> 困ることはありますか？

問答無用でnyaizeされるという機能なので、問答無用でなくなった時点で機能の意味がなくなる

**Comment by acid-chicken** [comment]
> クライアントでもいいかもしれませんがクライアントが対応してないとnyaizeされなくなってしまう点が微妙
> (Cat機能は問答無用で な が にゃ になってしまう理不尽さを楽しむジョーク機能なので)

**Comment by tamaina** [comment]
なるほど

**Comment by tamaina** [comment]
これ本当にいる？

**Comment by tamaina** [comment]
Nyaize、削除して編集するときに戻すのが困難なので使っていない

**Comment by taiyme** [comment]
Nyaizeする前のオリジナルな文章が取得できるとうれしい

**Comment by tamaina** [comment]
related to #9371
