### ISSUE TITLE
RenoteダイアログでEnterキーを長押しすると大量にRenoteされてしまう

### ISSUE THREAD

**Issue by YuzuRyo61** [misskey-dev/misskey#4630]
## Summary
WebでRenoteダイアログでEnterキーを長押しすると大量にRenoteされてしまう。

## Steps to Reproduce

1. Renoteする投稿でRenoteダイアログを開く
2. Enterキーを長押しする
3. 離すとたくさんRenoteされる

## Environment
Windows10
Chrome 73.0.3683.86

**Comment by AyaMorisawa** [comment]
再現できなかった (Misskey 11.30.0)

**Comment by YuzuRyo61** [comment]
多分どっかで直ってる可能性があるのでクローズしておきます( ˇωˇ )
