### ISSUE TITLE
投稿増殖バグ

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4632]
## Summary

インスタンスBで受信したインスタンスAの投稿のURLをインスタンスAの検索欄に入力すると投稿が重複してなされる

## Expected Behavior

重複して投稿されない

## Actual Behavior

重複して投稿される

## Steps to Reproduce

1. インスタンスAで何らかの投稿をする
2. インスタンスBでその投稿が流れてきたら、インスタンスB上でのその投稿のURLをコピー
3. インスタンスAの検索欄に張り付け
4. インスタンスAでその投稿が当該アカウントからもう一度なされる

**Comment by mei23** [comment]
Noteをresolveするためにfetchしようとしたuriとは違うuriを含んだNote objectを許容してしまっているということになるため、根本的にNoteのvalidationが抜けていることになる。
おそらくAnnouce target, Reply targetのvalidationも抜けてることになる。
