### ISSUE TITLE
Activity chart is broken at 10.99.0

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4636]
## 💡 Summary
10.99.0にするとActivityチャートが変になる

## 🙂 Expected Behavior
![image](https://user-images.githubusercontent.com/30769358/55656265-496c8000-5831-11e9-8e3c-d73bcf066115.png)

## ☹️ Actual Behavior
![image](https://user-images.githubusercontent.com/30769358/55655372-027d8b00-582f-11e9-9b7b-99caf60e977a.png)

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by mei23** [comment]
https://github.com/syuilo/misskey/commit/f26643cea3ec6b0a4dc8495353b05b4c2ec57d99
apexcharts 3.6.5 => 3.6.2 でなおりはする

**Comment by syuilo** [comment]
3.6.7で直ったっぽい
