### ISSUE TITLE
PWA作成時の名前をインスタンス名にする

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#4638]
## Summary

MisskeyインスタンスのPWAを作成すると、どのインスタンスにも関わらず名前が「Misskey」で固定される。環境によってはPWAのアプリ名を変更できなくて、判別が難しいという問題があるので、インスタンス名をデフォルトの名前にできたら良さそう（当方、ServiceWorker関連に明るくない為、技術的に可能なのかわかりません。）

**Comment by mei23** [comment]
Issue: #4618, Pull: #4619 でなおってるとおもう

**Comment by EbiseLutica** [comment]
あ、duplicatedでしたか。ありがとうございます閉じます
