### ISSUE TITLE
[解決済][方法記述]Google Cloud Storageを利用可能にしてほしい

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#4643]
### **Summary**

~~Google Cloud Storageがうまく動いていない~~
configの設定ミスだった

### **Expected Behavior**
~~GCSが利用可能になる~~

### **Actual Behavior**
~~GCSの指定したバケット内に画像ファイルを転送、保存自体はできている
ただしストレージ内に保存された画像ファイルを読み込むことができない~~

### **Steps to Reproduce**
~~default.ymlの S3 example (with CDN, custom domain)部分の該当箇所をを以下のように編集した~~
~~_.config/default.yml_~~
~~`bucket: your_gcs_bucket_name`~~
~~`baseUrl: https://storage.googleapis.com/`~~
~~`endPoint: storage.googleapis.com`~~

_.config/default.yml_ の **S3 example** 欄の
`endPoint: s3-us-west-2.amazonaws.com` を
`endPoint: storage.googleapis.com` に書き換える

**Comment by syuilo** [comment]
ファイルのURLにアクセスすると、どのようなエラーが表示されますか？

**Comment by acid-chicken** [comment]
~~`region` って設定しなくても大丈夫ですか？~~

アップロードできているのであれば気にする必要もなさそうですね、失礼しました。

**Comment by ghost** [comment]
`WARN 1	[api]	SLOW API CALL DETECTED: drive/files/create (2388.724227000028ms)`
log漁ってると画像をアップロードするたびにこの一文が出てるんですけど関係ありますかね？

**Comment by syuilo** [comment]
関係なさそう

**Comment by acid-chicken** [comment]
prefix って files のままですか？一回 bucket と同じ値を充ててみてもらえませんか？

**Comment by Amalilyth** [comment]
ん！？

**Comment by Amalilyth** [comment]
解決しました

**Comment by ghost** [comment]
S3 with custom domain じゃなくて通常のS3の欄に入力したら画像出力できました
謎

**Comment by acid-chicken** [comment]
解決されたようで良かったです。ただこれ**非常に不親切**なので、ドキュメントを書いた方が良いでしょうね。

一応解説しておきますと、baseUrlという名前は少し引っ掛けで、実際にベースとして使われるURLは`baseUrl + '/' + prefix`だったりします。なぜこういう設計にされたのかは自分も理解不能です。

**Comment by ghost** [comment]
えーっと一応解決方法ですが
`S3 example` の
`endPoint: s3-us-west-2.amazonaws.com` を
`endPoint: storage.googleapis.com`
に書き換えるとアップロードできました

**Comment by ghost** [comment]
あとregion欄は合わせなくてもアップロードされるみたいです
なんでこれで解決できたんだろ........
GCSそのものがS3互換だからなのかな

**Comment by Amalilyth** [comment]
なんでこれで解決できたんだろ........

**Comment by ghost** [comment]
これ初見殺しだと思うんでどっかに書いておくべきかもしれませんね確かに........

**Comment by acid-chicken** [comment]
私が頭悪いだけかもしれないですが、初見殺しどころか何度コード読んでも理解に時間がかかります……。

**Comment by ghost** [comment]
とりあえずGCSの設定方法一番上に書いておいたんで誰かが参考にしてくれるのを願うばかりです

**Comment by ghost** [comment]
>  リクエスト エンドポイント

> Amazon S3 などの他のクラウド ストレージ システムで使用するツールまたはライブラリ内で、Cloud Storage URI( https://storage.googleapis.com )を使用するようリクエスト エンドポイントを変更してください

Google Cloud Storageのドキュメント先生がなんでこれで解決できたかを解説してくれました

**Comment by mei23** [comment]
https://github.com/syuilo/misskey/issues/4643#issuecomment-480576630
https://github.com/syuilo/misskey/issues/4643#issuecomment-480577371

なにをどう勘違いしてるか書いてくれないと、単にディスってるだけなんですが

**Comment by mei23** [comment]
>  S3 example (with CDN, custom domain)

は基本的に、amazon等所有のドメインではなく独自ドメインでストレージを公開したい場合の設定になります。
endpointと公開ドメインが同じサービスの場合は`S3 example`のように`baseUrl`は明記しなくてよく
さらに`region`の概念がないサービスの場合は一番最初の例でOKです。

**Comment by ghost** [comment]
なるほど、ありがとうございます
でもひとつだけ気になるのがGCSはリージョンの概念があるサービスなんですがregionを編集してなくても使えるんですよね......
(例:GCSのregionがUS-CENTRAL1なのにconfigに `region: us-west-2` と記述してあっても使える)

**Comment by mei23** [comment]
bucketは全世界でユニークのようなので、本来regionはなくてもbucketは特定できるのですが
AWSだとそれでもregion指定が必要なので設定値があります。
regionはAWSの場合以外は参照されないのかもしれません。
