### ISSUE TITLE
ストリームが死んでいた部分のタイムラインの表示について

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#4645]
## Summary
ストリームが切れたてまた復帰したとき、切れていた時間に受信されるはずだった部分が（なかったことのように）抜けたまま新しい投稿が来る。これは少し不親切だと思う。

ストリームが復活したときに、ストリームが死んでいた所に「ノートをさらに表示」というボタンを表示して、受信できていなかったことをわかるようにし、さらにその分の投稿を取得・表示できるようになれば便利だと思う。

**Comment by syuilo** [comment]
v12でページリロードできるようになった

**Comment by tamaina** [comment]
よさげ

**Comment by tamaina** [comment]
Had related to #1538

**Comment by syuilo** [comment]
一応まだPR段階なので開いておきます

**Comment by tamaina** [comment]
（#1538 と被っていたのでcloseしてみた）  
今のv12の実装では、ネットワークの変更（例: Wi-Fi→モバイルネットワーク）で一瞬切断された等の場合でもすぐにポップアップが出てきてしまって特にモバイルだとウザいかもしれないので、タイムアウトで表示するようにしたほうがよさそう  
瞬断してる間に見逃しちゃう問題はあるけど…

**Comment by tamaina** [comment]
GitHubがバグっていたのでcloseし直した
