### ISSUE TITLE
CIをv10とv11で分ける

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#4659]
Summary
--

v10、v11それぞれ分ける？もう誰も見てないしやめる？

**Comment by acid-chicken** [comment]
やるならやるで脆弱性周りだとかこの際ちゃんと解決しておきたい。

**Comment by acid-chicken** [comment]
とりあえず yarn.lock は完了。ただし submodule 更新時に毎回手動で要生成。 acid-chicken/misskeyci-docker#120

**Comment by rinsuki** [comment]
私的にはやりたい

**Comment by rinsuki** [comment]
というか今のテストまともに動いてない気がするしそこからなんとかしたほうがよさそう

**Comment by Johann150** [comment]
I think this could be closed?
