### ISSUE TITLE
サムネイルがないファイルの表示が変

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#4673]
## 💡 Summary
サムネイルが提供されないタイプのファイルの表示が変

## 🙂 Expected Behavior
- https://github.com/syuilo/misskey/blob/develop/src/client/app/common/views/components/drive-file-thumbnail.vue で指定された通りファイルアイコンが表示される

## ☹️ Actual Behavior
- v10だと( thumbnail not avilable )が表示される
- v11だとリンク切れ

## 📝 Steps to Reproduce
1. ドライブにサムネイルが提供されないタイプのファイルをアップロードする
2. 表示する

**Comment by tamaina** [comment]
なるほど、 #4380 で挙動が変わったからか

/assets/thumbnail-not-available.png を条件として指定するのはなんか嫌だがしかたあるまい

**Comment by tamaina** [comment]
> サムネイルが提供されている形式 (image, video) 以外のファイルを
> アップロードした / 添付しようとした 時に
> 
> ドライブファイル一覧や添付画像一覧が
> カラーバーになってしまったり (オブジェクトストーレジ未使用時)
> 真っ白になってしまったり (オブジェクトストーレジ使用時)
> するのを修正

を達成するのであれば、 #4380 をリバートしてpost-formのほうをdrive-file-thumbnailにしたほうが便利そう

**Comment by tamaina** [comment]
いやv11はそうではないのか

**Comment by tamaina** [comment]
# まとめ
v11、v10それぞれ原因が異なる。

## v11の仕様変更
- getPublicUrl()より、thumbnailUrlが必ず含まれるようになり、サムネイルやwebPublicがない場合はオリジナルと同じURLになる。

## v10の仕様変更
nullのかわりに`/assets/thumbnail-not-available.png`を返すようになった。

**Comment by mei23** [comment]
> getPublicUrl()より、thumbnailUrlが必ず含まれるようになり、サムネイルやwebPublicがない場合はオリジナルと同じURLになる。

thumbnailでimageじゃないURLを返すのはまずいからこれはバグだわ

**Comment by tamaina** [comment]
私の感想: サムネイルがないのであればthumbnailUrlはnullにするべきだと思います
