### ISSUE TITLE
CHANGELOG in English

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#4693]
> [私は英語わからない](https://github.com/syuilo/misskey/commit/26c327145f84b30c96a4ca128a2296ab8b9a6f7e#commitcomment-32032323)

らしいのでどうするか。

**Comment by fz0000** [comment]
大丈夫ですよ
 👉 [Google翻訳](https://translate.google.com)

 (ちなみに，私も日本語わからない 😂 )

**Comment by Johann150** [comment]
I think this can be resolved by the english release notes on Misskey Hub. But it seems they are not updated.
