### ISSUE TITLE
renote 内の耳が小さい

### ISSUE THREAD

**Issue by nzws** [misskey-dev/misskey#4699]
## 💡 Summary

![image](https://user-images.githubusercontent.com/14953122/56137261-63475900-5fcf-11e9-910f-0e094cf6d821.png)

## 🙂 Expected Behavior

投稿の大きさと同じくらいほしい
![image](https://user-images.githubusercontent.com/14953122/56137724-67c04180-5fd0-11e9-8788-706550262ff0.png)

## ☹️ Actual Behavior

控えめ

## 📝 Steps to Reproduce

1. cat になる
2. renoteする
3. みる

## 📌 Environment

- Misskey v11.0.3
- Google Chrome 73.0.3683.103 (Official Build) （64 ビット）

**Comment by Johann150** [comment]
I think it works better currently, but it still does not look nice if square avatars are enabled.

**Comment by tamaina** [comment]
ちゃんと表示されてるのでclose
