### ISSUE TITLE
アカウントページのもっと読み込むで400が返る

### ISSUE THREAD

**Issue by nzws** [misskey-dev/misskey#4700]
## 💡 Summary

![image](https://user-images.githubusercontent.com/14953122/56138233-74916500-5fd1-11e9-9068-24746372d4de.png)

## 🙂 Expected Behavior

- もっと読み込まれてほしい
- なんらかの理由で読み込みに失敗した場合はエラーを表示して、それ以上ロードしようとしないかクールタイムを設けてほしい

## ☹️ Actual Behavior

- `INVALID_PARAM` として400エラーが返ってくる
- クライアントがめちゃくちゃサーバにアクセス繰り返してDoS攻撃みたいになる
	- DevToolsにエラーめちゃくちゃ吐き出してるだけなのでユーザはDoS攻撃してる事に気が付いてない

## 📝 Steps to Reproduce

1. アカウントページ(ex: https://misskey.io/@syuilo )にいく
2. 下までいく
3. くるくるする

## 📌 Environment

- Misskey v11.0.3
- Google Chrome 73.0.3683.103 (Official Build) （64 ビット）

**Comment by syuilo** [comment]
ありがとうございます
これですね
https://github.com/syuilo/misskey/issues/4696

**Comment by nzws** [comment]
🙇
