### ISSUE TITLE
[v11] ユーザーページで Renote を見るとユーザーページのユーザーのリアクションが設定されている

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#4701]

**Comment by syuilo** [comment]
どういうことだろう

**Comment by acid-chicken** [comment]
分からない。
リアクションをした覚えのない投稿にリアクションがついている。

**Comment by syuilo** [comment]
> リアクションをした覚えのない投稿にリアクションがついている。

確認しました

**Comment by syuilo** [comment]
うーむわからない

**Comment by mei23** [comment]
どういう事象かわからない…

**Comment by syuilo** [comment]
1. ユーザーAがリアクションが付いた投稿(X)をRenoteする
2. ユーザーBがユーザーAのページを開く
3. このときXにリアクションを付けたのがユーザーBでなくてもユーザーBがリアクションしたように表示されている

**Comment by syuilo** [comment]
クライアントサイドの問題ではなくサーバーサイドの問題ということは判明

**Comment by syuilo** [comment]
あーーーーーーー

**Comment by syuilo** [comment]
わかった
