### ISSUE TITLE
[v11] いきなり過去の投稿がLTLに流れてくる

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#4704]
リロードすると消えるタイプのやつです

**Comment by mei23** [comment]
**Local** TL で発生するのは不自然

**Comment by acid-chicken** [comment]
謎すぎて再現性がないので謎

**Comment by syuilo** [comment]
これ関係してそう
https://github.com/syuilo/misskey/issues/4632

**Comment by mei23** [comment]
v11, v10 ともに #4632 で発生することを確認
