### ISSUE TITLE
APIが違うユーザー扱いになっている

### ISSUE THREAD

**Issue by YuzuRyo61** [misskey-dev/misskey#4705]
## 💡 Summary
ハッシュ化したトークンを扱ってAPI操作をすると違うユーザーとしてAPI操作してしまう。

## 📝 Steps to Reproduce

1. app/create でアプリを作成
2. 作成したシークレットキーでセッショントークンを作成 (auth/session/generate)
3. ブラウザで認証してアクセストークンを発行する(auth/session/userkey) ＜＝ここまでは自分のアカウントだということがわかった
4. アクセストークンとシークレットキーをsha256化してハッシュ化
5. ↑のキーを使って何かしらのAPI操作をする
6. 自分のアカウントではなく他のアカウントとして操作していることになってる

※ノート削除とか一部機能は通じない？？？

**Comment by syuilo** [comment]
その「ほかのアカウント」は常に同じアカウントですか？

**Comment by YuzuRyo61** [comment]
> その「ほかのアカウント」は常に同じアカウントですか？

どうやらしばらく置いてたりするとアカウントが変わっているようで・・・。

![image](https://user-images.githubusercontent.com/18282413/56145820-fab4a800-5fdf-11e9-8c52-9e5b8e0699d6.png)

**Comment by syuilo** [comment]
ありがとうございます🙏

**Comment by syuilo** [comment]
たぶんどこかのクエリが抜けていて、認証したアカウントではなく常に最新のアカウントを持ってきているように思える

**Comment by syuilo** [comment]
でも見た感じ問題ないので謎

**Comment by YuzuRyo61** [comment]
（これは放おっておけない致命的なバグですね・・・。）

**Comment by acid-chicken** [comment]
一旦リリース消したほうがいいのでは。原因がわからないまま本リリース（非プレリリース）で出したままにしておくのは、脆弱性を把握していない運用者やユーザーを非常に困惑させると思います。

**Comment by syuilo** [comment]
テーブルの定義に問題がありそう

**Comment by syuilo** [comment]
これかな
https://github.com/typeorm/typeorm/issues/1795

**Comment by syuilo** [comment]
リリースって消せるのかな？

**Comment by acid-chicken** [comment]
今一度脆弱性がないか確認したあとv11を放棄してv12でやり直すのも選択肢の一つかも。(PHP 6 などのような事例)

**Comment by syuilo** [comment]
とりあえず 11.1.3 で出します

**Comment by mei23** [comment]
https://github.com/syuilo/misskey/commit/400cdf0f269fc3b035b897e10323371d4c79c751
この変更を適用するのに、スキーマの同期とかマイグレーションは必要になりますかね？

**Comment by syuilo** [comment]
そう考えてます
なのでアクセストークン作成はできなくなってるかもしれないです
どうやって同期させるか考え中です

**Comment by syuilo** [comment]
TypeORM内部の実装に由来する問題だとしたら、もしかしたらスキーマの同期しなくても大丈夫かもしれないですね
