### ISSUE TITLE
Allow the user to set the destination of the move (movedTo) and distribute it remotely.

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#4706]
Child of #5475

## Summary

Be able to set up/provide acct as a place to move to.

引越し先としてacctを設定/提供できるようにする。

**Comment by acid-chicken** [comment]
ToDo: Mastodon 等の仕様を確認し、同じような形式で配信する。

**Comment by rinsuki** [comment]
AP上はmovedToに移行先ユーザーのIDっぽい

**Comment by tamaina** [comment]
https://github.com/misskey-dev/misskey/issues/5475 に集約します

**Comment by rinsuki** [comment]
引っ越し先指定機能と引っ越し機能は分けておいたほうがいいような…

**Comment by rinsuki** [comment]
(別に引っ越し先指定機能自体はそんな難しくないはずだし)

**Comment by tamaina** [comment]
#5475 が実装されればこれが実装されるのは自明だし #5475 はMisskey開発者が死ぬまで実装しろと言われ続けそうなので集約して問題ないかなと思った

確かにPRを分けて作る場合は残しといたほうが良いか

**Comment by tamaina** [comment]
英語じゃないのが面倒だからclose

**Comment by rinsuki** [comment]
別にEditでいくらでもタイトル編集できる

**Comment by tamaina** [comment]
> (別に引っ越し先指定機能自体はそんな難しくないはずだし)

引っ越し元アカウントが操作できないようにする（ただしデータの出力等はできる）ようにする必要があるのでやや厄介だと思う  
…と思ったけど、movedToUriを判定して許可したエンドポイントだけいじれるようにすればいいのかしらね

**Comment by rinsuki** [comment]
Mastodonの場合別にmovedToだけなら操作できたはず

**Comment by rinsuki** [comment]
…と思ったがそんなことはなかった
<img width="648" alt="image" src="https://user-images.githubusercontent.com/6533808/202523071-86649985-7da0-4a60-935d-f2c751fb1152.png">

**Comment by tamaina** [comment]
というか: Mastodonってredirectとmigrationがあるのか

**Comment by rinsuki** [comment]
まあ適当に新規投稿あたり絞っとくくらいでいいんじゃないかという気はするが
