### ISSUE TITLE
deckのウィジェットが翻訳されていない(?)

### ISSUE THREAD

**Issue by S4WA** [misskey-dev/misskey#4709]
misskey.io, misskey.xyz でdeckのウィジェットがそのまま出ています。
コードの[ここらへん](https://github.com/syuilo/misskey/blob/80a2172715b6dd225a331d8f2cbccc78dcbd1302/src/client/app/common/views/deck/deck.widgets-column.vue#L24)ですかね。

![image](https://user-images.githubusercontent.com/24929259/56150981-1ffae380-5feb-11e9-9a56-4cd81d7054fe.png)

**Comment by S4WA** [comment]
最新のバージョンだった時のテキストもですかね。

![image](https://user-images.githubusercontent.com/24929259/56152394-80d7eb00-5fee-11e9-85a9-b76617857dea.png)

https://github.com/syuilo/misskey/search?q=no-updates-desc&unscoped_q=no-updates-desc

**Comment by S4WA** [comment]
![Screenshot_20190416-101753](https://user-images.githubusercontent.com/24929259/56175871-0205a100-6034-11e9-9be7-ff1e799c78c5.png)

**Comment by tamaina** [comment]
https://github.com/syuilo/misskey/issues/4709#issuecomment-483478328  
これはリロードすれば直ると思う  
あとi18nとは別の問題

**Comment by S4WA** [comment]
okei

**Comment by S4WA** [comment]
追加で...
![image](https://user-images.githubusercontent.com/24929259/56192338-144e0200-6069-11e9-8491-e7dc4934420c.png)
