### ISSUE TITLE
catの猫耳にアバターの色が反映されない

### ISSUE THREAD

**Issue by Simirall** [misskey-dev/misskey#4716]
## 💡 Summary
avgColorがなんかエラってるのをConsoleで見た事があるので関係ありそう？

**Comment by acid-chicken** [comment]
Related to 3304cc106ec75c2bfceeb47336afc250fc392c86.

**Comment by Simirall** [comment]
ioでもいつのまにかアイコン再設定すると反映されるようになってた
再設定してない人はまだピンクだけど

**Comment by syuilo** [comment]
Fixed
