### ISSUE TITLE
11.1.3: 管理画面のインスタンスメニューで変更前の設定が読み込まれないことがある

### ISSUE THREAD

**Issue by khws4v1** [misskey-dev/misskey#4719]
## 💡 Summary

管理画面(/admin)のインスタンスメニューで設定を変更して保存した後にもう一度同じページを開くと変更前の設定が読み込まれることがあります。  
変更前の設定が読み込まれた場合でも変更は反映されています。

## 🙂 Expected Behavior

変更後の設定が読み込まれる。

## ☹️ Actual Behavior

変更前の設定が読み込まれる。

## 📝 Steps to Reproduce

1. 管理ページを開いてメニューの「インスタンス」をクリックする
2. 設定を変更して保存する
3. メニューの「ダッシュボード」をクリックしてすぐにメニューの「インスタンス」をクリックする

ブラウザを更新して、ページ読み込みが完了してからインスタンスメニューを開くと変更した設定が読み込まれます。  
更新してすぐだと変更前の設定が読み込まれます。

## 📌 Environment

Misskey 11.1.3

**Comment by mei23** [comment]
getMetaのキャッシュのせいだと思ったら
キャッシュを無効にしてもあきらかにAPIから古いデータが返ってきているので謎。
APIに送ってる更新データも間違ってないので謎。

1. 値を0→1に更新
2. 再fetchすると0のまま
3. 1→2に更新
3. 再fetchすると1の値が返ってくる

**Comment by mei23** [comment]
うちの環境ではMetaにレコードが2つ出来てしまっていましたので
https://github.com/syuilo/misskey/issues/4719#issuecomment-483672981 の常に数世代前の値が返ってきてしまう事象はそのせいだと思います。

もとのIssueのすぐにインスタンスの更新が反映されない事象は、クライアント側のgetMetaのキャッシュのせいと思われます。
