### ISSUE TITLE
v11 インスタンスにおいて、ユーザー名に含まれているカスタム絵文字が表示されなくなった

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#4721]
## 💡 Summary
Misskey v11インスタンスにおいて、カスタム絵文字がユーザー名に含まれている場合に表示されなくなってしまった。(最初は問題なく表示されたが、何らかの問題が発生している)
リモートへ送信されるデータにも同じ現象が発生してしまっている。

**Comment by tkmrgit** [comment]
### 追加情報
1.カスタム絵文字が含まれた状態でユーザー名を保存する
2.デザインページを開き、壁紙を設定する
3.何故かユーザー名のカスタム絵文字がバグる

**Comment by syuilo** [comment]
ありがとうございます
🙏
