### ISSUE TITLE
v11 インスタンスにおいて、一部のカスタム絵文字リアクションが行えない

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#4723]
## 💡 Summary

ioで用意されている :angry_thinking_sleeping_face_with_tongue_sticking_out: や、 :vomiting_thinking_skeptical_face_with_hugging_hands: 等の名前の長いカスタム絵文字リアクションが行うことができない

## 📝 Steps to Reproduce

1.投稿でリアクションボタンを押す
2.:angry_thinking_sleeping_face_with_tongue_sticking_out: 等のカスタム絵文字を入力してリアクション
3.リアクションが実行されず、なにも反映されない

## 備考

v10インスタンスから同様の操作を行ってもv11インスタンスにリモート反映されていない可能性がある(👍が送られた状態にもなっていない)

**Comment by rinsuki** [comment]
リアクションを保存する側は

https://github.com/syuilo/misskey/blob/6444ef644468faab47e2f9c2a592982eae81b85d/src/models/entities/note-reaction.ts#L38-L41

で32文字までなのに

カスタム絵文字の名前は

https://github.com/syuilo/misskey/blob/6444ef644468faab47e2f9c2a592982eae81b85d/src/models/entities/emoji.ts#L15-L19

128文字制限で収まらないカスタム絵文字がある

(そもそもこれ連合対応してるのか?)

**Comment by mei23** [comment]
`note-reaction.ts`は128まで増やしているけど、マイグレーションスクリプトは書いてないみたい
https://github.com/syuilo/misskey/commit/8a55bdd89da6aa1228612ed7a2449ad96d965b60#diff-7140e4dab9a9c0d288555c360690f3de
