### ISSUE TITLE
アニメーション画像の表示に色々問題がある

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#4728]
### ~~APNG~~
~~webpublicはアニメーションしなくなる~~ → #4108 

### GIF
サムネイルが作られない

## 📌 Environment
misskey v11.1.3

**Comment by syuilo** [comment]
FYI
https://github.com/sindresorhus/file-type/issues/212

**Comment by tamaina** [comment]
一応こういうのもあるっぽい
https://github.com/davidmz/apng-js

**Comment by mei23** [comment]
アニメーションを再構成したりリサイズするのは大変なので、現実的なのはこのあたり
- PNGだったら無条件でメタデータ除去もリサイズもしない (GIFと同じ動作)
- APNGだったら無条件でメタデータ除去もリサイズもしない
  (APNG検出ルーチンを追加する必要がある)
- APNGだったらメタデータ除去をするがリサイズはしない
  (APNG検出ルーチンとメタデータだけを除去するルーチンを追加する必要がある)

**Comment by mei23** [comment]
Related #4108

**Comment by mei23** [comment]
file-typeはAPNGに対応していた
https://github.com/sindresorhus/file-type/releases/tag/v12.0.0

ただ、今までAPNGも`image/png`だったのが`image/apng`扱いになりそうなので
ちょっと注意が必要そう

**Comment by tamaina** [comment]
file-typeをv12にアップデートしてgifと同じ扱いにすれば解決できそう  
#4108 に統合します
（余談: `image/apng`っていうMIME、どうなの…）

**Comment by acid-chicken** [comment]
`image/vnd.mozilla.apng`?

**Comment by tamaina** [comment]
IANA的には`image/vnd.mozilla.apng`らしい  
https://www.iana.org/assignments/media-types/image/vnd.mozilla.apng
