### ISSUE TITLE
リモートへの鍵アカウントへのフォロー申請が不安定

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4729]
私は確認したことないものの、フォロー申請できない、フォロー申請したのに相手には届いてない といった現象が報告されることが多い

**Comment by tkmrgit** [comment]
鍵アカウントに限らないと思われる。
v11インスタンスA→v10インスタンスB またはその逆をフォローする場合に、Bのインスタンスで1つでもフォローされているアカウントが存在しないとフォローが行えない。

なので現在の暫定解決方法は、たとえば

1. v11インスタンスAでv10インスタンスBのユーザーをリストに追加(ゴーストにフォローさせる)
2. v10インスタンスBのユーザーをフォロー
_逆の場合においてもほとんどの場合で同様の操作で行えるようになるようです。_

という手順を踏まないとうまくいかない場合が多い。v10の場合は相手のインスタンスでの画面を開いてフォローボタンを押すだけで大抵のアカウントのフォローは問題なく行えたが、v11ではこれが何故かできなくなっている。
またこちらの方法でもできる場合があるとのこと https://misskey.io/notes/7robussi87

**Comment by mei23** [comment]
1分後, 3分後 再確認したりすると成功してたりはしませんでしょうか？

AP deliverで初回配送が失敗して、2回め (1分後) の再送で成功する事象はなんか見る。

**Comment by syuilo** [comment]
> AP deliverで初回配送が失敗して、2回め (1分後) の再送で成功する事象はなんか見る。

これたまにありますね リアクションとか投稿とかでも

**Comment by mei23** [comment]
とりあえずv11に未認知ユーザーからActivityが飛んできた場合にエラーになるのを確認

**Comment by mei23** [comment]
>>  AP deliverで初回配送が失敗して、2回め (1分後) の再送で成功する事象はなんか見る。
>
> これたまにありますね リアクションとか投稿とかでも

外にIPv6で出ていけないホストで起きてるなら #4871 かもしれない

**Comment by mei23** [comment]
io は EADDRNOTAVAIL がいっぱい出てた
DockerだとIPv6無効なのかも

**Comment by tamaina** [comment]
どんな感じじゃろ  
少なくとも最近はこのような不具合の話は聞かない

**Comment by KisaragiEffective** [comment]
triage: staleなので閉じます。もし再発するようであれば改めてissueを立てるかこのissueを開いてください 🙏🏻
