### ISSUE TITLE
アプリから通知タブにアクセスできない

### ISSUE THREAD

**Issue by u1-liquid** [misskey-dev/misskey#4738]
## 💡 Summary

アプリ(Subway Tooter)から通知タブにアクセスできなくなりました
数日前のxyzでは問題なくアクセスできたはずです・・・

## 🙂 Expected Behavior

* 通知タブにアクセスできる

## ☹️ Actual Behavior
* HTTP 400 エラーでアクセスできず
![image](https://user-images.githubusercontent.com/17376330/56308103-6c782780-6181-11e9-867c-af9df8e625e2.png)
 

## 📝 Steps to Reproduce

1. Subway Tooter にmisskey.ioのアカウントを登録
2. 左側のメニューで通知を選び、misskey.ioのアカウントを選択
3. 追加された通知タブを見ると・・・

## 📌 Environment

Subway Tooter 3.4.7 on Android 9

**Comment by u1-liquid** [comment]
同じ環境でmisskey.xyzのアカウントは通知タブにアクセスできることを確認しました。

**Comment by rinsuki** [comment]
v11からのパーミッションにアプリが正しく追従できていないことが問題そう

**Comment by rinsuki** [comment]
SubwayTooterに限っては、もう修正されてリリース待ちなので、次のリリースがされて手元の端末で更新したらSubwayTooterで「アクセストークンの更新」をするとよさそう
https://github.com/tateisu/SubwayTooter/commit/d7d04fc6db91701f76e36d9f5a6f6f1dcdc586f0

**Comment by u1-liquid** [comment]
これがv11からのパーミッション定義の変更点による問題だとすると他の機能はどうやって動いてるんですかね・・・

**Comment by syuilo** [comment]
以前の形式のパーミッションは新しい形式に変換されて解釈されるのでそれで動いてそう

**Comment by rinsuki** [comment]
https://github.com/syuilo/misskey/pull/4687 で簡易的に新形式に置換するようにしたけど、いくつか簡単な置換だけじゃ対応できない変更がされた(複数形になったりとか)権限があったので、そこで死んでそう

**Comment by u1-liquid** [comment]
~~ちょっといろいろ試してみましたが書き込むのはほぼ全部４００エラーですね。
でもなぜかHTLとかプロフィールなどの読み込む動作は動いてるに見えます。
今どこパーミッションを変換してくれるロジックがないというならこれらの読み込む動作も制限されるべきなのではないでしょうか・・・~~
#4687 ちゃんと見てなかった・・・反省してます・・・🙏

**Comment by rinsuki** [comment]
パーミッションを指定する時の文字列が、v10までは `account-read`みたいなやつだったのが、v11から `read:account` のような表記に変更された

Pull Request #4687 で私が `hoge-fuga` のような表記を `fuga:hoge` に単純に置換する変更を入れたけど、`note` が `notes` になったとか、細かい表記が変更されたものがあり、一部は対応できていない。

恐らく影響を受けたのは

- 通知 (`notification` → `notifications`)
- 投稿書き込み (`note` → `notes`)

で、他の権限は問題なく使える (ので、タイムラインは見れるしプロフィールも見れる。恐らくファイルアップロードもできる)

**Comment by tamaina** [comment]
その後どうでしょうか？

**Comment by u1-liquid** [comment]
subwaytooter側から修正されましたね
クローズします（すっかり忘れてました）
