### ISSUE TITLE
ファイルのアップロードに失敗しても添付できているように見える

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#4742]
## 💡 Summary
![image](https://user-images.githubusercontent.com/6533808/56313256-29bc4c80-618d-11e9-81d8-28307631f3a5.png)

投稿には失敗する

## 🙂 Expected Behavior

アップロードに失敗したらその旨を表示し、添付ファイルのリストには追加しない

## ☹️ Actual Behavior

アップロードに失敗してもその旨が表示されず、添付ファイルのリストに追加されてしまう

## 📝 Steps to Reproduce

1. どうにかして `drive/files/check_existence` は通るけど `drive/files/create` は通らない環境にする (使っているS3サーバーを落とす、1ユーザーあたりの保存可能ファイルサイズを越える、拡張機能でAPIのURLをブラックリストに入れるなど)
2. 投稿フォームでファイルをアップロードしようとする
3. 失敗するが、成功したように見える

## 📌 Environment

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

**Comment by tamaina** [comment]
未だにこうなっていて不便なので直したい

**Comment by tamaina** [comment]
最近直したんじゃなかったかしら

**Comment by syuilo** [comment]
直った
