### ISSUE TITLE
Misskeyモバイルにリロード(再読み込み)のためのボタンが欲しい

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#4751]
## Summary

タイトルの通り、Misskeyがモバイル表示の場合に再読み込みをするためのボタンが欲しい。そのままページの再読み込みをするためのものなので location.reload(); ができる的なボタン。場所は今思いつくところではメニュー一覧に出てくるとかになると思われる

**Comment by tamaina** [comment]
そもそも可能な限りリロードが不要なようにアプリを作る必要があると思うし、だからメニューにリロードボタンを付けるのは論外だと思う。  
言語の変更などでリロードが必要なときはその都度リロードボタンを表示すればいいし

**Comment by tkmrgit** [comment]
iOSのPWAが12.3になってから再表示するとTL読み込みがうまくできなくなってしまっていてちょっと不便かなと。Misskey本体側で再表示したときの読み込みがうまくできると不要にはなると思うけど現状毎回リセットして再表示しなければならなくなってしまった

**Comment by mei23** [comment]
論外と言うほどでもないと思う

**Comment by tamaina** [comment]
論外は言いすぎた気がしますが、私的にリロードボタン設置というのは格好悪い解決策だと思います

**Comment by mei23** [comment]
~~じゃあ世の中のブラウザは全部格好悪いですね~~
アプリに入れる話だからそうでもないわね

**Comment by mei23** [comment]
他に手段がない環境があるから仕方ないと思う

**Comment by tamaina** [comment]
> アプリに入れる話だからそうでもないわね

あーよかった（どう返したものかと困ってしまった）

一時的な対策として導入するなら良いとは思いますが、最終的にはリロードが不要な設計にするべきです。Androidでもリロードが必要なわけですし。

**Comment by u1-liquid** [comment]
一応今の状態で使える方法としては、ホームまたはデッキのトグルをすれば再読み込みと同様な効果がある事を確認しております。
また、「円形のアイコンを使用」、「ユーザー名にコントラストを付ける」「ユーザー名のホストを省略しない」の設定変更、
#5142 (b3c6e28)からはデスクトップ・モバイルモード設定時
再読み込みをするかどうか確認するダイアログボックスが発生するようになっていますので、そちらの方法も使えると思います。

**Comment by syuilo** [comment]
v12でストリーミング切断時にページリロードするようになったので、それ以外でリロード必要になるケースはほぼないと思うのでリロードボタンは必要なさそうです。

**Comment by tamaina** [comment]
GitHubのバグによりRecloseします
