### ISSUE TITLE
ストリーミングのchannelイベントにチャネルIDが含まれない

### ISSUE THREAD

**Issue by tateisu** [misskey-dev/misskey#4801]
## 💡 Summary

```
{
	"type":"channel",
	"body":{
		"type":"followed",
		"body":{
			"id":"7rm8yhnvzd",
			"name":null,
			"username":"tateisu_test2",
			"host":null,
			"avatarUrl":"https://misskey.io/avatar/7rm8yhnvzd",
			"avatarColor":null,
			"emojis":[]
		}
	}
}
```

## 🙂 Expected Behavior

https://misskey.io/docs/ja-JP/stream によるとチャネルからのメッセージにはチャネルIDが含まれるはず

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by tateisu** [comment]
{"type":"channel","body":{"type":"readAllNotifications","body":null}}

**Comment by rinsuki** [comment]
@tateisu どのようにチャンネルに接続する際にIDを指定していますか?
WebUIのストリーミングではIDが含まれているように見えます。

**Comment by tateisu** [comment]
IDがnullでもチャネルを登録できてしまうらしい

**Comment by rinsuki** [comment]
繋ぐストリームが一本だけ(LTLビューワーなど)、などのシチュエーションではチャンネルを識別できる必要がないのでIDを必須にする必要はないと思いますが、どうでしょう
(ID未指定で二本目からはエラーにするなどはあり? でも今のチャンネル購読って購読失敗のレスポンス返せるんだろうか)
cc: @syuilo

**Comment by tateisu** [comment]
https://misskey.io/docs/ja-JP/stream でIDを指定するように書いてあるので、IDなしでもいけるのならむしろドキュメントを直すべきなのでは。

**Comment by syuilo** [comment]
IDをnullにすることはできないようにしようと思います
