### ISSUE TITLE
デッキの通知カラムのリアクションが自分のものとして表示されない

### ISSUE THREAD

**Issue by nzws** [misskey-dev/misskey#4804]
## 💡 Summary

![image](https://user-images.githubusercontent.com/14953122/56737239-ee310c00-67a4-11e9-91be-db9ea3cb68d9.png)

(村上さんの投稿に対して💛リアクションを入れたのは自分ですが、通知には他人のリアクションとして見えてしまっています)

## 🙂 Expected Behavior

- 自分が行ったリアクションとして表示される

## ☹️ Actual Behavior

- 他人のリアクションとして表示される

## 📝 Steps to Reproduce

1. デッキにアクセスして通知カラムを開く
1. 他の人からリプしてもらうなりで投稿を通知に表示させる
2. リアクションする
3. リロードする

## 📌 Environment

- Misskey ver 11.4.0 (daybreak)
- Google Chrome 73.0.3683.103 (Official Build) （64 ビット） (cohort: Stable)

**Comment by rinsuki** [comment]
Notificationのpackするときにmeがないのが原因っぽい

**Comment by syuilo** [comment]
治ってそう
