### ISSUE TITLE
他のインスタンスのユーザーの自己紹介のMFMが壊れて見える

### ISSUE THREAD

**Issue by u1-liquid** [misskey-dev/misskey#4810]
## 💡 Summary

タイトル通り。

~他の鯖にプロフィールの情報を送る時は原文のプレーンテキストを提供する方がいいと思います。~
[ActivityPub仕様](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-summary)ではsummaryやコンテンツ等でHTMLを使うの自体は何の問題もないっぽい
HTMLでフォーマットされたメッセージのレンダリングの問題？

下のスクショをご覧下さい。

## 🙂 Expected Behavior

Misskeyインスタンスの間はプロフィールの自己紹介がMFMでレンダリングされる、Misskeyではない鯖では平文で提供される

### 自己紹介をMFMで書いたMastodonユーザー
![Screenshot_20190428-023915](https://user-images.githubusercontent.com/17376330/56853352-5debf600-6961-11e9-9148-6d97f6ea2d49.png)
### ほぼ同じ内容のMisskeyユーザー（他の鯖）
![Screenshot_20190428-023932](https://user-images.githubusercontent.com/17376330/56853367-ab686300-6961-11e9-83c6-7dee1fa4d009.png)
### Misskeyで見えるMisskeyユーザーの自己紹介（正常）
![Screenshot_20190428-023853](https://user-images.githubusercontent.com/17376330/56853427-ae178800-6962-11e9-9226-cee86a6f9c26.png)

### Mastodonで見えるMisskeyユーザーの自己紹介
![Screenshot_20190428-030250](https://user-images.githubusercontent.com/17376330/56853410-29c50500-6962-11e9-8274-8a8023f23e62.png)

## 📝 Steps to Reproduce

1.プロフィールの自己紹介をMFMで書く
2.他の鯖で確認する
3.読めない・・・

## 📌 Environment

Misskey v11.4.0
Mastodon v2.8.0

**Comment by futchitwo** [comment]
旧フロントエンドのissueですが、現在でもこの問題は起こりますか？

**Comment by ThatOneCalculator** [comment]
Still a problem on Misskey v12.111/112-beta

**Comment by kakkokari-gtyih** [comment]
まだこの問題残ってますね

- 発信元（画像右）: v13.14.2-io.4
- 確認サーバー:
  - p1.a9z.dev v13.14.2-p1.90
  - misskey.backspace.fm（画像左） v13.14.2-bsk0.1.1

![image](https://github.com/misskey-dev/misskey/assets/67428053/95195899-e98d-483c-806d-cebe65d84b9b)
