### ISSUE TITLE
Credential requiredエラーでファイルがアップロードできなくなることがある

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4813]
Chromium系だけで起きるっぽい

**Comment by syuilo** [comment]
ServiceWorkerが悪さしてそうだということが分かった

**Comment by mei23** [comment]
Chromium系で起きる

これが起きてるときは、ファイルアップロード時のmultipartの中にiがない
(他のパラメーターがどうかなってたかは未確認だけど、おそらくformの中身丸ごとないのかも)

関係してそうなもの
https://stackoverflow.com/questions/56413685/form-data-not-always-send-in-chrome-when-uploading-file-with-angular-7
https://github.com/angular/angular/issues/29629
(Chromium固有っぽいので誰かレポートしておいてみたいな感じで終わってる)
