### ISSUE TITLE
IDが誤採番されたインスタンスのデータの修復方法

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4815]
## Summary
https://github.com/syuilo/misskey/issues/4752 のため
v10 => v11 マイグレ後に意図しないIDが採番されてしまったインスタンスが存在していて

```
5xxxxxxxxxxxxxxxxxxxxxxx ←マイグレ前の採番
:
f8xxxxxxxxxxxxxxxxxxxxxxx ←マイグレ後の誤採番
:
8xxxxxxxxxxxxxxxxxxxxxxx ←マイグレ後の正常採番
```

マイグレ後の誤採番がソートした時に一番最初に来るため、各TLや通知などで上に来てしまう事象が起きてます。

- 投稿を管理者削除する
  →グローバル分が多すぎる
  →通知とかが消えない
- DBからデータを消す
  →対象テーブルが多そう
  →データは消えてしまう
  →本当に大丈夫なのか？
- f8より上のIDを採番するようにする
  →プログラムを変えないといけないが一番確実そう

どうすればいいのか

**Comment by rinsuki** [comment]
バグった箪笥用のID採番設定を付けるのがいちばん楽そう (見た目はアレだけど仕方ない)
