### ISSUE TITLE
Mastodon v2.8.0 のフォローリストがインポートできない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4816]
## 💡 Summary
Mastodon v2.8.0 のフォローリストがインポートできない

```
Account address,Show boosts
user@host,true
:
```
みたいなの

## 🙂 Expected Behavior
できる

## ☹️ Actual Behavior
できない

## 📝 Steps to Reproduce

1. Mastodon v2.8.0 のフォローリストをインポートする

**Comment by acid-chicken** [comment]
そもそも現状の実装が似非CSV？

**Comment by mei23** [comment]
前は
```
user@host
:
```
だったけどヘッダ行とカラムがふえた

**Comment by acid-chicken** [comment]
ヘッダ行があったりなかったりは厄介……。

**Comment by rinsuki** [comment]
最初の行がacctっぽくなかったら新仕様?

**Comment by acid-chicken** [comment]
`複数のカラムが存在する && 二つ目のカラムが/true|false/でない` が今のところ確実？

**Comment by rinsuki** [comment]
そもそもMastodonはどうしてるんだろう
