### ISSUE TITLE
api-docにアクセスできない

### ISSUE THREAD

**Issue by nzws** [misskey-dev/misskey#4825]
## 💡 Summary

https://misskey.io/api-doc

![image](https://user-images.githubusercontent.com/14953122/56967334-f53c8d80-6b9b-11e9-848b-fff852a2f0d5.png)

## 📌 Environment

- Misskey ver 11.7.0 (daybreak)
- Google Chrome 73.0.3683.103 (Official Build) （64 ビット）

**Comment by tamaina** [comment]
APIのパーミッションに問題がありそう

**Comment by tamaina** [comment]
既定のパーミッションのリストにないkindがAPIに指定されていると`api.json`にアクセスした際エラーを吐くように設計されているので、サーバーを動かしてみて`/api.json`にアクセスした際のエラーメッセージを見れば修正できそう  
（エラーにしないようにするのは……ご自由にどうぞ…）  
https://github.com/syuilo/misskey/blob/develop/src/server/api/openapi/description.ts
