### ISSUE TITLE
Firefoxで自分のユーザーメニューが開けない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4843]
## 💡 Summary
Firefoxで自分のユーザーページのメニューが開けない

## 🙂 Expected Behavior
開ける

## ☹️ Actual Behavior
開けない

## 📝 Steps to Reproduce
1. 自分のユーザーページに行く
2. …のメニューをクリックしても何も起きない (カーソルも変わらない)

なおコンソールに`this.$updateBanner is not a function`が出てくるがこれは直接関係なし。
これは 正常に開ける場所でも Chrome でも 出てきてしまう別の問題。

## 📌 Environment
Misskey v10, v11
Firefox 66

https://github.com/mei23/misskey/commit/53cf0c4d52078520d2ba905a7910d542d22ff92f でなおる

**Comment by rinsuki** [comment]
Firefox 66で再現してFirefox Developer Edition (67.0b17)で再現しないのでFirefox 66のバグっぽい
環境: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0`
