### ISSUE TITLE
ページ移動時にスクロール量のリセットが遅れる

### ISSUE THREAD

**Issue by nzws** [misskey-dev/misskey#4855]
## 💡 Summary

ので無駄にロードされている気がする
https://imgur.com/a/ifBhhdR

## 🙂 Expected Behavior

- ページ移動前(瞬間?)にスクロール量がリセットされる

## ☹️ Actual Behavior

- ページ移動してから数秒後にスクロール量がリセットされる

## 📌 Environment

- Google Chrome 73.0.3683.103 (Official Build) （64 ビット） (cohort: Stable)
- Misskey ver 11.10.0 (daybreak)

**Comment by syuilo** [comment]
Fixed
