### ISSUE TITLE
Deckでユーザー投稿の一部しか表示できない

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#4860]
## 💡 Summary

Deckでユーザー投稿の一部しか表示できない

## 🙂 Expected Behavior

過去の投稿が表示される

## ☹️ Actual Behavior

永遠と読み込まれず、リクエストで400が帰ってきている

## 📝 Steps to Reproduce
Deckでユーザーページを表示し、一番下までスクロールする

## 📌 Environment

Chrome Windows 73.0.3683.103 64bit

Misskey v11.10.1 

## memo
untilDateがnumberで定義されているが、リクエストはstringになっている

https://github.com/syuilo/misskey/blob/987168b863c52d0548050ffbac569782bb9a8cef/src/server/api/common/make-pagination-query.ts#L3

![image](https://user-images.githubusercontent.com/37681609/57187615-ab053480-6f2c-11e9-86f8-54c93b28d12f.png)

**Comment by syuilo** [comment]
https://github.com/syuilo/misskey/issues/4696
ですね
