### ISSUE TITLE
テーブル

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4861]

**Comment by tamaina** [comment]
これは何

**Comment by syuilo** [comment]
テーブルを作れるように

**Comment by tamaina** [comment]
MFMか

**Comment by syuilo** [comment]
ではない

**Comment by tamaina** [comment]
https://ja.wikipedia.org/wiki/%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB_(%E6%83%85%E5%A0%B1)
こういうやつか

**Comment by syuilo** [comment]
はい

**Comment by Johann150** [comment]
Would this be a MFM feature or just specific to pages?

**Comment by syuilo** [comment]
Either would seem to be fine, but may not be necessary in the first place.
