### ISSUE TITLE
[v11] `/i/messaging/username` でカスタム絵文字が表示されない

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#4867]
Misskey v11ではv10ではトークでも利用できたカスタム絵文字をv11では使用することができなくなっている。

**Comment by u1-liquid** [comment]
## 参考資料

![image](https://user-images.githubusercontent.com/17376330/57261942-f80c1680-70a4-11e9-92ae-66f2e129ca07.png)
![image](https://user-images.githubusercontent.com/17376330/57261949-fd696100-70a4-11e9-90b2-e5d2019e5e22.png)

そしてMFMなのにカスタム絵文字を使えない場所がありました。

### Misskeyページのテキスト
これはなぜか他のViewから最初に移動された時はカスタム絵文字がちゃんと見えますが同じページを一回再読込みすると下のようにカスタム絵文字だけプレーンテキストになります。
- 最初はこう見える
![image](https://user-images.githubusercontent.com/17376330/57262248-57b6f180-70a6-11e9-9f1e-c0f5a7095064.png)
- 再読込みするとこう見える
![image](https://user-images.githubusercontent.com/17376330/57261998-428d9300-70a5-11e9-8101-8b498c4962d9.png)

**Comment by mei23** [comment]
タイミングによって使えないのは #5105 かも
なおっているかは未確認

**Comment by rinsuki** [comment]
なおってそう だめだったらreopenしてください
