### ISSUE TITLE
トーク画面において、スクロールバーがメッセージ入力部まで表示されている

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#4868]
![image](https://user-images.githubusercontent.com/6533808/57250206-dd747600-7081-11e9-99f9-9a27df322e65.png)

スクロールバーが画面全体に表示されていますが、メッセージ送信欄は別にここのスクロールに関係ないので、ログの部分だけスクロールできるようにしたほうがいいと思うのですが、どうでしょう。
cc: @syuilo

**Comment by mei23** [comment]
Firefox で下のメッセージ送信欄に隠れた部分が見れないという問題もあり #4092

**Comment by syuilo** [comment]
v12で変わりました
