### ISSUE TITLE
isVerified廃止

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4870]
需要がなさそう

**Comment by u1-liquid** [comment]
藍ちゃんとかアプデ告知アカウントにピッタリだと思ってましたが
そう見りゃ公式アカウント一覧よりボット一覧のほうがいいかもしれませんね・・・

**Comment by syuilo** [comment]
misskey.io ではまあまあ使われてるけどその他のインスタンスでは isVerified はあまり使う機会がなさそう

**Comment by tamaina** [comment]
misskey.ioではまあまあ使ってるので廃止するのはよくない気がします

**Comment by syuilo** [comment]
ioのは本来想定している使い方とは少し違いそう

**Comment by SanMurakami** [comment]
io以外にもでかい規模のインスタンスが将来出来るかもしれない
有名人も来るかもしれない
そんなに複雑な機能では無いのでわざわざ消す必要もなさそう。

**Comment by tamaina** [comment]
@syuilo が本来想定していた公式アカウントバッジの使い方というものを見かけたことがまったくないのですが、どこに書かれていますか？

公式アカウントバッジの廃止についてアンケートをとってみましたので参考にしていただきたいです。  
https://misskey.io/notes/7sid7z3388

**Comment by syuilo** [comment]
Twitterと同じく著名な人物のなりすまし防止を目的としています

**Comment by tamaina** [comment]
> Twitterと同じく著名な人物のなりすまし防止を目的としています

たとえば、著名人や有名なグループが自身のファンのために開設するインスタンスでは、isVerifiedはその中心的な人物を判別するためにとても有効です。  
isVerifiedが廃止されると、逆にこのようなインスタンスは立てにくくなります。

**Comment by syuilo** [comment]
争いの元になるということが分かったのでやっぱり廃止したいと思います

**Comment by acid-chicken** [comment]
> 争いの元になるということが分かったので

流れは知りませんが misskey.io だけで起こったことを全体に持ち込むべきではないのでは。かつてのユーザーサジェストのようにオプションじゃダメだったんですかね。

**Comment by syuilo** [comment]
> 争いの元になるということが分かったので

これはおまけのような情報です
機能として明確な用法の定義がないのが最大の問題です

**Comment by acid-chicken** [comment]
> 機能として明確な用法の定義がない

なら、それこそオプションとして置いておいて各インスタンスのオーナーに解釈を仰げばいいのでは。
機能の追加はマイナーチェンジとしてよくても、もともとあった機能が消えるのは各インスタンスにあまり親切な変更ではないと思う。

**Comment by syuilo** [comment]
各インスタンスで用法が違う機能というのは不便

**Comment by acid-chicken** [comment]
それを言い出したら ActivityPub なんてめちゃめちゃ不便な気がする

**Comment by nokotaro** [comment]
個人的には廃止すべき機能だと考えています。すでにClosedなIssueにわざわざ長文コメントするのはどうかと思いつつも、個人鯖で発言したところでContributorの目には止まらないので、やはりこれからはGitHubでも積極的にコメントをする必要があるなと感じました。

isVerifiedの良い面としては、各インスタンスのadminが悪質ななりすましアカウントからユーザーを保護することが挙げられます。一方で、バッジを付与するしないの明確な基準を設けない限り、真にユーザーを保護することにはならず、むしろ、付与基準をどう設定するかという問題が生じることで、ユーザー間やadmin間(もしisVerifiedがisCatのようにリモートでも反映されるとすればなおさら)で要らぬ論争を生む懸念があります。

>たとえば、著名人や有名なグループが自身のファンのために開設するインスタンスでは、isVerifiedはその中心的な人物を判別するためにとても有効です。

本人、もしくは本人の関係者がインスタンスを開設・運営してるのであれば、admin権限を利用して不正なアカウントを凍結すれば済む話ではないでしょうか？
ユーザー保護以外の使用、活用方法として、例えば「adminではないがインスタンスの中心的なメンバーに付与する」「moderatorとは異なる働きでインスタンスの運営に貢献してくれているユーザーに付与する」などという意見もありますが、「isVerified」「公式アカウント」などの名称が付いている以上「著名人になりすますことで悪質な行為を働くアカウントからユーザーを保護するため」以外の用途としてこの機能を使用するのはユーザーにとってあまりにも不親切であるので、それはそれで別実装にすべきだと思います。

**Comment by tamaina** [comment]
> 本人、もしくは本人の関係者がインスタンスを開設・運営してるのであれば、admin権限を利用して不正なアカウントを凍結すれば済む話ではないでしょうか？

確かに凍結すればいい話ですが、凍結のようなブラックリスト式と比較してisVerifiedのようなホワイトリスト式のほうがインスタンスの瞬発力が高まりユーザーの混乱を招きにくいはずです。  
さらに、プログラム上で容易に判別可能なbool値であるため、私はバッジがついたユーザーのみのタイムライン( #4663 )のような形でもっと活用できると考えていましたし、exproleページではisVerifiedなユーザーのリストが公開されていました。

> 各インスタンスで用法が違う機能というのは不便

> ユーザー保護以外の使用、活用方法として、例えば「adminではないがインスタンスの中心的なメンバーに付与する」「moderatorとは異なる働きでインスタンスの運営に貢献してくれているユーザーに付与する」などという意見もありますが、「isVerified」「公式アカウント」などの名称が付いている以上「著名人になりすますことで悪質な行為を働くアカウントからユーザーを保護するため」以外の用途としてこの機能を使用するのはユーザーにとってあまりにも不親切である

プログラムが想定した使い方以外の使い方について考えてしまえば、ほかの機能についてもいくらでも言えますから、廃止の理由にならないと思います。プログラムの作成者が、そのプログラムの機能一つ一つの使い方についてあまり強制できるものではないと私は考えています（もちろん法律に抵触するような行為は禁止するべきですが）。  
また、isVerifiedのような機能はインスタンスの管理者の裁量に基づいており、その裁量がインスタンスごとに違うということについてほとんどのユーザーは理解できると思いますし、周知するべきだと思います。isVerifiedの付与の裁量がインスタンスによって違うことがユーザーにとって過度に不親切とはいえないと思います。

**Comment by acid-chicken** [comment]
機能を使いたくないインスタンスでは使わない、活用したいインスタンスでは使うということができるように、オプションで置いておくとある程度共通化されてかつ意味合いがそこまで揺れていない情報として存在するのは有用だったと考えるのですが、オプションとしてまで持ちたくなかった理由が分からないです。これを復活させるためだけに fork をして自分で revert しろというのも非プログラマな運営者に不親切な気がしてならないのですが……。

**Comment by tamaina** [comment]
ユーザーのピン留めを作るつもりだったなら最初から言ってほしい

**Comment by syuilo** [comment]
> オプションとしてまで持ちたくなかった理由

何のための機能かはっきりしていないためです

**Comment by acid-chicken** [comment]
> ユーザーのピン留めを作るつもり

どこ情報ですか

**Comment by syuilo** [comment]
> ユーザーのピン留めを作るつもりだったなら最初から言ってほしい

https://github.com/syuilo/misskey/issues/4870#issuecomment-490456857

**Comment by tamaina** [comment]
あーなるほど...

**Comment by acid-chicken** [comment]
「すれば良さそう」は提案であって実装予定の表明ではなくないですか
せめて Feature Request の Issue を作って頂ければ納得がいきます

**Comment by u1-liquid** [comment]
> せめて Feature Request の Issue を作って頂ければ納得がいきます

これは多分私が #4892 作ってたのでこうなったと思います。#4892にこっち reference して置くべきでした

**Comment by acid-chicken** [comment]
……！
ありがとうございます、全て納得がいきました。

**Comment by acid-chicken** [comment]
@syuilo 申し訳ありませんでした、他の Issue を追えていませんでした。上記の提案を全撤回します。
