### ISSUE TITLE
isVerifiedオプション化

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#4891]
機能を使いたくないインスタンスでは使わない、活用したいインスタンスでは使うということができるように、オプションで置いておくとある程度共通化されてかつ意味合いがそこまで揺れていない情報として存在するのは有用だったと考えるのですが、オプションとしてまで持ちたくなかった理由が分からないです。これを復活させるためだけに fork をして自分で revert しろというのも非プログラマな運営者に不親切な気がしてならないのですが……。

_Originally posted by @acid-chicken in https://github.com/syuilo/misskey/issues/4870#issuecomment-490976266_

**Comment by EbiseLutica** [comment]
#4107 を実現させたら汎用的でなおかつ表現が明確なalternativeとして成り立つと思っているのですが......。

**Comment by acid-chicken** [comment]
explore が地獄化しませんか

**Comment by EbiseLutica** [comment]
なぜ

**Comment by acid-chicken** [comment]
公式アカウントカラムのあった部分をバッヂごとに拡張したいということではなく？

**Comment by acid-chicken** [comment]
OSS は独裁的でなんぼと指摘があったので閉じます
