### ISSUE TITLE
おすすめアカウント機能

### ISSUE THREAD

**Issue by u1-liquid** [misskey-dev/misskey#4892]
## Summary

「おすすめのアカウント」を提案します。

おすすめのアカウントは3種類あって、一覧にはそれぞれの属性と短い説明文ををアカウント名と一緒に表示します。
* 永久、鯖缶指定
   常駐bot、告知アカウントなど
* 期間限定、鯖缶指定
   任期制のモデレーター、イベント用アカウントなど
* 期間限定、最近の「ハイライト｣ノートの投稿者
  インスタンスの規模によって適当に期間設定

あとこのおすすめアカウントはユーザー設定でOpt-Inすることで専用のTLが見れると良いですね。

**Comment by syuilo** [comment]
注目のノート機能は既にありますね

**Comment by u1-liquid** [comment]
そう言えばハイライト機能がありましたね。
眠すぎて勘違いしちゃったみたいです😪

**Comment by u1-liquid** [comment]
ピン留めされたユーザー機能で十分だと思います。
