### ISSUE TITLE
PWAとしてインストールできない

### ISSUE THREAD

**Issue by u1-liquid** [misskey-dev/misskey#4895]
## 💡 Summary

#4813 のせいで 289c76a8 でswが無効化されており、PWAとしてインストールできないことになっている

参考 https://developers.google.com/web/fundamentals/app-install-banners/?hl=ja

## 🙂 Expected Behavior

Service Worker が登録される

## ☹️ Actual Behavior

Service Worker が登録されない

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Android Pie

**Comment by syuilo** [comment]
PWAにServiceWorker必須なのか～

**Comment by mei23** [comment]
ServiceWorker は有効なままキャッシュだけ無効にしたら #4813 発生しなくなった気がするので
キャッシュは無効なままで ServiceWorker 有効にしてもいいかも。

**Comment by u1-liquid** [comment]
🤔 
![image](https://user-images.githubusercontent.com/17376330/59968693-af3aef00-9578-11e9-996a-63cd880e7858.png)

**Comment by EbiseLutica** [comment]
SWのキャッシュ機能が無いとPWA化はできないみたいです（そもそもキャッシュされたフロントエンドがオフライン環境で表示される点がPWAのミソですしね...）

**Comment by mei23** [comment]
AndroidのChromeやFirefoxではPWAできる
出来ないというのはDesktop Chromeのこと？

**Comment by u1-liquid** [comment]
これがPWA ホーム画面に追加するとアプリと同じようになります
![Screenshot_20190803-224144](https://user-images.githubusercontent.com/17376330/62412594-0fc14f80-b640-11e9-9ab5-f8285ff32584.png)
![Screenshot_20190803-224432](https://user-images.githubusercontent.com/17376330/62412632-67f85180-b640-11e9-890d-c5c69515a053.png)
![Screenshot_20190803-224440](https://user-images.githubusercontent.com/17376330/62412636-6cbd0580-b640-11e9-9260-846bb86d4f5a.png)

これはPWAではありませんね
ただのショートカットアイコンです
![Screenshot_20190803-224202](https://user-images.githubusercontent.com/17376330/62412601-1f409880-b640-11e9-86ab-d996fb5eab7d.png)

**Comment by mei23** [comment]
~~追加できてる~~ いやわからない

**Comment by mei23** [comment]
追加できてる
![image](https://user-images.githubusercontent.com/30769358/62413393-7139ec00-b649-11e9-8809-df24dfbe28ad.png)

**Comment by EbiseLutica** [comment]
macOS on Chrome でアプリとして認識されないのよね...

**Comment by u1-liquid** [comment]
~めいすきーはできるけどioはできない状態です~
めいすきーもできない？

**Comment by mei23** [comment]
あー新規追加できないかも
うちの端末だと完全に同じ見た目でアプリの一覧にはないというパターンになる Android 6.0

**Comment by rinsuki** [comment]
実装当初と変わってなければ、Android ChromeでPWAアプリ(WebAPK?)になるのはインストール催促バナーからインストールした時だけでメニューのショートカット作るみたいなやつからやってもならない

**Comment by u1-liquid** [comment]
> メニューのショートカット作るみたいなやつからやってもならない

TwitterやMastodonはメニューから｢ホーム画面に追加｣してもPWAになりますのでそれは違うと思います
