### ISSUE TITLE
Use Full Screen Width

### ISSUE THREAD

**Issue by Golutazem** [misskey-dev/misskey#4898]
Use the entire screen width to display content.  If there is a margin, make it not large -- not greater than about 2rem.
Currently, much space is unnecessarily wasted on a typical desktop monitor, even if
Deck column width = wide
. Using the CSS `flex` attributes is an option for sizing multiple columns. I may be able to help with that if you wish.

**Comment by Johann150** [comment]
Making the text full width is not sensible for multiple reasons:
1. Misskey is intended for short texts (notes) so most text would only be one or two lines anyway.
2. Text at full screen width on desktop devices has been shown to have worse readability than text with shorter line lengths.

If you are concerned about wasted screen space I would suggest switching to another of Misskey's UIs, for example use the *Classic* UI and add widgets to fill the "wasted" space.
