### ISSUE TITLE
HTTP Authentication

### ISSUE THREAD

**Issue by Golutazem** [misskey-dev/misskey#4901]
Allow the user to authenticate by HTTP Authentication.
This could be at a special URL for that purpose.

Using HTTP Authentication has the following benefits:
- It is automatically presented in the user's language for any language his browser supports
- It is certain to be visible and reliable. There are no problems caused by errors in your own log in page. The browser maker is responsible.
- If the browser can remember user name and passwords, it is guaranteed to work with that feature

**Comment by Johann150** [comment]
Using HTTP Basic Authentication would be problematic if a server is running only with HTTP and not HTTPS. Further there is no way to *log out* somebody who was using HTTP Basic Authentication because the browser will cache the authentification data.

Therefore I think this is not a good idea.
