### ISSUE TITLE
Import and Export Lists of Users to Follow or Mute or Block

### ISSUE THREAD

**Issue by Golutazem** [misskey-dev/misskey#4902]
Enable the user to import and export lists of users to follow or mute or block.
I believe that delimiting each entry with a linefeed character should be adequate. Mastodon works with such lists.

**Comment by syuilo** [comment]
The feature already exists.
![image](https://user-images.githubusercontent.com/4439005/57576826-6b969500-74a4-11e9-8c71-f2c75bc2029c.png)

**Comment by Golutazem** [comment]
You are correct. I am sorry for causing trouble.
