### ISSUE TITLE
DeckからPagesを開くとNot foundと出る

### ISSUE THREAD

**Issue by kabo2468** [misskey-dev/misskey#4905]
## 💡 Summary

DeckからPagesを開くとNot foundと出る

## 🙂 Expected Behavior

ページ一覧が出る

## ☹️ Actual Behavior

Not foundと出る

## 📝 Steps to Reproduce

1.Deckにする
2.上のところからページを選ぶ
3.Not found

## 📌 Environment

v11

**Comment by tamaina** [comment]
c7cc3dcdfd2c0962a39e7186852a17dbd09b6a5b で直ったみたい？
