### ISSUE TITLE
External user recommendation is secretly deleted in version 11

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#4907]
## 💡 Summary

In the version 11, our _external user recommendation_ feature is completely deleted. It has done in the commit https://github.com/syuilo/misskey/commit/f0a29721c9fb10f97faf386bc9d6b1b2fad97895, which is described just _Use PostgreSQL instead of MongoDB._ It is not too hard to migrate the _external user recommendation_ feature to PostgreSQL, but the developer have deleted the feature secretly.

No one loves _external user recommendation_ feature? https://misskey.m544.net or [some instances](https://distsn.org/misskey-instances.html) run their external user recommendation. But not available on the version 11.

## 🙂 Expected Behavior

Version 11 instances run the _external user recommendation_ feature.

## ☹️ Actual Behavior

In version 11, the code of _external user recommendation_ is completely deleted.

## 📝 Steps to Reproduce

No steps.

## 📌 Environment

Any environment.

**Comment by acid-chicken** [comment]
*It seems* he don't want to maintain features which isn't used in misskey.io (See conversation of #4870, the response was stopped at <https://github.com/syuilo/misskey/issues/4870#issuecomment-490976266>).

**Comment by syuilo** [comment]
> he don't want to maintain features which isn't used in misskey.io

No.

**Comment by syuilo** [comment]
> See conversation of #4870

繰り返しますが、公式バッジ機能の廃止にioは全く関係していません。

**Comment by acid-chicken** [comment]
> 繰り返しますが、公式バッジ機能の廃止にioは全く関係していません。

でしたら #4870 の方に投げた質問の回答を頂けると幸いです。（質問と同じことを書きますが、Issue 上の議論を読み直してもいまだに分からずじまいなため）
