### ISSUE TITLE
ormconfig.json自動生成

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#4925]
例えば npm run migrate のようなコマンドを実行すると設定ファイルの内容からormconfig.jsonを自動生成してマイグレコマンドを実行してくれるようにする

**Comment by u1-liquid** [comment]
default.yml との統合のほうが使い勝手的に良さそう

**Comment by syuilo** [comment]
TypeORM は default.yml を認識できない

**Comment by rinsuki** [comment]
ormconfig.jsでいいのでは

**Comment by u1-liquid** [comment]
db関連設定を最初から全部ormconfig.js またはormconfig.yml とかに集めても良さそう

でもこれやったら絶対mysql使いたがる人現るに違いない・・・
