### ISSUE TITLE
v11.14.0 ObjectStorage region error

### ISSUE THREAD

**Issue by sftblw** [misskey-dev/misskey#4930]
## 💡 Summary

Can't upload even after setting required fields to use ObjectStorage on admin panel

## 🙂 Expected Behavior

works

## ☹️ Actual Behavior

error happens. no upload

![2019-05-16 08_56_44-미스키 나루 카페 - Firefox Nightly](https://user-images.githubusercontent.com/5573010/57817109-e3bccd80-77b8-11e9-9a5a-eedc6d1ab667.png)

## 📝 Steps to Reproduce

1. 11.13.0 -> 11.14.0
2. set up Object Storage configs on admin panel, almost copying each fields from config. (I added port 443)
3. try to upload on drive

## 📌 Environment

Amazon S3
region: ap-northeast-2

**Comment by syuilo** [comment]
Thank you for reporting!
