### ISSUE TITLE
How to contribute with a danish language file?

### ISSUE THREAD

**Issue by JLKM** [misskey-dev/misskey#4935]
I would very much like to create and add a danish language file to this awesome project. I have followed the recommendation, logged in at crowdin.com and connected to the Syuilo language files (which don't encompass danish at the moment).

Here I'm stuck. How do I get started with my contribution?

**Comment by syuilo** [comment]
I added danish to crowdin now.
Thank you!

**Comment by JLKM** [comment]
Have just finished the danish translation on crowdin. Only 94 pct. complete, but nothing left to translate.

Please import the translation to the project - or tell me, how to do it myself.

**Comment by JLKM** [comment]
Thank you for the transfer to the project. Gone testing...;-)
