### ISSUE TITLE
お気に入りのMisskey Pagesのページを登録する機能

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#4936]
## Summary

現在ではPagesはURLが投稿されたり、自分のPagesのリストを確認することでしかアクセスすることができない。そこで、Pagesのページをお気に入りとして登録する機能を搭載するのはどうでしょうか？

#### お気に入り
現在投稿のみのお気に入りを確認すると、投稿のお気に入りとPagesのお気に入りを現在のTLのホーム/ローカル/ソーシャルのような感じで投稿/ページとタブで切り替えができるようにする。

#### 登録方法
Pagesのページの右上か最下部にお気に入りに登録するためのボタンを設置する

**Comment by syuilo** [comment]
ありがとうございます。
次のバージョンでは既に実装されています！
