### ISSUE TITLE
みつけるのもっと読み込むボタンがおかしい

### ISSUE THREAD

**Issue by Simirall** [misskey-dev/misskey#4959]
# 💡 Summary

1ページ目の繰り返しになってる

~~無限ループって怖くね？~~

**Comment by u1-liquid** [comment]
まだpagnation方式の統一ができていない模様

いくつかのAPIがlimit-untilIdではなくoffset-limit方式で`もっと読み込む`の処理をしている
みつけるのページのClient側のソースコードは11.18.1の時点でほぼ全部limit-untilId方式にqueryするようになっただめ動いてないみたい

https://github.com/syuilo/misskey/blob/9cfb72810c0919e4aa739ebe4110f0ffa7ff4ed0/src/server/api/endpoints/users.ts#L94
@syuilo これらのすべてlimit-untilIdのpagnation方式にします？
このバグみつけるページ以外にも何ヶ所ありそう

**Comment by syuilo** [comment]
> このバグみつけるページ以外にも何ヶ所ありそう

検索APIとかそうですね

**Comment by syuilo** [comment]
> これらのすべてlimit-untilIdのpagnation方式に

できればそうしたいですね

**Comment by syuilo** [comment]
でも例えば「最近投稿したユーザー」はどうページングしたらいいのか不明

**Comment by syuilo** [comment]
最近投稿したユーザーなんて刻々と変化するしページング自体不可能な気がしてきた

**Comment by tamaina** [comment]
GitHubのインデックスのバグによりreclose

**Comment by tamaina** [comment]
GitHubのインデックスのバグによりreclose
