### ISSUE TITLE
グループの招待コード

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#4960]
## Summary
グループへの招待をオープンにできるように、招待コードを発行し、グループ画面の招待コード入力欄にそのコードを入力すると入会できるような機能があるとうれしい

一回きりで失効するか恒久的に使用できるかを選べるようにできると便利そう  
また、招待コードを管理できるようになるといいと思う

**Comment by KisaragiEffective** [comment]
概念が消滅
