### ISSUE TITLE
トークンを再生成する機能

### ISSUE THREAD

**Issue by otofune** [misskey-dev/misskey#497]
設定画面にあるので実装されているのかと思っていた

**Comment by otofune** [comment]
native token を再生成する機能はトークンからのアクセスだけに限定したいが、実装をどうするかという問題が有る、現状認証系はどちらにせよ一緒くただったような気がするが

**Comment by syuilo** [comment]
パスワード必須にすればよい

**Comment by otofune** [comment]
パスワード必須にする、ただしそう
