### ISSUE TITLE
トーク履歴がないと履歴が読み込み中のままになる

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4972]
## 💡 Summary
トーク履歴がないと履歴が読み込み中のままになる
`Property or method "groupMessages" is not defined`

![image](https://user-images.githubusercontent.com/30769358/58299358-ef903b80-7e19-11e9-8f3d-322c5379abdf.png)

## 🙂 Expected Behavior
履歴はありませんと表示される

## ☹️ Actual Behavior
読み込み中のままになる

## 📝 Steps to Reproduce
1. 新規ユーザーでトークを開く

## 📌 Environment
v11

**Comment by williamd1k0** [comment]
I'm still having this issue on [misskey.dev (v11.20.0)](https://misskey.dev) :/

![image](https://user-images.githubusercontent.com/10428035/58908634-77fac000-86e7-11e9-9e7b-a3ab7f8df175.png)
