### ISSUE TITLE
npm run initを実行すると停止しない

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#4985]
## 💡 Summary
セットアップにおいて `npm run init` を実行すると、`Done :)` と表示されたあと、プロセスが残り続ける。

## 🙂 Expected Behavior
プロセスが終了する。

## ☹️ Actual Behavior
プロセスが終了しない。

## 📝 Steps to Reproduce

1. [setup.ja.md](https://github.com/syuilo/misskey/blob/c46bfcc76849ff08576034e6ed78a0cf0efce8c9/docs/setup.ja.md) に従う

## 📌 Environment
Linux 5.0.1

**Comment by syuilo** [comment]
WindowsだとDoneの数秒後にプロセスが終了しますね

**Comment by AyaMorisawa** [comment]
Done表示後にprocess.exit(0)すれば終了させることはできそうだけど、その終了の仕方でよいのかは分からず

**Comment by AyaMorisawa** [comment]
３分待っても終了しなかったので、終了しなさそう

**Comment by syuilo** [comment]
process.exit で問題ありませんでした
