### ISSUE TITLE
リアクションにhoverしたときツールチップで種類を表示する

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#4988]
こんな感じで

![Screenshot_2019-05-26_15-23-57](https://user-images.githubusercontent.com/10798641/58378183-9e737980-7fca-11e9-8491-015f4f618316.png)

**Comment by syuilo** [comment]
hoverしたときそのリアクションを行ったユーザー一覧をツールチップで表示する提案 (#1725) と競合しそう

**Comment by u1-liquid** [comment]
GitHubみたいに両方表示してくれるのはどうでしょう
![image](https://user-images.githubusercontent.com/17376330/58387198-1468f680-8046-11e9-852b-8d230ffddc97.png)
ちなみにGitHubは１０名まではidで、以後は数だけになる模様
![image](https://user-images.githubusercontent.com/17376330/58387244-c274a080-8046-11e9-90d6-c7b689ffdb1e.png)

**Comment by tamaina** [comment]
これどうするんだろう

**Comment by syuilo** [comment]
実装済みだと思われる

**Comment by tamaina** [comment]
Firefoxだとリアクションしたユーザーしか表示されないが、そもそもそれと被っているし、リアクションはすべて絵文字になったので表示するべき文字がない。

**Comment by u1-liquid** [comment]
結局これ（リアクションの種類を表示）は不採用ということでおk？
