### ISSUE TITLE
fork先リポジトリのTravis CIでリリース処理が行われる

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#499]
fork先のリポジトリのTravis CIからsyuilo/misskeyにpushすることはできないのでエラー終了する。

解決策→リポジトリ名がsyuiloであるかどうかチェックし、一致しなければリリース処理を行わない

**Comment by AyaMorisawa** [comment]
Pull Requestを受ける側としてはむしろfork先でCIを有効にして欲しいです＞＜

**Comment by otofune** [comment]
俺はやってるけどいちいち設定するの面倒なのでPR出した時にそれで本体側のCIが回ればそれでいいかなぁって思うんだよね
