### ISSUE TITLE
ピン留めされた投稿を削除したらピン留めも解除するように

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#5005]

**Comment by syuilo** [comment]
解除されませんか？

**Comment by AyaMorisawa** [comment]
![Screenshot_2019-05-27_23-24-36](https://user-images.githubusercontent.com/10798641/58426127-9dc80980-80d6-11e9-91a8-a62fd9151450.png)

F5で更新しても画像の状態

**Comment by syuilo** [comment]
バージョンは 11.20.0 ですか？

**Comment by AyaMorisawa** [comment]
![Screenshot_2019-05-27_23-26-21](https://user-images.githubusercontent.com/10798641/58426220-d962d380-80d6-11e9-873e-39cb2de2c6ee.png)

**Comment by syuilo** [comment]
バージョン 11.x 以降は修正されていますね

**Comment by AyaMorisawa** [comment]
このIssueどうしますか？

* v10をサポートしないなら単に閉じる
* 別でv10のみを対象としたバグ報告を作る

**Comment by syuilo** [comment]
私はv10サポートには積極的ではないですが、PRが来る可能性もあるので必要であれば 別でv10のみを対象としたバグ報告を作る で良いと思います。
このIssueは閉じます
