### ISSUE TITLE
ジョブキューのジョブ並列実行の最大数を設定できるように

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#5008]

**Comment by syuilo** [comment]
設定できたとしてもプロセス再起動などするまで反映されないので微妙そう

**Comment by SanMurakami** [comment]
そのプロセスの再起動とはMisskey本体のプロセスの話ですか？

もしクラスタ単位での再起動で反映できるなら、1プロセスずつ殺して再起動するスクリプトでなんとか出来るのでは
