### ISSUE TITLE
（デッキにおいて）ハイライトの日付が前後する（のが気になる）

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#5015]
## 💡 Summary
ハイライト（featured）について、サーバーはノートの投稿日時順ではなくスコア順で返すようだ。  
それによって、ホームではdetail-notesで表示しているため日付表示はないが、デッキでは通常のnotesで表示しているため、画像のように頻繁に日付表示が前後する場合がある。

## 🙂 Expected Behavior
日付の表示をしない、あるいはノートの投稿日時順に並べ替えてほしい

## ☹️ Actual Behavior

![image](https://user-images.githubusercontent.com/7973572/58745382-41c10480-848b-11e9-90ab-ea3f42da9479.png)

## 📝 Steps to Reproduce

1. デッキモードで`/featured`にアクセス

## 📌 Environment
Misskey ver 11.20.0 (daybreak) / Firefox 68.0b5 (64 ビット)

**Comment by syuilo** [comment]
v12でノートの投稿日時順に並べ替えて返すようにしました

**Comment by tamaina** [comment]
GitHubのバグでissue検索でopen扱いになってしまっているためrecloseします
