### ISSUE TITLE
絵文字の数が多いときのパフォーマンス改善

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#5022]
## Summary

絵文字が数百個存在するようなインスタンスにおいて、絵文字のサジェストおよび、管理画面の絵文字一覧の表示に凄く時間がかかってしまいます。

おそらく全絵文字のレンダリングを行っているので当然の挙動なのですが、100件ずつ表示するなどの処置が欲しいです。

**Comment by u1-liquid** [comment]
cache使ったら改善できそうですね

**Comment by mei23** [comment]
### サジェスト
`:`でローカルカスタム絵文字を全件→これは多分大量にあると重い
ただ、`:なんたら`みたいに1文字以上でサジェストしようとすると、Unicode絵文字のサジェストとぶつかるのでちょっとめんどくさそう
また、ローカルに数百数千単位で絵文字を追加するユースケースは特殊と思われるので、それにあわせて改善するべきかはわからない

### 管理画面の絵文字一覧
1000ぐらいは余裕と思う, 逆にフィルタがないのに100件ずつ表示するようにすると使いづらくなりそう

DBクエリは重くないので (数千行程度の小さなテーブルのクエリ) DB cacheは効かないと思う

**Comment by EbiseLutica** [comment]
> また、ローカルに数百数千単位で絵文字を追加するユースケースは特殊と思われるので、それにあわせて改善するべきかはわからない

そうですね...

> 1000ぐらいは余裕と思う

800文字ですが、おそらくvueサイドのレンダリングが遅延していて、表示に10秒ちかく要します（環境依存ではありそう）

**Comment by syuilo** [comment]
直ってそう
直ってなかったらreopenお願いします
