### ISSUE TITLE
Issue with file permission on digital ocean spaces

### ISSUE THREAD

**Issue by vitunvuohi** [misskey-dev/misskey#5023]
## 💡 Summary

I am using Digital Ocean Spaces, and there is no way to set default file permissions in DO's Spaces. By default, all files appear to be uploaded as private, so I cannot view files uploaded to S3.

I see an example for minio go (I believe misskey is using minio?) here: https://www.digitalocean.com/community/questions/how-to-set-permission-of-all-files-in-a-bucket-as-public-on-every-upload and the troubleshooting guide here leads me to believe I need to make the files public https://qiita.com/tamaina/items/3395cfac4fe03d89e8f8#s3-example-with-cdn-custom-domain (used google translate).

I will switch s3 providers if I need to but it would be great if i could use DO! 

## 🙂 Expected Behavior

Files should be viewable, no 403 error.

## ☹️ Actual Behavior

files are uploaded with private permissions, 403 error occurs when trying to retrieve.

## 📝 Steps to Reproduce

1. set up new misskey install
2. create DO spaces with custom subdomain (media.domain.com) and bucket (domain)
3. add to S3 section in admin
4. upload file
5. try to retrieve file
6. check permissions in bucket (it is private)

## 📌 Environment

ubuntu 19.04 / misskey 11.20.0 / node 12.3.1 / digital ocean spaces / production

**Comment by Johann150** [comment]
Closing because this issue report is for an older major version. From the linked issue this also seems to be resolved.
