### ISSUE TITLE
MinioのputObjectのリクエストヘッダに`'x-amz-acl': 'public-read'`を追加する

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#5024]
#5023 の解決法として有効~~そう（検証していないのでごめんなさい）~~

https://github.com/syuilo/misskey/blob/72fb23f4d51db1b999a10b7d8bb50293a81af163/src/services/drive/add-file.ts#L209 に手を入れれば大丈夫だと思う

https://www.digitalocean.com/community/questions/how-to-set-permission-of-all-files-in-a-bucket-as-public-on-every-upload  
https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/dev/acl-overview.html

**Comment by vitunvuohi** [comment]
with your post, I see in the code where to add it. I tried this and can say that it will work as a fix for #5023 . ありがとうございました！！

**Comment by mei23** [comment]
ioソース変えずにDigital Ocean Spaces使えてそう？

**Comment by syuilo** [comment]
ぽい

**Comment by mei23** [comment]
S3互換である以上、バケット単位で読み取り許可を設定する手段は提供されているはずなので
通常？バケットポリシーで読み取り許可を設定するのではと思われます。
