### ISSUE TITLE
English translation partially not working

### ISSUE THREAD

**Issue by matrix07012** [misskey-dev/misskey#5027]
## 💡 Summary

Certain text shows up in Japanese instead of English when the language is set to English. Most of these were translated in previous Misskey version I used.

## 🙂 Expected Behavior
![Opera Snapshot_2019-06-03_230525_waifuappreciation club](https://user-images.githubusercontent.com/8049717/58834744-63211c80-8654-11e9-86f2-a1d63460ad27.png)
![Opera Snapshot_2019-06-03_230549_waifuappreciation club](https://user-images.githubusercontent.com/8049717/58834751-661c0d00-8654-11e9-89e5-b7d06242fa0c.png)
![Screenshot 2019-06-03 23 06 06](https://user-images.githubusercontent.com/8049717/58834773-7633ec80-8654-11e9-9e43-cd57acada58b.png)

## ☹️ Actual Behavior

![Opera Snapshot_2019-06-03_225016_catgirl life](https://user-images.githubusercontent.com/8049717/58834248-23a60080-8653-11e9-9607-84e783e0dc12.png)
![Opera Snapshot_2019-06-03_225347_catgirl life](https://user-images.githubusercontent.com/8049717/58834407-9f07b200-8653-11e9-90e8-72159bd52df4.png)
![Opera Snapshot_2019-06-03_225402_catgirl life](https://user-images.githubusercontent.com/8049717/58834497-d8d8b880-8653-11e9-82df-0b3e09850082.png)
![Opera Snapshot_2019-06-03_225455_catgirl life](https://user-images.githubusercontent.com/8049717/58834509-e0985d00-8653-11e9-895e-44478a233661.png)
![Screenshot 2019-06-03 22 55 21](https://user-images.githubusercontent.com/8049717/58834515-e4c47a80-8653-11e9-8fba-ba98a91c1d5f.png)

## 📌 Environment
Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-50-generic x86_64)
NodeJS v12.3.1
PostgreSQL 10
Misskey 11.20.0

**Comment by acid-chicken** [comment]
The locale files were remapped at https://github.com/syuilo/misskey/commit/9403ee649569d923df03ca1870982d325d5432a1#diff-ebc81ffd271b64fd03110d4cd0d46afe, but Crowdin updates weren't merged yet. So it'll be fixed when #4979 is merged.
