### ISSUE TITLE
/api/notes/create 公開範囲private を渡すとタイムアウトする

### ISSUE THREAD

**Issue by tateisu** [misskey-dev/misskey#5028]
/api/notes/create に {"i":"**","text":"ダイレクト","visibility":"private","viaMobile":true} を送ると
タイムアウトする。
private はv10のどこかで廃止されてるはずだが、
https://github.com/syuilo/misskey/blob/develop/src/server/api/endpoints/notes/create.ts#L43 で"private" を受け取るように書かれているためエラー応答にならない。

期待される動作：
公開範囲がprivateの投稿が作成されるか、もしくはエラー応答を即座に返す。

## 📌 Environment

Maintainer: Syuilo, AureoleArk
Machine: arkjp-vm7-nvme1-lf84bxin-5b54d5b5cc-4jv5l
Node: v12.1.0
Version: 11.20.0

**Comment by acid-chicken** [comment]
@tateisu ありがとうございます。v10 までは互換性維持のためフォールバックしていましたが、v11 からフォールバック処理が削除され完全廃止となっていたところが、仰る通り API 上では受け取るように書かれたままになっていたようです。
