### ISSUE TITLE
バッジ機能

### ISSUE THREAD

**Issue by argxentakato** [misskey-dev/misskey#5034]
公式アカウント機能が削除されてしまったので、そういったアカウントを区別したりするためにアカウントにバッジを付ける機能を提案します。

一部のmisskeyインスタンスでは、誰がモデレーターかわからないためモデレーターを区別するために公式アカウント機能が使われていましたが、その機能が削除されてしまいました。ピン留めアカウントを使えばいいという意見もありますが、TL上で一目で分かるのは便利でしょう。

また、管理者によって面白いバッジや便利なバッジを追加することもできるでしょう。例えば…「開発者」とか「ミュージシャン」のような

**Comment by EbiseLutica** [comment]
多分 https://github.com/syuilo/misskey/issues/4107 と重複している

**Comment by tamaina** [comment]
#1895 や #1630 と重複している

**Comment by argxentakato** [comment]
めちゃくちゃ重複しててちょっと草。これはwontfixになるんですかね?

**Comment by acid-chicken** [comment]
Duplicate of #1630
I'll reopen it.

**Comment by acid-chicken** [comment]
Duplicate of #1630

**Comment by acid-chicken** [comment]
I'll reopen it.
