### ISSUE TITLE
「投稿内の動きのあるテキストを無効にする」だけ反応しない

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#5035]
## 💡 Summary

設定 > デザイン > デザイン の  
「投稿内の動きのあるテキストを無効にする」だけ反応しない

![2019-06-06_11-32-36](https://user-images.githubusercontent.com/37681609/59002906-f625a680-884e-11e9-90ee-5881fc003d34.gif)

## 🙂 Expected Behavior

反応する

## ☹️ Actual Behavior

反応はしないが、リロードしたら反映されている

## 📝 Steps to Reproduce

1. 設定を開く
2. デザインのデザインを開く
3. 「投稿内の動きのあるテキストを無効にする」をクリックする

## 📌 Environment

Misskey.io v11.20.0
Chrome 74.0.3729.169 Windows x64 & Linux x64

**Comment by mei23** [comment]
`null`とか`undefined`な設定値はその動き (保存できるけどUIに反映されない) になってしまうみたいです

`disableAnimatedMfm`については以下のあたりに初期設定値が抜けています
https://github.com/syuilo/misskey/blob/1432a7193d338b7945f2a285614f5068397d3fe9/src/client/app/store.ts#L9

~~初期設定値があったとしても、ユーザーがアカウント作成移行に実装されたDB保存の設定値は`null`で返ってくる可能性があるので、以下のあたりで`null`だったら`true`か`false`を返すようにした方がいいかもしれません。~~
DBにあるのは変更した値のみだからこっちは不要ぽい
https://github.com/syuilo/misskey/blob/1432a7193d338b7945f2a285614f5068397d3fe9/src/client/app/common/views/components/settings/settings.vue#L485
