### ISSUE TITLE
オブジェクトストレージに接続できない

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#5049]
Redisの接続数上限を超えないための機能である、PSQLのキャッシュを無効化した際に
オブジェクトストレージに接続できない

**Comment by syuilo** [comment]
どのようなエラーが出ますか？

**Comment by ghost** [comment]
misskeyのコンソール上ではこう出てます

27秒前 [core] ReplyError: Ready check failed: NOAUTH Authentication required
16秒前 [drive.register] hash: e7fd9c696066568a2e234238b99d4d35, mime: image/jpeg, ext: jpg, size: 258139
16秒前 [drive.register] creating web image
15秒前 [drive.register] uploading original: v11/30e6d57e-f041-4985-a06b-f28c97da1692.JPG
15秒前 [drive.register] uploading webpublic: v11/366207ed-9d92-418d-b1dd-4cb85fac6ba8.jpg
15秒前 [drive.register] uploading thumbnail: v11/684fd7f1-d4ae-4b9f-8d38-5e9c7c1f26fb.jpg
15秒前 [api] Error: getaddrinfo ENOTFOUND storage.googleapis.com

**Comment by syuilo** [comment]
PSQLのキャッシュを無効化したこととは関係ない可能性が高そう
キャッシュを有効化すると、オブジェクトストレージに接続できますか？

**Comment by rinsuki** [comment]
`curl -v https://storage.googleapis.com` は成功しますか？

**Comment by ghost** [comment]
accesskeyにスペースが入ってたのが原因でした
申し訳ありません
