### ISSUE TITLE
アップロードできないファイルがある

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#5050]
## 💡 Summary

Premature end of JPEG file VipsJpeg: out of order read at line 0
というログが記録されている

## 🙂 Expected Behavior

アップロードできる

## ☹️ Actual Behavior

アップロードできない

## 📝 Steps to Reproduce

1. 次のファイルをアップロードしようとする
![CF7258DB-3C7F-425B-A874-7EFDAF5820CD](https://user-images.githubusercontent.com/4439005/59433525-a59ce300-8e24-11e9-8138-32a674ec18d5.jpeg)

**Comment by tamaina** [comment]
いまは TypeError: Cannot destructure property 'width' of 'undefined' as it is undefined. とか言われる

…この画像、Firefoxで読み込むと真っ白になるので破損してる感じがある

**Comment by KisaragiEffective** [comment]
triage: 2024.5.0-kinel.1でアップロードはできた → #14001 が発覚
