### ISSUE TITLE
閉鎖されているとマークしてもジョブが詰まる

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#5055]
## 💡 Summary

マーク後ジョブキュークリア済み

![image](https://user-images.githubusercontent.com/37681609/59511790-2675e080-8ef2-11e9-8d97-ad72eb2383ad.png)
![image](https://user-images.githubusercontent.com/37681609/59511802-31307580-8ef2-11e9-8d9d-c36346557ff8.png)

## 🙂 Expected Behavior

そもそもキューに入らない

## ☹️ Actual Behavior

ジョブが詰まる

## 📝 Steps to Reproduce

1. 閉鎖済みとマークするを有効にする
2. ジョブキューをクリアする
3. 待つ

## 📌 Environment

Misskey.io v11.20.4

**Comment by mei23** [comment]
仕様だと思ってた
ブロックじゃないと効かない

**Comment by SanMurakami** [comment]
@mei23 このマークはなんのためにあるんですか

**Comment by mei23** [comment]
> このマークはなんのためにあるんですか

んー

**Comment by mei23** [comment]
v11でブロックを別枠にしちゃったから変な感じ
