### ISSUE TITLE
ハイライトでもっと読み込むすると振り出しに戻る

### ISSUE THREAD

**Issue by nzws** [misskey-dev/misskey#5056]
## 💡 Summary

ハイライトでもっと読み込むすると振り出しに戻る (投稿の読み込み自体はされるけど同じ物が読み込まれて下に積まれる)

## 📌 Environment

- Chrome 74.0.3729.169 (Official Build) （64 ビット）
- Misskey ver 11.20.4 (daybreak)

**Comment by AyaMorisawa** [comment]
Related to https://github.com/syuilo/misskey/issues/4959

**Comment by nzws** [comment]
🤦‍♂️🙇

**Comment by rinsuki** [comment]
みつけるとハイライトは別物なので別issueにして良い気がするけどどうですか @AyaMorisawa @syuilo

**Comment by syuilo** [comment]
確かハイライトはページングできない仕様だったと思うのでもっと読み込むボタンが表示されることがバグかな
