### ISSUE TITLE
2ndドメインでサブドメインを利用する意義

### ISSUE THREAD

**Issue by otofune** [misskey-dev/misskey#506]
なにかあるなら教えて欲しいですが、どこかのドメインのサブドメインを登録するとサブドメインのサブドメイン、4th levelになるので意義がないならトップレベルにマージしたい

**Comment by otofune** [comment]
追記ですが、続投するにしてもfileじゃなくてfilesのほうがいい気がするというのがある

**Comment by syuilo** [comment]
セカンダリドメインが廃止されました
