### ISSUE TITLE
どこからもトークが来ていないのに、通知のバッジが付く

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#5064]
## 💡 Summary

どこからもトークが来ておらず、未参加のグループもない状態で謎の通知バッジが付く

定期的に設定画面からクリアしているが気付いたらまた付いている

## 🙂 Expected Behavior

何もおこらない

## ☹️ Actual Behavior

通知バッジが付く

## 📝 Steps to Reproduce

1. 待つ
2. 待つ
3. 待つ

## 📌 Environment

Misskey.io v11.21.0

**Comment by syuilo** [comment]
ミュートしているユーザーはいませんか？

**Comment by SanMurakami** [comment]
@syuilo 1人だけ居るけど、ローカルユーザーじゃないので違うと思います。

**Comment by EbiseLutica** [comment]
そもそもミュートしているユーザーに由来する通知がバッジとして表示されること自体issueになりかねませんね（当方、手元で再現していないのでチケットを切っていませんが）

**Comment by SanMurakami** [comment]
まだなおってないです

**Comment by syuilo** [comment]
これマジ謎

**Comment by syuilo** [comment]
たすけて

**Comment by syuilo** [comment]
グループが関係してそうではある

**Comment by syuilo** [comment]
いろいろ試したけど再現しない

**Comment by syuilo** [comment]
懸賞金出します
とりあえず￥1,000

**Comment by syuilo** [comment]
現状確実に分かっていること:

* 誰もミュートしていなくても発生する(過去に一度もしたことない場合でも)

**Comment by tamaina** [comment]
これまだ発生するのかな

**Comment by SanMurakami** [comment]
> これまだ発生するのかな

まだ起こってます

**Comment by syuilo** [comment]
私も発生している
とても謎

**Comment by syuilo** [comment]
「全てのチャットを既読にする」をやっても消えない🤬🤬🤬

**Comment by mfmfuyu** [comment]
> ## Summary
> まず #5064 の問題についてですが、チャット一覧画面で表示されるバッジは、最新のメッセージを読んでいない場合に表示されるので、最新のメッセージを読んでいても過去に読まれていないメッセージがある場合にはバッジが表示されないので、一覧画面上ではすべて読んだように見えても実際には全て読んでいないので、サイドバー側の通知バッジが表示され続ける現象が発生しているのではと思います。
> 
> [#5064 (comment)](https://github.com/syuilo/misskey/issues/5064#issuecomment-636229675)
> そして、上記のコメントのバグはおそらくですがグループチャットのメッセージは「すべてのチャットを既読にする」で既読にならないのが関係していそうなので修正を行ってみました。

PR: https://github.com/syuilo/misskey/pull/6476

このIssueと直接関係しているのかは分かりませんが、グループチャットが怪しいのではと調査して気が付きました。

これが原因であれば、WebUI側で一覧のバッジの表示方法を変更する必要がありそうですが、APIの変更などが必要そうで少し大変そうと考えています。

**Comment by syuilo** [comment]
調査ありがとうございます！

> WebUI側で一覧のバッジの表示方法を変更する必要がありそう

👍

**Comment by tamaina** [comment]
グループ廃止
