### ISSUE TITLE
The uploaded image is corrupted in the drive but can be downloaded without error.

### ISSUE THREAD

**Issue by fz0000** [misskey-dev/misskey#5066]
I uploaded an image a looooooong time ago (and i forgot when…)
And I happened to see some issues today:

1. The preview image is corrupted in the drive.
2. It can **not** be set as the avatar (the default avatar will be displayed).
3. It can be set as the banner.

But when I download it, the downloaded file is the same as the original file and not corrupted… (The MD5 are the same)

I uploaded the same file again today and the new file works well.
![image](https://user-images.githubusercontent.com/5061311/59586392-71bc0900-9115-11e9-9903-e234bb93cf61.png)
![image](https://user-images.githubusercontent.com/5061311/59586542-c65f8400-9115-11e9-9f94-790fcb0dee05.png)

Well, I hope it's not a defect of misskey. Maybe just some network error occurred when it was uploaded. 😅

**Comment by syuilo** [comment]
This is not a problem with Misskey, it seems to be a problem with misskey.io.
🙏
