### ISSUE TITLE
自分のインスタンスのルートURIへのリンクが無になる

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#5073]
## 💡 Summary
![image](https://user-images.githubusercontent.com/7973572/59811129-6fd78d00-9343-11e9-80e3-a23e8b432cb3.png)

https://misskey.io/notes/7u7j6auxx9

## 📌 Environment
Misskey ver 11.22.0 (daybreak)

**Comment by SanMurakami** [comment]
![image](https://user-images.githubusercontent.com/37681609/60726427-763a4b80-9f76-11e9-9e23-4b2278e73bd2.png)
