### ISSUE TITLE
Support "Create=>Image" activity

### ISSUE THREAD

**Issue by Xanthec** [misskey-dev/misskey#5078]
## Summary
Misskey should display the activity sent with ActivityPub when someone create an image.
See https://github.com/tootsuite/mastodon/issues/11137

**Comment by mei23** [comment]
Misskey already supports it.
Create => Image adds files to the remote user's drive.
(Misskey has a feature called drive, which manages user files independently of posts.)
However, Misskey will not publish images that are not attached to the post, so it won't be visible to others.

**Comment by Xanthec** [comment]
Then you can move this to a bug issue instead of a feature issue.
Because currently, Misskey doesn't display the publication associated with the creation of an image.

**Comment by ealgase** [comment]
I think the confusion is, some platforms, like Hubzilla, use Create --> Image for public sharing.  Maybe with Create --> Image is received in an inbox, it's added to a user's public Drive that anyone can view?  That way, users could publish images directly from their Drive without adding to a post.

**Comment by Xanthec** [comment]
Still broken in ver 10.102.145-m544 
See https://misskey.m544.net/notes/7170163db23827bd1f33cd30

**Comment by mei23** [comment]
It's not a Misskey issue, as Hubzilla has only provided a link on the AP.

```
{
  '@context': [
    'https://www.w3.org/ns/activitystreams',
    'https://w3id.org/security/v1',
    'https://dacha.xmpp.moe/apschema/v1.8'
  ],
  type: 'Note',
  id: 'https://dacha.xmpp.moe/item/574ba361-1eed-4790-b1be-ab451e14f5b5',
  published: '2020-02-05T16:45:07Z',
  attributedTo: 'https://dacha.xmpp.moe/channel/caranistar',
  'diaspora:guid': '574ba361-1eed-4790-b1be-ab451e14f5b5',
  inReplyTo: 'https://dacha.xmpp.moe/item/025d1bc7-e335-4f58-9632-302948552387',
  content: 'Mécanique : <a href="https://dacha.xmpp.moe/wiki/caranistar/Magic(20)the(20)Gathering/m(c3a9)canique(3a)R(c3a9)surgence(20)"  target="_blank"  rel="nofollow noopener" >Résurgence</a>',
  actor: 'https://dacha.xmpp.moe/channel/caranistar',
  signature: {
    '@context': [
      'https://www.w3.org/ns/activitystreams',
      'https://w3id.org/security/v1'
    ],
    type: 'RsaSignature2017',
    nonce: '5141fa25244f6c45fb7a031b2be9f87b09fcea16db7428a99a1b4de628477c3e',
    creator: 'https://dacha.xmpp.moe/channel/caranistar',
    created: '2020-02-06T05:40:55Z',
    signatureValue: 'l02bI0K7WTq8qhUQJz7SMUzBiEyf+je4G4cVFF+0QYT8ZqXWubIXbFV/ZrnzFgbIWed5fLD3TD+PWSIQ8Qor8Al1rJiRsGOuwkY5jfbuJ8JeFRK16U5xxnluvYc14kwisEt+jvdMVu7YOC50/K++tnp7CzodeRt30ObI/hhRP3bAzFThV2bH+kwj30HxOCuqg4qWp2jRRMu2CR4Igru2fWus2n/KxTTLe7Mo24G/6XpkmtzIMBLIH48HKDe9qgPz2NTxs5vkAKmKW5IF2Tq791hc8vWrVSjPayaQzWDNdk5cNQMe+gWcm7Xgah+Rj+hQs/XCwgscmbkAQVxkNzz+rqQ37KuCkMUcbwwh2494B7XW7o6KmyHQgxuYvuhopExOicELKAsQ/GrxrilioisAL+UkxkZTzs4Lv4vo9tj9k7kFxF5xdgvodOjQDBelBI2PTvZYv/BT2KHIMlVLNRjZSuJiPOguh9ehsL231i+Ciq1Bplrb6FVdxbvrSA0lcr0d0Z8Vl2uSrHoG/uGh+xGj2e2FK0fjj/8s2ZrOiVAGAdjREb5QGehQN6rQxw0fWmDrb9icYlrWGoT6+wdzEzN0sNcWLn0GAfgFWopQ8Yn7Ib6wHd2ZqMJEpZCC05YSlHeHyPJYssm1czx/bU3WxvCjk4lXoHyWIDeoKkTECpclUkc='
  }
}
```

![image](https://user-images.githubusercontent.com/30769358/73909158-3a41dd00-48ef-11ea-9c06-4a1b16db7eb0.png)

**Comment by Xanthec** [comment]
You didn't understand.
What you're showing is a comment to the initial post which is the image sharing.
Just display the post in the initial context, and you'll see that it prooves the bug.
The initial post isn't displayed in MissKey. Only the comment.
What we expect is : both are displayed.

Please reopen this issue.
Thanks

**Comment by mei23** [comment]
Seem to `InReplyTo` tareget's post cannot be obtained, so it is impossible.
```
$ curl -Ss -L -i -H 'Accept: application/activity+json' https://dacha.xmpp.moe/item/025d1bc7-e335-4f58-9632-302948552387
HTTP/1.1 418 I'm a teapot
Date: Thu, 06 Feb 2020 17:45:51 GMT
Server: Apache/2.4.29 (Ubuntu)
Set-Cookie: PHPSESSID=4orjaa049smldu0rbf05rvihv8; path=/; secure; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Length: 0
Content-Type: text/html; charset=UTF-8
```

**Comment by Xanthec** [comment]
It works with 10.102.159-m544.

Thanks.
