### ISSUE TITLE
Reaction Emoji Inputbox で Colon を打ちたくない

### ISSUE THREAD

**Issue by itiradi** [misskey-dev/misskey#5079]
## Summary
現状、多分仕様的にコロンから始まる以外の絵文字がないので、リアクションの入力欄についてはコロンを省略したい

## 案
入力の先頭にコロンがあるように振舞う
絵文字が単体で入力された場合は、それをリアクションとして扱う

## 問題点
1. 将来、コロン以外から始まる絵文字に対応した場合に辻褄が合わなくなる
(なさそう。ないのでは？)

2. カスタム絵文字の識別子ないしエイリアスに、絵文字（マルチバイト文字）が使えるようになった場合、単体の絵文字を入力したときに直感的でない挙動になる可能性がある
(EmojiCodeとかアメリカのキーボードに最適化されてそうだしなさそう)

## 補遺
コロンがない場合、`:)` などの絵文字の入力が直感的ではなくなる可能性があるので、インプットボックスの左側に薄めなどでコロンを表示するとよさそう

**Comment by syuilo** [comment]
やった
