### ISSUE TITLE
Server module

### ISSUE THREAD

**Issue by bytesnz** [misskey-dev/misskey#5087]
## Summary
It would be really cool if the federation server was broken out into its own repository, so that they could be used with other projects.

I was thinking of creating a blogging site and was thinking it would be really cool if everytime I publish a new blog, it posts it as an activity feed. If the federation server was in its own node module, you could use it from other projects. It could end up just being a http server that listens on localhost that you can then manage your activity through.

**Comment by SanMurakami** [comment]
Misskey is tightly linked with the client.
Therefore, it's very difficult to operate only on the server.
The Misskey API is also incompatible with other applications and changes are devastating.
If you want to build your own service, I think it's fast to study Node.js.

**Comment by mei23** [comment]
Something like Pleroma?
