### ISSUE TITLE
通知タブが更新されない

### ISSUE THREAD

**Issue by Tacumi** [misskey-dev/misskey#5091]
## 🙂 Expected Behavior

表示されて欲しい

## ☹️ Actual Behavior

通知ガジェット，通知ボタンから確認することが可能な通知リストがロードのまま表示されない
どうやら，noteクラスにdeletedAtが定義されてないことからの問題かと？

## 📝 Steps to Reproduce

1. ホームに切り替える
2. メニューの通知ボタンをクリックする

## 📌 Environment

Brave version 0.65.121
Windows 10, macOS mojaveにて確認

**Comment by tamaina** [comment]
最新バージョンの状況はどうでしょう？

**Comment by Tacumi** [comment]
修正されていました．
