### ISSUE TITLE
Have a replacement for elasticsearch.

### ISSUE THREAD

**Issue by chaoticryptidz** [misskey-dev/misskey#5096]
## Summary

Elasticsearch is really resource intensive and is kinda slow.
Having support for something like https://github.com/valeriansaliou/sonic which I use in my other projects and am really happy with it's performance.
It'd make it easier for people with more underpowered computers.

**Comment by ThatOneCalculator** [comment]
Related: #8277

**Comment by KisaragiEffective** [comment]
related: #9323 
fixed by: #10755
