### ISSUE TITLE
画像サムネイルのプレフィックスを復活

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#5116]
以前は、ファイルサーバー側でサムネイルのプレフィックスを判定し、一般的であるLossy圧縮に加え、ユーザーの環境で利用できる場合はWebP圧縮を提供していました。

また、動的にUA等を判定することにより、モバイルの際にはクオリティを下げたデータを配信する等のフレキシブルな圧縮機能の提供を行ってきたため、プレフィックスを復活して頂きたいです。

Misskey本体の圧縮機能も素晴らしいですが、圧縮後のファイルを直接サーバーに保存するため十分とは言えません。

**Comment by tamaina** [comment]
確かに、thumbnailやwebPublicをアップロード時に生成して保存する方式は、CloudFlareをはじめとしたプロキシサーバーでキャッシュしている場合ではオブジェクトストレージまたはデータベースの容量を非効率に使用していることになってしまっています。  
CloudFlareなどのプロキシサーバーを利用しているインスタンスは多いと思うので、thumbnailやwebPublicは`/proxy/`での要求毎の処理に移行するべきでしょう。（これまでなぜそうでなかったのかと言えば、`/proxy/`がmei23によって作られた新しい処理だからなのだと思います。）`/proxy/`での処理にすれば、プロキシがプレフィクスで判別して横取り処理も可能になるでしょう。さらに、add-file時の圧縮処理コードを削除できます。

そもそも`/proxy/`ってURLではなくてドライブのIDで指定したほうがいいんでは？とか思ったりも（ドライブのファイルとドライブのファイル限定にすれば、detectMineしなくて済む上に「インターネット上のどんなファイルでも」という事態にはならない）。

~~ここまで書いてwebPublic周りのユーザー判別の話があることに気づきましたが、このコメントでは考えないことにしました。~~ サムネイルだけでいいのか

**Comment by SanMurakami** [comment]
@tamaina 話の趣旨がズレているので見なかったことにします。

**Comment by syuilo** [comment]
サフィックスでもいいですか？

**Comment by syuilo** [comment]
とりあえずプリフィクスしました
