### ISSUE TITLE
登録したてのユーザーログが保存されない

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#5117]
スパムユーザーを対処し、同一IPでのアクセスを確認しようとしたところサインインのログがありませんでした。

この状態だと、スパムアカウントを作成して再ログインしなければログが残らなくなってしまうので、アカウント登録時にもサインインと同じログを保存してほしいです。

**Comment by syuilo** [comment]
今ってサインイン時に何かログ出てましたっけ

**Comment by SanMurakami** [comment]
@syuilo signinテーブルにログインリクエストのヘッダーとユーザーのIDが保存される

**Comment by syuilo** [comment]
あー

**Comment by SanMurakami** [comment]
@syuilo それをアカウント作成時にもやってほしい(IPだとCF経由で正常に出ない可能性もあるのでHeaderも保存してほしい)

**Comment by syuilo** [comment]
signinテーブルではなくて普通に(管理画面で見られる)ログとして出力するのでも良さそうですか？

**Comment by SanMurakami** [comment]
@syuilo 管理画面のログだと早すぎて追うの難しそうなので、できればsigninに出してほしい感じはある
あと、管理画面のログはおもすぎるので定期的に削除している(バックアップは取ってるけど)

**Comment by mei23** [comment]
x 登録したてのユーザーログが保存されない

signup した後には signin されるので登録直後でも保存されるはず
signin ログ自体が保存されなくなっている #5179
