### ISSUE TITLE
ページウィジェット

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#5139]
## Summary

任意のページを表示できるウィジェット

**Comment by futchitwo** [comment]
任意のページを埋め込みたい理由が「ユーザーの動的コンテンツをウィジェット化したい」ならAiScript App ウィジェットで解決できる
ただAppウィジェットは他人作成のPagesやPlayを参照する形じゃなくてコードをコピペして埋め込む形になるから、コンテンツに更新があっても自分でコピペし直す必要がある
