### ISSUE TITLE
Exported data is not put in user storage/Drive

### ISSUE THREAD

**Issue by Golutazem** [misskey-dev/misskey#5141]
Select Settings : Profile and then Export
Exporting the following were tested:
- List of followers (I believe it means users you are following.)
- List of blocked accounts
- Lists

The user receives the message:
> After the export is complete, the resulting file will be added to the drive.

I view the Drive. It remains empty. No files are seen.
version: 11.25.1

**Comment by Johann150** [comment]
Exporting works for me currently. Since this is an old issue for v11 I assume it was fixed in the meantime.
