### ISSUE TITLE
通知内で名前が突き抜ける

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#5150]
![image](https://user-images.githubusercontent.com/4439005/61174371-082aff80-a5da-11e9-822e-3337f11549ed.png)

**Comment by mei23** [comment]
デッキのユーザーカラムで x が押せない
![image](https://user-images.githubusercontent.com/30769358/61297630-95a76300-a817-11e9-9dc6-2bdf9e50cd03.png)
