### ISSUE TITLE
プロフィールの画像欄に閲覧注意の画像が表示される

### ISSUE THREAD

**Issue by kabo2468** [misskey-dev/misskey#5166]
## 💡 Summary

プロフィールの画像欄に閲覧注意と設定した画像がマスク無しで表示される

## 🙂 Expected Behavior

表示しないようにするか、マスクを掛ける

## ☹️ Actual Behavior

すべての画像が表示されてしまう

## 📝 Steps to Reproduce

1.プロフィールの画像欄を見る

## 📌 Environment

Misskey v11

**Comment by acid-chicken** [comment]
Related to https://github.com/syuilo/misskey/blob/952789cc1eb77e2f2d54b489c016b56bac812ab7/src/server/api/endpoints/notes/local-timeline.ts#L114-L121 https://github.com/syuilo/misskey/blob/952789cc1eb77e2f2d54b489c016b56bac812ab7/src/server/api/endpoints/users/notes.ts#L168-L173
（一部の ToDo をほったらかしたまま v11 をリリースしてしまっているため？）
