### ISSUE TITLE
MFMの引用が正しく表示されない

### ISSUE THREAD

**Issue by kabo2468** [misskey-dev/misskey#5167]
## 💡 Summary

MFMの引用が正しく表示されない
![chrome_2019-07-16_21-43-15](https://user-images.githubusercontent.com/28654659/61299295-c341db80-a81a-11e9-9810-b1f3491aaa7d.png)

内容
```
>テスト
>テスト
>テストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテスト
```

## 📌 Environment

MIsskey v11

**Comment by syuilo** [comment]
修正されました🙏
