### ISSUE TITLE
[mfm] githubとtwitterをホストに取るメンションに対する特殊処理が効いていない

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#5168]
## 💡 Summary

これが動作していない？

https://github.com/syuilo/misskey/blob/develop/src/mfm/toHtml.ts#L130-L135

## 🙂 Expected Behavior

+ `@xeltica@twitter.com` がツイッターに飛ぶ
+ `@syuilo@github.com` が設計図共有サイトに飛ぶ

## ☹️ Actual Behavior

両者ともそういうホストのリモートアカウントを参照しようとしてしまう

## 📝 Steps to Reproduce

1. `@Xeltica@twitter.com` と投稿する
2. 投稿のリンクを踏む
3. 😇 

## 📌 Environment

+ Misskey 11.25.1

**Comment by syuilo** [comment]
ん、なんかそれ書いた記憶ないですね…
前からこの機能実装したいとは思ってたので、途中のやつを間違えてPushしちゃったのかも？

**Comment by u1-liquid** [comment]
https://github.com/syuilo/misskey/pull/3603

**Comment by syuilo** [comment]
あーなるほど🙏🙏🙏

**Comment by EbiseLutica** [comment]
なるほど
