### ISSUE TITLE
プロフィール設定でバナーに動画を設定すると以降編集ができない

### ISSUE THREAD

**Issue by Oni-Men** [misskey-dev/misskey#5172]
## 💡 Summary
バナーに動画をアップロードし保存を押すとページをリロードするまで再度プロフィールの編集ができない。尚、メール設定は編集できた。

## 📝 Steps to Reproduce

使用した動画はmp4です。

1.設定->プロフィール
2.バナーに動画をアップロード
3.保存をクリック

## 📌 Environment

Google Chrome ver.75.0.3770.100

**Comment by AyaMorisawa** [comment]
confirmed on Misskey v11.25.1

**Comment by AyaMorisawa** [comment]
これは２つの問題が含まれていますね。

* バナーには画像のみ設定できる想定なのに、クライアントがユーザーにそれを伝えていない問題 (サーバーはちゃんとBANNER_NOT_AN_IMAGEエラーを返すようになっている)
* 保存に失敗したときに保存中状態(編集不可状態)が解除されない問題(オフラインなどの理由で保存に失敗しても保存中状態が解除されない)

**Comment by Oni-Men** [comment]
なるほど！では[ここ](https://github.com/syuilo/misskey/blob/develop/src/client/app/common/views/components/settings/profile.vue#L268)から下の行を
```javascript
}).catch(e => {
  this.saving = false;
  //他の処理
});
```
とすれば(保存に)失敗しても保存中状態は解除されるようになるでしょうか。
他にも画像のみを設定できる旨を伝えるメッセージを送りたいところですね。
