### ISSUE TITLE
モバイルのウィジェットページが常に i/update-client-setting を呼び続ける

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#5210]
## 💡 Summary

Mobile UI でウィジェットページを開くと、常に `i/update-client-setting` を呼び続ける

## 🙂 Expected Behavior

ウィジェットの状態が変更された場合のみAPIを呼ぶ

## ☹️ Actual Behavior

常に(tick毎？)呼んでいる

## 📝 Steps to Reproduce

1. 何らかの方法でMobile UIを開く
2. 各種ブラウザの開発者ツールのような、APIコールを監視できるツールを準備
3. ウィジェットページを開く
4. わー

## 📌 Environment

Misskey: 11.26.1
Browser: Chrome 75
OS: macOS 10.14.5

## 🙄Additional Information

モバイルUI版ウィジェットページにはウィジェットを削除できない不具合があって(別issueで切ります)検証していないのですが、特定のウィジェットに原因があるかもしれないのでそれも要調査かと思います。

**Comment by AyaMorisawa** [comment]
<details>
  <summary>キャプチャした大量のリクエストのうちの１つのペイロード</summary>

```json
{
  "name": "mobileHomeProfiles",
  "value": {
    "Default": [
      {
        "id": "e6021a4b-49b8-4cef-ae15-75f8b937d3d1",
        "data": {
          
        },
        "name": "profile"
      },
      {
        "id": "a",
        "data": {
          "design": 0
        },
        "name": "calendar"
      },
      {
        "id": "b",
        "data": {
          "compact": false
        },
        "name": "activity"
      },
      {
        "id": "c",
        "data": {
          "url": "http:\/\/feeds.afpbb.com\/rss\/afpbb\/afpbbnews",
          "compact": false
        },
        "name": "rss"
      },
      {
        "id": "d",
        "data": {
          "design": 0
        },
        "name": "photo-stream"
      },
      {
        "id": "f",
        "data": {
          
        },
        "name": "nav"
      },
      {
        "id": "g",
        "data": {
          
        },
        "name": "version"
      }
    ]
  },
  "i": "xxxxxxxxxxxxxxxx"
}
```
</details>

**Comment by AyaMorisawa** [comment]
ずっと `mobileHomeProfiles` を更新しようとしてる

**Comment by mei23** [comment]
このへんがループしている
https://github.com/syuilo/misskey/blob/636f90ca0c61fa4fa57d38934826f0c8386f36f6/src/client/app/mobile/views/pages/widgets.vue#L102-L103

**Comment by syuilo** [comment]
https://github.com/syuilo/misskey/blob/636f90ca0c61fa4fa57d38934826f0c8386f36f6/src/client/app/mobile/views/pages/widgets.vue#L102-L106
この行要らないかも
