### ISSUE TITLE
投稿の翻訳

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#5213]
gas の LanguageApp

**Comment by EbiseLutica** [comment]
すみません間違えて本流に投げてしまいました閉じます

**Comment by argxentakato** [comment]
これ割と欲しくない?????? 実装しませんか?

**Comment by argxentakato** [comment]
ワシはDeepLに対応してもらえると嬉しいです。

**Comment by rinsuki** [comment]
APIないか高いので無理だと思う

**Comment by rinsuki** [comment]
URLで指定できる系はaiscriptからURL 開けるようにして (確認付き？)ショートカット提供とかできるようにしたらいいかもしれないですね

**Comment by acid-chicken** [comment]
[DeepL API](https://www.deepl.com/pro#developer) Integration はまあまあありだが、実装するならインスタンス側で提供する方式と個人でトークンを渡す方式の両方を用意した方がいいかも

**Comment by syuilo** [comment]
月額 630¥ か

**Comment by acid-chicken** [comment]
> 月額 630¥ か

にプラスで字数当たりの従量課金（多分）

**Comment by argxentakato** [comment]
素晴しい事に、いつの間にかDeepL APIは月500,000文字までは無料で使えるようになったらしい。

**Comment by syuilo** [comment]
> DeepL APIは月500,000文字までは無料で使える

いつまでその状態が続くのかはアンコントローラブルな要素だけど、実装してみる価値はありそう

**Comment by syuilo** [comment]
投稿の言語同定する必要があるな

**Comment by tamaina** [comment]
これもほしい

> 投稿の言語同定する必要があるな

ユーザーの言語設定使えばいいのでは…？

> DeepL APIは月500,000文字まで

翻訳結果をDBに保存するようにすればいろいろ親切かも……

**Comment by syuilo** [comment]
> ユーザーの言語設定使えばいいのでは…？

ユーザーの言語設定実装したのはこのため

**Comment by syuilo** [comment]
というかDeepL言語同定してくれたりしそう

**Comment by syuilo** [comment]
> URLで指定できる系はaiscriptからURL 開けるようにして (確認付き？)ショートカット提供とかできるようにしたらいいかもしれないですね

ちなみにすでにこういうプラグインがある

**Comment by syuilo** [comment]
無料でもクレジットカード要るのか
