### ISSUE TITLE
Remote emojis don't update

### ISSUE THREAD

**Issue by matrix07012** [misskey-dev/misskey#5218]
## 💡 Summary

A Pleroma instance moved emojis from /emoji/ to /emoji/custom/ but Misskey didn't update the remote emoji URL and tries to retrieve it from the old location even though the remote post has the correct URL.

Example: https://catgirl.life/notes/7vmfhk7xd9

## 📌 Environment

Misskey 11.26.2
NodeJS 12.6.0
PostgreSQL 10

**Comment by mei23** [comment]
Looking at Updated
But
```
    {
      updated: '1970-01-01T00:00:00Z',
      type: 'Emoji',
      name: ':cirnoThink:',
      id: 'https://pl.smuglo.li/emoji/custom/cirnoThink.png',
      icon: {
        url: 'https://pl.smuglo.li/emoji/custom/cirnoThink.png',
        type: 'Image'
      }
    }
```

**Comment by mei23** [comment]
Mastodonとかでもupdated変えずにurlだけDBから変えちゃう人いるので
updated見てるだけだとこわれる
