### ISSUE TITLE
Deckでハッシュタグのカラムが追加できない

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#5222]
## 💡 Summary

Deckでハッシュタグのカラムが追加できない
![image](https://user-images.githubusercontent.com/37681609/61973865-150b1280-b020-11e9-9bb9-8c6fa225c53a.png)

## 🙂 Expected Behavior

追加できる

## ☹️ Actual Behavior

追加できない

## 📝 Steps to Reproduce

1. Deckを開く
2. カラムの追加からハッシュタグを追加
3. 追加したいハッシュタグを記入

## 📌 Environment

Misskey.io v11.26.2
Chrome Linux 75.0.3770.142 64bit

**Comment by syuilo** [comment]
2 と 3 の手順を逆にすると出来ました

**Comment by syuilo** [comment]
(設定に)存在しないタグのカラムを追加しようとするとメッセージを出すのが良さそうですね
