### ISSUE TITLE
フォローリクエストが承認されたときの通知

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#5223]

**Comment by SanMurakami** [comment]
これはフォローをした側に行く通知ですか？
それとも、フォローされた側に行く通知ですか？

フォローされた側に行く通知だとしたら、新規フォローの表示がでるのでいらない気もします。

**Comment by EbiseLutica** [comment]
タイトルからしてリクエストを送った人に行く通知だと考えるほうが自然かと（フォローされた側だとしたらボタンを押した瞬間に意味のない通知が飛んでくる謎機能でしかない）

**Comment by CookieRamen** [comment]
これはMisskey間だけの機能になるんですかね
Mastodonにそういった機能がないならテキスト投稿として送ることになるんですかね

**Comment by syuilo** [comment]
した側ですね

**Comment by SanMurakami** [comment]
なるほど
