### ISSUE TITLE
非ログイン時トップの文言の「詳しく…」は不適切?

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#5228]
## Summary

ja-JP ロケールの非ログイン時トップは

```
インスタンス名
ホスト名 - Powered by Misskey. (各統計数)

インスタンス側が決めた説明
詳しく… (ここを押すとmisskeyの説明が開く)
```

になっているが、インスタンスの説明の後に置く「詳しく…」でインスタンスの詳細説明ではなくMisskeyの詳細説明が開くのは適切ではない気がする。

Misskeyの詳細説明を開く今の挙動をそのままにする場合、「Misskeyについて」とかにしたほうがよさそう。もしくはインスタンス管理者がリンク先を(ソース変更なしで)変えられるようにするのもありかも。

**Comment by mei23** [comment]
とりあえず適切ではないと思う

> 「Misskeyについて」にする

フッターにも「Misskeyについて」があるので「Misskeyについて詳しく…」とか

実際は「インスタンス側が決めた説明」と「詳しく…」の間に改行がなくて
説明文にMisskeyの言及がない場合に 同じブロックに詳しくリンクがあると変なので
下のリンクは別ブロックがいいかなと

**Comment by syuilo** [comment]
デザイン変えました
