### ISSUE TITLE
画像ファイルのプレビュー位置を変更できるように

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#5233]
Mastodon にもある、画像ファイルのプレビュー表示時の中心位置を決める機能
<img alt="名称未設定" src="https://user-images.githubusercontent.com/7106976/62195906-f0b08c80-b3b7-11e9-8f7e-e6ad15e694bd.png">

**Comment by mei23** [comment]
そもそもサムネイルの表示方法が「全体が収まるように枠内に収める」だから中心位置関係なくないです？

**Comment by EbiseLutica** [comment]
たしかに
