### ISSUE TITLE
「編集して削除」機能

### ISSUE THREAD

**Issue by itiradi** [misskey-dev/misskey#5254]
## どのような？
自分の投稿に対して、その内容に変更を加え再投稿し、直後に元の投稿が削除されるような機能、または、それらを一括で行うようなAPI

## なぜ？
1. 「削除して編集」が次の理由で使いづらい。（削除して編集機能自体が良くないわけではない）
	- 削除後に操作を間違えると内容が飛ぶ
	- 個人的に、元の投稿が一度削除され、**少しの時間をおいてから**、タイムライントップに（編集された投稿が）再び現れることが、心情的また視覚的にやかましい

1. APIレベルで実装する際、editedイベントを用意する、または、noteイベントを拡張（サードパーティに優しい）することで、次のような事が可能になる（かもしれない）。
	- 編集された内容で元の投稿の内容を置き換える
	- 編集された投稿がトップに上昇するアニメーション（意味的な繋がり）

## 懸念
- 編集したい投稿がすぐに削除されない 　☞　 「削除して編集」は残す？
	- 両方あると分かりづらそう　☞　設定でオンオフ？
- （特にサーバサイドで実現する場合）トランザクション処理が必要？

**Comment by mei23** [comment]
「編集の投稿が正常終了するまで削除しない」だけならクライアントで処理順変えるだけでできる
Before: 削除→編集画面に内容を入力→投稿 
After: 編集画面に内容を入力→投稿→削除

「編集が完了するまで元の投稿は残ります」は納得できても
「編集を途中で破棄すると元投稿も含めて破棄されます」え？
最初から「編集」という名前で「クライアント側で編集して削除」にすればよかったのかも。

既存の投稿の表示を変更するのはかなりめんどそう。

**Comment by itiradi** [comment]
まあ滅茶苦茶に凄い機能になるという感じではないので個人的には、（クライアントのみをいじるような）なるだけコストをかけずにできる実装がいいのではないかなと思います

**Comment by EbiseLutica** [comment]
個人的には編集中に間違いツッコまれるの嫌なので、間違った投稿には消えてもらいたい（からそういう実装にしたというのも理由の一つ）

**Comment by u1-liquid** [comment]
投稿を削除するともらったリアクションもそうだがリプもCASCADEで消えてしまう為できる限り早く削除した方がいいと思ってます

**Comment by rinsuki** [comment]
というかそもそも人の投稿に連動されて自分の投稿が消えるリプライの挙動はおかしい気がする

**Comment by acid-chicken** [comment]
@rinsuki Related to https://github.com/syuilo/misskey/pull/4572#issuecomment-478474515 #4863

**Comment by Johann150** [comment]
It seems the conclusion is that this is not necessary because we already have "Delete and edit". And the rest of this issue would be a duplicate of #8362.

**Comment by ThatOneCalculator** [comment]
I have to admit, delete and edit is a tad annoying when you have 5 likes already and notice a typo 😕

**Comment by Johann150** [comment]
I don't see how changing the order from deleting and then editing to editing and then deleting changes that.

**Comment by ThatOneCalculator** [comment]
> I don't see how changing the order from deleting and then editing to editing and then deleting changes that.

Wouldn't just editing still keep the post intact, or no?

**Comment by Johann150** [comment]
Yes, but "just editing" is issue #8362, as I said above.
