### ISSUE TITLE
アバター等で背景が透過されない

### ISSUE THREAD

**Issue by Simirall** [misskey-dev/misskey#5258]
## 💡 Summary

Webクライアントで、背景を透明にしたPNG画像などをアイコンにしたとき、v10以前だと透過されていたがv11以降だと透過されていない

## 📝 Steps to Reproduce

* 透過画像をアバターにする

## 📌 Environment

Misskey v11

**Comment by u1-liquid** [comment]
placeholderの色が表示される模様

**Comment by syuilo** [comment]
良い解決策募集

思いついたもの:
アバターのレンダリングをCSSのbackground-imageではなくimgタグで描画するようにして、描画完了イベントに合わせてplaceholder色を解除するようにする
懸念: imgタグでCSSのcoverの挙動と同等のものを実現できるか
imgタグに対してCSSのobject-fitプロパティを設定すればいけそう...?

**Comment by mei23** [comment]
- もうアバターが表示されないパターンはないはずなので、アバターには背景色を使わない
- v10のように透過画像なら背景色も表示しない (アバターにも添付にも適用になる)

とか

**Comment by syuilo** [comment]
> アバターには背景色を使わない

もちょっと考えたんですが、回線が遅いと読み込みまでに空白が表示されちゃうのでやっぱり背景色はあった方が良さそう

**Comment by syuilo** [comment]
v10方式は透過かどうかの検出・提供だったり透過だった場合の分岐を実装しないといけなくて複雑さが増すので廃止したんですよね

**Comment by mei23** [comment]
透過分岐がないと、ほぼ同色の透過画像が背景色で埋もれちゃうんですね
![image](https://user-images.githubusercontent.com/30769358/62819027-7f789280-bb8a-11e9-9acb-8d712b0a5d72.png)

![image](https://user-images.githubusercontent.com/30769358/62819020-62dc5a80-bb8a-11e9-9af1-eba24a675c1c.png)

**Comment by u1-liquid** [comment]
https://github.com/hilongjw/vue-lazyload とか使う？

**Comment by syuilo** [comment]
とりあえずimgタグで代用できるかやってみます

**Comment by futchitwo** [comment]
v12では解決済み？

**Comment by Johann150** [comment]
It seems it is resolved, see e.g. https://ente.fun/@ceilingfox
