### ISSUE TITLE
トレンドウィジェットが正常に動作しない

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#5271]
トレンドウィジェットを開くと、存在しない `notes/trend` API を見に行くので内部エラーにより表示されない模様

![image](https://user-images.githubusercontent.com/7106976/63134684-82013f00-c005-11e9-879b-d363e410b17c.png)

Misskey 11.27.1

**Comment by mei23** [comment]
#3460

**Comment by EbiseLutica** [comment]
100万回ぐらい類似issue検索してもみつからなかったのになぜ........

**Comment by mei23** [comment]
「トレンド」だとかからない…
