### ISSUE TITLE
連合ユーザーにグループの招待を飛ばせるが、何も起きない

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#5282]
## 💡 Summary

連合ユーザーにグループの招待を飛ばせるが、何も起きない

## 🙂 Expected Behavior

連合ユーザーにはグループの招待を飛ばせない、もしくはグループを連合に対応して連合相手のユーザーを本当に招待できる

## ☹️ Actual Behavior

連合ユーザーにグループの招待を飛ばせるが、何も起きない

**Comment by acid-chicken** [comment]
ちなみにリバーシも。

**Comment by tamaina** [comment]
グループ廃止
