### ISSUE TITLE
オブジェクトストレージを使用している場合Roomで画像を読み込めない(CORS)

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#5291]
## 📝 Steps to Reproduce

1.
2.
3.

**Comment by syuilo** [comment]
まだ直ってない(オブジェクトストレージ側の問題？)

**Comment by syuilo** [comment]
これ関係あるかな
https://stackoverflow.com/questions/43000648/html-img-src-works-but-js-image-loading-cause-cors-error

**Comment by syuilo** [comment]
普通にimgタグで表示するときは読み込めるのにcanvasに読み込もうとしたときだけエラーが出るの謎

**Comment by mei23** [comment]
まだこれがでる
`クロスオリジン要求をブロックしました: 同一生成元ポリシーにより、https://.../image.png.thumbnail.jpg にあるリモートリソースの読み込みは拒否されます (理由: CORS 要求が成功しなかった)。`
