### ISSUE TITLE
pinguin -> penguin

### ISSUE THREAD

**Issue by fz0000** [misskey-dev/misskey#5293]
"pinguin" is a German word (or maybe just a typo? 😄 ), in English it is "penguin".

location:
`misskey\src\client\app\common\scripts\room\furnitures.json5`, ln. 281
and the `pinguin` folder under `misskey\src\client\assets\room\furnitures`

**Comment by syuilo** [comment]
Probably Typo, but I'm going to use pinguin.

**Comment by acid-chicken** [comment]
Off Topic: A famous anime in Japan, called *Pingu* might be flashed into his head? 😆

**Comment by AyaMorisawa** [comment]
Possibly related to https://crowdin.com/translate/misskey/3/ja-zhcn#5352:drl:72:fangzheng
