### ISSUE TITLE
ピンギン -> ペンギン

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#5295]
## 💡 Summary
Related to #5293
Related to https://crowdin.com/translate/misskey/3/ja-zhcn#5352:drl:72:fangzheng

https://github.com/syuilo/misskey/blob/9bc4af76b88c6c5f595840ef3b056feff58d3b64/locales/ja-JP.yml#L2343

idにpinguinを使うのはいいと思うけど、利用者が見る画面で「ピンギン」は違和感がとてもあるので「ペンギン」にしたい

@syuilo

**Comment by noizenecio** [comment]
とりあえず使いたくなるインパクトのある見た目に特徴的な名前があるのは良いことだと思います

**Comment by syuilo** [comment]
そういう名前のキャラクターということにします
