### ISSUE TITLE
通知に非公開のリプライが来る

### ISSUE THREAD

**Issue by kabo2468** [misskey-dev/misskey#5296]
## 💡 Summary

通知に非公開のリプライが来る
内容は見れないが、投稿しているのがわかるので非公開の意味が薄れる
![2019-08-18_19-47-07_chrome](https://user-images.githubusercontent.com/28654659/63223471-fea44100-c1f0-11e9-8910-8daba0e20e7f.png)

## 🙂 Expected Behavior

表示されない

## ☹️ Actual Behavior

表示される

## 📝 Steps to Reproduce

0.投稿の自動ウォッチをオンにする
1.誰かが公開で投稿する
2.その投稿に自分がリアクションする
3.誰かがその投稿に非公開でリプライする
4.通知が来る

## 📌 Environment

Misskey v11

**Comment by KisaragiEffective** [comment]
公開範囲の意味が薄れるのでバグ扱い

**Comment by KisaragiEffective** [comment]
> 公開範囲の意味が薄れるのでバグ扱い

@syuilo これで問題ないでしょうか…？

**Comment by Sayamame-beans** [comment]
Related(or partially duplicate of): #13936 , #10496

**Comment by syuilo** [comment]
👍

**Comment by Sayamame-beans** [comment]
re-triage: 類似のバグ挙動は残っているが、本内容の`投稿の自動ウォッチ`は既に存在しない
他のissueがあるのでclose
