### ISSUE TITLE
カメラの座標移動

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#5310]
## Summary

- WASD移動
  - DキーがDark/Whiteモードの切り替えと被ってる
- ホイールボタンでドラッグ
  - トラックパッド勢どうすんの
- 何かしらのキーを押しながらドラッグ
- etc...

**Comment by EbiseLutica** [comment]
^や⌘とドラッグで回転できるのを見るとSHIFT+ドラッグとかが良さそう

**Comment by marihachi** [comment]
この中だとホイールボタンでドラッグがすき

**Comment by marihachi** [comment]
キーコンフィグがあればなんとでもなりそう
