### ISSUE TITLE
複数Roomを作れるように

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#5311]

**Comment by u1-liquid** [comment]
FYI: https://misskey.io/notes/7wca18lz7w
> Q. Room、1ユーザーに1個にゃの？
A. その予定

**Comment by EbiseLutica** [comment]
部屋目的で複垢作ろうとする輩が現れそうだなあとも思うのでroomを増やせるようにする案に賛成

**Comment by u1-liquid** [comment]
デレステのように「階」っていって2個くらい作れるようにするとか、レイアウトの保存・呼び出し機能あったら楽しそうですね

**Comment by marihachi** [comment]
レイアウトの保存・呼び出しに関して賛成です

**Comment by EbiseLutica** [comment]
ルームの保存・呼び出しはこちらがrelatedかな...? #5301
