### ISSUE TITLE
Room内でリバーシ

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#5314]

**Comment by acid-chicken** [comment]
Related to #1777

**Comment by tokaritami** [comment]
v11上でのリバーシの挙動を見た所マス目の数が可変なルールだったので、3D化の方法をどうやるのかなと考えています。(もちろんそれに必要な3Dアセットをどう作るかも

3Dモデル的には8x8の固定の盤を作って、白と黒の石だけ。というのが一番いいんですが、Room内でマス目可変させる場合は盤のパーツをバラバラにglbにしてコード側で並べる。等の方法もあります。
~~力技で全パターンの盤を用意するというのも出来ます~~

方針としてはv11のリバーシ完全再現を目指す感じですか？
