### ISSUE TITLE
MisskeyRoomからページを戻した時、テキスト入力画面で選択位置変更ができない

### ISSUE THREAD

**Issue by YuzuRyo61** [misskey-dev/misskey#5324]
## 💡 Summary

MisskeyRoomのページからブラウザの戻るボタンで戻った時に、テキスト入力するエリアでテキストカーソルの移動ができない。

## 🙂 Expected Behavior

MisskeyRoomからブラウザの戻るボタンで戻った後、テキスト入力エリアでテキストカーソルの移動ができる

## ☹️ Actual Behavior

（Summaryの内容）

## 📝 Steps to Reproduce

1. ルームページに移動する
2. ブラウザの戻るボタンでMisskeyのタイムラインに戻る
3. 投稿画面などのテキストを入力できるエリアで方向キーを使ってカーソルを移動

## 📌 Environment

Misskey: 11.29.0

**Comment by mei23** [comment]
メニューのルームから(router-linkで)ルームに遷移して戻ると起きる
メニューのルームを router-link => a にすればとりあえず起きないみたい

**Comment by syuilo** [comment]
Roomで何かキーボードイベントを受け取る処理があってそれと競合してそう
aで遷移するときはページ自体がリセットされるからイベントハンドラも何も残らないので問題が発生しない

**Comment by mei23** [comment]
たしかにRoom画面で矢印キー使うと動くようになってる

**Comment by mei23** [comment]
https://github.com/syuilo/misskey/blob/a39c1706a103a557c19e6701118def1c2c7385c7/src/client/app/common/scripts/room/room.ts#L769-L772
あたりに`this.controls.dispose()`を入れればなおりはする

ただ他にも`dispose()`しなければいけないものもありそうで
https://threejs.org/docs/#manual/en/introduction/How-to-dispose-of-objects
結構めんどくさいので、もうページ遷移にしちゃえばいいかも。

**Comment by syuilo** [comment]
とりあえず`this.controls.dispose()`するようにしました🙏
