### ISSUE TITLE
Room の連合

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#5325]
## Summary

+ 部屋のデータをAPで送受信
+ (独自拡張やバージョン差異などによる)対応していない家具IDはクライアントサイドで無視

**Comment by acid-chicken** [comment]
いわゆるボキャ貧に陥りそうですね……
(かといって `_misskey_うんたらかんたら` のような今までのプロパティと同じようなごまかしは避けたい)

**Comment by EbiseLutica** [comment]
独自拡張は避けたいものの、部屋を示すオブジェクトなんてものは存在しない以上拡張に委ねる他無さそう

**Comment by EbiseLutica** [comment]
APとしての正しさをいくら追い求めてもマストドンは未だOStatus時代を引きずった謎仕様だし、ユーザーにとって理に適った機能を実現できる手段であれば謎拡張も方便ってなってしまうのも現実...
