### ISSUE TITLE
Escキーで投稿フォームを閉じても絵文字ピッカーが閉じない

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#5333]
## 🙂 Expected Behavior
投稿フォームを閉じると絵文字ピッカーも閉じる

## ☹️ Actual Behavior
画面上に絵文字ピッカーが残る

## 📝 Steps to Reproduce

1. 投稿フォームを開く
2. 絵文字ピッカーを開く
3. Escキーを押す

## 📌 Environment
Misskey 11.29.0
Chrome 76.0.3809.100

**Comment by mei23** [comment]
visibility-chooserも
