### ISSUE TITLE
アカウントを削除(delete-account)がタイムアウトする

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#5336]
## 💡 Summary
[@aqz@misskey.io](https://misskey.io/@aqz)を削除しようとしたが、504 Gateway Timeoutしてできない

## 🙂 Expected Behavior
タイムアウトしない

## ☹️ Actual Behavior
タイムアウトする

## 📝 Steps to Reproduce

1. https://misskey.io/i/settings
2. プロフィール の 危険な設定を開く
3. アカウントを削除
4. パスワードを入力しておｋ

## 📌 Environment
Misskey ver 11.29.0 (daybreak) / Firefox 69.0b15 (64 ビット)

**Comment by u1-liquid** [comment]
API処理の中でDelete Person ActivityとDB変更ロジックがある為ちょっと時間かかるのが原因だと思われる
作業キュー使う必要あるかも

**Comment by tamaina** [comment]
アカウント削除には成功したみたいだけどAPIはタイムアウトしないような方式を使った方がよさそう

**Comment by mei23** [comment]
https://github.com/syuilo/misskey/blob/ab6a84cd45a266e97feee6a268495db8c161ce88/src/server/api/endpoints/i/delete-account.ts#L30-L33
`doPostSuspend`は1回クエリしてAP deliverをキューするだけなので多分おそくなくて

`Users.delete()`がユーザーが作ったもの(Notes, Notifications, …)をCASCADEで消すのでこれがおそそう

重くなるからゆっくり消したいというわけでもなければ、`Users.delete()`から`await`取るだけでいいかも

**Comment by mei23** [comment]
リモートにユーザー削除が飛んできているのに元インスタンスでは削除されてない事象を観測。
(サスペンドではない模様)

たぶん、Users.deleteが完了せず丸ごとロールバックとかされちゃってる
> // 物理削除する前にDelete activityを送信する
> await doPostSuspend(user).catch(e => {});
> 
> await Users.delete(user.id);

ユーザー削除部分はキューで以下のように処理とかしないとダメかも
- Notes削除 (逐次コミット)
- DriveFiles削除 (逐次コミット, オブジェクトストレージ等連携もする)
- User削除

**Comment by syuilo** [comment]
なるほど

**Comment by syuilo** [comment]
ジョブキューでやるにしても相当長い時間かかりそうだから、その間にサーバー再起動とかしたら処理が途中で止まって進まなくなりそう

**Comment by syuilo** [comment]
なんかたいへんそう

**Comment by mei23** [comment]
ジョブキューは再試行できるから、Notes/DriveFilesを少しずつ消してけば途中で止められてもそのうち終わるはず。

**Comment by syuilo** [comment]
Redisのデータ永続化してたか自信がなかった
