### ISSUE TITLE
The thumbnail size in CW is strange

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#5338]
## 💡 Summary
![image](https://user-images.githubusercontent.com/30769358/63622599-2866c900-c632-11e9-9765-914e1f5f993e.png)

## 🙂 Expected Behavior
See above

## ☹️ Actual Behavior
See above

## 📝 Steps to Reproduce

1. Post images with CW
2.
3.

**Comment by acid-chicken** [comment]
根本的に解決してないので一応開けておきたい
