### ISSUE TITLE
Syslogへの対応

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#5355]
現在ログはDBに直接保存されているが、大きなインスタンスになると1週間ほどで軽く1GBを超えてしまってDBのバックアップサイズに支障が出るので、Syslogサーバーへのログ転送を利用できるオプションがほしい。

**Comment by syuilo** [comment]
RFC3164, RFC5424, IBM LEEF, HP CEF というのがあるっぽいけどどれがいいんだろう

**Comment by SanMurakami** [comment]
RFC3164かRFC5424のどちらかなら大丈夫だと思います。
一般的に利用されてるのはRFC3164(BSD)形式が多いと思います。

**Comment by syuilo** [comment]
👍👍👍
