### ISSUE TITLE
ドライブのファイルを削除しても積算が減らない

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#5364]
むしろ増えている

![image](https://user-images.githubusercontent.com/37681609/63903253-b9c9a700-ca47-11e9-9b2b-7c3094be6a32.png)

![image](https://user-images.githubusercontent.com/37681609/63903210-956dca80-ca47-11e9-970d-e2d6b709db5b.png)

**Comment by anatawa12** [comment]
#8253 にてドライブ使用量の積算チャートが削除されたためcloseします。

https://github.com/misskey-dev/misskey/pull/8253/files#diff-34b2890731cab1ef976ea21fb22a1f9e219ba2602b8d799f964f63767899d119
