### ISSUE TITLE
開発ビルド時はAPI limitをすべて無効に

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#5365]
## Summary
limitのテストしたいときだけproductionにすればいいんじゃないかと

**Comment by AyaMorisawa** [comment]
configでon/offできるようにするのがいいかも

**Comment by AyaMorisawa** [comment]
(ビルドし直すのが面倒なので)

**Comment by KisaragiEffective** [comment]
fixed by ee6e022b2a523cfcd05154b2f88abb50e07104ed
