### ISSUE TITLE
「みつける」のユーザーリストがループする

### ISSUE THREAD

**Issue by Oni-Men** [misskey-dev/misskey#5369]
## 💡 Summary

「もっと読み込む」をクリックしてもそのリストの先頭のユーザーからまた始まる
(画像はでかいので最後に貼る)
## 🙂 Expected Behavior

次のユーザーから読み込まれる

## ☹️ Actual Behavior

先頭から読み込まれてループする

## 📝 Steps to Reproduce

1.みつける
2.ユーザーリストの「もっと読み込む」をクリック

## 📌 Environment
ver 11.30.0

![explore-bug](https://user-images.githubusercontent.com/19502796/64003873-2deb7400-cb48-11e9-8b1f-6b9a03c34b43.png)

**Comment by AyaMorisawa** [comment]
Duplicate of #4959
