### ISSUE TITLE
リアクションツールチップがタイミングによっては表示され続けることがある

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#5380]
表示された直後にカーソルを離すくらいのタイミングだとカーソルが離れてもツールチップが残り続けることがある

**Comment by AyaMorisawa** [comment]
APIアクセス中にカーソル離すと、hoverしてないのに表示される

**Comment by AyaMorisawa** [comment]
hoverしているかどうかの状態を保持すればよさそう
