### ISSUE TITLE
ブロックしているユーザーが自分の投稿に対してリアクションやRenoteなどをできないようにしてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#5387]
## Summary
ユーザーをブロックしたときフォローできなくなるだけでなくリアクションやRenoteができなくなるようにはしてもいいのかなと思うのですが、いかがでしょう？

**Comment by EbiseLutica** [comment]
ある意味コードレベルではないもののユーザーレベルでのBREAKING CHANGEのような気がするので要議論な気がします

そもそもMisskeyのブロックの仕様がちゃんとユーザーに伝わってないのでアレですが...

**Comment by SanMurakami** [comment]
そもそもブロックしているユーザーの投稿がブロックされている側のユーザーに流れる現象どどうにかすべきなのでは

**Comment by tamaina** [comment]
> ブロックしているユーザーの投稿がブロックされている側のユーザーに流れる

これは仕様で、被ブロックユーザーに対して隠しても公開・ホーム投稿についてはログアウトすれば見ることができるため結局無駄、ということで被ブロックユーザーに対して投稿を隠す機能は不要であるというように理解しています。
タイムラインについては、被ブロックユーザーのホームTLには流れなくなりますがローカルTLでは普通に流れているので、ローカルTLに投稿を流さないようにするというのはアリなんじゃないかと思います。

**Comment by SanMurakami** [comment]
タイムラインに流れるからリアクションされるのでは？

**Comment by EbiseLutica** [comment]
noteへのactivityを起こすきっかけはnoteが閲覧可能なことにあると思うので、なんというかミュートの逆みたいな機能は欲しいですね

**Comment by SanMurakami** [comment]
Twitterのブロックの仕様だとそうなってますね

というか、最近はもう慣れましたがMisskeyを初めて使ったときはびっくりした経験があるので、ほかのユーザーもおそらく同じ体験をしているのではないかと

**Comment by EbiseLutica** [comment]
つい最近同じことで躓いている（不安になってる）人がいたので、かなり多くの人間の思う挙動とズレているなあとは思います
