### ISSUE TITLE
モバイルでリアクション長押しで誰がしたか見れるようにする

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#5394]
## Summary

長押しを判定する方法がわからない
そういうライブラリあったけどwebpackでの使用は想定していなさそう

**Comment by AyaMorisawa** [comment]
@syuilo そのライブラリの名前分かりますか

**Comment by syuilo** [comment]
https://github.com/john-doherty/long-press-event ですね

**Comment by AyaMorisawa** [comment]
touchstartでsetTimeoutして、touchendでclearTimeoutするやつで判定できそう

**Comment by AyaMorisawa** [comment]
https://github.com/FeliciousX/vue-directive-long-press 使えそう

**Comment by syuilo** [comment]
done
