### ISSUE TITLE
Can't install Misskey on Raspberry Pi

### ISSUE THREAD

**Issue by matrix07012** [misskey-dev/misskey#5404]
## 💡 Summary

I tried installing Misskey on my Raspberry Pi and it seems one of the modules might not work on arm.

## 🙂 Expected Behavior

Build

## ☹️ Actual Behavior

![image](https://user-images.githubusercontent.com/8049717/64477464-1c374b80-d19c-11e9-830e-34ce9bdc8545.png)

[report.20190907.180254.24306.0.001.json.txt](https://github.com/syuilo/misskey/files/3586783/report.20190907.180254.24306.0.001.json.txt)

## 📝 Steps to Reproduce

1.Follow the install guide
2.Increase swap (just in case)

## 📌 Environment

OS: Raspbian GNU/Linux 10 (buster) armv7l
Host: Raspberry Pi 2 Model B Rev 1.1
Kernel: 4.19.66-v7+
NodeJS: 12.10.0
PostgreSQL: 11.5

**Comment by otofune** [comment]
By default, V8 (JS Engine used byNode.js) uses up to about 1GB memory as heap in 32bit system, but RaspberryPi2 has only 1GB Memory for all processes.
I suggest you to try passing smaller heap size by ‘ --max-old-space-size’ option. V8 may free unused data. (Or V8 may gives up...)

It can be set with ‘NODE_OPTIONS’ environment variable. See https://nodejs.org/api/cli.html for more informations.

**Comment by tamaina** [comment]
So you may be able to run Misskey on RasPi4B 2or4GB model.
