### ISSUE TITLE
Adminを変更することができないため変更コマンドの復活をしてほしい

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#5411]
## 💡 Summary

v10時代にはできていた(?) 以下の手順でAdminをコマンドで変更できる機能を復活させてほしい
https://github.com/syuilo/misskey/blob/ba474648a28a84a4f6bd31160fd513f3f6e7df99/docs/manage.ja.md

## 🙂 Expected Behavior

Adminを変更できる

## ☹️ Actual Behavior

Adminを変更するコマンドが用意されていないためできない

## 📝 Steps to Reproduce

1. https://github.com/syuilo/misskey/blob/ba474648a28a84a4f6bd31160fd513f3f6e7df99/docs/manage.ja.md の通りに操作
2. 変更できない

## 📌 Environment

Misskey v11.0～11.31.4(latest)?

**Comment by croche2574** [comment]
I also have this issue

Error: Cannot find module '/home/misskey/misskey/cli/mark-admin'

**Comment by dimlau** [comment]
For now maybe you can do this：

```
UPDATE public.user SET "isAdmin" = true WHERE username = 'YOUR-ADMIN-NAME！！！！';
```

**Comment by syuilo** [comment]
Fixed
