### ISSUE TITLE
投稿フォームが複数開いてしまう

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#5412]
## 💡 Summary
投稿フォームが複数開いてしまう

## 🙂 Expected Behavior
最大1つ

## ☹️ Actual Behavior
複数開く

## 📝 Steps to Reproduce

1. Nキーで投稿フォームを開く
2. バックグラウンドをクリックして投稿フォームを閉じようとする
3. 投稿フォームが閉じる前に、Nキーを押す

すると 2. で閉じようとした投稿フォームが閉じておらず、かつ、新たに投稿フォームが開く

## 📌 Environment
Misskey 11.31.4

**Comment by syuilo** [comment]
直ったっぽい
