### ISSUE TITLE
Implement Pleroma-style EmojiReactions instead of overloading Likes

### ISSUE THREAD

**Issue by lambadalambda** [misskey-dev/misskey#5425]
## Summary

This makes it possible to 'react' to a post with a single character unicode emoji. This adds a new object type called EmojiReaction. It looks pretty much like a Like, except it also has a content property.

See https://git.pleroma.social/pleroma/pleroma/merge_requests/1662.

**Comment by acid-chicken** [comment]
@lambadalambda Could you show us JSON-LD context definition of EmojiReaction object? I can't find the specs.

**Comment by lambadalambda** [comment]
Take a look at https://git.pleroma.social/pleroma/pleroma/blob/6fe2f554c36be1ef03ac1d1104a78d0686f48a26/test/fixtures/emoji-reaction.json this is how it looks.

**Comment by lambadalambda** [comment]
There's a spec here: https://git.pleroma.social/pleroma/pleroma-meta/issues/4

**Comment by acid-chicken** [comment]
I think the name of activity type called `EmojiReaction` doesn't seem to respect Activity Vocabulary naming style because it's not a verb. Would we use `EmojiReaction` as a content object of `Create` activity?

**Comment by mei23** [comment]
Create.EmojiReaction にするとまためんどくさいので、そのままでいいかな
動詞じゃないと気になるなら EmojiReact とか

**Comment by mei23** [comment]
Pleroma 側に Like => EmojiReaction の変換処理が入りそうなので
https://git.pleroma.social/pleroma/pleroma/merge_requests/1783

Misskey側では EmojiReaction => Like を入れればいいかなと

**Comment by mei23** [comment]
Pleroma に Like => EmojiReaction の変換が入っているので、
Misskey 側で EmojiReaction => Like の扱い (#5492) を入れれば、クローズでいいと思います。
