### ISSUE TITLE
Overlap of navigation bar in small browser window.

### ISSUE THREAD

**Issue by fz0000** [misskey-dev/misskey#5426]
## 💡 Summary
Overlap of navigation bar when put in left/right side.

## 🙂 Expected Behavior

![nav_correct](https://user-images.githubusercontent.com/5061311/64905313-ded93d80-d708-11e9-9311-174258512758.png)

## ☹️ Actual Behavior

![nav](https://user-images.githubusercontent.com/5061311/64905255-257a6800-d708-11e9-870a-16c9fd1f2d08.png)

## 📝 Steps to Reproduce

1. Resize the browser window, change the height to a small size (e.g. about 600px)
2. Settings -> Appearance -> Navbar position
3. Set to Left or Right

**Comment by nblthree** [comment]
I will work on this. also, you can assign to me any issue in English

**Comment by nblthree** [comment]
If this value https://github.com/syuilo/misskey/blob/932436096fcc2ad1d0c562db6c449c41f65ac2c9/src/client/app/desktop/views/components/ui.sidebar.vue#L319 is set to `39` it will work fine for screens of height `600` and above which should be right for the `desktop view` but there is also the possibility to make it like the `mobile view`. what do you say, which one is better?

**Comment by subpub** [comment]
#5645 is related to this. Lessen the width too and test.

**Comment by fz0000** [comment]
It seems that the style of the latest build changed a lot and it has a scroll bar now. So close it as fixed.
