### ISSUE TITLE
Use indexedDB instead of localStorage

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#5439]
## Summary
◎ Service Workerからもアクセスできる  
通知をi18nできるようになる  
◎ オブジェクトストア（テーブル）をいくつも作れる
軽量化できるかも  
▼ 非同期  
localeをindexedDBにするとなると、init.tsなどなどを全部async/awaitにしなければならなくなるが、ブロッキングだった部分が速くなるかもしれないし、ブロッキングな関数をPromiseな関数に変更できるきっかけになるかもしれない

コンポーネントでのi18n読み込み=` setLocaleMessage()`を使えばいけそう（未検証）  
https://kazupon.github.io/vue-i18n/api/#methods

[こういう](https://dexie.org/) [感じで](https://www.npmjs.com/package/vuex-persist#support-strict-mode)ラッパーライブラリがあるので実装はそこまで難しくはない気がする

**Comment by tamaina** [comment]
#6329 でi18nはindexeddbに保存されるようになった。

こんどはvuexを保存するようにしたい。

window.onstorageが使えないので、タブ間で値を共有するのに何か別の方法が必要になる

たとえば https://github.com/xanf/vuex-shared-mutations とか

**Comment by tamaina** [comment]
vuex-persistedstateは https://github.com/robinvdvleuten/vuex-persistedstate/issues/60 らしいので、永続化ライブラリを https://www.npmjs.com/package/vuex-persist とかに変える必要あり

**Comment by tamaina** [comment]
Service Workerへの設定共有はpostMessageでもできるので、必要性は薄くなった

**Comment by tamaina** [comment]
> Service Workerへの設定共有はpostMessageでもできる

保存先が複数になるのでちょっと微妙

あと、ストアがpizzaxになったので独自実装にする必要はある

**Comment by tamaina** [comment]
内容をメモリにロードしておくのは変えず（今と変わらない）、変更を適宜BroadcastChannelで通知してタブ間で同期……みたいな実装で良いかしら

**Comment by tamaina** [comment]
~~ユーザーストレージ機能でデバイスを超えてリアルタイムに設定が変化するようになってしまった~~

**Comment by tamaina** [comment]
いやでもwhere == accountだけじゃん

**Comment by tamaina** [comment]
ColdDeviceStorageをIndexedDB化してasync/awaitでやってくのがつらいので、サウンド関連の設定はpizzax化したい

**Comment by Sayamame-beans** [comment]
triage: already resolved?

**Comment by tamaina** [comment]
yep
