### ISSUE TITLE
ユーザーを特定のリストから外すと他のリストからも消える

### ISSUE THREAD

**Issue by u1-liquid** [misskey-dev/misskey#5454]
## 💡 Summary

同じユーザーが複数のリストにある場合
Aリストからそのユーザーを外すとBリストからも消えてしまう

## 🙂 Expected Behavior

外したリスト以外のリストにはそのユーザーが残っている

## ☹️ Actual Behavior

消える

## 📝 Steps to Reproduce

1. リストA、リストBを作って、両方にaiを追加する
2. リストAからaiを外す
3. リストBからもaiが外されてる

## 📌 Environment

Misskey 11.32.0

**Comment by syuilo** [comment]
Fixed
