### ISSUE TITLE
AP から Delete User が飛んできたら削除する

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#5457]
## Summary
リモートとかで凍結などされてDelete Userが飛んできたら削除する

**Comment by mei23** [comment]
この辺いじろうとするとリファクタしたくなる…

**Comment by mei23** [comment]
> DB から remove

物理削除になります

**Comment by acid-chicken** [comment]
定期的に Actor を Delete する Activity を送ってくる邪悪実装に弱くなりそうな気もする

**Comment by mei23** [comment]
そんなにNoteが溜まってなければDeleteの負荷は対してないし
投稿が溜まってるってことはCreate Noteを大量に送ってくる攻撃を受けてるということなので
物理削除自体は問題ないのかなと思います

**Comment by mei23** [comment]
`isSuspended`や`isDeleted`は`Undo Delete User`が来た時にめんどくさくて

**Comment by mei23** [comment]
連合がからむユーザー削除は #2017 にあり

**Comment by mei23** [comment]
https://github.com/misskey-dev/misskey/pull/7668 とか実装されたし
今はこれに渡すだけでいいんじゃないかなと
