### ISSUE TITLE
Semantic errors

### ISSUE THREAD

**Issue by matrix07012** [misskey-dev/misskey#5464]
## 💡 Summary
Error when building v11.33.0

## 🙂 Expected Behavior
No errors

## ☹️ Actual Behavior
![image](https://user-images.githubusercontent.com/8049717/65774919-7abe6c80-e13f-11e9-85b7-a3651cf22866.png)

## 📝 Steps to Reproduce

1.Following the update guide

## 📌 Environment

Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-55-generic x86_64)
Node v12.7.0

**Comment by syuilo** [comment]
Thank you. We are aware of this issue. You can safely ignore this error.

**Comment by syuilo** [comment]
FYI
https://github.com/typeorm/typeorm/issues/4696

**Comment by zyoshoka** [comment]
Seems to be resolved.
