### ISSUE TITLE
docker image tag 11.33.0  not found

### ISSUE THREAD

**Issue by shynome** [misskey-dev/misskey#5466]
## 💡 Summary

ci build failed , then docker image tag 11.33.0 not found

## 🙂 Expected Behavior

docker image tag 11.33.0 should be found

## ☹️ Actual Behavior

docker image tag 11.33.0 not found

## 📝 Steps to Reproduce

1. open browser , input `https://hub.docker.com/r/misskey/misskey/tags`
2. you can not find 11.33.0 on the page
3.

**Comment by acid-chicken** [comment]
It seems that the commit f4cb62db164b4315a4bc80fead8a74598c51c055 causes this issue. CC: @syuilo

**Comment by acid-chicken** [comment]
I pushed the tag `misskey/misskey:11.33.0-6f84b11` which has fixed Node.js image (base image) tag. You can use this tag instead of invalid one until official patch release bumped.

**Comment by shynome** [comment]
thank you

**Comment by syuilo** [comment]
> It seems that the commit [f4cb62d](https://github.com/syuilo/misskey/commit/f4cb62db164b4315a4bc80fead8a74598c51c055) causes this issue. CC: @syuilo

TypeScriptでコンパイルエラー出てるので、それが原因かと思ってましたけど違うのかな

**Comment by acid-chicken** [comment]
No. The image `node:12.11.0-alpine` is not exist.
FYI: https://hub.docker.com/_/node?tab=tags

**Comment by syuilo** [comment]
なるほど

**Comment by tamaina** [comment]
12.11.0-alpineについては3時間前に出たみたい

**Comment by acid-chicken** [comment]
Build task requeued https://app.circleci.com/jobs/github/syuilo/misskey/9589

**Comment by acid-chicken** [comment]
Successfully deployed https://hub.docker.com/layers/misskey/misskey/11.33.0/images/sha256-67a66d941da495ff3285b4b497869067e2f097cf83277c53b5a779eeca6489b2
