### ISSUE TITLE
投稿を削除しても投稿数が減らない

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#5479]
## 💡 Summary

投稿を削除してもユーザーのnotesCountが減らない

## 🙂 Expected Behavior

notes/delete 時に User.notesCount がデクリメントされる

## ☹️ Actual Behavior

notesCount の値が変わらない

## 📝 Steps to Reproduce

1. 何か投稿する
2. 削除する
3. 1 と 2 の間でnotesCountが変わらないのを確認

## 📌 Environment

Misskey 11.33.0

**Comment by mei23** [comment]
Related #4857 duplicate?

**Comment by mei23** [comment]
単体でデクリメントされないだけじゃなく
カスケード削除されたリプライ分もデクリメントされない
たぶんRenote元が消えた場合も

**Comment by EbiseLutica** [comment]
#4857 と被っていますね
カスケード系に関しては別件でissueにしたい所があるので一先ず閉じます。
