### ISSUE TITLE
Pagesの変数の定義をテキストで記述したい

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#5489]
現状, Pagesの変数機能は, 以下の点で使いにくいので, テキストで変数の定義を記述する機能がほしい.

* コピペができない(再利用ができない)
* 見た目が煩雑(変数定義が持つ木構造がそのままUIに出現しているので)

**Comment by futchitwo** [comment]
動的Pagesが廃止になるのでcloseでよさそうです
新機能のMisskey Playは今の所フルAiScriptなのですべてテキストで記述できます
