### ISSUE TITLE
Why HardSourceWebpackPlugin is commented?

### ISSUE THREAD

**Issue by nblthree** [misskey-dev/misskey#5498]
HardSourceWebpackPlugin will reduce build time but it's commented. is there any reason for that?

**Comment by syuilo** [comment]
When I used it, it was buggy.

**Comment by nblthree** [comment]
I will give it a try and see if I can solve the bugs

**Comment by acid-chicken** [comment]
FYI: twista enabled it few months ago but it's working well.

**Comment by nblthree** [comment]
I don't get any problem in the building process.

PS: I can't test the website yet because it is very annoying to set it up on windows

**Comment by nblthree** [comment]
So I tested it in the dev mode as well as the production mode but there was no error. Maybe it has something to do with the OS (I am on windows) it will be great if someone can confirm this.
