### ISSUE TITLE
文字列としてのリアクションを廃止

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#5501]
## Summary

現在のMisskeyは

* 文字列としてのリアクション
* 絵文字としてのリアクション
* カスタム絵文字としてのリアクション

があるけど、文字列を廃止して絵文字かカスタム絵文字かだけにしたい
分かりやすくなり、コードもすっきりする
プリンが二重に表示される問題(?)もなくなる
あと例えば`'like'`が来たら内部的に`'👍'`に変換してから処理すればいいので破壊的変更にはならない

**Comment by mei23** [comment]
擬態プリン (pudding) と 真プリン (🍮) を区別していたのがなくなってしまう
真プリン (🍮) を勝手に🍣にしていいものなのか

>  プリンが二重に表示される問題(?)もなくなる

擬態プリンと真プリンが同じ用に表示されるのは仕様のつもり…

**Comment by syuilo** [comment]
あー、プリンよりも寿司が好きオプションが動作しなくなる問題がある

**Comment by syuilo** [comment]
プリンよりも寿司が好きオプションも廃止した方が良さそう

**Comment by mei23** [comment]
えー

**Comment by syuilo** [comment]
ほむ

**Comment by EbiseLutica** [comment]
正直絵文字の仕様変更でプリン派も寿司派も仲良しになれたので、寿司好きオプション廃止は賛成です

**Comment by syuilo** [comment]
v12でやります

**Comment by mei23** [comment]
DB上で既存投稿のリアクションが
```json5
{
  'like': 2,
  'love': 1
}
```
で集計されてるところに

```json5
{
  'like': 2,
  'love': 1,
  '👍': 1
}
```
みたいなのが入って来ますが、マイグレとかする予定です？

**Comment by syuilo** [comment]
出来ればしたいですが、面倒そうなのでとりあえずはAPIレスポンス返す時にその都度 like だったら 👍 に変換するとかになりそうです
