### ISSUE TITLE
notes/search-by-tag のパフォーマンスが悪い

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#5513]
## Summary

インデックスが使われていないか、余分なデータまで取得しに行っている可能性(10件だけでいいのに全件取得してたりとか)
でもコード見る限りではインデックスも使われそうだしリミットも設定してあるから余分なものは取得されなさそう

**Comment by syuilo** [comment]
私が確認したのは「tag」パラメータのみを設定した場合

**Comment by syuilo** [comment]
良く使われるタグは速く、あまり使われないタグは遅いことから、やっぱりインデックスが使われていなさそうな予感

**Comment by u1-liquid** [comment]
FYI:
https://dba.stackexchange.com/a/125500
https://stackoverflow.com/a/39582975

**Comment by syuilo** [comment]
GINインデックスにすれば良さそう(?)

**Comment by syuilo** [comment]
https://blog.ohgaki.net/should-use-postgresql-for-tag-search

**Comment by syuilo** [comment]
https://github.com/typeorm/typeorm/blob/master/docs/indices.md#disabling-synchronization
