### ISSUE TITLE
凍結とサイレンスをした場合の新たな機能の提案

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#5521]
## Summary

スパムアカウントにより管理者が対応できる手段として、凍結とサイレンスというものがありますが、凍結及びサイレンスを行ってもその前に行われた投稿は削除されずに残るという仕様になっているようです。 ( https://misskey.io/notes/7z0o7b0lpu ) そのため、凍結やサイレンスを行った場合に既存の公開投稿をすべて削除するかローカルタイムラインでは見られないようにする機能を提案します。

### 案5 : 凍結後、それ以前の投稿を全て削除する (公開以外の投稿もすべて含む)  ( https://misskey.m544.net/notes/716de9b4f3c79aea55ba4ecc )

サイレンスについては、現在の仕様に加えて案1の流れないようにする処理をしていただきたい(大規模ではないインスタンスではスパムが残り続けることは望ましくないが、スパム以外のサイレンス処理のことも考えるとそれ以外は望ましくないため)。

**Comment by rinsuki** [comment]
凍結は解凍もできるので投稿全消去をセットにするとそのうち悲しいことが起きる気がします(一時的に投稿させないことを目的として凍結する時に過去の発言全部消す必要はない)、それはそれとしてユーザーの物理消去とか投稿全消去とかは別の機能としてあっていいと思うので別issueにするとよさそう (スパムのためならユーザーレコード残しておかなくてもユーザー物理消去でいいと思うので)
