### ISSUE TITLE
Activityグラフの描画がおかしい

### ISSUE THREAD

**Issue by YuzuRyo61** [misskey-dev/misskey#5528]
## 💡 Summary & 🙂 Expected Behavior

以前のバージョンまでは棒グラフの形状だった

## ☹️ Actual Behavior

最近のバージョンではこういう風になってる

![image](https://user-images.githubusercontent.com/18282413/67157159-5b43e980-f363-11e9-8854-5fff5aceb4b8.png)

## 📝 Steps to Reproduce

1. 誰かのプロフィールページに行く
2. activityのセクションを確認する（↑のような状態）

## 📌 Environment

- Misskey: 11.34.0
- Browser: Google Chrome 77.0.3865.120

**Comment by mei23** [comment]
たぶん
```diff
- "apexcharts": "3.8.6",
+ "apexcharts": "3.10.0",
```
のせいだけどよくわからない
