### ISSUE TITLE
groupByをどうにかする

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#5529]
src/prelude/array.tsのgroupBy関数について、名前に対して期待する挙動と実際の挙動が合わないっぽいので

@acid-chicken @mei23 

## 元のコメント
https://github.com/syuilo/misskey/pull/5515#discussion_r336269681

<details>

**acid_chicken**

> 挙動はわかるんですが、`groupBy` と `groupByX` の名前がちょっとややこしいかなと思ったりします。

**mei23**

> 既存のgroupByがgroupByじゃなくて
> [mei23@095032a](https://github.com/mei23/misskey/commit/095032ae476555de875345423cbf8bbcaa142c15)
> とかしたかったのですが
> 消したら消したでなにか言われそうなので別名にしてお茶を濁しました

**acid_chicken**

> うーん、個人的には既存の `groupBy` の名前を変えた方がいいと思います。

> 既存の方は表現としては間違ってはいないんですが、`groupBy` という名前を冠してしまうと**個人的には**期待されている動作とは違うかなといった感じがあります。ですが、LINQ 等とは異なって SQL 風の命名を避けているとも言えそうなので、いっそ NG ワードにしてしまってもいいかもしれません。

**mei23**

> 既存のgroupByは名前を変えるべきだとは思いますし
> 自分のソースなら変えちゃいますが人と調整してまで変えるモチベーションはないです
> その変めんどくさいからサクッと別名にしたのに…

> 一度`export`で公開しちゃったものでfork先とかどこで使われてるかわからないのと
> これはgroupByを変更するpull requestではないので
> とりあえずここでは元のgroupByは触らないことにして
> それは別のIssueとかでやればいいのではと
</details>

**Comment by AyaMorisawa** [comment]
preludeは、(少なくとも建前上は)アプリケーションとは関連しないコードなので、prelude側から見てどんなデータ構造が欲しいのかは分からないはずというのがあります。分類するという処理と、分類したあとにできる要素を集めてデータ構造を構築するという処理を、うまく分離できれば、必要なデータ構造ごとに構築処理を記述することはできそうです。(ただ、そこまでするほど、必要なデータ構造が多くあるかは未確認)

**Comment by KisaragiEffective** [comment]
triage: 生きている
