### ISSUE TITLE
ビルド済みコードがない状態で実行したときstderrを使う

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#5530]
## 💡 Summary
エラーだけリダイレクトしたいときに不便

> stdout に入れられるのは違和感なのと、そもそも終了コードが正常終了のそれになってしまう。

_Originally posted by @acid-chicken in https://github.com/syuilo/misskey/pull/5415_

## 🙂 Expected Behavior
* stderrを使う

## ☹️ Actual Behavior
* stdoutが使われている

## 📌 Environment
Misskey v11.34.0

**Comment by anatawa12** [comment]
該当のコードが現在のバージョンでは存在しないためcloseします。
