### ISSUE TITLE
グループの連合

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#5535]
## Summary

https://github.com/syuilo/misskey/pull/5534

**Comment by mei23** [comment]
Groupを宣言することは簡単だけど
グループにActivityを送ることを考えると
グループに第3インスタンスのユーザーが含まれている可能性があるのでめんどくさい

GroupはGroupとして伝えて
メンバーはグループが存在するインスタンスだけが知っている状態にして
そのインスタンスにさえ送れば処理してあげるようにしようとすると

1. Announceで第3のインスタンスに通知する方法があるが、公開投稿にしか使えない
2. Announceにobjectとして元投稿を添付しようとすると別の署名 (LD-Signatureとか) が必要
  MisskeyはLD-Signatureを実装していない めんどくさい
3. Announce objectにLD-Signatureを付けるくらいなら、LD-Signature付きのActivity自体を転送した方がいいかも

Group＋Groupメンバーを公開するようにして
送り側インスタンスがそれぞれメンバーのいるインスタンスに送るようにすると
上の問題はないがGroupメンバーは公開になる

**Comment by mei23** [comment]
ひとえにグループと言っても
- 第三者にメンバーを 公開する / しない
- グループ外から投稿できて よい / よくない
- フォローできる / 承認すればフォローできる / フォローできない
- メンバー追加は オーナーが一方的に追加 / 招待フローが必要

みたいな属性がありそうで、どれをサポートするかによって設計が変わりそう

Misskey v11のグループはトークのグループで 投稿のグループ みたいなのとは結構違っていて
- メンバーを公開しない
- グループ外から投稿できてよくない
- フォローできない (そもそもトークなのでフォローという概念がない)
- 招待フローが必要

みたいな属性で、APのPersonがGroupになっただけの状況とは一番遠そう。
トークのグループを連合するだけならAPのGroupに寄せなくてもいいかも。

この辺どうするかは、トークのグループを投稿に使えるグループに拡張できるかとか予定があるかにもよりそう。

**Comment by syuilo** [comment]
> トークのグループを投稿に使えるグループに拡張できるかとか予定があるかにもよりそう。

Misskeyのグループ機能は単なるリスト機能みたいな感じなので、トーク限定で使われることは想定していなくて、将来的にはグループのユーザーだけに投稿を公開するといった使い方もされるようになることを想定してました。

**Comment by tamaina** [comment]
・メンバーは別に

**Comment by tamaina** [comment]
グループトークの非公開は必須ですし、LDシグネチャの実装は必要なんじゃないかなぁと

・メンバー以外からの投稿は無視、招待者以外のフォロリクはリジェクトすれば...?    
・招待はダイレクト投稿として送信（Misskeyが受信したら招待として解釈する）とか

オーナーが「グループを公開する」とマークしてから連合するようにするとかであればメンバーの公開も大丈夫なのかなと

APについてよくわかっていないので間違ったことを言ってたらごめんなさい

**Comment by tamaina** [comment]
ん…どうなってるんでしたっけ

**Comment by tamaina** [comment]
グループ廃止
