### ISSUE TITLE
リモートアカウントを解決するとき、そのActorにendpointsが無いとTypeError

### ISSUE THREAD

**Issue by argxentakato** [misskey-dev/misskey#5539]
## 💡 Summary
[/src/remote/activitypub/type.ts](https://github.com/syuilo/misskey/blob/e14509574d534a74fcebf9515146b028bbdec153/src/remote/activitypub/type.ts)
```
export interface IPerson extends IObject {
	type: 'Person';
	name: string;
	preferredUsername: string;
	manuallyApprovesFollowers: boolean;
	inbox: string;
	sharedInbox?: string;
	publicKey: any;
	followers: any;
	following: any;
	featured?: any;
	outbox: any;
	endpoints: any; # ←ここ
}
```

## 🙂 Expected Behavior
W3Cのドキュメントによると、endpointsはあってもなくても良い

## ☹️ Actual Behavior
endpointsが無いと解決できず、TypeErrorで死ぬ

**Comment by mei23** [comment]
> endpointsが無いと解決できず、TypeErrorで死ぬ

これはどこで起きる事象でしょうか？
定義ががおかしいと言えばおかしいのですが
`endpoints`や`sharedInbox`がなくても
コンパイル時や実行時にTypeErrorになったり、Personが解決できないという事象は確認できませんでした

https://github.com/syuilo/misskey/blob/e14509574d534a74fcebf9515146b028bbdec153/src/remote/activitypub/models/person.ts#L158

**Comment by argxentakato** [comment]
記憶によればリモートアカウントを解決しようと、そのアカウントのプロフィールページを開いても、何も表示されないのでログを見るとTypeErrorを吐いていたような気がします…

今endpointsを削除してみましたが、エラーを再現できませんでした…
