### ISSUE TITLE
ログメッセージが長いとDB INSERTに失敗する

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#5549]
## 💡 Summary
ログメッセージが長いとDB INSERTに失敗する

ログ格納に失敗するとそこでエラーでコケてしまう
syslogなんかでも #5424

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by Johann150** [comment]
`log` was removed form the database in 0e4a111f81cceed275d9bec2695f6e401fb654d8
