### ISSUE TITLE
ナビゲーションバーの位置が上以外の場合に設定画面の動作に問題がある

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#5551]
💡 Summary

ナビゲーションバーの位置が上以外の場合(左/右設定)に問題があります。

## 🙂 Expected Behavior

設定画面が正しく切り替わる

## ☹️ Actual Behavior

設定画面が正しく切り替わらない(設定のフロート表示廃止ならそれで対応する?)
![スクリーンショット (5)](https://user-images.githubusercontent.com/28042693/67615322-0510f380-f806-11e9-97b0-e0cf5df099ee.png)
↑フロート表示の設定画面でデザインを選択しているが、プロフィールが表示されたままになっている状態(後ろの画面で切り替わりが反映されてしまっている)

## 📝 Steps to Reproduce

1. 設定→デザインでナビゲーションバーの位置を上以外にする
2. ナビゲーションバーに表示される設定アイコンをクリック
3. 設定が従来の設定画面(フロート表示)され、デザインや動作に切り替えるとフローと表示の設定画面ではなく後ろの設定画面だけが切り替わる

## 📌 Environment

それぞれの設定画面が専用リンクになったバージョン以降のMisskeyの問題(たぶん)

**Comment by mei23** [comment]
フロートの設定画面は
タイムラインのハッシュタグを追加でも出てきてしまう
もちろんv11でも

**Comment by tkmrgit** [comment]
フロート廃止ではなくフロート表示だけにしてほしいという意見

> ぶっっっっっちゃけ設定画面フロートに統一してほしい
> <cite><https://twista.283.cloud/notes/716e06d386ed8cea6f60bc5a></cite>

※twistaではこのバグは起こりません

**Comment by syuilo** [comment]
フロートの設定画面まだ残ってたのか＞＜

**Comment by acid-chicken** [comment]
（twista を閉鎖する気はさらさらないけど）投稿の URL ポン置きは xyz 時代に痛い目を見ているのでできれば引用して欲しいです。

**Comment by mei23** [comment]
https://github.com/syuilo/misskey/issues/5551#issuecomment-546575819
Related #5524
