### ISSUE TITLE
Image order gets scrambled when federating

### ISSUE THREAD

**Issue by chocological00** [misskey-dev/misskey#5558]
## 💡 Summary
When posting a note with manually ordered images, the activitypub renderer reorder images to uploaded order.

## 🙂 Expected Behavior
Images should be federated in the order set in Misskey.

## ☹️ Actual Behavior
Images get federated in DB row order.

## 📝 Steps to Reproduce
[On local](https://msky.naru.cafe/notes/816e11a7977d7749e9425c21) the image is ordered fine, but [on remote](https://madost.one/notes/7zdrvd0eo7) the image order is scrambled.

![image](https://user-images.githubusercontent.com/36347199/67666525-1271dd80-f9c0-11e9-97f4-6a55bd84d001.png)
![image](https://user-images.githubusercontent.com/36347199/67666535-1aca1880-f9c0-11e9-9862-5ebe137fbb09.png)

## 📌 Environment
Misskey 11.34.0 -> Other ActivityPub instances (including other Misskey Instance)

**Comment by chocological00** [comment]
Temporary fix [here](https://gitlab.com/chocological00/misskey/commit/c66ca02ed2cc0e8ff5ebdeb5811b4c649500ee53), but maybe there is a way to order this in ORM instead of using `.sort()`?

**Comment by mei23** [comment]
Related to (or duplicated?) https://github.com/syuilo/misskey/issues/5550

**Comment by mei23** [comment]
By Misskey's drive feature, sometimes DB order vs attached order is different.
So you need to preserve the attached order, instead of sorting by the id (DB row order / uploaded order).
