### ISSUE TITLE
Error While installing instance

### ISSUE THREAD

**Issue by iManolin** [misskey-dev/misskey#5569]
Error While installing instance 
can you help 
thanks 

Error
`misskey@linuxpc:/home/linuxc/misskey$ sudo NODE_ENV=production yarn build
yarn run v1.19.1
$ webpack && gulp build
  yes we can [====] 100% (100/100) 49.9s

Build completed in 49.938s

Hash: 0918805eff1cf56bfb7f
Version: webpack 4.41.1
Time: 49943ms
Built at: 10/31/2019 3:09:42 PM
                     Asset       Size      Chunks                    Chunk Names
              0.11.34.0.js    432 KiB       0, 66  [emitted]  [big]  
      0.11.34.0.js.LICENSE   95 bytes              [emitted]         
              1.11.34.0.js   55.6 KiB           1  [emitted]         
             10.11.34.0.js   2.08 KiB          10  [emitted]         
             11.11.34.0.js   1.97 KiB          11  [emitted]         
             12.11.34.0.js   4.85 KiB          12  [emitted]         
             13.11.34.0.js   3.58 KiB          13  [emitted]         
             14.11.34.0.js  936 bytes          14  [emitted]         
             15.11.34.0.js  880 bytes          15  [emitted]         
             16.11.34.0.js  591 bytes          16  [emitted]         
             17.11.34.0.js  591 bytes          17  [emitted]         
             18.11.34.0.js   83.9 KiB          18  [emitted]         
             19.11.34.0.js   48.6 KiB          19  [emitted]         
              2.11.34.0.js   5.04 KiB           2  [emitted]         
             20.11.34.0.js   25.3 KiB          20  [emitted]         
     20.11.34.0.js.LICENSE   73 bytes              [emitted]         
             21.11.34.0.js   11.2 KiB          21  [emitted]         
             22.11.34.0.js   92.3 KiB          22  [emitted]         
             23.11.34.0.js   39.3 KiB      23, 34  [emitted]         
             24.11.34.0.js    692 KiB          24  [emitted]  [big]  
             25.11.34.0.js   7.06 KiB      25, 34  [emitted]         
             26.11.34.0.js   6.84 KiB          26  [emitted]         
             27.11.34.0.js   8.52 KiB      27, 34  [emitted]         
             28.11.34.0.js    4.5 KiB          28  [emitted]         
             29.11.34.0.js   10.4 KiB          29  [emitted]         
              3.11.34.0.js   31.9 KiB           3  [emitted]         
             30.11.34.0.js     23 KiB          30  [emitted]         
             31.11.34.0.js    1.8 KiB          31  [emitted]         
             32.11.34.0.js   43.8 KiB          32  [emitted]         
     32.11.34.0.js.LICENSE  187 bytes              [emitted]         
             33.11.34.0.js   1.71 KiB          33  [emitted]         
             34.11.34.0.js   4.05 KiB          34  [emitted]         
             35.11.34.0.js   1.29 KiB          35  [emitted]         
             36.11.34.0.js   3.32 KiB          36  [emitted]         
             37.11.34.0.js   1.19 KiB          37  [emitted]         
             38.11.34.0.js    177 KiB          38  [emitted]         
             39.11.34.0.js  994 bytes      39, 66  [emitted]         
              4.11.34.0.js   76.4 KiB           4  [emitted]         
      4.11.34.0.js.LICENSE  125 bytes              [emitted]         
             40.11.34.0.js  845 bytes      40, 66  [emitted]         
             41.11.34.0.js   1.13 KiB          41  [emitted]         
             48.11.34.0.js   2.05 MiB          48  [emitted]  [big]  
             49.11.34.0.js   21.6 KiB          49  [emitted]         
              5.11.34.0.js   33.4 KiB           5  [emitted]         
             50.11.34.0.js   16.1 KiB          50  [emitted]         
             51.11.34.0.js   8.06 KiB      51, 41  [emitted]         
             52.11.34.0.js   5.23 KiB  52, 34, 55  [emitted]         
             53.11.34.0.js   16.3 KiB          53  [emitted]         
             54.11.34.0.js   8.21 KiB          54  [emitted]         
             55.11.34.0.js   4.76 KiB      55, 34  [emitted]         
             56.11.34.0.js   2.16 KiB          56  [emitted]         
             57.11.34.0.js   3.96 KiB          57  [emitted]         
             58.11.34.0.js    6.2 KiB          58  [emitted]         
             59.11.34.0.js    3.1 KiB          59  [emitted]         
              6.11.34.0.js   28.1 KiB           6  [emitted]         
             60.11.34.0.js    2.9 KiB          60  [emitted]         
             61.11.34.0.js   1.37 KiB          61  [emitted]         
             62.11.34.0.js   1.52 KiB          62  [emitted]         
             63.11.34.0.js   2.26 KiB          63  [emitted]         
             64.11.34.0.js   5.06 KiB          64  [emitted]         
             65.11.34.0.js  854 bytes          65  [emitted]         
             66.11.34.0.js  121 bytes          66  [emitted]         
              7.11.34.0.js   26.9 KiB           7  [emitted]         
              8.11.34.0.js   5.22 KiB           8  [emitted]         
              9.11.34.0.js      4 KiB           9  [emitted]         
          admin.11.34.0.js   1.38 MiB   42, 0, 66  [emitted]  [big]  admin
  admin.11.34.0.js.LICENSE  834 bytes              [emitted]         
           auth.11.34.0.js    814 KiB          43  [emitted]  [big]  auth
   auth.11.34.0.js.LICENSE  738 bytes              [emitted]         
        desktop.11.34.0.js    1.1 MiB       44, 4  [emitted]  [big]  desktop
desktop.11.34.0.js.LICENSE  864 bytes              [emitted]         
            dev.11.34.0.js   1.31 MiB          45  [emitted]  [big]  dev
    dev.11.34.0.js.LICENSE    2.1 KiB              [emitted]         
         mobile.11.34.0.js    992 KiB          46  [emitted]  [big]  mobile
 mobile.11.34.0.js.LICENSE  738 bytes              [emitted]         
             sw.11.34.0.js   3.55 KiB          47  [emitted]         sw
Entrypoint desktop [big] = desktop.11.34.0.js
Entrypoint mobile [big] = mobile.11.34.0.js
Entrypoint dev [big] = dev.11.34.0.js
Entrypoint auth [big] = auth.11.34.0.js
Entrypoint admin [big] = admin.11.34.0.js
Entrypoint sw = sw.11.34.0.js
  [6] ./src/client/app/config.ts 618 bytes {42} {43} {44} {45} {46} [built]
[113] ./src/client/app/common/views/deck/deck.column-template.vue + 4 modules 2.25 KiB {44} {46} [built]
      | ./src/client/app/common/views/deck/deck.column-template.vue 509 bytes [built]
      | ./src/client/app/common/views/deck/deck.column-template.vue?vue&type=template&id=cdbacc4a& 313 bytes [built]
      | ./src/client/app/common/views/deck/deck.column-template.vue?vue&type=script&lang=ts& 574 bytes [built]
      | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/dist/index.min.js!./src/client/app/common/views/deck/deck.column-template.vue?vue&type=template&id=cdbacc4a& 444 bytes [built]
      | ./node_modules/ts-loader??ref--5-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/dist/index.min.js!./src/client/app/common/views/deck/deck.column-template.vue?vue&type=script&lang=ts& 451 bytes [built]
[138] ./src/client/app/init.ts + 35 modules 612 KiB {42} {43} {44} {45} {46} [built]
      | ./src/client/app/init.ts 11.4 KiB [built]
      | ./src/client/app/common/hotkey.ts 3.06 KiB [built]
      | ./src/client/app/common/size.ts 537 bytes [built]
      | ./src/client/app/app.vue 449 bytes [built]
      | ./src/client/app/mios.ts 15.8 KiB [built]
      | ./src/client/app/common/keycode.ts 756 bytes [built]
      | ./src/client/app/app.vue?vue&type=template&id=1e8ddc01& 269 bytes [built]
      | ./src/client/app/app.vue?vue&type=script&lang=ts& 486 bytes [built]
      | ./src/client/app/store.ts 15.7 KiB [built]
      | ./src/client/app/common/scripts/stream.ts 8.66 KiB [built]
      | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/dist/index.min.js!./src/client/app/app.vue?vue&type=template&id=1e8ddc01& 316 bytes [built]
      | ./node_modules/ts-loader??ref--5-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/dist/index.min.js!./src/client/app/app.vue?vue&type=script&lang=ts& 556 bytes [built]
      |     + 24 hidden modules
[139] ./src/client/app/common/views/pages/not-found.vue + 4 modules 2.25 KiB {42} {43} {44} {45} {46} [built]
      | ./src/client/app/common/views/pages/not-found.vue 591 bytes [built]
      | ./src/client/app/common/views/pages/not-found.vue?vue&type=template&id=7a17a502&scoped=true& 314 bytes [built]
      | ./src/client/app/common/views/pages/not-found.vue?vue&type=script&lang=ts& 552 bytes [built]
      | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/dist/index.min.js!./src/client/app/common/views/pages/not-found.vue?vue&type=template&id=7a17a502&scoped=true& 460 bytes [built]
      | ./node_modules/ts-loader??ref--5-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/dist/index.min.js!./src/client/app/common/views/pages/not-found.vue?vue&type=script&lang=ts& 370 bytes [built]
[142] ./src/client/app/desktop/views/components/ui-notification.vue + 4 modules 2.42 KiB {44} [built]
      |    5 modules
[336] ./src/client/app/common/scripts/compose-notification.ts + 1 modules 2.59 KiB {44} {47} [built]
      | ./src/client/app/common/scripts/compose-notification.ts 2.08 KiB [built]
      | ./src/misc/get-reaction-emoji.ts 515 bytes [built]
[343] ./src/client/app/common/views/pages/share.vue + 4 modules 3.29 KiB {44} {46} [built]
      | ./src/client/app/common/views/pages/share.vue 575 bytes [built]
      | ./src/client/app/common/views/pages/share.vue?vue&type=template&id=d1a1f2d2&scoped=true& 310 bytes [built]
      | ./src/client/app/common/views/pages/share.vue?vue&type=script&lang=ts& 544 bytes [built]
      | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/dist/index.min.js!./src/client/app/common/views/pages/share.vue?vue&type=template&id=d1a1f2d2&scoped=true& 705 bytes [built]
      | ./node_modules/ts-loader??ref--5-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/dist/index.min.js!./src/client/app/common/views/pages/share.vue?vue&type=script&lang=ts& 1.18 KiB [built]
[344] ./src/client/app/common/views/pages/follow.vue + 4 modules 5.66 KiB {44} {46} [built]
      | ./src/client/app/common/views/pages/follow.vue 579 bytes [built]
      | ./src/client/app/common/views/pages/follow.vue?vue&type=template&id=9ec0c4e6&scoped=true& 311 bytes [built]
      | ./src/client/app/common/views/pages/follow.vue?vue&type=script&lang=ts& 546 bytes [built]
      | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/dist/index.min.js!./src/client/app/common/views/pages/follow.vue?vue&type=template&id=9ec0c4e6&scoped=true& 1.91 KiB [built]
      | ./node_modules/ts-loader??ref--5-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/dist/index.min.js!./src/client/app/common/views/pages/follow.vue?vue&type=script&lang=ts& 2.32 KiB [built]
[452] ./src/client/app/desktop/views/components/renote-form-window.vue + 4 modules 3.19 KiB {44} [built]
      |    5 modules
[701] ./src/client/app/sw.js 1.66 KiB {47} [built]
[702] ./src/client/app/dev/script.ts + 262 modules 774 KiB {45} [built]
      | ./src/client/app/dev/script.ts 1.01 KiB [built]
      | ./src/client/app/dev/views/index.vue 461 bytes [built]
      | ./src/client/app/dev/views/apps.vue 458 bytes [built]
      | ./src/client/app/dev/views/new-app.vue 467 bytes [built]
      | ./src/client/app/dev/views/app.vue 455 bytes [built]
      | ./src/client/app/dev/views/ui.vue 471 bytes [built]
      | ./src/client/app/dev/views/index.vue?vue&type=template&id=df4382ae& 289 bytes [built]
      | ./src/client/app/dev/views/index.vue?vue&type=script&lang=ts& 526 bytes [built]
      | ./src/client/app/dev/views/apps.vue?vue&type=template&id=1649a014& 288 bytes [built]
      | ./src/client/app/dev/views/apps.vue?vue&type=script&lang=ts& 524 bytes [built]
      | ./src/client/app/dev/views/new-app.vue?vue&type=template&id=3a79ebd2& 291 bytes [built]
      | ./src/client/app/dev/views/new-app.vue?vue&type=script&lang=ts& 530 bytes [built]
      | ./src/client/app/dev/views/app.vue?vue&type=template&id=7d9742f1& 287 bytes [built]
      | ./src/client/app/dev/views/app.vue?vue&type=script&lang=ts& 522 bytes [built]
      | ./src/client/app/dev/views/ui.vue?vue&type=template&id=f66716ca&scoped=true& 298 bytes [built]
      |     + 248 hidden modules
[704] ./src/client/app/mobile/script.ts + 95 modules 89.3 KiB {46} [built]
      | ./src/client/app/mobile/script.ts 11.7 KiB [built]
      | ./src/client/app/mobile/views/pages/index.vue 464 bytes [built]
      | ./src/client/app/mobile/views/pages/signup.vue 579 bytes [built]
      | ./src/client/app/mobile/views/pages/selectdrive.vue 599 bytes [built]
      | ./src/client/app/mobile/views/pages/drive.vue 464 bytes [built]
      | ./src/client/app/mobile/views/pages/notifications.vue 607 bytes [built]
      | ./src/client/app/mobile/views/pages/messaging.vue 476 bytes [built]
      | ./src/client/app/mobile/views/pages/messaging-room.vue 491 bytes [built]
      | ./src/client/app/mobile/views/pages/note.vue 571 bytes [built]
      | ./src/client/app/mobile/views/pages/search.vue 467 bytes [built]
      | ./src/client/app/mobile/views/pages/ui.vue 455 bytes [built]
      | ./src/client/app/mobile/views/pages/games/reversi.vue 473 bytes [built]
      | ./src/client/app/mobile/views/pages/tag.vue 458 bytes [built]
      | ./src/client/app/mobile/views/pages/index.vue?vue&type=template&id=75daf442& 298 bytes [built]
      | ./src/client/app/mobile/views/pages/index.vue?vue&type=script&lang=ts& 544 bytes [built]
      |     + 81 hidden modules
[705] ./src/client/app/admin/script.ts + 95 modules 179 KiB {42} [built]
      | ./src/client/app/admin/script.ts 593 bytes [built]
      | ./src/client/app/admin/views/index.vue 572 bytes [built]
      | ./src/client/app/admin/views/index.vue?vue&type=template&id=1a9d98d4&scoped=true& 301 bytes [built]
      | ./src/client/app/admin/views/index.vue?vue&type=script&lang=ts& 526 bytes [built]
      | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/dist/index.min.js!./src/client/app/admin/views/index.vue?vue&type=template&id=1a9d98d4&scoped=true& 5.88 KiB [built]
      | ./node_modules/ts-loader??ref--5-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/dist/index.min.js!./src/client/app/admin/views/index.vue?vue&type=script&lang=ts& 1.59 KiB [built]
      | ./src/client/app/admin/views/dashboard.vue 588 bytes [built]
      | ./src/client/app/admin/views/instance.vue 470 bytes [built]
      | ./src/client/app/admin/views/queue.vue 572 bytes [built]
      | ./src/client/app/admin/views/logs.vue 568 bytes [built]
      | ./src/client/app/admin/views/db.vue 452 bytes [built]
      | ./src/client/app/admin/views/moderators.vue 476 bytes [built]
      | ./src/client/app/admin/views/emoji.vue 572 bytes [built]
      | ./src/client/app/admin/views/announcements.vue 485 bytes [built]
      | ./src/client/app/admin/views/users.vue 572 bytes [built]
      |     + 81 hidden modules
[707] ./src/client/app/desktop/script.ts + 65 modules 79.9 KiB {44} [built]
      | ./src/client/app/desktop/script.ts 14.8 KiB [built]
      | ./src/client/app/desktop/views/home/home.vue 571 bytes [built]
      | ./src/client/app/desktop/views/pages/selectdrive.vue 599 bytes [built]
      | ./src/client/app/desktop/views/pages/drive.vue 575 bytes [built]
      | ./src/client/app/desktop/views/pages/messaging-room.vue 611 bytes [built]
      | ./src/client/app/desktop/views/pages/games/reversi.vue 473 bytes [built]
      | ./src/client/app/desktop/views/pages/settings.vue 587 bytes [built]
      | ./src/client/app/desktop/views/home/timeline.vue 587 bytes [built]
      | ./src/client/app/desktop/views/home/home.vue?vue&type=template&id=91627092&scoped=true& 309 bytes [built]
      | ./src/client/app/desktop/views/home/home.vue?vue&type=script&lang=ts& 542 bytes [built]
      | ./src/client/app/desktop/views/pages/selectdrive.vue?vue&type=template&id=a5a9083e&scoped=true& 316 bytes [built]
      | ./src/client/app/desktop/views/pages/selectdrive.vue?vue&type=script&lang=ts& 556 bytes [built]
      | ./src/client/app/desktop/views/pages/drive.vue?vue&type=template&id=0e2c6634&scoped=true& 310 bytes [built]
      | ./src/client/app/desktop/views/pages/drive.vue?vue&type=script&lang=ts& 544 bytes [built]
      | ./src/client/app/desktop/views/pages/messaging-room.vue?vue&type=template&id=a2720caa&scoped=true& 319 bytes [built]
      |     + 51 hidden modules
[709] ./src/client/app/auth/script.ts + 10 modules 7.9 KiB {43} [built]
      | ./src/client/app/auth/script.ts 537 bytes [built]
      | ./src/client/app/auth/views/index.vue 572 bytes [built]
      | ./src/client/app/auth/views/index.vue?vue&type=template&id=45a13a07&scoped=true& 301 bytes [built]
      | ./src/client/app/auth/views/index.vue?vue&type=script&lang=ts& 526 bytes [built]
      | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/dist/index.min.js!./src/client/app/auth/views/index.vue?vue&type=template&id=45a13a07&scoped=true& 1.49 KiB [built]
      | ./node_modules/ts-loader??ref--5-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/dist/index.min.js!./src/client/app/auth/views/index.vue?vue&type=script&lang=ts& 1.41 KiB [built]
      | ./src/client/app/auth/views/form.vue 568 bytes [built]
      | ./src/client/app/auth/views/form.vue?vue&type=template&id=ad3a50c6&scoped=true& 300 bytes [built]
      | ./src/client/app/auth/views/form.vue?vue&type=script&lang=ts& 524 bytes [built]
      | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/dist/index.min.js!./src/client/app/auth/views/form.vue?vue&type=template&id=ad3a50c6&scoped=true& 931 bytes [built]
      | ./node_modules/ts-loader??ref--5-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/dist/index.min.js!./src/client/app/auth/views/form.vue?vue&type=script&lang=ts& 810 bytes [built]
    + 1139 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  0.11.34.0.js (432 KiB)
  24.11.34.0.js (692 KiB)
  admin.11.34.0.js (1.38 MiB)
  auth.11.34.0.js (814 KiB)
  desktop.11.34.0.js (1.1 MiB)
  dev.11.34.0.js (1.31 MiB)
  mobile.11.34.0.js (992 KiB)
  48.11.34.0.js (2.05 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  desktop (1.1 MiB)
      desktop.11.34.0.js
  mobile (992 KiB)
      mobile.11.34.0.js
  dev (1.31 MiB)
      dev.11.34.0.js
  auth (814 KiB)
      auth.11.34.0.js
  admin (1.38 MiB)
      admin.11.34.0.js

[15:09:45] Requiring external module ts-node/register
[15:10:02] Using gulpfile /home/linuxc/misskey/gulpfile.ts
[15:10:02] Starting 'build'...
[15:10:02] Starting 'build:ts'...
[15:10:02] Starting 'build:copy'...
[15:10:02] Starting 'build:client'...
[15:10:02] Starting 'doc'...
[15:10:02] Starting 'build:copy:views'...
[15:10:02] Starting 'build:copy:fonts'...
[15:10:02] Starting '<anonymous>'...
[15:10:02] Starting 'build:client:script'...
[15:10:02] Starting 'build:client:styles'...
[15:10:02] Starting 'copy:client'...
[15:10:04] Finished 'build:client:styles' after 2.12 s
[15:10:04] Finished 'doc' after 2.36 s
[15:10:04] Finished 'build:client:script' after 2.14 s
[15:10:04] Finished 'build:copy:views' after 2.19 s
[15:10:06] Finished 'build:copy:fonts' after 3.5 s
[15:10:12] Finished '<anonymous>' after 9.65 s
[15:10:12] Finished 'build:copy' after 9.87 s
src/models/repositories/note.ts(216,10): error TS2589: Type instantiation is excessively deep and possibly infinite.
src/models/repositories/user.ts(162,18): error TS2589: Type instantiation is excessively deep and possibly infinite.
TypeScript: 2 semantic errors
TypeScript: emit succeeded (with errors)
[15:10:57] Finished 'build:ts' after 56 s
[15:10:58] gulp-imagemin: Minified 77 images (saved 395 kB - 8.3%)
[15:10:58] Finished 'copy:client' after 56 s
[15:10:58] Finished 'build:client' after 56 s
[15:10:58] Finished 'build' after 56 s
Done in 142.44s.
misskey@linuxpc:/home/linuxc/misskey$ npx node-gyp configure
npx: installed 98 in 17.836s
gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.0
gyp info using node@12.13.0 | linux | x64
gyp info find Python using Python version 3.6.8 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v12.13.0/node-v12.13.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.13.0/node-v12.13.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v12.13.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v12.13.0/SHASUMS256.txt
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, open '/home/linuxc/misskey/build/config.gypi'
gyp ERR! System Linux 4.15.0-66-generic
gyp ERR! command "/usr/bin/node" "/home/misskey/.npm/_npx/4555/bin/node-gyp" "configure"
gyp ERR! cwd /home/linuxc/misskey
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v6.0.0
gyp ERR! not ok 
misskey@linuxpc:/home/linuxc/misskey$ npx node-gyp build
npx: installed 98 in 6.542s
gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.0
gyp info using node@12.13.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/linuxc/misskey/build'
make: *** No targets specified and no makefile found.  Stop.
make: Leaving directory '/home/linuxc/misskey/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/misskey/.npm/_npx/4668/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-66-generic
gyp ERR! command "/usr/bin/node" "/home/misskey/.npm/_npx/4668/bin/node-gyp" "build"
gyp ERR! cwd /home/linuxc/misskey
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v6.0.0
gyp ERR! not ok 
misskey@linuxpc:/home/linuxc/misskey$ NODE_ENV=production yarn build
yarn run v1.19.1
$ webpack && gulp build
  yes we can [======] 95% (95/100) 41.3sError: EACCES: permission denied, open '/home/linuxc/misskey/built/client/assets/0.11.34.0.js'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
misskey@linuxpc:/home/linuxc/misskey$ 
`

**Comment by rinsuki** [comment]
Core issue is

> gyp ERR! stack Error: EACCES: permission denied, open '/home/linuxc/misskey/build/config.gypi'

and 

> Error: EACCES: permission denied, open '/home/linuxc/misskey/built/client/assets/0.11.34.0.js'

you must grant misskey user to read-write permission of `/home/linuxc/misskey`, or clone the misskey again to a place where the `misskey` user can write (e.g. under `/home/misskey/`).

**Comment by u1-liquid** [comment]
The problem caused by this command
```
misskey@linuxpc:/home/linuxc/misskey$ sudo NODE_ENV=production yarn build
```

It will create some important directory & resources under root ownership, so that normal user can't edit those files.

You should NOT build misskey via sudo.
If you have a some reason to use sudo that you forced use sudo on build time, you need to run node-gyp via sudo also.

p.s. It seems the build procedures are succeeded on your first try, so I think you don't have to run node-gyp and rebuild at that time.
