### ISSUE TITLE
Remote boost from Mastodon throws error "acct is not an user"

### ISSUE THREAD

**Issue by chocological00** [misskey-dev/misskey#5582]
## 💡 Summary
When trying to boost Mastodon's status from its original instance using misskey account, misskey throws "acct is not an user" error.
[Following status](https://planet.moe/@chocologic/102694679431847943) has been used for testing:

![image](https://user-images.githubusercontent.com/36347199/68214779-31144c00-0032-11ea-8595-85c0d7d965e2.png)

The page below can be accessed via pressing the the boost button below the status:

![image](https://user-images.githubusercontent.com/36347199/68214811-3e313b00-0032-11ea-91d9-b557ae5c26a9.png)

## 🙂 Expected Behavior
When using other mastodon account (`@chocologic@twingyeo.kr` in this case) it works fine, resolving the toot user interacted in that instance (`twingyeo.kr`):

![image](https://user-images.githubusercontent.com/36347199/68215017-9ec07800-0032-11ea-816a-0fd9ec89405c.png)

## ☹️ Actual Behavior
When using the misskey account (`@chocologic@madost.one`) it shows following error:

![image](https://user-images.githubusercontent.com/36347199/68215179-e7783100-0032-11ea-80d5-feca9d90f7f2.png)

## 📌 Environment
Mastodon 3.0.1 -> Misskey 11.35.1

**Comment by mei23** [comment]
Probably 'Remote Boost' is not implemented yet

Mastodonの実装を見ると
webfingerの `"rel":"http://ostatus.org/schema/1.0/subscribe"` の href に
ユーザーじゃなくて投稿のURLを入れると取得して投稿を表示してブーストなど出来るみたい？だけど仕様が見つからないのでよくわからない

**Comment by acid-chicken** [comment]
Related to #3899

**Comment by tamaina** [comment]
Maybe related to #2217

**Comment by firebirdos** [comment]
This issue is not resolved. It still exists in 12.47.1

**Comment by mei23** [comment]
なおってないんじゃなくてv12で壊したかサポートされなくなった
`Not a user` と出る
