### ISSUE TITLE
リモートのノートのURLが書かれていた場合、動作がおかしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#5593]
## 💡 Summary
例: https://mk.a9z.dev/notes/80546i02ru

## ☹️ Actual Behavior
- 本文のURLをクリックすると、通常のサイトのように外部に飛ぶ
- URLのプレビュー (summaly)をクリックすると、なぜかルートが自分のインスタンスのドメインになって開かれる（router-linkとして扱われる？）

## 🙂 Expected Behavior
つぎのいづれかにするべきかと思う

- 通常のサイトのリンクとして扱う
- ActivityPubのオブジェクトとして検索可能な形式ならばそのように取得し、インスタンス内のページに移動するようにする

## 📌 Environment
Misskey ver 11.35.1

**Comment by tkmrgit** [comment]
これ前から知っていたけどRenote時のURLにはRenoteした旨の表示が書かれていたから仕様かなと思ってた

**Comment by tamaina** [comment]
GitHubのバグでIssueインデックスがOpen扱いになってしまっているのでRecloseします
