### ISSUE TITLE
Search field is not visible under certain conditions

### ISSUE THREAD

**Issue by chocological00** [misskey-dev/misskey#5597]
## 💡 Summary
Search field/button on desktop view is not visible when page width is too thin or navbar is located vertically.

## 🙂 Expected Behavior
If the area is not large enough to display entire field, there should be a search button (like that of mobile view) which opens a modal with a search field.

## ☹️ Actual Behavior
This is top navbar when the browser is in fullscreen. Search field is visible:
![image](https://user-images.githubusercontent.com/36347199/69475859-8e780d80-0e26-11ea-9d35-be9e67ff257a.png)

Same settings, browser width decreased to half. Search field is gone:
![image](https://user-images.githubusercontent.com/36347199/69475863-a51e6480-0e26-11ea-80c9-9e8a57797622.png)

Changed the navbar to be on the left. Neither search field or button is visible:
![image](https://user-images.githubusercontent.com/36347199/69475888-d4cd6c80-0e26-11ea-805c-b0b0e06b2ede.png)

## 📌 Environment
Misskey 11.35.1

**Comment by tamaina** [comment]
v12で解消されました
