### ISSUE TITLE
XMPP links do not linkify

### ISSUE THREAD

**Issue by subpub** [misskey-dev/misskey#5603]
# summary

XMPP is an IETF Standard for Instant Messaging. XMPP links for example: xmpp:username@server.com should be linkified. So that XMPP apps may automatically open them.

# Expected Behavior

inserting `xmpp:` links in the following places should be linkified:

- About Me
- Profile Metadata
- Notes

# Current Behavior

It is not linkified.

**Comment by subpub** [comment]
Just adding to this for reference  https://github.com/tootsuite/Mastodon/issues/9776

**Comment by Johann150** [comment]
This should be solved by misskey-dev/mfm.js#73, MFM is supported in all three locations. You will have to put your XMPP URL into angle brackets to be recognized correctly like this: `<xmpp:nobody@example.com>` or put it in a markdown style link like this `[message me via XMPP](xmpp:nobody@example.com)`.

**Comment by subpub** [comment]
Cool!
