### ISSUE TITLE
Translate the documentation

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#5616]
I would like to implement the Misskey support with [Fedilab](https://f-droid.org/packages/fr.gouv.etalab.mastodon/)

Currently, I didn't find the documentation in english: https://misskey.io/api-doc
Is it planned to translate it?

**Comment by JochenFriedrich** [comment]
misskey support for Fedilab would be awsome 😃

**Comment by xeruf** [comment]
There are more issues:
- the readme links to a nonexisting install page (https://misskey-hub.net/docs/install/install.html)
- almost the whole navigation on https://misskey-hub.net/en/ is not translated
- the search box at the top right does not seem to do anything
- navigation links to chinese pages, I have to change the language back whenever I navigate around

This makes misskey hardly usable for non-chinese people at the moment. Note that I could become a contributing developer, but first I would like to get an overview of what misskey is capable of ^^

**Comment by syuilo** [comment]
We are aware of those problems and are currently developing them. By the way, Misskey is mainly in Japanese, not Chinese.

**Comment by xeruf** [comment]
Thanks, hard to distinguish for me as a European, sorry :)

**Comment by Johann150** [comment]
Translating the documentation should be done in the separate repository for Misskey hub: <https://github.com/misskey-dev/misskey-hub>. You are welcome to translate parts of the documentation there.

However the main API documentation is still `/api-doc` where I could not find any Japanese text.
