### ISSUE TITLE
OAuth認証画面の配色がおかしい

### ISSUE THREAD

**Issue by tateisu** [misskey-dev/misskey#5627]
## 💡 Summary

https://mastodon.juggler.jp/@tateisu/102919611557181327

開いた状態
- ユーザー名入力欄の「＠」「＠misskey.io」の文字色が白
- パスワード入力欄にヒントとパスワード伏字が両方表記されている

ユーザー名入力欄をタップしてフォーカスをあてて、何か1文字入力する
- 文字色と背景色の両方が白で何も見えない

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by SanMurakami** [comment]
確かこれ、すべての環境においてoAuthのログインは保護色になっていたはずなのだわ
