### ISSUE TITLE
Layout b0rked on narrow desktop view

### ISSUE THREAD

**Issue by subpub** [misskey-dev/misskey#5645]
On narrow width screen some things are not 'responsive'

![](https://framapic.org/nBmtCkjO3dyI/rf4d4xbck9lc)

-------

Here I have set Smallest text size. Still the name is cut:

![](https://framapic.org/xUqPLPNg7D7F/KXtavCu6snBi)

-------

Here Drive popup can't be closed at all:

![](https://framapic.org/sQfrnOZhuF76/OOIoaPxyDKy8)

-------
# 👉 Steps to reproduce
-------

1. Add Progressive Web App to phone homescreen
1. Change layout to 'desktop view'
1. Browse!

**Comment by nblthree** [comment]
The most logical thing to do is setting `min-width` (`600px` is a good value from what I see) for the wrapper div `id="app"`

**Comment by tamaina** [comment]
> Change layout to 'desktop view'

@subpub Why did you need to force 'desktop view'?
