### ISSUE TITLE
ノートのSVGのプレビュー画像がnull

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#5648]
## 💡 Summary
ノートのSVGのプレビューがnullになる。thumbnailUrlがnullだった場合の処理がうまくいっていないかもしれない。

## 🙂 Expected Behavior
SVGが表示される

## ☹️ Actual Behavior
![image](https://user-images.githubusercontent.com/7973572/71046507-dd8e3580-217b-11ea-9e73-997ca9d2d8de.png)

## 📝 Steps to Reproduce
1. svgをノートに添付して投稿

## 📌 Environment
Misskey ver 11.36.0 (daybreak)

**Comment by nblthree** [comment]
There is no thumbnail for SVG if I am not mistaken https://github.com/syuilo/misskey/blob/59493a0cd99f269c9896c49b78e8b3913527c9da/src/services/drive/add-file.ts#L177-L199

**Comment by tamaina** [comment]
@MarchWorks Yes, with some types of files, thumbnailUrl can be 'null'. The client needed to consider this, but it is not.

**Comment by nblthree** [comment]
is there any solution other than `this.image.thumbnailUrl || this.image.url` here https://github.com/syuilo/misskey/blob/4229065a695c8692e2b2a30a3e472526fd26df3a/src/client/app/common/views/components/media-image.vue#L42-L46

**Comment by tamaina** [comment]
~~これ多分サーバーサイドというか私の環境の問題で、sharpがsvgを処理できてなさそう~~  
~~一旦close~~

**Comment by tamaina** [comment]
* #5671 fixed this issue
