### ISSUE TITLE
line-heightを指定する

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#5657]
## Summary
AQUOS等のスマートフォンでは、モリサワ新ゴがプリインストールかつ初期指定のフォントなのだが、Misskeyを開くと下の画像のような状態になって非常に読みにくいため、line-heightを1.4ぐらいに指定して行間を開けて読みやすくしたほうがいいと思う。

<img src="https://d20bb5quu0uyhd.cloudfront.net/m/webpublic-a273abb8-92a3-439a-9aeb-a4ae03ca8f2c.png" width="320">

（私のデバッグ環境が整っておらず、本当にline-heightを変えたら普通の行間になるかは実はまだわからない…）

**Comment by tamaina** [comment]
デスクトップで`body, html {line-height: 1.4}`したスクショ
（ノートヘッダーをmargin-bottom: 4px→2pxに調整、その他も要調整？）
![image](https://user-images.githubusercontent.com/7973572/71398006-84823e00-2662-11ea-9d0a-69f090ad69b7.png)

**Comment by tamaina** [comment]
https://c2.a9z.dev/ に実際に適用してみた

![](https://d20bb5quu0uyhd.cloudfront.net/m/webpublic-cbddf295-58d0-4144-9580-166a991f45c2.png)

**Comment by tamaina** [comment]
（比較）

なし / 1.3  
<img src="https://d20bb5quu0uyhd.cloudfront.net/m/webpublic-a273abb8-92a3-439a-9aeb-a4ae03ca8f2c.png" width="320"><img src="https://d20bb5quu0uyhd.cloudfront.net/m/webpublic-f046da27-a603-4654-a3ea-444b39e98e9b.png" width="320">

1.3 / 1.4  
<img src="https://d20bb5quu0uyhd.cloudfront.net/m/webpublic-f046da27-a603-4654-a3ea-444b39e98e9b.png" width="320"><img src="https://d20bb5quu0uyhd.cloudfront.net/m/webpublic-79f6c930-bd56-454f-96dc-52efe1ac68d2.png" width="320">

**Comment by tamaina** [comment]
iOS Safariでめっちゃ読みにくいので、とりあえず適当なline-heightは指定しておきたいのですが……

**Comment by tamaina** [comment]
@syuilo 
> > v12用に立て直す
>
> 私が良い感じにやります

https://github.com/syuilo/misskey/pull/5659#issuecomment-579995029

**Comment by tamaina** [comment]
しゅいろができなさそうなのでやるか、昔と違って手元にiOSあるし

**Comment by tamaina** [comment]
1.5が標準的だけど、1.3ぐらいにしたい人もいると思う  
やっぱり可変式が無難な気がすると思うのだけれど…

**Comment by tamaina** [comment]
fontSize設定をvuexのdeviceからlocalStorageに移行したのはどういう理由があったのだろう…？

**Comment by tamaina** [comment]
あ～、location.reloadをするようにしたからっぽいな？

**Comment by syuilo** [comment]
やった
