### ISSUE TITLE
Renote時のvia表示の位置がよくない

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#5658]
## 💡 Summary

あたかもrenote元の投稿者がそのアプリを使って投稿したかのように見える

![image](https://user-images.githubusercontent.com/6533808/71408757-a5f32200-2682-11ea-9c44-11d550c639a6.png)

TL上でのvia表示のようにrenote表示の時間の左あたりに置くとよいかも?

## 📌 Environment

desktop, `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:73.0) Gecko/20100101 Firefox/73.0`

**Comment by EbiseLutica** [comment]
viaをrenote.userから取ってくるほうが良さそう

**Comment by rinsuki** [comment]
そもそもTL上ではrenoteしたクライアントのviaは出てないのでそれに合わせて出さないという方向でも有り
