### ISSUE TITLE
adguard入れると頻繁に接続エラーになる

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#5662]
##  Summary
https://misskey.io/notes/81qfrnetu7

**Comment by syuilo** [comment]
やっぱり警告表示した方が良いかも

**Comment by tamaina** [comment]
> やっぱり警告表示した方が良いかも

upvote  
何が起きるか予想がつかないし、一個一個対策するにしても広告ブロックなんてのは特に頻繁にアップデートされるのできりがなくなる

**Comment by acid-chicken** [comment]
完全無効にするんじゃなくてドメインだけホワリスに入れてもらわないとインラインプレイヤーの広告が出てきてしまいます。

**Comment by tamaina** [comment]
> 完全無効にするんじゃなくてドメインだけホワリスに入れてもらわないと

私AdNauseam(μBlock)しか使ったことないしそれもよくわからず使っているんですが、DISABLEや(-o)をクリックする=ドメインをホワイトリストに入れるというわけではない……？

![image](https://user-images.githubusercontent.com/7973572/71502006-edf78c00-28b0-11ea-987f-f68f77a61b12.png)
![image](https://user-images.githubusercontent.com/7973572/71502016-010a5c00-28b1-11ea-85c5-740974846a12.png)
