### ISSUE TITLE
Confused about predictive input method of emoji.

### ISSUE THREAD

**Issue by fz0000** [misskey-dev/misskey#5666]
## 🙂 Expected Behavior
The real-time predictive input should be on only when I am inputing the emoji. When the emoji has been inserted, it should be off.

##  ☹️ Actual Behavior
Please help to check which one(s) are correct behavior(s)...
1. Select an emoji from the emoji button -> The emoji list is displayed. ❓ 
![emoji](https://user-images.githubusercontent.com/5061311/71527645-4bbebf00-2917-11ea-8679-ce006302d96e.gif)

2. Just type `:emoji:` from keyboard -> The emoji list is displayed again. ❓ 
![emoji_type](https://user-images.githubusercontent.com/5061311/71527971-a1479b80-2918-11ea-9c28-53bb9d0917cc.gif)

3. Type part of the emoji code and select an emoji from the list -> The emoji list is not displayed. ✔️ 
![emoji_select](https://user-images.githubusercontent.com/5061311/71528010-c6d4a500-2918-11ea-85b5-cf38a7dd79a4.gif)

## 📌 Environment

ver 11.36.0

**Comment by Johann150** [comment]
The very similar issue linked above was fixed, and this issue is from the previous major version. I assume it has been fixed. If this is not the case, please reopen the issue.
