### ISSUE TITLE
ブロックしているインスタンス一覧が誰からでもわかる

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#5678]
## 💡 Summary
`meta`では隠しているが
`federation/instances`でフィルタ可能なので誰からでもわかる
https://github.com/syuilo/misskey/blob/e37840d870eec41599cde71baee70e3688e21f32/src/server/api/endpoints/federation/instances.ts

一般ユーザーでログインした状態で`/admin/federation`にアクセスするとUIでフィルタもできる

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by syuilo** [comment]
ブロックしているインスタンスを隠す意味はないかも

**Comment by mei23** [comment]
なるほど

**Comment by mei23** [comment]
ならmetaで隠しているのはなぜ→一般ユーザーに通常不要な情報だから とも言える

**Comment by mei23** [comment]
あえて隠匿したいって人がいたらFeature Requestとして別にIssue建ててもうらことにします
