### ISSUE TITLE
note.emojis と絵文字リアクション

### ISSUE THREAD

**Issue by tateisu** [misskey-dev/misskey#5685]
https://github.com/syuilo/misskey/blob/master/src/models/repositories/note.ts#L151 で
リアクション中の絵文字もemojisに何か書くようにしていますが、
試してみたらUnicode絵文字やカスタム絵文字リアクションをつけた投稿を見てもemojisはカラのままでした。

**Comment by mei23** [comment]
本当はカスタム絵文字リアクションに対応するEmojiを返すべき

**Comment by mei23** [comment]
今のWeb UIは、カスタム絵文字リアクションの対象絵文字を解決するために
note.emojisではなくmeta.emojisを見に行ってるので、それで動いています。
