### ISSUE TITLE
ドライブにファイルをアップロードできない

### ISSUE THREAD

**Issue by u1-liquid** [misskey-dev/misskey#5688]
## 💡 Summary

https://github.com/syuilo/misskey/blob/90cfd87f4636d98ad83ec0ce1d28eaa51dca97f8/src/misc/detect-mine.ts#L12
```
[core] TypeError: fileType is not a function
```
たぶん`file-type`をアップデートしたから起きてる

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey v11.37.0

**Comment by u1-liquid** [comment]
https://github.com/sindresorhus/file-type

```
Please be aware, the API recently changed to support smarter and more specialized methods to determine the file type.
```

使用方法が変わったぽい

**Comment by syuilo** [comment]
なるほど
メジャーアップデートじゃないから油断してた…

**Comment by syuilo** [comment]
ん、メジャーアップデートだった

**Comment by syuilo** [comment]
メジャーアップデートだけどマイナーアップデートに見間違えてたのが原因でした
