### ISSUE TITLE
ミュートしている人からのリアクション通知があると、通知があると表示される

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#5704]
## 🙂 Expected Behavior

通知はないものとして扱われる

## ☹️ Actual Behavior

通知自体は見えないけど通知があると表示される

## 📝 Steps to Reproduce

1. 
2.
3.

**Comment by rinsuki** [comment]
このへん?
https://github.com/syuilo/misskey/blob/d09d06e4cb86ce90a391cbe96a59df633c809fd4/src/models/repositories/user.ts#L197-L203

**Comment by syuilo** [comment]
そこでミュートしてるユーザーからの通知は無視するような処理してた気がしたけど気のせいだったか…
ありがとうございます👍

**Comment by tamaina** [comment]
GitHubのインデックスのバグによりRecloseします…
