### ISSUE TITLE
SCSSを使う

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#5709]
## Summary

Stylusよりメジャーな感じするしCSS標準の文法に近く学習コストを低くできそう

**Comment by acid-chicken** [comment]
個人的には PostCSS の方が良さそう。SCSS とも文法が近いし、Autoprefixer とか使うならどの道 PostCSS の依存が発生しそう。

**Comment by tamaina** [comment]
SASS使ってほしい......

**Comment by EbiseLutica** [comment]
- StylusでもSCSS的記法できる
- node-sass は gyp がしょっちゅう足を引っ張る

Stylus のリファクタリングをしてSCSS記法に切り替えるほうがゆるりとできそうにも思える 👀

**Comment by tamaina** [comment]
今はdart-sassがあるのでgypの心配は不要  

コロンまで省略して書いていたのをブロック記法にまでするのはかなり理由が気になるところ

**Comment by tamaina** [comment]
なんでdart-sass使ってないんですか？

**Comment by syuilo** [comment]
dart-sassを知りません

**Comment by tamaina** [comment]
なるほど
node-sassはレガシーなのでdart-sassを使ってください

**Comment by EbiseLutica** [comment]
@tamaina
> コロンまで省略して書いていたのをブロック記法にまでするのはかなり理由が気になるところ

につきましてはissueの主題の通り、

> CSS標準の文法に近く学習コストを低くできそう

が理由かと

**Comment by tamaina** [comment]
そのCSSの文法に近くしたい理由が知りたい

**Comment by rinsuki** [comment]
> 学習コストを低くできそう

だからでは

**Comment by tamaina** [comment]
理由として薄く感じてた

**Comment by tamaina** [comment]
ならなぜバックエンドのviewのpugもejsとかに置き換えないんだろう

**Comment by rinsuki** [comment]
バックエンドのview触る機会、フロントのCSS触る頻度に比べてかなり低そう

**Comment by tamaina** [comment]
GitHubのインデックスのバグによりRecloseしました…
