### ISSUE TITLE
MFM実装部分をライブラリとして分離してほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#5714]
## Summary
MFMの実装（パーサーとVueコンポーネント）をライブラリとして分離すれば、サードパーティのWebクライアントの製作が容易になりそう。  
また、Misskeyのコードを流用しようとするとAGPLによってソースコードを公開しなければならないが、MITなど別のライセンスでライブラリを提供すればAGPLで公開しなくてもいいようになる。

**Comment by rinsuki** [comment]
VueコンポーネントはCSSまでついてくると厄介そうだしパーサー部分だけでよさそう

(それはそれとして昔みたいに投稿情報にAST付けてくれれば必要性も下がるけど…)

**Comment by syuilo** [comment]
https://github.com/misskey-dev/mfm.js
