### ISSUE TITLE
時々スクロールがスムーズに行われない

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#5716]
## 💡 Summary

縦方向のスクロールをしようとすると引っかかることがある

原因がわからず、また再現性もなく、**リロードすると必ず治る**

情報が分かり次第追記します

## 🙂 Expected Behavior

スクロールがスムーズである

## ☹️ Actual Behavior

発生時はスクロールしようとすると引っかかってしまう

## 📝 Steps to Reproduce

不明

## 📌 Environment

macOS 10.15.2
Chrome 79.0.3945.117
Misskey 11.37.1

**Comment by SanMurakami** [comment]
スクロール自体が引っかかるというなら、Misskeyはネイティブのスクロールを利用しているのでブラウザの問題の可能性が高い

別のブラウザでも発生するなら、なにかがハングしてしまっている可能性はあるけど

**Comment by syuilo** [comment]
「引っかかる」というのは具体的にどういう状態を指すのかな
スクロールが止まってそれ以上動かなくなる？

**Comment by tamaina** [comment]
これの原因ではないかもしれないけど、スクロール位置の検知としてはスクロールされるごとに位置を確認するというような実装になっているのでパフォーマンスが悪い。スクロール検知はIntersectionObserver APIを使いたい。

**Comment by EbiseLutica** [comment]
動かなくなるわけではないものの、当該現象が起こるときは、下にスクロールするとたびたび数ピクセル上に戻りながらガクガクスクロールするような動きをする

私の環境以外でも再現するケースがある（リアルの知人から聞いたのでソースは提示できない）

**Comment by tamaina** [comment]
> 下にスクロールするとたびたび数ピクセル上に戻りながらガクガクスクロールする

URLプレビューを読み込んでる途中でスクロールするとガクガクするって感じなのでそれかもしれない？

通常のスクロールでも確かにfpsが下がることもあるけど、そこまで気にする程度ではないと思う…

**Comment by EbiseLutica** [comment]
直近数ヶ月で起きなくなったのでとりあえず閉じます
