### ISSUE TITLE
ストリーム経由のAPIリクエストを非推奨とするかどうか

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/misskey#5723]
非推奨とする場合は、
残っているドキュメントも必要に応じて削除や修正等する必要があると思います。
## 関連
https://github.com/mei23/misskey/issues/648

**Comment by tamaina** [comment]
これ非推奨なの？

**Comment by tamaina** [comment]
> サーバーはWebSocket からのAPIリクエストを普通に受け付けます
> サードパーティアプリのためにメンテナンスは続けているので、「APIのリクエスト方法(websocket/HTTP)によって返ってくるエラーの内容に違いがある」は普通にバグです
> 
> > 非推奨という認識は正しい？
> 
> まだ特に決まってないです
> 
> https://github.com/mei23/misskey/issues/648#issuecomment-575924588

**Comment by tamaina** [comment]
廃止を決定するなら今のうちですが

**Comment by syuilo** [comment]
廃止しないことは確実です

**Comment by tamaina** [comment]
それはなぜ

**Comment by syuilo** [comment]
利用しているプログラムがあるかもしれない

**Comment by tamaina** [comment]
それであれば十分な発信があれば廃止しても良いと私は思いますが、廃止に対する強い意見というのはあまり見られないので存続でもよさそう

**Comment by syuilo** [comment]
v12で非推奨にしてv13で廃止はあるかもしれない

**Comment by tamaina** [comment]
Misskey Webから削除された経緯を考えれば廃止に向かうのも妥当ですね
