### ISSUE TITLE
APIのリクエスト方法(websocket/HTTP)によって返ってくるエラーの内容に違いがある

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/misskey#5724]
以下を参照:
https://github.com/mei23/misskey/issues/648

**Comment by mei23** [comment]
WebSocket
https://github.com/syuilo/misskey/blob/ab1b0cc84043d6690dfae342ecdc35a3dffcffb2/src/server/api/stream/index.ts#L87

HTTP
https://github.com/syuilo/misskey/blob/ab1b0cc84043d6690dfae342ecdc35a3dffcffb2/src/server/api/api-handler.ts#L17-L23
