### ISSUE TITLE
Queue Deliver 500 Internal Server Error Adding Pixelfed User From Misskey

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#5725]
## 💡 Summary

[queue.deliver] failed(500 Internal Server Error) id=780 attempts=1/8 age=293ms to=https://pixelfed/users/test/inbox

## 🙂 Expected Behavior

Follow user from misskey, it should process and then show following status
![misskey-following](https://user-images.githubusercontent.com/60059665/72677761-0424f080-3adb-11ea-98dd-61c2e574f474.png)

## ☹️ Actual Behavior

Follow user and status stuck at processing

![misskey-processing](https://user-images.githubusercontent.com/60059665/72677759-fd967900-3ada-11ea-8993-f59f2c635908.png)

## 📝 Steps to Reproduce

1. add URL to pixelfed user
2. click follow
3. check status

**Comment by mei23** [comment]
Related #5715

**Comment by cliqsocial** [comment]
Ok thanks! @mei23 anything we can do to help test?

**Comment by mei23** [comment]
@cliqsocial
We have confirmed that it can be corrected.
For now it's OK. Thank you.
