### ISSUE TITLE
ReplyError: Ready check failed: NOAUTH Authentication required

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#5726]
## 💡 Summary

Getting error [core] ReplyError: Ready check failed: NOAUTH Authentication required.
{
"e": {
"code": "NOAUTH",
"command": "INFO"
}
}

## 🙂 Expected Behavior

not sure

## ☹️ Actual Behavior

not sure

What could be causing this error? Anything to check?

**Comment by mei23** [comment]
Probably Redis authentication failed.
Please check redis config.

**Comment by cliqsocial** [comment]
We tested by changing the redis password and also using very simple password (numbers and letters only) and still

> ReplyError: Ready check failed: NOAUTH Authentication required

Thank you for trying to help

**Comment by mei23** [comment]
Can you start Misskey?
If you can start it but get some errors, it might be another bug #5727.

**Comment by mei23** [comment]
Or, please check if the indent of config is broken.

Correct format:
```
redis:
  host: localhost
  port: 6379
  pass: password
```

**Comment by cliqsocial** [comment]
> Can you start Misskey?
> If you can start it but get some errors, it might be another bug #5727.

Misskey service is active and running. Timeline looks like it's getting updates.

> Or, please check if the indent of config is broken.
> 
> Correct format:
> 
> ```
> redis:
>   host: localhost
>   port: 6379
>   pass: password
> ```

Removed spacing and added two spaces before each one you listed.
After saving default.yml then restarted misskey service and same error

Not urgent so can wait until next update. Thank you for your time!

**Comment by Johann150** [comment]
I assume this was fixed with the other linked issue.
