### ISSUE TITLE
自分のユーザーページや投稿を検索エンジンにインデックスされないようにするオプション

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#5758]
## Summary

Googleなどのクローラーに、自分のコンテンツがインデックスされないようにするオプションが欲しいです。具体的には以下の内容が適用されると嬉しいです

- ユーザーページ
- Pages ページ
- 投稿

**Comment by syuilo** [comment]
検索エンジンにインデックスされたくない場合ってどんな時だろう
鍵アカウントなとき？(鍵アカウントではないけどインデックスはされたくないみたいなケースある？)

**Comment by rinsuki** [comment]
実用の面で言うとマルコフ連鎖bot系とか検索エンジンにかかっても邪魔なだけそう。
あと人間であっても「鍵にするほどではないが検索エンジンに乗るほど大々的には乗らせたくない」みたいな気持ちもありそう (ないよりはある方がマシ)

**Comment by u1-liquid** [comment]
> 検索エンジンにインデックスされたくない場合ってどんな時だろう
> 鍵アカウントなとき？(鍵アカウントではないけどインデックスはされたくないみたいなケースある？)

自分の発言がインデックスされ、自分の知らないうちにどこかで保存されること自体を嫌がる人達もいた
~~（なぜそういう人達がみんなの発言を全てのインスタンスに重複保存するFediverseにいるのかという点はわたしも疑問だけど）~~

**Comment by syuilo** [comment]
まあそういうオプションが有って損はないのでやる

**Comment by syuilo** [comment]
https://github.com/syuilo/misskey/pull/6853 でやった
