### ISSUE TITLE
AIDのノイズがあまりよくない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#5762]
## Summary
LinuxのPIDがほぼ連番に近い＋`worker.id`も1とか2 なので
ほぼ同じような値からのカウンタ値になっちゃいそう、乱数でいいかも
https://github.com/syuilo/misskey/blob/9c062643e17cc10fa9a5ff8cea2de27c62a1f695/src/misc/id/aid.ts#L7

**Comment by syuilo** [comment]
ノイズはほぼ同じ時刻で生成されたときにかぶらないようにする目的ですが、(時間ベースの)乱数にすると、ほぼ同じ時刻で生成すると乱数も同じになるのではないかという懸念がありました

**Comment by syuilo** [comment]
前に主要なMath.randomの実装はシードが時間ベースだという記事を読んだ気がしましたが、今ググっても特に出てこないので大丈夫かも

**Comment by rinsuki** [comment]
crypto.randomBytesとか使えば良いのでは

**Comment by mei23** [comment]
> ほぼ同じ時刻で生成すると乱数も同じになるのではないか

ちょっと調べたけど結局よくわからなかった
ただuuidもulidもcrypto使ってる、cryptoは速度どうなのだろう

**Comment by syuilo** [comment]
とりあえずカウンター初期値をn倍するとかで今より多少マシになるかも？

**Comment by mei23** [comment]
他のサーバーがあって同じようなPIDが生成された場合もあって
めんどくさいので最初からcryptoでカウンタ作っちゃうでいいかも
