### ISSUE TITLE
[meta] README.mdの自動更新PRがうるさい

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#5774]
## Summary

<img width="750" alt="image" src="https://user-images.githubusercontent.com/6533808/73145645-28dc2200-40f2-11ea-8e88-4e8fbb7c7141.png">

せめて一日に一回とかでいい気がする && PR にする意味あるのだろうか

**Comment by acid-chicken** [comment]
月末月頭に変更が集中することは過去にもあったのでその要領でいくらかマージしてみましたが、一向に収まるところを見せなくなったため API が仕様変更された可能性が高そうです。もはや直接 Markdown を編集するのはガタがきているとみてよいと思うので、更新を別のところに隔離して、そこから SVG で取ってくるとかの方が良いかも。

**Comment by rinsuki** [comment]
SVGだとリンクとかあれできなくてそれはそれでつらそう

**Comment by rinsuki** [comment]
そもそも README にこれ出すのなんとなくえー感があるし外したいなあと一瞬思ったが特典が README にしか出る(のとsyuiloをサポートできる)しかないのか…

https://www.patreon.com/syuilo

**Comment by acid-chicken** [comment]
なんとかいい感じにできる気がしてきたので、試してみてうまくいけそうだったら追記します。

**Comment by acid-chicken** [comment]
それはそれとして Patreon の画像更新が終わったっぽい？

**Comment by tamaina** [comment]
このREADME更新自体1年前に停止しているんですが、@syuilo はそれについてどう考えているのでしょうか…？

**Comment by rinsuki** [comment]
そもそも今の特典一覧には README に乗る旨が書かれてないのでもう消してもいいかも

**Comment by acid-chicken** [comment]
こないだ消した

**Comment by mei23** [comment]
なんかpushだけし続けてる？
https://github.com/misskey-dev/misskey/commits/patch/autogen/v11
