### ISSUE TITLE
post-form-attachesのメニューのバグ

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#5798]
## 💡 Summary
タッチデバイス(おそらく)で、post-formのファイルのサムネイルをクリックしたとき出せるメニューがclickで出てこない

こういう仕様にしたのかと思いきやこれはバグだった

予想としてはvue-draggableのせい

## 🙂 Expected Behavior
タップすればメニューが出る

## ☹️ Actual Behavior
長押ししてcontextmenuとして発火させないと出てこない

## 📌 Environment
Android Chrome latest

**Comment by syuilo** [comment]
iPadでは再現しなかった

**Comment by tamaina** [comment]
タップすれば出てくるということ？

**Comment by syuilo** [comment]
yes
