### ISSUE TITLE
v12でのデフォルトの公開範囲の問題

### ISSUE THREAD

**Issue by mfmfuyu** [misskey-dev/misskey#5799]
## 💡 Summary

v12以前のバージョンでデフォルトの公開範囲をローカルのみの設定にしている場合に設定を変更しないとBad Requestで呟けなくなってしまうため適切な設定にフォールバックしたほうが良いかなと思います。

## 📌 Environment

Misskey v12.0.0-alpha.13

**Comment by syuilo** [comment]
v11の設定が残っているとクリアしてリロードするはずなので謎ですね

**Comment by mfmfuyu** [comment]
まだ完全に処理を追えてはいませんがストレージのクリア自体はできているようです。
ただ、その後にサーバーから設定を取得しておりそこでv11の設定が読み込まれてしまっているようです。

**Comment by syuilo** [comment]
あー、なるほど
その設定はサーバー側の保存だったんですね
でも、公開範囲周りは特に変更してないのでやはり謎です

**Comment by mfmfuyu** [comment]
すみません、私の言葉足らずで誤解を招いてしまったかもしれません。
v12には現時点では公開範囲に「ローカルのみ」が存在しないためv11の時点で「ローカルのみ」の設定にしている場合には存在するものに変更しないと呟けないなどの問題が発生しています。
そこで、適切な設定に変更するのがいいのかな？と思いましたがProjectsのTo doに[ローカルのみの投稿](https://github.com/syuilo/misskey/projects/6#card-32468527)があるのを見逃してしまっていたのとv12はalphaという位置づけではあるため修正する必要はなく本IssueはCloseしてしまっても問題ないかもしれません。

**Comment by syuilo** [comment]
あー、v12ではローカルのみの設定は公開範囲の設定とは分離したことが原因かも
