### ISSUE TITLE
emoji関連のリポジトリへのライセンス表記が必要

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/misskey#5800]
他のリポジトリのコードのコピー(またはその改変)が含まれているので、そのライセンス表記を明記することが必要です。
他にもまだあるかも知れません。

https://github.com/twitter/twemoji-parser/blob/master/LICENSE.md
https://github.com/muan/emojilib/blob/master/LICENSE

**Comment by mei23** [comment]
意味合い的にはたぶん以下、どこに書けばいいかはわからない

Unicode絵文字正規表現は [twitter/twemoji-parser](https://github.com/twitter/twemoji-parser/) のものを使用しており、以下の内容でライセンスされています。  
https://github.com/twitter/twemoji-parser/blob/master/LICENSE.md

絵文字テーブルは [muan/emojilib](https://github.com/muan/emojilib) を元にしており、オリジナルは以下の内容でライセンスされています。  
https://github.com/muan/emojilib/blob/master/LICENSE

**Comment by marihachi** [comment]
LICENSE.mdに追記する感じで良いと思います。
Misskeyに対するライセンスとそれ以外のライセンスの区別がつくようにする必要はあります。(項目毎でタイトルを付けるとか)

**Comment by mei23** [comment]
LICENSE が丸ごと The AGPL v3 になっててそれがめんどくさいと思ってた

**Comment by mei23** [comment]
誰かうまいことかいてほしい

**Comment by marihachi** [comment]
LICENSEディレクトリを作って、ライセンスが適用されている対象別にファイルを分けるのもありだと思う
そういう管理も見たことがある

**Comment by rinsuki** [comment]
LICENSE.third-party.md とかにしてもよいのでは

**Comment by mei23** [comment]
メモ書き

LICENSE.third-party.md

Misskey is open-source software licensed under the GNU AGPLv3.
However, Misskey includes several third-party open-source softwares.

Unicode emoji regular expressions by Twitter, Inc.
License: MIT
https://github.com/twitter/twemoji-parser/blob/master/LICENSE.md

Emoji keywords for Unicode 11 and below by Mu-An Chiou
License: MIT
https://github.com/muan/emojilib/blob/master/LICENSE

**Comment by syuilo** [comment]
ソースコードにコメントとして書くので良いんじゃないかな

**Comment by mei23** [comment]
> ソースコードにコメントとして書くので良いんじゃないかな

半分そんな気もしていて
ソースコードリンクまでは書いてあるので、LICENSEリンクも足せばいいのかもと。

最上位でこれは syuilo AGPLv3 です！
と言い切っていいのか例外事項があることを書かなければいけないのか。

**Comment by mei23** [comment]
Resolved with #5809
