### ISSUE TITLE
Unable to see full conversation

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#5819]
## 💡 Summary

when viewing a note it's difficult to see if there is a reply.

## 🙂 Expected Behavior

see full note/post thread

## ☹️ Actual Behavior

can only see current reply and not all. have to click on each date to see additional reply

## 📝 Steps to Reproduce

1. post note
2. multiple replies
3. view reply

**Comment by syuilo** [comment]
related: https://github.com/syuilo/misskey/issues/3796

**Comment by cliqsocial** [comment]
@syuilo 

Hope to see something similar to how Twitter handles conversation thread

example: https://twitter.com/JeffVeillette/status/1224525085513592832

Thank you for misskey!

**Comment by cliqsocial** [comment]
Reference to the actual thread style

![twitter-thread](https://user-images.githubusercontent.com/60059665/73710633-8ebc4100-46d2-11ea-9a6d-718a7e14884f.png)

user can click to show more
