### ISSUE TITLE
Reversi stuck preparing

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#5828]
## 💡 Summary

reversi stuck at preparing message

![reversi-preparing](https://user-images.githubusercontent.com/60059665/73724731-fd60c500-46f9-11ea-995e-dfcb01e936de.png)

## 🙂 Expected Behavior

start play

## ☹️ Actual Behavior

stuck at preparing message

## 📝 Steps to Reproduce

1.click on games
2.invite user
3.click on ready

## 📌 Environment

nginx

**Comment by KisaragiEffective** [comment]
triage: 旧世代のリバーシのため概念ごと消滅している
