### ISSUE TITLE
JSON.parse unexpected character

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#5830]
## 💡 Summary

Misskey v12.0.0-alpha.14
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

## 📌 Environment
nginx 1.14.0 - postgres 10.10 - node 12.14.1 - npm 6.13.4 - yarn 1.21.1

**Comment by syuilo** [comment]
再現手順が不明なため閉じます 🙏🏻
