### ISSUE TITLE
Cannot read property offsetLeft

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#5832]
## 💡 Summary

Misskey v12.0.0-alpha.15
TypeError: Cannot read property 'offsetLeft' of undefined

## 📌 Environment

nginx 1.14.0 - postgres 10.10 - node 12.14.1 - npm 6.13.4 - yarn 1.21.1

**Comment by zyoshoka** [comment]
原因は以下の条件が一致していなかったことによるものと予測：

https://github.com/misskey-dev/misskey/blob/28c206304344ee5560679baf81ec1f301e344986/src/client/app.vue#L93

https://github.com/misskey-dev/misskey/blob/28c206304344ee5560679baf81ec1f301e344986/src/client/app.vue#L244

もう直っているので close します
