### ISSUE TITLE
catで投稿するとMFMコードの中が壊れてしまう

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#5837]
## 💡 Summary
catで投稿するとMFMコードの内のMFMぽいシーケンスが壊れてしまう

![image](https://user-images.githubusercontent.com/30769358/73821390-39e60b00-4837-11ea-95df-2cd8894e7f4e.png)
↓
![image](https://user-images.githubusercontent.com/30769358/73821395-3e122880-4837-11ea-99b5-13611195e0f9.png)

![image](https://user-images.githubusercontent.com/30769358/73821419-4c604480-4837-11ea-8fe6-e950a6bd4169.png)
↓
![image](https://user-images.githubusercontent.com/30769358/73821431-5124f880-4837-11ea-8e24-7ae5c8eeb762.png)

![image](https://user-images.githubusercontent.com/30769358/73821466-5da95100-4837-11ea-9901-f30371f74e13.png)
↓
![image](https://user-images.githubusercontent.com/30769358/73821469-600bab00-4837-11ea-9229-94ef0b2225a8.png)

## 🙂 Expected Behavior
コード下のものはそのまま出てくる

## ☹️ Actual Behavior
別のもので置き換えられてしまう
おそらく https://github.com/syuilo/misskey/pull/5813 の exclude 用のもの

## 📝 Steps to Reproduce
1. catにする
2. 上記のようなパターンを投稿する

## 📌 Environment
develop

**Comment by syuilo** [comment]
revertしてとりあえず直しました
