### ISSUE TITLE
MFM jump, spin, title が効かない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#5838]
## 💡 Summary
MFM jump, spin, title を指定しても効かずにただのテキストになる。
motionとかは効く, classまでは指定されている、のでdisableAnimatedMfmが有効になっているとかではなさそう。

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment
develop

**Comment by syuilo** [comment]
アニメーションをCSSで定義し忘れてそうですね
ありがとうございます🥰

**Comment by tamaina** [comment]
titleも忘れてそう
