### ISSUE TITLE
v12: list emoji picker appears after inserting an emoji via button picker

### ISSUE THREAD

**Issue by chocological00** [misskey-dev/misskey#5845]
## 💡 Summary
After adding an emoji using the emoji picker button (bottom of the note compose modal), the list emoji picker appears. When user tries to put two emojis first using the button emoji picker and then the list emoji picker, they end up getting something like `:emoji_1:emoji_2` (one colon in between, instead of two). I think this is a problem for user experience.

Related (duplicate?) with: #5666 

## 🙂 Expected Behavior
The list emoji picker should not appear when emoji is inserted via button emoji picker.

## ☹️ Actual Behavior
List emoji picker appears whenever a colon is inserted.

## 📝 Steps to Reproduce

1. Open emoji picker with the button on the bottom of the modal.
2. Insert an emoji.
3. Insert another emoji using the list picker that just appeared.

## 📌 Environment
v12.0.0

**Comment by Johann150** [comment]
I think this could be solved by inserting a space after the emoji if the emoji menu is used.

**Comment by Johann150** [comment]
I can no longer reproduce this issue. Could you please check if this still persists for you, @chocological00 ?

**Comment by chocological00** [comment]
Seems to be fixed. (Checked on 12.103.1)
