### ISSUE TITLE
投稿フォームのボタンの説明が欲しい

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#5847]
## Summary

![image](https://user-images.githubusercontent.com/6533808/73904140-77ea3a00-48de-11ea-8b4d-619595da96ec.png)
なんかやばそうなボタン(ローカルオンリーのフラグだっけ?) とか、初見じゃわからない。せめてtitle属性とかを指定するべき

**Comment by syuilo** [comment]
わかりにくいのでそのボタンは廃止予定

**Comment by tamaina** [comment]
title要素はタッチデバイスでは意味がないので、「長押しで表示するツールチップ」が必要
