### ISSUE TITLE
Mastodon相手にトークを送ると、Mastodon側からの返信が届かない

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#5848]
## 💡 Summary

Mastodon相手にトークを送ると、Mastodon側からの返信が届かない。

## 🙂 Expected Behavior

Mastodon相手にトークを送って、Mastodon側でトーク扱いの投稿に返信すると、トークとして扱われる or 普通にdirectな投稿になる

## ☹️ Actual Behavior

Mastodon相手にトークを送って、Mastodon側でトーク扱いの投稿に返信しても、Misskey側ではトークにもdirect投稿にもならない

## 📝 Steps to Reproduce

1. MastodonのアカウントにMisskeyからトークを送る
1. Mastodonのアカウントで届いたトーク (direct投稿扱い) に返信する

## 📌 Environment

misskey.io (v11)
misskey.noellabo.jp (v12)

両方で確認、Mastodon側は mstdn.rinsuki.net (v3.0.1)

**Comment by mei23** [comment]
inReplyToに元のMisskeyのNoteが添付されて返ってくるけど
その元のMisskeyのNoteは実在しない仮想のNoteなので
Reply先として解決できずにエラーになっている。

v11のDBのカスケーディングの仕様だとinReplyToが実在しないNoteは存在することができないので
Talkとして分岐して処理しないとダメそう。
