### ISSUE TITLE
/api-docを開くとエラーになる

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#5855]
## 🙂 Expected Behavior
APIドキュメントもしくはNot Found

## ☹️ Actual Behavior
`ENOENT: no such file or directory, stat '/path/to/redoc.html'`

## 📝 Steps to Reproduce

1. v12インスタンスで/api-docにアクセス

## 📌 Environment
Misskey v12.1.0

**Comment by syuilo** [comment]
Fixed
