### ISSUE TITLE
Discussion: Yarn v2

### ISSUE THREAD

**Issue by acid-chicken** [misskey-dev/misskey#5858]
Summary
--

Yarn の次期メジャーバージョンが RC 版としてリリースが開始されており、<https://yarnpkg.com/> も v2 に刷新されました。

> Yarn v2 is a very different software from the v1.
[&mdash; Migration | Yarn - Package Manager](https://yarnpkg.com/advanced/migration)

とあるぐらいそれなりに仕様変更等があるようなので、マイグレーション等どうするか議論しておきたいです。

**Comment by acid-chicken** [comment]
Memo: #5259 が Yarn の設定のみで実現できそう。
FYI: https://yarnpkg.com/advanced/migration#dont-use-resolvealiasmodules-webpack-or-modulenamemapper-jest

**Comment by acid-chicken** [comment]
少し触ってみた感想としてはまだ若干不安定（yarn.lock が存在しないとコマンドが何も動かなかったりする）

**Comment by acid-chicken** [comment]
node_modules を生成せずに `yarn node` コマンド内で `require` を自力解決するっぽい。

**Comment by acid-chicken** [comment]
> node_modules を生成せずに yarn node コマンド内で require を自力解決するっぽい。

じゃあ patch-package とかはどうすんのと思ったけど、大体そういう類は内蔵するっぽい。なんなら Yarn を拡張できるようになるみたい。

**Comment by rinsuki** [comment]
とりあえず Windows Installer / Homebrew のパッケージあたりが提供されてからで良いんではという気はする (PR作っとくのはありかもしれないけどあんまりPRでいる期間が長くなると conflict 対応つらそう)

**Comment by rinsuki** [comment]
それはそれとして、例えば webpack 5 にするみたいな既存のyarn v1の環境を壊さずにスムーズに移行できる準備を今からやってくのはアリだと思う

**Comment by acid-chicken** [comment]
とりあえず影響の少ない範囲で段階的に準備したい。

**Comment by acid-chicken** [comment]
Webpack v5 の方が楽に扱えるっぽいので同タイミングで本格移行したい。

**Comment by rinsuki** [comment]
`yarn set version berry` をするとper-projectでv2にできる (が、.yarn/releases/*.js にyarnがまるまるダウンロードされるのでかなり渋い機能)

**Comment by acid-chicken** [comment]
> `yarn set version berry` をするとper-projectでv2にできる (が、.yarn/releases/*.js にyarnがまるまるダウンロードされるのでかなり渋い機能)

依存関係の解決に必要なものや、依存関係の実体も圧縮して .yarn 内に管理することで、環境の違いによる挙動差をより減らしたいためと思われる。

**Comment by rinsuki** [comment]
それはそうだけどあちこちに同じバージョンのyarnが転がるのアレだしバージョン指定で済ませられるようにして欲しかった

**Comment by ThatOneCalculator** [comment]
I've been using yarn 3.x (berry) with Misskey for about a month -- both on my dev machine and on the server -- and there's been no problems. 

![image](https://user-images.githubusercontent.com/44733677/162042326-85c66b2c-16f7-4612-8c4f-27d5adbc1bd8.png)

**Comment by acid-chicken** [comment]
> それはそうだけどあちこちに同じバージョンのyarnが転がるのアレだしバージョン指定で済ませられるようにして欲しかった

@rinsuki 時は流れ、corepack によって実現された 🎉
