### ISSUE TITLE
Multiple thumbnail showing for old note

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#5867]
## 💡 Summary

each tag has a thumbnail showing = note is very long

## 🙂 Expected Behavior

existing note should show single thumbnail
https://github.com/syuilo/misskey/issues/5729

**Is there a way to clean and fix old note format?**

## ☹️ Actual Behavior

**existing old** note still showing multiple tags - new note is ok

## 📝 Steps to Reproduce

1. view old note before upgrade v11
2. multiple thumbnails showing
3. view new note after upgrade v12
4. no multiple thumbnails

## 📌 Environment

nginx 1.17.8 - node 12.14.1 - npm 6.13.4 - misskey **12.2.0**

**Comment by tamaina** [comment]
Too old to close. Reopen if you are still having problems.
