### ISSUE TITLE
404 thumbnail for old notes

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#5870]
## 💡 Summary

thumbnail are not generated for **old** notes with 404 error

## 🙂 Expected Behavior

display thumbnail

## ☹️ Actual Behavior

viewing old note in timeline showing broken thumbnail 404

compare same note
```
https://cliq.social/notes/82c4fn9ct9 (media missing)
https://mastodon.cloud/@evelynyap/103460681859768758 (media not missing)
```

## 📝 Steps to Reproduce

1. view timeline of old notes
2. thumbnail missing
3. view timeline of new notes
4. thumbnail ok

## 📌 Environment

nginx 1.17.8 - node 12.14.1 - npm 6.13.4 - misskey 12.2.0

**Comment by cliqsocial** [comment]
Another 404 thumbnail example

app.12.4.1.js:2

```
https://cliq.social/notes/834t0o61fv
```

![misskey-thumbnail404](https://user-images.githubusercontent.com/60059665/74092625-a0b43000-4a94-11ea-9341-8ec1b8d663f2.png)

**Comment by okpierre** [comment]
@syuilo Is this a Misskey caching issue? Maybe a setting in Misskey to delete all old reference and regenerate thumbnail would fix this?

**Comment by tamaina** [comment]
Too old to close. Reopen if you are still having problems.
