### ISSUE TITLE
404 unread svg

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#5871]
## 💡 Summary

unread svg showing 404

## 📝 Steps to Reproduce

1. go to misskey talk
2. browse
3. 404 error 

## 📌 Environment

nginx 1.17.8 - node 12.14.1 - npm 6.13.4 - misskey 12.2.0

**Comment by okpierre** [comment]
before 
![unread-before](https://user-images.githubusercontent.com/1679025/74203344-4904f880-4c3d-11ea-9e14-535cc0093cb2.jpeg)

after
![unread-after](https://user-images.githubusercontent.com/1679025/74203352-4e624300-4c3d-11ea-8805-7a5bb1963ec8.jpeg)
