### ISSUE TITLE
メディアプロキシのファイルを保存しようとするとファイル名が無くなる

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#5892]
## 📝 Steps to Reproduce

1.
2.
3.

**Comment by mei23** [comment]
Misskey側の生成URLを変えるという方法もあるけど
`https://mediaproxy/?url=<URL>`
↓
`https://mediaproxy/<FILE>?url=<URL>`

FILEの部分はURLから生成されたものなので
(メディアプロキシ＝リモートファイル だから必ずこのパターン)
メディアプロキシ側でURLからFILE取得してContent-Disposition出力でもいいかも。

**Comment by tamaina** [comment]
直した
