### ISSUE TITLE
Localization-Unable to display Chinese Translation

### ISSUE THREAD

**Issue by ZerowindSE** [misskey-dev/misskey#5902]
## 💡 Summary
When the browser language is Chinese, the Chinese interface will not be displayed.
**Display in all languages except Chinese.**

This error did not appear in the old version(12.4.1).

I checked the local language file, everything is OK.

## 📝 Steps to Reproduce
1.Set browser language to Chinese
2.Force page refresh
3.You can only see the English interface.

## 📌 Environment
Chrome 80.0.3987.87 / Firefox 57.0
Misskey Version : 12.6.0 (2020/02/10)

**Comment by syuilo** [comment]
Thank you for your report.
I will fix the issue 🥰
