### ISSUE TITLE
タイムラインの更新を止める機能

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#5907]
## Summary
v12からずっと更新されるようになったけど、フォロー数が多いと止まってくれないと厳しい

**Comment by tamaina** [comment]
タイムラインが更新されているかどうかを右上に▶（ライブ）/||（更新停止中）で表示されるようにして、スクロールが先頭でないときは自動的に||になる。
さらに、||のときは新着投稿の数をバッジで表示する。

みたいなやつをやりたい

**Comment by syuilo** [comment]
せっかくスクロール位置記憶するようになったのにバックグラウンドでタイムラインが流れていくと無意味だからやりたい

**Comment by tamaina** [comment]
ちょっと実装が面倒臭いかもだけど、メニューやリアクションを開いているときも止まってほしい

**Comment by syuilo** [comment]
あるコンポーネントが、スクロールされているのかどうか知る術がないのがキツイ

**Comment by syuilo** [comment]
``` ts
function getScrollPosition(el: Element | null): number {
	if (el == null || el.tagName === 'BODY') return window.scrollY;
	const style = window.getComputedStyle(el);
	if (style.getPropertyValue('overflow') === 'auto') {
		return el.scrollTop;
	} else {
		return getScrollPosition(el.parentElement);
	}
}
```
でいけるかも
