### ISSUE TITLE
Page not found for settings api

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#5911]
## 💡 Summary

Settings not found for `https://www.example.com/i/settings/api`
There was no page corresponding to the specified URL.

## 🙂 Expected Behavior

users can view settings page in v11

## ☹️ Actual Behavior

error: There was no page corresponding to the specified URL.

## 📝 Steps to Reproduce

1. login
2. go to page -> `https://www.example.com/i/settings/api`
3. error message

## 📌 Environment

nginx 1.17.8 - node 12.15 - npm 6.13.4 - misskey 12.6.0

**Comment by tamaina** [comment]
Settings moved to `https://www.example.com/my/settings`.  
I think it is necessary to redirect.

**Comment by cliqsocial** [comment]
Thanks for the url 

Checked `https://www.example.com/my/settings` and it's missing api section

Misskey v11 has the api section listed

**Comment by tamaina** [comment]
It seems that v12 don't have api section. Do you plan to revive the section, @syuilo ?

**Comment by syuilo** [comment]
Done
