### ISSUE TITLE
[HELP] サインアップ／ログインなどの情報が表示されない

### ISSUE THREAD

**Issue by mzch** [misskey-dev/misskey#5914]
## 💡 Summary
インスタンスは、https://c1m2.com ですが、空の画面が出るばかりで何もできません。
```
yarn
NODE_ENV=production yarn build
yarn run init
```
以外に何か必要なのでしょうか。

## 🙂 Expected Behavior
ログイン／サインアップリンクが表示される。

## ☹️ Actual Behavior
以下の通りです。

![Shot004](https://user-images.githubusercontent.com/621178/74222108-03a50180-4cf7-11ea-8e26-46ab13b661ac.png)

## 📝 Steps to Reproduce

1. https://c1m2.com にアクセスする

## 📌 Environment
`Node.js`: `12.15.0`
`Yarn`: `1.21.1`
`PostGreSQL`: `11.6`
`Redis`: `5.0.3`
`OS`: `Debian 10.3`

**Comment by tamaina** [comment]
Misskey本体のバグです。修正します。
