### ISSUE TITLE
アイコンファイルのソースをAIで保存

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#5922]
afdesignは一般的に開けるアプリケーションが少なく、オンラインのコンバーターもないのでAffinity Designerを持っていないユーザーは開けない

こういったファイルはAdobe Illustratorで編集するのが一般的なので、Adobe Illustratorで書き出しもしくはSVG等の一般的に開くことができるファイル形式で書き出すべき
https://github.com/syuilo/misskey/blob/develop/assets/icon.afdesign

**Comment by acid-chicken** [comment]
EPS の方が良さそう

**Comment by SanMurakami** [comment]
> EPS の方が良さそう

個人的にはAIファイルの方がいいと思いますけどね
SVGとの比較なら、EPSはブラウザでプレビュー出来ないのでやはりSVGの方がいいと思いますし

**Comment by SanMurakami** [comment]
というか、.afdesign, .ai, .eps, .svgを公開すれば済む話では

**Comment by syuilo** [comment]
> というか、.afdesign, .ai, .eps, .svgを公開すれば済む話では

affinity designerを持ってない人は編集した時にafdesignで保存できないからaiだけで良いと思う

**Comment by tamaina** [comment]
とりあえずaiかsvgにコンバートしてほしいです  
joinmisskeyのアイコン更新したい
