### ISSUE TITLE
Browser freeze when going to messaging

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#5930]
## 💡 Summary

browser freeze when opening messaging

## 🙂 Expected Behavior

messaging window open 

## ☹️ Actual Behavior

clicking on messaging and browser freeze then have to to close entire window

## 📝 Steps to Reproduce

1. go to messaging
2. start messaging
3. messaging with group
4. browser window freeze and can't be used 

## 📌 Environment

nginx 1.17.8 - node 12.15 - npm 6.13.4 - misskey 12.8.0

**Comment by syuilo** [comment]
Thank you for reporting, but i can not reproduce the issue 👀

**Comment by cliqsocial** [comment]
@syuilo here's the cause

```
TypeError: Cannot read property 'value' of undefined
    at o.data (app.12.8.0.js:2)
    at o.<anonymous> (app.12.8.0.js:2)
    at app.12.8.0.js:2
    at app.12.8.0.js:2
    at mn (app.12.8.0.js:2)
    at o.t._init (app.12.8.0.js:2)
    at new o (app.12.8.0.js:2)
    at kn.new (app.12.8.0.js:2)
    at kn.dialog (app.12.8.0.js:2)
    at o.startGroup (13b94.76.js:1)
```

**Comment by syuilo** [comment]
This bug seems to appear when there are no groups. I will fix the bug.
Thank you!

**Comment by cliqsocial** [comment]
You're welcome! Glad to test and help!
