### ISSUE TITLE
検索周りの改善について

### ISSUE THREAD

**Issue by mfmfuyu** [misskey-dev/misskey#5934]
## Summary

ヘッダーの検索フォームやメニューの検索ダイアログで検索を行ってしまうと入力内容が消えてしまう仕様は不便かなと思うので引き継ぐようにしたほうが親切かなと思うのですがいかがでしょうか？

実装済みなので問題なければすぐにPRを投げられる状態になっています。

**Comment by tamaina** [comment]
よくわからない

**Comment by mfmfuyu** [comment]
相当前に作ったIssue で今は色々と変わってそうなのでクローズしておきます...
