### ISSUE TITLE
メディアプロキシ使用時にリモートアバターの透過やアニメーションが失われる

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#5940]
## 💡 Summary
メディアプロキシの実装方法にもよるけど、
サムネイルは常にJPEGのような実装の場合
リモートのアバターの透過やアニメーションが失われてしまう。

おそらく投稿の添付ファイルのサムネイルも同様。

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by rinsuki** [comment]
メディアプロキシ側の問題なのでMisskeyではどうしようもないのでは…?

**Comment by mei23** [comment]
それもそう
でも公式インスタンスの挙動がこれなのはちょっと

**Comment by SanMurakami** [comment]
> それもそう
> でも公式インスタンスの挙動がこれなのはちょっと

これはMisskey.io側の問題なのでMisskeyに建てるIssueではないと思います。
問題は把握済みで現在対処中です。

**Comment by mei23** [comment]
リファレンスの仕様とか実装みたいなのがないのがいけないのかも
