### ISSUE TITLE
ユーザープレビューが稀に画面上から消えなくなってしまう

### ISSUE THREAD

**Issue by mfmfuyu** [misskey-dev/misskey#5943]
## 💡 Summary

ユーザープレビューが消えずに画面上に残ってしまう。
また、残ってしまったユーザープレビューにマウスカーソルを乗せてから離しても自動的に消えない。

## 🙂 Expected Behavior

ユーザープレビューが消える

## ☹️ Actual Behavior

ユーザープレビューが消えない

## 📝 Steps to Reproduce

不明

## 📌 Environment

v12.9.0（以前のv12バージョンでも確認しています）
Chrome（Desktop）

**Comment by tamaina** [comment]
URLプレビューのポップアップも同じ感じですね  
とくにモバイルだと顕著

**Comment by mfmfuyu** [comment]
モバイルではプレビューを無効化してしまっても良さそう

**Comment by syuilo** [comment]
モバイルというより、タッチ操作している場合は無効にしたいですが、JavaScriptではタッチ操作しているデバイスなのかどうか判定する術がない

**Comment by mfmfuyu** [comment]
確かにJSでは画面の種別とかは取得できないですね...
touchstartイベントなどを取得してやればタッチパネルを使っているかどうかの判定は無理やり実装はできそうです
この方法であればSurfaceのようなタッチパネルがあるような端末でもタッチ操作時は無効といった動作を実現できそう

**Comment by syuilo** [comment]
まだ直ってなかった＞＜

**Comment by syuilo** [comment]
プレビューが出る直前くらいにページ遷移すると発生する

**Comment by syuilo** [comment]
keep-aliveだとunbindが発生しないのが原因そう

**Comment by syuilo** [comment]
あー、プレビュー呼び出し側でコンポーネントの close を呼び出しても、ユーザー情報取得したときにコンポーネントが show = true されるから、close を呼び出した後にユーザー情報取得するようなタイミングだと永久にcloseされなくなる
