### ISSUE TITLE
TLの最上端に行くボタン

### ISSUE THREAD

**Issue by u1-liquid** [misskey-dev/misskey#5949]
## Summary

モバイルでは（TL画面ではdisableになる）ホームアイコンのボタン、PCでは画面上に↑ボタンを置いて、スクロールしたあとそれを押すとTLの最上端に飛ぶボタンを実装しようというIssueです👍

**Comment by syuilo** [comment]
PCでは「タイムライン」リンクを押すことで飛ぶようにするのが良さそう
