### ISSUE TITLE
ライトテーマで通知のRenoteアイコンが真っ白

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#5955]
## 💡 Summary
![image](https://user-images.githubusercontent.com/7973572/74599358-c7d9b580-50c3-11ea-9c56-f73dd382a086.png)

**Comment by okpierre** [comment]
@tamaina will create a pull request to fix this

**Comment by syuilo** [comment]
Fixed by @okpierre

**Comment by tamaina** [comment]
投票もだったっぽい
