### ISSUE TITLE
絵文字のオートコンプリートがカスタム絵文字数の多い環境で非常に遅くなる

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#5975]
件数制限などを設けたほうが良さそう？

**Comment by rinsuki** [comment]
文字コード順であらかじめソートしてこのへんからこのへんかな〜ってやるだけで軽くなりそう

**Comment by EbiseLutica** [comment]
: を書くだけで重くなる問題があるので、 : だけだとその推論ができそうもない

**Comment by rinsuki** [comment]
ふぅ〜む

**Comment by rinsuki** [comment]
というか : だけでどうやって補完してるんだ

**Comment by rinsuki** [comment]
: で出る絵文字を最近使った絵文字10選とかにするとよさそう

**Comment by EbiseLutica** [comment]
: は多分カスタム絵文字一覧の全件を取得してサジェストしているみたい。これが100個ぐらい登録しているインスタンスだとDOM更新&画像読み込みでめちゃ重くなる
絵文字ピッカーが実装されたので、:だけで補完しないようにしても良いような気がします

**Comment by EbiseLutica** [comment]
ただ:だけで補完する機能が、これまでリアクションにカスタム絵文字を使う上での便利機能だったので、リアクションピッカーに絵文字ピッカーボタンを用意したり、リアクションピッカーの設定画面に絵文字ピッカーを置いたりする必要が浮上します。

これは別issueのお話かな

**Comment by syuilo** [comment]
> : で出る絵文字を最近使った絵文字10選とかにするとよさそう

やった

> リアクションピッカーに絵文字ピッカーボタンを用意したり、リアクションピッカーの設定画面に絵文字ピッカーを置いたりする必要が浮上します。

リアクションピッカーと絵文字ピッカーが統合された
