### ISSUE TITLE
ドライブ画面を広くする

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#5985]
## Summary

スマートフォン最適化の影響によりドライブ画面が非常に小さくなってしまっている。
![LSRYZENCapture551](https://user-images.githubusercontent.com/28042693/74745329-14c9b180-52a7-11ea-892f-3b01f39bed0b.png)
画像引用元 : https://misskey.dev/notes/83vgsiyk1g

PC表示の場合はv11のようにドライブ画面のリサイズやより広い表示領域を確保してほしい。

**Comment by syuilo** [comment]
対応中
