### ISSUE TITLE
ユーザーのwatch 

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#599]
ユーザーをwatchするとそのユーザーのアクションが通知されるようになる

**Comment by rinsuki** [comment]
ネトストにつながるので良くないのでは（せめてターゲットユーザーの許可を得るべき）

**Comment by tamaina** [comment]
#5708 との違いとは

**Comment by syuilo** [comment]
こっちは投稿に限らず何らかのアクションを通知するものだと記憶しています

**Comment by syuilo** [comment]
需要なさそう
