### ISSUE TITLE
サムネイル画像が設定されているPagesのタイトル一覧の表示がバグっている

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#5992]
## 💡 Summary

![LSRYZENCapture558](https://user-images.githubusercontent.com/28042693/74747977-21e89f80-52ab-11ea-9a3e-3968626c1453.png)
サムネイル画像が設定されたPagesのタイトル一覧がバグって表示されます。サムネイルも一部だけが拡大されたような表示になっています。

## 🙂 Expected Behavior

バグらない(以下/v11のような表示になる)
![LSRYZENCapture561](https://user-images.githubusercontent.com/28042693/74748204-7b50ce80-52ab-11ea-8f0b-78c78d5a7a06.png)

## ☹️ Actual Behavior

バグる

## 📝 Steps to Reproduce

1.画像にサムネイルを設定したPagesを作成する
2.https://misskey.io/my/pages を開く
3.WOW!

**Comment by syuilo** [comment]
なおった
