### ISSUE TITLE
マルチアカウント運用時にアカウント連携をすると挙動がおかしい

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6000]
## 💡 Summary

マルチアカウント運用時に連携機能を使うと、アカウント追加前にはじめてログインしたアカウントに紐付けされてしまう。

Twitter, GitHub, Discord いずれも同じ挙動を再現。

## 📌 Environment

v12

**Comment by futchitwo** [comment]
アカウント連携機能が廃止されたのでcloseして良さそうです
