### ISSUE TITLE
セッションのリロード機能が場合によっては邪魔になり得る問題

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6002]
電車や館内など、電波の届きにくい場所だと頻繁に再接続が発生する

こういう場所で投稿を作成中にリロードされると非常に不便なのと、自動リロードが無効でもモーダルダイアログが表示されてしまい邪魔である

セッションが切れた時の挙動を
- 控えめにポップアップする
- ダイアログを出す
- 自動でリロードする
という3択にするのが良いかなーって思うんですが、どうでしょう

**Comment by SanMurakami** [comment]
現状の実装を確認してないけど、何もしなくても再接続は自動でされるのだろうか
というか、今までのように接続切れたら右下に「再接続中」って表示してほしさある

**Comment by EbiseLutica** [comment]
今まで再接続自体はされていて、本機能はその間の投稿が表示されない問題を解消するため明示的にリロードを促すダイアログが出るようになった、みたいな経緯だった気がする

でもタイムラインや通知だけリロードするんじゃダメなのかなこれとも思う

**Comment by SanMurakami** [comment]
> でもタイムラインや通知だけリロードするんじゃダメなのかなこれとも思う

それはそうって感じ

**Comment by tamaina** [comment]
リロードの表示関連は落ち着いた感じと思うのでCloseします
