### ISSUE TITLE
iOSのステータスバータップで上に戻れない

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#6004]
## 💡 Summary

iOSのステータスバータップで上に戻れない
ホームアイコンで戻れるけどiOSの殆どのアプリがステータスバータップで上に戻る仕様なので使えないとちょっと面倒くさい。

## 🙂 Expected Behavior

ステータスバータップで上に戻れる

## ☹️ Actual Behavior

ステータスバータップで上に戻れない

## 📝 Steps to Reproduce

1. スクロールする
2. ステータスバーをタップ

## 📌 Environment
Misskey.io
Misskey v12.16.0

**Comment by u1-liquid** [comment]
参考: https://stackoverflow.com/questions/14868053/webkit-overflow-scrollingtouch-and-tap-status-bar-to-scroll-to-top/18686427

**Comment by tamaina** [comment]
大丈夫そう
