### ISSUE TITLE
「通知一覧をポップアップではなくページで表示できるように」が動いていない

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#6005]
## 💡 Summary

[ChangeLogのv12.16.0](https://github.com/syuilo/misskey/blob/develop/CHANGELOG.md#12160-20200219)に
> 通知一覧をポップアップではなくページで表示できるように
とあるが実装されていない

## 🙂 Expected Behavior

通知がページで表示される

## ☹️ Actual Behavior

通知がポップアップで表示される

## 📝 Steps to Reproduce

1. メニューから通知をクリック

## 📌 Environment

Misskey.io
Misskey v12.16.0

**Comment by u1-liquid** [comment]
FYI: サイドバーの下の「設定」に行って、「通知一覧をポップアップに〜」を無効にすると全体画面の通知一覧が見れます。

**Comment by SanMurakami** [comment]
> FYI: サイドバーの下の「設定」に行って、「通知一覧をポップアップに〜」を無効にすると全体画面の通知一覧が見れます。

そうChangeLogに書いて置かないとこれは気付かない
