### ISSUE TITLE
Notification not translated

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#6011]
## 💡 Summary

Text not translated in notification window

## 🙂 Expected Behavior

Translated text

## ☹️ Actual Behavior

Showing Japanese characters in notification window

![notification](https://user-images.githubusercontent.com/60059665/74799316-31adb700-529e-11ea-89b6-e09dfdff015c.jpeg)

## 📝 Steps to Reproduce

1. Sign in
2. Go to notification
3. View note

## 📌 Environment

v12.14

**Comment by tamaina** [comment]
Duplicate of #3100
