### ISSUE TITLE
フォローされた時の通知にフォロー解除のボタンが出るのはおかしい

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#6020]
## Summary

フォローされたときに既にフォローしている場合、フォロー解除するボタンが出てきてしまう
これだとまるで、フォローされたからフォローを解除しろみたいな表示に見えてしまう（偏見）ので、フォローしていない場合にのみフォローボタンを出したほうがいい気がする

![image](https://user-images.githubusercontent.com/37681609/74838837-9e40b880-5367-11ea-9982-7679089c5141.png)

**Comment by syuilo** [comment]
無くすとフォローしているかどうかぱっと見分かりにくくなりそう
フォロー解除のボタンを無くすより文言を「フォローしています」とかに変える方がよさそう
