### ISSUE TITLE
APIリファレンスがバグってる

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#6022]
## 💡 Summary
- メニューをクリックしても勝手に閉じる
- スクロールができない

![10aRuwqqfx](https://user-images.githubusercontent.com/37681609/74840849-10ff6300-536b-11ea-9a49-8f5eac992760.gif)
![ssaYhqXZbg](https://user-images.githubusercontent.com/37681609/74840855-12309000-536b-11ea-8b67-e961a58a8f96.gif)

## 🙂 Expected Behavior

かくのめんどくさい

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Misskey.io
Misskey v12.16.0

**Comment by SanMurakami** [comment]
備考: https://misskey.io/notes/83wy74f979
![image](https://user-images.githubusercontent.com/37681609/74841532-2aed7580-536c-11ea-9bfa-2f9d084a5c2e.png)

**Comment by mei23** [comment]
https://github.com/Redocly/redoc/issues/1170#issuecomment-584207228
> Use rc.23

https://github.com/syuilo/misskey/blob/e6c9b1d9bdd64270149cac3c8d0881d04b3edf7e/src/client/assets/redoc.html#L22
今CDNが`redoc@next`=>`2.0.0-rc.22`なので多分そのうちなおる

お急ぎなら Use Firefox

**Comment by mei23** [comment]
CDNのファイルが変わった (`redoc@next`=>`2.0.0-rc.23`) のでなおってるみたい
