### ISSUE TITLE
Cannot sign in from OAuth by using a web browser

### ISSUE THREAD

**Issue by veer66** [misskey-dev/misskey#6026]
## 💡 Summary

Cannot sign in from OAuth by using a web browser because usernane and password fields were not shown.

## 🙂 Expected Behavior

I should be able to type my username and password and sign-in.

## ☹️ Actual Behavior

The web page did not show usernane textfield,  password textfield, and sign-in button.

![ภาพ](https://user-images.githubusercontent.com/370688/74856321-87549300-5374-11ea-8596-309aa7a1f90a.png)

## 📝 Steps to Reproduce

1. Open Subway Tooter
2. Add an account
3.Type: cliq.social
4. Tap OK

## 📌 Environment

Android (MIUI 11.0.4)

**Comment by u1-liquid** [comment]
参考: 既にログインされている場合は問題ないけど、ログインしてない状態でauthページに行くとログイン画面が出てこない

**Comment by u1-liquid** [comment]
https://github.com/syuilo/misskey/blob/f456feb3ffa6acb043198664bcb44237c0519fc1/src/client/pages/auth.vue#L29

mk-signin ではなく x-signinにしないと
https://github.com/syuilo/misskey/blob/develop/src/client/components/signin.vue
