### ISSUE TITLE
引用RNフォームを開いた時だけ、textareaにフォーカスが当たっていない

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6029]
## 💡 Summary

引用Renoteのフォームを開いた時、フォーカスが一瞬だけtextareaに移動したかと思えばフォーカスを失ってしまう。そのため、文字を入力しようとしてキーボードショートカットが暴発するという恐ろしいことが起こる。

## 📝 Steps to Reproduce

1. 引用Renoteボタンを押す
2. H, Tなどを押す
3. キーボードショートカットが暴発する

## 📌 Environment
Misskey v12

**Comment by syuilo** [comment]
これ気付いてたけど対応が面倒そうだから放置してた🥴

**Comment by Oni-Men** [comment]
どっちを優先するか
- メニュー閉じたらノートにフォーカス(アニメーションで遅延発生)

- テキストエリアへのフォーカス

**Comment by tamaina** [comment]
「ノートにフォーカス」という機能自体個人的に不要だと思っています.....

**Comment by Oni-Men** [comment]
#6039 を修正すると投稿フォームを閉じた後にノートにフォーカスができます
ノートへのフォーカスが必要なら場ですけど

**Comment by syuilo** [comment]
ノートにフォーカスできないとキーボード操作が不能になる気がする

**Comment by tamaina** [comment]
あー、要らないと言いたいのは引用・返信・リアクション後のフォーカス
