### ISSUE TITLE
macOSのSafariでチャット画面に文字を入力すると文字数に応じてスクロールしてしまう

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#6032]
## 💡 Summary

macOS MojaveのSafari(詳細環境は後述)において、チャット画面に文字を入力すると入力した文字数に応じてスクロールしてしまう　

## 🙂 Expected Behavior

スクロールしない

## ☹️ Actual Behavior

スクロールする
![mazd4-cld6j](https://user-images.githubusercontent.com/28042693/74897729-4e9bd480-53db-11ea-93c3-dbdd6a354b8a.gif)

## 📝 Steps to Reproduce

1.Safariでv12インスタンスにログイン
2.チャットを開き、入力欄に文字を入力する
3.WOW!

## 📌 Environment

Misskey v12.18.0 / macOS Mojave Safari  13.0.5

**Comment by tamaina** [comment]
チャット廃止
