### ISSUE TITLE
Safari loses place in timeline when navigating back from note.

### ISSUE THREAD

**Issue by cortices** [misskey-dev/misskey#6033]
## 💡 Summary

When viewing a timeline, and then going to detail of a note (or note author), the only way to get back to the timeline is to use the browser back function (with swipe right gesture, or back button), There is no 'back' button within misskey to restore the view. in iOS Safari, going back with the browser causes the position on the timeline to be lost, reset to the top of the timeline. This makes it nearly impossible to catch up on notes from past time.

## 🙂 Expected Behavior

Going back with the browser should not lose the scroll position in the timeline (Safari normally restores scroll position when going back).

## ☹️ Actual Behavior

The timeline scroll position is reset at the top.

## 📝 Steps to Reproduce

1. Open timeline.
2. Scroll down some way.
3. Tap the date/time of a note to go to its page and view a thread or reply.
4. Go back to timeline with browser back button or swipe gesture.
5. Timeline page reappears scrolled to top, losing position.

## 📌 Environment

iOS Safari 13.3. Website pinned to home screen. Issue is the same in macOS Safari (Mojave).
Misskey 11.37.1
Endless loading feature is enabled.

**Comment by syuilo** [comment]
Thank you for reporting!
This problem has already been resolved in Misskey v12 :)
