### ISSUE TITLE
バックグラウンドで効果音をストックしない or 鳴らし続ける

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#6041]
## 💡 Summary

バックグラウンドタブを開いてしばらく放置していると、効果音がストックされていてってタブをアクティブにしたときに耳が死ぬ

## 🙂 Expected Behavior

バックグラウンドでそのまま再生 
or
バックグラウンドを検出して音が鳴らないようにする
(DMとか気付きやすくなるので鳴らしたままのほうがいい気がする)

## ☹️ Actual Behavior

バックグラウンドで効果音がストックされて、アクティブにすると耳が死ぬ

## 📝 Steps to Reproduce

1. グローバルとか開く
2. タブを非アクティブにする
3. しばらく待つ
4. タブをアクティブにする
5. 耳が死ぬ

## 📌 Environment
Misskey.io
Misskey v12.18.1
Chrome/80.0.3987.106

**Comment by syuilo** [comment]
バックグラウンドな時は効果音を鳴らさないような処理は入れてないからブラウザが勝手にそうしてるのかしら

**Comment by SanMurakami** [comment]
可能性はある
ちなみにChromeは長時間バックグラウンドで放置すると、JSの実行が1秒1回になったり色々ある

**Comment by syuilo** [comment]
バックグラウンドを検知して音が鳴らないようにすると、そもそも通知音はバックグラウンドにしてても通知に気付けるようにすることが主な目的で作ったから、本末転倒気味になる

**Comment by rinsuki** [comment]
ずっとバックグラウンドにしとくと音がキューに積まれて鳴らなくなるの、前世代のmisskeyからあるので、通知音が鳴り終わるまで次のを鳴らさないぐらいの対策しかできなさそう

**Comment by tamaina** [comment]
> バックグラウンドにしてても通知に気付けるように

あんまし関係ないけど、Page Visibility APIでクライアントが全部hiddenだったら通知を送信するようにすることで代替できそうではある（実装めんどい気もするが

**Comment by tamaina** [comment]
Visibility API関係ないわこれ

**Comment by syuilo** [comment]
多分 https://github.com/syuilo/misskey/pull/6853 で直る

**Comment by syuilo** [comment]
(一度作ったAudioインスタンスを使い回すようにしたから、再生が終わるまでは何回play()しようとも次の再生が始まらない)

**Comment by rinsuki** [comment]
それ流速早いときに通知音追い付かなくならない？

**Comment by syuilo** [comment]
音が重なるよりはマシだと思った

**Comment by Sayamame-beans** [comment]
triage: 恐らくもう起きていないと思われるのでCloseします。
