### ISSUE TITLE
Video Plays In New Window

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#6051]
## 💡 Summary

When playing a video, it opens a new window

## 🙂 Expected Behavior

Photos open in same window and have popup
Should be same for video

## ☹️ Actual Behavior

After you press play, it redirects to new page

## 📝 Steps to Reproduce

1. Upload video
2. Play video
3. Video opens new window

## 📌 Environment

12.19.0

**Comment by tateisu** [comment]
むしろブラウザのPIP機能に対応させるべきでは。
firefox https://support.mozilla.org/ja/kb/about-picture-picture-firefox
Chrome https://www.itmedia.co.jp/news/articles/1810/21/news008.html

**Comment by rinsuki** [comment]
ブラウザのPiP機能はすでにあるvideoをユーザー側で浮かせることしかできないので、まずどこかにvideo要素を置く必要がありそう (ポップアップなりインライン再生なりで)

**Comment by okpierre** [comment]
Adding video to explain the issue better @syuilo 

mastodon: video plays in pop up window (better user experience)

![mas](https://user-images.githubusercontent.com/1679025/85888341-6800c300-b7b7-11ea-83c4-97398148865e.gif)

misskey: video opens new tab window

![mis](https://user-images.githubusercontent.com/1679025/85888415-8bc40900-b7b7-11ea-8ec4-d8c547d39dca.gif)

**Comment by jorgesat** [comment]
This issue is still there in v12.47.1
