### ISSUE TITLE
ノートの詳細表示が投稿時間クリックなのは不便

### ISSUE THREAD

**Issue by Oni-Men** [misskey-dev/misskey#6053]
## Summary

リプライを見たいときにわかりにくくて苦労した。
下線が表示されるけどホバー時だけだし、普通は投稿時間にホバーしないと思うので。

リノートの解除とかも同じくだけどアクションがあることをわかりやすくしたいです。

**Comment by syuilo** [comment]
v11ではノートのメニューに「詳細を表示」というのがあったのでそれ復活させます
