### ISSUE TITLE
投稿ができなかったときにエラーを表示する

### ISSUE THREAD

**Issue by YuzuRyo61** [misskey-dev/misskey#6060]
## 💡 Summary

投稿を押しても何もエラーが出ないので原因特定が困難

## 🙂 Expected Behavior

投稿できなかったときにエラーダイアログなどを表示する

## ☹️ Actual Behavior

何も出ずに投稿されない。開発者ログには残る

## 📝 Steps to Reproduce

1.投稿フォームで何かしら入れる（削除された投稿に引用やリプで向ける）
2.投稿ボタンを押す

## 📌 Environment

Misskey: v12.19.0

**Comment by syuilo** [comment]
やった
