### ISSUE TITLE
ノート内での検索をした場合に検索ボックスの枠が表示されない

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#6069]
## 💡 Summary
![LSRYZENCapture572](https://user-images.githubusercontent.com/28042693/75097366-621e8980-55ed-11ea-8b6e-008b659a34ff.png)

> https://misskey.io/notes/841i6lowls

検索ボックスの枠が表示されない。デザイン上の話になるけど表示されるべきでは...?

## 🙂 Expected Behavior

枠が表示される

## ☹️ Actual Behavior

枠が表示されない

**Comment by KisaragiEffective** [comment]
triage: `2024.5.0-kinel.1` 及び `2024.5.0-io.1a` では再現できないためcloseします。

![image](https://github.com/misskey-dev/misskey/assets/48310258/71c85d07-feaf-4172-bd5d-b663d5e92284)
![image](https://github.com/misskey-dev/misskey/assets/48310258/77f95e0c-6472-4310-baa0-c8e51e8d04f3)
