### ISSUE TITLE
Firefox環境にてプルダウンメニューの色がおかしくなる

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#6070]
## 💡 Summary

![LSRYZENCapture573](https://user-images.githubusercontent.com/28042693/75097412-e3761c00-55ed-11ea-9744-88aea99fa1e2.png)
Firefox環境での現象。プルダウンメニューの配色がダークモードの場合は薄くて見づらい

## 📝 Steps to Reproduce

1.FirefoxでMisskey v12にアクセス
2.設定→テーマのプルダウンメニューからダーク系テーマに切り替える
3.再度プルダウンメニューを表示させる

## 📌 Environment

Misskey v12.21.0 / Firefox 73.0.1 for Windows で確認

**Comment by robflop** [comment]
Vivaldi Browser 2.11.1811.38 (クロムベース)の類似の問題
