### ISSUE TITLE
ドキュメントのストリーミングAPIの解説が不完全

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6073]
mainチャンネルに存在するmessagingMessageタイプが書かれていないのを発見した  
他にもありそうな気配がする

**Comment by 4ioskd** [comment]
@tamaina 
何度もすみませんが、以下のしゅいろ氏が misskey-hub で書いた文章でどうでしょうか。
https://misskey-hub.net/docs/api/streaming/

**Comment by tamaina** [comment]
いい感じだと思う
