### ISSUE TITLE
Untranslated Dropdown item in Note context menu

### ISSUE THREAD

**Issue by robflop** [misskey-dev/misskey#6075]
## 💡 Summary

When opening the context Menu for individual Notes, the topmost item ("Details") is untranslated (and has no Crowdin translation string to translate it)

## 🙂 Expected Behavior

The topmost dropdown item should have a Crowdin Translation string so that it may be displayed in the language of the user's choice.

## ☹️ Actual Behavior

The topmost dropdown item is not translated.

## 📝 Steps to Reproduce

1. Go to any Misskey Note
2. Press the context menu button (rightmost, 3 dots)
3. See untranslated item

Image:  

![vivaldi_2020-02-23_21-08-58](https://user-images.githubusercontent.com/8159402/75119169-b888d800-5680-11ea-8e40-554efccaf5a9.png)

## 📌 Environment

Misskey 12.21.0
All browsers

**Comment by mei23** [comment]
Will be fixed in #6062

**Comment by SanMurakami** [comment]
Closeで良さそう
