### ISSUE TITLE
アカウント設定からアイコンのアップロードが使用できなくなっている

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#6076]
## 💡 Summary

アカウント設定からアイコンの部分をクリックして新しいファイルをアップロードすることができない

## 📝 Steps to Reproduce

1.左上のアイコンをクリックしてアカウント設定を開く
2.アイコンの部分をクリックしてアップロードをクリック
3.画像を選択してもアップロードが行われていない

## 📌 Environment

Misskey 12.21.0

**Comment by syuilo** [comment]
WindowsのChromeでは再現できなかった

**Comment by tkmrgit** [comment]
追加 : 再現可能ブラウザ
Firefox 73.0 / 同Mobile
iOS 12.4.1 / 13.3.1 Safari

**Comment by syuilo** [comment]
謎

**Comment by syuilo** [comment]
発生条件もよくわからない
iOSでも発生する時としない時がある

**Comment by u1-liquid** [comment]
Android 10
Chrome Dev 82.0.4085.12
Firefox Beta 68.7b1
両方で再現されなかった

**Comment by syuilo** [comment]
うーーーーん
再現が難しい

**Comment by syuilo** [comment]
原因はなんとなくわかっていて、おそらくDOMに即席で`document.createElement('input');`みたいにして作ったinputは、clickイベントを発火させられないみたいな制約がiOSにあるみたいな感じだと思う

**Comment by syuilo** [comment]
そうだとして、じゃあどうやって解決する？というのが...

**Comment by syuilo** [comment]
PCからファイルを選択する関数は、Misskeyの様々な個所から呼ばれる可能性があるので、あらかじめVue上にinput要素を作っておくとかはできない

**Comment by acid-chicken** [comment]
input 要素のスタックみたいなところに二つストックしておいて、使われたらスタックに要素を一つ足してみたいなことをすれば回避できそう？
