### ISSUE TITLE
同じアカウントが同じ投稿を繰り返しRenoteすることでRenote数のカウントが増えてしまう

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#6079]
## 💡 Summary

>やばい、誰に言っていいかわからんけど自分で何度もRNすればカウント稼げる
>https://misskey.io/notes/842ogsf04a

### 参考ノート

>https://misskey.io/notes/843xarvo4l

↑本人曰く、誤操作によるものとのこと

## 🙂 Expected Behavior

Renote数の表示をアカウント単位で表示する

## ☹️ Actual Behavior

Renote数がRenoteされた数を基準に動いている

**Comment by mei23** [comment]
Renoteが複数できる仕様な以上、RenoteされただけRenote数が増えるのは問題なくて
ハイライトの算出に使用される`score`が増えるのが問題なのではと。

`score`は、Reaction+Renote+Quoteだけど
Reactionだけする人間と 必ずRenoteもする人間がいるからブレが出るし
QuoteはカウントするのになんでReplyはカウントしないの？(QuoteもReplyも同じ用に投稿詳細ぶら下がるのに) という気もするので
`score`は単純にReactionだけカウントとかでもいいんじゃないかなと思いました。

**Comment by Oni-Men** [comment]
> `score`は単純にReactionだけカウントとかでもいいんじゃないかなと思いました。

これに賛成です。理由は
-  Reactionなら一人一つだし変更が少ない
- ハイライトに上がってるノート大体、RN数 < リアクション数 なので結果が今までと近くなる(たうぶん)

**Comment by tkmrgit** [comment]
Misskeyはリアクション数だけでも十分なscoreが獲得できるかもしれないけど、Fediverse全体だとRenote(ブースト等...)しかしない人もそれなりにいるのでRenote数考慮は一応はして欲しいかなぁ

**Comment by mei23** [comment]
Reactionだけ集計だと
今は取得していないけど、リモートの投稿を集計しようとすると
Mastodonからされた分が集計出来ないというのはあります。

**Comment by syuilo** [comment]
score計算をどうするかは別にして、とりあえずRenoteカウントは「何回Renoteされたか」ではなく「何人にRenoteされたか」で良いと思いました
一人何回でもRenoteできる以上、何回Renoteされたかという情報にそんなに価値が無いと思うので

**Comment by syuilo** [comment]
でも返信も「何人」ではなく「何回」だからその点を考えると返信とRenoteでカウント方法が異なるのも気になる
