### ISSUE TITLE
タイムラインウィジェットの数が多ければ多いほど、リアクションが多く付いて見える

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6080]
## 💡 Summary

タイムラインウィジェットを多く置くと、ストリーミングで流れてきたリアクションがタイムラインウィジェットの数+1個分多く表示されてしまう

例えば、ウィジェット3つで、リアクションが4倍表示される

## 📝 Steps to Reproduce

1. タイムラインウィジェットを増やす
2. リアクションを付けてもらう

## 📌 Environment

Misskey v12

**Comment by syuilo** [comment]
むむむ

**Comment by syuilo** [comment]
謎

**Comment by syuilo** [comment]
謎

**Comment by syuilo** [comment]
たすけて

**Comment by mei23** [comment]
わかった

**Comment by mei23** [comment]
ホームTLなどの同種のTL同士において、StreamからPushされたNoteにリアクションや投票された場合に起きます。

同種のTLが複数ある場合、
APIでPullした場合、note Objectはそれぞれで独立ですが、
StreamでPushされた場合、note Objectはそれぞれで共有になります。(timeline Componentの sharedConnection:homeTimeline とかの単位で共有)

一方、note Componentは常に独立なので、
それぞれのnote Componentがnoteをwatchする
→ それぞれリアクションを受信する
→ 共有しているnote Objectをそれぞれでインクリメントするが起きてしまいます。
