### ISSUE TITLE
画面が小さいとメニューがすべて見えない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6085]
## 💡 Summary
![image](https://user-images.githubusercontent.com/7973572/75240717-24497d00-5808-11ea-9cf8-0ba9b08c3d07.png)

**Comment by tamaina** [comment]
クライアント設定、左下ではなくアカウントメニュー内に設置したさがある

**Comment by syuilo** [comment]
> クライアント設定、左下ではなくアカウントメニュー内に設置したさがある

非ログイン時にクライアント設定を行えなくなりそう
