### ISSUE TITLE
Upload from URL does not work

### ISSUE THREAD

**Issue by robflop** [misskey-dev/misskey#6090]
## 💡 Summary

When writing a new note, trying to upload a file from a URL outputs an error message in the browser developer console. 

## 🙂 Expected Behavior

A form to enter an URL from which to upload the file should appear.

## ☹️ Actual Behavior

Nothing happens, error in browser developer console.

## 📝 Steps to Reproduce

1. Try to write a new note
2. Click on Upload file and then upload from url
3. Look at developer console and see error

![vivaldi_2020-02-25_20-24-15](https://user-images.githubusercontent.com/8159402/75279949-d420e980-580c-11ea-87ec-4fe2dfdac62a.png)

## 📌 Environment

- Likely all browsers, tested: Vivaldi 2.11.1811.41 (Chromium based) and Firefox 73.0.1
- Misskey v12.21.0 (Misskey.io)

**Comment by u1-liquid** [comment]
FYI: Currently this function is not implemented 🤯

**Comment by robflop** [comment]
Oh! I did not know that, sorry. I will close this issue then.

**Comment by u1-liquid** [comment]
This is still valid bug, till it is correctly implemented😱

**Comment by robflop** [comment]
Reopening this then. Apologies for being so awkwardly hasty 😅.

**Comment by Ai-rin** [comment]
I've stumbled on this one, too :) Good to know it's known issue.

**Comment by robflop** [comment]
このバグは12.47.1にまだ残ってる

**Comment by Ai-rin** [comment]
Can I embed external image to a note manually? Is there any syntax for that?

**Comment by robflop** [comment]
I don't think such functionality (such as in Pleroma for example) exists yet. I assume you mean syntax like \[text\]\(link\), right? It would be a good suggestion though, maybe open it as separate feature request?

**Comment by Ai-rin** [comment]
Yep, something like `[text](link)` or `[img] [/img]` etc.

**Comment by syuilo** [comment]
このバグは現在実装中の新UIで修正します💪

**Comment by robflop** [comment]
ありがとう！

**Comment by syuilo** [comment]
FYI, なぜこの機能が動作しないのか簡単な説明:
実は、Misskeyのサーバー自体にはURLアップロードAPIがあり、機能します（ドライブで実際にその機能が使えます）
しかし、ドライブとは違い、新しいノートを作成するときは、アップロードされたファイルをクライアントが受け取る必要が生じます(ノートに添付できないため)。
URLアップロードAPIは、リクエストを受け付けると、指定のURLから画像のダウンロードを開始しますが、ダウンロードの完了を待つことなくクライアントに「成功」レスポンスを返します。つまり、クライアントからはダウンロードされたファイルを受け取る方法が今のところありません。
したがって、アップロードされたファイル情報を受け取る何らかの方法を考え、実装するまではこのバグは簡単には直せません。

**Comment by syuilo** [comment]
> アップロードされたファイル情報を受け取る何らかの方法

現在このような方法を考えています:
1. URLアップロードAPIは、URLのほかに、任意のIDを受け付けるようにする
1. クライアントは、URLアップロードAPIにIDを生成してURLと一緒にリクエストする
1. URLアップロードAPIは、ファイルのダウンロードが完了して、ドライブにファイルを追加するときに、そのIDをファイルに追加する
1. クライアントは、「ドライブにファイルが追加された」イベントは受け取ることができるので、追加されたファイルがリクエストしたときに付けたIDと同じIDが付いていれば、追加されたファイルがリクエストしたファイルだと判定することができる
1. クライアントはそのファイルをノートに添付したりできる

NOTE: 「ドライブにファイルが追加された」イベントが受け取れるなら、IDで識別する必要がないように思えるかもしれませんが、ドライブにファイルが追加されることは様々なソース(ユーザーが手動でアップロード、サードパーティサービスからアップロードなど)から行われる可能性があるので、新たに追加されたファイルが必ずしもAPIにリクエストしたファイルとは限りません。
