### ISSUE TITLE
v12: ワードミュートの再実装

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6092]
無くなっていたので

**Comment by syuilo** [comment]
クライアントサイドではなくてサーバーサイドで実装したいけど、面倒そう

**Comment by syuilo** [comment]
SQLでやるのは重そうだから一旦普通にクエリして、その中にミュートにマッチするノートが含まれていたらそれを捨てて、足りにゃくにゃった分さらにクエリして持ってくる、という処理を繰り返していくのが良いのかにゃぁ

**Comment by rinsuki** [comment]
それでもミュートしまくってるとクエリ発行回数が無限になって終わりそう

**Comment by syuilo** [comment]
除外するのではなくて、CWにするというのが良さそう

**Comment by EbiseLutica** [comment]
現在実装中の仕様では、足りなくなった分をクエリするのも微妙だなあって思ってそのまま弾いてしまっています。数が揃わないと微妙だなあとは思うものの割り切っても問題ないような気がしています

**Comment by tamaina** [comment]
#6149 での発言引用…

> なんか私の考える良い感じの実装が見えてきたので私が適当に実装するかも  
> 一応私の考えとしては
> 
> - UserProfileにミュートワードカラム追加で良さそう
> - ワードミュートで引っかかったノートにはisMuted: trueを追加してクライアントサイドで非表示
> - isMuted: trueに対応していないサードパーティクライアントのことを考えて強制CWもする
> 
> https://github.com/syuilo/misskey/pull/6149#issuecomment-603844627

**Comment by tamaina** [comment]
私も↑の方針が合理的だと思うのですが、実装はいつになるのでしょう？

わりと使われている機能なので、従来通りのクライアントサイドでの実装で実装を早くした方が良いという考え方も出てきています。

**Comment by syuilo** [comment]
クライアントが複雑になることを考えると、やはりどうしてもサーバーサイドでやりたいので、サーバーサイドで上手いことできないか検討してみて無理そうだったら https://github.com/syuilo/misskey/issues/6092#issuecomment-616164134 でやる

**Comment by syuilo** [comment]
あー、クライアントにしろサーバーにしろ、ミュートされたノートがあると「あなた宛」とかで未読のノートがあると判定されたりする問題が出てくるな
解決策としては、ミュートをアンテナみたいな処理にすれば良さそう
つまり、あるノートが作成されると、全ての(ミュートが設定されている)ユーザーに対してそのノートがミュート対象かどうか判定する処理を行い、対象だったらMutedNotesみたいなテーブルにレコードを追加する。タイムライン取得時などは、そのレコードに入ってないノートのみにフィルタリングすれば良い。これはクエリのみで完結できる。
あなた宛に未読があるかどうかも、クエリでMutedNotesを参照してフィルタリングして判定すればよい。
また、この方法なら手動で「このノートをミュートする」のような機能(https://github.com/syuilo/misskey/issues/2227 )も実装可能になる。
さらに、この方法だとスパムと思われるメッセージを自動でフィルタリングするような、将来的に必要になると思われる機能の実装も容易になる。
他にはこの機能に付随して、アンテナごとにワードミュートを適用するかどうかの設定や、メーラーが迷惑メール一覧を見れるようにミュートされたノート一覧を見れる機能とかも実装すると良さそう

**Comment by syuilo** [comment]
↑の方法で、なにか懸念点とか有れば教えてください
アンテナと同様、ワードミュート設定しても過去のノートには適用されないのは留意点ですが、そこまで問題にはならなそう。

**Comment by tamaina** [comment]
> ワードミュート設定しても過去のノートには適用されないのは留意点ですが、そこまで問題には

対策しないとわりと問題になる気がするわね……ワードミュートって、めっちゃRenoteされるミーム的なノートをミュートするのにも使うと思うから。  
対策として、Renoteやリプライに遡ってMutedNoteかどうかを判定したり、#2227 を実装したりすればあまり問題にならなさそう

**Comment by syuilo** [comment]
ただやっぱり、すでにタイムラインにある、またはこれから遡っていくノートにも適用されて欲しいので、ソフトミュートとハードミュートという概念に分けようと思う

ソフトミュート … タイムライン取得時にフィルタリングする(多分クエリで)。これなら過去のノートもフィルタリングされる。クエリで実現することになると予想されることから、パフォーマンスを考えておそらくキーワード指定のみ。
ハードミュート … MutedNotesにレコード追加。過去のノートには適用されないが、ソフトミュートと違い、正規表現やAiScriptも使えるようにすることができる。

**Comment by syuilo** [comment]
もしかしたら↑のソフトミュートの実装方法では重いかもしれない。そしたらソフトミュートはいつか言及したように「isMuted: trueを追加してクライアントサイドで非表示」にするしかない(そうしたらソフトミュートでも正規表現やAiScriptも使える)

**Comment by syuilo** [comment]
ソフトミュートは全部クライアントでやっちゃう手もある
