### ISSUE TITLE
リストタイムラインがミュートを考慮仕切れていない？

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6093]
## 💡 Summary

リストタイムラインに、ミュートされたユーザーの投稿を含む投稿が流れてくる

以前通常タイムラインで流れなくなったものがリストでは依然流れる？

## 📌 Environment

Misskey v12

**Comment by mei23** [comment]
リストのstreamだけミュート情報が自動更新じゃなかったのでそれではと

自動更新は修正済み
https://github.com/syuilo/misskey/pull/6072

**Comment by Oni-Men** [comment]
[`src/server/api/endpoints/notes/user-list-timeline.ts`](https://github.com/syuilo/misskey/blob/develop/src/server/api/endpoints/notes/user-list-timeline.ts)でも対策しないと流れるかも

**Comment by tamaina** [comment]
リノートのミュートも考慮されていない

**Comment by tamaina** [comment]
user-list-timelineエンドポイントだけ漏れてるのか

（どうしてミュートクエリが適用されていないのかよくわからないので手出しに躊躇するけど

**Comment by tamaina** [comment]
Duplicate of #10443

**Comment by acid-chicken** [comment]
（逆じゃねと思ったけどまぁいいか）
