### ISSUE TITLE
連携アカウントでのログインができない

### ISSUE THREAD

**Issue by nafu-at** [misskey-dev/misskey#6094]
## 💡 Summary

Misskeyアカウントに紐付けられた連携アカウントでログインを行うと500 Internal Server Errorが発生する。 (Twitter, Discord, Github 全て同様)

## 🙂 Expected Behavior

紐付けられたアカウントにログインされる

## ☹️ Actual Behavior

サーバーエラーが発生しログインが出来ない

## 📝 Steps to Reproduce

1. アカウントに連携アカウントを紐付ける
2. 一旦ログアウトする
3. 紐付けた連携アカウントでログインを試みる

## 📌 Environment
Misskey v12.21.0  
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:74.0) Gecko/20100101 Firefox/74.0

**Comment by EbiseLutica** [comment]
おそらく #6000 に関連しています

アカウントを複数追加していなくても起こりますか？

**Comment by nafu-at** [comment]
そのアカウントのみがログインされている状況で紐付けを行いきちんと反映されているようです。  
設定を行ったものとは別のブラウザでIDが表示されている事を確認しました。

インスタンス側のエラーログを確認すると、連携アカウントを用いてログインを試行した場合に  
`QueryFailedError: column "twitter" does not exist` が発生することを確認しました。

**Comment by mei23** [comment]
少なくとも3つくらいおかしいところあり。

1. /??/cb が
iのCookieを持っているかどうかで「接続」or「ログイン」を分岐しているが
v12でログアウト時にiのCookieを消す処理がなくなったので
連携ログインしようとすると「接続」の処理に入ってしまって`invalid session`になる

2. iのCookieが消されていて、1が解消されてる状態でも`500 Internal Server Error`になる。
   たぶん上に書かれている事象だけど謎。

3. また、連携ログイン後はiのCookieが設定されてクライアントがCookieの値を拾うようになっていたが、v12でCookieの値を拾う処理が消えているので、1, 2まで解消されても動かない気がします。

**Comment by mei23** [comment]
2はJSONクエリの書き方が間違っていた
