### ISSUE TITLE
引用符内でNyaizeを無効化する

### ISSUE THREAD

**Issue by nafu-at** [misskey-dev/misskey#6107]
## Summary

日本の著作権法では原則著作物の無断改変は認められていないため、法律の遵守や引用の性質の観点からMFM構文の引用内ではNyaizeが自動的に無効化される等の機能があると良いと思います。

**Comment by mei23** [comment]
そのtextノードがquoteの下かどうかを感知していない
https://github.com/misskey-dev/misskey/blob/27c373ddf4516166d43d3f3c56870cb30048af94/src/models/repositories/note.ts#L225-L233
