### ISSUE TITLE
ユーザーサジェストはアクティブ順などで並べ替えて表示するようにしてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6110]
## Summary
現状の実装だと何のソートもしていないため、インスタンスへの登録順で出てきて、基本的に一番メンションしたい人が最後のほうに出てくるようになってきてしまっているので不便

**Comment by syuilo** [comment]
なんか上手く動作してない気が

**Comment by mei23** [comment]
sessionStorageでしてるキャッシュのせいとか

**Comment by syuilo** [comment]
あー

**Comment by syuilo** [comment]
> sessionStorageでしてるキャッシュのせいとか

これもありました
でもそもそもソートが逆になってそう？

**Comment by mei23** [comment]
updatedAt: null が上に来てそう

**Comment by syuilo** [comment]
なるほど
