### ISSUE TITLE
自分宛てではないダイレクト投稿にリアクションを付けられる

### ISSUE THREAD

**Issue by kotodu** [misskey-dev/misskey#6127]
## 💡 Summary

自分がリアクションをつけた他人の投稿に対し、通知欄に自分宛てではないダイレクト投稿が表示されてしまう。そこからリアクションを付与することが可能。

## 🙂 Expected Behavior

- 自分宛てではないダイレクト投稿が見えてしまうのを修正？
- リアクションを付けてしまえることの是非は検討？

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

Firefox

**Comment by kabo2468** [comment]
Related to #5296
