### ISSUE TITLE
chartでhourだけ記録するようにする

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#6139]
## Summary

理論的には、hourだけ記録していればdayのチャートも生成できる。
ただ面倒そう

メリット:
* 記録時の負荷が単純に考えて半減する
* データベースサイズを減らせる

デメリット:
* 無い。強いて言うなら集計時のパフォーマンスが多少悪化するかもしれない

**Comment by syuilo** [comment]
パフォーマンスはまあ大丈夫かなとは思う
むしろ記録時の負荷が単純に考えて半減するからそっちのメリットの方が大きそう

**Comment by syuilo** [comment]
んー、でも将来的に分単位での粒度を提供したくなったときに、この方法だと1年分のデータ取得に525600件のレコードを持ってくる必要が生じてキツそう(現在の実装なら365件で済む)

**Comment by rinsuki** [comment]
一日一回その日の分のレコード作るとか

**Comment by syuilo** [comment]
あーそういう手もあるか

**Comment by syuilo** [comment]
他にも良い方法はありそうなのでとりあえずOpenしておく

**Comment by syuilo** [comment]
> んー、でも将来的に分単位での粒度を提供したくなったときに、この方法だと1年分のデータ取得に525600件のレコードを持ってくる必要が生じてキツそう(現在の実装なら365件で済む)

その必要が生じたときにまた考えればよいと思うので、とりあえず実装する
https://github.com/syuilo/misskey/pull/7360

**Comment by SanMurakami** [comment]
> > んー、でも将来的に分単位での粒度を提供したくなったときに、この方法だと1年分のデータ取得に525600件のレコードを持ってくる必要が生じてキツそう(現在の実装なら365件で済む)
> 
> その必要が生じたときにまた考えればよいと思うので、とりあえず実装する
> #7360

サーバー統計が遅いと指摘が入りました
https://forum.misskey.io/d/8-instance-statistics-page-slow

**Comment by syuilo** [comment]
まだ現在の実装では一年分のデータ取得には8760件のレコードを持ってくるだけなので、なぜ遅いか謎

**Comment by syuilo** [comment]
8760件のレコード取得遅いかな

**Comment by SanMurakami** [comment]
![image](https://user-images.githubusercontent.com/37681609/114261828-bfef7a00-9a17-11eb-813f-a27749c257e4.png)
ioの変態スペックでも11秒とか掛かってるし普通のサーバーにはかなり厳しいかも？
