### ISSUE TITLE
オブジェクトストレージの設定でポートの指定が効かない

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#6142]
## 💡 Summary
![image](https://user-images.githubusercontent.com/37681609/76154981-d4808500-6128-11ea-822d-a35b8e35ba02.png)

エンドポイントに直接指定したら一応設定できるけど、ポートの欄を変更してもSSLありなら443、なしなら80に固定される

v11でもなったので結構前からあるバグっぽい

## 🙂 Expected Behavior

ポート指定欄のポートに接続する

## ☹️ Actual Behavior

SSLありなら443、なしなら80に固定される

## 📝 Steps to Reproduce

1. 管理権限を持つアカウントでログイン
2. オブジェクトストレージの設定でポートを指定

## 📌 Environment
Misskey.io v12.21.0
Misskey.dev v11.37.1

Linux Chrome/80.0.3987.132 64bit

**Comment by rinsuki** [comment]
動きそうなもんだけどなー 謎
https://github.com/syuilo/misskey/blob/db01fa0eefe22e21abc5ddbe727e99b796155077/src/services/drive/s3.ts#L14-L23

**Comment by SanMurakami** [comment]
よくわからんけど、これのコードにポート番号含まれてなくない？

metaにはobjectStorageEndpointと別にobjectStoragePortがあるように見えるけど、どこかで統合されてる？
https://github.com/syuilo/misskey/blob/db01fa0eefe22e21abc5ddbe727e99b796155077/src/models/entities/meta.ts#L319-L347

**Comment by rinsuki** [comment]
port欄が無視されているだけでスクリーンショットのようにhost:portで書けば動きそう port欄はいっそのことなくしてhost:portで書かせるようにしてもいいかもしれない

**Comment by rinsuki** [comment]
それはそれとしてこの画面初見だと記法がわからないのでplaceholderとかがあるとよさそう
