### ISSUE TITLE
一定以上の種類のリアクションが付いている場合はデフォルトでは表示せずに隠す

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#6144]
## Summary

~~>マジで激重~~
~~>https://misskey.io/notes/84jigrw43l~~
※アプリの話なので取り消し

>https://misskey.io/notes/7zzafqsm9a

大量にリアクションが付いている投稿には大量にリアクションが付いている状態で表示されてしまう。5種類?か10種類リアクションがある場合はそれ以上は・・・等で隠して読み込まないようにすると軽くなる？のではないでしょうか。

**Comment by rinsuki** [comment]
これmisskeyの標準UIじゃなくない?自作アプリの話では

**Comment by tkmrgit** [comment]
> これmisskeyの標準UIじゃなくない?自作アプリの話では

ありがとうございます。確かにMisskey本体はこんな機能付いてなかった。 内容修正します

**Comment by Johann150** [comment]
I think if we hide some reactions there should also be a way to see all reactions. Maybe add a menu option to show all reactions which would open a dialog with a list. (I think Discord does something similar)

**Comment by tamaina** [comment]
やる 16種類ぐらいでいいかな

**Comment by syuilo** [comment]
そもそもn種類以上のリアクションを付けられないようにしても良さそうだけどリモートからのリアクション考えると微妙かも
