### ISSUE TITLE
Notes from users on other instances not being synchronized

### ISSUE THREAD

**Issue by Sorixelle** [misskey-dev/misskey#6150]
## 💡 Summary

Let's say User A is a member of Instance 1, and User B is a member of Instance 2. If User A attempts to view User B's profile from Instance 1, none of User B's notes appear, except for pinned notes. If User A follows User B, and waits for User B to post a new note, then this new note is visible from Instance 1.

## 🙂 Expected Behavior

All of User B's notes should be visible from Instance 1, regardless of when the notes were posted, or if User B is being followed by someone on Instance 1.

## ☹️ Actual Behavior

User B's notes do not appear when their profile is viewed from Instance 1, until they are followed by a user on Instance 1. Once User B has been followed, only notes posted after they were followed will be visible from Instance 1.

## 📝 Steps to Reproduce

1. Set up users on 2 Misskey instances that have not talked to each other in the past.
2. Post some notes on one of the users.
3. View the profile of the user from step 2 from the other user's instance. No notes will be shown.
4. Follow the user that was viewed.
5. Post some more notes from the viewed user.
3. Repeat step 3. The notes posted after the user was followed will appear, but no older ones.

## 📌 Environment

OS: Debian 10
Node version: 12.16.1
PostgreSQL version: 11.7
Redis version: 5.0.3
Misskey version: 12.21.0

**Comment by u1-liquid** [comment]
This is normal behavior. We don't have any information even there is notes, followings, followers exists if user was never seen before, or the notes wasn't delivered from remote server.
This limitation is ActivityPub's limitation, so every(e.g Mastodon) ActivityPub implementation would have same problem.

**Comment by Sorixelle** [comment]
Ah, ok. Sorry for the misunderstanding ^^'
