### ISSUE TITLE
Huge black object in background with Falkon (QtWebEngine browser)

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#6152]
## 💡 Summary
There is a huge black bad thing at the "top" of the page.
I did a little investigation and it should be caused by css option:
`backdrop-filter: blur(32px);` at header.
When this option is disabled the huge black bad thing is gone.

## 🙂 Expected Behavior
No huge black bad thing on the page
![Screenshot_2020-03-11_20-36-40](https://user-images.githubusercontent.com/6304663/76456952-30246a00-63d8-11ea-88a4-0870d3911ee0.png)
PS: maybe ads should be in that place? no idea.... just checked the page once and went to report.

## ☹️ Actual Behavior
Huge black bad thing on the page.
![Screenshot_2020-03-11_20-36-04](https://user-images.githubusercontent.com/6304663/76456911-200c8a80-63d8-11ea-88fe-e1cdd1adf4fd.png)
PS: I overdid this screenshot a bit.

## 📝 Steps to Reproduce

1. Open page in Falkon (QtWebEngine based browser)
2. Go to https://miss.jaekr.sh/
3. Observe

## 📌 Environment
Web browser: Falkon
Application version 3.1.99 (e4b468e2)
QtWebEngine version 5.14.1
Operating System: Artix Linux 
Qt Version: 5.14.1
Kernel Version: 5.4.22-1-lts
OS Type: 64-bit

**Comment by tamaina** [comment]
This issue is probably due to a bug from Qt WebEngine. Could you report this bug to the Qt project?

**Comment by ghost** [comment]
> Could you report this bug to the Qt project?

Will check and do.

Done,
https://bugreports.qt.io/browse/QTBUG-82842?jql=text%20~%20%22backdrop%22
Please go and provide more information if you know, want and can.

**Comment by tamaina** [comment]
Qt v5.15.0 Beta3で修正がマージされたみたい  
https://bugreports.qt.io/browse/QTBUG-82842  
https://codereview.qt-project.org/c/qt/qtwebengine/+/294655

**Comment by ghost** [comment]
Hello,
Fixed in Qt 5.15.
