### ISSUE TITLE
MFMの検索構文の表示が壊れている

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6159]
## 💡 Summary
![image](https://user-images.githubusercontent.com/7973572/76703167-f5416f80-6712-11ea-920f-81ff66cd39fe.png)

1. CSS変数(google...)が存在しないために、色の指定が壊れている
2. 横幅の最小幅が指定されている(？)

## 📌 Environment
Misskey v12.21.0

**Comment by syuilo** [comment]
多分developでは直ってます

**Comment by tamaina** [comment]
なるほど

そろそろリリースきって♥
