### ISSUE TITLE
文字列検索機能でAND・ORを使えるようにしてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6160]
## Summary
半ば必須かもしれない

**Comment by tamaina** [comment]
age

**Comment by Johann150** [comment]
I'm not sure how it could be differentiated between when I am searching for text that contains "AND"/"OR". Maybe an advanced search mode would be necessary.

**Comment by futchitwo** [comment]
ioには色々実装されてる(ただしLIKE検索が封じされてる)
https://github.com/MisskeyIO/misskey/blob/io/packages/backend/src/server/api/endpoints/notes/search.ts

公式インスタンスであるioでは使えるのに他では使えないのはどうかと思うので、ioと同等の検索クエリはあったほうがいいと思う

**Comment by Johann150** [comment]
The search syntax looks similar to GitHub search, interesting idea. 👍

I don't understand what the [`&@~` operator](https://github.com/MisskeyIO/misskey/blob/ba40208539d9063e26e776e9a60ae685a7fd8552/packages/backend/src/server/api/endpoints/notes/search.ts#L100) is supposed to do. I could not find it anywhere else in the code, or in Postgres or TypeORM documentation...

**Comment by rinsuki** [comment]
it comes from PGroonga? https://pgroonga.github.io/reference/operators/query-v2.html

**Comment by Johann150** [comment]
I'm not sure PGroonga is something we could add as a dependency. But I wonder if some pieces of the search syntax could be transformed into a Postgresql style regular expression.

**Comment by tamaina** [comment]
FYI: How to install PGroonga and &@~ patch: https://hide.ac/articles/DjGNSvW4G

**Comment by tamaina** [comment]
Adding PGroonga as a dependency complicates the installation process.

**Comment by tamaina** [comment]
PGroongaと言ってたけどGroonga単体で使ってもいいじゃんという発想をした

**Comment by tamaina** [comment]
（とはいえRust製のMeilisearchのほうが現代的なのは明らか

**Comment by tamaina** [comment]
ORできるよね…？

**Comment by tamaina** [comment]
ORできない？

**Comment by syuilo** [comment]
できないかも
