### ISSUE TITLE
"Something Happened :(" when creating account on misskey.io

### ISSUE THREAD

**Issue by BurnyBoi** [misskey-dev/misskey#6163]
## 💡 Summary

Unable to create an account on misskey.io. Every time, it says "Something Happened :(". I've tried using a Firefox profile with no addons installed and all default settings. 

## 🙂 Expected Behavior

User registration should be successful

## ☹️ Actual Behavior

Screenshot of the error:

![2020-03-17_07-38-28_542x439_scrot](https://user-images.githubusercontent.com/41203525/76853008-e518b580-6822-11ea-852e-3bbe6da34c9a.png)

## 📝 Steps to Reproduce

1. Click Sign Up on misskey.io
2. Fill out a username, password, and recaptcha
3. Click Begin

## 📌 Environment

Firefox 72 on misskey.io

**Comment by q-TheDog** [comment]
I got a registration to work, but if I try again this error still happens more often.

**Comment by u1-liquid** [comment]
This is not a Misskey's issue.
Misskey.io does not allows frequent account creation.

**Comment by KisaragiEffective** [comment]
Please do not report about Misskey.io-specific issue to this repository. misskey-dev do not provide support on the specific server.

**Comment by Borkius** [comment]
Where then?

**Comment by KisaragiEffective** [comment]
One of the best way is contacting their support. And at least, not us. misskey-dev do not control specific server.
