### ISSUE TITLE
Bad @instance name with Glitch to Misskey

### ISSUE THREAD

**Issue by kazukyakayashi** [misskey-dev/misskey#6177]
Hi,

From Misskey (11.37.1), when a person under Glitch-Soc writes a message or answers me, the name of the instance of the people in the conversation is automatically replaced by the name of the person under Glitch.

Reply example, (me on Misskey : @meow.zarchbox.fr)
![glitch-soc-bug](https://user-images.githubusercontent.com/39823221/77244547-31466a00-6c16-11ea-94c5-c4f3551f87b9.JPG)

This problem only occurs with people under Glitch-Soc, no problem with Mastodon, Pleroma, Hubzilla or other social platform.

Issue on Glitch-Soc : https://github.com/glitch-soc/mastodon/issues/1304

**Comment by mei23** [comment]
```
<a href="..." class="u-url mention" rel="nofollow noopener tag noreferrer" target="_blank">
```
みたいに、`rel=tag`なものがHashtag扱いされてしまう。

たぶん`tag = Hashtag | Mention`なので`tag`見てHashtagを判定するのが正しくないのかも。

しかし、`rel=tag`を採用しないようにするとMisskeyのHashtagが認識できなくなってしまう。

contentのHTMLタグの属性を見るのではなく

APの`tag`の`name`にあるかどうか見たほうがいいかも
```
  tag: [
    {
      type: 'Mention',
      href: 'https://example.com/users/user',
      name: '@user@example.com'
    },
    {
      type: 'Hashtag',
      href: 'https://example.com/tags/tag',
      name: '#tag'
    },
```

**Comment by mei23** [comment]
でもこれ content <=> tag ってマッチ不可能では
```
content: <a href="https://example.com/@User">@User</a>
```
hrefはurl, textはホスト名が省略されている

```
  tag: [
    {
      type: 'Mention',
      href: 'https://example.com/users/User',
      name: '@User@example.com'
    }
```
hrefはid
textはホスト名が省略されていない

**Comment by mei23** [comment]
Hashtagのhref正規化してくれるとうれしい
```
<a href="https://example.com/tags/RSSfeed" class="mention hashtag" rel="tag">
```
```
  tag: [
    {
      type: 'Hashtag',
      href: 'https://example.com/tags/rssfeed',
      name: '#rssfeed'
    },
```

**Comment by mei23** [comment]
The cause is

At the time of reception, it is miss judged as a Hashtag instead of Mention.
Therefore, the host name is not added at the time of reception.

The client displays it as its own host.

**Comment by kazukyakayashi** [comment]
The developers of Glitch have fixed the problem 👍 

https://github.com/glitch-soc/mastodon/issues/1304
