### ISSUE TITLE
テーマのv11互換対応 Part 1(テーマの互換性向上)

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#6195]
## Summary

Misskev11では237個あったテーマのカスタマイズできる幅がv12では88となっており、また一部はランダム文字列?になっていて今後も使用できるかは怪しいものがあるため、その問題への対応。

**Comment by tamaina** [comment]
いる？  
というかv12の中でも互換性はヤバいんじゃなかったっけ

**Comment by SanMurakami** [comment]
イラン
