### ISSUE TITLE
テーマのv11互換対応 Part 2(v11のテーマ記法を使用できるようにする)

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#6196]
## Summary

v11では問題なくインストールできたテーマがv11ではインストール時にエラーが発生してしまいインストールできないものがあります。こちらはその問題への対応Issueです。Part1 #6195 を先に行っておく必要があるテーマがあると思いますのでPart1への対応がまず必要だと考えられます。

### 例:AiDark

```
{
	name: 'AiDark',
	author: 'cv_k',
	desc: '藍ちゃん壁紙に合うダークテーマ',
	base: 'dark',
	vars: {
		primary: 'rgb(255, 51, 200)',
		secondary: 'rgba(5, 5, 5, 0.41)',
		text: 'rgba(255, 255, 255, 0.75)',
	},
	id: '25a7ed82-dcf8-44f8-b7fa-7f4ccc5c5fb5',
}
```

### 表示されるエラー画面
![LSRYZENCapture733](https://user-images.githubusercontent.com/28042693/77829594-5b43e300-7166-11ea-8269-e6af907ed673.png)

**Comment by tamaina** [comment]
このリポジトリで手を付ける開発者は誰もいないと思うのでclose

**Comment by tkmrgit** [comment]
もうにゃんかずいぶん前の投稿にゃので考え変わってるかもしれないけど
https://misskey.dev/notes/85fc8e28cr
