### ISSUE TITLE
Add the is_bot property to the user model

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#62]

**Comment by otofune** [comment]
3つほど質問が。
1. `is_bot`は自らがセットできる？
2. `is_bot`値がセットされることによって提供される具体的な機能はどんなのがある？
3. `is_official`などの無駄をオミットして今回のMisskeyのDBは設計した、と以前聞いたけれど今回は無駄にはならないの？

**Comment by syuilo** [comment]
おそらくis_botは自ら設定することができる
is_botフラグが立っていることによってbotとわかるバッジが表示される
この機能が必要かどうか、無駄かどうかは検討中

**Comment by syuilo** [comment]
implemented
