### ISSUE TITLE
admin/accounts/createで一般ユーザーがアカウントを作成できてしまう

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#6204]
## 💡 Summary
API `admin/accounts/create`で認証されたユーザーなら管理者でなくてもユーザーを作成できてしまう。
CAPTCHAや招待コードなどの制限を迂回して作成できてしまう。
幸い管理者を作ることはできない。

https://github.com/syuilo/misskey/blob/a448172952845ebd0f756c19afee9ffc6bc7cafc/src/server/api/endpoints/admin/accounts/create.ts

## 🙂 Expected Behavior
`admin/accounts/create` は、ユーザーが0の時 または 管理者ユーザーしか使えない

## ☹️ Actual Behavior
一般ユーザーが使えてしまう

## 📝 Steps to Reproduce
1. 一般ユーザーでAPI `admin/accounts/create`を実行

## 📌 Environment
v12

**Comment by tamaina** [comment]
そもそもこのエンドポイント要る？  
Dolphin由来なわけだけど

**Comment by tamaina** [comment]
というかこれって脆弱性ではないのかしら

**Comment by tamaina** [comment]
> そもそもこのエンドポイント要る？

最初の管理者ユーザー作成で使ってるのね
