### ISSUE TITLE
/api-docが重すぎる

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6215]
## Summary
ReDocを使用しているものの、めちゃくちゃ重い。  

### 解決策
- ~~DOM生成処理にかなり時間を要していると思われるので、サーバーサイドでレンダリングしてやればマシになるはず。~~  
  → 実装してみた( #6216 )ものの、ReDocのシングルページで5MB程度になり、計算後のHTMLやDOMが大きすぎるのは同じ。若干軽くなったものの、サクサクにはならなかった。
- 軽いAPIドキュメントジェネレーターを探す。
- 一から実装する。厳しい。

**Comment by tamaina** [comment]
redoc-cli bundleでよさそう

**Comment by tamaina** [comment]
~~redoc-cli的なものを自前で実装することにした~~  
（依存関係にreactが混ざることになる…）

**Comment by rinsuki** [comment]
> redoc-cli的なものを自前で実装することにした

理由気になる

**Comment by tamaina** [comment]
ごめんやっぱなしで（redoc-cliでやりたいことができることがわかった）

**Comment by tamaina** [comment]
やっぱredoc-cli bundle的なものを自前で実装することにした。
api.jsonをgulpでファイルにしたかったけど難しかった。

**Comment by tamaina** [comment]
api.jsonの生成ができたのでredoc-cliをビルド時にやるようにした

――のですが、developに直接pushしてしまいました…  
https://github.com/syuilo/misskey/commit/795fb0eb60ea475533b1d9a12182030f93f01cac

事前にDOM生成してHTMLに保存したところで重いのは変わらないのでCloseは見送ります

**Comment by tamaina** [comment]
Dockerビルドがコケた

これってbuildにDB操作系の処理入れたらいけないやつ？

**Comment by syuilo** [comment]
> これってbuildにDB操作系の処理入れたらいけないやつ？

いけないと思う
いけなくないとしてもビルドにDBへの接続が必要というのは気持ち悪いのでやりたくない

**Comment by tamaina** [comment]
> ビルドにDBへの接続が必要というのは気持ち悪いのでやりたくない

そうするとapi.jsonをビルド時に生成できなくなるのでredoc-cliは使えなくなる

ここからとり得る選択肢としては、 #6216 を復活させる、軽いAPIドキュメントジェネレーターを探す、もしくは自前で実装する の3つぐらい？

**Comment by tamaina** [comment]
あってかこれ現状の実装はDBが用意されてないとnpm run buildがエラー吐くような感じになってそう、これは直さないと（init後にnpm run redocさせるようにメッセージを入れれば良いはず）

やっぱスマートじゃないのよね

**Comment by rinsuki** [comment]
init後にnpm run redoc、dockerだとだめそう

**Comment by tamaina** [comment]
Resolved by #6218  
これで3割軽くなったのでClose、redoc-cliはRevertしました。

もっと軽くしろと思ったら:-1:をリアクションしてください。Reopenするかも。
