### ISSUE TITLE
Activity on user profile not themed properly

### ISSUE THREAD

**Issue by robflop** [misskey-dev/misskey#6220]
## 💡 Summary

When you go to a user's profile and hover over individual entries in the activity chart, the window that shows up to tell you the exact amount of posts is not themed. This means that it shows up in white even if you use the dark theme, rendering it very hard to read. (And the positioning is also a bit off, as seen below)

## 🙂 Expected Behavior

The window that tells you the exact amount of posts should match the theme used.

## ☹️ Actual Behavior

The window that tells you the exact amount of posts does not match the theme used.

![PaintDotNet_2020-04-04_00-02-57](https://user-images.githubusercontent.com/8159402/78408512-a72fd580-7607-11ea-800c-a137b08a1492.png)

## 📝 Steps to Reproduce

1. Go to user profile
2. Hover over any day in their activity chart
3. Observe unfitting window show up

## 📌 Environment

Misskey v12.28.0-io, all browsers
(https://misskey.io/)

**Comment by Johann150** [comment]
Seems like this got fixed.
