### ISSUE TITLE
bullをbullmqに移行

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#6221]
## Summary

https://github.com/taskforcesh/bullmq

**Comment by mei23** [comment]
なにゆえ？bullとbullmqの違いがわからなかったわ

**Comment by syuilo** [comment]
> なにゆえ

名前変わってるけど単にバージョンアップ

**Comment by syuilo** [comment]
パフォーマンス向上とか含まれてそう

**Comment by mei23** [comment]
このへん
https://medium.com/@rockstudillo/beta-release-of-bullmq-4-0-867960aec51

Redis 5.x がちょっとめんどそう

**Comment by syuilo** [comment]
> Redis 5.x がちょっとめんどそう

どのへんが面倒そう？ 👀

**Comment by mei23** [comment]
まだ多くのLinuxリポジトリの標準じゃないから、インストールがひと手間かかるとか。
あとなんかbullmq自体まだまだな気がする。

**Comment by syuilo** [comment]
なるほど🙏

**Comment by syuilo** [comment]
時間経ったけどまだ状況に変化ないかな

**Comment by rinsuki** [comment]
Ubuntu 20.04 LTS (8月に.1が出た) なら Redis 5 が入っているが 18.04 勢に頑張ってもらうというのもアレな気はする
v13のついでとかならありかもしれない

**Comment by mei23** [comment]
前見たときはこんな感じだったけど今は知らない、調べる気はない
> 今までQueue1つで済んでたのがQueue, Worker ... それぞれ必要になるのややこしいし、Queue, Worker それぞれにconnectionとprefixが必要なのも釈然としないし、いまいちリトライとレートリミットがうまくいかないし

**Comment by syuilo** [comment]
ジョブごとにnameを設定したい(例えばdeliverのジョブ名を送信先ホストにするとか)んだけど、現在のbullだとnameが違うとprocessorも名前ごとに用意しないといけなくて実用的じゃないんだよね
bull-mqだとnameは単なる視覚的なヒントという扱いだからprocessorをnameごとに用意する必要がない点は良いと思った

**Comment by syuilo** [comment]
無印BullはTypeScriptとの相性が良くないのでより移行したくなってきた

**Comment by syuilo** [comment]
あと無印Bullはいつのまにかメンテナンスモードに入ってた

**Comment by syuilo** [comment]
今の MisskeyはRedisは7.x必要だしその点はクリア

**Comment by syuilo** [comment]
やるわ

**Comment by syuilo** [comment]
ジョブのtimeout設定はどうするんだ

**Comment by syuilo** [comment]
よくわからん
https://github.com/taskforcesh/bullmq/issues/136
