### ISSUE TITLE
yarnをやめる

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#6222]
## Summary

バージョン上げると依存関係がインストールできなくなったりしてサポートが面倒なのでnpmにしたい
ご意見募集中

**Comment by mei23** [comment]
> バージョン上げると依存関係がインストールできなくなったりして

え、そんなことないよ…

**Comment by syuilo** [comment]
couldn't be built successfully
とか出てインストールできなくなった

**Comment by acid-chicken** [comment]
それどの道 npm でも node-gyp で落ちませんか

**Comment by syuilo** [comment]
> それどの道 npm でも node-gyp で落ちませんか

npmだと大丈夫だった

**Comment by u1-liquid** [comment]
Yarn 2入れちゃっておかしくなったのかも（まだYarn 2対応していない？）
https://yarnpkg.com/advanced/migration

**Comment by acid-chicken** [comment]
couldn't be built successfully って何なのかと思ったら v2 のエラーか……
#5858 でも話しているとおり v2 を使う場合は移行作業がいります

**Comment by acid-chicken** [comment]
というか v2 入ってても `yarn set version berry` しない限りは v1 にフォールバックされませんか？

**Comment by acid-chicken** [comment]
あ、

> バージョンを上げる

ってそういうことか

**Comment by mei23** [comment]
yarn.lockのバージョンが変わっちゃってる
https://github.com/syuilo/misskey/commit/1b9f8a87d374392ed56743d971e93efff688adc8

```diff
- # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
- # yarn lockfile v1

+ # This file is generated by running "yarn install" inside your project.
+ # Manual changes might be lost - proceed with caution!
+ 
+ __metadata:
+  version: 4
```

**Comment by acid-chicken** [comment]
v2 を使う方向で行くなら #5858 に議論を移すか、v1 のままで行くなら当該コミットを一旦差し戻しましょう。

**Comment by rinsuki** [comment]
とりあえず yarn.lock revertしたい

**Comment by syuilo** [comment]
revertしてもpackage.jsonとのズレが生じるけどどうしたら良いんだろう

**Comment by mei23** [comment]
revertして、yarn v1 で yarn 叩けば yarn.lock なおしてくれたりしませんかね？

**Comment by acid-chicken** [comment]
> revertして、yarn v1 で yarn 叩けば yarn.lock なおしてくれたりしませんかね？

直る https://gist.github.com/acid-chicken/a2d609830ed97791d4f622d9f68f0a4b

**Comment by rinsuki** [comment]
> @syuilo 
> (前にもこんな感じの話したかもしれないけど記憶から消えたので再度)
> https://github.com/rogeriochaves/npm-force-resolutions 使う

**Comment by syuilo** [comment]
yarn使ってる理由ってresolutions解釈して欲しいだけだったと思うので、↑にすればyarnやめられそう

**Comment by rinsuki** [comment]
requiredなのはそれだけだけどそれ以外にも `npm` は QWERTY 配列で右側にめちゃくちゃ偏るけど `yarn` は左右にいい感じに分散してるとか `yarn` は `npm run xxx` が `yarn xxx` で行けるとかもある

yarn入ってないNode.js開発環境もあんまりない気がするし (これは主観かも) Dockerのnodeイメージにも最初から入ってるし

**Comment by syuilo** [comment]
なるほど

**Comment by tamaina** [comment]
v2に移行とかよくわからんからyarnやめようぜ

**Comment by acid-chicken** [comment]
> v2に移行とかよくわからんからyarnやめようぜ

やめて何使うの

> > @syuilo
> > (前にもこんな感じの話したかもしれないけど記憶から消えたので再度)
> > https://github.com/rogeriochaves/npm-force-resolutions 使う

npm に無理やり resolution 解決させる類い、確か lockfile 周りが残念な感じになって不整合の元になる

**Comment by syuilo** [comment]
最近のnpmってresolutionサポートなかったっけ？
なくてもまもなくサポートされそうな雰囲気はある

**Comment by acid-chicken** [comment]
npm/cli#4116 で似た機能は入ったらしい（互換性はないが）

**Comment by ThatOneCalculator** [comment]
> v2に移行とかよくわからんからyarnやめようぜ

Why even have v2 in the discussion when v3 is out already? I've been using v3 with Misskey with no issues.
