### ISSUE TITLE
リアクション数が0以下の値を取る

### ISSUE THREAD

**Issue by YuigaWada** [misskey-dev/misskey#6224]
## 💡 Summary

なぜかリアクション数がマイナス値を取る
id: 85rkl4nup7にて観測

<img src="https://s3.arkjp.net/misskey/webpublic-be4134d9-9c56-4ea2-b1d5-3f03a060f0a7.png">

## 🙂 Expected Behavior
リアクション数は正である必要がある

## ☹️ Actual Behavior
リアクション数が0以下の値を取る

ちなみにこれは前からの挙動だが、リアクションを取り消すとリアクション数0のまま残存する
(id: 85rnj50niv)
<img src="https://s3.arkjp.net/misskey/01651251-529e-4679-af1b-f01a631b31d6.png">

**Comment by syuilo** [comment]
これで解決する: https://github.com/syuilo/misskey/issues/6174

**Comment by mei23** [comment]
別のリモートMisskeyからリアクション/取り消しを行うとほぼ再現する。
もともと、同じ削除が同時行われるとリアクションごとのカウントがおかしくなるバグがあって
別のリモートMisskeyからリアクション/取り消しが行われた時に2つ飛んでくることがあるから。
#6253 でなおる。
