### ISSUE TITLE
requestをやめる

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6225]
## Summary
requestはdeprecatedなのでaxiosなどを使う

**Comment by tamaina** [comment]
これ代替ライブラリ何にしますか？axiosしか知らないのでaxiosで実装しようと思うのですが…

**Comment by acid-chicken** [comment]
node-fetch とか

**Comment by mei23** [comment]
Deprecatedのお話
https://github.com/request/request/issues/3142

Alternativesのお話
https://github.com/request/request/issues/3143

**Comment by mei23** [comment]
AP request を置き換えられるとうれしい (送信前にhttp-signatureを入れる必要がある) 
https://github.com/syuilo/misskey/blob/bb7edfee04d990fcf56e0cee46f1da7b62693cb6/src/remote/activitypub/request.ts

**Comment by mei23** [comment]
AP request は https のままでいいかも
axiosはconnection timeoutを検出するのにCancelTokenが必要だったり、エラーハンドリングが面倒だったのでnode-fetchの方がいいかも

**Comment by mei23** [comment]
v10-m544だけどnode-fetchでこんな感じ
https://github.com/mei23/misskey/commit/3c26a16fe02fe8e5c47b36fd7caccc1fd97e2233
