### ISSUE TITLE
WebUIでアンテナを保存するとexcludeKeywordsに空文字列が入るせいで動かない

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#6229]
## 💡 Summary

除外キーワードを空にしてても
![image](https://user-images.githubusercontent.com/6533808/78735191-1f3e2880-7985-11ea-877b-8f78f73a02c6.png)

excludeKeywordsが `[[""]]` で送信され
![image](https://user-images.githubusercontent.com/6533808/78735219-3250f880-7985-11ea-8de7-af52637d86bb.png)

https://github.com/syuilo/misskey/blob/c18f6fde80c4672df2d2b98d4ecd45bb2958a97d/src/misc/check-hit-antenna.ts#L55-L66

当然ここでは空文字列なんて考慮してないので全部弾かれず、何もアンテナにひっかからない

## 🙂 Expected Behavior

アンテナ設定時のAPIで lengthが0な文字列は消す && その結果配列のlengthが0になったら無視みたいな処理を入れて、excludeKeywordsに空文字列が入らないようにする (既存データにはマイグレーションで対処?)

## ☹️ Actual Behavior

excludeKeywordsに空文字が入る

## 📝 Steps to Reproduce

1. アンテナを作る
2. アンテナにひっかかりそうな投稿をする
3. ひっかからない

## 📌 Environment

- misskey.io (`v12.29.0-io` らしい) 
- Firefox 75 on macOS 10.15.4

**Comment by mei23** [comment]
> excludeKeywordsに空文字が入る

これ系前もあった
https://github.com/syuilo/misskey/issues/5420
