### ISSUE TITLE
Vue.jsをやめる（？）

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6237]
## Summary
- 重い。[Vue vs React vs Angularではパフォーマンスが最も悪い。](https://ics.media/entry/190731/)  
- 現状はVue3.0を待つという方針だけど、本当に正式版リリースに辿り着けるの？

**Comment by syuilo** [comment]
あと1年くらいは待つ

**Comment by tamaina** [comment]
1年経ってVue3のRCが出なかったらOpenします

**Comment by tamaina** [comment]
Vue.js v3.0.0-beta.1 がきた
https://github.com/vuejs/vue-next/releases/tag/v3.0.0-beta.1

**Comment by rinsuki** [comment]
それはそれとしてテンプレートをJS上に乗る何かではなくHTMLで書くライブラリ(Vue/Angularも?)はその部分の型付けがイマイチなのでTypeScriptの加護をあまり受けられない話はある

**Comment by rinsuki** [comment]
というか Vue3って早いんですか

**Comment by tamaina** [comment]
高速化が謳われてはいるけど実際は知らない
