### ISSUE TITLE
Add ability to have notifications sent to your email address

### ISSUE THREAD

**Issue by robflop** [misskey-dev/misskey#6262]
## Summary

It would be nice if it was possible to get Misskey notifications via email too, similar to the feature Mastodon has. E.g. You get an E-Mail when you are mentioned in a Note, or when someone replies to one of your notes, so that you don't miss notifications even if you are not manually checking.

It would be best if this was a user setting that you can turn on and off.

**Comment by norz** [comment]
Afaik this is in the settings now, though I never managed to make it work... 🤷‍♀️

**Comment by robflop** [comment]
Yea, i'll be closing this. The setting works for me.
