### ISSUE TITLE
Button for reporting notes does not have a Crowdin string

### ISSUE THREAD

**Issue by robflop** [misskey-dev/misskey#6280]
## 💡 Summary

In the dropdown menu for a note, you can, amongst other things like favoriting, report a note. However, there is no string to translate the text on the report button, so it always shows as "Report this note" in all languages except Japanese.

## 🙂 Expected Behavior

The text on the report button should show up as "Report this note" translated to each respective language and not always as "Report this note".

## ☹️ Actual Behavior

The button always shows the text "Report this note" in all languages except Japanese because there is no Crowdin string for it.

## 📝 Steps to Reproduce

1. Find any note
2. Open dropdown menu for it (three dots)
3. Look at the last menu item

## 📌 Environment

Misskey v12.35.0-io
All browsers

**Comment by tamaina** [comment]
このボタンは[misskey.io独自機能](https://github.com/CookieRamen/misskey)のようですので、ここに書かれても対応致しかねます。申し訳ありませんがよろしくお願いします。
