### ISSUE TITLE
Group invitations are not sent (?)

### ISSUE THREAD

**Issue by kazukyakayashi** [misskey-dev/misskey#6293]
## 💡 Summary

Hi,
I wanted to test the group feature again but it still doesn't work. Is this normal, not yet fully implemented ?

## 🙂 Expected Behavior

Invitation visible in the group page.

## ☹️ Actual Behavior

Misskey tells me that the invitation has been sent but on the invited account in the group there is no visible invitation.

## 📌 Environment

Misskey v12.36.1

**Comment by syuilo** [comment]
グループ機能は実装されています。

> Misskey tells me that the invitation has been sent but on the invited account in the group there is no visible invitation.

バグかもしれません。

**Comment by kazukyakayashi** [comment]
I've just tested with a test account on the same instance (on my personal instance), it works but the invitations from one instance to the other doesn't work.

**Comment by tamaina** [comment]
> the invitations from one instance to the other doesn't work.

グループは連合しません。これは仕様です。

Feature issue: #5535
