### ISSUE TITLE
ロール機能

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#6305]
ユーザーやグループ毎に詳細な権限を管理できる機能があれば非常に便利だと思います。

例えば
- 権限グループAは絵文字のアップロードができる
- 権限グループBは他人の投稿を削除したり凍結できる（モデレーター機能）
- 権限グループCは全機能にアクセスできる（Admin）
- 通常はグループ無しで一般権限

また、特定のユーザーのみファイルをアップロード出来なくする（スパム対応）等もあれば便利かと思います。

実装はかなり大変な物になると思いますが、この基礎をすべてのAPIで対応できれば拡張性がかなり広がると思います。

**Comment by syuilo** [comment]
新たにDBに

- Role(=権限グループ)
  - Role名(e.g. モデレーター)
  - 権限のリスト(e.g. silence, suspend, passwordReset)
- Roleとユーザーの紐づけ
  - userId
  - roleId

テーブルが必要そうか

あと権限をどのくらいの粒度で作っていくかを考えながら権限洗い出ししないと

memo
- silence
- suspend
- roleManage
- roleAssign

**Comment by Johann150** [comment]
maybe related to #8262 ? It might be solvable by giving different OAuth access scopes to users.

**Comment by syuilo** [comment]
やるか

**Comment by tamaina** [comment]
Discordってロールにメンションを送る機能があるけど、Misskeyはどうしようというのがある

**Comment by syuilo** [comment]
グループに対するメンションは考えたことある

**Comment by syuilo** [comment]
GroupとRole割と機能的に被りそう

**Comment by tamaina** [comment]
かも

**Comment by tamaina** [comment]
ん〜、実装的には似るけど機能的な被りはないかも？  
グループにメンションを送れるならロールにメンションはなくて良さそう

**Comment by syuilo** [comment]
ロールに指定のグループを紐付けるオプションとか用意すれば実質的にロールに対するメンションができることになりそう

**Comment by tamaina** [comment]
> ロールに指定のグループを紐付けるオプション

ロールにユーザーリストを紐づける機能も欲しい

**Comment by syuilo** [comment]
done
