### ISSUE TITLE
アップロードプログレスバーが動かない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#6306]
## 💡 Summary
アップロードプログレスバーが動かない

## 🙂 Expected Behavior
アップロードの進捗によってプログレスバーが動く

## ☹️ Actual Behavior
サイズによるが 最初に10%とか30%のあたりで停止して動かない
次に更新されるのはアップロード完了後

## 📝 Steps to Reproduce
1. 大きめのファイルをアップロード

## 📌 Environment
Desktop Firefox, Chrome などたぶん全て

**Comment by syuilo** [comment]
これは前から調べてるけど謎
