### ISSUE TITLE
Roomの復活

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6308]
## Summary
v12(#5712)で消えてしまったので復活してほしい。

Related to https://github.com/syuilo/misskey/projects/6#card-31898828

stylusからscssへの書き換えが面倒らしいけど、「混在しちゃってもよくない？後から書き換えればいいじゃん、それより復活を優先して欲しい」と思っております。

**Comment by tamaina** [comment]
ちなみにどうして今言い始めたかっていうと、これを見たから。

https://misskey.io/notes/86rh1zkxa8

**Comment by syuilo** [comment]
Done
