### ISSUE TITLE
リポジトリURLの明示について

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6309]
## Summary
使われてもないし設定されてもないけどバックエンドには残っているので宙に浮いた状態になってしまっている。  
ソースコードの開示はライセンス的に一番のところなのではやくどうにかすべき。  
正直言うと、metaではなくpackage.jsonのrepository.urlで扱いたい。

**Comment by tamaina** [comment]
ソースコードを書き換えてもらう方針で  
データベースのカラムは削除する

**Comment by tamaina** [comment]
> CUSTOMIZING.md 作ってここ変えてって書いときゃいいんじゃないかしら
https://misskey.m544.net/notes/71720904c833106203686629

**Comment by tamaina** [comment]
ん～、ソースコード書き換えはやっぱり面倒臭い。全部置き換えるにしてもノイズ多いし。

**Comment by tamaina** [comment]
> CUSTOMIZING.md 作ってここ変えてって書いときゃいいんじゃないかしら
> https://misskey.m544.net/notes/71720904c833106203686629

しゅいろが更新しなくて崩壊しそうなのでやめといたほうがいい気がする

**Comment by tamaina** [comment]
データベースに保存するのはAPIで取得できる形にするのも目的だった気がするので、やっぱりCUSTOMIZING.md案はやめたいです。

package.jsonのrepository.urlは扱えないとか誰かが言っていた気がするけどどうなのかしら

**Comment by mei23** [comment]
どっかにconstで書いとくだけでもAPIで取得できるかなと。

> package.jsonのrepository.urlは扱えないとか誰かが言っていた気がするけどどうなのかしら

URLがWeb用のURLとはちょっと違うし
https://docs.npmjs.com/files/package.json#repository
さらに`ベースURL+どこか`でくっつけて表現してる場所もあるし

**Comment by zyoshoka** [comment]
いまはフロント側でも明示されますのでクローズします
