### ISSUE TITLE
2FA Login does not work with Security Key

### ISSUE THREAD

**Issue by yitsushi** [misskey-dev/misskey#6319]
## 💡 Summary

For a while I never tried to log in on new device so I don't know when was it introduced, but if I have 2fa enabled I'm not able to log in because I get "Unable to sign in. The username or password you entered is incorrect."

**First scenario: I have 2fa with YubiKey and Passwordless login**
1. I type in my username
2. Press Sign In
3. A POST request goes out to `https://slippy.xyz/api/signin` (payload is only the username, obviously)
4. A response is coming back with `challenge`, `challengeId`, and all my registered keys
5. I get a "Unable to sign in. The username or password you entered is incorrect." dialog.

In the database (relevant entries):
```
-[ RECORD 1 ]---------+--
twoFactorEnabled      | t
securityKeysAvailable | f
usePasswordLessLogin  | t
```

**Second scenario: Disabled Passwordless login, still have 2 key attached**
1. Type in my username and password
2. A POST request goes out to `https://slippy.xyz/api/signin` (payload is my username and password)
4. A response is coming back with `challenge`, `challengeId`, and all my registered keys
5. I get a "Unable to sign in. The username or password you entered is incorrect." dialog.

In the database (relevant entries):
```
-[ RECORD 1 ]---------+--
twoFactorEnabled      | t
securityKeysAvailable | f
usePasswordLessLogin  | f
```

**Third scenario: Enabled `securityKeysAvailable` manually in the database to true...**
Same results

In the database (relevant entries):
```
-[ RECORD 1 ]---------+--
twoFactorEnabled      | t
securityKeysAvailable | t
usePasswordLessLogin  | t
```

As I disable `twoFactorEnabled`, I can log in with my password.

## Extra experiment

**I tried to add a new key if I can.**
1. Go to `my/settings`
2. Press `Register a new Security Key`
3. Asks my password
4. Type (copy actually because it's random)
5. Press OK
6 A POST request goes out to `api/i/2fa/register-key` (payload: password and the `i` token)
7. A response is coming back with `challenge` and `challengeId`
8 I no UI error, it's like nothing happend... but actually happend, console says:

![image](https://user-images.githubusercontent.com/183191/80896010-ea09c980-8ce9-11ea-8817-e1a6dc92a3f1.png)

## 📌 Environment

Tried:
 - Arch Linux Firefox
 - Arch Linux Brave
 - Ubuntu Firefox
 - MacOS Firefox
 - MacOS Safari

**Comment by robflop** [comment]
I can't help you personally, but I noticed one missing detail:

Which version of Misskey did this happen on? That's listed in your instance's "About <instance name>" in the "More" dropdown menu.

**Comment by yitsushi** [comment]
Oh sorry I missed this information: `Misskey v12.36.1`

**Comment by yitsushi** [comment]
\o/ with `12.37.0` it works again.
