### ISSUE TITLE
ローカルのみの表示に☣Biohazardを使うのはやめる

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6323]
## Summary
意味不明なので当たり障りのないアイコンにするべきかと。

昔は`♥`だったので`♥`で良いのではないでしょうか。

**Comment by rinsuki** [comment]
❤️ はそれはそれで意味不明

**Comment by acid-chicken** [comment]
[city](https://fontawesome.com/icons/city?style=solid) とか

**Comment by syuilo** [comment]
ローカルのみかどうか表示する必要ある？

**Comment by rinsuki** [comment]
ある

**Comment by mei23** [comment]
> ローカルのみかどうか表示する必要ある？

RenoteやQuoteでリモートに拡散できない投稿であることを表示しておかないと、リモートに送ったと思って送れてないことに気づかない

**Comment by tamaina** [comment]
普通は表示しておくものだと思っていたんだけど、どうして隠す必要があるのか

**Comment by syuilo** [comment]
Biohazardでよくね？

**Comment by syuilo** [comment]
「拡散できない(させない)」というイメージがBiohazardと合致している

**Comment by mei23** [comment]
～マークだからわかりづらいと言うよりは、
説明がないのでわからない、公開範囲選択と違う場所にあるので公開範囲に関連していることすらわからない、という感じかなと思います。

なので、v11以前と同じようにローカル分も公開範囲の一覧に含めるようにして
なおかつ、アイコンの上付きでローカルマークを付ければどうかなと思います。
![image](https://user-images.githubusercontent.com/30769358/82000924-c6089980-9694-11ea-8f5f-5b479d3f52fc.png)

こうしておけば、マークはハートでもバイオハザードでもなんでもいいのではと思います。
(上付きの場合細かいところが見えないので単純な図形がいいと思いますが…)

**Comment by tkmrgit** [comment]
twistaの実装例から。🛡(shield)はどうでしょうか?
>![drt](https://user-images.githubusercontent.com/28042693/82730691-a92b3080-9d3c-11ea-99a6-b68c8d12c7f7.png)
>https://twista.283.cloud/notes/71716a3ab4218f12a2166541
