### ISSUE TITLE
家具を選択できない

### ISSUE THREAD

**Issue by u1-liquid** [misskey-dev/misskey#6335]
## 💡 Summary

タイトルのまま

~大きいサイズの家具（ベッドなど）は選択できる~ベッドもびみょーだった
ちょっとマウスポインターのクリックした場所とずれたものが選択されてるかもしれない

## 🙂 Expected Behavior

選択できる

## ☹️ Actual Behavior

選択できない
![recording](https://user-images.githubusercontent.com/17376330/81468233-43598780-9219-11ea-8bef-bc95ad984e28.gif)

## 📝 Steps to Reproduce

1. 消しゴムを置く
2. 選択できない
3. ズームインしても選択できない

## 📌 Environment

develop
Chrome 84.0.4136.7（Official Build）dev （64 ビット）

**Comment by u1-liquid** [comment]
ベッドもびみょーだった
![recording](https://user-images.githubusercontent.com/17376330/81468390-443ee900-921a-11ea-822c-a767e2f54f7a.gif)

**Comment by syuilo** [comment]
再現しなかった🧐

**Comment by syuilo** [comment]
ディスプレイの解像度知りたい

**Comment by u1-liquid** [comment]
> ディスプレイの解像度知りたい

![image](https://user-images.githubusercontent.com/17376330/81472430-026e6c80-9233-11ea-8695-5c76997d2b02.png)

**Comment by u1-liquid** [comment]
ちなみにv11の時のルームでは特に問題なかった（めいすきーとか）

**Comment by syuilo** [comment]
ブラウザの拡大率設定を変更したら再現した

**Comment by u1-liquid** [comment]
> ブラウザの拡大率設定を変更したら再現した

あーなるほど、うちのスケール倍率200%だからか
