### ISSUE TITLE
会話が長くなると「あなた宛て」や「ダイレクト投稿」が使い物にならなくなるのを改善して欲しい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6336]
## Summary
1. 「あなた宛て」や「ダイレクト投稿」では、notes/mentionsの結果をそのまま表示する。
2. 「あなた宛て」や「ダイレクト投稿」では、投稿はnotes/conversationおよびnotes/childrenで取得した投稿をすべて表示する。

Misskey v12のクライアントはこのような実装になっています。  
しかし、結果として、リプライによる会話が長くなると、次に示す例のように延々と同じ内容の投稿が繰り返されることになり、極めて不便です。

「あなた宛て」や「ダイレクト投稿」では投稿を一度きりしか表示しないような実装が良いのではないかと思われます。（できれば）

例:   
投稿`い`を起点として甲（平仮名）と乙（片仮名）が会話し、スレッドが`いロはニほヘとチり`のようになったとき、甲の「あなた宛て」は次のように表示される。  
`<`はメインで表示されている投稿を示す。

```
い
ロ
は
ニ
ほ
ヘ
と
チ <
り
---
い
ロ
は
ニ
ほ
ヘ <
と
---
い
ロ
は
ニ <
ほ
---
い
ロ <
は
```

**Comment by syuilo** [comment]
APIサイドでオプションでまとめても良さそう

**Comment by syuilo** [comment]
どういう実装をするかが問題
普通にクエリしてそこからフィルタリングする方法だと、要求されている数より少ない数のノートを返すことになりおかしなことになるのでダメ
まとめてクエリするのではなく、ひとつひとつクエリ発行していくしかなさそう

**Comment by syuilo** [comment]
あーでもサーバーサイドでやるとあれだな
ストリーミングとの兼ね合いが難しい

**Comment by syuilo** [comment]
とりあえずmentions APIのレスポンスのノートが全てフルpackされているのはバグな気がするのでそれは直す
それだけでもだいぶ見やすくなりそう

**Comment by syuilo** [comment]
あー、フルpackされてなかった
クライアントサイドの問題か

**Comment by tamaina** [comment]
とりあえず、あなた宛てやノート個別画面で使われている表示では、スレッドを（以前のように？）…で省略するって感じでどうでしょう？

**Comment by tamaina** [comment]
XNoteの:detail="true"か

**Comment by syuilo** [comment]
> とりあえず、あなた宛てやノート個別画面で使われている表示では、スレッドを（以前のように？）…で省略するって感じでどうでしょう？

やった(と思う)

**Comment by syuilo** [comment]
(ノート個別画面はやってない)

**Comment by tamaina** [comment]
:detail="true"の指定を外したのね

ノート個別画面もやってほしい感じがある  
特にスマホだと最初の表示が全部会話ってことがありがちなので…

**Comment by tamaina** [comment]
あとできればmy/messagesもやってほしい

**Comment by syuilo** [comment]
> あとできればmy/messagesもやってほしい

やってある

**Comment by tamaina** [comment]
ほんとだ
