### ISSUE TITLE
マイグレーションが作成できない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#6337]
## 💡 Summary
commander 5.x になってるとマイグレーションが作成できない
```
> npx ts-node ./node_modules/typeorm/cli.js migration:generate -n 変更の名前
error: unknown option '-n'
```

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by u1-liquid** [comment]
あー

**Comment by mei23** [comment]
うごかなくなってる気がする
https://github.com/misskey-dev/misskey/commit/94b59e8b6f250b263be6a36ee05903267beff532
