### ISSUE TITLE
通知を全て見ても、サイドバーのインジケータが自動で消えなくなっている

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#6345]
## 📝 Steps to Reproduce

1.
2.
3.

**Comment by syuilo** [comment]
発生するときとしない時があり謎
でも体感的には高確率で発生する

**Comment by syuilo** [comment]
謎

**Comment by syuilo** [comment]
iOS限定で起こってそうな雰囲気

**Comment by syuilo** [comment]
リアクティブな値をオブジェクトのgetterで返すという、若干トリッキーなこと(Vueが想定していないかもしれない使い方)をしているのが原因だと思われるものの、じゃあどうやって解決したらいいかがよくわからない

**Comment by syuilo** [comment]
> リアクティブな値をオブジェクトのgetterで返す

具体的にはここのことです
https://github.com/syuilo/misskey/blob/ca2a33edc928c0dfe59f50502d3eedb9e97e88db/src/client/store.ts#L94

**Comment by syuilo** [comment]
こういう使い方がVueでサポートされてるのかが不明

**Comment by EbiseLutica** [comment]
> > リアクティブな値をオブジェクトのgetterで返す
> 
> 具体的にはここのことです
> https://github.com/syuilo/misskey/blob/ca2a33edc928c0dfe59f50502d3eedb9e97e88db/src/client/store.ts#L94

これが原因なら、シンプルに `getters.indicated` を呼んでいる箇所を `getters.isSignedIn && state.i.hasUnreadNotification` に置き換えて治らないかな

**Comment by syuilo** [comment]
気付いたらiPadで再現しなくなってた
iOS14にした影響かな

**Comment by tamaina** [comment]
気づいたらWindowsのFirefoxで起こり始めている感じがする  
でもreloadすれば治る

**Comment by syuilo** [comment]
最近発生してない気がするし、そうでないとしてもvue3で実装が変わって直ると思うのでClose
