### ISSUE TITLE
Delete activities not federated to AP Relay

### ISSUE THREAD

**Issue by chocological00** [misskey-dev/misskey#6354]
## 💡 Summary
Note delete activity is not federated to AP relay.

Imagine following situation:

1. Instance A (Misskey) and B (any) are both in the same relay.
2. No one in Instance A follows anyone in B, and vise versa (i.e. without the relay, two instances are completely unknown to each other)
3. User from Instance A posts a new note and deletes it

## 🙂 Expected Behavior
4-1. The note is deleted on the Instance B

## ☹️ Actual Behavior
4-2. The note is still visible in Instance B

## Links
1. [Actual Note in original Instance (Deleted)](https://k.lapy.link/notes/87755pp7s6)
2. [Copy of note in Instance in the same relay (Still visible)](https://madost.one/notes/87755pp7z0)

## 📌 Environment
v11.37.0

**Comment by mei23** [comment]
Which relay implementation (host) are you using?

**Comment by chocological00** [comment]
@mei23 
Seems like [this](https://git.pleroma.social/pleroma/relay) (I'm not completely sure, as I'm not the relay server owner :P)

Actual relay address can be found [here](https://relay.mastodon.kr/)

The relay has two endpoints, `/inbox` and `/actor`. Both servers used `/inbox` in this case.

**Comment by mei23** [comment]
@chocological00
Perhaps Pleroma type relays do not support Delete.

**Comment by chocological00** [comment]
@mei23 I will take a further look (probably next week) and provide you with an update.
The relay has existed for quite some time and Mastodon instance owners said they have not seen such problem :/

**Comment by mei23** [comment]
Pleroma relay seems to support Delete

**Comment by mei23** [comment]
I understood the cause.
In short, there seems to be a compatibility issue.
I think that if I change the specification of Misskey's signature, I'll fix it.

**Comment by mei23** [comment]
やはり、このMastodonとは違うリレー時のHTTP-Signatureの署名者はいくつかの実装と非互換みたい
https://github.com/syuilo/misskey/pull/6341#issuecomment-626270846

YUKIMOCHI Activity Relay Server (あちらで修正済み)
https://github.com/yukimochi/Activity-Relay/issues/36

Pleroma's relay 
https://git.pleroma.social/pleroma/relay
=> Signature validation failed になる
CreateはAnnounce型のrelayでとどくのですが
Deleteはforwardはとどきません

relay時のHTTP-Signatureの署名者を投稿者本人にすればなおるみたい
