### ISSUE TITLE
プッシュ通知にclosed, action, clickのイベントを作る

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6359]
## Summary
ブラウザの対応の差異はあれど、Notifications APIはわりといろいろなことができるので、活用したい。  
なんかスクショが出てこないので具体的な説明が今は不可能

MDN: https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API  
WHATWG: https://notifications.spec.whatwg.org/

**Comment by tamaina** [comment]
とりあえず、プッシュ通知は以下の動作を検知します:

- click（選択、つまりタップ）
- action(s)（こちらが任意のアクションを設定可能）
- close（閉じる、スライド（タッチ）や×をクリック（マウス））

これらを駆使して操作できるようにしていくんだけど、具体的な組み合わせはプログラムを組む前にすり合わせて決めておきたいと思う。

**Comment by tamaina** [comment]
# 案

## フォロー(follow)
<dl>
<dt>click</dt>
<dd>そのユーザーの詳細を開く</dd>
<dt>actions</dt>
<dd><dl>
	<dt>フォロー</dt>
	<dd>フォローバックする（フォローしていない場合に表示）</dd>
</dl></dd>
<dt>close</dt>
<dd>通知に既読をつける</dd>
</dl>

## メンション/リプライ(mention, reply)
<dl>
<dt>click</dt>
<dd>ノートの詳細を開く</dd>
<dt>actions</dt>
<dd><dl>
	<dt>返信</dt>
	<dd>返信フォームを開く（自分宛てのみ）<br>URLから返信フォームを開くようなものはMisskey Webに実装されていないと思うので、これを実装する必要あり → #6404</dd>
</dl></dd>
<dt>close</dt>
<dd>通知に既読をつける</dd>
</dl>

## 引用(quote)
<dl>
<dt>click</dt>
<dd>ノートの詳細を開く</dd>
<dt>actions</dt>
<dd><dl>
	<dt>返信</dt>
	<dd>返信フォームを開く（自分宛てのみ）<br>URLから返信フォームを開くようなものはMisskey Webに実装されていないと思うので、これを実装する必要あり → #6404</dd>
	<dt>Renote</dt>
	<dd>Renoteする</dd>
</dl></dd>
<dt>close</dt>
<dd>通知に既読をつける</dd>
</dl>

（actionsが要るかどうかは微妙なところあり）

## リアクション(reaction)
<dl>
<dt>click</dt>
<dd>ノートのページに移動する</dd>
<dt>actions</dt>
<dd><dl>
	<dt>ユーザーを開く</dt>
	<dd>ユーザーのページに移動する</dd>
</dl></dd>
<dt>close</dt>
<dd>通知に既読をつける</dd>
</dl>

## 投票された(pollVote), Renote
<dl>
<dt>click</dt>
<dd>ノートの詳細を開く</dd>
<dt>close</dt>
<dd>通知に既読をつける</dd>
</dl>

## フォローリクエストを受信(receiveFollowRequest)
<dl>
<dt>click</dt>
<dd>ユーザーの詳細を開く<br>操作の順番的に、ユーザーページに「このユーザーからフォローリクエストが届いています。承認しますか？」という感じでユーザページから承認と拒否ができるようになるといいかも</dd>
<dt>actions</dt>
<dd><ul><li>承認</li><li>拒否</li><li>フォローリクエスト一覧を開く</li></ul></dd>
<dt>close</dt>
<dd>通知に既読をつける</dd>
</dl>

## 自分の送ったフォローリクエストが承認された(followRequestAccepted)
<dl>
<dt>click</dt>
<dd>ユーザーの詳細を開く</dd>
<dt>close</dt>
<dd>通知に既読をつける</dd>
</dl>

## グループに招待された(groupInvited)
<dl>
<dt>click</dt>
<dd>グループ一覧を開く</dd>
<dt>actions</dt>
<dd><ul><li>許可</li><li>拒否</li></ul></dd>
<dt>close</dt>
<dd>通知に既読をつける</dd>
</dl>

## 未読のチャットメッセージがある(unreadMessagingMessage)
<dl>
<dt>click</dt>
<dd>チャットルームを開く</dd>

**Comment by tamaina** [comment]
そろそろ実装する

リアクションクリックはユーザーを開くようにするようにするか

**Comment by rinsuki** [comment]
ユーザー開いてもどうしようもなくない?該当投稿のほうがいい気がする

**Comment by tamaina** [comment]
Twitterの挙動を見たら投稿を開くようになっていたので、やっぱ投稿を開くようにする

**Comment by tamaina** [comment]
現状の実装だとServiceWorkerにiが読み込めないので…あぁ、コードの変更範囲が広がってしまう…

**Comment by tamaina** [comment]
そもそもActionsの上限が2つだったわ
