### ISSUE TITLE
reCAPTCHAが動かなくなってる

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#6362]
## 💡 Summary
https://github.com/syuilo/misskey/pull/6303#issuecomment-627258877

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by acid-chicken** [comment]
hCaptcha が reCAPTCHA を破壊するっぽいので一度でも hCaptcha がロード済みの状態になってないかが確証持てないとなんとも

**Comment by mei23** [comment]
1から構築してrecaptcha-failedになる
