### ISSUE TITLE
検索でサジェストしたい

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#6363]
## Summary
v12からダイアログの検索でユーザー名などのサジェストが出来なくなってるので、出来るようにして欲しい。

**Comment by syuilo** [comment]
ダイアログでサジェストそのまま表示すると、下のボタン類がサジェストで隠されてしまってUXが低下する問題があって考え中

**Comment by tkmrgit** [comment]
![gr](https://user-images.githubusercontent.com/28042693/82247005-ab7a3d00-9980-11ea-8cee-878aa1f0a963.png)
#### 実装提案(現在は左側、提案は右側)
PC版ではすでに右上に検索ボックスが存在しているのでそもそも既定では検索アイコンが無くてもいいかも？と思ったり。
