### ISSUE TITLE
Selected Themes are not propagating across browsers/devices

### ISSUE THREAD

**Issue by imjustafox** [misskey-dev/misskey#6377]
## 💡 Summary

Selected Themes are not propagating across browsers/devices

## 🙂 Expected Behavior

Themes should remain the same for users across browsers

## ☹️ Actual Behavior

Themes aren't propagating across browsers

## 📝 Steps to Reproduce

1. Select Theme for your user
2. Log In on new device
3. Themes are not the same 

## 📌 Environment
Debian10 64bit, 
Misskey v12.37.0

**Comment by syuilo** [comment]
テーマがブラウザ保存なのは仕様だけどアカウントに保存した方が良いのかなぁ

**Comment by wertyy102** [comment]
Apologies in advance: Using google translate because I'm a stupid American ;-;

謝罪、グーグル翻訳を使用して。

エンドユーザーの頭痛の種を減らすことができるので、アカウントに保存するのが最善だと思います。

**Comment by imjustafox** [comment]
closing as stale, unsure if it was fixed/worked on
