### ISSUE TITLE
Custom theme registered for the account

### ISSUE THREAD

**Issue by kazukyakayashi** [misskey-dev/misskey#6380]
## Summary

Currently for custom themes you have to rewrite them for each web browser or device.

It would be convenient if they were registered globally for the account, which would avoid rewriting them each time you change your internet browser or device.

**Comment by imjustafox** [comment]
This is a Duplicate of https://github.com/syuilo/misskey/issues/6377

**Comment by kazukyakayashi** [comment]
Not really, here I'm talking about custom themes (made with the theme editor), and not about applying themes per device per user.
