### ISSUE TITLE
Pleromaのリンクが変

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6383]
## 💡 Summary
https://c2.a9z.dev/notes/87g75in4za

## 🙂 Expected Behavior
`[$text](<http$href>)`になる

## ☹️ Actual Behavior
`[]($href)$text` になるっぽい

## 📝 Steps to Reproduce

1. Pleromaからリンク付きの投稿をする
2. Misskeyで表示

## 📌 Environment
Pleroma v2.0.4-213-g52ec1b67-develop → Misskey v12.38.0

**Comment by tamaina** [comment]
[AP](https://pleroma.eniehack.net/activities/07016948-cc02-487a-b48c-a57d9015656a)みた  
Pleromaは以下のように送ってくるらしい

```
<a href=\"https://c2.a9z.dev/notes/87g6mkla6c\"></a><a href=\"https://c2.a9z.dev/notes/87g6mkla6c\" rel=\"ugc\">https://c2.a9z.dev/notes/87g6mkla6c</a>
```

これはPleroma側に仕様変えてもらいたいけど…

**Comment by mei23** [comment]
元はこれだったのでパーサー自体は間違ってなさそう
```
<a href="https://c2.a9z.dev/notes/87g6mkla6c"></a>
<a href="https://c2.a9z.dev/notes/87g6mkla6c" rel="ugc">https://c2.a9z.dev/notes/87g6mkla6c</a>
```

**Comment by mei23** [comment]
MFMからレンダリングする時に空リンクラベル (`[]`)は不可視にしちゃえばいいのかな

**Comment by tamaina** [comment]
私的にはfrom-htmlでtxt = getText(node)が空の場合は何もしないようにするべきかと

**Comment by mei23** [comment]
ここのMarkdownは`[]`は消しちゃう仕様
`[](https://example.com)` => [](https://example.com)

**Comment by tamaina** [comment]
なるほど  
なんか気持ち悪い感じがあるけどまあそれでもいいのかな

**Comment by tamaina** [comment]
#6426 が原因  
移動します

**Comment by mei23** [comment]
> #6426 が原因
> 移動します

これ本当に関連してる？

**Comment by mei23** [comment]
HTML `<a href="http://example.com"></a>`
↓
MFM `[](http://example.com)`
↓
空`[]`はMFMではValidではないのでそのまま出てくる
