### ISSUE TITLE
#5935 を逆に有効にするオプション

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#6386]
## Summary

~~Misskey v12がどれくらい使えるかどうかの調査中~~ (指摘を受けたので取消)
Misskey v11からv12へスムーズにアップデートをして使いたいためにv11とv12を比較して、v11では流れるのにv12では流れない投稿に違和感を覚えてめいめいに調べてもらったところ( https://misskey.dev/notes/87g9chauf1 )、 #5935 が原因とのことでした。

これはバグだったようですが正直有効に活用していたため、機能を把握しているユーザー向けに「フォロー外へのリプライを隠す」というオプションを用意しv12でも利用できるようにして頂きたいです。既定の設定はこれまで通りで問題ないと思います。

めいすきーで行われた同一Issueは以下参照▼
https://github.com/mei23/misskey/issues/855

**Comment by EbiseLutica** [comment]
TLに流れるリプライ、かなり賛否両論なので、個人的にはAからBへのリプライについて、

- AをフォローしていればAからのリプライは全て表示（v11仕様）
- A,B両方フォローしていれば表示（Twitter仕様）
- 自分自身のと、自分またはA自身へのリプライ以外は非表示（v12仕様）

の3種類から選択可能にしたいです

**Comment by mei23** [comment]
> A,B両方フォローしていれば表示（Twitter仕様）

あたり1つでいいと思ってて、https://github.com/mei23/misskey/issues/855 でオプションにしてるのは、単にフォローが少数だと重いからです。

**Comment by EbiseLutica** [comment]
そもそもTLに余計なノートが流れてくるのが邪魔と僕が文句を言った結果この仕様になったので、そうでない方のニーズを考えたissueがこれなのならば、1つでいいって言われると元も子もないような:confused:

**Comment by xianonn** [comment]
このオプションは #8202 で「タイムラインにノートへの返信を表示する」として実装されました。
