### ISSUE TITLE
PCでタイムラインを簡単に切り替えられるようにする

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#6387]
## Summary
簡単に言うと・・・
![LSRYZENCapture1082](https://user-images.githubusercontent.com/28042693/82241607-68679c00-9977-11ea-96b6-d7a1b5d1a673.png)
▲これを復活させる

## ｋｗｓｋ
 - 現状のUIはスマートフォン等のタッチデバイスに最適化されすぎていてPCでは使いにくい箇所がある
- v11ユーザーからの意見で特に必要だと感じた
>v11ではTLの切り替えがワンクリックでできるが、v12は選択式なのでクリック数が増えてる
>https://misskey.dev/@c0_ke/pages/1589472585817

- さすがにv11そのままのUIは適さない恐れがあるため、Syuilo Design Systemに沿ったv12版を作るべきだと思う

**Comment by syuilo** [comment]
新しいUIで実装しました
