### ISSUE TITLE
もっと！に表示される項目が多すぎるため整理する

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#6389]
![LSRYZENCapture1085](https://user-images.githubusercontent.com/28042693/82247978-550dfe00-9982-11ea-8be6-849614872f96.png)
## Summary

もっと！のメニューの項目がv12.38.0の時点で13個となっておりiPhone SEのような端末ではギリギリになってきているため整理する。

## 統合案

~~返信・DM
┗あなた宛て　　　(←タブで切り替え)
┗ダイレクト投稿　(←タブで切り替え)~~
→ #6387 PC #6391 モバイル

遊ぶ
┗Misskey Games(←タブで切り替え/そろそろリバーシを動かせるように...)
┗ルーム (←タブで切り替え/とりあえずリバーシが動くまで既定はこちらかな?)

ページ
┗スクラッチパッド (自分のページといいねしたページを1クリックで切り替えられるようにする #6390 を実装した上で各ページの下に配置)

ヘルプ
┗[インスタンスドメイン]について　　　(←ヘルプの下にリンクを表示)
┗Misskeyについて　　　　　　　　　　(←ヘルプの下にリンクを表示)

これで8個に減らすことができると思います。

## 追加案
ログアウトまでが遠いという意見があるため、ログアウトボタンの追加

**Comment by tamaina** [comment]
個人的に「あなた宛て」と「ダイレクト投稿」は昔の位置（タイムライン切り替え）にあっていいと思う

**Comment by tkmrgit** [comment]
なるほど。 #6391 を立ててみました。

**Comment by futchitwo** [comment]
もっと！の項目は各個人でカスタマイズできるので、改善が必要かはわからないです
今やるとするとこんな感じになりそうです

通知
┗あなた宛て
┗ダイレクト投稿
(#8365)

インスタンス情報(<インスタンス名>について)
┗連合
┗絵文字

ヘルプ
┗スクラッチパッド(AiScriptの使用範囲はPagesに限らないので)
┗MFMチートシート(#8035)
┗Misskey-hubへのリンク

チャット
┗グループ(ただしグループメンションなどが実装されてチャットの範疇を越える可能性がある)

設定
┗UI切り替え

**Comment by syuilo** [comment]
YOSASOU
