### ISSUE TITLE
アプリ連携が自動的に行われる可能性があるのではないかという疑問

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/misskey#639]
アプリ連携に関するapiのコードを読んでいて、疑問に思ったことがあったので質問させてください。

連携のフローとしては以下のように想定されていると思います:
1.  `/auth/session/generate` にリクエストすると、セッショントークン と 連携画面のURL が返却される
2.  連携画面のURLにユーザーがアクセスしブラウザ上に表示、「アクセスを許可」をクリック。
3. `/auth/accept`  にリクエストされ、AccessTokenをinsert & 204を返却。その後にアクセスキーが取得可能に

このフローの手順(2)を飛ばして、**自動的に**acceptさせることが出来てしまうのではないかと思いました。
この他になにか対策がされているんでしょうか？
返信よろしくお願いします。

**Comment by syuilo** [comment]
自動的に というのは具体的にどのような手順を指しますか？

**Comment by syuilo** [comment]
なんにせよ /auth/accept にリクエストする際、ユーザーのプライベートなトークンが必要なので(そしてそれはユーザーしか知り得ない情報(もちろんサードパーティ アプリからも知ることはできない))、自動的に、といったことは不可能だと考えています。

**Comment by syuilo** [comment]
(ユーザーのプライベートなトークン = ユーザーのパスワードのようなもの と考えて差し支えありません)

**Comment by syuilo** [comment]
CSRF対策もされているので、ほかのサイトから /auth/accept にリクエストを飛ばす、といった手順での自動化も不可能と考えています。

**Comment by syuilo** [comment]
Misskeyは全面的にサイトを iframe の中に入れて表示させるといったことも(たとえMisskey内部だとしても)禁止しているので、クリックジャッキング等も不可能と考えています。

**Comment by marihachi** [comment]
例えば、ユーザーのPC上でブラウザ以外のプログラム(ウイルス等)が動作していたとして、
そのプログラムが `/auth/session/generate` を呼び出した後に、`/auth/accept` が順に呼ばれていったときに、その操作(アクセストークンの取得)は成功はしないのかどうかについてが知りたいです。

**Comment by marihachi** [comment]
言葉足らずで申し訳なかったです。

**Comment by syuilo** [comment]
そのプログラムが何らかの方法でユーザーのプライベートなトークンを入手できていたのなら成功しますが、それはMisskey自体のセキュリティ上の問題ではないと思います。

**Comment by marihachi** [comment]
ユーザーからの連携の許可を得られていない状態で、アクセスキーが取得されるのは問題だと思ったんですが..

**Comment by syuilo** [comment]
**`/auth/accept`にリクエストされる = 100%ユーザーが自分の意思で自分自身で許可した** ということなので問題ないと思っています。

**Comment by marihachi** [comment]
ちなみに「ユーザーのプライベートなトークン」というのはコード上ではどのような名前で扱われていますか？

**Comment by syuilo** [comment]
(もちろん、コンピューターが何らかのウィルスに感染しているとかでない限り)

**Comment by syuilo** [comment]
リクエストされるというか、リクエストされそれが**受理される**

**Comment by marihachi** [comment]
なるほど、概ね理解できました。
確かに、コンピュータウィルスに感染するなどしていなければ、セキュリティ上問題はないかもしれませんね。
返信頂きありがとうございます。

**Comment by syuilo** [comment]
こちらこそありがとうございました。いつでもお気軽にご質問ください :>

**Comment by marihachi** [comment]
ありがとうございます :)
