### ISSUE TITLE
UI Suggestion: ホームをタブ式に

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6392]
## Summary
![image](https://user-images.githubusercontent.com/7973572/82355568-58b28b00-9a3d-11ea-9f1f-e13113a602e0.png)

こんな感じで

**Comment by tamaina** [comment]
#6387 の一案として

**Comment by tamaina** [comment]
近々手をつけようと思っているんだけど、 @syuilo はどう思いますか？

**Comment by syuilo** [comment]
新しいUIで実装しました
