### ISSUE TITLE
ブラウザビルトインのObject.fromEntries()を使うように

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6400]
## Summary
fromEntriesは私が使いたくなった当時はTypeScriptに収録されていなかったため、array preludeで実装していた。  
しかし現在はTypeScriptで型が定義されているので、できれば標準のものを使いたい。

#6396 で硫酸鶏氏に型定義してもらった直後で申し訳なさはある

**Comment by acid-chicken** [comment]
<details><summary>Off Topic</summary><blockquote>#6396 で硫酸鶏氏に型定義してもらった直後で申し訳なさはある</blockquote>これに関してはどうとも思ってないけど、それはそれとして TypeScript ビルトインの型がガバガバで笑っちゃった。</details>
