### ISSUE TITLE
`/share`でもっと色々な情報を渡せるようにしたい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6404]
## Summary
/share で以下のような情報を渡せるようにしたい

※specifiedはvisibilityとvisibleAccts/visibleUserIdsで指定する

### リプライ情報
以下のいずれか

<dl>
<dt>replyId</dt>
<dd>リプライ先のノートid</dd>
<dt>replyUri</dt>
<dd>リプライ先のUrl（リモートのノートオブジェクトを指定）</dd>
</dl>

### Renote情報
以下のいずれか

<dl>
<dt>renoteId</dt>
<dd>Renote先のノートid</dd>
<dt>renoteUri</dt>
<dd>Renote先のUrl（リモートのノートオブジェクトを指定）</dd>
</dl>

### 公開範囲
<dl>
<dt>visibility</dt>
<dd>公開範囲 ['public' | 'home' | 'followers' | 'specified']</dd>
<dt>localOnly</dt>
<dd>0[false] or 1[true]</dd>
<dt>visibleUserIds</dt>
<dd>specified時のダイレクト先のユーザーid カンマ区切りで</dd>
<dt>visibleAccts</dt>
<dd>specified時のダイレクト先のacct（＠?username[＠host]） カンマ区切りで</dd>
</dl>

### ファイル
<dl>
<dt>fileIds</dt>
<dd>添付したいファイルのid（カンマ区切りで）</dd>
</dl>

**Comment by noellabo** [comment]
FYI:
https://github.com/tootsuite/mastodon/pull/13023 Mastodonへ、visibilityパラメータを提案しています。当人のデフォルト公開範囲よりオープンにはできない制約付きです。

**Comment by tamaina** [comment]
visibilityは真っ先に考え付いたのですが、（Misskey Webの内部の話で）post-formをvisibilityを指定して開くような実装はされていないので敢えて挙げませんでした。  
別に実装して悪いことはなさそうだけど、このためだけに開けるっていうのもなんだかなと思っています。

**Comment by tamaina** [comment]
私としては、偶然Mastodonと/shareのURLとパラメータが一致しているだけだと認識しているので、互換性をとるとかはそんなに深くは考えていません。

**Comment by tamaina** [comment]
ダイレクト（specifiedToUserName(仮)）があれば外部のサービスからvisibilityを指定する機会はなさそうなのでvisibilityは不要だと思う

**Comment by acid-chicken** [comment]
> 別に実装して悪いことはなさそうだけど、このためだけに開けるっていうのもなんだかなと思っています。

このためだけにって理由で実装を躊躇するのもそれはそれでなんだかなとなりません？（ユースケースが全く想定されないわけではなさそうだし）

**Comment by tamaina** [comment]
driveFileIdsを渡せるようにもしたいよねって思ったので付けたした

**Comment by tamaina** [comment]
最初の案からわりと変更した

**Comment by tamaina** [comment]
visibilityは結局入れたんだけど、MisskeyとMastodonでは互換性が全くないのはどうしようかしら  
変換を入れておくべき？

**Comment by tamaina** [comment]
特に変換してまずいことはなさそうなので変換するようにしておく

**Comment by syuilo** [comment]
互換性は無くて良いと思う

**Comment by tamaina** [comment]
しゅいろがそういうならなくすか
