### ISSUE TITLE
AiScriptをページごとに許可できるように

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6411]
## Summary
ページを表示する  
→AiScriptがあったらAiScriptの許可設定を確認  
→すべて許可であれば何もしない  
→「このページでAiScriptを実行するようにしますか？」
　　はい
　→ページでの許可を記録する
　　いいえ
　→ページでの不許可を記録する

**Comment by rinsuki** [comment]
とりあえず今回だけAiScriptを有効とかでいい気がする

**Comment by futchitwo** [comment]
動的Pages廃止でAiScript許可設定が消えたのでcloseで良さそう
PlayはAiScript前提なのでAiScriptを許可しない設定はいらなさそうだし
