### ISSUE TITLE
Email Server Settings missing from Instance Settings

### ISSUE THREAD

**Issue by Kusoneko** [misskey-dev/misskey#6415]
## Summary

On this page: https://join.misskey.page/en/wiki/developers/email
It states that by going into Instance > Settings I'm supposed to find a section to set up info on a SMTP server to use to send verification emails and add email support in general, however, on my Misskey instance running v12.38.1, there is no such section in the Instance Settings. Is it a missing feature from v12?

**Comment by tamaina** [comment]
Sorry, but yes, v12 doesn't have email server settings.

**Comment by Kusoneko** [comment]
Is it planned to be added back eventually?

**Comment by tamaina** [comment]
@syuilo may know about it.

**Comment by robflop** [comment]
I'm also interested in this.

**Comment by koyuawsmbrtn** [comment]
Same, I cannot open registrations until users have a way to confirm their e-mails

**Comment by polkonic** [comment]
same here, is it possible to add smtp configurations to default.yml file?

**Comment by koyuawsmbrtn** [comment]
I haven't figured it out yet. The only mention of SMTP is a SMTP proxy server which is exactly what I want to avoid at all costs.

**Comment by tamaina** [comment]
インスタンス設定にはメールサーバー設定が復活しました

**Comment by robflop** [comment]
ありがとうございます！
