### ISSUE TITLE
[MiAuth] トークンが利用できない

### ISSUE THREAD

**Issue by YuzuRyo61** [misskey-dev/misskey#6419]
## 💡 Summary

MiAuthで認証したトークンが利用できない。

## 🙂 Expected Behavior

MiAuthで認証したトークンを利用して認証が必要なAPIにアクセスができる。

## ☹️ Actual Behavior

トークンが不正というレスポンスが返る。(HTTP 403)

```json
{
  "error": {
    "message": "Authentication failed. Please ensure your token is correct.",
    "code": "AUTHENTICATION_FAILED",
    "id": "b0a7f5f8-dc2f-4171-b91f-de88ad238e14",
    "kind": "client"
  }
}
```

## 📝 Steps to Reproduce

1. MiAuth経由で認証してトークンを取得する。
2. 返ってきたトークンを利用して認証が必要なAPIにアクセスする

## 📌 Environment

Misskey v12.38.1

**Comment by syuilo** [comment]
謎

**Comment by YuzuRyo61** [comment]
> 謎

`src/server/api/authenticate.ts` 内の

```typescript
const accessToken = await AccessTokens.findOne({
	hash: token.toLowerCase()
});
```

憶測で申し訳ないのですが、多分 `token.toLowerCase()` で小文字でデータベースを検索しているのでMiAuthで作成したトークンが見つからないのではないかと思われます
