### ISSUE TITLE
FirefoxのプライベートブラウジングでMisskeyが使えるように

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6420]
## Summary
IndexedDB導入の影響  
IndexedDBが使えない場合の処理を入れておいた方がいいかもしれない

**Comment by rinsuki** [comment]
:eyes: https://bugzilla.mozilla.org/show_bug.cgi?id=1639542

**Comment by tamaina** [comment]
indexedDBに戻った

**Comment by rinsuki** [comment]
> indexedDBに戻った

localStorageに戻ったの間違い？
