### ISSUE TITLE
デッキの復活

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6422]
## Summary
個人的な実装案（内部の実装ではなく使い勝手的なもの）

- カラムは #6315 と同一のものにする
- カラムの表示/非表示を以下のように選択可能にする。
  1. ホームだけで表示するカラム
  2. いつも表示するカラム
  3. ホーム以外のみで表示するカラム
- ページ表示領域を特別なカラムとして扱う。これならば、v11までのような両脇にカラムを持つ表示も可能となる。できるかどうかは不明。
  * ページ表示領域カラムは左から1番目か2番目にしか配置できないし、追加も削除もできない。また、表示設定は2か3のみ選択可能。
  * 従来のホームの幅かデッキサイズの幅かを選択可能。

**Comment by syuilo** [comment]
ページ表示領域を特別なカラムとして扱うよりは、単にカラムに左か右かの情報を持たせれば良さそう
スマホ/タブレットでは使えないけど

**Comment by tamaina** [comment]
内部的にはそのほうがよさそう

ただ、vue-draggableのようなものでドラッグしたとき良い感じになるようにしたさがある

**Comment by syuilo** [comment]
復活自体はした

**Comment by tamaina** [comment]
だいたい復活した
