### ISSUE TITLE
UIの上部のマージンは必要？

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6425]
## Summary
![image](https://user-images.githubusercontent.com/7973572/83351764-be7a0d80-a381-11ea-8fe8-9f03642e8ac6.png)

![image](https://user-images.githubusercontent.com/7973572/83351729-7d81f900-a381-11ea-8f56-d28231d33cde.png)

画像のようにページの上部にマージンがつくけど、私的にはいらないとおもう

**Comment by EbiseLutica** [comment]
消すとのっぺりして微妙

**Comment by syuilo** [comment]
新しいUIではシャドウとの兼ね合いでやはり必要
