### ISSUE TITLE
twitterカードの実装をちゃんとする

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6426]
https://github.com/syuilo/misskey/issues/6383 の具体的な修正

~~meta(name="twitter:card" content="summaly")のみの実装は正規ではない（はず）なので、~~Twitterカードの実装はちゃんとtwitter:descriptionなどを定義するようにする。

**Comment by mei23** [comment]
ogにfall backしてくれるみたいだから間違えというわけではなさそう
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#twitter-cards-and-open-graph

**Comment by tamaina** [comment]
https://git.pleroma.social/pleroma/pleroma/-/issues/1835

結局Pleroma側で修正するっぽいし要らないかも
