### ISSUE TITLE
Support minimal text formatting in "Instance Information"

### ISSUE THREAD

**Issue by yitsushi** [misskey-dev/misskey#6435]
## Summary

Right now, it does not matter what do we type in as "Instance Information", it will be one big text-block. Even a single newline support would be much better. With newline characters we can create lists, separated blocks. 

```
👉 Text goes here
👉 Text goes here
👉 Text goes here
```
It will be rendered as

```
👉 Text goes here 👉 Text goes here 👉 Text goes here
```

Ideally it would be:
```
👉 Text goes here
👉 Text goes here
👉 Text goes here
```

**Comment by syuilo** [comment]
MFM使えるようにするか

**Comment by syuilo** [comment]
あ、既にHTMLが使えるようになってた

**Comment by syuilo** [comment]
@yitsushi You can use HTML to description of instance. So:

```
<p>👉 Text goes here</p>
<p>👉 Text goes here</p>
<p>👉 Text goes here</p>
```

**Comment by yitsushi** [comment]
Hah, html is working :O I'm pretty sure I tried to add some html in there and `<p>` was simply printed as string `<p>`.

👍
