### ISSUE TITLE
まったく異なるユーザー、引用元で連合してくることがある

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#6439]
# 元の投稿
![63D92CF7-7323-4653-9680-5A2578794BED](https://user-images.githubusercontent.com/4439005/83643349-e029fd80-a5ea-11ea-98d8-8877e6e95267.png)

# Misskeyに来た投稿
![510646FB-18CA-4228-8CFC-F89035B1791A](https://user-images.githubusercontent.com/4439005/83643394-eddf8300-a5ea-11ea-955e-df0da77dc4c1.png)

ユーザーも、引用元の投稿も間違ったものになっている

**Comment by mei23** [comment]
これDBに入れる時におかしくなってるとしか思えなくて・・・

**Comment by mei23** [comment]
aidのノイズbit数だと、同ミリ秒の場合全く同じIDが生成されることがそこそこある。
DBに`save (Insert or Update)`で保存してるので、IDが重複してた場合でもエラーにならず既存を部部分更新してしまう。
`ただのRenote`と`通常Note`がDBで合体した結果、Renoteが無関係な投稿文章を持つ引用投稿に化けてしまう。
