### ISSUE TITLE
INSERTするときにはsaveではなくinsertを使用する

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#6441]
## Summary
DBにINSERTするときに`.save()`を使いまくってるけど
`.save()`は`INSERT` or `UPDATE`で、重複エントリを (部分) 更新してしまうので
新規挿入で重複チェックして欲しいときには使ってはいけない。
https://typeorm.io/#/repository-api/repository-api

Related #6439

**Comment by mei23** [comment]
修正サンプルコード
https://github.com/syuilo/misskey/commit/6d22032b61dc9ae92200d83fab1e96232c0bdc09 https://github.com/syuilo/misskey/compare/use-insert-for-insert

**Comment by syuilo** [comment]
saveを使ってる箇所は無くなった
