### ISSUE TITLE
リモートからの投稿を受信できていない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6444]
## 💡 Summary
@aqz@yuzulia.xyz(v12.38.1) → @aqz@suki.tsuki.network(v12.38.1-83ec906e)でできていないことを確認

**Comment by tamaina** [comment]
> 5時間前から受信できて無さそう

https://yuzulia.xyz/notes/81727f78da123aa200a24662

**Comment by syuilo** [comment]
5時間前ってどんなコミットしたっけ...

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/83761701-9e17bf00-a6b1-11ea-823d-4b2ee9296504.png)

**Comment by tamaina** [comment]
なんで受信だけ死んでいるんだろう

**Comment by mei23** [comment]
このへんでinboxのroute飛ばしたとか？
https://github.com/syuilo/misskey/commit/83ec906ee7c5d9bd42b11129f3f0b3df85287b3c

**Comment by syuilo** [comment]
見てるけど問題ありそうには見えないんだよな...

**Comment by rinsuki** [comment]
*がprefix無視してるみたいなオチありそう

**Comment by syuilo** [comment]
/* にしないとダメとかかなぁ

**Comment by rinsuki** [comment]
みんな手前に何かしらのリバースプロキシ挟んでるだろうしログ見てもらうとよさそう

**Comment by tamaina** [comment]
> *がprefix無視してるみたいなオチありそう

> /* にしないとダメとかかなぁ

c2で/*にしたけどだめっぽい

**Comment by rinsuki** [comment]
ログ的にはどうなってるの、404?

**Comment by tamaina** [comment]
アクセスログ取ってないのでわかんないのですが、ELB的に504かなと

![image](https://user-images.githubusercontent.com/7973572/83765392-12546180-a6b6-11ea-9400-e9bf8ec407fb.png)

**Comment by tamaina** [comment]
13時になっているのはUTCだから

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/83765616-5e070b00-a6b6-11ea-9cfa-1f83b61164e0.png)

**Comment by tamaina** [comment]
c2→sukiの送信を見てみると、タイムアウトとして記録されてる

![image](https://user-images.githubusercontent.com/7973572/83766385-5431d780-a6b7-11ea-9203-bacefdc491c2.png)

**Comment by tamaina** [comment]
c2からsukiの送信ログを見てると、timeoutとして記録されてる

![image](https://user-images.githubusercontent.com/7973572/83767887-1f268480-a6b9-11ea-9096-e32c4deb45c9.png)

**Comment by tamaina** [comment]
c2は普通に私が使っててわりと困るのでとりあえず

```
git revert 83ec906ee7c5d9bd42b11129f3f0b3df85287b3c
```

したところ、ちゃんと正常に受信しだした  
83ec906ee7c5d9bd42b11129f3f0b3df85287b3c が悪いというのは確実そう

**Comment by u1-liquid** [comment]
とりあえずバージョン発行は取り下げてもらえると助かります
自動アプデでiro.moeまで外部からノートの受信ができなくなりました…

**Comment by SanMurakami** [comment]
海外の方もアップデートして色々困ってるみたいです。

全員が日本語を読めるわけでもGitHubのIssueを確認している訳でもないので、ここまででかいバグなら早急に一旦戻すべきだと思います。

**Comment by tamaina** [comment]
このIssueどうする？Closeする？名前変える？

**Comment by tamaina** [comment]
#6418 を名前を変えてReopenしました。こちらはCloseします。
