### ISSUE TITLE
何かの拍子にインスタンスの設定が消える

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#6448]
## 💡 Summary
どのタイミングかは分かりませんが、インスタンスの設定がいつの間にか消えてる事があります。
すべての設定が消えるわけではなく、所々消える感じです。
もう3回ぐらい起こってて、発生するとファイルがDockerのコンテナ上にアップロードされて再起動やアップデートの時に消えてしまうので勘弁してほしいです。

消失を確認してるもの
- ServiceWorker
- ピン留めユーザー
- オブジェクトストレージ
- インスタンスブロック
- 連携

消失していないもの
- 基本情報
- hCaptcha
- ファイル
- プロキシアカウント

![image](https://user-images.githubusercontent.com/37681609/83832672-2b482b80-a725-11ea-810a-859f25f010b6.png)
![image](https://user-images.githubusercontent.com/37681609/83832685-313e0c80-a725-11ea-8390-3e49cf1d34b9.png)
![image](https://user-images.githubusercontent.com/37681609/83832723-431faf80-a725-11ea-9d66-14ba2cb7790d.png)

## 📌 Environment
misskey.io(custom) v12.39.1
co.misskey.io(vanilla) v12.38.1

**Comment by EbiseLutica** [comment]
これ、原因は複雑ながらちょっとわかっていて

1. 管理者ではないアカウントでインスタンスの設定を開く
2. 当然、管理者しか見れない部分は空っぽな状態で設定画面に表示される
3. 管理者に切り替える
4. どういうわけか、サーバー設定が再fetchされず、2. の情報が表示されたままである
5. この状態でサーバー設定をすると、2. の空っぽな情報がそのままサーバーに送られる
6. 結果、:innocent:

という感じみたいです

**Comment by SanMurakami** [comment]
自分は少なくとも最近インスタンス設定を変更してないですし、他のモデレーターについてはインスタンス設定を変更出来る権限自体を持っていない筈なのでしっくりこないですが、もしそれが原因なら以前のように管理画面は別に用意すべきな気がします。

そもそも今の管理画面はv11に比べて設定できる情報が少なすぎる問題もありますし。

**Comment by SanMurakami** [comment]
作者が犯人だった
![image](https://user-images.githubusercontent.com/37681609/83834198-a9f29800-a728-11ea-9726-6cfb107fd845.png)

**Comment by syuilo** [comment]
管理者アカウントに切り替えたとしても、ページ自体がリロードされるので 2 が表示されたままというのは不可解だな

**Comment by EbiseLutica** [comment]
> ページ自体がリロードされるので 2 が表示されたままというのは不可解

F5 を押さないとちゃんと更新されなくて、ステート更新のライフサイクルに問題が起きているかもしれないなあと

**Comment by mei23** [comment]
アカウント切り替え => `localtion.reload()`後にサーバーからfetchしてる値は問題なし
metaは一度stateに入れているので`localtion.reload()`直後にstateから取って来る値が変なのかなと
`localtion.reload()`を使わなければとりあえず大丈夫ぽい
