### ISSUE TITLE
ユーザーのリノートのみをミュート

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6450]
短時間での連続リノートが目立つユーザーがいるので、ユーザーのリノートだけを表示しない特殊なミュート機能が欲しい

**Comment by h3zjp** [comment]
この機能、個人的に欲しい
その人の投稿だけを見たいのに、リノートばっかで何だかなあ…🤔
 って思うことがよくあるので
Twitter や Mastodon にも実装されているので、みすきーにも実装を希望します。

**Comment by EbiseLutica** [comment]
MutingテーブルにrenoteOnly列を生やしてやっていく感じかなあーやるなら。クエリが増えそうだけどどうしよう

**Comment by tamaina** [comment]
#9325 でRenoteは別に保持すればいいんじゃね

**Comment by h3zjp** [comment]
👍
