### ISSUE TITLE
外部のカスタム絵文字が直リンになる

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#6451]
## 💡 Summary

外部のカスタム絵文字が直リンになる

## 🙂 Expected Behavior

外部のカスタム絵文字がproxyを通る

## ☹️ Actual Behavior

外部のカスタム絵文字がproxy経由じゃなくて直リンになる

## 📝 Steps to Reproduce

1. Developer Tools の Network タブを開く
2. カスタム絵文字使ってる外部の投稿を見る
3. proxy通ってないことがわかる

## 📌 Environment

misskey.io (v12.39.1)

**Comment by rinsuki** [comment]
そもそも pack を実装する必要がある https://github.com/syuilo/misskey/blob/78ef0a9929a1a4460acdca4f1810f8c0ca08f37f/src/models/repositories/note.ts#L169-L172

**Comment by mei23** [comment]
そもそも（投稿の添付ファイルとかと同じように）ローカルにコピーしとけという話があって・・・

**Comment by rinsuki** [comment]
でもカスタム絵文字ってownerがいないからdriveのファイルにできなくない?
(instance actorって確実にいるわけでもないはずだし)

**Comment by syuilo** [comment]
ドライブのファイルはowner無し対応してたはず

**Comment by rinsuki** [comment]
あしてるんだ、じゃあそれでよさそう

**Comment by mei23** [comment]
> ドライブのファイルはowner無し対応してたはず

カスタム絵文字導入した当時はこの機能なかったというやつです

**Comment by rinsuki** [comment]
Related #3214

**Comment by rinsuki** [comment]
連合先がなぜかHTTPのURLを配っているレアケース (sunisky.club) で巻き添えで各misskeyが mixed contents になってSafariの鍵マークが外れる
