### ISSUE TITLE
ローカル限定な 公開範囲:ダイレクト を指定できてしまう

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6452]
## 💡 Summary

12.39.0 以降の新たな公開範囲ピッカーで、これまで選べなかったローカルオンリーなダイレクト指定が選べてしまう

このまま投稿しても、サーバーサイドでは特にエラーを返さず、普通にlocalOnly + directなノートが生成されるため、問題ないような気はするが、12.39.0より前のバージョンと挙動が異なるため一応issue化

## 🙂 Expected Behavior

公開範囲:ダイレクトを選んでいるときに「ローカル限定」スイッチはグレーアウトする
or
選択時に公開範囲:フォロワーに強制する？

## ☹️ Actual Behavior

公開範囲:ダイレクト のボタンが、選択されたままグレーアウトしてしまう

## 📝 Steps to Reproduce

1. 公開範囲ピッカーでダイレクトを選ぶ
2. 公開範囲ピッカーをもう一度立ち上げて、ローカル限定にチェックを入れる
3. 表題の通りになる

## 📌 Environment
- Misskey 12.39.1
- misskey.io

**Comment by mei23** [comment]
APIで出せる設計だからUIで指定できても問題ないかなと

「localOnly + direct」は、以前からローカルのみ投稿にダイレクトリプライすることでUIから作れるので、特に作れること自体は問題ないはずです。

(localOnly + Public) & (非localOnly + Direct) = localOnly + Direct になる

**Comment by EbiseLutica** [comment]
なるほど...なんで旧来禁止されていたんだろう:thinking:

**Comment by rinsuki** [comment]
禁止というか単に意味なかったからでは

**Comment by mei23** [comment]
UIで全パターン網羅するとスペース取るから… 意味がないし

**Comment by EbiseLutica** [comment]
v11まではそうだったけど、v12でローカルのみが別れた時、わざわざ `v-if="visibility !== 'direct'"` 的な分岐がされていた

**Comment by EbiseLutica** [comment]
閉じちゃってもよきですか？
