### ISSUE TITLE
外部のカスタム絵文字のリアクションを押すとエフェクトだけ出る

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#6453]
## 💡 Summary

![画面収録 2020-06-05 21 41 35 mov](https://user-images.githubusercontent.com/6533808/83877390-6c682c00-a775-11ea-8767-086a54bc2b35.gif)

## 🙂 Expected Behavior

エフェクトが出ない

## ☹️ Actual Behavior

出る

## 📝 Steps to Reproduce

1.  外部のカスタム絵文字のリアクションが付いた投稿を探す
2. 外部のカスタム絵文字のリアクションを押す

## 📌 Environment

misskey.io (v12.39.1)

**Comment by mei23** [comment]
自分の投稿へのリアクションを押したときとかにも出ちゃう
（こっちは押せそうなUIになっちゃってもいる）

**Comment by EbiseLutica** [comment]
ot: 自分の投稿、リアクション押せても良くない？と思っていてissue立てようと思っているのですがどうですか
