### ISSUE TITLE
プロフィールの「場所」「誕生日」を連合する

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6461]
Person オブジェクトの attachments の中にでも入れておけば良さそう？

```json
{
    "attachments": [
        {
            "type": "Birthday",
            "name": "Birthday",
            "value": "1970-01-01"
        },
        {
            "type": "Location",
            "name": "Location",
            "value": "日本"
        }
    ]
}
```

**Comment by mei23** [comment]
たぶん`vcard:`なやつを使う
https://www.w3.org/TR/activitystreams-core/#actors

Actor.typeをArrayにするまですると、読めない実装ありそうだからそこはやりたくないなあと

**Comment by EbiseLutica** [comment]
`vcard:geo` と `vcard:bday` かな？現在地にいい加減なこと書いてる人多いけど大丈夫なのだろうか

**Comment by mei23** [comment]
`Address`あたりならまあなんでもありかも
https://www.w3.org/2006/vcard/ns-2006.html#Address

**Comment by EbiseLutica** [comment]
なるほど。
