### ISSUE TITLE
Link To Poll Results Not Translated

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#6464]
## 💡 Summary

Text not translated on remote instance

## 📝 Steps to Reproduce

1. Create poll
2. View poll outside of Misskey
3. Text not translated

![poll-results](https://user-images.githubusercontent.com/1679025/84304127-0d643780-ab26-11ea-8191-dc6176d5c67e.png)

**Comment by mei23** [comment]
I don't think the link is needed anymore, as it's a remnant of when the votes weren't federated.

**Comment by EbiseLutica** [comment]
これ outdated ぽいので閉じちゃっても良いですか

**Comment by Johann150** [comment]
is outdated
