### ISSUE TITLE
自分のノートにリアクションを押せるようにする

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6468]
自分のノートだけリアクションが押せないの、特に理由の無い制限な気がするので。Mastodon では自分のトゥートをお気に入りにできますし

実用面ではToDo 系のノートにチェックを付けるような使い方などができるかも

**Comment by syuilo** [comment]
> 実用面ではToDo 系のノートにチェックを付けるような使い方などができるかも

👍
