### ISSUE TITLE
フォロワー公開範囲のアイコンを閉じ鍵にする

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#6474]
## Summary
限定ユーザー投稿が閉じ鍵だったときの名残りで、フォロワー限定投稿が開き鍵だけど、
閉じ鍵がなくて開き鍵だけあるとなんか別の意図を感じて不自然なので閉じ鍵の方がいいかなと。

![image](https://user-images.githubusercontent.com/30769358/85305638-4cac6400-b4e8-11ea-8211-324da4dca094.png)

**Comment by EbiseLutica** [comment]
フォロワー限定を閉じ鍵にしてホームを開き鍵にしたいなとも思ったけど、今までのUIから変えることを考えると混乱しそう
