### ISSUE TITLE
名前の長いカスタム絵文字でリアクションされると通知されない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#6499]
## 💡 Summary
例えば128文字のカスタム絵文字でリアクションされると
NoteReactionテーブルには入るがNotificationテーブルには入らなくて通知だけされない
`value too long for type character varying(128)`

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by syuilo** [comment]
good catch👍👍👍
