### ISSUE TITLE
ウェルカムページの内容とウェルカムウィジェットの内容が被っているのでどっちかだけ表示するようにしたい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6510]
## Summary
![image](https://user-images.githubusercontent.com/7973572/86786658-346b4600-c09f-11ea-8148-23a084bcf16c.png)

**Comment by EbiseLutica** [comment]
#6493 と重複している
#6509 で修正

**Comment by tamaina** [comment]
Duplicate
