### ISSUE TITLE
つのファイル Shows On Social Media 

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#6517]
## 💡 Summary

Hi @syuilo this text **`(1 つのファイル)`** message is shown when a post is shared on social media

![misskey-share](https://user-images.githubusercontent.com/1679025/87108155-9490f200-c22f-11ea-877b-20d92f6ca6e3.png)

## 🙂 Expected Behavior

Display translated text

## ☹️ Actual Behavior

Text not translated

## 📝 Steps to Reproduce

1. add photo and only tags to post (ie: **`#test #test2 #test3`**)
2. share post to social media (ie: twitter)
3. it shows **`#test #test2 #test3 (1 つのファイル)`**

**Comment by tamaina** [comment]
なんか見つけたけど直ったかしら

**Comment by tamaina** [comment]
あー、リンクのサマリーとかの話か～。サーバーサイドレンダリングをどうこうする話なのでインスタンスの言語設定とかつけないと難しいやつだ  
そして似たようなIssueがあった気がする

**Comment by tamaina** [comment]
なんか見つけたけど直ったかしら

**Comment by tamaina** [comment]
fixed
