### ISSUE TITLE
ノートの投稿日時がざっくりとしか確認できない

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#6520]
## 💡 Summary

ノート詳細ページでも時間が相対表示のまま

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by EbiseLutica** [comment]
こんな見た目でどうだろう

（個人的には公開範囲の表記がダサいなってちょっと気になっている）

![](https://user-images.githubusercontent.com/7106976/92367083-ef13d500-f130-11ea-8198-53ffb476959b.png)

**Comment by mei23** [comment]
私はこれがベストだと思ってるわ
![image](https://user-images.githubusercontent.com/30769358/92426707-95a9b580-f1c5-11ea-8373-51b0c8d506ee.png)

**Comment by EbiseLutica** [comment]
わかる

**Comment by syuilo** [comment]
やった
