### ISSUE TITLE
Deck(デッキ)モード のカラムの配置において、フレキシブル表示を行えるようにする

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#6522]
## Summary

![LSTP25Capture228](https://user-images.githubusercontent.com/28042693/87215455-94990b00-c371-11ea-9e33-054aca60713c.png)
画像はv11インスタンス｢デッキのカラムの配置｣の場合。v12テスト版では｢カラムの寄せ｣にフレキシブルが存在しないため、v11同様にフレキシブルサイズでの表示を行えるようにする。

**Comment by syuilo** [comment]
やった
