### ISSUE TITLE
Deck(デッキ) メニューが追加されたことで設定を選べなくなってしまっている

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#6526]
![dqw](https://user-images.githubusercontent.com/28042693/87217648-93260d80-c386-11ea-81e3-e2e36c66b7ed.png)

## 💡 Summary

画像参照。デッキに切り替えるためのメニューが追加されたことによりSafariのブラウザ表示で一番下の設定メニューを選択することができません。

関連Issue : #6389 (縦幅解像度問題が共通)

## 📌 Environment

Apple iPhone SE(2020)
Safari iOS13.5.1

**Comment by syuilo** [comment]
原因としてはSafariのバグっぽい

**Comment by tkmrgit** [comment]
> 原因としてはSafariのバグっぽい

Apple側の対応を待つのは得策ではないかなと。v11だとサイドメニューが固定ではないのでスクロールで正常に一番下のリンクまでスクロールしてタップができることが確認できました。いっそのこと下部固定のメニューの固定をやめた方が良いかもしれない。
![IMG_0063](https://user-images.githubusercontent.com/28042693/87233726-fb1b3900-c404-11ea-9105-1baca4df9983.jpg)

**Comment by EbiseLutica** [comment]
fyi 関係あるかはわからない（サイドバーの実装を見ずに言及しているので）、iOS Safari は `vh` の計算にバグがあって、サイドバーやトップバーの高さとの兼ね合いがうまくいかないことがあるので、もし vh を使っていればそのせいだったりする？

**Comment by syuilo** [comment]
vh使ってるのでそれっぽい

**Comment by syuilo** [comment]
https://github.com/rodneyrehm/viewport-units-buggyfill

**Comment by syuilo** [comment]
https://allthingssmitty.com/2020/05/11/css-fix-for-100vh-in-mobile-webkit/

**Comment by syuilo** [comment]
https://css-tricks.com/the-trick-to-viewport-units-on-mobile/
