### ISSUE TITLE
ノート詳細 /notes/:id ページの直リンを踏むと404

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#6533]
## 💡 Summary

<img width="469" alt="image" src="https://user-images.githubusercontent.com/6533808/87238597-7dc0ea00-c43f-11ea-9f64-a836df33eeb0.png">

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

misskey.io (12.41.1) / groundpolis.app(12.41.1-gp-3.10.0)
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0

**Comment by syuilo** [comment]
そこらへん変更した覚えないけどなんでだろ

**Comment by syuilo** [comment]
あー
koa-routerアピデしたから何か影響したのかも

**Comment by mei23** [comment]
`@koa/router` 9.1.0 以降で
APとWebで同じパラメータ付きルートを持っている時に
https://github.com/syuilo/misskey/blob/f8e06f12fd2922aa8d530868b2afb907a2686ae4/src/server/activitypub.ts#L65-L66
https://github.com/syuilo/misskey/blob/f8e06f12fd2922aa8d530868b2afb907a2686ae4/src/server/web/index.ts#L240-L241

後に処理するWebの方で取得できる値 (`params.note`) が `:note` みたいな値自身になってしまう。

**Comment by mei23** [comment]
とりあえず9.0.1に戻すしかないかなと

**Comment by mei23** [comment]
https://github.com/syuilo/misskey/commit/4b13431a19492b400c67da27e79cf800072a48d1 で上げたので壊れた
