### ISSUE TITLE
iOS/macOS Safariでpost-formやノートメニューをたまに表示できない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6540]
## 事象
どういうわけか、storeにpostFormActionsやnoteActionsが存在しないことがある。

再現条件が不明。

### Safari
13.1.1 (15609.2.9.1.2)

v14だと普通に動くらしい[*](https://github.com/syuilo/misskey/issues/6540#issuecomment-657222148)

### Misskey
Misskey v12.41.0 ~2

**Comment by tamaina** [comment]
this.$refs.text.focusがundefinedらしい

**Comment by syuilo** [comment]
Misskeyのバージョンいくつ？

**Comment by tamaina** [comment]
12.41.1…そういえばアプデしてないわ

**Comment by tamaina** [comment]
でもpost-formは.2にアプデしても変わらなさそう…？

というか原因箇所の目星はついてる

https://github.com/syuilo/misskey/blob/develop/src/client/components/post-form.vue#L330

**Comment by tamaina** [comment]
~~↑の箇所をnextTickにしたらやっぱり直った~~

**Comment by tamaina** [comment]
$store.state.postFormActions.lengthがないといわれるエラーも一緒に出ていたように記憶しているので、それが原因かもしれない

**Comment by syuilo** [comment]
ぽい
https://mewl.me/notes/817342746c276044f14274bd

**Comment by tamaina** [comment]
私のVueレベルが低いのでどうして$store.state.postFormActionsが虚無なのかよくわからない

**Comment by syuilo** [comment]
> 私のVueレベルが低いのでどうして$store.state.postFormActionsが虚無なのかよくわからない

私もこれで頭抱えてる

**Comment by syuilo** [comment]
というか再現条件もよくわからない

**Comment by tamaina** [comment]
だからSafari固有のバグなのか()

**Comment by syuilo** [comment]
謎すぎてもはやVue側のバグを疑うレベル

**Comment by rinsuki** [comment]
iOS 14.0 b2 / Safari Technology Preview (Release 109 (Safari 14.0, WebKit 15610.1.17.2))だと普通に動く
Safari バージョン13.1.1 (15609.2.9.1.2) はだめ

**Comment by tamaina** [comment]
Misskeyを一回開く→Safariを再起動する をすると大丈夫になる説を立ててみる

**Comment by syuilo** [comment]
特定のブラウザバージョンでのみ発生する現象ということ？

**Comment by tamaina** [comment]
~~原因、たぶんこれ~~ これも違った
https://github.com/syuilo/misskey/pull/6484

**Comment by tkmrgit** [comment]
12.41.0までは全く報告されていなかった/起きなかった気がするのだが、もしかしてPolyfill関連なのでは...?

**Comment by rinsuki** [comment]
polyfill消して早くなったから間に合わなくなった説🥴

**Comment by tkmrgit** [comment]
Can I use... Support tables for HTML5, CSS3, etc 
https://caniuse.com/#feat=resizeobserver

変更点調べたらResizeObserverが出てきたので調べてみましたがSafari側の実装に問題ありが正しいのかも。
一応サポートされていないとされているiOS 12.4.1/12.4.6で問題なくメニューを開くことが確認できました。

**Comment by EbiseLutica** [comment]
古い iOS で問題なく動くのであれば、iOSではとりあえずResizeObserverを使用するコードを無効化してしまうのが良いのかな:thinking:

**Comment by syuilo** [comment]
> 12.41.0までは全く報告されていなかった/起きなかった気がするのだが、もしかしてPolyfill関連なのでは...?

今回のエラーは、プラグインシステムに関連するプロパティが無いというエラー。だからプラグインシステムが原因(なぜそうなるのかは謎)
Polyfillは無関係

**Comment by rinsuki** [comment]
<img width="755" alt="image" src="https://user-images.githubusercontent.com/6533808/87296923-89490980-c542-11ea-8d5d-96ed01d04faa.png">
まさかのSafari固有バグではなかった
macOS 10.15.5 + Firefox 78.0.2
でも Safari ほど確実に再現はしない

**Comment by syuilo** [comment]
undefinedになるのはどの時点からなのか(ページ読み込み直後からとか、それ以降からとか)とか、undefinedになったときその他のプロパティは有るのかなども調べると何か手掛かりになりそう

**Comment by syuilo** [comment]
ちょっと外出するので帰ったらやる…と思ったけど私の環境だと再現しないんだよな
iPhoneだとたまに再現するけどiPhoneでデバッグは困難

**Comment by rinsuki** [comment]
Safariだと `this.$refs.text.focus()` でコケる時は `this.$refs` が空っぽい

**Comment by rinsuki** [comment]
![image](https://user-images.githubusercontent.com/6533808/87299151-75070b80-c546-11ea-879b-504ea9379fcc.png)

**Comment by rinsuki** [comment]
その時の `this.$el` はこう
![image](https://user-images.githubusercontent.com/6533808/87299289-b0093f00-c546-11ea-80fe-1e29059ead33.png)

**Comment by rinsuki** [comment]
components に dynamic import を使ってる場合それが終わらないと $refs が使えないらしい?
ref. https://forum.vuejs.org/t/refs-is-undefined-in-mounted/1700/4

**Comment by syuilo** [comment]
$el や $refs が無いのは $store.state.postFormActions がundefinedになってエラーになってるからコンポーネントのマウント自体が失敗してるからとかではなく？

**Comment by rinsuki** [comment]
っぽいな

**Comment by rinsuki** [comment]
何らかの理由で `this.$store.state.postFormActions` がundefinedなことがある (なんで?)
![image](https://user-images.githubusercontent.com/6533808/87303374-09c13780-c54e-11ea-830e-f7826eb54775.png)
そもそもこのエラーが出る状態だと永続化されているやつしか `this.$store.state` に存在しない?
![image](https://user-images.githubusercontent.com/6533808/87303656-7b00ea80-c54e-11ea-8264-7d97c0d3715b.png)

https://github.com/syuilo/misskey/blob/aae9bc4cf4c583b4d675391fe3da2fa53b7f18e0/src/client/store.ts#L92-L106

**Comment by rinsuki** [comment]
本来はこうなるはず
![image](https://user-images.githubusercontent.com/6533808/87304429-c5369b80-c54f-11ea-9e11-5c7045e4450d.png)

**Comment by rinsuki** [comment]
うしろむきな解決案として https://github.com/syuilo/misskey/commit/d327bb8ff1b8765e92d6815d244e74f0793f6157 で上げられた vuex のバージョンを下げるなどがある

**Comment by rinsuki** [comment]
とはいったものの https://github.com/vuejs/vuex/compare/v3.4.0...v3.5.1 対した変更はないな…

**Comment by syuilo** [comment]
お手上げ🙌

**Comment by syuilo** [comment]
せめてこのプロパティが消える現象がいつから起きていたのかが分かればなぁ

**Comment by syuilo** [comment]
実際は昔からこの現象が起きてて、たまたま最近プラグインシステム実装したおかげで(？)顕在化したという可能性があるんだよな

**Comment by syuilo** [comment]
なんもわからん

**Comment by syuilo** [comment]
Chrome拡張機能のVueDevToolには、Vuexの状態がどのように変わってきたかを履歴で見れる機能あるんだけど、それ見て何か分かったりしないかな

**Comment by syuilo** [comment]
あと、VuexとVuexPersistenceのソースコードを読んでみて最初に定義したプロパティが消えてしまうようなことが起こり得る実装になってないかも確認したい

**Comment by syuilo** [comment]
しゅいろPCでは一回も再現しないのつらい

**Comment by syuilo** [comment]
@rinsuki 再現するコツとかある？

キャッシュ有効/無効にしたりネットワーク速度激遅にしても再現しないからそれらは無関係っぽいけど...

**Comment by rinsuki** [comment]
全くわかってない、謎

**Comment by tamaina** [comment]
@syuilo 
検索ボックスってやっぱり関係ないかしら？

**Comment by syuilo** [comment]
> @syuilo
> 検索ボックスってやっぱり関係ないかしら？

はっきりしたことは何も言えないけどさすがにCSSが影響するとは考えにくい

**Comment by syuilo** [comment]
@rinsuki ioじゃなく、ローカルの開発環境とかでも再現しました？

**Comment by rinsuki** [comment]
io以外では試してない

**Comment by syuilo** [comment]
なるほど

**Comment by syuilo** [comment]
ioは広告が入ってたりするからそれらが不具合を引き起こしてる可能性もゼロではないな...

**Comment by syuilo** [comment]
まぁほぼゼロだとは思うけど

**Comment by syuilo** [comment]
再現しないことにはなかなか調査も難しい

**Comment by tamaina** [comment]
他の小規模インスタンスやローカルでも不具合を確認してます

**Comment by syuilo** [comment]
なるほどなるほど

**Comment by tamaina** [comment]
たまに普通に動くのが厄介

**Comment by syuilo** [comment]
あーずっとChromeでテストしてたけどrinsukiが使ってたのFirefoxか

**Comment by syuilo** [comment]
でもアレか 仮にFirefoxで再現できたとしてもVueDevToolが使えないからあまり調査の役には立たないか

**Comment by syuilo** [comment]
お手上げ🙌

**Comment by tamaina** [comment]
いや、（macは知らないけど）Firefoxアドオンある

**Comment by syuilo** [comment]
あらそうなのか

**Comment by tamaina** [comment]
私のmacのFirefoxで再現しませんでした…

**Comment by tamaina** [comment]
ストアのdeviceUser/setTlが原因かも？

**Comment by tamaina** [comment]
これ使ってみた

https://github.com/vuejs/vue-devtools/tree/dev/packages/shell-electron

**Comment by tamaina** [comment]
発生条件として、**タイムラインの切り替えをするとストアがだめになる**ことが判明した（Safari）

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/87315348-5f521000-c55f-11ea-86d6-2ace251490f3.png)

![image](https://user-images.githubusercontent.com/7973572/87315382-6b3dd200-c55f-11ea-8e8d-f5156e17c154.png)

**Comment by tamaina** [comment]
つまり、永続化するべきデータを変更するとストアがだめになる…？

**Comment by syuilo** [comment]
ふむふむ
こっちだとTL切り替えても再現しない

**Comment by tamaina** [comment]
@syuilo Safari? FIrefox?

**Comment by syuilo** [comment]
ChromeなのでFireFoxでもやってみる

**Comment by syuilo** [comment]
Firefoxでやっても再現しなかった

**Comment by syuilo** [comment]
@tamaina aqzの環境だとTL切り替えると100%再現する？

**Comment by syuilo** [comment]
setTl 見ても単に state.tl にオブジェクトを代入してるに過ぎないので謎

**Comment by tamaina** [comment]
@syuilo iOS/macOS 最新develop+デバッグ用コードで、SafariでTL切り替えると100%ダメになります

あと、ウィジェットを挿入してもダメになったのでpersistedstateの問題の可能性が高くなった

**Comment by syuilo** [comment]
@tamaina よかったら vuex-persistedstate を削除した状態で再現するか確認してもらえると嬉しい
```
import createPersistedState from 'vuex-persistedstate';
```
と
```
	plugins: [createPersistedState({
		paths: ['i', 'device', 'deviceUser', 'settings', 'instance']
	})],
```
を削除すればおK

**Comment by tamaina** [comment]
@syuilo persistedstateを削除したら直りました

**Comment by syuilo** [comment]
ありがとう🥰🥰🥰
vuex-persistedstateが犯人でよさそう

**Comment by syuilo** [comment]
このあたり怪しい
https://github.com/robinvdvleuten/vuex-persistedstate/blob/ff2e71119955a5253e60c998858cab59c8e3f6a6/src/index.ts#L57-L63

**Comment by syuilo** [comment]
```
['i', 'device', 'deviceUser', 'settings', 'instance']
```
で列挙した以外のプロパティがすべて消えることを考えると、reducerの処理が何らかの原因でstateにそのまま上書きされている(?)みたいな感じだろうなぁ

**Comment by tamaina** [comment]
@syuilo persistedstate消したら直りました（キャッシュ削除して一応再確認したけどやっぱりそんな感じだった）

**Comment by syuilo** [comment]
これ以上詳細に調査するにはやっぱり手元で再現しないと...

**Comment by syuilo** [comment]
この行を消した状態のvuex-persistedstateを使うと再現するんだろうか
https://github.com/robinvdvleuten/vuex-persistedstate/blob/ff2e71119955a5253e60c998858cab59c8e3f6a6/src/index.ts#L60

**Comment by tamaina** [comment]
reducerはオプションで外部から指定できるっぽい

**Comment by syuilo** [comment]
デフォルトのreducerでもコード的には問題なさそうに見えるから謎

**Comment by tamaina** [comment]
reducerがどうしたところでストアのstateには影響しないし、persistedstateのコードに問題はないように見える

**Comment by tamaina** [comment]
アプデしたWebpackのせいとかは？

**Comment by tamaina** [comment]
あ〜、報告忘れてた

persistedstateのオプションに`reducer: (state, paths) => state`を追加したところ、ちゃんと動くようになりましたが全てのstateがlocalStorage.vuexに記録されました

**Comment by tamaina** [comment]
Webpackの問題だったらSafariだけバグが起きるってことは考えにくいか…

オブジェクトの参照が入れ替わってるとかそういうことなんだろうけど……

**Comment by tamaina** [comment]
localStorage.vuexにはちゃんとreducedなデータが入っているので入れ替わってはないっぽい

**Comment by syuilo** [comment]
ついに原因が分かった

**Comment by syuilo** [comment]
## 再現条件
1. 複数のタブでMisskeyを開いている状態で、
1. 片方でlocalStorageの更新を行うと、
1. もう片方でstateが消える

## 原因
Misskeyでは、複数のタブ間でlocalStorageに永続化されたVuexの状態を同期する仕組みがあり、その処理にバグがあった。具体的には、localStorageに更新があると、永続化されないstateまでlocalStorageの情報で上書きされ、結果的に永続化されないstateは消えることになる。
当該箇所: https://github.com/syuilo/misskey/blob/b6c3399abeab100f0991f5c77bc47919fdcbfaad/src/client/init.ts#L106-L112

## 解決策
``` ts
store.replaceState(JSON.parse(localStorage['vuex']));
```
の部分を、まるごと上書きではなく現在のstateとマージするようなコードにすればよい。

**Comment by syuilo** [comment]
「ひとつのタブしか開いていないが、この現象が発生する」という報告もチラホラあるな
これについてはよくわからないが、いずれにせよ上に挙げた当該コードの修正で直るはず
