### ISSUE TITLE
スクロールの動作がおかしくなるときがある

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#6543]
## 💡 Summary

動画:
https://s3.arkjp.net/misskey/3748b5db-d193-41b1-a943-3e84d2273893.mp4

かなり前から発生しているバグ。

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by tamaina** [comment]
「ノートPCなどのタッチパッドでデッキを横スクロールする」場合にこうなるのできつい
（Surface Pro w/ Edge）

（デッキ、Surface Proのタッチパネルを使うにしても横スクロールがカラム上だと取り消されてしまってマージン部分を掴む必要があるのでつらい）

**Comment by tamaina** [comment]
原因はここらへんかな

https://github.com/misskey-dev/misskey/blob/develop/packages/client/src/ui/deck.vue#L139

**Comment by syuilo** [comment]
デッキ以外でもなるから関係なさそう

**Comment by tamaina** [comment]
別の問題か  
(デッキの横スクロール以外に経験したことないけど)

**Comment by tamaina** [comment]
しゅいろは今もバグってるということ？

**Comment by syuilo** [comment]
あー最近は見ない気がする

**Comment by tamaina** [comment]
ならこのissueはcloseする
