### ISSUE TITLE
Blur effect broken in firefox

### ISSUE THREAD

**Issue by nonetrix** [misskey-dev/misskey#6552]
## 💡 Summary

The blur effect on Firefox doesn't work it's just translucent this could be Firefox's fault but doing blur effects seems possible on Firefox so it should at least have a fall back

Also changing the user agent does nothing 

## 🙂 Expected Behavior

Nice blur effect :D 

## ☹️ Actual Behavior

No blur effect big sad D: 

## 📝 Steps to Reproduce

1. Download Firefox desktop or mobile
2. Open misskey
3. Look at the header bar or etc

## 📌 Environment

Firefox any version running geko
![Screenshot_20200716-055001](https://user-images.githubusercontent.com/45698918/87662768-53657a00-c728-11ea-854d-06cc6b3ff163.png)
![Screenshot_20200716-055039](https://user-images.githubusercontent.com/45698918/87662776-5a8c8800-c728-11ea-971f-4fa70aa7f35e.png)

**Comment by nonetrix** [comment]
Here's a example of something that works on Firefox and apparently IE but no uses that let's be real
https://github.com/cryptodescriptor/frosted-panel

**Comment by rinsuki** [comment]
https://github.com/cryptodescriptor/frosted-panel is supporting only one static background image, so we can't use this.
this blur actually requires backdrop-filter CSS https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter , but Firefox Android does not supporting this CSS.

see https://bugzilla.mozilla.org/show_bug.cgi?id=1178765
