### ISSUE TITLE
Error "too much recursion" occurs when preview theme.

### ISSUE THREAD

**Issue by fz0000** [misskey-dev/misskey#6557]
## 💡 Summary

Error "too much recursion" occurs when preview theme.
## 🙂 Expected Behavior

Theme should be changed.

## ☹️ Actual Behavior
Error "too much recursion" occurs.

![image](https://user-images.githubusercontent.com/5061311/87850494-39dc5200-c923-11ea-83e1-0d6918949abd.png)

## 📝 Steps to Reproduce

1. Go to https://misskey.io/theme-editor
2. Select a property. (e.g. **Background**)
3. (Important) Choose "**Reference a property**".
4. Select the default value of the property (e.g. **Background**) in the list.
5. Click Preview button.

## Additional info:
This defect doesn't occur when click Save button.

## 📌 Environment
develop

**Comment by rinsuki** [comment]
This is expected behaviour.
If you want use default value, please use "Default value" directly instead of "Reference property".

actually this error occurs in apply theme, so we can save invalid theme, but can't use.
