### ISSUE TITLE
ValidationError: The blurhash string must be at least 6 characters

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#6569]
## 💡 Summary

ValidationError: The blurhash string must be at least 6 characters @syuilo 

## 🙂 Expected Behavior

No validation error

## ☹️ Actual Behavior

```
ValidationError: The blurhash string must be at least 6 characters
    e https://misskey/assets/app.12.42.0.js:2
    o https://misskey/assets/app.12.42.0.js:2
    default https://misskey/assets/app.12.42.0.js:2
    draw https://misskey/assets/app.12.42.0.js:2
    mounted https://misskey/assets/app.12.42.0.js:2
    Vt https://misskey/assets/app.12.42.0.js:2
```

## 📝 Steps to Reproduce

1. Update to v12.42.0
2. Visit homepage
3. Error

## 📌 Environment
v12.42.0

**Comment by syuilo** [comment]
Files uploaded before Blurhash is implemented will result in an error because there is no Blurhash string.  I'll fix it by simply ignoring Blurhash.
