### ISSUE TITLE
空白文字列のみの投稿がWebから出来るにもかかわらずサーバー側ではエラーになる

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#6570]
## 💡 Summary
Web UIで本文に空白文字列のみを入力すると、投稿ボタンは有効になり投稿は許容されるにもかかわらず
実際に投稿するとサーバー側でAPIエラーになる。

## 🙂 Expected Behavior
空白文字列のみを許容しないならWeb側でも投稿ボタンを無効にする

## ☹️ Actual Behavior
Summaryに同じ

## 📝 Steps to Reproduce
1. 投稿フォームをいて、本文にスペースを入力する。
2. 投稿する

**Comment by syuilo** [comment]
> 空白文字列のみを許容しないならWeb側でも投稿ボタンを無効にする

でいきます

**Comment by mei23** [comment]
なおってる
