### ISSUE TITLE
asahi.comのOGPを表示しないように

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6574]
## Summary
朝日新聞デジタル利用規約（非会員用）（2020.7.28実施）による

> **第6条 リンクについて**
> 3. 利用者は、当社がSNSでのシェアのためにデジタル版に設定したOGP（Open Graph protocolを意味し、設定されるタイトル・テキスト・画像等の一切のコンテンツを含みます）については、当該OGPが設定されたページで当社がシェアボタンを設置したSNSのためにのみ使用できます。それ以外での使用については営利・非営利を問わず禁止します。

https://digital.asahi.com/info/guide/index09_10.html

※edited: 非会員用のものにリンクと文章を書き換え

**Comment by syuilo** [comment]
朝日新聞に限らず、インターネット上のあるサイトがOGPの利用を禁止しているかどうかプログラムから判定する術が無いので、OGP自体全て無効にしないといけなくなりそう

**Comment by rinsuki** [comment]
> 本規約は、当社が提供するデジタル版の購読申込者の申し込み、並びにデジタル版購読者によるデジタル版購読及び利用に関する一切について適用されます。

だから関係ない気もするが

**Comment by rinsuki** [comment]
それとは別で robots.txt をちゃんと読むぐらいはやってもいいかもしれない

**Comment by tamaina** [comment]
> 関係ない気もする

確かに…？

> > 「デジタル版」とは、当社が提供する電子情報サービス「朝日新聞デジタル」をいい、当社が提供するモバイル端末向けアプリサービスを含みます。
> 
> > 「デジタル版購読者」とは、本規約を承諾のうえで当社所定の方法によりデジタル版の購読を当社に申し込み、当社が購読を認めた個人をいいます。
> 
> > 本規約は、当社が提供するデジタル版の購読申込者の申し込み、並びにデジタル版購読者によるデジタル版購読及び利用に関する一切について適用されます。

当社所定の方法とかぼかして言われている以上、「デジタル版購読者」が誰を指すのかが曖昧ではある（"認証"を前提にした規約ではあるのでうーん…）

**Comment by tamaina** [comment]
そもそもタイトルに（会員用）って書いてあった（改定前は書いてないので別のがある？

**Comment by tamaina** [comment]
非会員用っていうのがあったわ

https://digital.asahi.com/info/guide/index09_10.html

**Comment by rinsuki** [comment]
> 利用者は、デジタル版へのリンクについて、営利を目的とせず、デジタル版へのリンクである旨を明記し、フレームなしで行うなど一定の条件を満たしている限り、原則として自由に行うことができます。ただし、デジタル版の趣旨に合わない場合や情報発信源を誤認させるような形でリンクを張るなど、当社の事業等を害する恐れがある場合（次項に定める方式を含む）は、リンク自体をお断りすることがあります。なお、デジタル版の編集・更新の都合により、サービス内の各ページは予告なく変更・削除されることがあり、リンクを設定いただいても、短期間でリンク切れとなる可能性もあることを、利用者はあらかじめ承諾するものとします。
> いわゆるフレームリンク、直リンク、エンベッドなど、デジタル版の内容を他サイトのコンテンツと組み合わせて表示するリンクや、デジタル版の内容が単独で表示される場合であっても、リンク先のホームページの一部として表示される形のリンク、または一般に当社の信用にかかわるようなリンクの仕方は、営利・非営利を問わず禁止します。

からするともはや asahi.com のURLの投稿を弾く必要があるのでは

**Comment by tamaina** [comment]
それをやると言論弾圧ガーって言ってきそうだわ

**Comment by tamaina** [comment]
**ブラウザでの表示の問題**なので、ユーザーが個々でワードミュート ( #6092 ) すればいいことなのではないかと思うわ

**Comment by rinsuki** [comment]
リンクは非ログインユーザーでも見れちゃうからだめじゃない?

**Comment by tamaina** [comment]
あー…

**Comment by acid-chicken** [comment]
summaly で議論した方がよさそう（この手のは Amazon も確かダメ）
