### ISSUE TITLE
画像プレビューのobject-fitをcontainに戻す

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6575]
## Summary
Blurhash実装で画像プレビューがobject-fit: cover;になったが、司法で[事件番号 平成28(ネ)10101](https://www.ip.courts.go.jp/app/hanrei_jp/detail?id=4927)が[最高裁で棄却された](https://www.courts.go.jp/app/hanrei_jp/detail2?id=89597)ことにより、判例上、サービスがデザイン上画像をトリミングすることは同一性保持権の侵害であるとされてしまった。

利用規約で画像改変について許諾をとればいい話ではあるが、面倒ごとを避けるためにはobject-fit: contain;に戻したほうが良いのではないかと思う。

Blurhashを背景に表示しておくとかで良い感じにできそう

**Comment by tamaina** [comment]
最高裁判決は同一性保持権について言及していないので、判例になったとは言えない（らしい）

**Comment by mei23** [comment]
今までcontainにしてたのは
coverの場合元画像を拡大する必要があり、元画像のサイズによっては (例えばスマホの縦長の写真とかの場合) かなり荒くなってしまうからというのがあります。
今のサムネイルサイズは、ホームのサイズを基準に全体が498x280に収まるように作成しているため、coverにする場合は見直す必要があるかと思います。
ただ、これ以上サムネイルサイズを大きくするのも考えものな気がするので、containに戻すとかでもいいと思います。

**Comment by mei23** [comment]
> 利用規約で画像改変について許諾をとればいい話ではあるが

トリミングがどうこう言われてない国から飛んでくるかもしれないし、ローカル表示時にトリミングしないインスタンスから飛んでくるかもしれない
