### ISSUE TITLE
ノートの添付画像の表示をcoverではなくcontainにしたい

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#6579]
## Summary

画像の全てを確認するのに都度クリックしてフルサイズの画像を読み込まないといけなくて不便
でもcontainだとblurhashと併用することが難しいのでアイデア募集中

**Comment by rinsuki** [comment]
blurhashと併用しづらいとは

**Comment by syuilo** [comment]
blurhashには画像のアスペクト比情報が無いから合わせられない
けどdriveFileにwidth/heightプロパティあるからそれ使えば可能かも

**Comment by tamaina** [comment]
canvas（blurhash）を背面に、imgを前面に、position: absoluteで重ねてしまえばいいんじゃない？と思ったけど、CSS的にそう簡単な話ではないのかしら

**Comment by syuilo** [comment]
新UIでやった
