### ISSUE TITLE
Misskey adds a "y" to certain words

### ISSUE THREAD

**Issue by kazukyakayashi** [misskey-dev/misskey#6584]
## 💡 Summary

On some words Misskey adds a `y`, example with `Snapchat` which becomes `Snyapchat`

![cECZipwHjC](https://user-images.githubusercontent.com/39823221/88372941-315aa000-cd97-11ea-87c3-458f4d134b66.gif)

## 📝 Steps to Reproduce

1. Write Snapchat and publish.
2. Misskey display Snyapchat.

## 📌 Environment

Misskey 12.42.0
(I don't have this problem on a Misskey instance v1.39.1)

**Comment by syuilo** [comment]
It is expected behavior.
If you turn on the Cat setting, you become a cat, and the word changes that way.

**Comment by kazukyakayashi** [comment]
Oh okay 
~~I find it annoying not to be able to keep my cat ears because of this feature really 😔~~

Edit : okay it only affects me and if I remove the chat mode the addition of the y disappears.
Sorry 😅

**Comment by acid-chicken** [comment]
Related to #2556
