### ISSUE TITLE
ノートの投稿画面が多重に開ける

### ISSUE THREAD

**Issue by akaregi** [misskey-dev/misskey#6597]
## 💡 Summary

ノートの投稿画面を開いて、<kbd>Tab</kbd>なりでフォーカスを記述画面外に飛ばした後ショートカットキー叩くと記述画面が多重に開けます。

## 🙂 Expected Behavior

投稿画面が多重に開かない

## ☹️ Actual Behavior

下記の再現手段でいくらでも開く

## 📝 Steps to Reproduce

1. ノート記述画面を開く（ボタンでもショートカットキー <kbd>N</kbd> でも）
2. <kbd>Tab</kbd> なりでフォーカスを記述画面外に飛ばす
3. <kbd>N</kbd>叩く
4. ノート記述画面の上にまた記述画面が開く
5. （繰り返しでいくらでも開けるようです）

## 📌 Environment

Misskey v12.43.0

## 備考

投稿画面に適当な文章を打ち込んで ↑ の手順で画面をまた開くと、文章が開いた画面に継承されます。そして「上にある」投稿画面で投稿しても「下にある」投稿画面の文章は消えません。これを利用して、ひたすら多重に開いて Ctrl+Enter なりで貯めた投稿を飛ばすことでスパムっぽいことがかなり簡便にできます。

**Comment by Sayamame-beans** [comment]
triage: まだあった気がする
