### ISSUE TITLE
Object Storage File Not Found 404

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#6600]
## 💡 Summary

Unable to view cdn files (maybe the url is hardcoded?)

## 🙂 Expected Behavior

Post display attached media from cdn

## ☹️ Actual Behavior

no problem adding image from cdn from post
no problem deleting image from cdn from post

Error display media in post

## 📝 Steps to Reproduce

1. post with media attachment
2. view url
3. error message and broken url

## 📌 Environment

12.44.1 with DO spaces

bucket: storage
prefix: misskey

Actual path from cdn:
`https://cdn.example.com/**storage/misskey**/thumbnail-xxxx.jpg`

Misskey posts shows:
`https://cdn.example.com/**files**/thumbnail-xxx.jpg`

**Comment by okpierre** [comment]
@syuilo is there a list of object storage providers that works for Misskey?

**Comment by rinsuki** [comment]
in this case, i think you should set Base URL as `https://cdn.example.com/**storage/misskey**/`, not `https://cdn.example.com/`

**Comment by okpierre** [comment]
@rinsuki Thank you for your help. I tried your suggestion and also many different base url but still not working.

403 Forbidden error is displayed inside Misskey media folder and in note. 

Does Misskey apply media permission?

**Comment by rinsuki** [comment]
misskey doesnt set any permission to file, so you maybe must enable public-read ACL as bucket default policy.
related https://github.com/syuilo/misskey/issues/5024

**Comment by okpierre** [comment]
reference: https://developers.digitalocean.com/documentation/spaces/#acls
