### ISSUE TITLE
Retain CW title when reply on a CW note

### ISSUE THREAD

**Issue by yitsushi** [misskey-dev/misskey#6605]
## Summary

When there is a note with CW comment/title, it has a reason why the note is behind a CW mark and most of the cases the reply should be in CW too. To add the CW with the same comment/title to keep the thread we have to copy the previous one manually, but removing it if we don't want to CW the reply would be much easier if that would be the default behavior.

So, expected behavior: Reply on CW note automatically turns on CW for the reply note and populates the Comment field with the original CW Comment field value. If we don't want to reply with CW, deleting/turning off the CW flag is much easier.

**Comment by EbiseLutica** [comment]
これv12で消えてたの気づかなかった
