### ISSUE TITLE
Mastodon等からの画像に付いているalt-textを保存しAPIで提供する

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#6606]
## Summary

とりあえずローカルユーザーからの指定はできなくても受け取ったものの保持はしておいたほうがいい

ActivityPub的にはDocumentのnameで来るらしい
<img width="529" alt="image" src="https://user-images.githubusercontent.com/6533808/88934760-f935ee80-d2bb-11ea-9b71-003c0c2e7199.png">

- `DriveFile#comment` をそのまま使う? それとも別にプロパティ生やす?

**Comment by syuilo** [comment]
commentで良いかも

**Comment by mei23** [comment]
本来こうマップするべきなのではと思うけど、Mastodonがnameで送ってきちゃうからしょうがない。

AP name <=> DB name
https://www.w3.org/TR/activitystreams-vocabulary/#dfn-name

AP summary <=> DB comment
https://www.w3.org/TR/activitystreams-vocabulary/#dfn-summary

**Comment by Johann150** [comment]
Image descriptions from Mastodon are federated, so I think this has been fixed.
