### ISSUE TITLE
KaTeX の描画処理ががうまくいっていない

### ISSUE THREAD

**Issue by akaregi** [misskey-dev/misskey#6613]
## 💡 Summary

KaTeX の描画処理がうまくいっていません。
ノート、お知らせなど全体的に死んでいます。

## 🙂 Expected Behavior

表示がまともな数式になる

## ☹️ Actual Behavior

表示が崩れる

Vivaldi：
![KaTeX + Vivaldi](https://user-images.githubusercontent.com/44235328/89098925-9b71e580-d426-11ea-887c-336b23d052d8.png)

Firefox:
![KaTeX + Firefox](https://user-images.githubusercontent.com/44235328/89099000-366abf80-d427-11ea-803d-a580b45c9508.png)

## 📝 Steps to Reproduce

1. ノートなりお知らせなりで適当な TeX 式を書く（例：`\(\KaTeX\)`）
2. 投稿する
3. 表示がバグる

## 📌 Environment

* Misskey v12.45.1
* Chrome, Vivaldi, Firefox, Safari

**Comment by syuilo** [comment]
Good catch🥰

**Comment by syuilo** [comment]
謎

**Comment by syuilo** [comment]
とりあえずkatex前のバージョンに戻すと解決しそう

**Comment by syuilo** [comment]
というよりcss-loaderの可能性

**Comment by syuilo** [comment]
https://github.com/syuilo/misskey/commit/60736bab2ac974c2d2c2c106d297fa67fdaff87a
で直った
