### ISSUE TITLE
Code display in messages 

### ISSUE THREAD

**Issue by kazukyakayashi** [misskey-dev/misskey#6616]
## 💡 Summary

The code display in the messages seems to be broken after upgrading to version 12.45.1.

## ☹️ Actual Behavior

On Misskey v12.45.1
![code01](https://user-images.githubusercontent.com/39823221/89118242-3c52b600-d4a4-11ea-8e97-5c6394b86065.PNG)

On Misskey 12.45.0
![code02](https://user-images.githubusercontent.com/39823221/89118276-acf9d280-d4a4-11ea-9d6e-4140f5b5a8b4.PNG)

## 📌 Environment

Misskey v12.45.1

**Comment by syuilo** [comment]
Thank you for your reporting!
This issue should be resolved in 12.46.0, so please check.

**Comment by kazukyakayashi** [comment]
Oh ... my bad sorry :(
