### ISSUE TITLE
ユーザーページのタブに mk-tab を使う

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6619]
ここを mk-tab で書き換えたい
https://github.com/syuilo/misskey/blob/b265cdbd8453edb65a5aab739bc4d3dfd3ce075d/src/client/pages/user/index.timeline.vue#L3-L7

**Comment by futchitwo** [comment]
今はMkTab使われてるのでcloseで良さそう
https://github.com/misskey-dev/misskey/blob/70805e00eb2b2b3af7d7460b374f270a7de627e7/packages/frontend/src/pages/user/index.timeline.vue#L4-L8
