### ISSUE TITLE
WebPのアニメーションが失われる

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#6625]
## 💡 Summary
アニメーション付きのWebPをアップロードすると、サムネイルでも公開画像でもアニメーションが失われてしまう。
もちろんオリジナルでは保持されている。

## 🙂 Expected Behavior
アニメーションが保持されている

## ☹️ Actual Behavior
アニメーションが失われてしまう

## 📝 Steps to Reproduce
1. アニメーション付きのWebPをアップロードして投稿する

**Comment by syuilo** [comment]
webpって静止画像フォーマットじゃなかったっけ？

**Comment by mei23** [comment]
アニメーションあるっぽい

**Comment by syuilo** [comment]
アニメーション使えるって情報と静止画像フォーマットって情報が混在しててよく分からんけど使えるなら対応した方が良いかも

**Comment by okpierre** [comment]
> アニメーション使えるって情報と静止画像フォーマットって情報が混在しててよく分からんけど使えるなら対応した方が良いかも

WebP Animation:
-Google Chrome (desktop and Android) 32+
-Microsoft Edge 18+
-Firefox 65+
-Opera 19+

**Comment by rinsuki** [comment]
サムネイルはアニメーション消しといたほうがいいと思う webpublicはアニメーションするべき

**Comment by okpierre** [comment]
Compare webp

913.3 kB bird png 
**138.8** kB bird webp

![bird-png-webp](https://user-images.githubusercontent.com/1679025/89435711-3dd5e580-d713-11ea-94b4-8f89b0e651d5.jpg)
```

<picture>
  <source srcset="img/bird.webp" type="image/webp">
  <source srcset="img/bird.png" type="image/jpeg"> 
  <img src="img/bird.png" alt="bird!">
</picture>
```

**Comment by mei23** [comment]
> サムネイルはアニメーション消しといたほうがいいと思う webpublicはアニメーションするべき

サムネイルのアニメーションを止める設定はクライアント側にあるんですよね。(いやv12にはないんですけど…）
