### ISSUE TITLE
画像の圧縮にwebpを使う

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#6626]
## Summary

iOSでもサポートされてきているらしいので

**Comment by mei23** [comment]
WebP未対応のバージョンのiOSのサポートはもう12.94.0で切ってることになってる
https://caniuse.com/webp
https://github.com/misskey-dev/misskey/blob/develop/CHANGELOG.md#12940-20211025

**Comment by tamaina** [comment]
これ結局どうするのかしら(ドライブまわりの変更してるので気になる)

**Comment by syuilo** [comment]
やるか

**Comment by syuilo** [comment]
AVIFも良さそうと思ったけどSafari対応してなかった

**Comment by tamaina** [comment]
リモート向けに使うにはMastodonが対応していない

https://github.com/mastodon/mastodon/pull/11589 ということらしい

**Comment by tamaina** [comment]
https://github.com/mastodon/mastodon/pull/9879 なるほど

**Comment by tamaina** [comment]
> WebP、そもそも必ずしも同等クオリティの JPEG よりファイルサイズが小さくなるとは限らない https://www.ctrl.blog/entry/webp-avif-comparison.html
> https://github.com/misskey-dev/misskey/pull/8216#issuecomment-1030840152

**Comment by tamaina** [comment]
thumbnailやproxy(Misskeyクライアントからでしか使わない)にはwebpを使うことが出来そう

**Comment by tamaina** [comment]
webpはアルファチャンネルを有効にしつつ非可逆圧縮ができるのでよい

**Comment by tamaina** [comment]
webpをjpegに変換しているためreopenする

**Comment by tamaina** [comment]
mstdn.jp: 4.1.0  
pawoo.net: 3.3.3
best-friends.chat: 3.2.1
fedibird: 3.4.1だけどwebp対応してなかった？

**Comment by tamaina** [comment]
pawoo, ベスフレぐらい古いバージョンってそもそも他の要素でも連合の障害になってきそうだし、互換性を切ってもいい気がしてきた
