### ISSUE TITLE
プッシュ通知を複数アカウント対応に

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6628]
## Summary
現状、プッシュ通知は最初に登録したユーザーのものしか受信できない。プッシュ通知も複数アカウントに対応させたい。

余談:  
プッシュ通知のendpointって端末&ドメインにつき1つらしいので、endpointの同一で同じ人物かどうかバレる可能性がありそれを嫌う人がいそうだけど、クライアント設定でそこらへんは管理できるようにすればいいか。

**Comment by rinsuki** [comment]
> endpointの同一で同じ人物かどうかバレる可能性があり

まあそもそもログちゃんと読めば UA & IP でバレそう(って思ったけどログイン履歴とか残してないんだっけ）

**Comment by tamaina** [comment]
マジで嫌ならブラウザを分ければまあバレないわね
