### ISSUE TITLE
queue deliver failed error enotfound

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#6630]
## 💡 Summary

`[queue.deliver] failed(Error: ENOTFOUND misskey) id=132113 attempts=8/12 age=4m to=https://misskey/inbox`

Showing **8/12** attempts

## 🙂 Expected Behavior

Not sure what ENOTFOUND means but maybe 1 is enough for this error?

## 📌 Environment

Misskey 12.46.0

**Comment by mei23** [comment]
ENOTFOUND はDNSエラーであり、一時的なエラーです。
(`ENOTFOUND`という名前だけど、一時的なリソース不足でも出るらしい。)
そのため、恒久的なエラーとせずリトライする必要があります。

**Comment by syuilo** [comment]
@mei23 ホストが`misskey`になっているのはMisskey側のバグではない？

**Comment by mei23** [comment]
@syuilo 
> ホストがmisskeyになっているのはMisskey側のバグではない？

これは流石にログを編集したのではないかと思ってます。
ホスト`misskey`だとフォローできないし、フォローしないとまず`sharedInbox`に送られることはないだろうし・・・

**Comment by rinsuki** [comment]
maybe https://github.com/syuilo/misskey/issues/5596

**Comment by Johann150** [comment]
This can happen when there is an error with the DNS setup and I don't think this is an issue with Misskey itself.
