### ISSUE TITLE
ストリーミングで、read...が大量に届く仕様を改善してほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6631]
## Summary
現状の実装では、subNoteのたびにreadAllUnreadMentions, readAllUnreadSpecifiedNotes, readAntenna, readAllAntennasがなんかめちゃくちゃ届いてくる。

Misskey Webはsnを大量にするので、通信量が馬鹿にならないし、このようなメッセージを受信するたびにvuexのコミットが発生するためにクライアントが重くなっているかもしれない。

**Comment by syuilo** [comment]
たしかTODOとしてソースコードに注釈してあった気がする

**Comment by tamaina** [comment]
read.tsの6行目に書いてあった

> // TODO: 状態が変化していない場合は各種イベントを送信しない

**Comment by tamaina** [comment]
vuexのコミット一覧でupdateIKeyValueがめちゃくちゃ多いからバグかなと思ったら仕様だったという…

**Comment by syuilo** [comment]
https://github.com/syuilo/misskey/pull/6621
で直ります
