### ISSUE TITLE
WebSocketをSharedWorkerにまとめる

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6633]
## Summary
SharedWorkerを使えばWebSocketの接続をブラウザに1つにまとめられるのではないか……と考えてみた。できるかは知らない。

**Comment by rinsuki** [comment]
Safari と Android Chrome がだめ https://caniuse.com/#feat=sharedworkers

**Comment by syuilo** [comment]
related: https://github.com/syuilo/misskey/issues/936

**Comment by rinsuki** [comment]
あとうまくやらないと note watch のリークが発生しそう

**Comment by tamaina** [comment]
> related: #936

そうかしら…？というか、そうではない気がする…

**Comment by tamaina** [comment]
Safari v16は対応してきたけどAndroid Chromeはなんか永久にだめそう

**Comment by rinsuki** [comment]
まあAndroidの人はFirefoxを使ってもらうということで…ダメか

**Comment by tamaina** [comment]
無理があろうと思われます

![Capture20160808-150728.jpg](https://user-images.githubusercontent.com/7973572/205524792-f308916f-58df-4245-aaac-b2245e4b113f.jpg)

**Comment by Sayamame-beans** [comment]
triage: Android Chromeは未だ非対応

**Comment by tamaina** [comment]
ウィンドウ機能できたからめっきり複数タブで使うことなくなったし要らないのでは

**Comment by tamaina** [comment]
やるきないしとりあえずclose
