### ISSUE TITLE
無条件アンテナは作成できないようにする

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#6640]
## Summary

そのようなアンテナのユースケースは無いだろうし、データベースが重くなる

**Comment by mei23** [comment]
リストも
こっちはリスト追加時点でユーザー0のリストがコミットされるUIなのでめんどくさいですが。

リストも~~アンテナも~~、条件0だったらAPIでクエリせずに`[]`返すとかでいいかも。
アンテナは過去クエリなかった。

**Comment by mei23** [comment]
「無条件アンテナ」って全部かかっちゃって全部蓄積されちゃって重い方ですね。
リストは、かからない条件のタイムラインでクエリが重くなる方なので別にしました。#6641

**Comment by EbiseLutica** [comment]
セキュリティ Issue な気がする（大量の無条件アンテナを作るだけで弱小鯖を落とせてしまいそう）

**Comment by syuilo** [comment]
それを言うと重めのAPIすべて該当しそう

**Comment by syuilo** [comment]
こにIssueが他と違う点は、負荷をかけようと意図しなくても負荷をかけてしまうことかな
例えばアンテナの設定を間違っていたりアンテナ作成途中で何も条件を設定していないとか

**Comment by syuilo** [comment]
done
