### ISSUE TITLE
npm i -g web-push は不要

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#6642]
## Summary
`web-push`コマンドを使うために`npm i -g web-push`をしているが
`web-push`はMisskeyの動作に必要→`node_modules`に必ずある ので
`npx web-push`だけでインストール済みのが実行できるのでそれで十分

なので以下は不要
https://github.com/syuilo/misskey/blob/377377595abb56f10b24db43774da4661b6e9f06/Dockerfile#L36

なお、Dockerでの`web-push`の実行方法がドキュメントされてない、そもそもv12だと非Docker/Docker問わず`web-push`の実行方法もどこにも書いてない という問題があるのでどこかに記述が必要。

v11までならこのあたりにあった
https://github.com/mei23/misskey/commit/c682095f3a6f4da5fe2c2607b9e1c087f36187ad

**Comment by rinsuki** [comment]
もはやサーバーサイドで勝手に生成&設定するボタンでもいい気がする

**Comment by KisaragiEffective** [comment]
triage: 現行だと消えている: https://github.com/misskey-dev/misskey/blob/379ce0145b9d0b74334b35fa57f2ef87366388f2/Dockerfile
