### ISSUE TITLE
streamのping messageでサーバーにエラーが出力されてしまう

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#6658]
## 💡 Summary
streamにmessageとして`ping`を送ると`pong`が返ってくるのがあって、動くけど
https://github.com/syuilo/misskey/blob/122076e8eaa5517ee3fab6caacd0d12e61654125/src/server/api/streaming.ts#L60-L64

別のイベントハンドラの方で
https://github.com/syuilo/misskey/blob/122076e8eaa5517ee3fab6caacd0d12e61654125/src/server/api/stream/index.ts#L68
`SyntaxError: Unexpected token p in JSON at position 0`が出力されてしまう

## 🙂 Expected Behavior
ちゃんと動いているのでエラーは出力されない

## ☹️ Actual Behavior
エラーが出力されてしまう

## 📝 Steps to Reproduce

1. streamにmessageとして`ping`を送る

**Comment by syuilo** [comment]
Good catch👍
