### ISSUE TITLE
通知ミュートの判定がおかしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6676]
## 💡 Summary
create-notificationサービスのisMutedの判定がおかしいっぽい？

多分だけど、includingNotificationTypesがnullの場合に判定がおかしくなる？

**Comment by tamaina** [comment]
includingNotificationTypesってそもそもどうしてnullableにしたんだろう

**Comment by mei23** [comment]
デフォルトのNULLは全許可にしないといけないからたぶんこう
```diff
- const isMuted = !profile?.includingNotificationTypes?.includes(type);
+ const isMuted = !(profile?.includingNotificationTypes == null || profile.includingNotificationTypes.includes(type));
```


> includingNotificationTypesってそもそもどうしてnullableにしたんだろう

`['follow', 'mention', 'reply', `みたいにデフォルトで全部列挙するようにしちゃうと
新しい通知種別が出来たときにそれがオフになってしまう

**Comment by tamaina** [comment]
あー、これホワイトリストだっけ

**Comment by mei23** [comment]
たぶんスキーマに、通知設定全体が未定義 と この種別の通知については未定義 の両方の概念があったほうが良かったのかなと
```
notificationTypes?: Record<string, boolean | undefined>;

if (notificationTypes == null) return true;
if (notificationTypes[key] == null) return true;
return notificationTypes[key];
```

**Comment by tamaina** [comment]
そもそもブラックリスト形式でよかったような気も

**Comment by mei23** [comment]
excludeNotificationTypes でよかったのかも

**Comment by tamaina** [comment]
直接コミットした(
