### ISSUE TITLE
デッキ(deck)でアンテナカラムを追加すると操作不能になる

### ISSUE THREAD

**Issue by tokaritami** [misskey-dev/misskey#6682]
## 💡 Summary

デッキを開いてからカラム追加→アンテナを選択するとページがクリックに反応しなくなる

## 📌 Environment

環境 windows10 
firefox80.0(64bit) 
GoogleChrome85.0.4183.83(64bit)

**Comment by syuilo** [comment]
直ってそうなのでclose
