### ISSUE TITLE
ノートの詳細画面でのノートの投稿日時の表示を復活してほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6686]
## Summary
PCなら「n時間前」をホバーすれば見えるけど、スマホだと「n時間前」のところをロングタップしても見られないので  
（すくなくともAndroid Chromeだと）

**Comment by syuilo** [comment]
これかな
https://github.com/syuilo/misskey/issues/6520

**Comment by syuilo** [comment]
やった
