### ISSUE TITLE
Drop ElasticSearch support

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#6689]
## Summary

- なんもわからん
- メンテできない
- データの二重管理になる
- なくてもサーバー管理者が設定すればPostgreSQLで全文検索できる

## TODO

- [ ] PostgreSQLでの高速な全文検索を自動で設定するようにするか、設定方法をドキュメント化する

**Comment by AlfredSK** [comment]
I support the idea. :-)

A user of my ~~instance~~ server found out that the full text search results are more or less unrelated to the actual search term if Elasticsearch is used by ~~the instance~~ Misskey. For example when you search for `water` or some other word you get a lot of results without the word `water`.

I tried to search directly in the Elasticsearch index by using `curl` on command line. The results were ok. But in Misskey the results seem to be completely unrelated to the search term.

So I disabled Elasticsearch in Misskey's config file and stopped the Elasticsearch service.

W/o Elasticsearch the results are as expected - I only get notes that contain the search term. Much better.

Also, the performance of a full text search isn't significantly worse. It is slower but not much slower. 

Bottom line: Elasticsearch is superfluous - even if it would work properly. The small performance improvement does not justify the additional effort to set it up and also does not justify the additional memory usage.

**Comment by tamaina** [comment]
これどうよ

**Comment by mei23** [comment]
どれよ

**Comment by mei23** [comment]
> なんもわからん
> メンテできない
> データの二重管理になる

同意

> なくてもサーバー管理者が設定すればPostgreSQLで全文検索できる

結構大変かなと

**Comment by syuilo** [comment]
現状、ESがなくても、かつ管理者が特別な設定をしないでも、PostgreSQLで(パフォーマンスは悪いけど)全文検索できたはず

**Comment by tamaina** [comment]
> パフォーマンスは悪い

自鯖だとノート数少ないからそこそこ動いちゃうんだよな…  
でも機能が貧弱

**Comment by syuilo** [comment]
アンケート中
https://misskey.io/notes/8pxzbgeihv

**Comment by syuilo** [comment]
意外とES使ってるインスタンスが多いなあ
メンテはできないけど残しておくべきか否か

**Comment by tamaina** [comment]
Deprecatedをアナウンスしておいて、ESにかかわるコードを変更する必要が出てきたら実際に廃止する、みたいな感じでいいのでは

**Comment by syuilo** [comment]
DeprecatedするからにはPostgreSQLに移行するにあたっての最低限の指針的なもの(こういうふうに設定すれば高速に全文検索できるよ)は用意しておきたい

**Comment by tamaina** [comment]
メモリの量？とも思ったんだけど1割(2.4GB)しか使っていないらしい

**Comment by tassoman** [comment]
I hope PGSql full-text search can be an optional feature. 
In my instance there are notes in different languages (:it: :fr: :uk: :jp: ). 
As far I know, extension configuration is unique for one language. I prefer to stay with original search.
Inside [pleroma, they do like this](https://docs.pleroma.social/backend/configuration/howto_search_cjk/)

**Comment by syuilo** [comment]
した
