### ISSUE TITLE
Twitterのようにテーマカラーを指定できるようにする

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#67]
#f76d6cあたりのピンクが指定されているのを、個人設定で変えられるようにしてほしい。

**Comment by syuilo** [comment]
昔のMisskeyにはあったんだけどね〜

**Comment by syuilo** [comment]
現時点でRiotがスタイル中に式を展開するようになっていないため厳しそう
将来的にRiotがそれをサポートすれば...

**Comment by rinsuki** [comment]
@syuilo Vue.jsになりましたがどうですか

**Comment by syuilo** [comment]
Vue.jsでもCSS中に変数を埋め込むことはできないので厳しいことに変わり無さそう

**Comment by rinsuki** [comment]
CSS variableを使えばできそう

**Comment by syuilo** [comment]
CSS variableではある色を薄めたりとかそういった操作が行えない

**Comment by rinsuki** [comment]
あーたしかに...

**Comment by syuilo** [comment]
Service Worker案が一番現実的そう

**Comment by marihachi** [comment]
これテーマ機能によって実現済みだと思います

**Comment by acid-chicken** [comment]
Twitterのテーマカラーは設定したユーザーが他のユーザーに対しても効力を持っている気がする
