### ISSUE TITLE
連携アプリ通知がストリーミング以外で反映されない

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6702]
## 💡 Summary

連携アプリからの通知生成（notifications/create呼び出し）による通知が、ストリーミングには流れてくるものの、

- i/notifications のレスポンス
- SW通知

には流れてこない

## 📝 Steps to Reproduce

1. https://misshaialert.xeltica.work に登録
2. アラートタイプを「Misskey に通知」にする
3. 連携先インスタンスを開く
4. [アラートをテスト送信] ボタンを押す
5. 通知が流れてきている（ストリーミング）
6. 再読込する
6. 通知がいない

## 📌 Environment

Misskey v12.47.1

**Comment by syuilo** [comment]
(まだコード見ていないけど、現時点で)謎

**Comment by EbiseLutica** [comment]
もしかして #6647 の所為だったりする...?

**Comment by EbiseLutica** [comment]
ローカルでは再現しない（misskey.io, groundpolis.app, yuzulia.xyzで再現）

WHAT'S UP????????????????????

**Comment by syuilo** [comment]
ローカルのバージョン(ブランチ)は何？

**Comment by EbiseLutica** [comment]
develop でやっていたけど、そういえばって思ってmaster(12.47.1)に戻した後　という状況

**Comment by syuilo** [comment]
おそらくデータベースのマイグレーションスクリプトにミスがありそう

**Comment by EbiseLutica** [comment]
原因がわかったので共有。以下の2つのうちどちらかを満たすと少なくとも表示できなくなる

* 一人でもインスタンスに凍結者がいる
* 自分が誰かをミュートしている

この辺の処理が原因？

https://github.com/misskey-dev/misskey/blob/master/src/server/api/endpoints/i/notifications.ts#L97-L100

**Comment by syuilo** [comment]
> 原因がわかったので共有。以下の2つのうちどちらかを満たすと少なくとも表示できなくなる
> 
> * 一人でもインスタンスに凍結者がいる
> * 自分が誰かをミュートしている
> 
> この辺の処理が原因？
> 
> https://github.com/misskey-dev/misskey/blob/master/src/server/api/endpoints/i/notifications.ts#L97-L100

👍👍👍
