### ISSUE TITLE
リアクションピッカーカスタマイズのGUIをリッチにする

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6704]
#6699 と競合します

文字だけで説明するには難しかったので挿絵付きで提案します

<img src="https://user-images.githubusercontent.com/7106976/93490501-82c07f00-f943-11ea-98cd-17b7a764d96d.jpg" height="400"/>

- ①実際のリアクションピッカー同様に5列任意行の絵文字が表示されます
  - ピッカーをドラッグして絵文字を並び替えられます
- ② ①の絵文字をこのゴミ箱にドラッグすることで削除できます
- ③ 絵文字のショートコードを入力（リアクションの下部と同様）して、①に絵文字を追加します。[+]ボタンは無くても良さそう？
- ④ 絵文字ピッカーから絵文字を選び、①に追加します

あと挿絵に追加忘れていましたが、[保存] ボタンもあったほうが良い

**Comment by syuilo** [comment]
絵がかわいい

**Comment by syuilo** [comment]
理想はそうだなぁ
実装が面倒そうだからテキストエリアでお茶濁してた

**Comment by EbiseLutica** [comment]
やってみたい
