### ISSUE TITLE
moment.js をやめる

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6708]
moment.js はバンドルが肥大化しやすい特徴を持つ

## 代替案

[dayjs](https://github.com/iamkun/dayjs/blob/master/docs/ja/README-ja.md) を試したい

dayjs は moment.js とAPI互換性があるらしくさくっと移行して試験運用するに値しそう

[比較記事](https://qiita.com/yagi_suke/items/2848c8981ea6d9f26587#%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%94%E3%81%A8gzip)によれば、gzipしたファイルサイズは15%に、未圧縮のファイルサイズは5%に縮まるっぽい

**Comment by mei23** [comment]
v12はmoment.js使ってないはず

**Comment by rinsuki** [comment]
https://github.com/syuilo/misskey/pull/5215 でやめてる

**Comment by rinsuki** [comment]
と思ったが chart.js が moment に依存してるな

**Comment by EbiseLutica** [comment]
webpackのマップにおるよな...って思ったらそういうことか

参考: https://github.com/tokyo-metropolitan-gov/covid19/issues/2079

**Comment by syuilo** [comment]
Code splittingして初期バンドルに含めないようには出来そう

**Comment by syuilo** [comment]
chart.js v3にしたから消えたかも

**Comment by syuilo** [comment]
仮にchart.jsが依存してても

> Code splittingして初期バンドルに含めないようには出来そう

は達成してるしcloseで良さそう
