### ISSUE TITLE
アスタリスクによる斜体がアルファベット以外で機能しない

### ISSUE THREAD

**Issue by akaregi** [misskey-dev/misskey#6709]
## 💡 Summary

MFM には `*...*` による斜体が実装されているっぽいのですが、これがアルファベット以外で動きません。
何故か `<i>...<i>` では他の文字でも動きます。

cf. https://m.fedyya.net/notes/8ckofgv6ca
![italic](https://user-images.githubusercontent.com/44235328/94181989-3fce5080-fedb-11ea-800c-9f2c94a6f1e2.png)

## 🙂 Expected Behavior

（上の投稿を元にすると）

アルファベット: *alphabet*
キリル文字: *Кириллица*
仮名: *あいうえお*

## ☹️ Actual Behavior

アルファベット: *alphabet*
キリル文字: \*Кириллица\*
仮名: \*あいうえお\*

## 📝 Steps to Reproduce

1. ロシア語なりを話そうとする
2. 斜体を混ぜる
3. 斜体にならない

## 📌 Environment

Misskey 12.47.1, Vivaldi

## 備考

MFM の仕様が[`@aqz@yuzulia.xyz`氏](https://yuzulia.xyz/@aqz/pages/mfm)のそれ以外に見当たらないのですが、どこかにありますでしょうか？`*...*` という斜体記法自体がこの仕様にはないのでどの挙動が正しいのかよくわかりません。

**Comment by syuilo** [comment]
MFM の仕様についての公式なドキュメントは今のところありません。
アスタリスクによる斜体がアルファベット以外で機能しないのは仕様です。
アスタリスクは顔文字などでも使われ、アルファベット以外の文字列を許可すると誤認識が発生すると考えられるためです。

**Comment by syuilo** [comment]
`<i>`だけにしても良いかもしれない

**Comment by marihachi** [comment]
これ仕様だからCloseで良さそう
