### ISSUE TITLE
/streamingに非WebSocketリクエストが来た場合にキャッシュ可能としてbase htmlを返してしまう

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#6718]
## 💡 Summary

`/streaming?i=~`のようなWebSocketと同じパスに非WebSocketリクエストが来た場合に
base htmlを`Cache-Control: public, max-age=300`で返してしまいこれがnginx等でキャッシュされてしまうと
同パスにWebSocketリクエストが来てもキャッシュから返してしまい、しばらくStreaming接続が出来なくなる。

- 非WebSocketが起きる起因は不明、本当に非WebSocketで飛んできたのか or なぜかMisskey側でWebSocketとしてハンドル出来ないことがあるのか も不明。
  ただし来てしまった場合にキャッシュ可能として返すのはよくない
- nginx等でキャッシュされるかは設定によるが、今のサンプルConfigならキャッシュされる。

## 🙂 Expected Behavior
/streamingに非WebSocketリクエストが来たら、異常系ステータス＋キャッシュ不可として返す。

## ☹️ Actual Behavior
200で`Cache-Control: public, max-age=300`を返してしまう

## 📝 Steps to Reproduce

1. フロントエンドにnginxを使用し、サンプルのconfigで構成する。
2. Misskeyを起動してブラウザから接続する。
3. 接続してきた`/streaming?i=`のパスに対して、curl等で通常のHTTPリクエストを行う。
4. ブラウザをリロード後はストリーミングに接続出来ず、投稿などしても投稿が流れてこない状態になる。

## 📌 Environment
Misskey v10, v11, v12 で確認

**Comment by acid-chicken** [comment]
一応共有

Cloudflare でリクエストをせき止めるワークアラウンド
--

1. Cloudflare Workers でスクリプト部に `addEventListener('fetch',e=>(e.request.headers.get('Connection')||'').toLowerCase()=='upgrade'&&(e.request.headers.get('Upgrade')||'').toLowerCase()=='websocket'||e.respondWith(new Response(null,{headers:{Upgrade:'websocket'},status:426})))` を持つ Worker を作成。 ![image](https://user-images.githubusercontent.com/20679825/94653477-97831680-0336-11eb-812f-23e1c20c12ad.png)
2. ホストドメインの Workers 設定で `example.tld/streaming` に対して先ほど作成した Worker を割り当てる。 ![image](https://user-images.githubusercontent.com/20679825/94653598-c7cab500-0336-11eb-86ba-49317d39b894.png)

**Comment by mei23** [comment]
Cloudflare => nginx => Misskey の構成で
稀にupgradeがないリクエストが飛んでくることがあってそれが非WebSocket扱いになるみたい

OK
```
GET /streaming?i=!xxx HTTP/1.1
Upgrade: websocket
Connection: upgrade
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: xxx
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
```

NG
```
GET /streaming?i=!xxx HTTP/1.1
Connection: close
sec-websocket-version: 13
sec-websocket-key: xxx
```

↑ nginx => Misskey のキャプチャで、ヘッダーの大文字小文字の違いも流れていたまま

**Comment by acid-chicken** [comment]
Memo: 原因に関しては引き続き要調査（これ以外の問題を孕むかもしれない）
