### ISSUE TITLE
Cannot reply mastodon instance 

### ISSUE THREAD

**Issue by CGsama** [misskey-dev/misskey#6727]
## 💡 Summary
When reply a note from a mastodon site with the pop up redirection, it fails. And an error generated in the server log: 

```
{
"e": {
"code": "StatusCodeError",
"message": "StatusCodeError: 401 - "Request not signed", url=https://some remote note url"
},
"ep": "ap/show",
"ps": {
"i": "some token",
"uri": "https://some remote not url"
}
}

```

**Comment by mei23** [comment]
Please write a specific URL.
Maybe the other Mastodon instance has ActivityPub secure mode enabled.
You can't get posts for that instance because it's incompatible.

**Comment by mei23** [comment]
https://docs.joinmastodon.org/admin/config/#basic
AUTHORIZED_FETCH
LIMITED_FEDERATION_MODE

**Comment by CGsama** [comment]
Ah that is the reason! Is there any plan to implement the signing process in future Misskey release? Thank you

**Comment by mei23** [comment]
In my opinion, even if implemented ...
This has the disadvantage of slowing down communication to most Mastodon instances, but I can't find the instance I need.
So I don't want to make it the default.

**Comment by CGsama** [comment]
bgme.me, this instance seems have turn it on
