### ISSUE TITLE
[vue-i18n] Not found 'isAdmin' key in 'en-US' locale messages.

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#6734]
## 💡 Summary

[vue-i18n] Not found 'isAdmin' key in 'en-US' locale messages.

## 📝 Steps to Reproduce

1. login
2. visit your profile 
3. error

## 📌 Environment

Misskey v12.48.1

![fallbacktotranslateerror](https://user-images.githubusercontent.com/1679025/96358297-bc67df80-10d3-11eb-87ab-21bf6a10e352.png)

**Comment by syuilo** [comment]
Thank you for reporting.
This is a temporary issue until the translation is completed.
