### ISSUE TITLE
Uncaught (in promise) TypeError: t is null

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#6735]
## 💡 Summary
Uncaught (in promise) TypeError: t is null

## 📝 Steps to Reproduce

1. open misskey
2. visit channel https://misskey.io/channels
3. error 

## 📌 Environment

Misskey v12.48.1

![type-error-t-is-null](https://user-images.githubusercontent.com/1679025/96358525-179ad180-10d6-11eb-96b2-43b5c97989ca.png)

**Comment by Johann150** [comment]
Can not reproduce, seems to have been fixed.
