### ISSUE TITLE
docker-compose buildに失敗します

### ISSUE THREAD

**Issue by kaias1jp** [misskey-dev/misskey#6736]
## 💡 Summary

docker-compose buildを実行すると./built/meta.jsonが見つからないというエラーが出て失敗する

## 🙂 Expected Behavior

docker-compose buildを実行すると問題なく成功する

## ☹️ Actual Behavior

RUN yarn buildで「./built/meta.jsonが見つからない」というエラーの後yarn buildが失敗する

## 📝 Steps to Reproduce

1.docker-compose buildを実行する

## 📌 Environment

x64のUbuntu Server 20.04のDocker環境で発生します。
なお、Dockerfileの「RUN yarn build」の前の行に「COPY ./src/meta.json ./built/」を挿入して実行したら成功しました。

**Comment by acid-chicken** [comment]
多くの場合、yarn build 時に gulp のタスクで ./built/meta.json が ENOTFOUND になるのは、その前タスクである webpack が失敗して成果物を出力できていないために発生している問題なので、webpack のエラーログを確認してみてください。

**Comment by kaias1jp** [comment]
ありがとうございます。Dockerfileに自分で挿入した行を削除してもう一度docker-compose buildしましたが今度は正常終了します。念のためdocker-compose build --no-cacheも試しましたが正常終了しました。この環境でdocker run --rm misskey_web npm run webpack --colorも試してみましたがエラーは発生しませんでした。他にdocker環境でのwebpackの過去のエラーログを確認する方法がありましたら教えてください。

**Comment by kaias1jp** [comment]
先程12.48.2にしてdocker-compose buildしましたがエラーは発生せず正常に動作しましたので一旦クローズします。
