### ISSUE TITLE
Button Issues On Settings Page

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#6740]
## 💡 Summary

Buttons alignment, button spacing and move save button before test email

![misskey-settings-button](https://user-images.githubusercontent.com/1679025/96387959-ed97ec80-1173-11eb-9d0b-58f126639b06.png)

## 📝 Steps to Reproduce

1. Go to http://www.example.com/instance/settings/
2. View buttons from desktop (alignment)
3. View buttons on mobile (spacing)

![misskey-settings-button-mobile](https://user-images.githubusercontent.com/1679025/96388066-70b94280-1174-11eb-8983-b62b026edeed.png)

## 📌 Environment

Misskey v12.48.1

**Comment by syuilo** [comment]
fixed
