### ISSUE TITLE
タイムラインのノートが特定条件で大きくなる

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6750]
## 💡 Summary

タイムラインページが非アクティブなときにバックグラウンドで追加されたノートが、タイムラインに戻ったときに文字の色やマージンが大きく見える（PCでのスタイルが当たってるように見える）

iPhone Safariで確認。おそらくスマートフォン対応の不具合と見られるが、Androidや、幅を極端に狭くしたPCのブラウザでも再現するかは未検証

## 🙂 Expected Behavior

いかなるときも適切なサイズで描画される

## ☹️ Actual Behavior

上記の条件にて、ノートのデザインが崩れる

## 📝 Steps to Reproduce

1.タイムラインページを開く
2.通知ページを開く
3.しばらく待つ
4.タイムラインページを開く

## 📌 Environment

- iPhone SE (2世代)
- iOS 14.0.1
- Misskey 12.48.2

**Comment by syuilo** [comment]
これだね
https://github.com/vuejs/vue-next/issues/2349

**Comment by EbiseLutica** [comment]
なるほど既知

**Comment by tamaina** [comment]
DOMがなくてもmatchMedia等を使って画面幅で判断するようにすれば、スマホでなら解決可能な気がする

**Comment by tamaina** [comment]
ContainerQueryで解消されたはず
