### ISSUE TITLE
Support request: What are the minimal hardware recommendations?

### ISSUE THREAD

**Issue by AlfredSK** [misskey-dev/misskey#6761]
Hello there,
I couldn't find any information about the recommended minimal resources for running a Misskey server. So I decided to ask here.

I'm planning to run a Misskey instance on a VPS. Now I'm wondering how much memory, cpu, storage etc. is needed for a small Misskey instance?

Unfortunately, I have no experience with Node.js and PostgreSQL (I'm a PHP-MariaDB-person ;-) ). So, I'm pretty clueless about how much memory is necessary to maintain good performance.

The options for a VPS are...
2 cores, 8 GB RAM, 80 GB SSD
4 cores, 8 GB RAM, 160 GB SSD <-- my current preference
4 cores, 16 GB RAM, 160 GB SSD

What do you think or recommend?

**Comment by syuilo** [comment]
It depends on the number of users, but I think that 8GB of memory is enough.

**Comment by AlfredSK** [comment]
Thank you!

> It depends on the number of users

Well, I will start with one user. ;-)

**Comment by rinsuki** [comment]
If you have a only few users, I think misskey should work with more cheap specs machine (e.g. 2GB or 4GB RAM server).

**Comment by AlfredSK** [comment]
Thank you for your support. It's up! 🎉💃🚀


![image](https://user-images.githubusercontent.com/3656054/97096350-2bf94400-166b-11eb-94c6-6ed8c795081c.png)
