### ISSUE TITLE
Forgot admin password.

### ISSUE THREAD

**Issue by wiredsis** [misskey-dev/misskey#6775]
Hey so I forgot what my (admin) password was *haha*. Is there a way to change it from CLI?

**Comment by wiredsis** [comment]
Wait. This is a bigger issue actually. No accounts work. I'm gonna have to open this as a bug.

**Comment by wiredsis** [comment]
Nvm this is NOT a bug, but me being dumb :P

**Comment by wiredsis** [comment]
Ok I created a second account, gave it admin and when I go to change my password, this happens.
https://pog.gay/i/l1fe.png
Any help?

**Comment by rinsuki** [comment]
can you check server logs?

**Comment by wiredsis** [comment]
Where are logs located at?

**Comment by rinsuki** [comment]
how do you running misskey? if you are using docker-compose, you can check logs with `docker-compose logs -f`

**Comment by wiredsis** [comment]
Running it as shown on setup.en.md. Using systemd to start it.

**Comment by wiredsis** [comment]
oh yup and there we go. that's the issue https://pog.gay/i/e4a4.png

**Comment by rinsuki** [comment]
you can see logs with `journalctl -u misskey` (maybe required `sudo`)

**Comment by wiredsis** [comment]
yup i looked at them with `systemctl status misskey.service`. the issue is i can't reset the password of another admin. is there a way to circumvent this protection or just demote an admin?

**Comment by rinsuki** [comment]
for force demote an admin, execute SQL `UPDATE "user" SET "isAdmin" = false WHERE id='<user id>'` (replace `<user id>` to actual user id. user id is like 8xxxxxxxx, not `admin`).

**Comment by wiredsis** [comment]
wait. i modified mark admin and it works! i may do a pull request of this slightly modified script. so yup. thanks for the help!
