### ISSUE TITLE
Interface does not refresh itself for some reason

### ISSUE THREAD

**Issue by fabiscafe** [misskey-dev/misskey#6784]
## 💡 Summary

After installation of misskey, I noticed that my global stream only refreshes, when I actually reload the site (F5). That messages or announcements or whatever don't show up before that. That green notification point also does not disappear after I read the message either (I have to reload the site also). So it feels like something is wrong but I cant find a cause in the logs.

## 🙂 Expected Behavior
Global stream should "roll in" all the times. Interface should refresh itself.

## ☹️ Actual Behavior

Nothing new rolls in, I need to reload the site to see new content

## 📝 Steps to Reproduce

1. Login
2. Switch to global stream
3. Wait…

## 📌 Environment
Linux, Debian 10
npm 6.14.8
yarn 1.22.5
nodejs v14.15.0
misskey git master
Setup using a nginx reverse proxy (but it also doesn't work if I go directly to $url:3000)

**Comment by wlt233** [comment]
I have the same problem and wonder the solution 🤔

**Comment by wlt233** [comment]
I've found a solution. In my situation it's a Websocket conection problem.

Checkout the console of you browser and see if there's some problem with Websocket. If that, maybe you have a wrong Nginx proxy config. Just add:
```
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
```

**Comment by fabiscafe** [comment]
I cant very, because I've switched away from misskey. 
The lines
```
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
```
Where part of my setup. So maybe there was something else missing. Sadly I can't check that out anymore. So if this is fixed for you I'll close it, since it's at least a solution to the problem. Thanks! :+1:

**Comment by wiredsis** [comment]
Even after using the fix mentioned I still can't get Misskey to refresh by itself sadly.
