### ISSUE TITLE
HTL→GTL→HTLと移動した時にHTLに再接続されない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#6788]
## 💡 Summary
HTL→GTL→HTLとタイムラインを移動した時に、ストリーミングのHTLのチャンネルに接続されてない状態になる。

## 🙂 Expected Behavior
HTLに戻ってきた時にHTLのチャンネルに再接続される

## ☹️ Actual Behavior
HTLに戻ってきた時にHTLのチャンネルに再接続されず、投稿などが流れない状態になる。

## 📝 Steps to Reproduce

1. ホームタイムラインを開く
2. グローバルタイムラインに移動する
3. ホームタイムラインに移動する

## 📌 Environment

v12.51.0
Windows 10
Firefox / Chrome

**Comment by kabo2468** [comment]
GTLだけではなくアンテナやリストに移動したあとでも同じことが起こる

**Comment by syuilo** [comment]
移動した時に切断はされる？

**Comment by kabo2468** [comment]
![image](https://user-images.githubusercontent.com/28654659/97773882-e078f580-1b96-11eb-8a44-5a3472587c96.png)
される

**Comment by syuilo** [comment]
このコミットで直ったっぽい
https://github.com/syuilo/misskey/commit/c055b4d32dbe719134228f13cb711ce5d11d5525
