### ISSUE TITLE
Development Build of vue-i18n Warning Message

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#6794]
## 💡 Summary

You are running a development build of vue-i18n.
Make sure to use the production build (*.prod.js) when deploying for production.

## 📌 Environment

Misskey v12.51.0

**Comment by syuilo** [comment]
これ謎。vue-i18n側の問題な気がしている

**Comment by rinsuki** [comment]
どうにかして .prod.js を読んで欲しいんだろうけどどうやって読むのかは謎 https://cdn.jsdelivr.net/npm/vue-i18n@9.0.0-beta.6/dist/

**Comment by syuilo** [comment]
vue-i18nをやめた
