### ISSUE TITLE
How to get / build a working misskey docker image?

### ISSUE THREAD

**Issue by pwFoo** [misskey-dev/misskey#6796]
## 💡 Summary

It' more a question than a bug...
**How do I get a working misskey docker image to run as docker swarm container?**

I try to run misskey inside of docker / swarm container, but start fails. Image build from misskey github repo and misskey/misskey image (think pre-configured---?!)  doesn't work.

## 🙂 Expected Behavior

Get running misskey instance...

## ☹️ Actual Behavior

Custom build from misskey github repo gets created, but not started?
Existing image misskey/misskey stops with the following error.

```
# docker logs -f a7633d345e73

> misskey@12.51.0 migrateandstart /misskey
> npm run migrate && npm run start


> misskey@12.51.0 migrate /misskey
> ts-node ./node_modules/typeorm/cli.js migration:run

Error during migration run:
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:577:3)
    at tryReadSync (fs.js:353:20)
    at Object.readFileSync (fs.js:390:19)
    at Object.load [as default] (/misskey/built/config/load.js:20:37)
    at Object.<anonymous> (/misskey/built/config/index.js:4:33)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Module.m._compile (/misskey/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Object.require.extensions.<computed> [as .js] (/misskey/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:1049:32) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! misskey@12.51.0 migrate: `ts-node ./node_modules/typeorm/cli.js migration:run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the misskey@12.51.0 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-01T19_31_52_168Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! misskey@12.51.0 migrateandstart: `npm run migrate && npm run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the misskey@12.51.0 migrateandstart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-01T19_31_52_195Z-debug.log
```
No access to debug log because it's inside of a docker swarm container. I need to add a volume to have a persistent debug log...

## 📌 Environment

ubuntu and rancheros docker host.

**Comment by rinsuki** [comment]
How do you mount your .config?

this error comes from here.
https://github.com/syuilo/misskey/blob/666c8c0498c97b3605072cdfeb2e3b506124dd29/src/config/load.ts#L23
and this source code trying to read (`.config/default.yml`) as *file*, but it fails to read it because your `.config/default.yml` is a directory.

**Comment by pwFoo** [comment]
Thanks, should bei a file... I'll check...

**Comment by pwFoo** [comment]
Thanks! It was really created as directory and so can't work...
Started and reachable with misskey/misskey image!
