### ISSUE TITLE
scv41のChromeで上のタブからカラム移動すると上のアイコンの表示が乱れる

### ISSUE THREAD

**Issue by Kami-0x10** [misskey-dev/misskey#6799]
## 💡 Summary
scv41のChromeで上のタブからカラム移動すると上のアイコンの表示が乱れる。
## 🙂 Expected Behavior
他の端末では状況を再現できなかった。　端末の問題なのかなぁ...
## ☹️ Actual Behavior
<img src="https://sakura-jk.tokyo/files/3b00f9b5-c17d-49d6-9607-ff4ff3a0f3b2"  alt="状況">
## 📝 Steps to Reproduce

1.scv41のChromeでmisskeyにログインする。
2.上のアイコンをランダムで適当に押し続ける。
3.表示が乱れる。

## 📌 Environment
バージョン:Misskey 12.52.0
端末:scv41 Android10
Chromeバージョン:86.0.4240.110
状況を再現できる方、ご協力お願いします。

**Comment by tamaina** [comment]
グラフィックの問題…？

Note: SCV41（Galaxy S10 au）のSoCはSnapdragon855

**Comment by rinsuki** [comment]
そういう表示崩れなんかわりとWebKit/Blink系でありがちなイメージ

**Comment by Kami-0x10** [comment]
詳しくないのでわかりません()
同じSoC(Snapdragon855)を積んだGalaxy Foldでも試してみましたが、とくに表示乱れみたいなことにはなりませんでした。

**Comment by Kami-0x10** [comment]
続報です。
Xiaomi Mi Note 10でも同じように表示崩れしました。
<img src="https://sakura-jk.tokyo/files/e2afbf54-8005-4a5a-b53b-08048326bd01" alt="状況">
これってなおせないんでしょうか？

**Comment by Kami-0x10** [comment]
すみません、
chrome://flags/#disable-accelerated-2d-canvas
を
Disable
にしたらなおったっぽいので閉めます。
また何かあったらissue送るのでよろしくです。
