### ISSUE TITLE
メッセージの内容が表示されていない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#68]
誤表示？バグ？
![2](https://cloud.githubusercontent.com/assets/7973572/22251848/9692e9b0-e28f-11e6-9708-b858dc8f4052.PNG)

----

* FireFox Dev
* デスクトップ版Misskey

**Comment by tamaina** [comment]
気になるので消してほしいですん

**Comment by syuilo** [comment]
未読のメッセージがありますね

**Comment by tamaina** [comment]
(元の題名)
> ナビゲーションバーの[メッセージ]の横の🔴

→**メッセージが表示されてなかった所以でした。**
