### ISSUE TITLE
Theme Settings Reset To Default

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#6802]
## 💡 Summary

**Unable to save theme settings**

## 📝 Steps to Reproduce

1. visit settings - theme
2. select theme 
3. login on another PC
4. default theme is displayed instead

## 📌 Environment

Misskey v12.53.0

**Comment by syuilo** [comment]
このIssueが作成された時点では、テーマはアカウントではなくブラウザに保存されるため、これは仕様です。
ただ、現在のバージョンではテーマはアカウントに保存されるようになりました 🎉
