### ISSUE TITLE
Person#discoverable フィールドを尊重する

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6806]
https://docs.joinmastodon.org/spec/activitypub/#discoverable

もし false なら、「見つける」ページに表示されないようにしたい

## 実装案

1. User#isExplorable フィールドを生やす
2. Person オブジェクト変換時に Person#discoverable を User#isExplorable として表現する
3. `User#isExplorable === false` の場合、「みつける」ページから除外する

## 脱線

副産物として、Misskeyユーザーの「みつける」への反映も除外できるようになりそうなので実装したい

**Comment by EbiseLutica** [comment]
マストドン拡張なので、わざわざ採用する必要あるかどうかわからないけど...。

**Comment by syuilo** [comment]
仕様として標準化されたらやるでよさそう

**Comment by mei23** [comment]
```diff
- もし true なら、「見つける」ページに表示されないようにしたい
- User#isExplorable === true の場合、「みつける」ページから除外する

+ もし false なら、「見つける」ページに表示されないようにしたい
+ User#isExplorable === false の場合、「みつける」ページから除外する
```
かな

**Comment by mei23** [comment]
たぶん `discoverable: true` で送らないとMastodonの (ユーザー) ディレクトリには表示されない。
Mastodonではopt-in。
実質 opt-in / opt-out がお互いに違うので、単純にマップすると悩ましいことになる。

**Comment by mei23** [comment]
別にMisskeyをopt-inで実装するでもいいのかも


> 仕様として標準化されたらやるでよさそう

鍵垢ですら標準じゃないのでまずないと思います

**Comment by mei23** [comment]
> 副産物として、Misskeyユーザーの「みつける」への反映も除外できるようになりそうなので実装したい

これをopt-inで入れれば relay.actor のような特殊ユーザーを「みつける」から除外できるので良いかなと思いました。

**Comment by syuilo** [comment]
やるか

**Comment by mei23** [comment]
やろうと思ってた

これはv10だけど
https://github.com/mei23/misskey/commit/e7437fb2e8b459d1b8e464636f455231d9a5171a
https://github.com/mei23/misskey/commit/46edb4b59067102dd7cfc11190ad98a5649511be
