### ISSUE TITLE
リポストされた投稿にリアクションを付けた場合に即座にリアクション数がインクリメントされない

### ISSUE THREAD

**Issue by otofune** [misskey-dev/misskey#681]
モバイル版で確認。これは面倒な問題だと思う。リポストされた投稿自体にはリポストでラップされてるものにリアクションをつけても更新される。

**Comment by otofune** [comment]
repostされた方でリアクションをつけ、本体はリアクション数が更新される図
![screenshot_20170811-063157 2](https://user-images.githubusercontent.com/15062473/29193100-df9a3c56-7e5e-11e7-987f-4f2b5f138f78.png)

**Comment by syuilo** [comment]
Duplicate of #304 ?

**Comment by otofune** [comment]
@syuilo キャプチャ機構って言うのか、それはともかくdupだと思う

**Comment by syuilo** [comment]
でもこちらのIssueの方が分かりやすいのでタイトルなどコピーします
