### ISSUE TITLE
CHANGELOG.mdを復活してほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6810]
## Summary
CHANGELOG.mdの内容がリリースノートに移行されているわけではないので、CHANGELOG.mdを消すのはやめてほしかった…

ファイルの先頭に「`[これ以降はGitHubのReleasesをご覧ください](https://github.com/syuilo/misskey/releases)`」と書いて復活させてほしいです…

**Comment by robflop** [comment]
僕も欲しいです、復活してください。

**Comment by tamaina** [comment]
した
