### ISSUE TITLE
CWで画像が隠されたとき、画像の高さがおかしいことになる

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6811]
## 💡 Summary
CWで画像が隠されたとき、画像の高さがおかしいことになる

https://github.com/syuilo/misskey/commit/21b6e23e986b5f43de89927d675f310055d83d97 でこれを不完全ながら防いでいたんだけど、メモリリークの問題があるのかぁ…

## 🙂 Expected Behavior
![image](https://user-images.githubusercontent.com/7973572/98245847-e1ee5780-1fb4-11eb-83e1-d860426cb579.png)

## ☹️ Actual Behavior
![image](https://user-images.githubusercontent.com/7973572/98245801-d1d67800-1fb4-11eb-9e7d-6418a8c76022.png)

## 📝 Steps to Reproduce

1. CWで画像が添付されている投稿を見つける
2. CWを開く

## 📌 Environment
Firefox 83.0b8 (64 ビット); Misskey v12.53.0

**Comment by syuilo** [comment]
iOSのGridバグはまだあるんかな
ないならワークアラウンド削除してそれでおわりにできるけど

**Comment by syuilo** [comment]
👀 
https://github.com/rachelandrew/gridbugs/issues/43

**Comment by syuilo** [comment]
あ

**Comment by syuilo** [comment]
ミス

**Comment by syuilo** [comment]
iOS14.2ではまだ直ってなかった

**Comment by argxentakato** [comment]
Vivaldi 3.3.2022.47とWindows 10 Version 1909でもなるんでGridバグ関係なさそう

**Comment by rinsuki** [comment]
iOSのgridバグのために全UAでworkaround入れてるって話では

**Comment by rinsuki** [comment]
iOSというかWebKitか

**Comment by argxentakato** [comment]
あーなるほど

**Comment by syuilo** [comment]
このコミットで直る可能性
https://trac.webkit.org/changeset/273435/webkit/

**Comment by syuilo** [comment]
iOS15で直ったのでぼちぼちワークアラウンド削除してもよさそう

**Comment by rinsuki** [comment]
まだ正式版出てないのに消すのは早すぎでは

**Comment by tamaina** [comment]
それがMisskey（とはいえ早すぎる

**Comment by EbiseLutica** [comment]
さすがにproduction-readyじゃない以上待ったほうが良いのでは

**Comment by syuilo** [comment]
戻すか

**Comment by null31** [comment]
Hi, I made an pr aiming to fix this issue. Should fix #7041 and #6833 too.
This was the best solution I could think about with my current knowledge.

Thank you.
