### ISSUE TITLE
DBのクエリが多すぎる

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#6813]
## 💡 Summary
毎秒800〜1500ぐらいのクエリがPostgreSQLに飛んでいて、PostgreSQLとMisskeyを違うネットワークに置くと極端に重くなる。

参考GIF（内容が見えないようにリサイズしてます）
![dJQkjHx4qG](https://user-images.githubusercontent.com/37681609/98434659-1547f800-2115-11eb-8c39-e7f7e8afca9c.gif)

## 🙂 Expected Behavior
DB内部である程度処理してから結果を返す

## ☹️ Actual Behavior
全部Misskey側で処理している

## 📝 Steps to Reproduce

1. PostgreSQLのログを見れるようにする
2. ユーザーが多いインスタンスを作る

## 📌 Environment
Misskey.io v12.54.0

**Comment by syuilo** [comment]
全部Misskey側で処理している の詳細が知りたい

**Comment by syuilo** [comment]
例えばタイムラインを取得するクエリを例にすると、取得されることになる各ノートのユーザー情報を予めJOINするようにしているからDBで出来る限りのことはやっている状態ではなかろうか
https://github.com/syuilo/misskey/blob/30c9c3739f086a7f9df2c4d8ccae78c605a25bb9/src/server/api/endpoints/notes/timeline.ts#L125

**Comment by rinsuki** [comment]
packManyがpackを全部並列で呼び出してるのでfindOneが呼ばれまくってると思う
本来はpackManyでよしなにやってpackがpackManyのラッパになっているべき

別プロジェクトだけど例 https://github.com/rinsuki/sea/blob/5766344c7463dd856ea27d83a47245d764b14cac/src/db/repositories/post.ts (これも application は手抜いてfindOneを投稿数ぶん呼んでるのでよくない)

**Comment by syuilo** [comment]
packMany はそれぞれに pack を呼び出していて、pack は渡されたものがオブジェクトなら find せずにそのまま利用しているから新たなクエリは発生しないように見える
https://github.com/syuilo/misskey/blob/30c9c3739f086a7f9df2c4d8ccae78c605a25bb9/src/models/repositories/note.ts#L95

**Comment by rinsuki** [comment]
noteのrepositoryだとpopulateEmojisとかだめそう

**Comment by syuilo** [comment]
populateEmojisはカスタム絵文字が含まれてない限りクエリ発火しなさそうだけど populateMyReaction は毎回発火してそう

**Comment by mei23** [comment]
大きいインスタンスでクエリ数稼いでるのがたぶんこの辺
https://github.com/mei23/misskey-v12/pull/686/files
↑はsaveで無駄にトランザクションとSELECT流してるところを修正しているけど
この辺をクエリ的に減らすのは難しいかも

**Comment by rinsuki** [comment]
> populateEmojisはカスタム絵文字が含まれてない限りクエリ発火しなさそう

それはそうなんだけどカスタム絵文字がめっちゃ付いてるとだいたいおもしろいのでRNされまくって刺さり度上がりそう (まあコーナーケースではある)

**Comment by syuilo** [comment]
> 大きいインスタンスでクエリ数稼いでるのがたぶんこの辺

ノート作成はいろいろやることあるからクエリ多いだろうなぁ

**Comment by syuilo** [comment]
write時のクエリを減らすのはめいめいが言っているように厳しそうだけど、read時のクエリはなんか工夫すれば減らせそうな雰囲気はするな

**Comment by syuilo** [comment]
populateEmojis は見る感じやってることが複雑だからDBサイドでやるのは難しそう

**Comment by rinsuki** [comment]
packManyの時notesの分集約して一回のクエリで問い合わせればマシになりそう

**Comment by syuilo** [comment]
あと気になっているのはデータベースという割と頻繁にアクセスされるであろうシステムを地理的に離れたサーバーで動かすのは割と良くあることなんだろうか

**Comment by rinsuki** [comment]
DB分けないとアプリサーバーの数増やせなくない？

**Comment by mei23** [comment]
pack系は非アクティブユーザーの分は処理しないからさほど増大しないけど
Note作成後にミュートやアンテナ見る所は休眠ユーザー分も処理するから登録ユーザーが増えるに従って増大していきそう

**Comment by syuilo** [comment]
> DB分けないとアプリサーバーの数増やせなくない？

サーバー自体を分けるのはあると思うけど、それを地理的に離れている場合でもやるのかなって思った

**Comment by SanMurakami** [comment]
離れてると言っても国内だから20msぐらいの遅延だし、地理的に離れてないと以前の震災みたいに影響を受ける

**Comment by rinsuki** [comment]
> サーバー自体を分けるのはあると思うけど、それを地理的に離れている場合でもやるのかなって思った

2リージョン以上で同じアプリ動かす時には素直にやるとDBをどっちかのリージョンに寄せないといけない気がするけどあんまり詳しくない (まあリードレプリカとかでマシにはなるだろうけどそれでもwriteはプライマリに行くはずだし)

**Comment by SanMurakami** [comment]
> 2リージョン以上で同じアプリ動かす時には素直にやるとDBをどっちかのリージョンに寄せないといけない気がする

元々はPgpool-IIでロードバランシングしてたけど、クエリが多すぎるせいかPgpool-II噛ませるだけでかなりパフォーマンスが下がる
今回の構成も最後の方にPgpool-II入れてPostgreSQLでストリーミングレプリケーションしている同一ネットワーク内のDBにウェイトを置いてたけどそれでもめちゃめちゃ重かった

**Comment by syuilo** [comment]
> Note作成後にミュートやアンテナ見る所は休眠ユーザー分も処理するから登録ユーザーが増えるに従って増大していきそう

一定期間使用がなかったアカウントのミュートとかアンテナは削除するか一時停止みたいな処理しないとダメかなぁ
まあMisskeyくらいの規模ならデータベースに負荷がかかるほどの`ミュート/アンテナ設定済み休眠アカウント`はなかなか発生しない気はする

**Comment by syuilo** [comment]
負荷を考える上では休眠かどうかは考慮しなくて良いか

**Comment by syuilo** [comment]
需要の無さそうなautoWatch機能を削除したのでノート作成時のクエリが若干減った
https://github.com/syuilo/misskey/commit/9d1fa3f20259cf7c303d49d5aae8e1fecdafc7ed

**Comment by syuilo** [comment]
(需要があったとしてもサーバーサイドでやる必要はない)

**Comment by syuilo** [comment]
https://github.com/syuilo/misskey/commit/4f249159d310d4296753fcfe8e2bbd390fd9002b とか https://github.com/syuilo/misskey/commit/8aa089178a54559cbc4e4fe84a618fc7535f178c あたりでクエリ数まあまあ減った

**Comment by syuilo** [comment]
> packManyの時notesの分集約して一回のクエリで問い合わせればマシになりそう

これやるか

**Comment by syuilo** [comment]
やった

**Comment by syuilo** [comment]
あと`noteRead`系の処理でもかなりクエリ発行するからバルクで行えるようにしたい
ただ、それに伴う「通知全部読んだよ」系のイベントは、比較的リアルタイム性が求められるので、ストリーミングからバラバラにくるメッセージをバルクで扱うようにする実装と相性が悪そう、というのが懸念される

**Comment by syuilo** [comment]
テーブルの結合を適切に行うことで、通知一覧取得時のクエリが大幅に減った
https://github.com/syuilo/misskey/commit/5e61c60f85e262421c1655eb6f8a317b88ccb88f

**Comment by syuilo** [comment]
メンションされていなかったり自分宛でないノートをreadしても(チャンネルやアンテナのノート除き)無意味なので、限られた条件の場合のみread処理するようにすることでタイムライン読み込み時のクエリがさらに減った
https://github.com/syuilo/misskey/commit/87c8f9ff953499340496e9c5db09c93eaff08851

**Comment by syuilo** [comment]
populateEmojis もまとめて行うようにするか

**Comment by syuilo** [comment]
やった

**Comment by syuilo** [comment]
ここまでの諸々の改修の結果

## タイムラインを100ノート分、通知を100個分読み込んだ時の総発行クエリ
1クエリで3msのオーバーヘッドがあると仮定した場合の時間も併記する

### before
797 (2391ms)

- notifications: 542クエリ
- timeline: 255クエリ

### after
25 (75ms)

- notifications: 11クエリ
- timeline: 14クエリ

**Comment by mei23** [comment]
フォロワー検索の場合
src/server/api/endpoints/users/followers.ts
```ts
	.innerJoinAndSelect('following.follower', 'follower')
```
フォローされてる検索の場合
src/server/api/endpoints/users/following.ts
```ts
	.innerJoinAndSelect('following.followee', 'followee')
```
あたりを表結合するといいはず

**Comment by mei23** [comment]
あと、API (TL/show) 系でクエリされる場合、必ず (デフォルトのDetailedPackedNoeでは) reply, renote, app は解決されるので
```
.leftJoinAndSelect('note.reply', 'reply')
.leftJoinAndSelect('note.renote', 'renote')
.leftJoinAndSelect('note.app', 'app')
```
あたりを最初から結合しとくといいかも。
どうせID=NULLならどれともマッチしないのでJOIN負荷は変わらない（と思う）

→ app以外は既に入ってた

**Comment by mei23** [comment]
あと`leftJoinAndSelect('note.user', 'user')`よりは、`innerJoinAndSelect('note.user', 'user')`なのかも？と
今は、ユーザー→ノートでカスケード削除されるからどっちども同じだけど、ユーザーがいない時はレコードを返さないのが正しいかも。

**Comment by mei23** [comment]
https://github.com/syuilo/misskey/commit/d7e7848c9206b68ab86d2d566ec4247db87827c0
`note.user` 以外はINNERにしちゃダメなはず

**Comment by mei23** [comment]
```ts
.leftJoinAndSelect('reply.user', 'replyUser')
.leftJoinAndSelect('renote.user', 'renoteUser')
```
は使われない気がする？

**Comment by syuilo** [comment]
> ```ts
> ```ts
> .leftJoinAndSelect('reply.user', 'replyUser')
> .leftJoinAndSelect('renote.user', 'renoteUser')
> ```
> 
> 
> は使われない気がする？

リプライとRenoteのpackするときは必ずそのユーザーも引っ張ってくるからjoinしてる

**Comment by syuilo** [comment]
> [d7e7848](https://github.com/syuilo/misskey/commit/d7e7848c9206b68ab86d2d566ec4247db87827c0)
> `note.user` 以外はINNERにしちゃダメなはず

リプライとかrenoteが消えていたときも(今のところ)レコード返したくないからそうしたけど、問題ありそうかな

**Comment by mei23** [comment]
replyUser, renoteUser はどこからも参照されてないし、entityにも定義なくないです？

**Comment by syuilo** [comment]
確認したときはこの書き方でjoinされたと思ったけど、勘違いだったかな
再度確認してみる

**Comment by mei23** [comment]
> リプライとかrenoteが消えていたときも(今のところ)レコード返したくないからそうしたけど、問題ありそうかな

最初からリプライでもRenoteでもない投稿がまるごと消えちゃう

**Comment by rinsuki** [comment]
というかappがDBに投げるクエリ数の話なのに INNER JOIN か LEFT JOIN かって関係あるの？

**Comment by syuilo** [comment]
クエリ数で言えば関係ない

**Comment by syuilo** [comment]
> 確認したときはこの書き方でjoinされたと思ったけど、勘違いだったかな
> 再度確認してみる

やはりjoinされてたので、第二引数は他のクエリ内で参照するための単なるエイリアス的な扱いでそんなに重要じゃないのかも

**Comment by syuilo** [comment]
出来ることはやって大分減ったはず
もう改修の余地がほぼなく、これ以上は原理的に(？)減らせないと思うのでclose

**Comment by SanMurakami** [comment]
かなり改善しました、ありがとうございます。

改善前
![image](https://user-images.githubusercontent.com/37681609/112037150-c7dc9c80-8b84-11eb-83dd-6d81fe33f652.png)

改善後
![image](https://user-images.githubusercontent.com/37681609/112037176-cf9c4100-8b84-11eb-842f-f8acba2aa615.png)
