### ISSUE TITLE
MFMの新たな記法の提案(xspin, yspin, vflip)

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6816]
表現力向上の為、以下の記法を提案します

- xspinタグ
  - spinのX軸版。X軸を基準に回転する。CSS的には `transform: rotateX()`
- yspinタグ
  - spinのY軸版。Y軸を基準に回転する。CSS的には `transform: rotateY()`
- vflipタグ
  - flipの縦版。flipが横反転するのに対し、vflipは縦反転する

詳しい見え方は https://groundpolis.app/notes/8eb8mk7pyr を見るとよくわかります

**Comment by syuilo** [comment]
それら考えてるけど今のMFMパーサー/MFMコンポーネントの設計だと装飾追加するたびに新たな構文分岐実装する必要があって冗長なのでまずそこ改善したい
具体的には装飾系の構文はすべて`[flip 🍕]`とか`[shake 🍕]`みたいにしたい
