### ISSUE TITLE
FB Like Comments System 

### ISSUE THREAD

**Issue by iManolin** [misskey-dev/misskey#6823]
Hello , 
I found misskey a great platform but i have a problem with its commenting system ,

it will be great if misskey used a simple one like FB one i hope you do that.

Thanks  @syuilo  friend keep going

**Comment by SanMurakami** [comment]
I don't know what FB's commenting system is, do you have a screenshot?

**Comment by iManolin** [comment]
Fb comments style is it  clear now ????!!!!!!!!!!!

**Comment by syuilo** [comment]
Thank you!
First, I think you need to be specific about what's problem with Misskey's comment system.
Also, since I (and other members) have never used FB, I would appreciate it if you could explain the specific advantages of this as well.
