### ISSUE TITLE
デッキの翻訳漏れ

### ISSUE THREAD

**Issue by argxentakato** [misskey-dev/misskey#6826]
## 💡 Summary

デッキのカラムの一部が翻訳されていない

![2020-11-11 04 55 05 norimono moe b81fc16d5ac8](https://user-images.githubusercontent.com/14871483/98726789-4efd5500-23da-11eb-9e2d-10678b89a970.png)

## 🙂 Expected Behavior

英語表示なので英語で表示されるはず

## ☹️ Actual Behavior

日本語で表示されてしまう

## 📝 Steps to Reproduce

1.言語を英語に設定する

**Comment by syuilo** [comment]
カラムの名前はカラムを追加したときに決定されます。
なので、カラム追加したときに日本語表示ならそのあとに他の言語に変えても日本語のままなのは仕様です。

**Comment by argxentakato** [comment]
なるほど、了解しました
