### ISSUE TITLE
タイムライン種別を切り替えると「新しいノートがあります」の表示が残留してしまう

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6831]
## 💡 Summary

「新しいノートがあります」ポップアップ表示中にタイムラインの種別を切り替えると、ポップアップが残留してしまう

## 🙂 Expected Behavior

タイムラインを切り替えた時点でポップアップが消滅する

## ☹️ Actual Behavior

Summary同様の症状が起こる

## 📝 Steps to Reproduce

Summary同様

## 📌 Environment

Misskey 12.55.0

**Comment by tamaina** [comment]
直ってないんだこれ
