### ISSUE TITLE
ノートをCWを付けて引用し、画像を添付すると画像が引用元を覆い隠してしまう

### ISSUE THREAD

**Issue by argxentakato** [misskey-dev/misskey#6833]
## 💡 Summary
ＣＷが付いた投稿をCWを付けて引用し、さらに画像を添付すると画像が大きすぎて引用元のノートが隠れてしまいます。
![image](https://user-images.githubusercontent.com/14871483/98903090-3a17e300-24fa-11eb-88f8-413792abb950.png)

## 📝 Steps to Reproduce

1. ＣＷ付きのノートを投稿
2. それを引用
3. 画像を添付、そして投稿

## 📌 Environment
Vivaldi: 3.3.2022.47 (Stable channel) (64-bit)
変更履歴: 0ccf6997c3958ed4378f4fdea56f2dcf01757962
OS: Windows 10 OS Version 1909 (Build 18363.1139)
JavaScript: V8 8.5.210.26

**Comment by argxentakato** [comment]
![image](https://user-images.githubusercontent.com/14871483/98903454-f83b6c80-24fa-11eb-8b66-383eaacc04cb.png)
引用元のCWに関わらず覆い隠される模様

**Comment by tamaina** [comment]
Duplicate of #6811
