### ISSUE TITLE
New MFM and cyrilic

### ISSUE THREAD

**Issue by RaZZlom** [misskey-dev/misskey#6834]
## 💡 Summary

Not all markdown formating working with new MFM

## 🙂 Expected Behavior

What i write:

```markdown
**bold**
__bold__
**болд**
__болд__
*italic*
_italic_
*италик*
_италик_
~~cross~~
~~зачеркнуто~~
```

Want all rendered.

## ☹️ Actual Behavior

What i got:

![2020-11-12 12 01 37 quietplace xyz 9be2f30fde38](https://user-images.githubusercontent.com/73530026/98918586-da600e80-24de-11eb-9f07-fc453d67b0dd.png)

`**bold**` - ✔
`__bold__` - ✔
`**болд**` - ✔
`__болд__` - ❌
`*italic*` - ✔
`_italic_` - ✔
`*италик*` - ❌
`_италик_` - ❌
`~~cross~~` - ✔
`~~зачеркнуто~~` - ✔

## 📝 Steps to Reproduce

1. Post note with text from ## 🙂 Expected Behavior

## 📌 Environment

Misskey v12.55.0

**Comment by akaregi** [comment]
cf. https://github.com/syuilo/misskey/issues/6709
> アスタリスクによる斜体がアルファベット以外で機能しないのは仕様です。
アスタリスクは顔文字などでも使われ、アルファベット以外の文字列を許可すると誤認識が発生すると考えられるためです。

**Comment by KisaragiEffective** [comment]
triage: won't fix per #6709
