### ISSUE TITLE
/api/meta broken

### ISSUE THREAD

**Issue by seanking2919** [misskey-dev/misskey#6835]
## 💡 Summary

When I visit https://misskey.io/api/meta, I get "Not found" instead of an API response.

## 🙂 Expected Behavior

When I visit https://misskey.io/api/meta, it should give an API response with information about the instance.

## ☹️ Actual Behavior
I get "Not found".

**Comment by syuilo** [comment]
When requesting the API, use POST instead of GET.

**Comment by seanking2919** [comment]
> When requesting the API, use POST instead of GET.

Ah, ok. Thanks!
