### ISSUE TITLE
Client: webpackの代わりにviteを使う

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6845]
Webpack + TerserPlugin は非常に時間がかかる（5分くらいかかる場合もある？）し、ビルドに要求するメモリの量がかなり大きい

Evan You氏謹製のVue専用モジュールバンドラー[Vite](https://github.com/vitejs/vite)は軽く、高速らしい

ただしまだベータ版である

**Comment by mei23** [comment]
Webpack 5.x がデフォルトで参照している terser-webpack-plugin 5.x がめちゃ重いだけなので、
terser-webpack-plugin 4.x を参照しちゃえば軽いです https://github.com/mei23/misskey-v12/pull/760

Webpackは重いだろうけど、with terser-webpack-plugin 5.x を例に出すのはフェアじゃないかなと。

**Comment by EbiseLutica** [comment]
terser-webpack-plugin 5.xってwebpack 5でも使える？

**Comment by EbiseLutica** [comment]
あ、https://github.com/mei23/misskey-v12/pull/760 見たけどつかえるのか

**Comment by syuilo** [comment]
ChromeでMisskeyで開発者ツール開くとめちゃくちゃ重くなるのもwebpackが原因説あるからViteにすることでそれも解決できそう

**Comment by tamaina** [comment]
@syuilo これやったことある？
（やってできていないとしたらその問題は何か教えてほしい）

**Comment by syuilo** [comment]
> @syuilo これやったことある？ （やってできていないとしたらその問題は何か教えてほしい）

めんどくさそうだからまだトライしてない
SVGをインポートするみたいなことがviteで出来るのかまだ調べてないというのもある

**Comment by tamaina** [comment]
(実はちょっとやってみている

**Comment by syuilo** [comment]
https://p1.a9z.dev/
がViteで動いてるけど、開発者ツール重くなる現象起こらなくなったからwebpackが原因で間違いなさそう
