### ISSUE TITLE
MFMリンク構文でエンコードされてないURLがリンク扱いされない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#6846]
## 💡 Summary
MFMリンク構文でエンコードされてないURLがリンク扱いされない

`[あ](http://example.com/い)` はリンクにしたいがリンクにならない
`[う](<http://example.com/え>)` はリンクになるがバグなのか仕様なのかがわからない

参考: https://github.com/syuilo/misskey/issues/4430

![image](https://user-images.githubusercontent.com/30769358/99256800-4af98900-2859-11eb-933b-168a218b7b3f.png)

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by syuilo** [comment]
リンクになった方が親切そう

**Comment by mei23** [comment]
ちなみにこれは、HTML => MFMでどう変換すれば無難かで悩んでる
https://github.com/syuilo/misskey/blob/50e917d232ade794d7b472d5d185134b03271f13/src/mfm/from-html.ts#L61

**Comment by mei23** [comment]
修正済みでいいと思う
