### ISSUE TITLE
PostgreSQL 13にアップデート

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#6850]
## Summary

したい

**Comment by rinsuki** [comment]
なんかいいことあるんだっけ

**Comment by syuilo** [comment]
パフォーマンスが向上してそう

**Comment by syuilo** [comment]
普通にdocker-composeに書いてあるバージョン上げるだけで良いのかワカラン(データの移行とか自動でやってくれるのか？)

**Comment by yakumo-saki** [comment]
MySQLと違ってPostgreSQLはバージョンが変わると手動でアップグレードしないと起動時にエラーで落ちます
手元で 11 => 13 にバージョンだけ変えて実験してみたときのログが以下です。

```
PostgreSQL Database directory appears to contain a database; Skipping initialization                                                                  
│ 2020-11-26 14:22:02.099 UTC [1] FATAL:  database files are incompatible with server                                                                   
│ 2020-11-26 14:22:02.099 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 13.1  
│ stream closed  
```

**Comment by syuilo** [comment]
なるほどなるほど…

**Comment by mei23** [comment]
2bb0a61a891445df4d78bfc0d4a64551ac9b7a39 でしれっと 11 => 12 に変えてるけど大丈夫だったんですかね
多分アウトだけど、たまたまdocker-composeのPostgreSQLで本番運用しているところがなかったか、泣き寝入りしたか…

**Comment by yakumo-saki** [comment]
手元で試してみたら 11 => 12 でも落ちますね…一応ログ張っておきます
postgres:11.10-alpine から postgres:12-alpine に変更して試しました。

```
 2020-12-02 03:31:56.864 UTC [1] FATAL:  database files are incompatible with server                                                                                       
│ 2020-12-02 03:31:56.864 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 12.5.                     
│ stream closed 
```

**Comment by syuilo** [comment]
リリースノートに「DockerのPostgreSQLのバージョンを上げたので、手動でアップグレード作業を行ってください」って書いておけば良いかな？

**Comment by Johann150** [comment]
According to the English installation guide on Misskey hub, we already use PostgreSQL 13, so I think this can be closed.

**Comment by syuilo** [comment]
Misskey's [docker-compose](https://github.com/misskey-dev/misskey/blob/a29ff7b1fa45e01bc7c097e8d770a4c4eedf2a8f/docker-compose.yml#L30) still specifies PostgreSQL 12 and should be opened.

**Comment by tamaina** [comment]
これどうするんだろうか

**Comment by tamaina** [comment]
どうするんだろうかといいながら15になったわ
