### ISSUE TITLE
Missing local strings for 'left' and 'center' in deck settings.

### ISSUE THREAD

**Issue by fz0000** [misskey-dev/misskey#6856]
## 💡 Summary

https://github.com/syuilo/misskey/blob/db8b824b84ae9fe345947e7a06628d87d9fde072/src/client/pages/settings/deck.vue#L17-L18

![image](https://user-images.githubusercontent.com/5061311/100254785-b8a26500-2f7d-11eb-93d7-9fe1cc57e59c.png)

## 📌 Environment

develop

**Comment by syuilo** [comment]
直った
