### ISSUE TITLE
ログイン履歴のIPアドレスがローカルアドレスの表示となる

### ISSUE THREAD

**Issue by nenohi** [misskey-dev/misskey#6857]
## 💡 Summary
アカウント設定よりセキュリティタブを閲覧した際に
ログイン履歴が表示される

## 🙂 Expected Behavior
グローバルIPアドレスが表示される

## ☹️ Actual Behavior
ローカルIPアドレスが表示される

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by syuilo** [comment]
Misskey側ではどうしようも無い気がするな
プロキシとかCloudFlareの設定を管理者に見直してもらうくらいか

**Comment by nenohi** [comment]
2019年7月まではグローバルが見えてるっぽいからioの問題・・・？

**Comment by SanMurakami** [comment]
`X-Forwarded-For`がついてる場合はそっちを拾うのが普通だと思う

特にMisskeyはCloudFlare使ってるインスタンスも多いから`CF-Connecting-IP`もあるかどうか判定して、ある場合はそっちを優先して拾ったほうがいいと思う。

**Comment by syuilo** [comment]
X-Forwarded-Forは見てた気がする

**Comment by SanMurakami** [comment]
ioはちゃんと渡してるはず

他のアプリケーション（wikijs）とかはちゃんと拾えてる

**Comment by syuilo** [comment]
CF-Connecting-IP対応するか

**Comment by mei23** [comment]
途中のnginxとかにこの辺あるならコメントアウトしてみて
https://github.com/syuilo/misskey/blob/db8b824b84ae9fe345947e7a06628d87d9fde072/docs/examples/misskey.nginx#L53-L55

**Comment by mei23** [comment]
一番外のCloudflareが作った`X-Forwarded-For`はノータッチでNodeまで渡してこないといけない
(途中で、消してもダメだし `X-Forwarded-For`のチェインに追加してもダメ)

**Comment by SanMurakami** [comment]
k8sに入る前のサーバー振り分けの部分で
```
        proxy_set_header X-Real-IP CF-Connecting-IP;
        proxy_set_header X-Forwarded-For CF-Connecting-IP;
        proxy_set_header X-Forwarded-Proto https;
```
になってるけど、これも外したほうがいい？

**Comment by mei23** [comment]
前段にCloudflareが入ってるなら外したほうがいいです

**Comment by SanMurakami** [comment]
![image](https://user-images.githubusercontent.com/37681609/100298736-36458f80-2fd5-11eb-99a5-abf64429e690.png)
おー拾えた
それ知らない人多そうだし何かしらで広めた方が良いかも

**Comment by mei23** [comment]
たぶんmisskey.nginxのサンプルにコメント追加しておく…
