### ISSUE TITLE
フォントにBIZ UDゴシックを指定するのはやめてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#6858]
## Summary
なぜこれにしたのか

**Comment by syuilo** [comment]
Windowsだとメイリオになるけど、メイリオあまり好きじゃなかった

**Comment by tamaina** [comment]
せめてUDPGothicにしない？UDゴシックは等幅なので英字が見にくくて仕方がない・・・  
（そもそもフォント設定は変えられた方がよさそう

**Comment by rinsuki** [comment]
理想だけを言うとsans-serifだけ指定してあとはみんながブラウザのsans-serif設定を変えるのがいいのでは

**Comment by mei23** [comment]
> 理想だけを言うとsans-serifだけ指定してあとはみんながブラウザのsans-serif設定を変えるのがいいのでは

それがBeforeだったりする
(前に指定してある欧文フォントは、たしか日本語フォントの欧文がイマイチな端末対策)
```css
font-family: Roboto, HelveticaNeue, Arial, sans-serif;
```

**Comment by EbiseLutica** [comment]
フォント、設定できたら良さそう

だってマカー蚊帳の外なんだもん...

**Comment by syuilo** [comment]
まぁMacは最初からフォント綺麗だからね

**Comment by syuilo** [comment]
英字見にくいのでとりあえず UDPGothic 試すか

**Comment by mei23** [comment]
`BIZ UDPGothic`にすると、欧文の幅が結構広くて欧文やURLが見づらかったり間延びした感じになる。

和文フォントの前に欧文フォントを置いて欧文を置き換えればまともになるけど
`Roboto, HelveticaNeue, Arial, 'BIZ UDPGothic', sans-serif`
今度は、BIZ UDPGothicだと行間が詰まってるのが気になる。
行間調整すればいいけど、これだけのために行間調整していいのかが気になる。

あと、このフォントWindowsでレンダリングするとサイズによっては潰れたりベースラインがずれたりしてしまう (これはフォント自体はは悪くないんだろうけど)。

なので、結局このフォントWebだと扱いづらい気がする。

**Comment by syuilo** [comment]
フォント変える動機の一つにline-heightを共通にしたいというのがあって、メイリオとiOS系のフォントだと行間が違いすぎて難しいというのがあった
現在の BIZ UDゴシック でも同じline-heightを指定しても若干iOSの方が詰まっているので、 `BIZ UDPGothicだと行間が詰まってる`はむしろメリットになりそう(それに合わせて行間を調整したときに、iOSとのline-heightのズレが少なくなる)

**Comment by syuilo** [comment]
とりあえず「システムデフォルトのフォントを使う」オプションでも実装するか
