### ISSUE TITLE
一部カードの背景設定ミス

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#69]
> 開発者募集中！
> 
> Misskeyはオープンソースで開発されています。リポジトリはこちら。

背景を設定できていないので例えば青い背景を設定すると画像のようになります。

![default](https://cloud.githubusercontent.com/assets/7973572/22251898/ba3573ce-e28f-11e6-9803-78baf655edfe.PNG)

----

* FireFox Dev
* デスクトップ版Misskey\

**Comment by ha-dai** [comment]
backgroundにrgba(255,255,255,.8)するとか

**Comment by syuilo** [comment]
壁紙廃止するとか

**Comment by syuilo** [comment]
廃止しました。
