### ISSUE TITLE
Terser Webpack Plugin 4 を使う

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6901]
詳しくは https://github.com/syuilo/misskey/issues/6845#issuecomment-727611322

**Comment by syuilo** [comment]
4と5で何が違うのか把握してからだな

**Comment by mei23** [comment]
> 4と5で何が違うのか把握してからだな

terser-webpack-pluginはterserを呼び出すプラグインであくまでも最適化エンジンはterserなので
terser-webpack-plugin4と5で最適化の内容は変わらないと思います。

では、terser-webpack-plugin4と5はなにが違うかと言うと`performance improvement`と言われています。
しかし、実際に速くなっているかと言うと微妙で、ヒープメモリの使用量が使用量が多くなっており環境によってはコケる確率が高くなっていて、さらにスワップの発生によって逆に遅くなっていると思われます。

リッチなデスクトップ開発環境のように8コアとか16GBあるような環境なら恩恵が受けられるのかもしれませんが、
そもそもdevelopmentではJSの最適化を行わないので微妙な気がします。

Dockerイメージの生成に使っているCircleCI環境ではどうかと言われると
CircleCIのFreeはおそらく 2vCPU / 4GB あたりと思われるため (ここの2vCPUは物理CPUの1コア2スレッド分を割り当てと推測)
並列化の恩恵は程遠いと思われ逆にメモリが厳しめの環境に属すると思います。

個人的には絶対terser-webpack-plugin 5じゃないと出来ないことがない限り4でいいのではないかという印象です。

**Comment by syuilo** [comment]
なるほどなるほど👀
詳細にありがとうございます

**Comment by EbiseLutica** [comment]
これ導入してみたけど改善していないどころか悪化しているんですが...

**Comment by mei23** [comment]
> これ導入してみたけど改善していないどころか悪化しているんですが...

ソース

**Comment by EbiseLutica** [comment]
@mei23 
実行した版のコミット: https://github.com/Groundpolis/Groundpolis/commit/edf976bc142a1b833e3498dfde1b425245eed7a3
マージしたコミット: https://github.com/Groundpolis/Groundpolis/commit/92bc613653209f70daf1ba7f04dad225641089fd

## 実行環境
|||
|---|---|
|RAM|1GB|
|スワップ|1.5GB|
|node options|`--max-old-space-size=2048`|

**Comment by mei23** [comment]
@Xeltica 
おそらく4.xにして解決するのは、ヒープ使用量が減って`--max-old-space-size=2048`がいらなくなるかもという点
既に`parallel: 1`まで入れていて重い環境なら効果が薄いのかも
ヒープが減っても後はどれだけスワップが速いかになるから、ディスクIOとかが原因で元から遅い環境ではあまり変わらないのかも

**Comment by EbiseLutica** [comment]
そういえば具体的に何が起こるのかを書きそびれていました

時間がかかるならまだしも、Terserが起動したあたりでKilledと表示されて強制終了してしまう感じです。他鯖の管理者からの報告によれば、メモリ2GBの環境でも起こってしまっているようです

**Comment by mei23** [comment]
@Xeltica 
![image](https://user-images.githubusercontent.com/30769358/101282648-a811aa80-3819-11eb-9e36-b5a74276ab76.png)

12.x は前は heap out of memory が出てたけど今は大丈夫みたい
でも、terser-webpack-plugin 4.x with parallel=1 の方が速かったよ

Groundpolis は依然として heap out of memory が出ちゃうよ
また、terser-webpack-plugin 4.x を入れても変わらないよ

**Comment by EbiseLutica** [comment]
Groundpolisサイドの問題ですか...検証ありがとうございます&大変失礼しました

**Comment by tamaina** [comment]
関連したIssueはあるけどあんまり解決してる感じがない

https://github.com/webpack-contrib/terser-webpack-plugin/issues/403  
https://github.com/webpack/webpack/issues/13550
