### ISSUE TITLE
Firefoxで、投稿欄に#か:リンクを入力した後に日本語入力がうまくできない

### ISSUE THREAD

**Issue by m-hayabusa** [misskey-dev/misskey#6904]
## 💡 Summary

Firefoxで、投稿欄に`#`、`:`、リンクを入力した直後に日本語入力がうまくできない
(Chromeであれば正常に入力できる)

## 🙂 Expected Behavior

`#かにたま`
`:かにたま`
`[リンク](https:///example.com)かにたま`

## ☹️ Actual Behavior

`#ｋｋああｎｎｔああｍｍああ`
`:ｋｋああｎｎいいｔｔああｍｍああ`
`[リンク](https:///example.com)ｋｋああｎｎいいｔｔああｍｍああ`

## 📝 Steps to Reproduce

1. Firefoxで投稿欄を開く
2. `#`、`:`、もしくはリンクを入力
3. スペースを開けずに日本語入力

## 📌 Environment
Misskey 12.61.0, 12.60.0, おそらくもっと古いバージョンから
Win10 Pro 1909 / Firefox Developer Edition 84.0b7 (64 ビット) / SKK日本語入力FEP
Win10 Pro 1909 / Firefox 83.0 (64ビット) / Microsoft IME (Windows 10 1909)

**Comment by mei23** [comment]
なんとなくFirefox 83以降で起きてる気がする、Google IMEでも起きる。
たぶん、オートコンプリートのポップアップを開いたり閉じたりするタイミングで日本語入力が確定してしまっている。

今は`:日本語`みたいな絵文字としてありえないパターンでもサジェストを出そうとしているので、行の前の方に`:`とかがあれば起きてしまう。このパターンを厳しくすれば影響は減る。

それでも、日本語ハッシュタグのサジェストは出来ないままだし、`#`や`:`の直後で日本語入力したい場合もダメなので
結局Firefoxが？なおらないと解決できなそう。

**Comment by m-hayabusa** [comment]
Windows Sandbox内で試してみましたが、確かにFirefox 82.03では再現せず、83.0で再現しました。
(Misskey 12.61.0 / Win10 2004 / Microsoft IME)

**Comment by rinsuki** [comment]
Misskey 12.61.0 + macOS 10.15.7 + Firefox 83.0 + AquaSKK or 標準IME では再現しなかった(そもそも変換中はオートコンプリートが更新されてないように見える)ので Windows 環境固有？
(Google IME は入れてないのもあって試してないのでもしかしたらそっちだと再現するかも)

**Comment by mei23** [comment]
Xubuntu 18.04 + Firefox 83.0 でも起きない
日本語入力中はinputイベントが起きない→オートコンプリートも更新されない みたいなのでたぶんOSXと同じパターン

**Comment by m-hayabusa** [comment]
Firefox Developer Edition 85.0b2で解決していることを確認しました。Firefox側のバグだったようです
(Misskey 12.63.0 / Windows 10 2004 / Microsoft IME)
