### ISSUE TITLE
Messaging Is Broken

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#6928]
## 💡 Summary

Messaging Is Broken

## 📝 Steps to Reproduce

1. Click on Messaging
2. Type name of local user
3. Unable to find

## 📌 Environment

Misskey v12.62.0

**Comment by syuilo** [comment]
Has the target user ever posted?
The user search has the specification to exclude users who have never made a note.

**Comment by okpierre** [comment]
@syuilo I can understand exclusion for users but shouldn't admin be able to message anyone?

**Comment by rinsuki** [comment]
can you try manually access to `/my/messaging/SCREEN_NAME`?

**Comment by okpierre** [comment]
@rinsuki yes that works, thanks! 

By the way, the search was working before so not sure what happened.

**Comment by rinsuki** [comment]
🤔 https://github.com/syuilo/misskey/commit/346036ec88fae983d249fbd9367fb7d2b28404a5

maybe we should use `ORDER BY DESC NULLS LAST` instead of `updatedAt IS NOT NULL`?

**Comment by syuilo** [comment]
> maybe we should use ORDER BY DESC NULLS LAST instead of updatedAt IS NOT NULL?

NULLS LASTの存在知らなかった…
そっちの方が望んだ挙動になりそう

**Comment by tamaina** [comment]
直った？
