### ISSUE TITLE
Some values disappeared from instance/settings

### ISSUE THREAD

**Issue by AlfredSK** [misskey-dev/misskey#6929]
## 💡 Summary

Looks like Misskey 12.62/12.62.1 is forgetting the instance settings for `smtp server config` and `service worker config`. These settings on /instance/settings are empty since I updated from 12.61.1.

When I re-enter the values for smtp (host, port, username, password) and service worker (public key, private key) and save the settings everything looks right. But when I reload the page those fields are empty again.

## 🙂 Expected Behavior

The config values for `smtp server config` and `service worker config` should stay. :-)

## ☹️ Actual Behavior

The config values for `smtp server config` and `service worker config` are missing (they disappeared). When I re-enter the values for smtp (host, port, username, password) and service worker (public key, private key) and save the settings everything looks right. But when I reload the page those fields are empty again.

## 📝 Steps to Reproduce

1.  Go to instance/settings
2.  Check the fields for smtp and service worker settings
3.  When they're empty re-enter the values and save settings
4.  Reload page or go to some other page and return to settings/instance
5.  Check those settings again

## 📌 Environment

Misskey v12.62/v12.62.1
Node.js v14.15.1
PostgreSQL v12.5 (Ubuntu 12.5-0ubuntu0.20.04.1)
Redis v5.0.7

**Comment by RaZZlom** [comment]
I have same problem with `block storage` and `proxy user` settings.

**Comment by syuilo** [comment]
These settings have specifications that can only be edited by an admin account.
Make sure the account you are operating under is an admin.

**Comment by AlfredSK** [comment]
Yes. My account is an admin account.

![image](https://user-images.githubusercontent.com/3656054/101280996-d74dfa80-37cc-11eb-84ac-5d1896170094.png)

Can I check that somewhere else? 

Edit: Ah! Found it! :-)

![image](https://user-images.githubusercontent.com/3656054/101281687-c2736600-37d0-11eb-910c-d35b886f2e93.png)

**Comment by AlfredSK** [comment]
**1. The setting is disabled (but was enabled before)**

![image](https://user-images.githubusercontent.com/3656054/101281101-8985c200-37cd-11eb-9134-612c59f20995.png)

**2. Enabled again, but the values are gone**

![image](https://user-images.githubusercontent.com/3656054/101281165-ea14ff00-37cd-11eb-963d-6c7ade88748e.png)

**2. Re-entered the values and saved the settings (green check-mark showing success)**

![Bildschirmfoto vom 2020-12-06 14-20-46](https://user-images.githubusercontent.com/3656054/101281345-b1295a00-37ce-11eb-99e4-4beca90d89fd.png)

**3. Went back to my timeline, then went to instance/settings again -> Setting is disabled again, saved values are gone**

![image](https://user-images.githubusercontent.com/3656054/101281401-f2ba0500-37ce-11eb-84eb-f8e1ed20060a.png)

![image](https://user-images.githubusercontent.com/3656054/101281410-fea5c700-37ce-11eb-984c-01e8c52dbdd1.png)

The same happens with mail (smtp) settings and the other settings @RaZZlom mentioned.

**Comment by AlfredSK** [comment]
I can change other settings. I changed the instance description as a test. That worked.

**Comment by syuilo** [comment]
Oh, this is indeed a bug.

**Comment by syuilo** [comment]
Fixed. Thank you for the report🙏

**Comment by AlfredSK** [comment]
Awesome! :-) Thank you for fixing it. ❤️🎉
