### ISSUE TITLE
Push notification of Antenna note

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#6965]
特定のユーザーがノートを作成したとき通知する機能

**Comment by syuilo** [comment]
アンテナで代用できるかも

**Comment by EbiseLutica** [comment]
むしろ、アンテナ通知が通知として飛んできてほしいかも（現状光るだけ）

**Comment by syuilo** [comment]
まあTwitterにも特定アカウントのツイート通知するオプションあるし実装しても良いかも

**Comment by tamaina** [comment]
Issueを転用した

**Comment by tamaina** [comment]
これアンテナ設定で「新しいノートを通知する」が有効になっていれば自動的に通知を受信するようにするんでいいよね…？
