### ISSUE TITLE
Run failed after update (eg: cause 502) / アップデートしたら502とかになる

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#6988]
## 💡 Summary
When you update Misskey, the build succeeds but may fail to start.
(In most production environments, 502 occurs.)
Run `yarn --force` to fix it.

Misskeyをupdateすると、ビルドは成功するものの起動に失敗することがある。
(大抵のproduction環境では502が発生する)
`yarn --force` でなおる。

※Misskeyのバージョン問わず起きる
※たぶん失敗する時は、 node_modules がデフォルトに戻っているにも関わらず`Building fresh packages...`でsharpのビルドがトリガされていない

## 🙂 Expected Behavior
起動に成功する

## ☹️ Actual Behavior
起動に失敗する

## 📝 Steps to Reproduce
一度ビルド後に違うバージョンをcheckoutする
例えば 12.53.0 -> 12.55.0, 12.55.0 -> 12.53.0

```
yarn && yarn build && yarn start 
```
```
Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- MISSKEY_PATH/node_modules/sharp/lib/constructor.js
- MISSKEY_PATH/node_modules/sharp/lib/index.js
- MISSKEY_PATH/built/services/drive/image-processor.js
- MISSKEY_PATH/built/services/drive/generate-video-thumbnail.js
- MISSKEY_PATH/built/services/drive/add-file.js
- MISSKEY_PATH/built/services/drive/upload-from-url.js
- MISSKEY_PATH/built/remote/activitypub/models/image.js
- MISSKEY_PATH/built/remote/activitypub/models/person.js
- MISSKEY_PATH/built/remote/resolve-user.js
- MISSKEY_PATH/built/services/note/create.js
- MISSKEY_PATH/built/remote/activitypub/models/note.js
- MISSKEY_PATH/built/remote/activitypub/kernel/create/note.js
- MISSKEY_PATH/built/remote/activitypub/kernel/create/index.js
- MISSKEY_PATH/built/remote/activitypub/kernel/index.js
- MISSKEY_PATH/built/remote/activitypub/perform.js
- MISSKEY_PATH/built/queue/processors/inbox.js
- MISSKEY_PATH/built/queue/index.js
- MISSKEY_PATH/built/server/activitypub.js
- MISSKEY_PATH/built/server/index.js
- MISSKEY_PATH/built/boot/worker.js
- MISSKEY_PATH/built/boot/index.js
- MISSKEY_PATH/built/index.js
- MISSKEY_PATH/index.js

- Run "npm rebuild --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues
```

※sharpでなくre2で出ることもある https://github.com/syuilo/misskey/issues/6829

## 📌 Environment
node: v14.4.0
yarn: v1.22.10
npm: v6.14.5

**Comment by tamaina** [comment]
昔のしゅいろなら「npmにしようぜ」って言いそう(

**Comment by mei23** [comment]
まだあるかな？

**Comment by tamaina** [comment]
npm run clean-all && npx yarn installでだいたい治る気がする

**Comment by mei23** [comment]
`clean-all` かけるより、ここらへんのyarnのオプションに`--force`を付けられるようにした方が復旧が速い。(というか最初から付けててもあまり速度変わらない)
https://github.com/misskey-dev/misskey/blob/333ba491f10446066c076338f7cd495ac715f436/scripts/install-packages.js#L6
https://github.com/misskey-dev/misskey/blob/333ba491f10446066c076338f7cd495ac715f436/scripts/install-packages.js#L14
