### ISSUE TITLE
プロフィール画面で投稿が右に寄りすぎてる

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#6991]
## 💡 Summary

左にプロフ右に投稿まではいいけどさらに左に何か置くべきじゃない (右に寄りすぎてると思う)

![image](https://user-images.githubusercontent.com/6533808/102436089-2a407100-405b-11eb-9727-f2a41afe3b4c.png)

あとログイン状態だとウィンドウ幅によってはフォローボタンのとことかが壊滅する
![image](https://user-images.githubusercontent.com/6533808/102436292-9ae78d80-405b-11eb-9053-a2ef42ab5ea1.png)

**Comment by futchitwo** [comment]
![image](https://user-images.githubusercontent.com/74236683/162635954-4aed5ed6-da21-421d-afb3-d520aef694a2.png)
最新のバージョンでは修正されています
