### ISSUE TITLE
Support request: Inline playback of videos

### ISSUE THREAD

**Issue by AlfredSK** [misskey-dev/misskey#6994]
こんにちは,
I have searched the documentation and help pages. Unfortunately, I have not found anything about this topic. ;-) So I'm asking about it here.

When someone has shared a video (e.g. mp4), a preview image is displayed in the timeline. When I click on the preview image a new window/tab will be opened where I can play the video.

I'd like to be able to play videos directly in the timeline. Is it possible to configure the Misskey instance in a way that the player is loaded inline after clicking on the preview image?

どうもありがとうございました,
Steffen

**Comment by okpierre** [comment]
@AlfredSK Agree! Video should work the same as inline image. 

By the way, reported this bug early this year https://github.com/syuilo/misskey/issues/6051 in Misskey v12.19
