### ISSUE TITLE
vue-i18n更新後WebUIが表示されない

### ISSUE THREAD

**Issue by ikuradon** [misskey-dev/misskey#7002]
## 💡 Summary

#6993 で更新されたvue-i18n起因でWebUI表示時にDevConsole上に`TypeError: e.$t is not a function`が出てWebUIが何も表示されない

## 🙂 Expected Behavior

WebUIが表示される

## ☹️ Actual Behavior

WebUIが表示されない

## 📝 Steps to Reproduce

1. 57d0c19a98c75cf1b64115c8a6c5e6134c020fa4 以降にする
2. ビルドする
3. WebUIを開く

## 📌 Environment

Misskey#develop 57d0c19a98c75cf1b64115c8a6c5e6134c020fa4

**Comment by ikuradon** [comment]
intlify/vue-i18n-next#204 のBreakingChangeが原因

**Comment by syuilo** [comment]
vue i18nやめたので解決👍
