### ISSUE TITLE
No ability to expand post to see thread/replies in v12.63.0?

### ISSUE THREAD

**Issue by belatedly** [misskey-dev/misskey#7022]
## 💡 Summary

Can no longer expand threads to view replies. Expand option is missing from the menu.

![Screen Shot 2020-12-25 at 11 16 30 AM](https://user-images.githubusercontent.com/63966511/103139648-e3c6c400-46a3-11eb-9367-74809f892ed0.jpg)

## 🙂 Expected Behavior

I was on v12.47.1 til I updated yesterday, and had the option to "Expand" the thread in the menu. That option is gone and I do not see any other way to view replies unless they are in my home timeline.

## ☹️ Actual Behavior

The "Expand" option is gone and I do not see any other way to view replies unless they are in my home timeline.

## 📝 Steps to Reproduce

1. Locate a post that shows a reply number
2. Right click or click on the menu
3. Expand option is not there

## 📌 Environment

v12.63.0 on the home timeline, profile page

**Comment by okpierre** [comment]
@elenners when you click on the note itself, you will see the entire thread

**Comment by belatedly** [comment]
That does not work on Safari Version 14.0.1 (16610.2.11.1.3) nor Firefox 84.0.1 (64-bit). Clicking a note on both browsers just ends up highlighting the text.

**Comment by okpierre** [comment]
@elenners Here what it looks like on Firefox 84.0

![misskey-thread](https://user-images.githubusercontent.com/1679025/103179555-4e6e3000-485b-11eb-84ac-44f9c830d48a.png)

**Comment by belatedly** [comment]
All it is doing for me is adding a dashed border and highlighting the text if I try to click it a second time. 

<img width="794" alt="Screen Shot 2020-12-27 at 2 53 31 PM copy" src="https://user-images.githubusercontent.com/63966511/103179645-b1f45f80-4853-11eb-8ad4-56336e6b79f7.png">

**Comment by okpierre** [comment]
@elenners Try the note link. In my example, I clicked on the **2d ago**.

**Comment by belatedly** [comment]
Oh wow, I feel dumb. I have been using this system since September and never knew. Thank you so much.

**Comment by okpierre** [comment]
@elenners You're welcome! Enjoy!
