### ISSUE TITLE
クライアントのスクリプトのビルドを不要にしたい

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#7023]
## Summary

スクリプトを各言語ごとに生成するようにすると、とても時間がかかるため、予めビルドしてリリースしたい

**Comment by rinsuki** [comment]
ロケールクライアント側で埋め込みにしたらいいのでは

**Comment by syuilo** [comment]
ロケールのためにサーバーとの通信が発生するの微妙だし、レスポンス返ってくるまでVue初期化できなかったりと面倒

**Comment by syuilo** [comment]
まあ仮にロケールごとに生成しないとしてもやはり予めビルドしたい
たまにメモリ不足でビルドできないという人がいるため

**Comment by rinsuki** [comment]
そういう人はdockerイメージ使ったらいいのでは

**Comment by syuilo** [comment]
dockerイメージって予めビルドされてるの？

**Comment by rinsuki** [comment]
dockerhubにpushされてるやつはビルドされてるのでは

**Comment by syuilo** [comment]
じゃあ表題の「クライアントのスクリプトのビルドを不要にしたい」は既に達成されているのか
