### ISSUE TITLE
User Reports Note But Nothing Happens

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7025]
## 💡 Summary

User reports a post but nothing happens

## 🙂 Expected Behavior

Admin should see indicator or receive notification similar to new message

## ☹️ Actual Behavior

Nothing

## 📝 Steps to Reproduce

1. Login as regular user and report a post
2. Login as admin
3. Don't know of any reports

## 📌 Environment

Misskey 12.63.0

**Comment by Amolith** [comment]
To add a bit more context, I had been receiving reports from local users for about a month and had no idea. Pleroma and Mastodon both notify admins and moderators through the web UI *and* through email when there are new reports and I expected Misskey to behave the same way.

As much as I dislike the constant blinking light from More > Mentions, the admin panel could definitely benefit from something similar, whether it's a blinking light, a proper notification, or an email. Silent reports are definitely less than ideal imo.

**Comment by Johann150** [comment]
I think it would also be nice to create a notification in the Misskey UI since there is already the `newAbuseUserReport` event being sent to the admin stream if I understand the code correctly.
