### ISSUE TITLE
デッキをフレキシブルにしている時に左に重ねるを実行するとフレキシブル状態が維持されなくなる

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#7032]
## 💡 Summary

![LSRYZENCapture1708](https://user-images.githubusercontent.com/28042693/103265252-83f85200-49f0-11eb-9e3d-e7f115326fc0.png)

## 🙂 Expected Behavior

フレキシブル状態が維持される

## ☹️ Actual Behavior

フレキシブル状態が維持されない

## 📝 Steps to Reproduce

1.UI切り替えでデッキにする
2.カラムを3つ開いた状態にして全てFlexibleを有効にする
3.一番左以外のカラムで「左に重ねる」を行う

## 📌 Environment

Misskey v12.65.0

**Comment by syuilo** [comment]
一応仕様で、フレキシブルは上下分割したカラムには適用されない

**Comment by tkmrgit** [comment]
> 一応仕様で、フレキシブルは上下分割したカラムには適用されない

それじゃv11より退化してるじゃないですか😢

**Comment by tkmrgit** [comment]
![LSRYZENCapture1709](https://user-images.githubusercontent.com/28042693/103266559-34ffec00-49f3-11eb-9f8a-39deb0be3f6e.png)
こんな感じでv11使わせていただいているので復活してほしいにゃ

**Comment by syuilo** [comment]
> それじゃv11より退化してるじゃないですか😢

v11では個別に設定できなかったので進化してる

**Comment by syuilo** [comment]
やった
https://github.com/syuilo/misskey/commit/d815838762425d08e3466f7efca5c3ffcf646e7f

**Comment by tkmrgit** [comment]
しゅいろさん流石！(test)

**Comment by syuilo** [comment]
✌️(test)

**Comment by tkmrgit** [comment]
にゃーん (test)
