### ISSUE TITLE
PagesでAiScriptをより自然に利用できるように

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/misskey#7033]
仕様の変更案

## 全般
- スクリプトに文法エラーがある、無効なPage変数を使用している等のエラーがある場合、ページの表示は行われないように
  - 整合性が崩れた曖昧なページデータを元にページを表示するのはあまり意味がない
  - どのように表示されるのが正しいのか分からない
- Page毎に従来のPage変数を使用するかAiScript変数を使用するかを選択できるようにする(Pageのスクリプトモード？)
  - Pageのスクリプトはスクリプトモード時のみ利用可能
  - スクリプトモード: Pageで使用される変数は全て(？)AiScript変数
  - 非スクリプトモード: Pageで使用される変数は従来どおりのPage変数
  - これまでに作成されたページはページの作者が非スクリプトモードのPageに移行される
  - Pageのスクリプトモード有効設定は後からも変更可能

## Page変数
- AiScript変数型のPage変数を廃止
- 条件分岐(if)型のPage変数を廃止
- ユーザー定義関数型のPage変数を廃止

## スクリプト
- (API)MkPages:updatedは廃止せずそのまま維持
  - AiScript変数はPageから直接使用されるが、値の変更タイミングで任意の処理を実行したい場合も想定されるため
- Pageのスクリプトは常にパースされるようにする
  - 文法エラーがある場合ユーザーに表示する
- Pageに対してAiScript変数として抽出される変数はルートのスコープのみにする

## 入力ブロック
- 入力ブロックに関連付ける変数は既に定義されているPage変数の中から選択する
  - AiScriptの変数を入力ブロック側が動的に追加することを避ける
- 入力ブロックでPage変数の代わりにAiScript変数も使用できるように

## 破壊的変更
仕様変更に合わせてPageの再編集が必要になるケース
- これまでに作成されたPageが非スクリプトモードに移行されると、AiScriptを主に使用していたページではスクリプトが実行されなくなる
- これまでに作成されたAiScript変数型のPage変数を含んだページの表示がされなくなる
- これまでに作成された条件分岐(if)型のPage変数を含んだページの表示がされなくなる
- これまでに作成されたユーザー定義関数型のPage変数を含んだページの表示がされなくなる

**Comment by marihachi** [comment]
# 旧案

仕様の変更案

## 全般
- スクリプトに文法エラーがある、無効なPage変数を使用している等のエラーがある場合、ページの表示は行われないように
  - 整合性が崩れた曖昧なページデータを元にページを表示するのはあまり意味がない
  - どのように表示されるのが正しいのか分からない
- Page毎に従来のPage変数を使用するかAiScript変数を使用するかを選択できるようにする(Pageのスクリプトモード？)
  - Pageのスクリプトはスクリプトモード時のみ利用可能
  - スクリプトモード: Pageで使用される変数は全て(？)AiScript変数
  - 非スクリプトモード: Pageで使用される変数は従来どおりのPage変数
  - これまでに作成されたページはページの作者が非スクリプトモードのPageに移行される
  - Pageのスクリプトモード有効設定は後からも変更可能

## Page変数
- AiScript変数型のPage変数を廃止
- 条件分岐(if)型のPage変数を廃止
- ユーザー定義関数型のPage変数を廃止

## スクリプト
- (API)MkPages:updatedは廃止せずそのまま維持
  - AiScript変数はPageから直接使用されるが、値の変更タイミングで任意の処理を実行したい場合も想定されるため
- Pageのスクリプトは常にパースされるようにする
  - 文法エラーがある場合ユーザーに表示する
- Pageに対してAiScript変数として抽出される変数はルートのスコープのみにする

## 入力ブロック
- 入力ブロックに関連付ける変数は既に定義されているPage変数の中から選択する
  - AiScriptの変数を入力ブロック側が動的に追加することを避ける
- 入力ブロックでPage変数の代わりにAiScript変数も使用できるように

## 破壊的変更
仕様変更に合わせてPageの再編集が必要になるケース
- これまでに作成されたPageが非スクリプトモードに移行されると、AiScriptを主に使用していたページではスクリプトが実行されなくなる
- これまでに作成されたAiScript変数型のPage変数を含んだページの表示がされなくなる
- これまでに作成された条件分岐(if)型のPage変数を含んだページの表示がされなくなる
- これまでに作成されたユーザー定義関数型のPage変数を含んだページの表示がされなくなる

**Comment by syuilo** [comment]
仕様自体はよさそう
破壊的変更を避けるために、pageにversion的なカラム追加してそれで処理分けるとかできないかな

**Comment by marihachi** [comment]
バージョン分ける方向で行こうか
