### ISSUE TITLE
CW/Subject/Topics image bug

### ISSUE THREAD

**Issue by clarjon1** [misskey-dev/misskey#7041]
## 💡 Summary

Image in collapsed CW posts do not properly expand, covering the reply/renote/react/etc buttons

## 🙂 Expected Behavior

The interaction buttons should appear below the image, as per usual posts

## ☹️ Actual Behavior

https://jumanji.co/notes/8gdtmgcypd  Example post to demonstrate behaviour live

Screenshots:
![image](https://user-images.githubusercontent.com/627845/103312419-f9612400-49ea-11eb-86ab-17e374f64167.png)
![image](https://user-images.githubusercontent.com/627845/103312429-ff570500-49ea-11eb-838d-5a97e83ec667.png)
When mousing over image, interaction buttons vanish:
![image](https://user-images.githubusercontent.com/627845/103312443-1269d500-49eb-11eb-9074-de03b839206c.png)

## 📝 Steps to Reproduce

1. Post image with CW/Subject/Topic
2. Click "Load More" button
3. Observe image covering buttons

## 📌 Environment
misskey v12.64.2

**Comment by tamaina** [comment]
Duplicate of #6811
