### ISSUE TITLE
Embed not found image in each domain instead of external domain?

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7043]
## 💡 Summary

The "not-found" image is external and not local

## 🙂 Expected Behavior

Image should point to instance folder not external

## ☹️ Actual Behavior

Image pointing to external

## 📝 Steps to Reproduce

1. Visit `https://misskey.io/anything-here`
2. View image url

## 📌 Environment

Misskey 12.65.3

**Comment by okpierre** [comment]
These images should be moved locally so path is local each instance instead of going to external site

Image here for reference
![misskeyexternalimages](https://user-images.githubusercontent.com/1679025/115961734-ac4b1580-a4e5-11eb-9961-f6a1541eea72.png)

**Comment by Albirew** [comment]
you can also add external iframe on your list (show in classic UI view)
![Sans titre](https://user-images.githubusercontent.com/2805161/213933152-17fe9d40-1be2-4329-804e-e777181a18fe.png)

**Comment by KisaragiEffective** [comment]
triage: closing this issue as #10959 is landed today. https://github.com/misskey-dev/misskey/issues/7043#issuecomment-1399567669 is separated as #14010.
