### ISSUE TITLE
We should be able to delete an account

### ISSUE THREAD

**Issue by Dehelssey** [misskey-dev/misskey#7064]
## Add (or restore ?) the ability to delete one's account

It seems like it is, as i'm writing, impossible to delete your account on a Misskey instance.

I'm pretty sure there used to be a button to do so. Actually, both instances i have an account on say on their about page that account can be deleted any time. But i've searched everywhere in the settings pannels and i can't find it...

so, 
1. option was never implemented in the first place and should definitely be 🔥 
2. option was implemented but somehow get lost (in the translation process maybe ?) 🤔 
3. option is still there but (too damn) well hidden and i missed it 😄 

Thanks for the otherwise awesome software 😺

**Comment by cliqsocial** [comment]
@syuilo is there a reason why this feature is not available? We received several requests on our instance.

**Comment by syuilo** [comment]
This button has been restored in the develop branch.

**Comment by Dehelssey** [comment]
Perfect ! Thanks a lot 🤗
