### ISSUE TITLE
Widget bug : Server metrics (RAM)

### ISSUE THREAD

**Issue by kazukyakayashi** [misskey-dev/misskey#7067]
## 💡 Summary

The Server Metric widget bug.

## ☹️ Actual Behavior

The server metric widget doesn't seem to work properly, this one shows me 95% of used RAM, with htop or other tools I'm only ~1Go of used RAM, and I have the same problem on my second instance where the widget also shows 95% of used RAM

## 📌 Environment

- Misskey v12.66.0
- Debian 10

**Comment by defango** [comment]
I'm having a similar problem. I moved from a 16gb instance to a 128 gig instance and it says its using all like 67% of that 128 gigs. That would only make sense if it was adding in all the files from storage.
