### ISSUE TITLE
Total do not match number of replies

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#7076]
## 💡 Summary

number of replies do not match total

this is what it looks like
![misskey-reply-count](https://user-images.githubusercontent.com/60059665/104208738-d6793b80-53fe-11eb-82b5-dd6318b3e521.jpg)

## 🙂 Expected Behavior

if there are 3 replies total should be 3

## ☹️ Actual Behavior

3 replies and total is 1

## 📝 Steps to Reproduce

1. reply to note
2. another account reply to that reply
3. count does not increment

## 📌 Environment

misskey 12..66.0

**Comment by Johann150** [comment]
This is intended because it only counts the top level replies, and not replies of replies.
