### ISSUE TITLE
デッキの操作は右クリックできなくても困らないようにしてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#7077]
## Summary
カラム追加やカラムメニューの表示が右クリックになりましたが、iOSでは開けさえしないですし、そもそも右クリックで隠れているものはわかりにくいという問題があります。

カラム追加に関しては「余白を右クリック」というかなりわかりにくい操作になっており、実際にユーザーから混乱の声が聴かれます。

カラムメニューに関しては、どうして右上▼で開けたものをわざわざ設定だけのボタンにしたのでしょう？タイムラインや通知などの設定はカラムメニューから開くようにする、という手順にしても問題ないと私は思います。

右クリックだけではなく、実ボタンで操作できるようにしてほしいです。

**Comment by syuilo** [comment]
> カラムメニューに関しては、どうして右上▼で開けたものをわざわざ設定だけのボタンにしたのでしょう

例えばウィジェットカラムでそれをすると「設定」という項目が二つできて紛らわしい(カラム自体の設定と、ウィジェットの設定)

**Comment by syuilo** [comment]
> カラム追加に関しては「余白を右クリック」というかなりわかりにくい操作になっており

分かりにくいのはドキュメントを目立つように表示すれば解決しそう

**Comment by tamaina** [comment]
> 「設定」という項目が二つできて紛らわしい

"カラム編集"と"ウィジェット設定"とかにして区別するのではだめ?

> 分かりにくいのはドキュメントを目立つように

わかりにくいUIをドキュメントで補完するのはどうなのよと思ったり。右端の+ボタンを復活する方がよくない？  
タッチデバイスで追加できない問題はどう解決しようと思っているのでしょうか？

**Comment by syuilo** [comment]
> タッチデバイスで追加できない問題はどう解決しようと思っているのでしょうか？

そもそもDeckはPC向け機能なので特に積極的に解決しようとは考えていないけど、クリックでもコンテキストメニュー開くとか、PCで編集したものをプロファイル機能使って同期とかすれば良さそう

**Comment by syuilo** [comment]
+ボタン表示するとフレキシブル表示にした時に画面の幅いっぱいまでカラムが広げられない問題がある

**Comment by EbiseLutica** [comment]
フローティングさせればよさそう？

**Comment by tamaina** [comment]
べつに"追加"は画面の右端に表示しなくてもいいとは思う

私が思いつくのは、サイドメニューの項目にするとか

（実装めんどくさそう

**Comment by syuilo** [comment]
サイドメニューはスマホだと表示されないからウーム

**Comment by tamaina** [comment]
サイドメニューじゃなくてサイドバーか

**Comment by syuilo** [comment]
やった
