### ISSUE TITLE
リリースノートページ

### ISSUE THREAD

**Issue by kabo2468** [misskey-dev/misskey#7081]
## Summary

しゅいろさんがアップデート情報を投稿しても、フォローしていない人や見逃した人、ただSNSの別の居場所としてMisskeyを使っている人に新機能を知らせることが出来ないので、アップデート履歴などが見れるリリースノートが有ったほうがいいと思う

アプデしたときに「こんな機能が追加されました」みたいなお知らせを表示するとより良いかも

**Comment by syuilo** [comment]
> アップデート履歴などが見れるリリースノートが有ったほうがいいと思う

ここで見れます
https://github.com/syuilo/misskey/releases

> アプデしたときに「こんな機能が追加されました」みたいなお知らせを表示するとより良いかも

これは予定中

**Comment by syuilo** [comment]
related: https://github.com/syuilo/misskey/issues/7070

**Comment by syuilo** [comment]
i18nをどうするかだな

**Comment by syuilo** [comment]
i18nはしないでも良さそう
