### ISSUE TITLE
1MB以上のファイルのアップロードができない🥺｜Cannot upload file over 1MB

### ISSUE THREAD

**Issue by KawaneRio** [misskey-dev/misskey#7099]
## ⍝ 基本概要 〜Summary

1024KBまたはそれ以上のファイルのアップロードが [misskey.io](https://misskey.io) と [co.misskey.io](https://co.misskey.io) でできなくなっちゃいました( ；∀；)

## 🙂 期待動作 〜Expected Behavior

1MBの写真でも15MBの動画でも（常識の範囲内であれば）アップロードできるハズですーっζ#`з́)ζ

## ☹️ 実際行動 〜Actual Behavior

アップロードが100%で止まって、えっと、クルクルはずっと回ってるんだけど、ずっとそのままなんですー。

## 📝 再現手順 〜Steps to Reproduce

1. まずはお手頃な`1023KB`のファイルと`1MB`のファイルを作ってみよう！
2. 端末でtruncateのコマンドを使う：`truncate -size 1023K 1023KB  && truncate -size 1M 1MB`
3. さっき作った`1023KB`っていう名前のファイルと`1MB`っていう名前のファイルを[misskey.io](https://misskey.io)へアップロードしてみよう！
4. `1023KB`のファイルは無事アップロードされるが、`1MB`のファイルはなぜかアップロードされない。
5. 🥺

## 🐧 動作環境 〜Environment

OS: Ubuntu 20.04.1 LTS x86_64 
Browser: Mozilla Firefox 84.0.2 (Mozilla Firefox for Ubuntu Canonical 1.0)
Misskey: v12.67.1

Tested and reproduced on both, [misskey.io](https://misskey.io) and [co.misskey.io](https://co.misskey.io) platforms.
![スクリーンショット_2021-01-16_00-23-34](https://user-images.githubusercontent.com/61252570/104807281-104d9780-579b-11eb-9c93-3f5172b399aa.png)

**Comment by syuilo** [comment]
たしかmisskey.ioではそのようなアップロード制限をしていたと記憶しています。
なのでMisskey自体に問題がある訳ではないはず

**Comment by KawaneRio** [comment]
マジすか・・・いったいいつの間に・・・
1MBだと、自分がスマホで撮った写真が無編集でうｐできないので難しいにゃ…この制限はなんとか回避できないのでしょうか？

**Comment by syuilo** [comment]
ちょっとその辺の制限は私はよく把握してないので、インスタンスの運営に問い合わせてみてください🙏

**Comment by KawaneRio** [comment]
わかりましたっ。わざわざありがとうございます🙇

**Comment by KawaneRio** [comment]
（あっ、これって勝手に閉めちゃってよかったのかな・・・？）
