### ISSUE TITLE
vuex廃止前に非ログイン状態で閲覧していたMisskeyを開こうとすると，無のユーザーとしてログインしてしまう

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#7107]
## 💡 Summary

vuexの永続化データに`i: null`がセットされているとき，Local Storageの`account`キーに`{"token":null}`という値がセットされてしまう．こうなると非ログイン状態ではなく，nullユーザーでログインしたという状態になってしまい，いろいろとおかしい状態になる．

vuexからのマイグレーションに問題があるが，過去にこの不具合を踏んでアカウントが作成できない人もいると思うので，マイグレーション修正と共に，accountキーに正しいトークンが入っていないときに削除する処理も実装したほうが良さそう．

## 📝 Steps to Reproduce

1. 非ログインかつ，最後に訪れたのがMisskey 12.64.0 にアップグレードする前であるインスタンスに行く

## 📌 Environment

Misskey 12.67.1

**Comment by rinsuki** [comment]
これそういうバグだったのか

**Comment by Sayamame-beans** [comment]
triage: そこそこ前の話なので今後対応すべきかは不明
