### ISSUE TITLE
AiScriptのMk:apiの呼び出し制限を緩和

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/misskey#7123]
繰り返しAPI実行するプラグインなどが書けないので、それを緩和したい
どうですかね

**Comment by kakkokari-gtyih** [comment]
繰り返し実行じゃなくても、何度か呼び出すうちに上限に達してページ再読み込みをかけないといけないので、個人的にはそうなるとすごくありがたいです

**Comment by slofp** [comment]
個人的には負荷対策せずにapiを実行してしまうときの対策だと思うので
### 案

1. 1～5秒くらい？のクールタイムを入れる
2. 通常のレートリミット処理のように実行できる回数が事前にあって、使った分は時間経過で回復する

ような感じが良いなと思いました。(ただ1に関しては時間が経たなければ次が実行できないため使い勝手は悪くなりそうですが...)

**Comment by syuilo** [comment]
AiScriptからリクエストする場合だけ殊更に制限する必要はなさそう
