### ISSUE TITLE
How to change a misskey instance's domain?

### ISSUE THREAD

**Issue by TennousuAthena** [misskey-dev/misskey#7137]
## Summary

  Hi. I'm trying to change the domain for my instance. Is it OK to just modify .config/default.yml:url?
   
  I've tried it but it seems another instance would respond 500 FAILED_TO_RESOLVE_REMOTE_USER

**Comment by syuilo** [comment]
This is not possible because Fediverse does not handle domain changes. If you want to use a different domain, you will need to create a new separate instance.

**Comment by TennousuAthena** [comment]
Got it. Thank you!
