### ISSUE TITLE
Use findOneOrFail instead of ensure

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#7139]
## Summary
Use `findOneOrFail` instead of `ensure`

https://github.com/syuilo/misskey/blob/develop/CONTRIBUTING.md#%E7%B0%A1%E7%B4%A0%E3%81%AAundefined%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF

TypeORMに最初から[`findOneOrFail`というものがある](https://github.com/typeorm/typeorm/blob/master/docs/repository-api.md) ので、そっちを使ったほうがエラーメッセージもまともになるのでいいかなと思いました。

Code:
```ts
const user = await Users.findOne(userId).then(ensure);
↓
const user = await Users.findOneOrFail(userId);
```

Error message:
```
ぬるぽ
↓
Could not find any entity of type "User" matching: {
    "id": "a"
}
```

**Comment by syuilo** [comment]
なるほど、よさそう
