### ISSUE TITLE
ハッシュタグを正規化

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#7149]
## Summary

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/normalize

**Comment by syuilo** [comment]
NFKC使うと良さそう
ref.
- https://analytics-note.xyz/programming/unicode-normalization-forms/
- https://maku77.github.io/js/string/normalize.html

**Comment by mei23** [comment]
たぶんこんな感じ
https://github.com/mei23/misskey-v11/commit/897dc65ae2de9f88f8b9075c4fb3409336395c49
https://github.com/mei23/misskey-v11/commit/43b91fe1518829c77a3d73fff0cddfab40370acc
