### ISSUE TITLE
ノート（リプライ(ダイレクト)・引用・メンション）を既読にしたら、通知も既読にする

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#7165]
## Summary
MisskeyのUI的に、通知欄(notifications.vue)ではreply, quote, mentionはノートがそのまま表示されるので、ノートが表示されたらそのnotificationも既読になるのが自然

逆はやらない。通知が表示されたからと言って完全に表示されているかわからないし、画面上でnoteを完全に表示すればsubscribeが発生してnoteが既読になる。

（PR 7129でこれはやりません）

**Comment by tamaina** [comment]
あと、ノートが削除されたら通知が削除されるようにもしなければならない

**Comment by tamaina** [comment]
いや、普通に消えそう

**Comment by tamaina** [comment]
消えそうだけど、CASCADEで消えるのをフックする必要がある

**Comment by tamaina** [comment]
あと、フォロリク/グループ招待を承認/拒否→通知既読、~~フォロリク/グループ招待キャンセル→通知削除~~もかな

**Comment by syuilo** [comment]
~~現在はnotifications.vueでnoteコンポーネントとnotificationコンポーネントを出しわけているけど、全部notificationコンポーネントにしてnotificationコンポーネント側で必要に応じてnoteコンポーネント呼び出したりするようにすればいい感じになるかな？~~

**Comment by syuilo** [comment]
フォロリク/グループ招待については別途実装が必要だけど

**Comment by syuilo** [comment]
ぬあーいろいろ勘違いしてた

**Comment by syuilo** [comment]
普通にsearvice/note/read.tsでnotificationのread処理追加するだけで事足りそうか

**Comment by tamaina** [comment]
> ぬあーいろいろ勘違いしてた

いや、書き方が悪かった感ある（通知ではなくあなた宛てとかを例に出すべきだった

> 普通にsearvice/note/read.tsでnotificationのread処理追加するだけで事足りそうか

yes
