### ISSUE TITLE
PackedNoteSchemaがNotes.packの変更を反映していない？

### ISSUE THREAD

**Issue by Cj-bc** [misskey-dev/misskey#7174]
## 💡 Summary

`Notes.pack`で返されるオブジェクトに対して、`PackedNoteSchema`に記載されていないもの・なくなっているものがいくつかある気がします。
(`Notes.pack`によって返されるオブジェクトの説明用のオブジェクトが`PackedNoteSchema`、という認識の上で書いています。間違っていたらすぐ取り下げます...)

Packしている部分:
https://github.com/syuilo/misskey/blob/d0cf26b3421c9a8da466bda623d5011f65f0159f/src/models/repositories/note.ts#L216-L262

Schema:
https://github.com/syuilo/misskey/blob/d0cf26b3421c9a8da466bda623d5011f65f0159f/src/models/repositories/note.ts#L288-L417

### Schemaに足りないもの

- `emojis`
- `localonly`
- `reactions`
- `renoteCount`
- `repliesCount`
- `uri`
- `url`
- `_featuredId_`
- `_prId_`
- `myReaction`

(`_featuredId_`と`_prId_`は書式的に、載せないでいいものかな...?)

### Schemaにあるが`pack`されていないもの

- `isHidden`

## 🙂 Expected Behavior

それらがドキュメントに載っている・載っていない

## ☹️ Actual Behavior

それらがドキュメントに載っていない・載っている

## 📝 Steps to Reproduce

コードを参照するか、https://misskey.io/api-doc

**Comment by Cj-bc** [comment]
これは修正作業してしまっていいですか...?

するとして、`properties`を追加する順序は何かありますか？
`pack`での順番と同じかと思ったのですが違いそうなので

**Comment by syuilo** [comment]
> これは修正作業してしまっていいですか...?

ぜひお願いします🙏

> するとして、propertiesを追加する順序は何かありますか？

特にありません。

余談:
プロパティに抜けがあることも問題だけど、抜けがあるのに型定義上のエラーが出ない(出てるけど見逃してるだけ？)のも問題ですね

**Comment by Cj-bc** [comment]
作業しています！

`reactions`のSchemaなのですが、「絵文字をkeyにしてその個数をvalueにとる」という構造の表現の仕方がわかりません...
例として何かの絵文字を例に出すことはできるとは思うのですが、それは違う気がします。

今は`items`を定義せずに`description`に書くようにしていますが、これでいいでしょうか？
```typescript
reactions: {
	type: 'object' as const,
	optional: false as const, nullable: false as const,
	description: 'Key is either Unicode emoji or custom emoji, value is count of that emoji reaction.',
},
```

**Comment by Cj-bc** [comment]
PRが無事mergeされたのでcloseします 🎉
