### ISSUE TITLE
Federation problems with misskey.io, null pointer exception

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#7177]
## Summary

When i try to federate with misskey.io i get this error message at server log:
`failed(Error in actor https://misskey.io/users/7rkrarq81i - Error: ぬるぽ) id=643416 attempts=4/4 age=11m activity=https://misskey.io/likes/8i4et2jdzt`

Also, i tried to remove instance entry and all its users entries for "misskey.io" from my psql database and then refetch them, but error still here.

When i try to fetch users using API console:
Request - federation/users,
`{
  host: 'misskey.io',
  sinceId: '',
  untilId: '',
  limit: 100,
}`
Response -
`{
  message: 'Internal error occurred. Please contact us if the error persists.',
  code: 'INTERNAL_ERROR',
  id: '5d37dbcb-891e-41ca-a3d6-e690c97775ac',
  kind: 'server',
  info: {
    e: {
      message: 'ぬるぽ',
      code: 'Error',
      stack: 'Error: ぬるぽ\n    at ensure (/home/misskey/misskey/built/prelude/ensure.js:9:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async UserRepository.pack (/home/misskey/misskey/built/models/repositories/user.js:146:39)\n    at async Promise.all (index 0)\n    at async /home/misskey/misskey/built/server/api/endpoints/federation/users.js:43:12\n    at async Object.exports.default (/home/misskey/misskey/built/server/api/call.js:64:12)',
    },
  },
}`

## Expected Behavior
Normally federating with misskey.io

##  Environment
Raspberry Pi 4B (armv7l)
PostgreSQL - 13.1
Node.js - 14.15.4
Redis - 6.0.9
Misskey - 12.69.0

**Comment by SanMurakami** [comment]
What is the hostname of the instance where the error is occurring?

**Comment by ghost** [comment]
> What is the hostname of the instance where the error is occurring?

nyan.nekoea.red

**Comment by SanMurakami** [comment]
![image](https://user-images.githubusercontent.com/37681609/107838187-f928b680-6de7-11eb-8401-17e75d27ff9e.png)
We have checked the logs and found that your instance is using Tor, which has been flagged as BadScore and blocked by CloudFlare.

We have just added your instance to our whitelist, so please try again.

**Comment by ghost** [comment]
Thank you, now all is fine, i can follow users from misskey.io and i don't get "null pointer exception" anymore!
I've also purged **all** misskey.io related entries from all tables to make it function properly
By the looks of things, it was a problem related to empty entries about misskey.io, the receipt of which was blocked by CF
Btw, now it shouldn't show you Tor at panel, because i've switched all my outgoing traffic to go through Shadowsocks proxy on my gateway
