### ISSUE TITLE
Mastodon instances not displaying avatars and banners from my instance

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#7178]
## Summary
When i try to open any account from my instance (nyan.nekoea.red) using mastodon i see blank image instead of actual avatar (tried using mastodon.social and inex.rocks)

## Expected Behavior
Displaying avatar

## Environment

Raspberry Pi 4B (armv7l)
PostgreSQL - 13.1
Node.js - 14.15.4
Redis - 6.0.9
Misskey - 12.69.0 (signToActivityPubGet: true)

**Comment by mei23** [comment]
Apparently Mastodon cannot use WebP for Avatar / Banner, and it seems that both cannot be updated even if one of them has an error.

**Comment by ghost** [comment]
Thank you very much!
Works just fine now, i just replaced my banner image with one in png format
Marking as closed
