### ISSUE TITLE
プラグイン設定が開けない

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#7188]
## 📝 Steps to Reproduce

1. 設定ページを開く
2. [プラグイン] を選択
3. 何も表示されない

## 📌 Environment

Misskey 12.69.0 (misskey.io)

**Comment by EbiseLutica** [comment]
io では無い他の Misskey 12.69.0 インスタンスでは再現しなかったので io 固有の不具合（マージミス？）かもしれないです

**Comment by syuilo** [comment]
設定画面からキャッシュクリアすると直りそう

**Comment by EbiseLutica** [comment]
治った✌️
