### ISSUE TITLE
TypeError: this.$i is null

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7189]
## 💡 Summary

`TypeError: this.$i is null`

![thisiisnull](https://user-images.githubusercontent.com/1679025/107838542-52570280-6d74-11eb-9999-0b5163a3b9f3.png)

## 📌 Environment

Misskey v12.69.0

**Comment by syuilo** [comment]
どんな操作 / ページでそのエラーが発生しましたか？👀

**Comment by okpierre** [comment]
`https://misskey.io/preview`
