### ISSUE TITLE
iPhone SE（第1世代）などでウィジェットトレーを閉じることができない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#7191]
## 💡 Summary
device-width <= 320 の端末では左側に余白がないためウィジェットトレーを閉じることができない

![WIN_20210213_13_15_14_Pro](https://user-images.githubusercontent.com/7973572/107841451-59c2ee00-6dfe-11eb-93a6-c677360abb53.jpg)

## 🙂 Expected Behavior
上部に閉じるボタンがあればよさそう

## ☹️ Actual Behavior
左側に余白がないのでウィジェットトレーを閉じることができない

## 📝 Steps to Reproduce
1. ウィジェットトレーを開く
2. 終 制作・著作 / ⓃⒽⓀ

## 📌 Environment
c2.a9z.dev (Misskey @ develop+7219) / iPhone SE @ iOS 14.5

**Comment by tamaina** [comment]
iPhone 13 miniで再発した(

**Comment by tamaina** [comment]
拡大表示にしているからだったわ  
どちらにしても直さなければならないけど

**Comment by syuilo** [comment]
iPadで横に表示するやつ(名前忘れた)で出したときも問題になる

**Comment by tamaina** [comment]
> iPadで横に表示するやつ(名前忘れた)で出したときも問題になる

SlideOver
