### ISSUE TITLE
Serviceworkerによって言語ファイルがキャッシュされ、キャッシュクリアボタン押しても更新されなくなる

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#7192]
## 📝 Steps to Reproduce

1.
2.
3.

**Comment by tamaina** [comment]
キャッシュしないほうがいいかしら

**Comment by mei23** [comment]
> キャッシュしないほうがいいかしら

PWAとして認識させたいのか or プッシュ通知が使えればいいのか 方針によると思う。

**Comment by mei23** [comment]
てゆうかこれって本当にSWのせい？SW入れる前から更新されないような気がするわ

**Comment by syuilo** [comment]
あ、localSotrageのキャッシュを手動で削除してもServiceWorkerサイドでキャッシュされてるから更新されないという意味

**Comment by syuilo** [comment]
PWAとして認識させるメリット特にない気がする

**Comment by mei23** [comment]
「キャッシュをクリア」でServiceWorkerのキャッシュもクリアすればいいのかもと

**Comment by tamaina** [comment]
SW実装は次のいずれか？

1. そもそもfetchでキャッシュを返さない
2. self.onfetchでキャッシュを返すけどDevelopment（_DEV_）においてはfetchLocale時に必ずサーバーにlocaleファイルをフェッチしに行く

**Comment by syuilo** [comment]
ここで問題になっているのは開発時/本番問わないので、どちらかと言えば1かな

**Comment by tamaina** [comment]
> 開発時/本番問わない

本番環境は考慮しなくてもいいのでは？

**Comment by tamaina** [comment]
（どっちでもいいと思うので1にしますが

**Comment by syuilo** [comment]
> 本番環境は考慮しなくてもいいのでは？

言語ファイル更新する手段がないのはマズい

**Comment by syuilo** [comment]
バージョン変わったらキャッシュヒットしなかった記憶もあるけど曖昧

**Comment by tamaina** [comment]
localeファイルの名前にはバージョンが挿入されるので、バージョンを変えたら必ず新しいlocaleが読み込まれる。はず。

**Comment by mei23** [comment]
そもそも、今はバージョン変わってもロケールが更新されないはず。
https://github.com/syuilo/misskey/blob/6477ad2cfc2198aa9e974a1879412b46366e1e94/src/server/web/boot.js#L16-L38

**Comment by syuilo** [comment]
バージョン変わって、かつキャッシュクリアボタン押すと更新されるかも

**Comment by syuilo** [comment]
このissueのタイトルが良くないな

**Comment by mei23** [comment]
バージョン変わってもロケールが自動でfetchされないのはいいの？（よくない）

**Comment by syuilo** [comment]
そのうち直したいけどこのisseuとはまた別かな

**Comment by mei23** [comment]
開発環境でもクライアント変更したらバージョン変えるのが本来な気もするので
バージョン変わったらロケールが自動でfetchされないのを直して、
developビルド時にはバージョンにノイズを付けてビルドするようにするとか。
→ ただこれをやるとwebpack watchがうまくいかなくなる
→ どうせwebpack watchでロケールとかうまくいかないから別にいいかも

**Comment by tamaina** [comment]
そもそも、onfetchの関数が空関数でもPWAとして認識されるので、onfetchは空関数にすることにする  
（しゅいろがonfetch嫌いっぽいし

**Comment by mei23** [comment]
fetch外しても

おそらくここのタイミングで
https://github.com/syuilo/misskey/blob/6477ad2cfc2198aa9e974a1879412b46366e1e94/src/client/sw/sw.ts#L28-L40

言語ファイルもキャッシュに入ってるので大丈夫か気になる (アプリの一部扱い？)
![image](https://user-images.githubusercontent.com/30769358/107846927-061ac980-6e2b-11eb-998c-5f30ea3a0642.png)

**Comment by tamaina** [comment]
> 言語ファイルもキャッシュに入ってるので大丈夫か

大丈夫もなにも、これが今回のIssueで問題になっている箇所

**Comment by mei23** [comment]
on install の中も消さなくていいのって話

**Comment by tamaina** [comment]
ん、oninstallでは`/?v=${version}`しか追加していない

localeファイルをキャッシュに追加しているのは

https://github.com/syuilo/misskey/blob/6477ad2cfc2198aa9e974a1879412b46366e1e94/src/client/sw/sw.ts#L128
