### ISSUE TITLE
delete reply note does not decrement replies count of main note

### ISSUE THREAD

**Issue by ehsanjavadynia** [misskey-dev/misskey#7208]
Assume that we have these hierarchy of notes:
- Main post
  |-> reply 1
  |-> reply 2
At this point "repliesCount" for main post is 2. if we delete "reply 1" note, the "repliesCount" won't change and stays the same (2).
I think in delete note service we should check if the note hast replyId and is local and in that case we should decrement repliesCount of the main post.

https://github.com/syuilo/misskey/blob/5cdd9d20277193aa4857d424dc15a8c2bab119b9/src/services/note/delete.ts#L23

**Comment by EbiseLutica** [comment]
Related to #4857
