### ISSUE TITLE
Error: integer out of range

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7209]
## 💡 Summary

Getting 100+ errors for this:

`ERROR:  integer out of range`
`STATEMENT:  UPDATE "instance" SET "driveUsage" = "driveUsage" + 197061 WHERE "host" = $1`

## 📌 Environment

Misskey 12.69.0 PostgreSQL 10.15

**Comment by mei23** [comment]
#6807
#6977

**Comment by okpierre** [comment]
@mei23 Are they all related? Is there a quick fix for this? So many log entries for this error and the issue has been opened since November 2020.

**Comment by mei23** [comment]
全部ここでスキーマ直したのにマイグレスクリプト書いてないのがいけない
https://github.com/syuilo/misskey/commit/6d4526576307d2ff62b3e512f2b9ce6cc9ffa3ab#diff-cde0f9bc7fbf190b07e782ab3cc550a78b469b9eec21b23f8e1eba89ce16cbbe
