### ISSUE TITLE
ERROR:  value too long for type character varying(1024)

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7210]
## 💡 Summary

Getting 100+ errors for this:

`ERROR:  value too long for type character varying(1024)`
`STATEMENT:  UPDATE "user_profile" SET "url" = $2, "fields" = $3, "description" = $4, "birthday" = $5, "location" = $6 WHERE "userId" = $1`

## 📌 Environment

Misskey 12.69.0 PostgreSQL 10.15

**Comment by mei23** [comment]
descriptionを1024=>2048にしてるのにマイグレスクリプトを書いてない
でも2048でも少ないかな
https://github.com/syuilo/misskey/commit/2be13736c839d1b191f630fc6bae125d9f7b3047#diff-bc4f48da70d5c21214704569bb7b89073769d3a8ea54085bf448039c88b87084
