### ISSUE TITLE
TypeError: Cannot read property 'all' of undefined

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7217]
## 💡 Summary

`TypeError: Cannot read property 'all' of undefined

![misskey-typeerror](https://user-images.githubusercontent.com/1679025/108157271-535b9d00-70b0-11eb-91f2-c83d6a7bcdff.png)
`
## 📝 Steps to Reproduce

1. Login
2. Visit https://www.example.com/instance/logs
3. error

## 📌 Environment

Misskey 12.69.0 PostgreSQL 10.15

**Comment by KisaragiEffective** [comment]
Triage: Latest stable release `2024.5.0` does not have such path. Please re-open if this is still able to reproduce on latest.
