### ISSUE TITLE
Pages:変数を代入しないオプション

### ISSUE THREAD

**Issue by futchitwo** [misskey-dev/misskey#7225]
## Summary

本文のテキストへAiScriptやKaTeXを書くときに`{}`が変数の代入として扱われ不便なので、それをブロック毎に無効にするオプションがほしい

**Comment by marihachi** [comment]
良さそう
JSONでもこの問題がある

**Comment by syuilo** [comment]
related: https://github.com/syuilo/misskey/issues/6710
