### ISSUE TITLE
I can't join Misskey.io anymore

### ISSUE THREAD

**Issue by kazukyakayashi** [misskey-dev/misskey#7244]
## 💡 Summary & ☹️ Actual Behavior

I can't join Misskey.io anymore, when I try to look at a user's profile it doesn't find anything.

```
{
	message: 'Internal error occurred. Please contact us if the error persists.',
	code: 'INTERNAL_ERROR',
	id: '5d37dbcb-891e-41ca-a3d6-e690c97775ac',
	kind: 'server',
	info: {
		e: {
			message: 'Could not find any entity of type "DriveFile" matching: "8344bpcqd1"',
			code: 'EntityNotFound',
			stack: 'EntityNotFound: Could not find any entity of type "DriveFile" matching: "8344bpcqd1"\n    at new EntityNotFoundError (/home/misskey/misskey/node_modules/typeorm/error/EntityNotFoundError.js:11:28)\n    at /home/misskey/misskey/node_modules/typeorm/entity-manager/EntityManager.js:544:51\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async DriveFileRepository.pack (/home/misskey/misskey/built/models/repositories/drive-file.js:82:54)\n    at async Promise.all (index 0)\n    at async Promise.all (index 16)\n    at async Object.awaitAll (/home/misskey/misskey/built/prelude/await-all.js:8:28)\n    at async NoteRepository.pack (/home/misskey/misskey/built/models/repositories/note.js:188:24)\n    at async Promise.all (index 3)\n    at async Promise.all (index 31)\n    at async Object.awaitAll (/home/misskey/misskey/built/prelude/await-all.js:8:28)\n    at async UserRepository.pack (/home/misskey/misskey/built/models/repositories/user.js:242:16)\n    at async /home/misskey/misskey/built/server/api/endpoints/users/show.js:97:16\n    at async Object.exports.default (/home/misskey/misskey/built/server/api/call.js:64:12)',
		},
	},
}
```

## 📌 Environment

Misskey 12.71 ( --> https://meow.zarchbox.fr/)
Debian 10
PostgreSQL

**Comment by SanMurakami** [comment]
What is your Misskey.io username?

**Comment by kazukyakayashi** [comment]
This happens when I try to see Syuilo's profile or Misskey's github bot @repo@misskey.io on my instance.

My username : @KazukyAkayashi@meow.zarchbox.fr

**Comment by SanMurakami** [comment]
![image](https://user-images.githubusercontent.com/37681609/109777349-f8e14580-7c46-11eb-86a7-19ce5c03eaf2.png)

I checked it out and it seems that meow.zarchbox.fr is rejecting Misskey.io's communication.
I also looked into other causes, but could not find any.

**Comment by kazukyakayashi** [comment]
I don't understand why, I didn't block misskey.io or stop traffic to the instance.

Could it be that it remained blocked but directly in the database (for some unknown reason) ?

**Comment by kazukyakayashi** [comment]
It's really strange even when I try to block the instance from the interface nothing happens (but the option to stop the traffic, it works).

https://user-images.githubusercontent.com/39823221/109788362-87d26b80-7c0f-11eb-93a0-92b878a5f359.mp4

**Comment by mei23** [comment]
> Could not find any entity of type "DriveFile" matching: "8344bpcqd1"

The DB is corrupted.
It may have been corrupted by a bug or you may have manually remove the record. 

> meow.zarchbox.fr is rejecting Misskey.io's communication.

The remote block flag does not affect the transmission result. 
I don't know, but it may be related to the lack of IPv6 connectivity in meow.zarchbox.fr. 

> Block UI doesn't work 

Bug #6353

**Comment by kazukyakayashi** [comment]
> The DB is corrupted.
> It may have been corrupted by a bug or you may have manually remove the record.

😨 ... I did not touch the database manually,
Is it possible to repair this corruption, recreate the record by hand or force a resynchronization ?
