### ISSUE TITLE
Add an option to show/copy TOTP token directly, and give backup code in case 2fa device is unavaiable

### ISSUE THREAD

**Issue by subsys-R9boq8** [misskey-dev/misskey#7253]
I hope someone can add an option to show/copy TOTP token directly during 2 factor authentication setup process.
Though most users uses an 2fa app on the phone like Google authenticator, MS authenticator and AndOTP, some may prefer to use a solution with desktop app or browser extension (like Bitwarden) to manage their 2fa credential to complete the setup, which can be inconvenient.

![image](https://user-images.githubusercontent.com/64412822/108949486-66e0a800-765c-11eb-98d2-e4066a19bd1e.png)

I would also be appreciated if misskey can show user some backup code before the setup is complete, for user to login in case the 2fa device is temporarily unavailable, like Github.

**Comment by tamaina** [comment]
I made a PR to display the content of qr.

Implementing the backup code is going to take a bit of work.  
I would prefer to implement email authentication (but not yet implemented), since backup codes may get leaked just like passwords.

**Comment by tamaina** [comment]
Resolved by https://github.com/misskey-dev/misskey/commit/98e42ec6ffd245f522bc1cbceda0d3f84d3330b5
