### ISSUE TITLE
Non-ASCII URLs are truncated

### ISSUE THREAD

**Issue by RichardDern** [misskey-dev/misskey#7257]
## 💡 Summary

URLs containing non-ASCII characters are truncated when displayed in a posted message.

Example of problematic URL: https://fr.wikipedia.org/wiki/Wikipédia:Accueil_principal

## 🙂 Expected Behavior

URLs should be encoded, which should also increase security to some level, either using [punycode](https://en.wikipedia.org/wiki/Punycode) or encodeURI.

## ☹️ Actual Behavior

Once posted, the URL is truncated to https://fr.wikipedia.org/wiki/Wikip

## 📝 Steps to Reproduce

1. Add a URL containing non ASCII characters, such as https://fr.wikipedia.org/wiki/Wikipédia:Accueil_principal
2. Post the message
3. See how the URL (and preview) is truncated to https://fr.wikipedia.org/wiki/Wikip

## 📌 Environment

Misskey v12.71.0
Node.js v15.9.0
PostgreSQL v11.11 (Debian 11.11-1.pgdg100+1)
Redis v5.0.3

**Comment by RichardDern** [comment]
Note that the issue is not raised if I add manually encoded URL to my message instead, ie https://fr.wikipedia.org/wiki/WikipWikip%C3%A9dia%3AAccueil_principal%0A instead of https://fr.wikipedia.org/wiki/Wikipédia:Accueil_principal

**Comment by tamaina** [comment]
Try `<http...>` notation like below

```
<https://fr.wikipedia.org/wiki/Wikipédia:Accueil_principal>
```

**Comment by acid-chicken** [comment]
Related to #4430

**Comment by RichardDern** [comment]
Yep, adding <> works 👍
Thanks !
