### ISSUE TITLE
Cannot read property 'series' of undefined

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#7258]
## 💡 Summary

After getting error, unable to browse to different links!!

```
6038.12.71.0.js:1 
Uncaught (in promise) TypeError: Cannot read property 'series' of undefined
    at Proxy.renderChart (6038.12.71.0.js:1)
    at Proxy.fetchChart (6038.12.71.0.js:1)

```
## 🙂 Expected Behavior

No error and no blank pages

## ☹️ Actual Behavior

All of these links and others lead to blank page
```
https://cliq.social/explore
https://cliq.social/featured
https://cliq.social/announcements
```
## 📌 Environment

misskey 12.71.0 - node 12.20.2 - postgresql v10.15

**Comment by futchitwo** [comment]
I don't know how exactly to reproduce this bug. Is it fixed in the latest version?

**Comment by KisaragiEffective** [comment]
Triage: `2024.5.0` do not have those issues: `/explore` has no error, and others are not contained. Please re-open if this is still able to reproduce on `2024.5.0`.
