### ISSUE TITLE
Whitelist Option (EDITED)

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#7259]
## Summary

I love the custom options for Misskey, and I think it is amazing work. I would love to move my users to Misskey! 
They really value privacy, and a "whitelisting feature" would be perfect. Creating a server in whitelist mode, other servers cannot interact with you by default unless you "whitelist" that server, as opposed to a blacklist where you only stop certain servers from interacting. 

EDITED: Thank you for pointing out local-only posts already exist!!

**Comment by rinsuki** [comment]
local-only posts are already implemented

![image](https://user-images.githubusercontent.com/6533808/109094433-4c422800-775d-11eb-8c10-796ff6a65fca.jpeg)

**Comment by ghost** [comment]
> local-only posts are already implemented
> 
> ![image](https://user-images.githubusercontent.com/6533808/109094433-4c422800-775d-11eb-8c10-796ff6a65fca.jpeg)

Thank you!! I wasn't sure what all was meant by home, I also didn't see local-only, but I see it is clearly there now.

**Comment by belatedly** [comment]
I am looking for this feature as well - I have used it in the past with Pleroma and I know it is also available with Mastodon. If there's any plans to implement it into Misskey that would be amazing.

**Comment by KisaragiEffective** [comment]
duplicated: #2318
