### ISSUE TITLE
speakeasyがNOT MAINTAINEDなのでどうにかする

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#7260]
## Summary
speakeasy（二段階認証で使っているライブラリ）がNOT MAINTAINEDなのでどうにかする

**Comment by tamaina** [comment]
そんなに複雑なライブラリでもないしただちに動かなくなることはない気はするけど、将来的に何かが起きる予感

**Comment by tamaina** [comment]
https://www.npmjs.com/package/otpauth

これ使うとか

**Comment by tamaina** [comment]
なんで先送りにしたんだっけ

**Comment by tamaina** [comment]
QRコードの生成で難儀したのか

そもそもQRコードいる？？

**Comment by CyberRex0** [comment]
QRコードはスマホで管理する2段階認証アプリでは圧倒的便利なため必須

**Comment by tamaina** [comment]
> QRコードはスマホで管理する2段階認証アプリでは圧倒的便利

スマホでotpauthリンクを踏めば登録できる気がする

**Comment by CyberRex0** [comment]
PCからスマホは？(Google Authenticatorなど)

**Comment by sim1222** [comment]
PCでMisskeyを開いていてスマホの2段階認証アプリしか使っていないユーザー（Google Authenticatorなどが大半）の場合に不便になるかも

**Comment by tamaina** [comment]
まあそうか

**Comment by tamaina** [comment]
otpauthにした

（QRコードが原因ではなくて、単純に面倒だったのか他のことに意識が行ったかでやらなかっただけっぽい）
