### ISSUE TITLE
絵文字ピッカーにカテゴリのタブを付けてほしい

### ISSUE THREAD

**Issue by mendakon** [misskey-dev/misskey#7264]
絵文字ピッカーにカテゴリのタブをつけてほしい
絵文字が多くにゃると、下の方にあるカテゴリを見に行くのに、いちいちその上にある全カテゴリの絵文字を読み込む必要があり無駄にゃので。

よろしくお願いします！

**Comment by syuilo** [comment]
絵文字ピッカーの狭い幅で表示できるタブ数は6くらいが限界なのと、絵文字をその6くらいのカテゴリにどういう粒度で分類するかがなかなか難しいので、タブというよりは各々の絵文字カテゴリセクションをデフォルトで折りたたんだ状態で表示するようにして、カテゴリ名をクリックすることで展開できるようにするデザインになりそう
