### ISSUE TITLE
Too many links fill up bottom of page

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#7269]
## 💡 Summary

If member creates a page and add different details, a preview box is added at the bottom if it includes a link.

Reference: https://cliq.social/notes/8ip7aeka4b

## 🙂 Expected Behavior

do not repeat links

## ☹️ Actual Behavior

for each link in a list, a preview is added at the bottom

## 📝 Steps to Reproduce

1. create a new page
2. add a list of anything including links
3. bottom of page keeps creating new boxes

## 📌 Environment

misskey 12.71.0 - node 12.20.2 - postgresql v10.15

**Comment by tamaina** [comment]
Try `?[link text](https://example.com)` syntax (to add `?` to the head) for each link.

**Comment by KisaragiEffective** [comment]
triage: 
> for each link in a list, a preview is added at the bottom

このissueのポイントは同じリンクを複数回ペーストするとその分だけプレビューがノート下部に生成されることと思われる。しかし、2024.5.0ではそのような問題が起きていない:

![image](https://github.com/misskey-dev/misskey/assets/48310258/4b9235eb-3227-43a8-9448-6e6f51ab3e47)

よって、このissueをcloseする。

----

Please let us know for re-opening if your intention does not match with above.
