### ISSUE TITLE
Firefoxにおいて、overflow: clipをflexな要素で使うとバグる

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#7272]
## 💡 Summary
カラムスタックにバグがある

## 🙂 Expected Behavior
均等に表示される

## ☹️ Actual Behavior
タイムラインカラムをスタックすると、一番上のタイムラインしか表示されない

## 📝 Steps to Reproduce

1. タイムラインカラム①を作成
2. タイムラインカラム②を作成
3. ②を左に重ねる

## 📌 Environment
Misskey v12.72.0, Firefox 87.0b3 (64 ビット)

**Comment by tamaina** [comment]
Firefoxだけのバグっぽいな

**Comment by tamaina** [comment]
というか、Flexboxの状態が全体的に変

![image](https://user-images.githubusercontent.com/7973572/109415017-8e879580-79f9-11eb-8a92-6d8c3ef11bfc.png)

**Comment by tamaina** [comment]
overflow: clipが全体的に悪さしてそうな感じ？

**Comment by tamaina** [comment]
clip消したら正常になったのでclipがダメだなぁ

**Comment by tamaina** [comment]
そもそもなんで書き換えたの（パフォーマンス？） @syuilo

**Comment by syuilo** [comment]
overflow hiddenに比べて省メモリでパフォーマンスが良いのと、clipにするとoverflowをhiddenしつつposition stickyが効くようになるという、ほぼhiddenの上位互換だから(hiddenと比べたときのclipの制約としてJavaScriptを使っても中身をスクロール出来ないというのがあるけど、Misskeyではそのようなことはしていないので全て置き換えて大丈夫だと判断した)

**Comment by tamaina** [comment]
なるほど……

解決策があるかもしれないけど、とりあえずhiddenに戻すのが無難かなと…（Firefoxに対応させるなら

**Comment by tamaina** [comment]
overflow: clipって、たぶん要素の幅とかを全く気にせずclipしちゃうからパフォーマンスが爆上げするという話なんだろうけど、flexboxは計算された本当の幅をもとに計算するものだから、デザインが成立しなくなってしまう…という感じかしら？

Chromeで崩壊してないのはclip指定がそもそも効いてないっぽい

**Comment by tamaina** [comment]
…えっ？そもそもプロパティが効いてないのに追加したってこと？
