### ISSUE TITLE
Emojis selector blinks and be unusable with Chromium browsers on ARM

### ISSUE THREAD

**Issue by kazukyakayashi** [misskey-dev/misskey#7274]
## 💡 Summary

On the web app with [Bromite](https://www.bromite.org/) (Chromium fork) on Android, the emojis selector is unusable.

## ☹️ Actual Behavior

The emojis selector is extremely slow and blinks constantly.
[For exemple on Bromite](https://meow.zarchbox.fr/notes/8isty762yi)

## 📌 Environment

Misskey 12.72.0
Android 10

**Comment by kazukyakayashi** [comment]
I tried with Chromium directly, the result is a little bit the same, it's unusable, it's extremely slow and Chromium has crashed 2 times.

**Comment by tamaina** [comment]
Chromeだと特に重い。しかしEdgeやFirefoxはあんまり問題にならない感じがある。

**Comment by syuilo** [comment]
遅いのと点滅は別の問題で、遅いのに関して詳細は https://github.com/syuilo/misskey/issues/7276 に

**Comment by tamaina** [comment]
リンク先が見えなかったので適当に判断しちゃったけど、別の問題なのか

**Comment by defango** [comment]
I am also having a similar issue with Chrome and the PWA. I have also checked on safari and its the same issue. I’m using ipad pro and a windows desktop. When it is clicked nothing happens, the picker does not open up.

**Comment by kazukyakayashi** [comment]
I don't have any more problems since the recent misskey updates.
I've emptied the cache on misskey and it's running.

**Comment by tamaina** [comment]
問題報告が最近ないのでcloseします
