### ISSUE TITLE
リアクションピッカーのVNodeが再構築される

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#7276]
最近の改修でリアクションピッカーが再利用されるようになり、表示が爆速になったが、何故か実際のインスタンスで動くMisskey上ではパフォーマンス改善していないか、むしろ悪化している

Chromeのパフォーマンス計測ツールで調べたところ、実際のインスタンスでは、DOM上のリアクションピッカーは想定しているように再利用されているが、**何故かVNodeが再構築されている**っぽい。
ローカルではそのような再構築はトリガされていない。

何故ローカルとそれ以外でVueの挙動が違うのかが本当に謎で、いくつか思い当たる差異を洗い出してみたがどれも該当しなかった。

- ビルド時のオプションが違う？
  - ローカルでproduction指定してビルドしたが再現せず。インスタンス側もproductionビルドである
- Vueのバージョンが違う？
  - それはなさそう
- なんらかのクライアント設定が違う？
  - ローカルとインスタンスでそれぞれ新しくアカウント作って同じ状態にしても、やはり前者と後者で挙動が違う
- ブラウザのバージョンが違う？
  - 同じブラウザで試しても再現した

**Comment by tamaina** [comment]
c2.a9z.devではそんなに重さを感じないけどmisskey.ioでは極めて重たい

違いといえば、カスタム絵文字が多いかどうかぐらい？

**Comment by syuilo** [comment]
c2.a9z.devで確認してみたら、vnode再構築してなかった(ローカルと同じ)

**Comment by syuilo** [comment]
つまりインスタンスによって挙動が違うのか

**Comment by syuilo** [comment]
期待した挙動になっているインスタンス
- しゅいろのローカルインスタンス
- c2.a9z.dev

VNodeが再構築されるインスタンス
- sushi.suki
- misskey.io

**Comment by SanMurakami** [comment]
ちなみに重たい原因、Misskey.ioの場合タグが大量に設定されていることも関係してそう。

ioの場合はタグだけで109個ぐらいタブの要素があって、それをdevtoolsから消してみたらかなり軽くなった

**Comment by syuilo** [comment]
> ちなみに重たい原因、Misskey.ioの場合タグが大量に設定されていることも関係してそう。

VNodeが再構築されなければいくらタグがあってもパフォーマンスにはほぼ影響しない(初回起動時に少し重い程度)から、関係ないと言えばないかな

**Comment by SanMurakami** [comment]
もしかしたら要素が多すぎてChromeで自動的に消されてるかも？

**Comment by mendakon** [comment]
すしすきもタグ結構ありました！

**Comment by syuilo** [comment]
> もしかしたら要素が多すぎてChromeで自動的に消されてるかも？

DOM自体は残っていることは確認してる
VNodeだけが再構築される

んでVNodeはあくまでもVue内部のシステムなのでそれがブラウザによって干渉されることはないだろう

**Comment by syuilo** [comment]
Vueのバグかどうかは不明なものの、インスタンスによってそれが起きるかどうかが異なるのが本当に謎
その理由さえわかれば解決できそうなのに

**Comment by SanMurakami** [comment]
とりあえずioの絵文字DBエクスポートして渡すからローカルで突っ込んで挙動確認してみてほしさある

**Comment by syuilo** [comment]
仮説として、あるvnodeがメモリ的に大きい場合、Vueがそのvnodeをメモリから解放する、みたいな処理がもしかしたらあるのかもしれない

**Comment by SanMurakami** [comment]
ioの絵文字CSV
https://s3.arkjp.net/misskey/bd7aefdf-6f31-4483-a689-4b47a708a297.csv

**Comment by syuilo** [comment]
参考:

## vnodeが再構築されないケース
![image](https://user-images.githubusercontent.com/4439005/109461649-d19f4280-7aa5-11eb-9d29-15ff6585e472.png)

## vnodeが再構築されるケース
![image](https://user-images.githubusercontent.com/4439005/109461809-0a3f1c00-7aa6-11eb-957f-74f7cc1592ba.png)

**Comment by SanMurakami** [comment]
参考になるか分からないけど、スマホで見るとこんな感じの挙動になって常駐アプリが全部落ちる
（同一症状複数人確認済み）
https://s3.arkjp.net/misskey/76914c72-256d-4b1e-8fe4-13e47e04f958

**Comment by syuilo** [comment]
あ、ioの絵文字インポートしたらローカルで再現した

**Comment by syuilo** [comment]
![image](https://user-images.githubusercontent.com/4439005/109463240-014f4a00-7aa8-11eb-827c-dedb15110e98.png)

**Comment by acid-chicken** [comment]
VNode 維持してくれる上限値突破してるとかでは

**Comment by syuilo** [comment]
かなー

**Comment by syuilo** [comment]
タグのセクション消したら再現しなくなった

**Comment by syuilo** [comment]
原因はよくわからんけど一旦↑の状態でリリースするか

**Comment by syuilo** [comment]
あと、**何がトリガーになって**再構築が走るのかも気になる
すごく雑にいうとCSSを使って要素の表示/非表示を切り替えて位置移動させてるだけなので、そのうちのどれがトリガーになるのかわかれば改善の余地が生まれそう

**Comment by syuilo** [comment]
(おそらく、コンポーネントが感知しているリアクティブな値のミューテーションとかだろうけど…)

**Comment by tamaina** [comment]
今はどうだろう？

**Comment by syuilo** [comment]
タグのセクションがあると何故かこの現象が発生するみたい。現在のピッカーはタグのセクション消したので影を潜めているけど、復活させたら再発しそう

**Comment by tamaina** [comment]
Vueのバージョンも上がったしワンチャン

**Comment by syuilo** [comment]
また発生するようになった(今回もローカルでは再現しない)
![image](https://user-images.githubusercontent.com/4439005/177426469-2cedf87a-7a20-42ff-8fe5-2d39f7e1851e.png)

**Comment by syuilo** [comment]
最近絵文字ピッカー周り弄ったのこのコミットくらいしかないからこれが原因そう
https://github.com/misskey-dev/misskey/commit/bc73ad2e5650217f8910f28eab994cc713af5659

**Comment by syuilo** [comment]
あれ、revertしたけど変わらん

**Comment by syuilo** [comment]
あー
そういえば大量の絵文字インポートした直後から発生してそうだから、やっぱり登録している絵文字の多さによって発生する/しないが決まるっぽい(もしくは常に発生しているけど絵文字数が少ないとVNode再構築の時間も短いから気づかないだけかも)

**Comment by syuilo** [comment]
v-once設定したら爆速になった
おそらくこの辺のfilterの計算が重かった可能性が高そう
https://github.com/misskey-dev/misskey/blob/6d7a29b2cbb0239dbe85b05b2592a4cbf99d93fd/packages/client/src/components/emoji-picker.vue#L64

**Comment by syuilo** [comment]
closeで良さそう
