### ISSUE TITLE
The date format is "yyyy/mm/日" on profile page on Edge browser.

### ISSUE THREAD

**Issue by fz0000** [misskey-dev/misskey#7278]
## 💡 Summary

date format error on user profile page on MS Edge browser.
## 🙂 Expected Behavior

Firefox is OK:
![image](https://user-images.githubusercontent.com/5061311/109525867-eb17ad00-7aec-11eb-9f60-a58771dc1912.png)

Chrome(and the new WebKit based Opera) is OK:
![image](https://user-images.githubusercontent.com/5061311/109526150-3b8f0a80-7aed-11eb-880b-376b8d397d09.png)

## ☹️ Actual Behavior

The format is incorrect on Edge:
![image](https://user-images.githubusercontent.com/5061311/109525719-c9b6c100-7aec-11eb-8595-e632bce661b0.png)

## 📝 Steps to Reproduce

1. Log in to misskey.io
2. Go to https://misskey.io/settings/profile
3. Check the Birthday area in the form.

## 📌 Environment
develop

OS: Win10 x64
Microsoft Edge: 88.0.705.81
Firefox: 86.0
Chrome: 88.0.4324.190
Opera: 74.0.3911.160

**Comment by tamaina** [comment]
It seems to be fixed.

**Comment by fz0000** [comment]
Re-test on current https://misskey.io/ (version 12.89.2) with MS Edge (version 92.0.902.84), this issue still occurs.
I guess it has something to do with MS Edge languages (i.e. MS Edge App is displayed in this language)

For example:
- Arabic:
![image](https://user-images.githubusercontent.com/5061311/131210432-e171d457-ed0b-4305-8d3c-ba8c253b9dad.png)
- Chinese (Simplified):
![image](https://user-images.githubusercontent.com/5061311/131210434-b304a1ae-aad3-4c6d-8f83-d6f3f3634c9e.png)
- Chinese (Traditional):
![image](https://user-images.githubusercontent.com/5061311/131210439-3092477d-06c5-4b21-a7ed-e68334e12179.png)

- You can try to reproduce it by changing MS Edge display language:
![image](https://user-images.githubusercontent.com/5061311/131210712-3100bca2-bdeb-4966-902e-ffdad08d66f4.png)

**Comment by rinsuki** [comment]
It can be reproduce with simple `<input type="date">` (it is used by Misskey), that means its Edge side issue.
Please report to Microsoft instead of Misskey.

![image](https://user-images.githubusercontent.com/6533808/131211007-fef950aa-0030-4897-89c5-08e71ce9997e.png)
