### ISSUE TITLE
Missing birthday indicator on profile page on MacOS X Safari

### ISSUE THREAD

**Issue by fz0000** [misskey-dev/misskey#7279]
## ☹️ Actual Behavior

No indicator on profile page and error occurs when user input an invalid date.

https://user-images.githubusercontent.com/5061311/109538147-b3affd00-7afa-11eb-8409-6afb0f9d53f7.mp4

## 📝 Steps to Reproduce

1. Launch Safari on MacOS X.
2. Log in to misskey.
3. Go to https://misskey.io/settings/profile
4. Input a invalid string in Birthday textbox.

## 📌 Environment

develop

macOS Big Sur 11.0.1 (20B50)
Safari: 14.0.1 (16610.2.11.51.8)

PS: This is a virtual machine. I will re-test on a real Mac mini later.

**Comment by fz0000** [comment]
Not sure if it's related to #7278

**Comment by fz0000** [comment]
Re-test on real Mac mini(Late 2012), and this issue also occurs.
macOS Catalina 10.15.7 (19H524)
Safari: 14.0.3 (15610.4.3.1.6, 15610)

**Comment by fz0000** [comment]
It seems to be the Safari issue.
https://bugs.webkit.org/show_bug.cgi?id=195666

**Comment by rinsuki** [comment]
It should be fixed in Safari 14.1 (macOS 11.3~, iOS 14.5~)
