### ISSUE TITLE
一部の携帯端末で投稿時のリアクションピッカー画面がちらつく

### ISSUE THREAD

**Issue by mendakon** [misskey-dev/misskey#7296]
一部の携帯端末で投稿時のリアクションピッカー画面がちらつく

すしすき～にて現在2件確認

1. Android10のVOG-L29、ブラウザはChrome
2. xiaomiのmi9t pro、ブラウザはchrome

上記2つは12.730で起こっているが、
このバグは12.72.0の時から確認されていて、12.73.0で改善されたたケースもあり。

12.71.0では確認していない。

**Comment by tamaina** [comment]
Duplicate of #7274
