### ISSUE TITLE
Profiles no longer show integrations!

### ISSUE THREAD

**Issue by Mstrodl** [misskey-dev/misskey#7300]
## 💡 Summary

User's integrations used to be showed on profile pages (Discord, Github, etc.) but they aren't any more

## 🙂 Expected Behavior

User integrations should show

## ☹️ Actual Behavior

There are no integrations shown

## 📝 Steps to Reproduce

1. Enable an integration (Like github)
2. Link your account with an integration (Like github)
3. Navigate to your profile page and see there's no Github entry

## 📌 Environment

Linux, misskey develop branch

**Comment by Mstrodl** [comment]
Seems to have been removed with v12

**Comment by tamaina** [comment]
仕様なのか単に忘れているだけなのか @syuilo

**Comment by syuilo** [comment]
以前案内しましたが、廃止しました(URLをbioに書けば済む話なので)

**Comment by Mstrodl** [comment]
@syuilo I liked the special spot and icons for it (and it demonstrates ownership from a trusted instance)

I would be okay with creating a PR for this

**Comment by syuilo** [comment]
FYI:
Some people don't want their linked services to be public, so each service will need to have a "Show in profile" option when implementing this.
