### ISSUE TITLE
Tool for deleting notes (for users)

### ISSUE THREAD

**Issue by kazukyakayashi** [misskey-dev/misskey#7302]
## Summary

It would be useful to be able to delete the notes directly from the user interface with a button provided for this purpose, and why not with options such as :

- since X months
- delete grades of more than X years

**Comment by 4ioskd** [comment]
I hope this pull request will be merged.
https://github.com/codl/forget/pull/544

**Comment by Johann150** [comment]
For your information, the above linked pull request has been merged.
