### ISSUE TITLE
Chromium browser crashes when attaching files

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7305]
## 💡 Summary

Chromium browser crashes when attaching files

## 🙂 Expected Behavior

Was able to attach files in previous version 

## ☹️ Actual Behavior

Each time I try to attach a file browser exits

## 📝 Steps to Reproduce

1. Create note
2. Click attach files button
3. Browser crash each time

## 📌 Environment

Misskey 12.73.0 Chromium 89.0.4389.72

**Comment by SanMurakami** [comment]
What is your operating system?

**Comment by okpierre** [comment]
More testing using same steps as above but in different browsers ...

Chrome 89.0.4389.72 (window stays open)
```
Uncaught TypeError: Cannot read property 'offsetWidth' of null
    at Proxy.align (app.12.73.0.js:2)
    at ResizeObserver.<anonymous> (app.12.73.0.js:2)
align @ app.12.73.0.js:2
(anonymous) @ app.12.73.0.js:2
```


Firefox 86.0 (window stays open)
```
Uncaught (in promise) DOMException: The operation is insecure. app.12.73.0.js:2
Uncaught (in promise) DOMException: The operation is insecure. app.12.73.0.js:2

Uncaught TypeError: e is null
    align https://misskey/assets/app.12.73.0.js:2
    mounted https://misskey/assets/app.12.73.0.js:2
    mounted https://misskey/assets/app.12.73.0.js:2
    promise callback*Ht https://misskey/assets/app.12.73.0.js:2
    mounted https://misskey/assets/app.12.73.0.js:2
    kt https://misskey/assets/app.12.73.0.js:2
    Ct https://misskey/assets/app.12.73.0.js:2
    __weh https://misskey/assets/app.12.73.0.js:2
    Ut https://misskey/assets/app.12.73.0.js:2
    Wt https://misskey/assets/app.12.73.0.js:2
    promise callback*Rt https://misskey/assets/app.12.73.0.js:2
```

**Comment by syuilo** [comment]
おそらくそれらのエラーは関係ありません。Chromiumは不安定な傾向があるため、Chromium側のバグでWebサイトがクラッシュするのは比較的良くあることです(次のバージョンでしれっと直ってたりする)

**Comment by SanMurakami** [comment]
![image](https://user-images.githubusercontent.com/37681609/110141641-b8392600-7e18-11eb-9893-aefa39c3844b.png)
It is working fine on Chrome 89.0.4389.72 on my M1 MacBook Air (macOS 11.2.1).

**Comment by SanMurakami** [comment]
![image](https://user-images.githubusercontent.com/37681609/110142082-24b42500-7e19-11eb-8437-bda776381fcb.png)
It is also working fine on Chrome 89.0.4389.72 on Windows 10.

This problem may be caused by your Chrome.

If you can't solve the problem by trying in guest mode, I recommend you to reinstall Chrome.

**Comment by okpierre** [comment]
This was not happening before upgrading to the new version of Misskey. Will test more.

**Comment by okpierre** [comment]
Upgraded another Chromium browser to 89.0.4389.72 and no problems. Just on that computer. Closing this issue.
