### ISSUE TITLE
Behavior of the emoji picker (especially for PWA)

### ISSUE THREAD

**Issue by kazukyakayashi** [misskey-dev/misskey#7321]
## Summary

I find the new emojis selector not really practical especially on the mobile version (PWA), having the selector window that remains permanently displayed is quite annoying, especially for cell phones with normal size screens (example my Nexus 5)

Would it be possible to add an option to enable or disable the behavior? And thus return to the behavior it had before.

**Comment by mendakon** [comment]
I completely agree. I think a bigger problem is that after typing a colon, the list of emoji appears and takes up most of the screen.

**Comment by defango** [comment]
that’s weird I am not able to get the emoji picker to even pop up in the PWA or chrome

**Comment by mendakon** [comment]
> that’s weird I am not able to get the emoji picker to even pop up in the PWA or chrome

Oh, I think that's a different context than this issue.
See next. #7274 #7276
