### ISSUE TITLE
Can't start messaging

### ISSUE THREAD

**Issue by FinecoFinit** [misskey-dev/misskey#7329]
## 💡 Summary

![image](https://user-images.githubusercontent.com/22540805/110628061-df06ac00-81cc-11eb-8d1e-d5f4c6a72c42.png)

there is no list with people, and this "ok" button is not working as well

## 📌 Environment

Browser: Firefox 86
Docker on Debian

**Comment by okpierre** [comment]
Maybe the same as https://github.com/syuilo/misskey/issues/6928?
