### ISSUE TITLE
Failed to load resource favicon.ico

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7332]
## 💡 Summary

Where is the favicon.ico stored? Which folder is it loaded from?

Failed to load resource: the server responded with a status of 404 () favicon.ico

## 🙂 Expected Behavior

No favicon.ico error when loading main page

## ☹️ Actual Behavior

Error when visiting page

## 📝 Steps to Reproduce

1. visit instance
2. broken favicon.ico loading
3. error message

## 📌 Environment

Misskey 12.74.1 Chrome 89.0.4389.82

**Comment by syuilo** [comment]
[/assets/favicon.png](https://github.com/syuilo/misskey/blob/develop/assets/favicon.png)が読み込まれます。
404になるのは再現できませんでした。

**Comment by okpierre** [comment]
@syuilo I installed Misskey on new server and same issue. I also have both favicon.**ico** and favicon.**png**

![misskeyfavicon404](https://user-images.githubusercontent.com/1679025/111015720-4e6ccf00-8378-11eb-9f6b-858ba48377b5.png)

**Comment by okpierre** [comment]
Here's what I tried:
-favicon.ico in assets folder / icon url = [blank]
-favicon.ico in assets folder / icon url = static-assets/favicon.ico
-favicon.ico in assets folder / icon url = https://misskey/static-assets/favicon.ico

Still showing 404 for each
