### ISSUE TITLE
ファイル削除時に参照しているノートを削除しないようにする

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#7346]
## Summary
#4724 でファイル削除時に参照しているノートも削除するようにしているが
https://github.com/syuilo/misskey/blob/9cf811b048c03d093871b21c0a357813746378af/src/services/drive/delete-file.ts#L89-L112

- `Note.fileIds (Array)`のクエリに (このままでは) インデックスが効かないので重い。
- ちゃんとトランザクションを張る必要があるが、関連するノートの探索もあるのでトランザクションがややこしくなる。
- リモート起因のノートが削除された際には、どのノートからも参照されなくなったファイルを削除する必要があるが、ファイルが削除されたらノートも削除するの規則もあるとややこしくなる。

ので、ドライブファイルが削除されてもノートには何もしない方が良さそう。
ノートなどがDB上で削除されていたファイルを参照していた場合は参照してなかったことにしてしまう (#7345 でまかなえる)
や v10 のようにドライブファイルは論理削除にしてしまうなど。

**Comment by syuilo** [comment]
論理削除にしたくなってきた
ref. https://github.com/syuilo/misskey/issues/7342

**Comment by mei23** [comment]
ドライブファイルは別に物理削除でいいと思う。
削除した跡を残したい場合、ノートから参照しているドライブファイルがなかったらそれは削除済みだと区別付くので。

**Comment by mei23** [comment]
解決済み
