### ISSUE TITLE
グループメンション

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#7348]
## Summary

グループにscreen name的なものを設定できるようにして、そのscreen nameあてにメンションすることでそのグループメンバーに通知がいくようになる

**Comment by syuilo** [comment]
`a-zA-Z0-9_`以外も使えるようにしたいのと、通常のメンションと区別するために、多分
```
@@ほげグループ
```
になりそう

**Comment by tamaina** [comment]
グループ廃止
