### ISSUE TITLE
How to migrate from local to server?

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7349]
I couldn't find any documentation to migrate from local to server

Goal is to only backup and move **necessary** folders

All other files and folders (optional) are recreated from new pull

Which folder is used by Misskey to store files?
Which files are newly created by Misskey after initial setup?

**Comment by defango** [comment]
If you are going to be migrating local to Server you really only need to be  taking the. /files folder. That’s where all the Photos and Videos are uploaded everything else is in the Database. I have moved a couple of times between servers and it seems pretty straight forward. 

1. Rsync your Local /files to the server in the “misskey” folder. I moved about 50 gigs in no time.
2.  Next Dump your Database and import to your new server.
3.  then you can just finish the Misskey install as normal and when you INT the Database it should pick up right where you left off on the local server. 

if you followed the Misskey Tutorial your files should be in /misskey/misskey/files

**Comment by okpierre** [comment]
One folder and a DB dump is great news! I'll give it a try. 

Thanks for sharing the details.

**Comment by defango** [comment]
Ya, seems pretty simple. I would just get the server setup to step 5 and build Misskey. Then move your files and database into place. Updated your config for the new user on postgres and you should be good to go to finish off the install and get it running
