### ISSUE TITLE
Duplicate HSTS used in headers

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7350]
## 💡 Summary

Instead of just one `strict-transport-security` HSTS listed, Misskey adds additional one

## 🙂 Expected Behavior

Only one HSTS listed if nginx is already configured with it

## ☹️ Actual Behavior

There is another one added by Misskey

## 📝 Steps to Reproduce

1. browse default nginx with HSTS configured
2. add misskey and nginx. check header
3. shows two `strict-transport-security` in headers

## 📌 Environment

Misskey 12.74.1 Chrome 89.0.4389.82 nginx 1.18.0

**Comment by mei23** [comment]
順番的に重複ヘッダを追加してるのはnginxじゃないの？とか思いつつ…

Related: https://github.com/syuilo/misskey/issues/2923

Misskey can be disabled with config 
https://github.com/syuilo/misskey/blob/7d02b36092bbb4e1887abde57500e3aba13497f4/.config/example.yml#L117

**Comment by okpierre** [comment]
> 順番的に重複ヘッダを追加してるのはnginxじゃないの？とか思いつつ…

Misskey sets its own HSTS value and nginx is adding the Misskey value.


> Misskey can be disabled with config

Thank you - `disableHsts` works!
