### ISSUE TITLE
misskeyディレクトリーを全部削除した後再度git cloneしたらダッシュボードが見れなくなった

### ISSUE THREAD

**Issue by Kami-0x10** [misskey-dev/misskey#7362]
参考にしたサイト
https://join.misskey.page/ja/wiki/developers/installation/ubuntu

画像
<img src="https://d3mo71axvjwtk1.cloudfront.net/m/20bb396c-15ab-42b3-8694-0d36c1e29180.png">

**Comment by Kami-0x10** [comment]
一応上のページに書いてあることは一通りやりましたが解決せず、、、
ビルドはうまくいっているはずです
たぶんこれ新規にMisskeyを入れてビルドしても同じ結果になると思います
そうでなければnodejs関連が怪しい

**Comment by Kami-0x10** [comment]
<img src="https://d3mo71axvjwtk1.cloudfront.net/m/2a71dfca-78aa-4402-9bb1-9f822920a350.png">
misskeyのバージョンを12.70.0に戻したらなおりました、、、
うーん

**Comment by syuilo** [comment]
CloudFlareなどのCDNは使用していますか？

**Comment by Kami-0x10** [comment]
クラフレは一応挟んでいます

**Comment by tamaina** [comment]
相当の時間が経っているためcloseさせていただきます。もしまだ不具合が継続しているようでしたらreopenをお願いいたします。
