### ISSUE TITLE
Violation message when viewing profile

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7388]
## 💡 Summary

[Violation] 'setTimeout' handler took [x] ms 
5927.12.75.0.js

## 🙂 Expected Behavior

No violations

## ☹️ Actual Behavior

@syuilo Each time you scroll violation is reported

![misskeysettimeoutviolation](https://user-images.githubusercontent.com/1679025/112074863-a14f3f00-8b4d-11eb-972f-ee5bb979e37c.png)

## 📝 Steps to Reproduce

1. Visit any profile
2. Scroll to the bottom
3. Error message
4. Scroll more
5. Additional error message

## 📌 Environment

Misskey 12.75.0 PostgreSQL 10.15

**Comment by Johann150** [comment]
I think this may have been caused by long loading times. I can not reproduce it.
