### ISSUE TITLE
Error when accessing log

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7393]
## 💡 Summary

TypeError: Cannot read property 'all' of undefined

reference to this https://github.com/syuilo/misskey/blob/5a8cc7851b4af9ae4a0d7efc5b66b224bbe9b4c8/src/client/pages/instance/logs.vue#L9

## 🙂 Expected Behavior

No errors

## ☹️ Actual Behavior

Accessing log as admin result in error

![misskeyallundefined](https://user-images.githubusercontent.com/1679025/112089818-c1d8c280-8b68-11eb-921f-50b3115d07ac.png)

## 📝 Steps to Reproduce

1. Login as admin
2. Click on menu instance and choose Logs 
3. Error message

## 📌 Environment

Misskey 12.75.0 PostgreSQL 10.15

**Comment by Johann150** [comment]
Could you please check if this issue still occurrs? The logs work fine for me at least since 12.87.0.

**Comment by okpierre** [comment]
Tried it with Misskey 12.88.0 and didn't encounter any error message.
