### ISSUE TITLE
v12 Webクライアントのメニューの表示設定をサーバーが記憶するようにする

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#7400]
## Summary

設定→メニュー→表示の設定がサーバーで記憶されていないため他環境からのログインでリセットされてしまうため記憶するようにしてほしい

※アップデートに伴い設定内容が変更されていたため12.89.2時点に合わせた内容に修正しました。

**Comment by futchitwo** [comment]
同期するなら、できればモバイルとそれ以外の設定で分けてほしいです
今使い分けているので

**Comment by syuilo** [comment]
環境が違うと画面サイズが違うことが多いと思うので(PC/スマホ/タブレットなど)、記憶すると逆にかなり不便になりそう
同期するかどうか設定できるようにすれば解決するけど、そこまでの複雑性を追加してまで作り込むメリットがあるかというと疑問(単に他の環境でも設定し直せば済む)

**Comment by tkmrgit** [comment]
> 環境が違うと画面サイズが違うことが多いと思うので(PC/スマホ/タブレットなど)、記憶すると逆にかなり不便になりそう
> 同期するかどうか設定できるようにすれば解決するけど、そこまでの複雑性を追加してまで作り込むメリットがあるかというと疑問(単に他の環境でも設定し直せば済む)

アップデートに伴って設定のテキストが変わっていたため修正しました。プロファイルみたいなの作れてサーバーに状態を保存した上で環境によって分けられるとベストだけどそこまでは厳しいか...

**Comment by syuilo** [comment]
あー
まあ実装するとしたらそんな感じにするか
