### ISSUE TITLE
設定したテーマと背景の状態をサーバーが記憶するようにする

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#7403]
## Summary
他の環境からログインした際にテーマと背景の設定が記憶されないため、設定をサーバーで記憶するようにする。ユーザーによっては従来の設定が良い場合もあるため、環境によって解除もできるようになると望ましい

### テーマ関連未解決Issue
#6195 #6196

**Comment by syuilo** [comment]
テーマはサーバーに保存されている

**Comment by tkmrgit** [comment]
> テーマはサーバーに保存されている

“設定”したテーマと背景の“状態”をサーバーが記憶するようにする 
▲タイトルが適切ではなかったため変更しました。

**Comment by okpierre** [comment]
I login to 12.75.1, set theme, then login to another PC and theme is reset

Reference to previous issue https://github.com/misskey-dev/misskey/issues/6802
