### ISSUE TITLE
v12 投稿を右クリックでリアクションが出てこないようにする

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#7404]
## Summary

投稿を右クリックでリアクションできるようになっているが、通常のコンテキストメニューが出てくるようにしてほしい。

### 関連Issue
#7087 #7078 #7077

**Comment by syuilo** [comment]
設定で無効にできる

**Comment by tkmrgit** [comment]
> 設定で無効にできる

設定の場所が分からない :crying_ai: 😭

**Comment by syuilo** [comment]
![image](https://user-images.githubusercontent.com/4439005/112487454-0f02a180-8dc0-11eb-9ec3-f5b13d7bffa5.png)

**Comment by tkmrgit** [comment]
設定→リアクションからもできると良いかも。。ちょっと分かりにくかった。とりあえずCloseします
