### ISSUE TITLE
Blank users count in nodeinfo

### ISSUE THREAD

**Issue by RaZZlom** [misskey-dev/misskey#7410]
## 💡 Summary

A blank value where the number of users should be. I checked my instance and misskey.io.

[quietplace.xyz](https://quietplace.xyz/nodeinfo/2.0)
[misskey.io](https://misskey.io/nodeinfo/2.0)

## 🙂 Expected Behavior

25 users at my instance

## ☹️ Actual Behavior

usage: users: []

## 📝 Steps to Reproduce

1. Open in browser https://misskey.io/nodeinfo/2.0

## 📌 Environment

Misskey       - v12.75.1
Node.js        - v14.16.0
PostgreSQL - v13.2 (Debian 13.2-1.pgdg100+1)
Redis           - v5.0.3

**Comment by 4ioskd** [comment]
This issue is solved by #8126 and #8255 .
