### ISSUE TITLE
Option to edit and delete channels.

### ISSUE THREAD

**Issue by RaZZlom** [misskey-dev/misskey#7412]
## Summary

It would be great to be able to edit and delete channels. At the moment, there is a feeling that the channels are incomplete.

Screenshot from the Groups, for example:

![image](https://user-images.githubusercontent.com/73530026/112719231-f520a600-8f08-11eb-9da6-74dc6c7d2ba3.png)

**Comment by RaZZlom** [comment]
Oh, i found another request - https://github.com/misskey-dev/misskey/issues/7171
Sorry

**Comment by tamaina** [comment]
Duplicate of  #7171
