### ISSUE TITLE
Can not install misskey dependencies

### ISSUE THREAD

**Issue by ShrekisLyf** [misskey-dev/misskey#7414]
Hi,

I am currently following the setup instruction to have misskey running on my server, at the step after checking if there's an update
The guide says to run "yarn" to install dependencies
But it get a "ERROR: There are no scenarios; must have at least one." as there's something missing

**Comment by RaZZlom** [comment]
You use wrong yarn.

https://yarnpkg.com/
https://linuxize.com/post/how-to-install-yarn-on-debian-10/

**Comment by ShrekisLyf** [comment]
I do not use Debian, I have ubuntu,
And how can I use the wrong yarn?
What exactly do I have to install?
