### ISSUE TITLE
Internal server error when starting server

### ISSUE THREAD

**Issue by ShrekisLyf** [misskey-dev/misskey#7417]
Hello, I was able to install everything from misskey and start it, yet when I try to reach it, the site only says "internal server error"
Thjs is what gets outputted from the Console (I am on phone sorry for the quality) 
![Screenshot_20210328-223238_JuiceSSH](https://user-images.githubusercontent.com/63299919/112767233-cf34f780-9015-11eb-925b-da6a5a54e8ca.jpg)

**Comment by syuilo** [comment]
Try `npm run init `
