### ISSUE TITLE
ショートカットキー要望

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#742]
既存でしたら申し訳ないです

- タイムラインでダブルクリックに相当するもの
  * 同じキーでポップアップから戻れたらなおよいです
- タイムラインで`[j]`と逆の動きをするもの
- タイムラインでリアクションを開く→リアクションを付ける
  * テンキーで選ぶとよさそう

* デスクトップ版Misskey

**Comment by syuilo** [comment]
`j`の逆は`k`だった気がします

**Comment by syuilo** [comment]
あとリアクションに関しては既出です https://github.com/syuilo/misskey/issues/368

**Comment by tamaina** [comment]
ｲﾝﾌﾟﾘﾒﾝﾃｯﾄﾞ!!
