### ISSUE TITLE
Safari10(iOS10.3.3)においてmisskey webクライアントが開かない

### ISSUE THREAD

**Issue by Kami-0x10** [misskey-dev/misskey#7421]
調べてみたらvue.js周りで対処するしかないらしい
サファリ側のバグなのでデベロッパー側で対処するしかないみたい

**Comment by Mirei-Kagurazaka** [comment]
Misskeyを正しく動作させるためにはiOS12以降が必要なので、宗教上の理由がない限り最新のiOSにアップデートしてお試しください

**Comment by Kami-0x10** [comment]
iOS12以上でないとMisskeyがまともに動かないらしいのでクローズします
