### ISSUE TITLE
Misskey is not showing any pictures at all

### ISSUE THREAD

**Issue by ShrekisLyf** [misskey-dev/misskey#7423]
## 💡 Summary

Well, misskey is not showing any pictures whether it be profile pictures or just user uploaded pictures
## 🙂 Expected Behavior
It should show pictures

## ☹️ Actual Behavior
Well, pretty self explained, it doesn't show pictures

## 📝 Steps to Reproduce

1.go onto my misskey
2.log in or register
3.and voilà, no pictures, just the broken picture sign

## 📌 Environment
Ubuntu 20.04
Nodejs 12

Everywhere where pictures should be

**Comment by ShrekisLyf** [comment]
Update: misskey tries to reach https when I did not install ssl

**Comment by ShrekisLyf** [comment]
Well now misskey interferes with my second website and it can not find the files directory

**Comment by pplude** [comment]
Can confirm, I'm having the same issue on Misskey 12.108.1, installed via Docker-Compose

**Comment by KisaragiEffective** [comment]
triage: closing this as stale, please let us know if you reproduced with 2024.5.0 🙏🏻
