### ISSUE TITLE
Misskey doesn't support digits-only hashtags and breaks tags with dot

### ISSUE THREAD

**Issue by Ai-rin** [misskey-dev/misskey#7427]
In the example below, #123456 and #misskey.io are broken:
![Screenshot_20210403_192746](https://user-images.githubusercontent.com/29887769/113484925-9b455080-94b3-11eb-99ba-354e8c4abcc8.png)
## 📌 Environment
Misskey v12.75.1

**Comment by skobkin** [comment]
![image](https://user-images.githubusercontent.com/967576/113485662-69ce8400-94b7-11eb-9235-0cbf97b5c6b4.png)

@Ai-rin Mastodon too.

**Comment by Ai-rin** [comment]
@skobkin We can be better! :muscle:

**Comment by tamaina** [comment]
> Misskey doesn't support digits-only hashtags

It's in the specifications.

**Comment by Johann150** [comment]
Digits-only hashtags can be a problem because "#" is also used as number sign (see also how Github issues are mentioned). Could lead to a lot of hashtags being recognized which were not meant to be hashtags. And I don't think digits-only hashtags add much value.
