### ISSUE TITLE
Youtube previews don't work anymore - cookie notice problem

### ISSUE THREAD

**Issue by AlfredSK** [misskey-dev/misskey#7428]
## 💡 Summary

Well, not really a bug. It's a new annoyance Google has invented. Instead of showing the YouTube page of a video Google is redirecting the user to a full page with a lengthy explanation about cookies and so on. The user has to declare their consent by clicking a button to proceed to the actual YT video.

**Example URL:**
https://m.youtube.com/watch?v=JqJ6dgmbJrk

**Redirection page:**
https://consent.youtube.com/m?continue=https%3A%2F%2Fm.youtube.com%2Fwatch%3Fv%3DJqJ6dgmbJrk&gl=DE&m=1&pc=yt&uxe=23983172&hl=de&src=1

Maybe this only happens in the European Union but I'm not sure.

This annoyance unfortunately breaks the YT preview/player in Misskey too.

## 🙂 Expected Behavior

Show a preview of the video and the player to play the video.

## ☹️ Actual Behavior

A URL preview for the page https://consent.youtube.com is shown instead... "before you continue to YouTube...".

## 📝 Steps to Reproduce

1. Maybe you have to relocate your server to the EU ;-) (not sure)
2. Look at a note with a shared YT video
3. Look at the preview...

## Screenshot

![IMG_20210404_031021](https://user-images.githubusercontent.com/3656054/113495661-7375dd00-94f3-11eb-98ae-a4f66e8db4d0.png)

## 📌 Environment

Germany/European Union
Server in Finland
Client in Germany
Misskey v12.75.1
Node.js v14.16.0
PostgreSQL v12.6 (Ubuntu 12.6-0ubuntu0.20.04.1)
Redis v5.0.7

**Comment by foldedcascode** [comment]
the problem is in summaly. i have a fix here that uses the workaround of resetting cookies every time it fetches a url: https://github.com/foldedcascode/summaly/tree/fix-youtube-previews

(PR at https://github.com/syuilo/summaly/pull/143 )

**Comment by norz** [comment]
It seems to be working again now. 😊 
E.g.: https://misskey.de/notes/8ooqrl3rx6

(v12.86.0)

**Comment by AlfredSK** [comment]
Yep. I noticed that too. :-) I think I can close it.

Probably fixed by https://github.com/syuilo/summaly/pull/144
