### ISSUE TITLE
リアクションショートカットで高速反復入力すると無限増殖するバグ

### ISSUE THREAD

**Issue by KawaneRio** [misskey-dev/misskey#7431]
## 💡 基本概要
数字キーに当てられたリアクションショートカットを幾つか交互にｶﾀｶﾀｶﾀｶﾀーって入力するとリアクションを無限に増やすことが出来る。

## 🍮 豫測動作
過去にユーザーがしたそのノートへのリアクションは全て消され、代わりにユーザーが最後に打った一つのリアクションだけが登録されるハズ。

## 🍣 実際動作
一個前に打ったリアクションが消滅せず、リアクションが増殖する。それも無限に。#自己自演乙

## 📝 再現手順

0. 数字キーにリアクションショートカットを割り当てます（Misskeyではデフォルトで絵文字が10個入ってるのでこの手順は無視してよい）
1. バズらせたいノートを選択します
2. 増殖させたいリアクションを数字キーから打ち込みます。
3. 違う数字キーを押して、別のリアクションを打ち込みます。
4. ステップ`2.`と`3.`を交互に4msぐらいで入力します
5. **なんということでしょう。**

## 📌 動作環境
当バグは以下の**デスクトップ**ブラウザ環境で確認された。

- Mozilla Firefox 87.0 (64 bit) for Ubuntu; canonical - 1.0
- Flast Browser 82.0.5 (Beta, Electron: 9.0.0-beta.5, Chromium: 82.0.4048.0)

## 🖼 画像など
![](https://user-images.githubusercontent.com/61252570/113509233-6d353e80-958f-11eb-9422-491140316a40.png)
![](https://user-images.githubusercontent.com/61252570/113509229-69092100-958f-11eb-9fd8-1f74cebfdd7b.png)

**Comment by mei23** [comment]
んー
https://github.com/misskey-dev/misskey/commit/449ea4b669252cff3dee0de0192ce4a353106444

**Comment by mei23** [comment]
再現条件は同じリアクションを続けて送る
![image](https://user-images.githubusercontent.com/30769358/113509906-f732d680-9592-11eb-8486-dde6deb32d08.png)
