### ISSUE TITLE
レジストリへ値を読み書きするAiScript API

### ISSUE THREAD

**Issue by futchitwo** [misskey-dev/misskey#7443]
## Summary
クライアントが違ってもデータを共有できるようにする
システムの設定値を変更できないように、ドメインまたはスコープはAiScript専用のものを用意する

プログラムごとではなく、プログラムの作者ごとにスコープを分けるとプラグイン間やページ間でデータを共有できて面白いかも

**Comment by marihachi** [comment]
ユーザー毎のLocalStorage load/saveで良さそうな気がする

**Comment by syuilo** [comment]
> ユーザー毎のLocalStorage load/saveで良さそうな気がする

それだと

> クライアントが違ってもデータを共有できるようにする

ができない

**Comment by marihachi** [comment]
たしかに

**Comment by futchitwo** [comment]
Duplicate of #12209
