### ISSUE TITLE
URLを[]()で書くと表示されない

### ISSUE THREAD

**Issue by nenohi** [misskey-dev/misskey#7448]
## 💡 Summary

```
[misskey](https://misskey.io)
```
や
```
?[misskey](https://misskey.io)
```
が表示されていない

## 🙂 Expected Behavior
[misskey](https://misskey.io)
と表記される

## ☹️ Actual Behavior
何も表示されない
プレビューは表示されるみたい

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by syuilo** [comment]
https://github.com/misskey-dev/misskey/commit/7378c4a9d8c8c48a8ecf043d7a8e27b0d013f335
で直しました🙏
