### ISSUE TITLE
MFM search tag not available in certain languages.

### ISSUE THREAD

**Issue by noridev** [misskey-dev/misskey#7450]
## 💡 Summary

MFM search tag not available in certain languages.

## 🙂 Expected Behavior

It doesn't seem to work for languages other than Japanese and English.

## ☹️ Actual Behavior

![image](https://user-images.githubusercontent.com/11006910/115045560-951e8d80-9f11-11eb-8969-86c9ca0f9b69.png)
Korean

![image](https://user-images.githubusercontent.com/11006910/115045592-9e0f5f00-9f11-11eb-97f2-53a9e6eac503.png)
English

![image](https://user-images.githubusercontent.com/11006910/115045634-a798c700-9f11-11eb-8038-5566e8774746.png)
Japanese

## 📝 Steps to Reproduce

1. Go to (your instance link)/mfm-cheat-sheet
2. Scroll down and find the search box.
3. Try typing 検索(Search) in a language other than English.

## 📌 Environment

* Ubuntu 20.04 LTS
* nodejs 15.14.0
* misskey 12.76.1

**Comment by marihachi** [comment]
In the current specifications, MFM search syntax is not supported in languages other than English and Japanese.

**Comment by noridev** [comment]
> In the current specifications, MFM search syntax is not supported in languages other than English and Japanese.

It wasn't a bug. Thanks for the reply!
