### ISSUE TITLE
ノート詳細ページウィンドウからリアクションを押そうとするとリアクションピッカーが後ろに回ってしまい入力できない

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#7453]
## 📝 Steps to Reproduce

1. 
2.
3.

## 📌 Environment

Misskey 12.76.0 - 12.77.0

**Comment by syuilo** [comment]
いよいよzIndex管理システム実装しないといけなさそうだな

**Comment by tamaina** [comment]
リノートやノートメニューとかもこうなるようになってしまった

**Comment by kabo2468** [comment]
related to #7550

**Comment by syuilo** [comment]
直した
