### ISSUE TITLE
Add ability to mark single notification as read

### ISSUE THREAD

**Issue by animeavi** [misskey-dev/misskey#7457]
## Summary

Mastodon has the ability to clear a single notification with [/api/v1/notifications/:id/dismiss](https://docs.joinmastodon.org/methods/notifications/)
Pleroma can do the same (or multiple, if you wish) with [/api/v1/pleroma/notifications/read](https://docs-develop.pleroma.social/backend/development/API/pleroma_api/#apiv1pleromanotificationsread) or(?) [/api/v1/notifications/destroy_multiple](https://docs-develop.pleroma.social/backend/development/API/differences_in_mastoapi_responses/#delete-apiv1notificationsdestroy_multiple)

I feel like this is missing from Misskey, you can only mark every single notification as read or mark the ones you're returning from `/api/i/notifications` as read, you have no ability to mark a particular notification as read after doing some action to it (like a bot would).

**Comment by syuilo** [comment]
Thank you for your suggestion.
I will implement this.
