### ISSUE TITLE
モジュールインポートのタイミングで副作用のある処理をしない

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/misskey#7465]
## Summary
しない方が良いと思うんだけどどうかな

モジュールを使う側が、そのモジュールをインポートすることで何が起こるかを推測できなくて困る。
(ドキュメント化されていれば別)

## 関連
#3713

**Comment by syuilo** [comment]
現状そうなっている箇所の例ある？

**Comment by marihachi** [comment]
例: 
https://github.com/misskey-dev/misskey/blob/135ff280b9b555fb28ae4968979a9d6de2f99f77/src/config/index.ts 

importで"Configのロードが発生する"ということが予測できない。

**Comment by syuilo** [comment]
もしそれを関数にしてしまうと、全てのconfigを読む箇所で関数呼び出し発生することになりそう

**Comment by syuilo** [comment]
良い方法があれば副作用無しにしても良さそうだけど思いつかない

**Comment by syuilo** [comment]
おそらくモジュールインポートのタイミングで副作用のある処理をしているケースのほとんどは、例のような「プロセス全体で共有する必要がある値/インスタンス」を提供するためであると思う
んでそのようなケースでは、ほかに簡単な実装方法無いように思える
「値を保持するクラスを作り、そのインスタンスをexportする」のような実装にすれば回避できないこともないけど、やはり利用側でひと手間必要になる(プロパティアクセスまたはメソッド呼び出しが発生する)

**Comment by syuilo** [comment]
ちなみに一度importされると結果がキャッシュされるので、例のケースでは、「importで"Configのロードが発生する"」という副作用は一番最初にimportされた時だけ当てはまる

**Comment by syuilo** [comment]
まあそんな感じの事情のため、副作用を排するために複雑な実装にするよりは、最初の一回だけ副作用を許可し、後はその値を使い回すような実装にした方がシンプルじゃね、あと副作用と言ってもreadだけだし、みたいな感じかなあ
もちろん上記の事情に当てはまらないケースで副作用のある処理をしている箇所があればリファクタの余地はありそう(でも記憶する限りではそんなにないはず)

**Comment by syuilo** [comment]
データベースのコネクションとかも似たような実装だった気はする

**Comment by marihachi** [comment]
事情は把握できた
何かいい方法があればいいけど

**Comment by marihachi** [comment]
そもそもissueを立てたのはファイルの直下に処理が並んでるのが奇妙に思ったから、なんとかできればなと思って

**Comment by syuilo** [comment]
> 値を保持するクラスを作り、そのインスタンスをexportする」のような実装にすれば回避できないこともないけど

こんな感じ

``` ts
class ConfigManager {
	private config: FIXME;

	public load() {
		this.config = hogehoge;
	}

	public get(): ConfigManager['config'] {
		if (this.config) {
			return this.config;
		} else {
			throw new Error('config not loaded!');
		}
	}
}

export default new ConfigManager();
```

**Comment by marihachi** [comment]
モジュールのimport/exportを利用して状態を保持・受け渡ししようとしてるのが問題なのかも知れない
面倒かもしれないけど、データオブジェクトを引数でプロセス全体にまわした方が良い気がする

**Comment by syuilo** [comment]
> データオブジェクトを引数でプロセス全体にまわした方が良い気がする

これ理想だけど死ぬほど面倒そう

**Comment by rinsuki** [comment]
引数であちこちに引き回すのこれどこで初期化してるんだ？っていうのがめちゃくちゃわかりづらくなるのであんまり好きじゃない

**Comment by mei23** [comment]
> データベースのコネクションとかも似たような実装だった気はする

DBのmodelをimportしただけで接続が発動するので、toolsやtestでほとんどの関数を使うことが困難。
```
ConnectionNotFoundError: Connection "default" was not found.
    at new ConnectionNotFoundError (/home/runner/work/misskey-v12/misskey-v12/src/error/ConnectionNotFoundError.ts:8:9)
    at ConnectionManager.get (/home/runner/work/misskey-v12/misskey-v12/src/connection/ConnectionManager.ts:40:19)
    at Object.getRepository (/home/runner/work/misskey-v12/misskey-v12/src/index.ts:284:35)
    at Object.<anonymous> (/home/runner/work/misskey-v12/misskey-v12/src/models/index.ts:66:30)
```

`initDb()`した後に`require`するとかしかない。
