### ISSUE TITLE
Show/hide image button doesn't work anymore

### ISSUE THREAD

**Issue by AlfredSK** [misskey-dev/misskey#7467]
## 💡 Summary

The little button that triggers the show and hide (blur) function for images (e.g. when an image has a CW) doesn't work anymore. When I click on it nothing happens. I have cleared my cache and tried it with Firefox and Chromium. No luck. Button doesn't work.

## 🙂 Expected Behavior

When I click on the button the image should be hidden (blurred) or shown.

## ☹️ Actual Behavior

That little button has no function anymore. It's impossible to hide (blur) images.

## 💻 Screenshot

![show-hide-button](https://user-images.githubusercontent.com/3656054/115275755-81a63900-a142-11eb-8377-07ca5aa25d32.png)

## 📌 Environment

Firefox or Chromium
Misskey v12.77.1
Node.js v14.16.1
PostgreSQL v12.6 (Ubuntu 12.6-0ubuntu0.20.04.1)
Redis v5.0.7

**Comment by AlfredSK** [comment]
Could be fixed by #7509

**Comment by Candinya** [comment]
Fixed now in #7509 .

**Comment by AlfredSK** [comment]
Works again. 🎉 Thanks. Closing...
