### ISSUE TITLE
Don't include external scripts/styles - font awesome CSS is not included in Misskey's code

### ISSUE THREAD

**Issue by AlfredSK** [misskey-dev/misskey#7475]
## 💡 Summary

Misskey has switched to font awesome. That's fine. But please DON'T include it via a remote resource. Include every needed third party libraries/code in Misskey's code instead so it is loaded from the local instance/server instead of loading it from 'https://use.fontawesome.com'.

I found out about it because my local content security policy (CSP) blocks untrusted remote code/scripts. The icons in the top navigation bar and on other places are missing because of that.

Misskey v12.78.0 is now loading CSS from some remote URL. That's really a bad habit. Please change that.

## 🙂 Expected Behavior

Include all required libraries/scripts in Misskey's code. CSS/code/scripts should only be loaded from the local server/instance.

## ☹️ Actual Behavior

> Refused to load the stylesheet 'https://use.fontawesome.com/releases/v5.15.3/css/all.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline'". 

Icons don't load because of that.

![grafik](https://user-images.githubusercontent.com/3656054/115912518-b7635e80-a46f-11eb-8af9-10f3641e31cc.png)

## 📌 Environment

Misskey v12.78.0
Node.js v14.16.1
PostgreSQL 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1)
Redis 5.0.7

**Comment by kazukyakayashi** [comment]
I totally agree, please remove the external script call.

I also find it a very bad idea and it adds privacy problems. I'm not on the Fediverse (with Misskey) to be tracked by Google (and neither are my users).

**Comment by syuilo** [comment]
> remove the external script call

It's not script, it's style. Therefore, there is almost no possibility of malicious code being embedded.

We could use this style as an internal link, but it is expected that linking to external resources will be a normal occurrence as we develop in the future.

**Comment by lapineige** [comment]
> Therefore, there is almost no possibility of malicious code being embedded.

It's not even a matter of malicious code, it's a matter of not being tracked because your IP/UA is revealed to a third party that knows you're connecting to your misskey, when and from where - while that could be embedded directly with no privacy issue + lower network usage.

**Comment by kazukyakayashi** [comment]
> We could use this style as an internal link, but it is expected that linking to external resources will be a normal occurrence as we develop in the future.

Please don't do this... this is a very very bad idea and an extremely dirty practice ...

**Comment by okpierre** [comment]
I agree. It's the same thing with images hosted outside of misskey instance. Should be local folder instead.

reference to issue I opened: https://github.com/misskey-dev/misskey/issues/7043

**Comment by AlfredSK** [comment]
Also, Misskey seems to load SVGs (emojis) from `https://twemoji.maxcdn.com`. I just created a new user account and when I logged in the first time I saw a lot of requests to that CDN.
Same here. Please include all required and default assets in Misskey itself.

**Comment by syuilo** [comment]
> font awesome CSS is not included in Misskey's code

There is a licensing issue, so we cannot include external resources directly. We will (probably) need a implementation to download those resources at build time. (Contributions are welcome).

**Comment by mei23** [comment]
> There is a licensing issue

え、ほんとう？
https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself
https://fontawesome.com/license/free

**Comment by AlfredSK** [comment]
Yes. I think that's the best way to solve it - to pull external fonts/emoji/css sources as third party dependencies during the build process. Thanks for considering this.

**Comment by mei23** [comment]
@syuilo 添付しちゃいけないという記述は見つからないけど、それはPro版ではなくて？

**Comment by syuilo** [comment]
@mei23 あー、とくに根拠はないけどサードパーティなものをこのリポジトリに含めるとAGPLとして再配布になるから、それは一般的には禁止されてそうと思った

**Comment by acid-chicken** [comment]
> Font Awesome Free is free, open source, and GPL friendly. You can use it for
commercial projects, open source projects, or really almost whatever you want.
Full Font Awesome Free license: https://fontawesome.com/license/free.

だしやりようは十分あるように思う

**Comment by acid-chicken** [comment]
例えば [`npm:@fortawesome/fontawesome-free`](https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/) で依存として CSS をもらってきてバンドルに含めることは、ライセンスの表記さえあれば問題ないように読める。
