### ISSUE TITLE
MFMのアニメーション構文が機能していない？

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#7477]
## Summary
https://msk.seppuku.club/notes/8kz2zwiyi9

![image](https://user-images.githubusercontent.com/7973572/115953696-ec32ec80-a527-11eb-8177-64ba4c87e42b.png)

at Misskey 3286c93c8f67b65851e82c70e8a97f9af8ebee08

**Comment by tamaina** [comment]
（Featureにしちゃった  
（よく考えたらOrganization抜けたの自分だった

**Comment by marihachi** [comment]
mfm.js v0.16.2 で関数構文を無効化したのでその影響だと思う。
v0.16.3で一応復活させたのでMisskey側でそれが使われるようになれば直るはず
https://github.com/misskey-dev/mfm.js/releases/tag/v0.16.2 
https://github.com/misskey-dev/mfm.js/releases/tag/v0.16.3

**Comment by syuilo** [comment]
naotta
