### ISSUE TITLE
ファイルに対してのドライブのメニューが機能していない

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#7481]
## 💡 Summary

ファイルに対するドライブのメニューが機能しません

## 🙂 Expected Behavior

ファイルに対して操作できるメニューが表示される
![LSRYZENCapture2325](https://user-images.githubusercontent.com/28042693/115985997-3f20a880-a5e9-11eb-8773-98f807577fd6.png)

## ☹️ Actual Behavior

ファイルをクリックしても何も起きない/右クリックで通常のコンテキストメニューが開く
![afafdhsrh](https://user-images.githubusercontent.com/28042693/115985961-231d0700-a5e9-11eb-8937-f216fe9d113d.png)

## 📝 Steps to Reproduce

1. ドライブを開く
2. ドライブのファイルをクリックまたは右クリックする
3. Wow

## 📌 Environment

Misskey v12.78.0～

**Comment by SanMurakami** [comment]
```
app.12.79.1.js:2 ReferenceError: faICursor is not defined
    at Proxy.getMenu (7160.12.79.1.js:1)
    at Proxy.onContextmenu (7160.12.79.1.js:1)
    at 7160.12.79.1.js:1
    at app.12.79.1.js:2
    at l (app.12.79.1.js:2)
    at u (app.12.79.1.js:2)
    at HTMLDivElement.n (app.12.79.1.js:2)
```
