### ISSUE TITLE
Cannot follow mastodon/pleroma users: Public key not found for key...

### ISSUE THREAD

**Issue by nadiamoe** [misskey-dev/misskey#7487]
## 💡 Summary

I cannot follow users on remote Mastodon or Pleroma servers. Remote misskey servers do work.

From what I can tell, there seems to be an issue with remote servers not being able to fetch user's keys. I've set up an HTTP proxy and I got the following when sending a follow request to @Gargron@mastodon.social (sorry Eugen):

**Request**
```
POST https://mastodon.social/users/Gargron/inbox HTTP/1.1

User-Agent: Misskey/12.79.1 (https://mk.roobre.es)
Content-Type: application/activity+json
Digest: SHA-256=tv5cKcXxt9Cdmlq2vRNjdQMTX2IfTG0zvjB5aKt6XPk=
Host: mastodon.social
Date: Mon, 26 Apr 2021 19:06:46 GMT
Signature: keyId="https://mk.roobre.es/users/8l0n2xtprl#main-key",algorithm="rsa-sha256",headers="(request-target)  date host  digest",signature="DplaWEPrjYVcItqqh4T8BgswXdmWfZ+WDcltodikTu7dOAD6a6Zb1hQ2VXo8g6ytyMNICgx+bjH3Cd8S/g5iYY5mU1EWUroafxZ+S5WkaChtNXF897ZV70nP1t48hQzgwLmWfQv9i9lRiLrz8PJoRKLeTHSDbZ/7Yzh9ZL1yCQCGDfX6/onlmyZ1B/43ATzVOR7/uT7gdPQJlrXvtGM65Qe+Gy07gkNCvzWIGdk1dsWHCKakXva64BuyxDB/HWraxEmpfxWMDzNaKDVLJOSqv/gm5/8ouTTkrR/B76mh4chVtMWuNc3jYk5I10wY2rgBmxceeQq8nIOWERA/9PGo8nUxRCu+LqLPK1F0h4gse0MGlnIIrfFxrUChaDzVNMoJ+yp8aqugTsYXttieWsnJFvoW+LhzB9sxr/7EUKHJGPNrrBE/ikQnb9xIOfrwQ6bH6pkVNvhgD1tWw34PG0iW7lu+1OacEV4WfBFeVyElicUrLxWAtA8uOysCNT1k/r5XtoA8Tv1YIi3sju9HOLD77VX/kP2zhBZMzNfywxfrr023W0VTZ/FRjYNzlvoeGj764T6TqVzdSzZiLb+nqq9CXUb1NcAyaIBYPZM4ygaVMP/I3M43FYifS3KcCZf+fBhujy1Us8qzy9Fwc+o4HEUPEFkwSN3E0+/h14WEV6pbTIg="
Connection: close
Content-Length: 263

{"@context":["https://www.w3.org/ns/activitystreams","https://w3id.org/security/v1"],"type":"Follow","actor":"https://mk.roobre.es/users/8l0n2xtprl","object":"https://mastodon.social/users/Gargron","id":"https://mk.roobre.es/77921cc1-1844-4244-aac7-8fa20e502b04"}
```

**Response**
```
HTTP/1.1 401 Unauthorized

Date: Mon, 26 Apr 2021 19:06:46 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Server: Mastodon
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Permissions-Policy: interest-cohort=()
Vary: Accept-Encoding
Cache-Control: no-cache
X-Request-Id: c2df7370-f5a5-4a0f-ab78-75730c662637
X-Runtime: 0.262555
Strict-Transport-Security: max-age=63072000; includeSubDomains

Public key not found for key https://mk.roobre.es/users/8l0n2xtprl#main-key
```

If I navigate to the Misskey UI, I can see my public key there: 
![DeepinScreenshot_select-area_20210426212131](https://user-images.githubusercontent.com/969721/116138673-6654a400-a6d5-11eb-88c2-43350ab4a691.png)

Pleroma is not working either (returns 400 and response body just says `error`).

## 🙂 Expected Behavior

Mastodon and pleroma should be able to find my public key on misskey.

## ☹️ Actual Behavior

Mastodon and pleroma do not seem to be able to find my public key on misskey.

## 📝 Steps to Reproduce

1. Bring up a misskey instance
2. Try to follow @Gargron@mastodon.social

## 📌 Environment

Docker: `misskey/misskey:12.79.1`

Using nginx reverse proxy (Kubernetes ingress controller)

---

Similar-to: https://github.com/misskey-dev/misskey/issues/5715 perhaps?

**Comment by roobre** [comment]
Not sure if it's related, but I seem to be able to find my public key under `https://mk.roobre.es/users/8l0n2xtprl/publickey` (as opposed to `https://mk.roobre.es/users/8l0n2xtprl#main-key`, as reported in `Signature: keyId="https://mk.roobre.es/users/8l0n2xtprl#main-key",algorithm=[...]`

**Comment by mei23** [comment]
One of the `roobre.es` DNS servers cannot resolve `mk.roobre.es`.

```
roobre.es.              86400   IN      NS      ns1.roobre.es.
roobre.es.              86400   IN      NS      ns2.afraid.org. ★
```
```
mk.roobre.es on ns1.roobre.es => NOERROR
mk.roobre.es on ns2.afraid.org => NXDOMAIN ★
```
Therefore, it seems that a communication error sometimes occurs.

**Comment by nadiamoe** [comment]
Hi,
Thanks for the quick response! 

I just thought about this like 20 minutes ago and removed the faulty one. I'll recheck tomorrow after the records propagate, but seems like the root cause to me as well.

Likely mastodon/pleroma failing but misskey succeding was just luck.

Additionally, I've carefully inspected mastodon's code and found zero discrepancies between how it returns data w.r.t. my instance so… I gues it was dns. Again.

Many thanks for the help!

EDIT: After some time I'm still facing the same issue, with other instances I never tried to interact with before (so there shouldn't have a cache). I'll try again after some more time, although [this tool](https://dnschecker.org/#NS/roobre.es) seems to hint that propagation has already taken place. TTL for my DNS should be 10 minutes so that shouldn't be cached either.

**Comment by nadiamoe** [comment]
Hey, quick update, this is now fixed. My reverse proxy was only allowing TLS 1.3 with a select list of ciphers:
```
ssl-protocols:         "TLSv1.3"
ssl-ciphers:           "EECDH+AESGCM:EDH+AESGCM"
```
Apparently some instances do not support this combination. Switching to the nginx defaults (which include TLSv1.2 and some other ciphers I haven't checked) fixed the issue 🎉
