### ISSUE TITLE
MentionsとDirect Noteタブが表示されない

### ISSUE THREAD

**Issue by numaaqours** [misskey-dev/misskey#7490]
## 💡 Summary
MentionsとDirect Noteが表示されない

## ☹️ Actual Behavior
![CA1C3D55-D1B1-45BE-8ADE-EE8B2653A2AB](https://user-images.githubusercontent.com/71965043/116684335-d15eed00-a9eb-11eb-9d00-f397f2eae50c.png)
![6774AA2D-44A4-48A9-856D-BE7D429CB47E](https://user-images.githubusercontent.com/71965043/116684344-d328b080-a9eb-11eb-8be4-8a02f013e04b.png)

## 📝 Steps to Reproduce
クライアント上のMentions、Direct Noteの項目を選択し、画面遷移させる。

## 📌 Environment
12.79.3

**Comment by syuilo** [comment]
fixed
