### ISSUE TITLE
Social media login broken (again)

### ISSUE THREAD

**Issue by wiredsis** [misskey-dev/misskey#7497]
## 💡 Summary

I'm having the same issue as #3343. Basically I added some social media integration into my instance and whenever I want to log in with the integrations i've linked, it doesn't work.

## 🙂 Expected Behavior

User should be logged in into their account when clicking "Login in with Twitter/Discord/GitHub"

## ☹️ Actual Behavior

The server log reports `Error: Cannot send secure cookie over unencrypted connection` and the user sees "Internal Server Error"

## 📝 Steps to Reproduce

1. Go to instance settings
2. Add any social network under "Integrations"
3. Try to link an account to a social network
4. Try to log in to the account

## 📌 Environment

Ubuntu 20.04.2
Yarn 1.22.5
PostgreSQL 12.6
Redis 5.0.7-2
Misskey 12.80.1

**Comment by wiredsis** [comment]
Hey, can I get some help in this? Haven't figured out how to solve it yet

**Comment by rinsuki** [comment]
are you using nginx or Apache or other reverse proxies?

**Comment by wiredsis** [comment]
I'm using nginx as my proxy, yes.

**Comment by rinsuki** [comment]
OK, then you should add `proxy_set_header X-Forwarded-Proto $scheme;` to before of `proxy_pass ...`

**Comment by wiredsis** [comment]
Ok thank you! It worked!
