### ISSUE TITLE
Reacting to note using shortcuts bypass constraints check

### ISSUE THREAD

**Issue by chocological00** [misskey-dev/misskey#7503]
## 💡 Summary
When adding reactions to note using keyboard shortcuts (number keys), it is possible to violate constraints check of the backend and add more than one reactions at once.

## 🙂 Expected Behavior
One user should only be able to leave single reaction per note.

## ☹️ Actual Behavior

![image](https://user-images.githubusercontent.com/36347199/117194920-af31ea00-adb2-11eb-9b03-123fd16efa40.png)

(Can be seen [here](https://madost.one/notes/8lf6tmjwln))

Doing this to someone else's note also makes that person get "locked out" from the UI (shown below)
https://user-images.githubusercontent.com/36347199/117194341-ff5c7c80-adb1-11eb-8ca1-4b81301d7a44.mp4

## 📝 Steps to Reproduce

1. Select (highlight) the target note with mouse click on PC
2. Press 1 and 2 simultaneously
3. You can bypass the reaction constraints and leave more than one reacts to the note.

## Notes
`/src/services/note/reaction/create.ts` line 41 seems to be missing delete and re-insert to `note_reaction` table.

## 📌 Environment
Misskey 12.80.3

**Comment by acid-chicken** [comment]
Related to #7431
