### ISSUE TITLE
既にリアクションしているノートに再度リアクションできてしまう

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/misskey#7507]
## 💡 Summary
既にリアクションしているノートを再度リアクションすると受理されてしまう

クライアント:
リアクションしているノートは右クリックでもリアクションピッカーが開かないことが望ましい (or 新しいリアクションで置き換わることを期待する)

API:
普通はAPIで弾かれるべきだけど、この辺の変更で判定がうまくできなくなったのかも
https://github.com/misskey-dev/misskey/commit/449ea4b669252cff3dee0de0192ce4a353106444 

## 📝 Steps to Reproduce

1. リアクションする
2. ノートを右クリックして再度リアクション
3. 受理されて状態がバグる

## 📌 Environment
v12.80.3

**Comment by syuilo** [comment]
同じ？
https://github.com/misskey-dev/misskey/issues/7431
https://github.com/misskey-dev/misskey/issues/7503

**Comment by mei23** [comment]
https://github.com/misskey-dev/misskey/pull/7432 で大丈夫はなず (なぜか閉じてるけど)
