### ISSUE TITLE
Note作成でクエリエラーなどが発生すると返ってこない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#7508]
## 💡 Summary
Note作成
https://github.com/misskey-dev/misskey/blob/591a5c277cdf197f043e5b24743dbdb346e65c4f/src/services/note/create.ts#L115
は
```
=> new Promise<Note>(async (res, rej) => { 
```
だけど

DBクエリなどの明示的にcatchしてrejectしてないものがあり
それらでエラーが発生すると返ってこずに結果的にAPI等が応答なしになったりする。

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by zyoshoka** [comment]
今はちゃんと catch されているはずなのでクローズします
https://github.com/misskey-dev/misskey/blob/92367cf70065dca5e33ece2266f0318c3b682d1a/packages/backend/src/server/api/ApiCallService.ts#L421-L422
