### ISSUE TITLE
MFMのrotateを復活させてほしい

### ISSUE THREAD

**Issue by marihachi** [misskey-dev/misskey#7512]

**Comment by mei23** [comment]
過去にrotate構文が存在したことはなさそうに見える。
forkではないかと。

**Comment by marihachi** [comment]
forkだっけ
あれ表現力が上がって楽しい

**Comment by EbiseLutica** [comment]
他の実装でも作られうるので定かではありませんが、指定した角度で傾けて表示するrotate構文なら、Groundpolis拡張にありますね

**Comment by marihachi** [comment]
Resolved
