### ISSUE TITLE
Emoji selector in PWA is not usable anymore

### ISSUE THREAD

**Issue by kazukyakayashi** [misskey-dev/misskey#7513]
## 💡 Summary

The emoji selector in PWA is not usable anymore, indeed when we want to add an emoji the selector remains in background and it is impossible to add an emoji

## 🙂 Expected Behavior

The emoji selector is in the foreground and we can use it.

## ☹️ Actual Behavior

The emoji selector stays in the background behind the message window and it is impossible to use the emoji selector.

https://user-images.githubusercontent.com/39823221/117928513-f57bd180-b2fb-11eb-8bab-3c324fbd1732.mp4

## 📌 Environment

Misskey v12.81.0
Tested on **Bromite** and **Firefox/Fennec**

**Comment by kazukyakayashi** [comment]
Hmm I have the same problem on my PC with Firefox when I try to reply to a message.

**Comment by nullobsi** [comment]
I confirm this on Firefox desktop and mobile

**Comment by syuilo** [comment]
Fixed by https://github.com/misskey-dev/misskey/commit/be7e389bb5d9b1028013c8e466e31fd2010228cf and https://github.com/misskey-dev/misskey/commit/d7522757302ff2a9378a86bedfbe3285c07a730a
