### ISSUE TITLE
背景画像設定がコントロールパネルにない

### ISSUE THREAD

**Issue by Minemu398** [misskey-dev/misskey#7514]
## 💡 Summary

v12.80.3で発生
バナー画像の設定で、画像のURLを貼ってもバナーとして表示されませんでした。
CDNなどの影響なのか確認しましたが、違うみたいです。
![スクリーンショット 2021-05-16 18 40 42](https://user-images.githubusercontent.com/44996819/118398275-d5009e00-b692-11eb-8932-d530a853a08d.png)

## 📌 Environment

v12.80.3

**Comment by remitocat** [comment]
補足：デベロッパーツールで確認したところ、`background-image` の値が変更前の画像のURLになっていました。
Discord等のプレビューカードには変更後の画像が問題なく反映されていました。

**Comment by syuilo** [comment]
そこに表示されるのはバナー画像ではなく、インスタンス設定で背景画像設定がないことが原因ですね

**Comment by tamaina** [comment]
Fixed
