### ISSUE TITLE
絵文字ピッカーが後ろに隠れてしまう

### ISSUE THREAD

**Issue by Minemu398** [misskey-dev/misskey#7515]
## 💡 Summary
v12.81.0で発生しました
Nキーで投稿フォームを表示し、そこで絵文字を使おうとすると絵文字ピッカーが後ろに隠れてしまいました。
![2021-05-15 08-36-44 1](https://user-images.githubusercontent.com/44996819/118398622-6a506200-b694-11eb-8095-faab2b0d17ea.png)

## 📌 Environment
v12.81.0

**Comment by syuilo** [comment]
ありがとうございます。こちらdevelopブランチでは直ってます。リリースまでお待ちください🙏

**Comment by Minemu398** [comment]
ありがとうございます！
