### ISSUE TITLE
MisskeyからobjectがnullのUndoが飛んでくる

### ISSUE THREAD

**Issue by noellabo** [misskey-dev/misskey#7516]
## 💡 Summary

MisskeyからobjectがnullのUndoが飛んでくる

## 🙂 Expected Behavior

Undo Activityのobjectには過去のActivityのIDか、Activity自体がセットされている

## ☹️ Actual Behavior

Undo Activityのobjectがnullで送られてくる

## 📝 Steps to Reproduce

fedibird.com および nightly.fedibird.com に、下記のMisskeyからどきどき送られてきています。

```
{
    "@context": [
        "https: //www.w3.org/ns/activitystreams",
        "https://w3id.org/security/v1"
    ],
    "type": "Undo",
    "actor": "https://misskey.io/users/xxxxxxxx",
    "object": null,
    "id": "https://misskey.io/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}
```

misskey.io, misskey.nokotaro.work, m.anirloli.dev, nekomimi.yokohama から同一のパターンの受信を確認しています。

**Comment by AlfredSK** [comment]
Hint: I don't know if this is related to the issue but at Friendica we had an issue with the `context` as well.

The problem was that the URL `https://w3id.org/security/v1` doesn't resolve anymore. It is throwing a 404 error.

**Comment by mei23** [comment]
> The problem was that the URL https://w3id.org/security/v1 doesn't resolve anymore. It is throwing a 404 error.

Thank you for the information.
However, the `@context` issue doesn't seem to matter.
However, I think the inability to resolve `w3id.org/security/v1` is a serious problem for ActivityPub.

**Comment by AlfredSK** [comment]
Sidenote: The W3C restored the file, so everything should be fine with that URL.
