### ISSUE TITLE
Margin and element size Problem in Pope ui

### ISSUE THREAD

**Issue by kazukyakayashi** [misskey-dev/misskey#7523]
## 💡 Summary / ☹️ Actual Behavior

There are some problems on the Pope interface, especially on the search where instead of having a fixed and centered column it stretches over the whole space and there are missing margins on the left, same thing when you display a discussion with a person.

![BIIapkzvyh](https://user-images.githubusercontent.com/39823221/118609915-88fd4880-b7bb-11eb-900a-dc33fac0d07b.png)

![firefox_RuXtKUzCfZ](https://user-images.githubusercontent.com/39823221/118609958-9286b080-b7bb-11eb-9a8e-7813fbbb6480.png)

There are also other problems in some parts of the administration of the instance where there are missing margins or overlapping elements.

![firefox_n8sXVa915u](https://user-images.githubusercontent.com/39823221/118610046-aa5e3480-b7bb-11eb-8706-038c08828f40.png)

![firefox_bh2WuGl52B](https://user-images.githubusercontent.com/39823221/118610072-b0541580-b7bb-11eb-85af-66a00d419cfa.png)

## 📌 Environment

Misskey 12.81.0

**Comment by futchitwo** [comment]
Duplicate with #7449 ？

**Comment by kazukyakayashi** [comment]
Done 👌
