### ISSUE TITLE
サイレンスを即時反映させたい

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#7525]
## 💡 Summary
サイレンスをしてもLTLやSTL等に表示される

## 🙂 Expected Behavior
フォローしているユーザーのみに表示される

## ☹️ Actual Behavior
全ユーザーに表示される

## 📝 Steps to Reproduce

1.ユーザーをサイレンスする
2. 投稿する
3.

## 📌 Environment
Misskey.io v12.80.3

**Comment by syuilo** [comment]
現状の実装だと、パフォーマンス上の理由で内部的にユーザー情報を最大一時間キャッシュするようになっているから、サイレンスの状態も反映されるまで最大1時間かかる
サイレンス状態が変わったらキャッシュも更新するような実装で良いかもしれない

**Comment by SanMurakami** [comment]
仕様ならCloseする？

**Comment by syuilo** [comment]
タイトル変えた

**Comment by mei23** [comment]
~~「効いてない」でも「キャッシュのせいで即時反映されない（だけ？）」でもなくて
サイレンスの仕様は「そのユーザーの新規投稿を強制Homeにする」でしかないので
ユーザーの過去投稿に対しては一切影響ないのが今の仕様。~~

やっぱり、authenticateのユーザーキャッシュの影響がメインかも

**Comment by mei23** [comment]
凍結、アカウント削除、トークン更新 しても最大1時間残ってるのは結構まずい気が…
もともと対して重いクエリでもないのでキャッシュ1分とか10秒でいいかも。

**Comment by syuilo** [comment]
キャッシュなくていいかも
