### ISSUE TITLE
Can't process ActivityStreams objects where the type is an array

### ISSUE THREAD

**Issue by Minoru** [misskey-dev/misskey#7535]
## 💡 Summary

[ActivityStreams spec says that `type` may have multiple values](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-type), i.e. it can be an array. However, I discovered that Misskey ignores documents where `type` is an array.

## 🙂 Expected Behavior

Misskey should look through the array of types, pick the most specific one that it supports, and process the document as if it was of that type. For example, if the document has `"type": ["Note", "http://purl.org/goodrelations/v1#Location"]`, and Misskey only supports `Note`, it should process the document as if it said `"type": "Note"`.

## ☹️ Actual Behavior

Misskey ignores documents where the `type` field is an array.

## 📝 Steps to Reproduce

1. Suppose you have an ActivityPub actor somewhere (I just wrote a bunch of static files and put them onto a new sub-domain of my site, aptest.debiania.in.ua);
2. Make this actor post the following activity at https://aptest.debiania.in.ua/notes/2:

    ```json
    {
      "id": "https://aptest.debiania.in.ua/notes/2",
      "type": ["Note", "gr:Location"],
      "published": "2021-05-23T09:06:18.141413+00:00",
      "attributedTo": "https://aptest.debiania.in.ua/actor",
      "content": "Hello, multi-typed world!",
      "to": [
        "https://www.w3.org/ns/activitystreams#Public"
      ],
      "cc": [],
      "inReplyTo": "",
      "summary": "",
      "tag": [],
      "sensitive": false,
      "gr:category": "restaurants/french_restaurants",
      "@context": [
          "https://www.w3.org/ns/activitystreams",
          {
              "gr": "http://purl.org/goodrelations/v1#"
          }
      ]
    }
    ```

    (This is a variation of [an example from the AS-Core spec](https://www.w3.org/TR/activitystreams-core/#fig-an-object-that-is-both-a-place-and-a-gr-location).)
3. Type https://aptest.debiania.in.ua/notes/2 into the search box in Misskey. Observe the logs of your server — you'll notice that Misskey fetches the document, but its UI never shows the post.
4. Optional: try searching for https://aptest.debiania.in.ua/notes/1 This is a simpler document with `"type": "Note"`. It is fetched and displayed just fine, proving that the issue is not with my webserver setup or anything like that.

## 📌 Environment

Here's all the files for my actor: [www.tar.gz](https://github.com/misskey-dev/misskey/files/6531813/www.tar.gz) I simply dropped them into a directory that I served with Nginx. Nginx was configured to set the correct `Content-Type` header on these files:

```
location /notes {
    default_type application/activity+json;
}

location /actor {
    default_type application/activity+json;
}

location /.well-known/webfinger {
    default_type application/jrd+json;
}
```

**Comment by mei23** [comment]
Related https://github.com/misskey-dev/misskey/issues/4633

**Comment by mei23** [comment]
It's not directly related, but the JSON in the `https://aptest.debiania.in.ua/actor` seems to be invalid. 

```
SyntaxError: JSON.parse: expected double-quoted property name at line 89 column 1 of the JSON data
```
```
  "endpoints": {
    "sharedInbox": "https://aptest.debiania.in.ua/inbox"
  }, <=
}
```

**Comment by Minoru** [comment]
Ah, sorry about the malformed JSON! I kept changing it, and probably didn't notice that it's broken because all the servers cached the response already. It's fixed now.

And I see you already submitted a PR fixing this, thanks for that too!
