### ISSUE TITLE
koaやめる

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#7537]
## Summary

TypeScriptネイティブではないので、[型定義上の問題](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36161)が起きやすく不便

**Comment by syuilo** [comment]
良い代替のフレームワークなさそう

**Comment by tamaina** [comment]
@mei23 がまえにkoaやめる話をしてた気がする

**Comment by mei23** [comment]
前Fastify使おうとしていた
https://github.com/mei23/misskey/pull/2285

**Comment by rinsuki** [comment]
これとかどうだろう https://github.com/talentlessguy/tinyhttp

**Comment by syuilo** [comment]
tinyhttpにしてみるか

**Comment by syuilo** [comment]
やたら「express互換だよ！express replacementだよ！」ってアピールされているのがちょっと気になる
別にexpressにこだわり無いから…

**Comment by syuilo** [comment]
> tinyhttpこの間使ったけどなんかバグ踏んで散々な目にあった
>  https://github.com/tinyhttp/tinyhttp/issues/279
> @rinsuki

> Fastifyバグっぽいのはあったことないけど、TypeScriptネイティブじゃないからTypeScriptでどう書くの～って悩む所はちょこちょこあったのだわ。
> @mei23@misskey.m544.net

**Comment by mei23** [comment]
> tinyhttp/tinyhttp#279

そういえばkoa-routerも同ルートで変なとこあった気がした
https://github.com/misskey-dev/misskey/issues/6533

**Comment by sousuke0422** [comment]
tinyhttpはv2で完全なESMに移行したらしい
https://github.com/tinyhttp/tinyhttp/releases/tag/%40tinyhttp%2Fapp%402.0.0

**Comment by syuilo** [comment]
なんでHTTPフレームワークでデータベースの話が出てくるんだろう
https://github.com/fastify/fastify/issues/3005

**Comment by syuilo** [comment]
fastifyの型が完全じゃないことがあるというのは明記されてた
> As the team works on improving framework and type definition synergy, sometimes parts of the API will not be typed or may be typed incorrectly

**Comment by syuilo** [comment]
でもfastifyの方がメジャーではあるんだよな

**Comment by mei23** [comment]
tinyhttpのサイトって重かったり落ちてたりするからなんだか

**Comment by mei23** [comment]
express/koa/tinyhttpあたりのexpress系にある`next()`を呼ぶというのがわかりづらくて嫌いなので、その概念がないFastifyの方が好き。

**Comment by syuilo** [comment]
Fastifyでやってみるか

**Comment by syuilo** [comment]
型で困らないことを祈る

**Comment by rinsuki** [comment]
fastify なんかバリデーションとかまで入ってて壮大で、そうじゃないんだよな…感あった (いまさら)

**Comment by syuilo** [comment]
それは思った
ちょっと機能が多すぎな感じはある

**Comment by syuilo** [comment]
バックエンド全体の話になるけどNest.jsとか導入するのはどうだろうと思ってた
んだけど、試した感じ
- 事実上express使うことを余儀なくされる
- Nest.jsがそこら辺(express)を抽象化してくれる訳でもないため、express由来の型エラーに悩まされることも多かった
- REST APIを想定していて、Misskeyには合わなそう
- エラーが握りつぶされることがあり、デバッグに手間取った
- ドキュメントの情報量が多くて学習コストがかなり高い
- これはNest.jsというよりデザインパターンの話だけど、「ノートをお気に入り登録するのはNoteServiceに書くのか？FavoriteServiceに書くのか？」みたいな悩みが発生しがち

だから微妙な感じした
使いこなせれば今の状態より見通し良くなるかもしれないけど…

**Comment by syuilo** [comment]
fastifyに移行するのも結構大変かも

**Comment by mei23** [comment]
そう？

**Comment by syuilo** [comment]
コード量というよりは対応する機能を探すのが大変そうと思った

**Comment by mei23** [comment]
参考
https://github.com/mei23/misskey/pull/2285/files

fastifyStatic => koa_send みたいなの
pointOfView: view(pug) あたり
基本headerは先にsetする
next()で流れ落ちみたいな概念はないので、/users/:id みたいな APとWebでAccpetで出し分ける場所は1つのroute内で分岐になる？

**Comment by syuilo** [comment]
app.proxy が https://www.fastify.io/docs/latest/Server/#trustproxy か

**Comment by syuilo** [comment]
> 参考
https://github.com/mei23/misskey/pull/2285/files

any にキャストしている箇所が所々あるけど、やっぱり型エラーとか出るのかしら

**Comment by mei23** [comment]
> app.proxy が https://www.fastify.io/docs/latest/Server/#trustproxy か

たぶんそうだわ。たしかkoaだとtrue相当しかなかったけど、本当はどのIPアドレスを信頼するか指定できるべきだわね。

**Comment by mei23** [comment]
> any にキャストしている箇所が所々あるけど、やっぱり型エラーとか出るのかしら

あからさまに型がおかしいところはほとんどなかった気がするのだわ。


> `(req as any).file`

わすれた

> `(server as any).getDefaultJsonParser`

たぶんdtsの漏れ、マイナーなところだからかも。

> `request.body as any`

bodyのdefaultはunknownで、ちゃんとそれを確定させる手段はあるはず。

**Comment by syuilo** [comment]
再チャレンジするか

**Comment by tamaina** [comment]
graphql対応も一緒にやろうぜ(などと

**Comment by syuilo** [comment]
Fastify v4がそろそろ出そうだからそれまで待つか
https://github.com/fastify/fastify/issues/3482

**Comment by syuilo** [comment]
リリースされた
https://github.com/fastify/fastify/releases/tag/v4.0.0

**Comment by syuilo** [comment]
そろそろやりたい

**Comment by syuilo** [comment]
やるわよ

**Comment by syuilo** [comment]
やっぱりfastify(Misskeyにとっては)要らない機能が多くてドキュメント見にくい

**Comment by syuilo** [comment]
うーーーーーむ

**Comment by syuilo** [comment]
なんか自作した方が良さそう

**Comment by syuilo** [comment]
https://github.com/unjs/h3 もあるっぽい

**Comment by syuilo** [comment]
今まで見てきた中で一番機能的に最小限そうで、TypeScriptで書かれてるし良いかもしれない

**Comment by syuilo** [comment]
> やっぱりfastify(Misskeyにとっては)要らない機能が多くてドキュメント見にくい

あと一部のドキュメントがcommonjs

**Comment by syuilo** [comment]
``` ts
ctx.response.vary('Accept');
```
はどうしたらいいかね
varyライブラリ直接使う？

**Comment by syuilo** [comment]
> next()で流れ落ちみたいな概念はないので、/users/:id みたいな APとWebでAccpetで出し分ける場所は1つのroute内で分岐になる？

ガード的な機能も無さそうだからそうなりそうでめんどい
これそもそもAPとWebでURL分けることは出来ないんだっけ

**Comment by syuilo** [comment]
tasukete

**Comment by acid-chicken** [comment]
URL 分けるというか、今 AP コンテキストか否かを [constraints](https://www.fastify.io/docs/latest/Reference/Routes/#constraints) かなんかでルートの設定に条件として渡せばなとかなりそう。

**Comment by syuilo** [comment]
> URL 分けるというか、今 AP コンテキストか否かを [constraints](https://www.fastify.io/docs/latest/Reference/Routes/#constraints) かなんかでルートの設定に条件として渡せばなとかなりそう。

いけそう
https://github.com/delvedor/find-my-way#custom-constraint-strategies

ただ同じパスで二種類のコンテンツを出し分けるというのは分かりにくいからできれば止めたいと思った

**Comment by acid-chicken** [comment]
> いけそう
https://github.com/delvedor/find-my-way#custom-constraint-strategies

こういうノリかな

```ts
import Fastify from 'fastify';

const fastify = Fastify({
  ..._,
  constraints: {
    aCoolIdentifierGoesHere: {
      storage() {
        const store = {};
        return {
          get(key) {
            return store[key] || null;
          },
          set(key, value) {
            store[key] = value;
          },
        },
      },
      deriveVersion(req, ctx) {
        return isActivityPubReq(req) ? 'ap' : 'html'
      },
    },
  },
})

// ...

fastify.get<{ Params: { note: string; } }>('/notes/:note', { constraints: { aCoolIdentifierGoesHere: 'ap' } }, async (request, reply) => {
  // handler for activity pub here
})
```

> ただ同じパスで二種類のコンテンツを出し分けるというのは分かりにくいからできれば止めたいと思った

非 AP 側の URL を貼り替えないと AP 上で既存のアクティビティに対して破壊的変更になりそう

**Comment by syuilo** [comment]
謎の型エラーが出る
![image](https://user-images.githubusercontent.com/4439005/192717379-43f3f209-8134-45ef-8598-0a1901315d8b.png)

あと必ずルートで宣言しなければならないというのはFastifyの掲げるカプセル化の思想と逆行するわね(プラグイン内で定義で来てほしい)

**Comment by syuilo** [comment]
> あと必ずルートで宣言しなければならないというのはFastifyの掲げるカプセル化の思想と逆行するわね(プラグイン内で定義で来てほしい)

👀 
https://github.com/fastify/fastify/issues/3615

**Comment by syuilo** [comment]
よくわからない

**Comment by syuilo** [comment]
> > あと必ずルートで宣言しなければならないというのはFastifyの掲げるカプセル化の思想と逆行するわね(プラグイン内で定義で来てほしい)
> 
> 👀 [fastify/fastify#3615](https://github.com/fastify/fastify/issues/3615)

ちょっと違う話っぽい(プラグイン全体に制約を「適用」したいという話で、プラグイン内に制約を「定義」したい話ではなさそう)

**Comment by acid-chicken** [comment]
`fastify.addConstraintStrategy` でいけそう

**Comment by syuilo** [comment]
> `fastify.addConstraintStrategy` でいけそう

ちょうど見てた
thx

**Comment by syuilo** [comment]
でもやっぱり
```
Property 'validate' is missing in type '{ name: string; ...
```
エラーが出る

**Comment by syuilo** [comment]
validate なんてプロパティドキュメントのどこにもないんだけど

**Comment by syuilo** [comment]
げっ、しかも deriveConstraint の req って IncomingMessage じゃん
そうすると`@fastify/accepts`とかが使えない...

**Comment by syuilo** [comment]
tasukete

**Comment by acid-chicken** [comment]
> validate なんてプロパティドキュメントのどこにもないんだけど

これはなんか[型の書き間違え](https://github.com/delvedor/find-my-way/blob/b7cdb2e62ecc4af182f663abfc3bdd59014410ff/lib/constrainer.js#L87-L89)っぽそう

> げっ、しかも deriveConstraint の req って IncomingMessage じゃん そうすると`@fastify/accepts`とかが使えない...

まあ [`@fastify/accepts` は `accepts` のラッパっぽい](https://github.com/fastify/fastify-accepts/blob/459130c266a33ec3d362c5572773a0b5d048aacc/index.js#L3)し直接呼べばよさそう

**Comment by syuilo** [comment]
ドキュメントでは deriveConstraint ってなってたり deriveVersions ってなってたり型定義では validate ってなってたりどれが正解なんだ

**Comment by syuilo** [comment]
ヌァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァンンンンオオオオンンオンオンオンオンンンンンンンンン゛ン゛！！！！！！！！！！！！！！！！

**Comment by syuilo** [comment]
nani
![image](https://user-images.githubusercontent.com/4439005/195731023-e11cfcc7-3bf3-4e30-94fb-297b7a45dc05.png)

**Comment by syuilo** [comment]
どんなURLにしてもnot foundになるんだけど

**Comment by syuilo** [comment]
tasukete

**Comment by syuilo** [comment]
あとこれが出る
![image](https://user-images.githubusercontent.com/4439005/195732845-3c17a6d6-b355-4f32-ba35-0f8a71b31a05.png)

**Comment by syuilo** [comment]
preParsingフックなんて使ってないのになぜpreParsing処理を呼ぼうとしてるんだ

**Comment by syuilo** [comment]
これだけ単純化しても同じエラー出る
```ts
const fastify = Fastify({});

fastify.get('/hello', async (request, reply) => {
	return 'world!';
});

fastify.server.listen(this.config.port);
```

**Comment by syuilo** [comment]
```
fastify.server.listen(this.config.port);
```
を
```
fastify.listen({ port: this.config.port });
```
にしたら直った

**Comment by syuilo** [comment]
なんか Route Prefixing が機能してないような気がする

**Comment by syuilo** [comment]
🤯 
![image](https://user-images.githubusercontent.com/4439005/195735882-cc792547-0e98-4239-a75a-0ae413914b6f.png)

**Comment by syuilo** [comment]
エラーは出なくなったけどなんかレスポンスが返ってこない

**Comment by syuilo** [comment]
直った

**Comment by syuilo** [comment]
なぜか `request.body` が undefined になる

**Comment by syuilo** [comment]
tasukete

**Comment by syuilo** [comment]
なんも分からん

**Comment by syuilo** [comment]
ヌァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァァンンンンオオオオンンオンオンオンオンンンンンンンンン゛ン゛！！！！！！！！！！！！！！！！

**Comment by syuilo** [comment]
> なぜか `request.body` が undefined になる

解決した方に報奨金を進呈

**Comment by syuilo** [comment]
解決した

**Comment by tamaina** [comment]
結局何が原因だったの？
