### ISSUE TITLE
Typo: Serice -> Service

### ISSUE THREAD

**Issue by fz0000** [misskey-dev/misskey#7540]
## 💡 Summary

Typo in variable.

## 🙂 Expected Behavior

Service

## ☹️ Actual Behavior
Serice

https://github.com/misskey-dev/misskey/blob/d76345264ded05b2f8a1e7b75922914fd5aeb159/locales/ja-JP.yml#L314-L315
https://github.com/misskey-dev/misskey/blob/d76345264ded05b2f8a1e7b75922914fd5aeb159/src/client/pages/settings/integration.vue#L7-L8
https://github.com/misskey-dev/misskey/blob/d76345264ded05b2f8a1e7b75922914fd5aeb159/src/client/pages/settings/integration.vue#L16-L17
https://github.com/misskey-dev/misskey/blob/d76345264ded05b2f8a1e7b75922914fd5aeb159/src/client/pages/settings/integration.vue#L25-L26

## 📝 Steps to Reproduce

1. N/A

## 📌 Environment

develop

**Comment by syuilo** [comment]
Good catch

**Comment by fz0000** [comment]
By the way, other *.yml files under `locales` folder may also need update. Or will they be synchronized automatically?

**Comment by syuilo** [comment]
> will they be synchronized automatically?

Yes
