### ISSUE TITLE
Pin users to /explore page has vanished

### ISSUE THREAD

**Issue by AlfredSK** [misskey-dev/misskey#7544]
## 💡 Summary

The possibility to pin users to the .../explore page of an instance has vanished from the instance settings. In the past it was possible to add and remove users to/from the 'pinned users' section of the explore page. That option has vanished lately. I can't find it in the instance settings anymore.

This is a very useful and cool feature. Please bring it back. 

## 🙂 Expected Behavior

That's a very cool feature. I promote interesting fedi users there. It should be possible to manage that list of pinned users. 

## ☹️ Actual Behavior

The feature is still there (pinned users section exists on .../explore). But the possibility to manage the pinned users (add/remove) has vanished from the instance settings.

## 📝 Steps to Reproduce

1. Go to .../instance
2. Try to find the dialogue to add/remove pinned users
3. Becoming aware that it has vanished :-)

## 📌 Environment

Misskey 12.81.2
Node.js 14.17.0
PostgreSQL 12.6

**Comment by syuilo** [comment]
Fixed
