### ISSUE TITLE
ランダムにテストがコケるのをなんとかする

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#7547]
なんかテストがランダムにコケる
![image](https://user-images.githubusercontent.com/6533808/120120876-500d9c80-c1db-11eb-854f-7602b770f23e.png)

コケる時は絶対

```
  1) Note
       "before all" hook for "投稿できる":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/misskey/misskey/test/note.ts)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)
```

でコケてる

14.x でも 16.x でもコケる

**Comment by mei23** [comment]
たぶん、この類の処理が微妙に30秒じゃ終わらない
https://github.com/misskey-dev/misskey/blob/a5a2f9d01e36a09dae9d475c0dc4814a3bde9cb5/test/note.ts#L26-L31
https://github.com/misskey-dev/misskey/blob/a5a2f9d01e36a09dae9d475c0dc4814a3bde9cb5/test/mute.ts#L25-L29

**Comment by mei23** [comment]
`process.env.NODE_ENV === 'test'`で起動するとスキーマのsyncが走るから遅い
→ そうでもないっぽい

**Comment by mei23** [comment]
(起動が遅いのではなくて) コケてる時は`launchServer` あたりで？ `Port is already in use` が出てる

**Comment by mei23** [comment]
テストで上げたMisskeyプロセスを終了しようとする
↓
SIGTERMでチャートの書き込みが走るので終了が遅い
というか、前のプロセスの終了時の書き込みと次のプロセスのスキーマのsyncとかが被る？
↓
前のプロセスが終了する前に次のテスト用Misskeyが起動しようとしてポートが使用中で失敗する
↓
その後のテストが失敗する

**Comment by mei23** [comment]
test時のquietとか無効にしないといざCIがコケてても何が起きてるかわからない

**Comment by mei23** [comment]
直近の必ずコケてるのは関係なし。
![image](https://user-images.githubusercontent.com/30769358/121453952-f7a97c80-c9dc-11eb-95d8-993b0fb6c8cd.png)

原因はtypeormを上げたせいで、typeorm 0.2.33 以降でテスト回すと
`Cannot read property 'substring' of undefined` で起動できないのはわかってるので上げちゃダメ

https://github.com/mei23/misskey-v12/pull/1675
