### ISSUE TITLE
削除したノートが、リモートユーザーによってRenoteされると稀に復活する

### ISSUE THREAD

**Issue by EbiseLutica** [misskey-dev/misskey#7557]
## 💡 Summary

タイトルの通りです。リモートユーザーによるRenoteのタイミング次第で、削除したノートが復活したかのような挙動を起こしてしまいます。

## 🙂 Expected Behavior

削除したノートがRenoteされることはない

## ☹️ Actual Behavior

Renoteされたタイミングで削除したノートが復活する

## 📝 Steps to Reproduce

1. ノートを作成する
2. 削除する
3. 2. のときに絶妙なタイミングでノートをリモートRenoteする

## 📌 Environment

* Misskey 12.81.2
* misskey.io

**Comment by syuilo** [comment]
まだ調べてないけどおそらく物理削除してることが原因そう

**Comment by syuilo** [comment]
「削除したノート」はローカルのもの？

**Comment by EbiseLutica** [comment]
そいですね、ローカル（misskey.io）で投稿したものです

**Comment by syuilo** [comment]
ふぅーむ謎

**Comment by mei23** [comment]
1. ローカルユーザーが投稿する AP uri=https://example.com/notes/01
2. その投稿がリモートから取得されるなどして https://example.com/notes/01 みたいなURIでnginxにキャシュされる
3. ローカルユーザーが投稿を削除する
4. リモートユーザーがその投稿をRenoteする Target uri=https://example.com/notes/01
5. そのRenote対象の投稿をDBから探そうとするが当然DBにはもう存在しない
6. DBにはないのでHTTPリクエストを出して取得しようとする。Target uri=https://example.com/notes/01
7. そこのURIがローカルインスタンスを指しているにも関わらず、Webサーバーのキャッシュから投稿を取得して新規IDを採番して新しい投稿を作成してしまうため復活したようになってしまう。

7でローカルをチェックをすればここで問題になっているローカル投稿の復活は防げる。

しかしながら v11- みたいに物理削除の場合、リモート側の一意IDで落とすことが困難なためリモート投稿を復活させてしまう可能性は残る。

**Comment by syuilo** [comment]
論理削除にすると良さそう
けどdeletedAtのようなフラグを新たに設けることになるから以下の懸念はある(けどメリットの方が上回りそうだから岸に内で良いかも)
- インデックスサイズが増加してメモリ使用量が増える？
- Noteテーブルのサイズ自体少し増える？
- ノートやタイムライン取得クエリなどで論理削除を考慮するようにする必要がある
  - モレがあると消したはずのノートが見えてしまうことになり苦情が来そう
    - 昔やってたと思うけど削除フラグ立てるのと同時にtextを空文字列にするとかである程度緩和できそう
  - あとクエリ(特にタイムライン)のパフォーマンス自体悪化しないか気になる
- クライアントで論理削除をよしなにハンドリングする必要がある
  - 例えば、会話の起点となった投稿が消されても今までとは違いリプライなどが残るから、消された投稿の表示("削除されたノート"のような表示)に対応しなければならない
- その他にも、論理削除による考慮ポイントはいくつか隠れていそう

**Comment by syuilo** [comment]
論理削除するようにするのは時間かかるからとりあえず

> 7でローカルをチェックをすればここで問題になっているローカル投稿の復活は防げる。

でよさそう

**Comment by mei23** [comment]
案外削除された投稿の比率ってすごく少ないからあまりパフォーマンスは変わらないかも。
UI的な見せ方がめんどくさいのはあるけどだわ。

**Comment by mei23** [comment]
簡単な再現手順
1. MisskeyインスタンスAをサンプル通りnginxとかのキャッシュ付きでセットアップする。
2. Aで投稿をして投稿URLを取得する。
3. フォロー関係のないMisskeyインスタンスBにて、検索ボックスに2のURLを入れて投稿を取得する。
4. Aで投稿を削除する。
5. Bで取得していた投稿をRenoteする。
6. Aのインスタンスで投稿が復活する。 (同タイムスタンプ, 異ID)

これを3分以内に実行すると再現する

**Comment by mei23** [comment]
これUserの方でも試したら`@<ローカルインスタンス>`のユーザーが生成されちゃった。
