### ISSUE TITLE
リバーシを別リポジトリにする

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#7561]
## Summary

ミニブログに関係ない

**Comment by futchitwo** [comment]
Roomも当てはまりそうな感じ

**Comment by mei23** [comment]
DB model, API endpoint, UI はすんなり切り離せなさそうだし、
それ以外の部分となると別にサーバーに思考ロジックがあるわけでもないから、
別リポジトリに入れるものなくない？

**Comment by samunohito** [comment]
再実装されたリバーシのことではなさそうなのでclose（切り離せないだろうし）
