### ISSUE TITLE
ヘルプ内のAPI文書の目次が作動しない

### ISSUE THREAD

**Issue by noridev** [misskey-dev/misskey#7563]
## 💡 Summary

日本語以外の言語でヘルプ内のAPI文書を開いたとき、目次が作動しない問題

## 🙂 Expected Behavior

目次を押すと当該目次へ移動

## ☹️ Actual Behavior

移動しない

## 📝 Steps to Reproduce

1. API文書が翻訳された言語の中から一つを選択（例：韓国語、英語など）
2. ヘルプのAPI文書を開く
3. ハイライトされている文章をクリック

## 📌 Environment

misskey.io

**Comment by Johann150** [comment]
i think this should be closed like #7564
