### ISSUE TITLE
ハードミュートの登録数を制限する

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#7574]
## Summary
こういうことされるとサーバーに負荷がかかるので。
50もあれば十分そう

![image](https://user-images.githubusercontent.com/37681609/121643065-5994df80-cacc-11eb-9e05-f3bf476d6c3d.png)

**Comment by syuilo** [comment]
改善の余地がなさそうならする

**Comment by syuilo** [comment]
やる

**Comment by acid-chicken** [comment]
そもそも（ソフトとハードは）どういう理由で分かれてるんだっけ

**Comment by tamaina** [comment]
ソフト = クライアント側で処理, サードパーティクライアントの対応が不明,Misskey Webでは存在が小さく表示されて展開して閲覧することができる

ハード = サーバー側で処理, すべてのクライアントで存在が表示されない

（そういえば全く違う話だけど、ハードミュートでは引用が処理されないという話を聞いたことがある

**Comment by syuilo** [comment]
ハードミュートはミュート解除しても過去にミュートされたのはミュートされ続けるのと、(v13から)ミュートされてから一定期間経過するとミュート解除される

**Comment by syuilo** [comment]
ワードミュートの数を制限するだけだと、正規表現使って回避できそうだから文字数制限も必要かも
