### ISSUE TITLE
ソフトミュートにおいてもミュート時のメッセージを表示させない設定

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#7575]
## Summary
ソフトミュートではなくハードミュートに大量にワードを追加して使っていしまうと、意図せずサーバーに負荷がかかってしまうため、サーバーに影響を与えないクライアント制御のソフトミュートの場合でもハードミュートと同様に非表示になった際のメッセージを表示させない設定を追加してもらいたいです。

追記：2023.12.0にて実装予定。ソフトミュートについて記述しているが実質ハードミュートの一部として実装される見込みか

関連 : #7574

**Comment by CookieRamen** [comment]
> ソフトミュートではなくハードミュートだとサーバーに負荷がかかってしまうため
一連の投稿を見てない人には理解できなさそう。

そもそもハードミュートが悪いわけではなくハードミュートに700ワードも追加するから悪いと言われてるわけであって、ソフトミュートにおいてメッセージを表示しない事とはなんら関係ない

**Comment by CookieRamen** [comment]
> ソフトミュートではなくハードミュートに大量にワードを追加して使っていしまうと、意図せずサーバーに負荷がかかってしまうため、サーバーに影響を与えないクライアント制御のソフトミュートの場合でも

ここ要らなさそう

**Comment by tkmrgit** [comment]
えー...導入したいと考える理由について述べただけにゃんだけどにゃぁ :crying_ai:

**Comment by CookieRamen** [comment]
Issueにあなたが導入したい個人的な理由は必要ない

**Comment by syuilo** [comment]
理由あった方がユースケースにあった実装できたり優先度決めるのに役立ったりする

**Comment by CookieRamen** [comment]
これって「ソフトミュートにおいてもミュート時のメッセージを表示させない設定（がほしい）」って言うIssueだけどハードミュートにしたらサーバーに負荷が掛かるからって理由必要なの

**Comment by CookieRamen** [comment]
個人的にはかくならこう言うコメント欄かなって思うんだけど
Issue漁っててノイズが混じってると普通に見にくいきがする

**Comment by EbiseLutica** [comment]
個人的に私も欲しいなーって思うので理由をば。

* 見たくないからミュートしているのに、「なにかを言いました」って隠し表示されてしまったら気になってしまう
* ↑上の問題に対処すべくハードミュートのみを使用している
* ハードミュートはサーバーに負荷がかかるので、多用しすぎてもあまり心配いらないソフトミュートで対処したい

**Comment by kabo2468** [comment]
```css
.muted {
    display: none;
}
```
カスタムCSSが実装されたので一応できなくはない

**Comment by tkmrgit** [comment]
ハードミュート廃止かみたいな議論ににゃってるみたいなので

・このIssueのようにサーバーに負荷を掛けないミュート方法かつ消える方法が欲しい
・カスタムCSSによる解決方法が共有されているが、環境毎に設定しないといけないのでとても不便(Misskeyは設定画面の内容が環境毎に保存される項目が多すぎて毎度設定するのが大変にゃのだ！)

これ2021年のIssueですが、ハードミュート廃止に踏み切られるようであれば実現していただきたいなと思います。

**Comment by tkmrgit** [comment]
https://github.com/TeamNijimiss/misskey/commit/1645cd18877afbad9333805966b60e69732b6cde にじみすが対応してくれました (現在サーバーのほうは当該バージョンにはアップデートしていません)

**Comment by tkmrgit** [comment]
https://github.com/misskey-dev/misskey/pull/12376
https://github.com/misskey-dev/misskey/pull/12564

実装されたのでclose
