### ISSUE TITLE
ドライブの既定アップロード先を指定してもそこにアップロードされない

### ISSUE THREAD

**Issue by minetaro12** [misskey-dev/misskey#7576]
## 💡 Summary

ドライブの設定で既定アップロード先を指定してもそこにアップロードされない

## 🙂 Expected Behavior

既定アップロード先に指定したフォルダにアップロードされる

## ☹️ Actual Behavior

既定アップロード先に指定したフォルダにアップロードされない

![Screenshot_20210612-154918](https://user-images.githubusercontent.com/77948036/121767982-9fb67580-cb96-11eb-9b6c-33123d4adb6a.png)

![Screenshot_20210612-154954](https://user-images.githubusercontent.com/77948036/121767989-a5ac5680-cb96-11eb-8ede-cc81f0699908.png)

![Screenshot_20210612-155002](https://user-images.githubusercontent.com/77948036/121767992-aba23780-cb96-11eb-9397-91a250c9f30a.png)

![Screenshot_20210612-155010](https://user-images.githubusercontent.com/77948036/121767994-b066eb80-cb96-11eb-9bfe-e4b1352b4719.png)

## 📝 Steps to Reproduce

1.サイドメニューを開く
2.設定を開く
3.ドライブの設定を開く
4.既定アップロード先を設定
5.ノートの画面からファイルをアップロード
6.既定アップロード先でなくルートディレクトリにアップロードされている

## 📌 Environment

Misskey 12.83.0

**Comment by tamaina** [comment]
私の環境だと再現しなかった…

**Comment by tamaina** [comment]
私の環境では再現しなかった…

**Comment by minetaro12** [comment]
misskey.ioでも同じ症状が出ました…
もしかすると開発ブランチでは直ってるという感じですかね？
![Screenshot_20210713-230946_1](https://user-images.githubusercontent.com/77948036/125467132-c2f2ed92-c8bf-4051-a4ac-75d8f28f2cb4.png)

**Comment by syuilo** [comment]
ページリロードしたあとアップロードしても反映されないです？

**Comment by minetaro12** [comment]
されないです
一応今PCでも確認しましたが既定アップロード先ではなく必ずルートディレクトリにアップロードされます

**Comment by syuilo** [comment]
ローカル(develop)で再現した

**Comment by syuilo** [comment]
原因もわかった
