### ISSUE TITLE
Mute thread option

### ISSUE THREAD

**Issue by WeebleWee** [misskey-dev/misskey#7580]
Add feature that stops sending you reply notifications for threads you are mentioned in. After I stopped replying to a conversation I will still get mention notifications when people reply, I would like to mute those notifications after I stopped participating in a conversation.

Mastodon has something similar 
![image](https://user-images.githubusercontent.com/74576496/121770959-153c2a80-cb32-11eb-9504-dbdfabd8d0cf.png)

**Comment by tamaina** [comment]
通知については #2144 #2227 あたりが似ていそう

メンション欄にメンションを表示したくない、ということになると別の機能になるかも

**Comment by syuilo** [comment]
ThreadMuteテーブル追加して、そこに追加されたノートの子ノートについて通知しないようにすれば良いか
ただ、あるノートがMuteされたノートの子であるかどうかというのは再帰的に調べる必要があって、SQL上では判定が難しいから、通知を作成しないようにはできても、メンション一覧から取り除くというのは難しいかもしれない

**Comment by syuilo** [comment]
Muteされたノートに子ができた時、その子についてもMuteを挿入する仕組みにすれば回避できるか

**Comment by syuilo** [comment]
うーんもうちょっとスマートな実装方法ないかな

**Comment by syuilo** [comment]
あー、メンション一覧取得はNoteのmentionsカラム見てたはずだから、作成時に親がMuteされてたらMentionsに追加しないというのでも良いけど
ただそうするとミュート解除しても永遠に見られない

**Comment by noellabo** [comment]
PostgreSQLで再帰クエリ書いちゃってもいいとは思うけど、

Mastodonの場合は投稿にあらかじめconversation_id（スレッドID）振ってるので、誰がどのconversation_idをミュートしてるかだけ管理すればいいようになってる。

**Comment by syuilo** [comment]
conversation_id って全ての葉ノードが同じIDになるんですかね？
とするとあるスレッドの一部でもミュートすると一番親の投稿に基づく全ての子が(いくら分岐してようとも)ミュートされる感じなのかな

**Comment by noellabo** [comment]
このIssueにスクショされてるMastodonのMute conversationはそういう挙動ですね。

スレッドの最初の親になってる投稿のIDがconversation_idと同じになってて、リプライが生成されるときにそのconversation_idを引き継いでいく感じです。
