### ISSUE TITLE
[i18n] Add Vietnamese (vi) language on Crowdin

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#7583]
Hello.
Can you add Vietnamese language to the project? I would like to help to translate it in my spare time.
Thank you.

**Comment by tamaina** [comment]
これなんでやってないの？

**Comment by tamaina** [comment]
（あ、いや、いきなり問い詰めてもしょうがないんだけど）

**Comment by 4ioskd** [comment]
Why this language didn't add into Crowdin??

**Comment by syuilo** [comment]
翻訳の提案や質問も含めCrowdinをメンテナンスする時間が全く取れていないため、メンテナーを募集しています。

**Comment by KawaneRio** [comment]
メンテナーってCrowdinの？翻譯關聯の質問に答へたり、新しい言語をMisskeyに追加したりする的にゃ？

**Comment by syuilo** [comment]
yes

**Comment by robflop** [comment]
(Hi, new Crowdin maintainer here)

I've added the language. Thanks for your help with translating!
