### ISSUE TITLE
Add sinhalese language on crowdin

### ISSUE THREAD

**Issue by Aikatsui** [misskey-dev/misskey#7584]
I already sent message to @syuilo 6 months ago through crowdin but it seems haven't noticed.
Language: Sinhalese/Sinhala (si)

**Comment by tamaina** [comment]
なんでこういうの放置するの？  
（問い詰めてもしょうがないけど）

**Comment by 4ioskd** [comment]
Why this language didn't add into Crowdin??

**Comment by robflop** [comment]
I've added the language. Thanks for your help with translating!
