### ISSUE TITLE
Broken build when using watch mode

### ISSUE THREAD

**Issue by Skehmatics** [misskey-dev/misskey#7587]
## 💡 Summary

`yarn run watch` produces a broken build.

## 🙂 Expected Behavior

Builds should be identical between `yarn run build` and `yarn run watch`

## ☹️ Actual Behavior

Building via `yarn run watch` somehow seems to ignore the "paths" option from `src/tsconfig.json`, causing module resolution to fail.

## 📝 Steps to Reproduce

1. Run `yarn run watch` and wait for build to complete.
2. Run `yarn run start`

## 📌 Environment

Fedora 34
yarn 1.22.10
node v12.20.1

**Comment by rinsuki** [comment]
We should split this script to `watch-ts` and `watch-tsc-alias`

https://github.com/misskey-dev/misskey/blob/d97fc9ce4ea19466fd77428724ffcab6fe001966/package.json#L24

**Comment by Johann150** [comment]
The current setup for watch seems to work.
