### ISSUE TITLE
Mysterious error shows up when trying to access / (not signed in)

### ISSUE THREAD

**Issue by parabirb** [misskey-dev/misskey#7589]
## 💡 Summary

When attempting to access the homepage, some users on my instance are receiving an error. The instance URL is https://wrongthink.me

## 🙂 Expected Behavior

Homepage should show up

## ☹️ Actual Behavior

Error appears along the lines of:

```
:warning:エラーが発生しました
問題が解決しない場合は管理者までお問い合わせください。以下のオプションを試すこともできます:

簡易クライアントを起動
BIOSで修復を試みる
キャッシュをクリアする
ERROR CODE: SOMETHING_HAPPENED
Details
Uncaught SyntaxError: Unexpected token .
https://wrongthink.me/cli

https://wrongthink.me/bios

https://wrongthink.me/flush
```

## 📝 Steps to Reproduce

This bug is difficult to reproduce and it doesn't appear that there is much in common connecting the errors. It has only been reproduced 3 times out of 200 users.

## 📌 Environment

DigitalOcean Droplet (1GB RAM, 1 vCPU, 25GB SSD) running Ubuntu 18.04 with Node.js v14.8.0, Redis 4.0.9, and PostgreSQL 10.17

**Comment by syuilo** [comment]
In most cases, this error is caused by the user's browser or OS version being out of date. Please update it.

**Comment by parabirb** [comment]
Thank you.
