### ISSUE TITLE
音を消すボタンをどこかに着けてほしい

### ISSUE THREAD

**Issue by mendakon** [misskey-dev/misskey#7590]
ピコピコしてほしい時とピコピコしてほしくない時（電話がかかってきたときなど）があり、手早く切り替えられると便利なので

お願いします！

**Comment by tamaina** [comment]
- グローバルのミュートのオンオフ
- mキーでミュート/ミュート解除するキーショートカット
- ミュートを制御するサイドバーの項目

あたりを実装すればよさそう？

**Comment by syuilo** [comment]
off topic: そのサイトをミュートするショートカットくらいブラウザ側で用意してほしい感はある

**Comment by mei23** [comment]
ブラウザ自身にサイトをミュートする機能はあるからアドオンでどうにか出来そうな気がする

**Comment by tamaina** [comment]
……それ言ったらPC自体をミュートすればよくない？と思ってしまった

**Comment by syuilo** [comment]
スマホブラウザだとミュートする機能無い場合が多いけど、スマホで一時ミュートしたいときがあるのかはわからん

**Comment by tamaina** [comment]
iOSやAndroidの仕様的に通話中ってほかの再生がミュートされないのかしら…？

あと、FirefoxはCtrl+Mでタブをミュートできる

**Comment by EbiseLutica** [comment]
そもそもiOSでは音がまともに鳴らない

**Comment by SanMurakami** [comment]
> off topic: そのサイトをミュートするショートカットくらいブラウザ側で用意してほしい感はある

PCに関してはChromeのショートカットをカスタマイズする拡張機能があったはず
それつかってこれ割り当てられそう

![image](https://user-images.githubusercontent.com/37681609/129464547-432d98c4-ecc9-43f0-a2c7-ffd16f23a491.png)

スマホに関してはiOSはしらんけどAndroidは通知音とメディア音と通話音が分かれてるのでメディアをミュートしてくれって感じ
