### ISSUE TITLE
Unable to communicate with a specific Mastodon instance

### ISSUE THREAD

**Issue by belatedly** [misskey-dev/misskey#7592]
## 💡 Summary

A friend recently moved to a Mastodon instance that my Misskey instance fully federates with. She has been able to see our accounts and submit follow requests, but we do not receive them. When I attempted to search for her account, the logs output an error.

While troubleshooting, I ended up seeing that I cannot refresh the accounts of anyone on that instance and it kicks out an error. The admin of that instance said everything looks good on his end and his admin panel isn't showing any errors for us. Full information and screenshots below.

## 🙂 Expected Behavior

When I search for a user on a Mastodon instance I federate with, I should see that account come up.

## ☹️ Actual Behavior

When I search for @sourcookie@rage.love, I encounter the error page:

![image](https://user-images.githubusercontent.com/63966511/125136554-a91cfa00-e0d0-11eb-8d21-f15fc988cabd.png)
Retry does not have a different result.

The logs show the following:
- 4m ago [remote.resolve-user] WebFinger for sourcookie@rage.love
- 4m ago [remote.resolve-user] return new remote user: sourcookie@rage.love
- 4m ago [api] failed to resolve remote user: [object Object]

While reviewing the logs, I noticed that she replied to a user from her instance that we currently follow, and a 401 error came in the logs regarding us receiving that note:
- 51s ago [remote.ap] Error in inReplyTo https://rage.love/users/sourcookie/statuses/106547988326511288 - 401
- 47s ago [api] Internal error occurred in ap/show: 401 Unauthorized

When I attempt to update any of that instance's users, I get this error:

![image](https://user-images.githubusercontent.com/63966511/125136904-4b3ce200-e0d1-11eb-880d-aed2342c701d.png)

When I attempt to look at any of their users' ActivityPub info, I get this error:

![image](https://user-images.githubusercontent.com/63966511/125136975-660f5680-e0d1-11eb-9791-b19131ace090.png)

We are still receiving posts and interactions from the users we are following from that instance:

![image](https://user-images.githubusercontent.com/63966511/125137047-86d7ac00-e0d1-11eb-9d9b-eedac0322930.png)

The instance's admin is filing a ticket with their server provider, but I want to also verify that there is not something wrong on my Misskey instance.

## 📝 Steps to Reproduce

See above.

## 📌 Environment

Misskey v12.83.0

**Comment by mei23** [comment]
I couldn't see it from that account, mastodon.social, so it doesn't seem to be a Misskey-specific issue.

**Comment by belatedly** [comment]
> I couldn't see it from that account, mastodon.social, so it doesn't seem to be a Misskey-specific issue.

They do not federate with mastodon.social

**Comment by rinsuki** [comment]
I think rage.love is using Mastodon's AUTHROIZED_FETCH mode https://github.com/tootsuite/mastodon/pull/11269 .

If this mode enabled, signature is always required (to enforce domain blocks), and Misskey mayn't supported this (currently).

**Comment by mei23** [comment]
> mayn't supported this (currently).

してる

Try enabling `signToActivityPubGet` in config.

.config/default.yml
```
signToActivityPubGet: true
```

**Comment by belatedly** [comment]
> 
> 
> > mayn't supported this (currently).
> 
> I'm doing
> 
> Try enabling `signToActivityPubGet` in config.
> 
> .config / default.yml
> 
> ```
> signToActivityPubGet: true
> ```

That fixed the issue! Thank you so much!!
