### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by RaZZlom** [misskey-dev/misskey#7593]
## 💡 Summary

On my instance (https://quietplace.xyz/) I'm using s3 to store media files and uploaded videos not playing. Console log shows CORS error.

Link to post - https://quietplace.xyz/notes/8nzgdfavww
Link to video - https://misskeyfiles.s3.nl-ams.scw.cloud/files/27080826-4da3-45ab-a7fc-40e16d1f682e

I tried add add_header 'Access-Control-Allow-Origin' '*' to nginx config, but it not help.

## 🙂 Expected Behavior

Video playing.

## ☹️ Actual Behavior

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://misskeyfiles.s3.nl-ams.scw.cloud/files/27080826-4da3-45ab-a7fc-40e16d1f682e. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

## 📝 Steps to Reproduce

1. Open post.
2. Click play.

## 📌 Environment

Misskey - v12.83.0
Node.js - v14.17.0
PostgreSQL - 13.3 (Debian 13.3-1.pgdg100+1)
Redis - 5.0.3

**Comment by mei23** [comment]
Related https://github.com/misskey-dev/misskey/issues/7323

**Comment by RaZZlom** [comment]
> Related #7323

From Mastodon i can see videos perfectly. I can't see videos from my own instance!

**Comment by mei23** [comment]
#7594 OR Add `Access-Control-Allow-Origin: *` to your object storage's host (eg: misskeyfiles.s3.nl-ams.scw.cloud) may fix it.

**Comment by RaZZlom** [comment]
> #7594 OR Add `Access-Control-Allow-Origin: *` to your object storage's host (eg: misskeyfiles.s3.nl-ams.scw.cloud) may fix it.

I added cors config and it not working. :disappointed: 


```terminal
razzlom@razzlom-pc ~> aws s3api get-bucket-cors --bucket misskeyfiles
```

```json
{
    "CORSRules": [
        {
            "AllowedHeaders": [
                "*"
            ],
            "AllowedMethods": [
                "GET",
                "HEAD",
                "POST",
                "PUT",
                "DELETE"
            ],
            "AllowedOrigins": [
                "http://quietplace.xyz",
                "http://www.quietplace.xyz"
            ],
            "ExposeHeaders": [
                "Etag"
            ],
            "MaxAgeSeconds": 3000
        }
    ]
}
```

Test post here - https://quietplace.xyz/notes/8o1ah1i060

Waiting for new misskey version and hope it help. 
Thank you!

**Comment by rinsuki** [comment]
> ```json
>             "AllowedOrigins": [
>                 "http://quietplace.xyz",
>                 "http://www.quietplace.xyz"
>             ],
> ```

You should use `https://` instead of `http://`.

**Comment by RaZZlom** [comment]
> > ```json
> >             "AllowedOrigins": [
> >                 "http://quietplace.xyz",
> >                 "http://www.quietplace.xyz"
> >             ],
> > ```
> 
> You should use `https://` instead of `http://`.

Oh, I'm very stupid. :facepalm: 
Now it works.
VERY big thank you for your help! :pray:
