### ISSUE TITLE
言語ファイルから型を取得したい

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#7598]
## Summary

https://github.com/quicktype/quicktype
とか使う？YAML非対応っぽいけど

**Comment by tamaina** [comment]
言語ファイルの型を別途ts（もしくはmisskey.js）で定義しちゃえば…

最初は作るの大変そうだけど、追加するときは付け足せばいい気がする

**Comment by syuilo** [comment]
面倒くさいけどそれもアリ

**Comment by tamaina** [comment]
んてかTypeScriptネイティブでjsonを型にする機能ってないかしら
