### ISSUE TITLE
インスタンス → サーバーにする

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#7599]
## Summary

- インスタンスという呼称は一般的に馴染みがなく説明が難しい
- 類似の概念を他サービス(Discord等)ではサーバーと呼称している
- プログラミングの「クラスのインスタンス」と紛らわしい

**Comment by tamaina** [comment]
私のお気持ち: 今更変えるのか～（私が作成している文章を変えるのを負担に感じているだけ）

Mastodonでもサーバーと呼ぶようになっているけど、普及してしまった以上「インスタンス」は今でも広く使われているからあんま意味ない気がしてる。  
たとえばマストドン日本語ウィキはいまでも[サーバー](https://ja.mstdn.wiki/%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC)よりは[インスタンス](https://ja.mstdn.wiki/インスタンス)と呼んでいる。

> インスタンスという呼称は一般的に馴染みがなく説明が難しい

分散SNSの概念自体が新しいものなので用語を変更したところで理解してもらえるかどうか不明。使ってもらえばふわっとでも理解してもらえるものだと思う。

> プログラミングの「クラスのインスタンス」と紛らわしい

一般ユーザーにとっては紛らわしくなることってほぼないし、開発者が混乱している場面もあまり想像できない。「サーバー（サービス）」が複数の「物理サーバー」にまたがって構築されるとこんどは一般用語としてのサーバーと混乱しそうだけど、クラウドVMはインスタンスと呼ばれるのでどっちもどっち

**Comment by EbiseLutica** [comment]
一般的に馴染みがないことが逆に固有名詞的に扱えるから僕も全然変えなくて良いかな～と思う

名称変更による混乱リスクと天秤にかけても反対します

**Comment by tamaina** [comment]
アンケートとってみた  
https://p1.a9z.dev/notes/8oa0qxcjck

**Comment by mei23** [comment]
でも、多数決なんか気にせず @syuilo の気分でいいわよ

**Comment by ghost** [comment]
ご参考までに。[Mastodon の Esperanto 語版UIでは英語原文で server となっているところが servilo (サーバー) と nodo (ノード，結わえ目，道の交わる交通の要所；結節点，物事の核心；要) のどちらかに意訳されている](https://ja.crowdin.com/translate/mastodon/all/en-eo?filter=basic&value=0#q=nodo)ようです。ただ私の語学力の関係でこの訳者がどういう条件でこの2つの言葉を使い分けているのかがよく分からない。

ちなみに自分は非中央集権型という言葉の意味を教えてもらった時から nodo という言葉を検討はしていました。ekzemplo (en: instance) とは違って kun-feder-i (同盟する，連合する)、kunfederaĵo (連合)という語との関係が明確になるからです。意訳大事

**Comment by ghost** [comment]
言語的距離の遠い印欧語の文章のうちの逐語訳ができない見慣れない表現や言い回しの一部分を切り取ってそのまま新たな概念のカタカナ語として導入してしまうのは現代日本語くらいのものなのかもしれない。
> 分散SNSの概念自体が新しいものなので用語を変更したところで理解してもらえるかどうか不明。使ってもらえばふわっとでも理解してもらえるものだと思う。

> 一般的に馴染みがないことが逆に固有名詞的に扱えるから僕も全然変えなくて良いかな～と思う

　これについては、巷に跋扈するカタカナ語の大半は敢えて日本語と互換性のない言い回しに言い換えることで相手の判断力を鈍らせる効果を狙ったものだということからわかるように、必要性の乏しい新たな外来語を導入することによって学習効果が上がるようなことはないし、たとえば仮に今「サーバー＝クライアント型」等といった有名な言葉に「サーバー」という言葉のイメージが引きづられていたとしても時間の経過によって語義は移ろいゆくものなんちゃう？

**Comment by SanMurakami** [comment]
> プログラミングの「クラスのインスタンス」と紛らわしい

これに関してはサーバーにするとハードウェアのサーバーと紛らわしいし、一般的にクラスのインスタンスと認識するのはプログラマーだけだと思うというのはある

**Comment by ghost** [comment]
補足：
専門職からしてみれば適当と思われる言い方を（見かけ上は）できているかということと実際の発話者の言語理解とには乖離があってもおかしくないし、同じ単語でも文脈や言い回しというレベルで区別できるものなのでは

**Comment by 4ioskd** [comment]
各fediverseアプリケーションの鯖への呼称を「ブランディングや広報」という観点で考えるのはどうでしょう。鯖への呼称として、サーバー、インスタンス、ポッド、ホスト、ピア、ノードなど様々な用語がありますが、「インスタンス」という言葉は、個人的にはfediverse以外でかつプログラミング関連を除けば、あまり聞いた事がありません。一方、「サーバー」は用語としては一般の人にはよく知られていてmisskeyの説明がしやすいですが、インスタンスからサーバーに呼称変更した際に、各fediverseアプリケーションの鯖缶やユーザーからどういう反応が返ってくるか、という点が気になりますかね。ちなみにFunkwhaleのポッドの由来は、Funkwhaleに「ポッドキャスト」の配信機能があるからだ、と考えてます。

参考：各fediverseアプリケーションの鯖への呼称
マストドン：サーバー
プレロマ：インスタンス
Pixelfed：サーバー
PeerTube：インスタンス
Lemmy：サーバー
Funkwhale：ポッド
Diaspora: ポッド

**Comment by 4ioskd** [comment]
個人的には現状維持で「インスタンス」が良いと思います。ドキュメントの書き直しによる手間や名称変更による混乱を考えれば。

**Comment by ghost** [comment]
インスタンスという呼称を使いたい人が引き続きインスタンスと呼べばいいだけ。ドキュメントの書き直しはたったの一度だけであり、大部分が単純な文字列置換だけで済む。
　しゅいろが .io で行った投票つき投稿でも Mastodon がインスタンスをサーバーに名称変更していた事実を知らなかったという人が大部分を占めていました。混乱が生じるなどというのは杞憂でしょう

> 「インスタンス」という言葉は、個人的にはfediverse以外でかつプログラミング関連を除けば、あまり聞いた事がありません。一方、「サーバー」は用語としては一般の人にはよく知られていてmisskeyの説明がしやすいですが、インスタンスからサーバーに呼称変更した際に、各fediverseアプリケーションの鯖缶やユーザーからどういう反応が返ってくるか、という点が気になりますかね。

あとこれって仮に

> 各fediverseアプリケーションの鯖への呼称を「ブランディングや広報」という観点で考える

のであれば前者になるのが自然なのではありませんか？

**Comment by ghost** [comment]
失礼。私が意図しているのは文脈上「サーバー」であるので前者ではなく「後者」が正解ですね

**Comment by 4ioskd** [comment]
>ドキュメントの書き直しはたったの一度だけであり、大部分が単純な文字列置換だけで済む。

一口にドキュメントと言っても、misskey-devリポジトリ全体だけでなくmisskey-wikiやサードパーティアプリやmisskeyのハードフォークなどの外部プロジェクトのドキュメントもありますからね。

>各fediverseアプリケーションの鯖への呼称を「ブランディングや広報」という観点で考えるのであれば後者になるのが自然なのではありませんか？

確かに広報的な意味合いが多いですね。
私の発言の「インスタンスからサーバーに呼称変更した際に、各fediverseアプリケーションの鯖缶やユーザーからどういう反応が返ってくるか、という点が気になりますかね。」が言葉足らず出したが、ブランディング要素ですかね。従来からPleromaは鯖のことをインスタンスと呼んでいますが、misskeyは最近の海外Pleromaユーザーが海外マストドンにではなくmisskeyに大移動したように、以前から関係性が良いですよね。では現在のインスタンスからマストドンなどが利用するサーバーに名称変更すると、元海外Pleromaユーザーのミスキストや現海外Pleromaユーザーらはどういう反応をするでしょうね。国内では問題が無いのかな？とは思うものの、この辺りは考慮した方が良いでしょう。また彼らは、misskeyへの様々な支援を行っている事をお忘れなく。

**Comment by ghost** [comment]
>サードパーティアプリやmisskeyのハードフォークなど

それはここの管轄外でしょう。

**Comment by 4ioskd** [comment]
ですね。misskey-devでの呼称を変えると、リポジトリ全体だけでなくmisskey-wikiやサードパーティアプリやmisskeyのハードフォークなどの外部プロジェクトにあるドキュメント全てに影響が発生する、と言いたかったのでした。

**Comment by ghost** [comment]
技術者やFediverse既存ユーザーは既に知っているだろうし、誰にでも意味の分かる言葉である「サーバー」でも別に構わないだろうというのが個人的な意見です。
同じく物理サーバーではないメールサーバーだってインスタンスって言いませんよね。
　Pleroma ユーザーは（過去のある時点で）Mastodon と Pleroma を天秤にかけてPleroma を選びましたが、Misskey と Mastodon を天秤にかけたわけではありません。今になってMastodon の細かな用語を思い出すことなどないでしょう。

　ちなみに、これはめいめい氏が自身のmisskeyでさらっと挙げていたのですが「ホスト」という言葉があります。良い案だと思います

**Comment by marihachi** [comment]
逆に惑星みたいなユニークな名前にしても楽しそう

**Comment by marihachi** [comment]
名称変更時、サードパーティには適切にアナウンスすれば問題ないと思う

**Comment by Johann150** [comment]
First of all I think changing the name would cause a lot of unnecessary work, e.g. changing all the translations, changing the documentation, translations of the documentation...

> インスタンスという呼称は一般的に馴染みがなく説明が難しい
> (deepl: The term "instance" is generally unfamiliar and difficult to explain.)

The term "server" to a non-technical user is probably also very confusing because it can mean different things: software or hardware (or even a waiter in a restaurant). And technical users will be quickly able to understand what instance means (see also last point).

> 類似の概念を他サービス(Discord等)ではサーバーと呼称している
> (deepl: A similar concept is called a server in other services (such as Discord).)

A "server" on Discord is again a different definition than the ones I mentioned above: It's definitely not a hardware server, and probably not even a different software server (and of course nothing to do with restaurants). If I could name it, I would probably call it an instance instead (because it is an instance of a software server or maybe only a database entry). I also saw some other people saying that on discord, servers should be named guilds (組合), probably because that term was used in some other software before.

> プログラミングの「クラスのインスタンス」と紛らわしい
> (deepl: Confusing with "instance of a class" in programming.)

I don't think everyone using Misskey is a programmer or knows about classes and instances. And even the people that do know about classes and instances will not confuse this because it is not at all in the context of OOP.
If anything this point may get worse by calling it a server, because what do you mean by Misskey Server now? Hardware, software? Maybe a Docker container?

---

Summary: Renaming is **unnecessary** and might make things worse. The better solution would probably be to have **good documentation material**.

**Comment by syuilo** [comment]
やっぱりインスタンスというのは馴染みがないのか、サーバー呼びの方が広まってきてる

**Comment by SanMurakami** [comment]
別に公式にインスタンス、サーバーを決めずに好きに読んでもらえばいいんじゃね感はある

**Comment by EbiseLutica** [comment]
MisskeyやMisskey Hubなどで使用する文言を統一したいというのが本issueの趣旨なら、私はどっちでも良いとおもうよ

強いて言えば、マストドンが「サーバー」という語を採用している為、あえてインスタンスって名前を使い続ける必要は無いかも。

**Comment by syuilo** [comment]
最初の画面で「インスタンスに登録」「インスタンスを探す」とか出てきても初めての人にとっては何のこっちゃだと思うからサーバーにしたい感が高まってきた
サーバーなら既にオンラインゲームとかDiscordなどのサービスでも一般的な概念だしわかりやすいと思う

**Comment by weepjp** [comment]
<s>「#InstanceTicker」を名付けたら翌年に、Mastodon側が「インスタンス」を「サーバー」表記に置き換える動きが出てきて、まるでハシゴ外されたような思いをした身なので駆けつけてきました。</s>

会話上の表現としては随所随所で、言葉として座りのいいほうを選ぶでしょう。
そういう意味では賛成も反対もしません。
Twitter の プロフィール文を bio 、いいねを fav と言ったりする文化もとてもすきです（知らん人には不親切ではある）。

ただ今回は、それとドキュメント上の表現とは分けて考えるべきで、ドキュメント上において表記ゆれがあることは、好ましくないことは大いに理解できますし、Mastodon 側の 「インスタンス → サーバー」に至った経緯もおいらは納得しています。

// 個人的には、「ノートのインスタンス情報」はどういう表記になるのかが興味深いところで、仮に「ノートのサーバー情報」に置き換えた場合、なんか仰々しいので「ノートのサーバー名」あたりになるのかな？と気になってしまった。

**Comment by syuilo** [comment]
分かりやすさと、表記揺れを解消したいためUI上はサーバーに統一する方向で
