### ISSUE TITLE
誕生日が必須

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#76]
必須にしないで

**Comment by syuilo** [comment]
必須じゃないよ

**Comment by rinsuki** [comment]
誕生日設定しないとプロフィール変えられない

**Comment by syuilo** [comment]
ふぅ〜む

**Comment by syuilo** [comment]
need details

**Comment by rinsuki** [comment]
misskey.xyzの設定から（誕生日を一度も設定していない状態で）誕生日以外を変更して適応しようとすると変わらない
Developer Toolsでリクエスト見ると`{"error":"invalid birthday"}`でしんでる 
実質必須になってる

**Comment by syuilo** [comment]
@Petitsurume Thanks!
