### ISSUE TITLE
自動で投稿にハッシュタグをつける機能

### ISSUE THREAD

**Issue by kabo2468** [misskey-dev/misskey#7600]
## Summary

TVの実況とかでハッシュタグをつけたいときに、毎回入力するのが面倒なので

**Comment by tamaina** [comment]
前にもこんなIssue（もしくは機能？）なかったかしら

あと、チャンネルを使おうぜという意見も一部から寄せられました

**Comment by kabo2468** [comment]
v11のときは投稿フォームに前に投稿したハッシュタグの一覧があったから不便じゃなかったと思ってる

チャンネルは連合しない、編集・削除ができないのでそこが改善されれば代わりに使うのもあり

**Comment by rinsuki** [comment]
このへん？めいすきーだけど https://mstdn.rinsuki.net/users/rinsuki/statuses/106136634645866657

**Comment by mei23** [comment]
https://github.com/misskey-dev/misskey/issues/7600#issuecomment-881506722
は、タグ検索した後に投稿フォームを開くとそのタグを自動入力する だからちょっと違うかもだわ。

**Comment by kabo2468** [comment]
欲しいのはGroundpolisの「ノートの末尾に加えるテキスト」って機能みたいな感じですね
投稿してもそれが消えずに残っててほしい

**Comment by EbiseLutica** [comment]
<details>
<summary>実装例</summary>

* https://github.com/Groundpolis/Groundpolis/commit/7603eb656f873781b0be42da27ca2fee333faf6e
* https://github.com/Groundpolis/Groundpolis/commit/4b6ec007becee911fc7347bc92733fdb06b969c1

</details>

**Comment by acid-chicken** [comment]
> 前にもこんなIssue（もしくは機能？）なかったかしら

昔に見た気がするのは twista のせいかも 8ab7db42972bf241b946e6e826b33169b29a2969

**Comment by EbiseLutica** [comment]
Twistaをぱｋｹﾞﾌｹﾞﾌｹﾞﾌｹﾞﾌﾝ!!!ﾊｧ!!!参考にしましたね
