### ISSUE TITLE
希望misskey添加代理远程用户的头像

### ISSUE THREAD

**Issue by rsesot** [misskey-dev/misskey#7601]
## Summary

When I open the proxy remote file, the avatar will not be proxied, which greatly affects the appearance and use. I hope that I can add a proxy for the avatar

[https://oss.ovo.ci/neko/8bb5d844-6f9d-4745-9eee-fdf4c6bb84dc.png](url)

[https://oss.ovo.ci/neko/5c91c7de-eb26-4730-b5ee-6cc41bbabb42.png](url)

**Comment by mei23** [comment]
It doesn't work due to a bug.
