### ISSUE TITLE
misskey fails to start workers after update.

### ISSUE THREAD

**Issue by WillowMist** [misskey-dev/misskey#7607]
After upgrading to the latest master build, and following all the upgrade instructions (multiple times), I'm getting 
`
INFO *	[core boot]	Welcome to Misskey!
INFO *	[core boot]	Misskey v12.83.0
INFO *	[core boot env]	NODE_ENV: production
INFO *	[core boot env]	You do not have root privileges
INFO *	[core boot nodejs]	Version 14.17.2
DONE *	[core boot config]	Loaded
INFO *	[core boot db]	Connecting...
DONE *	[core boot db]	Connected: v10.17 (Ubuntu 10.17-0ubuntu0.18.04.1)
DONE *	[core boot]	Misskey initialized
INFO *	[core boot]	Starting 1 worker...
ERR  *	[core cluster]	[1] died :(
ERR  *	[core cluster]	[2] died :(
ERR  *	[core cluster]	[3] died :(
ERR  *	[core cluster]	[4] died :(
ERR  *	[core cluster]	[5] died :(
ERR  *	[core cluster]	[6] died :(
ERR  *	[core cluster]	[7] died :(
ERR  *	[core cluster]	[8] died :(
ERR  *	[core cluster]	[9] died :(
`
I downgraded nodejs to version 14 (from 15).  I can't find anything being logged to indicate what's not working.  lournalctl just shows all of those core cluster died lines.  I have also done this manually, with and without the production environment variable.  Neither gives more information.

Any idea what I've missed?

**Comment by Johann150** [comment]
Have you tried upgrading Nodejs to version 16?

**Comment by tamaina** [comment]
Close due to prolonged neglect.
