### ISSUE TITLE
データ移行する時などのためにMisskeyの概ね必要とされるであろう全データをエクスポートするスクリプトを用意

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#761]
サイズが大きくなりすぎるのでドライブのファイル情報は含まれない(あらかじめユーザーにデータが消えることを告知して重要なファイルはダウンロードしておいてもらうなどの対策が必要か)
プライベートなメッセージ情報も含めない方が良いかも

**Comment by rinsuki** [comment]
どちらかというと利用者側に自分の全投稿等をダウンロードできる機能を提供した方がいいのでは
