### ISSUE TITLE
Renoteされた時刻が投稿された時刻のように表示される

### ISSUE THREAD

**Issue by SanMurakami** [misskey-dev/misskey#7620]
![image](https://user-images.githubusercontent.com/37681609/129052251-1bf151a3-0529-4f33-bcc0-b9325cb1564b.png)

## 💡 Summary

Renoteされた時刻が投稿された時刻のように表示される

## 🙂 Expected Behavior

投稿された時刻が表示される

## ☹️ Actual Behavior

Renoteされた時刻が表示される

## 📝 Steps to Reproduce

1. 投稿する
2. Renoteする
3. Renoteされた通知を通知から開く

## 📌 Environment

Misskey.io v12.84.3

**Comment by rinsuki** [comment]
Related https://github.com/misskey-dev/misskey/issues/7060
