### ISSUE TITLE
ARM64 Support for Self-building Docker Image

### ISSUE THREAD

**Issue by AMoonRabbit** [misskey-dev/misskey#7626]
## 💡 Summary

Pi4BとドッカでMISSKEYをインストールをしました。でも、アップデートをしたい時、マニフェストのLinuxとアーム６４とｖ８がありませんでしたからｖ１２．８７のウェブを建てて失敗しました。

I have Misskey installed on a Pi4B with Docker. When I tried to update, the web build failed because there was no manifest for linux, arm64, or v8.

`ERROR: Service 'web' failed to build: no matching manifest for linux/arm64/v8 in the manifest list entries`

## 📝 Steps to Reproduce

1. Try to update instance on arm based hardware to 12.87
2. Get build error for web component.

## 📌 Environment

OS: Ubuntu 20.04.2 LTS aarch64
Host: Raspberry Pi 4 Model B Rev 1.4
Kernel: 5.4.0-1041-raspi
CPU: BCM2835 (4) @ 1.500GHz
Memory: 3371MiB / 7811MiB

**Comment by AMoonRabbit** [comment]
I think with the release of 12.87.1, this has been resolved. I was able to successfully build 12.87 without the error reported. Thank you.

**Comment by rinsuki** [comment]
it seems still not supported

```
$ docker run --rm -it misskey/misskey:12.110.0 sh
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
/misskey # uname -a
Linux 99e95b9ef247 5.10.104-linuxkit #1 SMP PREEMPT Wed Mar 9 19:01:25 UTC 2022 x86_64 Linux
/misskey #
```

**Comment by rinsuki** [comment]
it is different issue; this is for building, my issue is pre-built image. sorry for pinging

**Comment by tamaina** [comment]
This issue is talked about self-building.

FYI: There is PR about docker hub image: #8279
