### ISSUE TITLE
TypeError: Cannot read property 'removeItem' of undefined

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7631]
## 💡 Summary

Unable to delete files. Getting error message

## 🙂 Expected Behavior

Item should be removed after selecting delete

## ☹️ Actual Behavior

TypeError: Cannot read property 'removeItem' of undefined

## 📝 Steps to Reproduce

1. Login as admin
2. From the menu, visit /instance/files
3. Select remote file, then choose delete

## 📌 Environment

Misskey 12.87.0 PostgreSQL 10.15

**Comment by syuilo** [comment]
FYI: It actually deleted a file.
