### ISSUE TITLE
The follow-button does not cancel properly under a specific situation

### ISSUE THREAD

**Issue by blackskye-sx** [misskey-dev/misskey#7638]
## 💡 Summary

When the remote user is on an instance that is down or there is some other delayed connection between the remote and local instances, the follow-button for the local user does not display properly when cancelling a follow request.  While the follow-button is displaying "Processing", after clicking once or several times, the button continues displaying "Processing".

On the backend, for the server side, the event has properly cancelled the follow request. The front end is not updating properly.

For an end user who doesn't understand the issue, they may click the "Processing" button several times and not realize that the cancelled event has occurred. And by clicking "Processing" repeatedly, the user is sending a random number of requests to follow and unfollow without a  proper update on the front end.  

## 🙂 Expected Behavior

For a remote user who is on an instance that is down or delayed, and the local user has clicked "Follow", 
While the follow-button is displaying "Processing", the local user will click once and the button turns back into "Follow".

## ☹️ Actual Behavior

While the follow-button is displaying "Processing", the local user will click once or several times, the button continues displaying "Processing".

## 📝 Steps to Reproduce

To recreate the issue, we need a user on a server that is down. We can use @disney@birdsite.skye.cx while logged in at https://misskey.io
To recreate this from different instance, birdsite.skye.cx may not work. You would need a different server that is currently down but has previously federated with the instance. And a user from that down server.

1. From the front end of misskey, open the search box and enter @disney@birdsite.skye.cx  (you may need to refresh once more due to "error, try again").
2. Click "Follow" once. The button will turn into "Processing"
3. Wait a few seconds. 
4. Click "Processing" *once* to cancel the attempt to follow. The button will remain as "Processing".  Note; on the backend, the local instance has cancelled the request to follow, but the front end/client ui has not properly refreshed. 
5. Reload the page and the button will now say "Follow".

## 📌 Environment

Misskey 12.83 thru 12.87
May not be limited to these client versions. 

##  Proposed solution

This is working for me on my instance; 
within the file; src/client/components/follow-button.vue
between lines 112 and 113, add a line;
						this.hasPendingFollowRequestFromYou = false;						

@@ -110,6 +110,7 @@ export default defineComponent({
						await os.api('following/requests/cancel', {
							userId: this.user.id
						});
						this.hasPendingFollowRequestFromYou = false;						
					} else if (this.user.isLocked) {
						await os.api('following/create', {
							userId: this.user.id

**Comment by Johann150** [comment]
I think the problem is that the button does not listen to the message the server sends when the follow request is cancelled:
https://github.com/misskey-dev/misskey/blob/b5cadeca2e02f88d46625f27c3fcc796e45c2526/src/services/following/requests/cancel.ts#L35

The follow button component only listens to `follow` or `unfollow`:
https://github.com/misskey-dev/misskey/blob/b5cadeca2e02f88d46625f27c3fcc796e45c2526/src/client/components/follow-button.vue#L75-L78

I think that it would be too much if the follow button had to listen to all `meUpdated` messages. Perhaps more sensible would be to additionally send an appropriate `unfollow` message (or a new `followCancelled` message, I do not know where else the `unfollow` message is used) as is done for unfollowing:
https://github.com/misskey-dev/misskey/blob/bb6cd258f3b811cd10bdd2618af7e24c65d2549b/src/services/following/delete.ts#L34-L35

**Comment by blackskye-sx** [comment]
Just to be clear, you're right about everything you say, but the solution is to add one line to follow-button.vue. I documented it in the original bug report at the end. I already added it to my own fork and it works perfectly. That line is already used elsewhere in the file, but it's used for =true. In this scenario, =false is more appropriate.

**Comment by Johann150** [comment]
Yes, your solution works too.
It is a matter of if you want to be technically correct if the server actually cancelled the follow request. Your way can be confusing in edge cases. For example if Misskey is temporarily unavailable but you still have the page cached.

**Comment by blackskye-sx** [comment]
Understood. Thanks.
