### ISSUE TITLE
migrationを軽くしてほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#7639]
## Summary
migrationは少なくとも1GBのメモリを要求するので、廉価なコンピュートインスタンスとかだと実行が厳しい。

別にスワップを追加すればいいと言えばそれまでなんですが、Docker Hubのおかげでビルド不要で起動できるのに、結局マイグレーションのときにスワップを追加することになるので、migrationさえ軽ければと思ってしまいます。

もしかしたらts-nodeで実行しないようにすれば軽くなるのかも

**Comment by mei23** [comment]
ここんとこに`.js`加えて
https://github.com/misskey-dev/misskey/blob/53f55defda9129baeb15f023050b63148d400940/ormconfig.js#L13

migration作成時に`-o`で`.js`で吐かせるだけで良さそう
```
npx ts-node ./node_modules/typeorm/cli.js migration:generate -o -n 変更の名前
```
JSコードをガリガリ書くなら`.ts`にしたいかもしれないけど、
実際ベタクエリを流してるだけなのでわざわざ.tsでpublishするメリットもなさそう。

**Comment by mei23** [comment]
あーマイグレーション時ののts-nodeをやめないと早くならないか…

既存の.tsを全部.jsにして、新規も.jsで作成するようにして、
実行時にts-nodeを使わないようにすればたしかに速そう

**Comment by rinsuki** [comment]
開発中にビルド結果を参照すると tsc -w 中にリネームしたファイルが二重にひっかかってうざいので NODE_ENV == production の時だけビルド結果を使ったほうがいいかも

**Comment by tamaina** [comment]
軽くなったんじゃない？

**Comment by syuilo** [comment]
> あーマイグレーション時ののts-nodeをやめないと早くならないか…
> 
> 既存の.tsを全部.jsにして、新規も.jsで作成するようにして、 実行時にts-nodeを使わないようにすればたしかに速そう

これはもうやったわね

**Comment by tamaina** [comment]
軽くなったと思うけどどうだろうか

**Comment by tamaina** [comment]
軽くなったよなぁ(いま一番重たいのはyarn installとviteかな)
