### ISSUE TITLE
スマホでウィンドウを閉じれない

### ISSUE THREAD

**Issue by futchitwo** [misskey-dev/misskey#7643]
## 💡 Summary

スマホでウィンドウを表示しているとき、閉じるボタンをタップしてもウィンドウを閉じることができない

## 🙂 Expected Behavior

ウィンドウが閉じる

## ☹️ Actual Behavior

ウィンドウが閉じない

## 📝 Steps to Reproduce

1.スマホのMisskeyで何らかのページをウィンドウで開く
2.右上の閉じるボタンをタップする

## 📌 Environment

Misskey  12.87.0
Chrome Android, Chrome Firefox, Chrome Windows　(開発者モードのモバイル表示)

**Comment by syuilo** [comment]
既に修正されています🙏
