### ISSUE TITLE
アンテナのノート保存上限を導入する

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#7644]
## Summary

データベースサイズ肥大化の一因になる
アンテナを相当過去まで遡りたいユースケースは少なさそうなので、例えば直近100ノートまでのように制限しても良さそう
ただレコード挿入のたびにレコード数がオーバーフローしているかどうか、そしてしているなら最も古いレコードを削除、という処理が発生するので負荷が高まるかも？

**Comment by tamaina** [comment]
インスタンス内で上限を共有すれば多少は負荷軽そう……と思ったけど「最も古いレコードを削除する」という処理自体を毎回やるのがきついか

**Comment by syuilo** [comment]
定期的に古いレコードを削除するようになった
