### ISSUE TITLE
DeepL translation feature does not appear to work with a DeepL Pro account

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#7648]
## 💡 Summary

The DeepL translation feature does not appear to work with a Pro API key.

## 🙂 Expected Behavior

Translating a Note should work.

## ☹️ Actual Behavior

Nothing happens on the UI. The server returns the following error:
```
[api]        Internal error occurred in notes/translate: Cannot read property '0' of undefined
```

## 📝 Steps to Reproduce

1. Purchase a DeepL Pro subscription (I can help debug this if needed)
2. Enter API key in Misskey instance settings
3. Attempt to use the translation feature with any Note

## 📌 Environment

openSUSE Tumbleweed, Node.js 16.6.0, Misskey 12.88.0

**Comment by Candinya** [comment]
DeepL API Pro have different API endpoint from DeepL API Free, you may change `https://api-free.deepl.com/v2/translate` in `src/server/api/endpoints/notes/translate.ts` to pro's endpoint. If return parameters are different, you may need to manually edit some settings (I don't know exactly)
An editable endpoint (may with default value / selection) might be better.

**Comment by syuilo** [comment]
> An editable endpoint (may with default value / selection) might be better.

I'll try to do that.

**Comment by syuilo** [comment]
Considering the possibility that the format of requests and responses may change between free and pro in the future (although I don't think so), it may be better to implement a flag to indicate whether an account is pro or not.
