### ISSUE TITLE
背景色がおかしい

### ISSUE THREAD

**Issue by futchitwo** [misskey-dev/misskey#7649]
## 💡 Summary

背景色が -bg であるべきところが -panel になっている
pagesの一覧画面やハイライトなどではよくわかるように、背景とパネルの区別がつかない
デフォルトUIではあまり気にならない部分もあるが、ウィンドウやpope UIでは目立つ

## 🙂 Expected Behavior

背景色が -bg

## ☹️ Actual Behavior

背景色が -panel

## 📝 Steps to Reproduce

ハイライト、Pagesの一覧などを開く
（ほとんどのページで起こるが、ここが多分わかりやすい）

## 📌 Environment

Misskey　v.12.87.0　v.12.88.0

**Comment by syuilo** [comment]
一応意図したもの
見にくくなっている部分に関しては直します

**Comment by futchitwo** [comment]
https://github.com/misskey-dev/misskey/commit/ded0f6f0dfd68f448d3026163c76d9fcb83eb4f9 で根本的な修正されたっぽい
