### ISSUE TITLE
タイムラインで pope UI が デフォルトUI の見た目になっている

### ISSUE THREAD

**Issue by futchitwo** [misskey-dev/misskey#7650]
## 💡 Summary

pope UI でタイムラインを表示したとき、タイムラインがデフォルトUI の見た目で表示される
pope UI は横幅が広いので、チャットUIのようでもある

## 🙂 Expected Behavior

タイムラインが pope UI のスタイルで表示される

## ☹️ Actual Behavior

タイムラインが デフォルト UI のスタイルで表示される

## 📝 Steps to Reproduce

pope UI でタイムラインを開く

## 📌 Environment

misskey v.12.88.0

**Comment by syuilo** [comment]
戻した
