### ISSUE TITLE
ESmodulesに移行

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#7658]
## Summary

node向けのライブラリもes modulesを使用するものが増えてきて、commonjsだと使えないため

### やることリスト

- [x] ディレクトリインポートを直す
- [x] 拡張子省略しない
- [x] requireをimportにする
- [x] jsonをimportしている箇所をどうにかする
  - `--experimental-json-modules`
- [x] `__dirname`を置き換える
  - https://stackoverflow.com/a/64383997
- [x] デコレータがなんか動かないのを何とかする
- [x] use the [node: protocol](https://nodejs.org/api/esm.html#esm_node_imports) for imports
- [x] Add "type": "module" to your package.json
- [x] autobind-decorator の代替を考える
- [ ] テストが動かないのをどうにかする

ref. https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by syuilo** [comment]
ESMだとディレクトリインポートができないみたい

例えば
``` js
import boot from './boot';
```
は
``` js
import boot from './boot/index.js';
```
に書き換える必要がある

**Comment by syuilo** [comment]
(そんなのTypeScriptコンパイラーがよしなにやってほしい)

**Comment by syuilo** [comment]
あー、あとそもそも拡張子省略できない

**Comment by syuilo** [comment]
死ぬほど大変じゃん

**Comment by syuilo** [comment]
とても大変ということが分かったので、ESMに移行するのは一旦諦め、CJSに対応している古いバージョンのライブラリを使い続けていくことにする

**Comment by rinsuki** [comment]
なんか単純置換でいけそうな気もする

**Comment by syuilo** [comment]
ふーむ

**Comment by syuilo** [comment]
あるインポートがローカルのファイルを指しているのかパッケージを指しているのか区別が難しい場合もあるかもしれないけど、ほとんどは置換でいけるか…？

**Comment by syuilo** [comment]
多分ほとんどのローカルのインポートは./とかで始まってる気がするからいけるかも

**Comment by rinsuki** [comment]
ローカルのファイルは基本 @/ or ./ or ../ から始まるはず

**Comment by mei23** [comment]
> node向けのライブラリもes modulesを使用するものが増えてきて、commonjsだと使えないため

例えばどれだわ？

**Comment by syuilo** [comment]
pureimageとかis-rootとか

**Comment by syuilo** [comment]
jsonをrequireしてる箇所ってどう置き換えれば良いんだろ

https://stackoverflow.com/questions/34944099/how-to-import-a-json-file-in-ecmascript-6

によると将来的には出来るようになるらしいけど

**Comment by syuilo** [comment]
`import * as foo from './foo.json';`って書けばTypeScriptがよしなにやってくれるっぽい

**Comment by syuilo** [comment]
いや嘘
やってくれなかった

**Comment by syuilo** [comment]
現時点での移行は難しいかも

**Comment by mei23** [comment]
あんまりCommonJSで動かないモジュールって記憶になくて

pureimageは 0.3.3 >= は本当にdistフォルダがないから単に壊れてるだけかも
`Error: Cannot find module '.../node_modules/pureimage/dist/pureimage-umd.cjs'. Please verify that the package.json has a valid "main" entry`

is-rootはESM要求してるけど、そもそもrootチェックっていらないのではと。

**Comment by rinsuki** [comment]
というか is-root 中身は process.getuid() === 0 だしわざわざパッケージ使わなくてもよさそう

**Comment by syuilo** [comment]
is-rootたった3行しかなかった

**Comment by syuilo** [comment]
`--experimental-json-modules`付ければいけた
https://nodejs.org/api/esm.html#esm_experimental_json_modules

**Comment by syuilo** [comment]
`__dirname `は使えないっぽい

**Comment by syuilo** [comment]
https://stackoverflow.com/a/64383997

**Comment by syuilo** [comment]
あー、拡張子を.jsにするとts-nodeで直接ts動かす時にエラーになるな

**Comment by syuilo** [comment]
👀
https://github.com/TypeStrong/ts-node/issues/783

**Comment by syuilo** [comment]
うーんﾖｸﾜｶﾗﾝ

**Comment by marihachi** [comment]
これ止めといたほうが良い気がする
よっぽど依存モジュールが少なくないと厳しそう

**Comment by syuilo** [comment]
一旦pendingしてる
ただ https://github.com/misskey-dev/misskey/commit/b9cb6d1c10729869cbb57ce50c8174ad7474db75 で移行しやすいように準備はした

**Comment by syuilo** [comment]
やることリストupdated

**Comment by mei23** [comment]
> requireをimportにする

これやると物によってはdtsがないって怒られるようになるのが気になる

**Comment by syuilo** [comment]
node-fetch もESMしか提供しなくなったっぽい

**Comment by mei23** [comment]
https/node-fetch/gotが混在しているリクエスト系はなんとなくgotに集約しようとしてた。
node-fetchだと最終リダイレクト先のipが取れないのでSSRF避けがしにくいというのもあり。
https://github.com/misskey-dev/misskey/pull/7814
https://github.com/mei23/misskey/pull/3012

gotもそのうちESMになるかもだけどそれはそれで。

**Comment by syuilo** [comment]
TypeScript 4.5ではESMとしてトランスパイルできるようになるらしい

**Comment by syuilo** [comment]
さらにESMじゃないと読み込めないライブラリが増えてきた

**Comment by mei23** [comment]
↓が改善するからTypeScript 4.6まで待って的なことたまにモジュールのリリースノートで見るけど
https://github.com/microsoft/TypeScript/issues/46452
結局4.6に入る様子がないんだわね…

**Comment by syuilo** [comment]
npmでインストールしたライブラリがCJSでもESMは使えるよね？そんなことない？

**Comment by syuilo** [comment]
もし依存ライブラリもすべてESMでないといけないとしたらESM移行は不可能そう

**Comment by syuilo** [comment]
> npmでインストールしたライブラリがCJSでもESMは使えるよね？そんなことない？

ESMで出力したら`TypeError: redisLock is not a function`が出るようになったため

**Comment by syuilo** [comment]
> > npmでインストールしたライブラリがCJSでもESMは使えるよね？そんなことない？
> 
> ESMで出力したら`TypeError: redisLock is not a function`が出るようになったため

`import * as redisLock from 'redis-lock';` を `import redisLock from 'redis-lock';` にしたら直った

**Comment by syuilo** [comment]
```
C:\Users\ai\projects\misskey\packages\backend\node_modules\reflect-metadata\Reflect.js:553
                var decorated = decorator(target, propertyKey, descriptor);
                                ^

TypeError: decorator is not a function
    at DecorateProperty (C:\Users\ai\projects\misskey\packages\backend\node_modules\reflect-metadata\Reflect.js:553:33)
    at Reflect.decorate (C:\Users\ai\projects\misskey\packages\backend\node_modules\reflect-metadata\Reflect.js:123:24)
    at __decorate (file:///C:/Users/ai/projects/misskey/packages/backend/built/services/chart/core.js:8:92)
    at file:///C:/Users/ai/projects/misskey/packages/backend/built/services/chart/core.js:508:1
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
```
が出るわね

**Comment by syuilo** [comment]
[autobind-decorator](https://github.com/andreypopp/autobind-decorator)がES2020に対応してないっぽい？

**Comment by syuilo** [comment]
> [autobind-decorator](https://github.com/andreypopp/autobind-decorator)がES2020に対応してないっぽい？

決して手動bindするか

**Comment by syuilo** [comment]
TypeORMデコレータ多用してるけど大丈夫なのかしら

**Comment by syuilo** [comment]
> [autobind-decorator](https://github.com/andreypopp/autobind-decorator)がES2020に対応してないっぽい？

reflect-metadataに依存してるのはautobind-decoratorじゃなくてTypeORMだった

**Comment by syuilo** [comment]
:tasukete:

**Comment by syuilo** [comment]
> npmでインストールしたライブラリがCJSでもESMは使えるよね？そんなことない？

ライブラリによっては型として正しいimport方法と実際に動くimport方法が異なる場合が発生するな

**Comment by syuilo** [comment]
> ```
> C:\Users\ai\projects\misskey\packages\backend\node_modules\reflect-metadata\Reflect.js:553
>                 var decorated = decorator(target, propertyKey, descriptor);
>                                 ^
> 
> TypeError: decorator is not a function
>     at DecorateProperty (C:\Users\ai\projects\misskey\packages\backend\node_modules\reflect-metadata\Reflect.js:553:33)
>     at Reflect.decorate (C:\Users\ai\projects\misskey\packages\backend\node_modules\reflect-metadata\Reflect.js:123:24)
>     at __decorate (file:///C:/Users/ai/projects/misskey/packages/backend/built/services/chart/core.js:8:92)
>     at file:///C:/Users/ai/projects/misskey/packages/backend/built/services/chart/core.js:508:1
>     at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
>     at async Loader.import (node:internal/modules/esm/loader:178:24)
>     at async Object.loadESM (node:internal/process/esm_loader:68:5)
>     at async handleMainPromise (node:internal/modules/run_main:63:12)
> ```
> 
> が出るわね

autobind消したら出なくなった

**Comment by syuilo** [comment]
起動しようとするとエラーは出なくなったけど起動しない

**Comment by syuilo** [comment]
> 起動しようとするとエラーは出なくなったけど起動しない

直った

**Comment by syuilo** [comment]
一応起動するとこまでは来た

**Comment by syuilo** [comment]
autobind消したから、this周りの不具合が発生するはずなので何か対策考えないと

**Comment by syuilo** [comment]
https://github.com/misskey-dev/misskey/tree/esm

**Comment by syuilo** [comment]
うーむ
- https://stackoverflow.com/questions/56503531/what-is-a-good-way-to-automatically-bind-js-class-methods
- https://medium.com/@charpeni/arrow-functions-in-class-properties-might-not-be-as-great-as-we-think-3b3551c440b1

**Comment by syuilo** [comment]
> autobind消したから、this周りの不具合が発生するはずなので何か対策考えないと

おとなしく`this.foo = this.foo.bind(this)`をコンストラクタに書くようにした

**Comment by syuilo** [comment]
テストが動かない問題を解決した人に¥3000進呈

**Comment by Johann150** [comment]
A lot of calls to `os.popup` still use `import(...)`.

**Comment by tamaina** [comment]
> A lot of calls to os.popup still use import(...).

Is this a standard feature of esmodules...? @Johann150
