### ISSUE TITLE
みつける(explore)が壊れている

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#7659]
![vvrv](https://user-images.githubusercontent.com/28042693/130018483-ebe0e514-b0fa-4714-a919-b7126e3a2ac4.png)

## 💡 Summary

みつけるの画面でピン留めユーザー以外が正しく表示されておらずエラーになる

## 📝 Steps to Reproduce

1.みつける (/explore)を開く

## 📌 Environment

Misskey 12.88.0

**Comment by tamaina** [comment]
Duplicate of #7656
