### ISSUE TITLE
built/meta.jsonが{ "version": "unknown" }になる

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#7671]
## 💡 Summary
meta.jsonの内容が

```
{
    "version": "unknown"
}
```

になる。

**Webpackで生成したものを誰かが勝手に上書きしている？？？**

こうなってしまうとクライアントが読み込めない。

## 🙂 Expected Behavior
package.jsonで指定したバージョンが入る

## ☹️ Actual Behavior
unknown

## 📝 Steps to Reproduce

1. NODE_ENV=production npm run build
2. built/meta.jsonの内容を確認
3. unknown

## 📌 Environment
Misskey@1ffee15

**Comment by tamaina** [comment]
VS Codeを見ていると、build-webpackでは正しい値になるがbuild-tsでなぜかunknownに置き換わってしまう

**Comment by syuilo** [comment]
あー

**Comment by syuilo** [comment]
jsonをインポートしてるからTypeScriprコンパイラがコンパイルしちゃうのか

**Comment by tamaina** [comment]
package.jsonを読むのではいけないの？

**Comment by syuilo** [comment]
package.jsonだとビルドしてなくてもバージョン変わっちゃうからな

**Comment by syuilo** [comment]
例えばMisskey v99の状態でMisskey v100のコードをpullして、ビルドしてない状態で起動したら実際はMisskey v99なのにMisskey v100と判定される

**Comment by tamaina** [comment]
まあ確かにそういうケースはあるけど、かといって少ないような気も……

**Comment by rinsuki** [comment]
ビルドすっぽぬかしわりとありそうな気もする

**Comment by syuilo** [comment]
少ないけど、ちょっとでも可能性あるのはだめ
実際これが原因でクライアント起動しない事故とか起こってきたし

**Comment by syuilo** [comment]
`import('../meta.json').then(...)`形式で読み込めば回避できそう

**Comment by syuilo** [comment]
tscにjsonをemitしないオプションないのかな？

**Comment by syuilo** [comment]
> `import('../meta.json').then(...)`形式で読み込めば回避できそう

こうするとどうしても非同期になっていろんなところに影響が波及するから`fs.readFileSync`した方が良いかもしれない
