### ISSUE TITLE
While using browser inspector, loading Misskey causes 100% CPU load and over 30 seconds to load page

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7683]
## 💡 Summary

Very high cpu load and long load times for Misskey 12.89.0

## 🙂 Expected Behavior

Normal page load like Misskey 12.87.0

## ☹️ Actual Behavior

If you open main page https://www.example.com or a profile page https://www.example.com/@misskey while using browser inspector it will lock your computer with 100% cpu load

## 📝 Steps to Reproduce

1. open any Chrome based browser
2. open inspector
3. load any Misskey instance website with version 12.89.0

## 📌 Environment

Tried on three different Misskey instance version 12.89.0 using Chrome based browser with same results

**Comment by syuilo** [comment]
This is probably a bug in Chrome, as it is not reproduced in Firefox.

**Comment by okpierre** [comment]
> This is probably a bug in Chrome, as it is not reproduced in Firefox.

No problems when I tried the same steps for Misskey 12.88 and 12.87 - issue only exists for 12.89.x instances

**Comment by syuilo** [comment]
直ってる
