### ISSUE TITLE
クリーンビルドでバージョンアップした際、チャンク読み込みに失敗し、トラブルシューティングを選択してもトラブルシューティングのチャンク読み込みも失敗する

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#7686]
1. バージョンが上がっており、サーバーに存在しないチャンクの読み込みに失敗する

![image](https://user-images.githubusercontent.com/7973572/130547177-f11f0278-bf45-431c-acd5-54ff6e561003.png)

2. トラブルシューティングに移ってもチャンクの読み込みに失敗する

![image](https://user-images.githubusercontent.com/7973572/130547379-02429fb2-1a49-4b9d-94ec-0cb1ca05b78f.png)

めいめいはクリーンビルド否定派みたいだけれど、私はクリーンビルドしたい派なんですよね……。

トラブルシューティングへのリンクだけでなく、サーバーのバージョンを比較して「新しいバージョンがあります」と表示するとか、リロードボタンを付けるとかするのが親切かも。

## 📌 Environment
Misskey@12.89.0

**Comment by mei23** [comment]
> めいめいはクリーンビルド否定派みたいだけれど、私はクリーンビルドしたい派なんですよね……。

バージョンアップ頻度, 開発前提の環境なのか一般公開なのか, ユーザー数
などの状況によっては、基本クリーンビルドしないで運用するとUXが低下しにくいと言っただけ。
「クリーンビルド否定派」と言い切ると誤解を招く。

**Comment by tamaina** [comment]
うーん、やっぱり古いクライアントが実行され続ける方がUXが低下する気がするんだよな

バージョンアップまわりについては根本的に見直すとなると大掛かりな変更に…？そうするとしゅいろ案件になりそう

**Comment by mei23** [comment]
直近のクライアントをサポートすることを古いクライアントが実行され続けると拡大解釈しているのが意味不明

**Comment by mei23** [comment]
リロードしろって書いとけばいい話

**Comment by tamaina** [comment]
> 直近のクライアントをサポートすること

これは私が面倒だと思っているというだけで批判ではないのですが…（反対意見ではあるけど）

ストリームの切断と同じく「新しいバージョンがあります」的なのを右下に表示すればいいと思う

**Comment by mei23** [comment]
どっちもやっときゃいいんじゃないかしら
