### ISSUE TITLE
12.89.1 breaks custom CSS support

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#7689]
## 💡 Summary

After updating to 12.89.1, clients with custom CSS in local storage will fail to load the page correctly.

## 🙂 Expected Behavior

Page loads correctly.

## ☹️ Actual Behavior

An error message is displayed.
```
ERROR CODE: SOMETHING_HAPPENED_IN_PROMISE
[object PromiseRejectionEvent]
```

## 📝 Steps to Reproduce

1. Set custom CSS in user settings. Even something like `/**/` is enough.
2. Reload the page.

## 📌 Environment

Server: openSUSE Tumbleweed, Node 16.6.0, Misskey 12.89.1
Client: qutebrowser 2.3.1, QtWebEngine 5.15.5, based on 
Chromium 87.0.4280.144

**Comment by syuilo** [comment]
このコミットが原因っぽい
https://github.com/misskey-dev/misskey/commit/dad6a7764542d125c8e3ee41c195fd732c3973f5
