### ISSUE TITLE
websocketかwsかどっちか一方にする

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#7690]
websocketとws両方使ってるの同じようなライブラリを両方使ってるのは微妙なのでどっちかにしたい

https://github.com/misskey-dev/misskey/blob/f84483896edeb1f8655175b77d35ecd49f6e1985/package.json#L243-L244

今はサーバーでwebsocketを使っててテストでwsを使ってるっぽいので、特にテストでwsを使う必要性がなければテスト側をwebsocketに寄せる？

**Comment by tamaina** [comment]
Resolved
