### ISSUE TITLE
Failed to load page error message when opening browser

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7697]
## 💡 Summary

Failed to load page error message

![misskeyfailedtoloadpage](https://user-images.githubusercontent.com/1679025/130664862-7ff6ed76-552d-49c1-942f-b6cb56956df3.jpg)

## 🙂 Expected Behavior

No error

## ☹️ Actual Behavior

When visiting page this error pops up

## 📝 Steps to Reproduce

1. Not sure how to reproduce
2. It does not appear again after refresh of browser

## 📌 Environment

Misskey 12.89.0  Firefox 91.0.1 (64-bit)

**Comment by okpierre** [comment]
## **Now getting this when visiting syuilo profile**

![misskeysyuilo](https://user-images.githubusercontent.com/1679025/130834739-d52db994-603c-4239-8c25-10b863ef6a86.png)

**Comment by sousuke0422** [comment]
Duplicate #7686 ?

**Comment by Johann150** [comment]
Since you said it worked after a reload and the error screen also specified to clear the browser cache, and also the other linked issue, I would consider this fixed.
