### ISSUE TITLE
Clear cache button not working

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7698]
## 💡 Summary

Clear cache button not working for changes

Clear browser cache is working

## 🙂 Expected Behavior

Clear cache as per troubleshooting guide
---
![misskeyclearcache](https://user-images.githubusercontent.com/1679025/130665817-345343dd-f159-4f5f-8f3c-15b29f5a503d.jpg)

## ☹️ Actual Behavior

UI changes remain the same after clear cache

## 📝 Steps to Reproduce

1. make a small change to test
2. clear cache button (see picture above)
3. view page (not working)
4. clear browser cache
5. view page (working)

## 📌 Environment

Misskey 12.89.0 nginx

**Comment by Johann150** [comment]
If you are using the nginx configuration that comes with Misskey (i.e. [`docs/examples/misskey.nginx`](https://github.com/misskey-dev/misskey/blob/develop/docs/examples/misskey.nginx)), there is an additional layer of caching by nginx which would have to be cleared out with e.g. `rm -rf /tmp/nginx_cache/*`

**Comment by okpierre** [comment]
Do you know if it uses both Misskey cache and also nginx cache at the same time?

**Comment by cliqsocial** [comment]
> If you are using the nginx configuration that comes with Misskey (i.e. [`docs/examples/misskey.nginx`](https://github.com/misskey-dev/misskey/blob/develop/docs/examples/misskey.nginx)), there is an additional layer of caching by nginx which would have to be cleared out with e.g. `rm -rf /tmp/nginx_cache/*`

Does the nginx confguration doc need to be updated? Additional layer of caching sounds like a conflict.

**Comment by Johann150** [comment]
The idea is that if you upgrade to a newer version, what nginx caches will not affect the new version, because it will use other files. If you notice for example, all JS files have the version in them, e.g. `assets/app.12.89.2.js`. However this might be an issue if you are e.g. developing or working on misskey and recompile without changing the version.

**Comment by tamaina** [comment]
> make a small change to test
> UI changes remain the same after clear cache

Your problem is not about themes, so don't refer to "Parts of the UI are weird".
