### ISSUE TITLE
Picture compression function

### ISSUE THREAD

**Issue by KormiMeiko** [misskey-dev/misskey#7704]
## Summary
I hope you can add a compressed file size function to the image upload

**Comment by Johann150** [comment]
I think if you want to compress the file, you should do it before uploading. If Misskey has to compress the file, it could be complicated.

**Comment by tamaina** [comment]
I think it would be useful, since continuously uploading large images can stress drive space.

**Comment by tamaina** [comment]
Maybe there should be an option to save only the webpublic and not the original.

**Comment by KormiMeiko** [comment]
> I think it would be useful, since continuously uploading large images can stress drive space.
I agree with this view very much!
There may be another way:
https://github.com/misskey-dev/misskey/issues/7732

**Comment by KormiMeiko** [comment]
> I think if you want to compress the file, you should do it before uploading. If Misskey has to compress the file, it could be complicated.

Maybe so, but I just want to have this function to make it as convenient as possible for community users~

**Comment by Johann150** [comment]
> continuously uploading large images can stress drive space

There is a drive size limit. So users should pay attention to how much space they have left. And then they hopefully notice that it may not be much and know to upload smaller images. It is easy to do using e.g. Paint and resizing the image to a smaller size.

> I just want to have this function to make it as convenient as possible for community users~

If it is easy for community users, then it is probably hard for developers.
Also it might be hard on the servers CPU, unless it is done with JavaScript. But using JS for this sounds like a bad idea to me.

**Comment by tamaina** [comment]
> hard on the servers CPU

Even now, Misskey servers always compresses the file when the image is uploaded.  
(As for remote images, it depends on the instance settings.)

**Comment by mei23** [comment]
クライアントで変換してあげるといい感じになる。
実装上はcanvas展開してブラウザでjpg変換しているので、変換もアップロードも速くなる。
https://github.com/mei23/misskey/blob/0df470cb0cc9269960a70cf043f4e116872ad58a/src/client/app/common/views/components/uploader.vue#L41-L53
https://github.com/mei23/misskey/blob/0df470cb0cc9269960a70cf043f4e116872ad58a/src/client/app/common/views/components/uploader.vue#L69-L70
※ただこれiOSあたりでorientationがおかしくなる疑惑あり
