### ISSUE TITLE
Favicon broken icon for certain pages

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#7707]
## 💡 Summary

Favicon logo is broken

![misskeyfaviconlogo](https://user-images.githubusercontent.com/60059665/130893758-896ddead-7a0f-482d-827f-6a243decb0cf.png)

similar issue reported here but closed 
https://github.com/misskey-dev/misskey/issues/7332

## 🙂 Expected Behavior

No broken image

## ☹️ Actual Behavior

Once you refresh the page in Notifications or Drive the logo is broken

## 📝 Steps to Reproduce

First you need to add your favicon then

1. Go to Timeline then click Drive then refresh page
2. Broken favicon
3. Go back to Timeline, refresh page and no problem
4. Go to Notifications, refresh page
5. Broken favicon

## 📌 Environment

misskey 12.89.0 - nginx 1.21.1 - node 12.22.5 - postgresql v13.4

**Comment by cliqsocial** [comment]
Was able to capture the issue with the help of an eagle eye community member 
https://cliq.social/notes/8pxcjbtfp4

This is what it looks like:
![misskeyfilepath](https://user-images.githubusercontent.com/60059665/131202821-c37038f7-417d-4fb0-843c-5fc9e68b65a6.png)

The favicon is pointing to wrong URL `/my/files/xxxxxx` and should be going to `/files/xxxxxx`

Problem:
/my/notifications
/my/messaging
/my/drive

No problem:
/gallery
/featured
/explore
/announcements
/settings
/instance

**Comment by okpierre** [comment]
Check the URL in case you recently switched path of files to S3 storage

Also verify you use `/` in the beginning or it will pick up the path of `/my/`
