### ISSUE TITLE
I want to process data around the drive as a Stream instead of storing the data in storage.

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#7711]
ドライブまわりの処理データはデータをストレージに保存せずStreamのまま渡すようにしたい

- /filesなどのリモートのプロキシは一旦DLしてから再送されるのでラグが発生する（リモートのファイルを保持するのは微妙かなと）
- ストレージの負荷も減る

**Comment by syuilo** [comment]
なんか理由があったかもしれないけど、今は状況が変わってるかもしれない

**Comment by mei23** [comment]
その辺、本当は正常なファイル終端か途中で切断されたか検出しないといけなくて
https://github.com/mei23/misskey/blob/f08f67f0dc338714c47ac3ab635ac66adf3ebbc8/src/misc/download-url.ts
streamで渡すだけで完結させようとするとなんかめんどい

**Comment by tamaina** [comment]
複雑な処理が多くてBufferを多用することになりそう…んー

**Comment by tamaina** [comment]
あ、for-awaitとかですべてメモリにロードする処理は禁止にしないとヤバいな

**Comment by tamaina** [comment]
> 複雑な処理が多くてBufferを多用する

(真面目にStreamを使わってないからのような気がしてきた

**Comment by tamaina** [comment]
結論: tmpfs使え

**Comment by tamaina** [comment]
あー、複雑な処理はともかく、ダウンロードして即再送するような場面はStreamを使うようにするのは有意義ではあるか

**Comment by tamaina** [comment]
filesのリモートプロキシ動作は動画等の大きいファイルだとラグが大きいのでやっぱこれやりたい

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/207841144-bc2ce0e7-bc06-4130-83dd-f43f114261f8.jpeg)

**Comment by tamaina** [comment]
Gotは(web) fetchに置き換えてよい？

**Comment by tamaina** [comment]
→ #8522
