### ISSUE TITLE
私の投稿の復活

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#7721]
## Summary

プロフィールページにおける「私の投稿」(Renoteを除く純粋な投稿のみを表示させる機能)を復活させる。

**Comment by tkmrgit** [comment]
https://github.com/misskey-dev/misskey/commit/ce1218a2b27cb8208019ad3697f54b459fee63bd
ようやく復活する模様。2021年08月から2年1ヶ月

**Comment by syuilo** [comment]
done
