### ISSUE TITLE
Webクライアントのウィジェットの設置状態をサーバーが記憶するようにする

### ISSUE THREAD

**Issue by tkmrgit** [misskey-dev/misskey#7724]
## Summary

v11までのWebクライアントではウィジェットの設置状態が記憶されていたが、v12では記憶されなくなっているため。
違う環境でログインした際に配置をし直さなければならず、とても不便なため。

**Comment by syuilo** [comment]
してなかったっけ

**Comment by tkmrgit** [comment]
> してなかったっけ

デッキではされているけど、他のUIではされていないと思われる

**Comment by tkmrgit** [comment]
![fwffrw](https://user-images.githubusercontent.com/28042693/131140712-2e6e7868-cf6a-4fb9-a0e7-0903706e3303.png)
左：デフォルトUIでそのままログインした場合の第2環境 / 右：デフォルトUIでそのままログインした場合の第1環境

ウィジェットにサーバーメトリクスを追加しているが反映されていない

**Comment by tamaina** [comment]
これはwhere: 'account'にしても問題ない気がするけどどうかしら

**Comment by tamaina** [comment]
placeがおかしいことになりそう…？  
絶対に`right`か`left`を入れるようにして、nullにしているような場所では`right`にする、みたいな感じにするべきかも
