### ISSUE TITLE
Whole station data export function

### ISSUE THREAD

**Issue by KormiMeiko** [misskey-dev/misskey#7726]
## Summary
A whole station data export function is added to facilitate the backup and migration of software content (under special circumstances)

This function can export the user data, network disk data, post data, site configuration, etc. of the whole station

**Comment by Johann150** [comment]
You can already easily make a backup like this:
```
systemctl stop misskey

pg_dump misskey > backup.sql
tar -czf backup.tar.gz backup.sql $MISSKEY_DIR/files

systemctl start misskey
```
`$MISSKEY_DIR` has to be replaced with the directory where misskey is installed, then the backup will be `backup.tar.gz`. Of course you also have to adjust other things slightly if for example your database has a different name.

On the other hand, adding a backup functionality into the web interface may create security issues, because the whole database can be exported.

**Comment by KormiMeiko** [comment]
> You can already easily make a backup like this:
> 
> ```
> systemctl stop misskey
> 
> pg_dump misskey > backup.sql
> tar -czf backup.tar.gz backup.sql $MISSKEY_DIR/files
> 
> systemctl start misskey
> ```
> 
> `$MISSKEY_DIR` has to be replaced with the directory where misskey is installed, then the backup will be `backup.tar.gz`. Of course you also have to adjust other things slightly if for example your database has a different name.
> 
> On the other hand, adding a backup functionality into the web interface may create security issues, because the whole database can be exported.

This is really a good way.

But I think if this function is made into a graphical interface, it can better facilitate users.

I think it is convenient for users who use docker to run misskey.

0.0

**Comment by Johann150** [comment]
> But I think if this function is made into a graphical interface, it can better facilitate users.

Convenience comes at a price and I think it could be very dangerous to expose the entire database on the graphical UI. And only admins should make a backup of all data of the instance, so it would only help a few people.

What would make more sense is to add some documentation how to make a backup. For example the commands I gave above.

> I think it is convenient for users who use docker to run misskey.

You can use the same commands in docker with `docker exec`, for example see this article: https://stackoverflow.com/questions/39210274/how-do-i-backup-a-database-in-docker#39211347

**Comment by Johann150** [comment]
If a break-in or security issue with Misskey ever allowed someone to gain admin privileges on an instance, this could already cause a lot of damage. But if we further enabled them to access a complete backup and thus the private keys used for HTTP signatures, this would even allow the attacker to impersonate all actors on the instance. Thus, as I already said above, this feature is too dangerous to ever implement. Making a backup should require having access to the machine the instance is running on, assuming this access can be protected much better (secure shell, VPN etc.).
