### ISSUE TITLE
File upload size limit function

### ISSUE THREAD

**Issue by KormiMeiko** [misskey-dev/misskey#7732]
## Summary
You can set a threshold for the upload size of files. If the threshold is exceeded, upload is not allowed.

You can also specify the upload size for specific file types (such as pictures, audio and video files).

**Comment by okpierre** [comment]
This would be a good feature for all instance admin to set for their community. 

Maybe something like: 
media upload limit: 5MB 

Then display message to user when file size is over limit when composing note and adding media

For now, if you use nginx you can set `client_max_body_size` but it's not user friendly way

**Comment by spirillen** [comment]
To those who stumble on this issue for manage file size... It is know ALSO a variable in the rules

![Image](https://github.com/user-attachments/assets/a97646eb-d505-4cd0-8aef-8ee1499dac5b)
