### ISSUE TITLE
Delete a user completely by admin

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#7735]
## Summary
現状、凍結はできるけどユーザーデータを消すことはできない  
（凍結→ユーザーのコンテンツを表示しようとするとエラーになる、リモートユーザーなら連合から投稿を受け付けなくなる）

リモートユーザーを物理削除すると再生成されてしまうので、そこはフラグテーブルで対処(?)

**Comment by mei23** [comment]
admin/delete-accoutを実装すればすぐじゃないかしら
> ほかのユーザーのリプライ・引用RNが消えてしまうのはまずいので、そこらへんは論理削除にする？

まずくない、まずいと思うならv11の時点で言うべきだわ

**Comment by tamaina** [comment]
> admin/delete-accoutを実装すれば

「アカウント物理削除」だと、リモートユーザーをまた拾ってきてしまう場合がありそう  
（なので投稿を削除してアカウント凍結処理しておけばよいという考え）

> まずくない

相手ユーザーが自発的に削除したのを受けて自分の投稿が消えるのと管理者削除の煽りで消えるのは違くない…？と思ったけどまあいっか

**Comment by mei23** [comment]
> 「アカウント物理削除」だと、リモートユーザーをまた拾ってきてしまう場合がありそう

2, 3周考えて、論理削除がない時点で… 凍結+Notes/Files削除しかないわね

**Comment by tamaina** [comment]
ん～…UsedUsernamesみたいに専用テーブルで削除したことだけを記憶しておくのも良いかも？  
(UsedUsernamesはsignupで全ユーザー名を記憶するものだけれど)

**Comment by mei23** [comment]
んー、論理削除がないばかりに… フラグテーブルが増えてくのもうーんだわ

**Comment by syuilo** [comment]
論理削除実装できないの？

**Comment by mei23** [comment]
してないだけだわ

**Comment by mei23** [comment]
いや、アカウントじゃなくて投稿消すだけなら別に普通のNotes削除でいいか

**Comment by tamaina** [comment]
ここで実現したいのはユーザーデータを消去してリモートユーザーの再登録を行わないことなので、物理削除+フラグテーブルが実装難易度的によさそうかなと…

**Comment by tamaina** [comment]
(ユーザーデータにドライブファイルとかもあるのを忘れていた)

**Comment by tamaina** [comment]
(タイトルと説明文をバッサリ変更しました

**Comment by tamaina** [comment]
リモートユーザーを物理削除するとローカルユーザーからのブロック/ミュート関係が忘れられてしまうことに気が付いた

**Comment by syuilo** [comment]
論理削除だとなんか問題あるのかしら

**Comment by tamaina** [comment]
ローカルユーザーを削除するとき論理削除だとGDPRが云々という話だったような

とりあえずローカルユーザー削除はユーザーが操作するアカウント削除と同じことをすればいいのではないかしら。  
リモートユーザーのことは後回しで。

**Comment by syuilo** [comment]
あー、勝手にこのIssueリモートユーザーの話かと思ってたけどローカルも含むのか

**Comment by syuilo** [comment]
ローカル: 物理(delete-accountと同じ)
リモート: 論理(delete-accountの、最後のアカウント物理削除するとこだけ抜かしたバージョン)で良いんでないかしら
