### ISSUE TITLE
Listen address を変更可能にする

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#7738]
## Summary
MisskeyのListen addressは、おそらくNode.js側のデフォルトの`::`や`0.0.0.0`になっているが、
https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback
広すぎる気がするので、デフォルトでは`127.0.0.1`にして、設定により変更できるようになどする。
→ デフォルトはそのままの方が良いかな

**Comment by mei23** [comment]
Dockerコンテナ内のMisskeyのListen addressの決め方がよくわからない。

**Comment by ledlamp** [comment]
Yes, please add a config option for the bind address.
はい、バインドアドレスのコンフィグオプションを追加してください。

**Comment by ledlamp** [comment]
> Dockerコンテナ内のMisskeyのListen addressの決め方がよくわからない。

Docker applications should listen on 0.0.0.0, but native applications should listen on 127.0.0.1.
Dockerアプリケーションは0.0.0.0をリッスンしますが、ネイティブアプリケーションは127.0.0.1をリッスンする必要があります。[deepl]

**Comment by ledlamp** [comment]
https://github.com/misskey-dev/misskey/blob/d35ad95c18a91f3733de4937dd11f162c2be3fe8/packages/backend/src/server/ServerService.ts#L198

do `fastify.listen({ port: this.config.port, host: this.config.host });`.

**Comment by ledlamp** [comment]
Actually, default `host` should be "::" or empty, so that it listens on both IPv4 and IPv6. If you specify `"0.0.0.0"`, it is not available on IPv6.
