### ISSUE TITLE
チャンネルへのノートのピン留め

### ISSUE THREAD

**Issue by futchitwo** [misskey-dev/misskey#7740]
チャンネルの仕様的なもの
- #6621

には書いてある機能
APIを叩くと`not function`と返ってきたのでコードを見てみると実際には空のファイルがおいてあるだけだった
https://github.com/misskey-dev/misskey/blob/develop/src/server/api/endpoints/channels/pin-note.ts

**Comment by futchitwo** [comment]
ファイル消えてた
機能としては有っていいと思うからcloseしません

**Comment by syuilo** [comment]
やるか
