### ISSUE TITLE
Problems with logging into an account.

### ISSUE THREAD

**Issue by MoeruIshiki** [misskey-dev/misskey#7757]
## 💡 Summary
When I try to sign in to my account, every time I do, all I see is a spinning circle loading screen. I can get into my account itself, but only after reloading the page.

![21](https://user-images.githubusercontent.com/44948433/131942744-56d83c4c-355e-4113-8185-e1889653e363.png)

## 🙂 Expected Behavior

After entering a username and password, it should immediately be redirected to the main page.

## ☹️ Actual Behavior

Just a spinning circle loading screen and nothing more. It doesn't go away after a minute or two.

## 📝 Steps to Reproduce

1. Just logging into an account
2. Wait about two minutes, give up, and reload the page

## 📌 Environment
Misskey 12.89.2, but the same thing happened when I was still on Misskey 12.89.0.

**Comment by tamaina** [comment]
Close due to out-of-date
