### ISSUE TITLE
Docker build failed in 12.90.0

### ISSUE THREAD

**Issue by junkurihara** [misskey-dev/misskey#7762]
Hello! First of all, I would like to thank all contributors for this unique and fun project! I really like Misskey.

## 💡 Summary

Du to the change of Dockerfile in 12.90.0., `docker build` failed as you can see below.

## 🙂 Expected Behavior

`docker build` should successfully finish.

## ☹️ Actual Behavior

In v12.90.0, it fails as

```:shell
Step 6/18 : RUN git submodule update --init
 ---> Running in 909b730ea6f9
/bin/sh: git: not found
The command '/bin/sh -c git submodule update --init' returned a non-zero code: 127
```

This is actually because `git` is not installed. I've already fixed this. So can I make a PR to develop branch?

## 📝 Steps to Reproduce

1. Just run `docker build -t <your_tag> .`

## 📌 Environment

```
$ docker --version
Docker version 20.10.8, build 3967b7d
```
and GitHub Actions.

**Comment by AMoonRabbit** [comment]
Ah, not just me. When you say you resolved this, did you install git locally or within the container?

**Comment by junkurihara** [comment]
In the container, `apk install git` is required for `git submodule`. Also `.git` must be removed from `.dockerignore`.

**Comment by syuilo** [comment]
> So can I make a PR to develop branch?

Please🙏 Thank you.

**Comment by junkurihara** [comment]
This resolved the issue.
https://github.com/junkurihara/misskey/commit/71ac3fff72c96554d02d10c9ba72ef27f3ab33e8

(I also cleaned up `Dockerfile` to reduce its image.)

**Comment by junkurihara** [comment]
@syuilo OK! Give me a minute.
