### ISSUE TITLE
src下をbackend/frontend/sharedのような構成にしたい

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#7779]
## Summary

ごちゃごちゃしてきたため

- テストもそれぞれのpackage内に置きたい
- ormconfig.jsもbackendに移したい

**Comment by acid-chicken** [comment]
モノリポ化して package ごと分離した方が良さそう

**Comment by syuilo** [comment]
misskey-dev/misskeyはライブラリじゃないから各モジュールをpackageって呼んでいいのかわからないけどそんな感じをイメージしてる

**Comment by syuilo** [comment]
テストとかもそれぞれのpackage内に置きたい

**Comment by syuilo** [comment]
package.jsonも分離した方がすっきりするかしら

**Comment by syuilo** [comment]
やるか

**Comment by tamaina** [comment]
（フォークやプルリクでこれ追従するの、めちゃくちゃ面倒そう）

**Comment by syuilo** [comment]
なのでPRをあらかたマージしてからやりたい

**Comment by syuilo** [comment]
フォークは気にしてたら先に進めない気がする

**Comment by tamaina** [comment]
うーん、diffファイルで良い感じにディレクトリを変更できるパッチ作れないかな（書いたことないけど）

**Comment by syuilo** [comment]
ディレクトリだけじゃなくてビルドやテストの方法とかtsconfigの扱いとか全部変わりそう

**Comment by tamaina** [comment]
require/importのパスが変わるからだめだわ

**Comment by tamaina** [comment]
テストが死んでる

**Comment by tamaina** [comment]
んー、やっぱフォーク開発者的に🤬な感じがある

**Comment by syuilo** [comment]
「フォーク開発者」はどういう人を指してる？

**Comment by tamaina** [comment]
Xeltica氏とか私（でかいPRを未だにOpenしている）とか

**Comment by syuilo** [comment]
私の観測する範囲では積極的にmisskey-dev/misskey追従するフォークプロジェクト開発している人ほとんど見ない(misskey.ioくらい？)
単に「PRのためにフォークしてる人」のことならそんなに追従難しくないから私がconfilict解消する予定

**Comment by syuilo** [comment]
> そんなに追従難しくない

単にディレクトリ変わっただけだから新しくpullしてコピペするだけでできる

**Comment by tamaina** [comment]
うーん、ディレクトリの変更がよくわからないから #7667 のマージやってほしさ

**Comment by rinsuki** [comment]
というかでかいプルリク分割してほしい (でかいとレビューする気になれない)

**Comment by syuilo** [comment]
#7667はまだレビュー時間かかりそう

**Comment by EbiseLutica** [comment]
私のGroundpolisプロジェクトはもう12.69.0で止まっているのでご心配なく

**Comment by tamaina** [comment]
> #7667はまだレビュー時間かかりそう

さっきと言ってることがちがう(などと(自分でやるからええんや…

> プルリク分割

#7667についてはわりと分割した感

**Comment by tamaina** [comment]
キーボードショートカット暴発した

**Comment by syuilo** [comment]
> さっきと言ってることがちがう

あー、マージってdevelop追従のことかな

**Comment by syuilo** [comment]
それにしても追従はdevelopへのマージ段階でやろうと思ってた
今すぐやった方が良いんかしら

**Comment by tamaina** [comment]
んー、自分のインスタンスで動かしてるから面倒だなってだけなので、今すぐしゅいろがやるとかの必要はないと思う

**Comment by rinsuki** [comment]
#7667 は(個人的には)Changesのチェックボックス一個につき1PRレベルで分割してほしい

**Comment by tamaina** [comment]
- そこまで分割すると実装の意味がわからなくなりそう
- しゅいろのPRってけっこうデカいやん

みたいな雰囲気でこれ以上分割するのはどうかと思ったけど…分割するにしても追従終わったらだなぁ

**Comment by tamaina** [comment]
static-assetsが読めてない感
