### ISSUE TITLE
ユーザーインジケーターについてヘルプを作る

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#7787]
## Summary
ここ最近質問が多い

**Comment by syuilo** [comment]
そういや書いてなかったな

**Comment by syuilo** [comment]
Misskey Hubの方で追加した
https://github.com/misskey-dev/misskey-hub/commit/50312faf46d449ed3cdb8ff0dca83c8ac643fc54

**Comment by 4ioskd** [comment]
@tamaina 
しゅいろ氏が書いて下さったみたいですが、どうでしょうか。

**Comment by tamaina** [comment]
ええんちゃう？
https://misskey-hub.net/docs/features/online-status.html
