### ISSUE TITLE
インスタンスプロフィールレンダリング

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#7788]
## Summary
インスタンスのプロフィール(インスタンス名、紹介文、ロゴ画像およびバニャー画像、ユーザー数にゃど)をHTML形式か画像形式でレンダリングするURLを提供すれば、Misskey Hubのインスタンス一覧画面でそれを埋め込むことが出来便利そう

**Comment by tamaina** [comment]
Misskey HubをVuePressにこだわる理由とは…いやまあ別にいいけど

**Comment by syuilo** [comment]
一番しっくり来た

**Comment by syuilo** [comment]
まあ正直どの静的サイトジェネレーター選んでもできることはたいして変わらないだろうから決めの問題

**Comment by tamaina** [comment]
インスタンス一覧は静的サイトジェネレーターである必要性が薄いと思っている。主に画像表示のパフォーマンス面で。

**Comment by syuilo** [comment]
静的サイトジェネレーター以外の選択肢って何かある？

**Comment by syuilo** [comment]
> 主に画像表示のパフォーマンス面で。

詳しく知りたい

**Comment by tamaina** [comment]
> 静的サイトジェネレーター以外の選択肢って何かある？

本当に手前味噌だけどjoinmisskeyでやっとるやんと思っている
https://join.misskey.page/ja-JP/instances

> パフォーマンス

インスタンスバナーを大量表示するとパフォーマンス落ちるじゃん  
(まあlazyloadとか対策はあるけれど…)

**Comment by syuilo** [comment]
この話題はこっちでやりたい

https://github.com/misskey-dev/misskey-hub/issues/3

**Comment by syuilo** [comment]
> 本当に手前味噌だけどjoinmisskeyでやっとるやんと思っている

joinmisskeyがどのような仕組みでインスタンス一覧出してるのかよく知らなかった

**Comment by tamaina** [comment]
misskey-dev/misskey-hub#3 で解説する
