### ISSUE TITLE
Help debugging why Misskey cannot follow an Owncast account

### ISSUE THREAD

**Issue by gabek** [misskey-dev/misskey#8165]
Hello.  In testing ActivityPub Federation support between Owncast and Misskey I found I've been unable to follow an Owncast account from Misskey.  The follow request is handled and accepted by Owncast, but nothing happens on the Misskey side when the `Accept` is sent to it.

Could you point me in the right direction of what might be missing to fix this incompatibility?

## 💡 Summary

Unable to follow an Owncast server from Misskey.  The Follow `Accept` activity from Owncast that is sent from Owncast to Misskey is ignored and the state stays in `Processing...`.

## 🙂 Expected Behavior

`Processing...` should conclude and the user will be seen as Followed.

## ☹️ Actual Behavior

Misskey stays in `Processing...` status and the Owncast user is not successfully followed.

## 📝 Steps to Reproduce

1. Visit an Owncast profile with Misskey.
2. Press "Follow".
3. Owncast receives the Follow request and sends back an `Accept`.
4. Nothing further happens.

An example Owncast profile is: https://misskey.io/@demo@watch.owncast.online

The following `Accept` payload is what is sent to Misskey:

```
{"@context":"https://www.w3.org/ns/activitystreams","actor":"https://OWNCAST_SERVER/federation/user/testing","id":"https://OWNCAST_SERVER/federation/FoC_r6Jng","object":"https://misskey.io/2395e9f0-4e85-42d3-bb27-63180fb5b258","type":"Accept"}
```
Sent to https://misskey.io/users/8vr4n4kqug/inbox

**Comment by gabek** [comment]
Hi there. Just checking in to see if anybody has any suggestions on what might be an issue here.  Other ActivityPub powered services can follow Owncast servers, but Misskey can't. So if there's something specific that I'm missing that I need to add so this can be fixed, I'd love to resolve it. I want all the Misskey users out there to be able to take advantage of following Owncast, too.

**Comment by Amolith** [comment]
I don't know much about TypeScript or Misskey's codebase but I'd be more than happy to help debug things and provide admin-side logs; I run instances of both Owncast and Misskey.

**Comment by mei23** [comment]
Understood. Does not support hs2019. 
> signature parse error: InvalidParamsError: hs2019 is not supported

I will consider it.

**Comment by gabek** [comment]
Thank you for looking into it!  PeerTube recently made the change to support `hs2019` with [this fork](https://github.com/Chocobozzz/node-http-signature), so maybe you could drop that in as well.

**Comment by mei23** [comment]
Memo:
ParserでPeerTubeの[fork](https://github.com/Chocobozzz/node-http-signature)を使うのもあるが、未定義のデフォルトをsha512=>sha256にした方が良さそう。

またはガッツリ書いちゃうか
https://github.com/digitalbazaar/http-signature-header
https://github.com/mei23/crytest/blob/mein/src/http-signature.ts

**Comment by mei23** [comment]
Okay, I fixed the HTTP signature.
However, I got stuck with a 307 redirect. hmm ...
See a little more.

**Comment by gabek** [comment]
If it's helpful, Owncast will redirect if you try to access an ActivityPub resource without using an `Accept` header of either "application/json", "application/json+ld" or "application/activity+json".

**Comment by 4ioskd** [comment]
FYI:
英語圏を中心としたmisskeyユーザーがOwncastのサーバーを建てるか他人のサーバーにアカウントを作って配信する、またはOwncastで配信をする度に配信URLをmisskeyのノートに貼って投稿するのをよく見かけるようになりました。私はコードコントリビューターではないですが、misskeyとOwncastがActivityPubで連合されて、両プラットフォームを利用するユーザーにより良い環境がもたらされることを願ってやみません。
ちなみに、個人的にはOwncastは好きなfediプラットフォームの一つです。

**Comment by gabek** [comment]
Somebody has been helping me look a bit deeper into this and they mentioned something that I hadn't noticed before:

When Misskey sends a `Follow` request to Owncast, its ID is not valid.  For example the `Follow` request from Misskey sent to Owncast

```
{"actor":"https://misskey.io/users/8vr4n4kqug","id":"https://misskey.io/474402c5-f7f2-41e4-9427-2ed3e0a83024","object":"https://auth-testing-001.ngrok.io/federation/user/streamer","type":"Follow"}
```

Has the ID of `https://misskey.io/474402c5-f7f2-41e4-9427-2ed3e0a83024`. Fetching that returns an invalid response.
```
curl -H "Accept: application/activity+json" "https://misskey.io/474402c5-f7f2-41e4-9427-2ed3e0a83024"
...
<!DOCTYPE html><!--
  _____ _         _
 |     |_|___ ___| |_ ___ _ _
 | | | | |_ -|_ -| '_| -_| | |
 |_|_|_|_|___|___|_,_|___|_  |
                         |___|
 Thank you for using Misskey!
 If you are reading this message... how about joining the development?
 https://github.com/misskey-dev/misskey
-->
<html><head><meta charset="utf-8">
...
```

So when Owncast sends back an `Accept` with the above ID as the `object` I'm not sure what is happening on the Misskey side.

To work around this I tried replacing the `object` on the `Accept` with the fully resolved `Follow` request, just in case Misskey is trying to resolve that above invalid ID for some reason, but that didn't seem to make a difference.

**Comment by gabek** [comment]
It seems like sending along the fully resolved follow as the `object` _does_ work, but I was testing on a Misskey server that did not yet have the `hs2019` signature update.

Do you know the status of getting that change merged into the shipping version?

**Comment by 4ioskd** [comment]
Although I'm not a code contributor, it seems that the hs2019 signature isn't yet supported in the latest misskey v12.110.0

**Comment by mei23** [comment]
If Owncast returns a full object on Accept, it should work if you modify Misskey's HTTP Signature library.

誰か、misskey-devあたりにforkして置き換えたりしてもらえるといいんじゃないかしら
https://github.com/mei23/node-http-signature

**Comment by gabek** [comment]
I understand. But when is Misskey's HTTP Signature library going to be updated for all Misskey users?

**Comment by gabek** [comment]
Hi there, just checking in again. What are the plans for getting HTTP signature support into people's hands?

**Comment by Johann150** [comment]
The peertube folks seem to have released their version to NPM: [`@peertube/http-signature`](https://www.npmjs.com/package/@peertube/http-signature)
I think we should be able to use that, forking to misskey-dev seems unnecessary.

**Comment by mei23** [comment]
The fork of peertube has been set to sha512, so it doesn't work.
Need to change to sha256.
https://github.com/mei23/node-http-signature

**Comment by Johann150** [comment]
Are you sure? I just tested the linked PR with Pleroma & Mastodon and posting seemed to work both ways. But maybe that is because they use LD signatures in that case.

I am confused because Peertube seems to use it like that itself, so it works for them?

**Comment by Johann150** [comment]
I just looked at the latest RFC draft for HTTP signatures I could find and it also says to use SHA-512 from what I understand:
> For example, assume that the `algorithm` value was "hs2019" and and the `keyId` refers to an EdDSA public key. This would signal to the application that [...] the signature string hashing function is SHA-512 [...].
> https://tools.ietf.org/id/draft-cavage-http-signatures-12.html#verify

and again later:
> Algorithm Name: hs2019
> [...]
> Hash Algorithm: [RFC 6234](https://tools.ietf.org/id/draft-cavage-http-signatures-12.html#RFC6234), SHA-512 (SHA-2 with 512-bits of digest output)
> https://tools.ietf.org/id/draft-cavage-http-signatures-12.html#hsa-registry

**Comment by mei23** [comment]
> Are you sure? I just tested the linked PR with Pleroma & Mastodon and posting seemed to work both ways. But maybe that is because they use LD signatures in that case.

Pleroma & Mastodon doesn't matter because They won't be sent in hs2019.

**Comment by mei23** [comment]
> ... the signature string hashing function is SHA-512 [...].

This is an example when the signature is not what you expected, so sha512 has no meaning.


> Hash Algorithm: [RFC 6234](https://tools.ietf.org/id/draft-cavage-http-signatures-12.html#RFC6234), SHA-512 (SHA-2 with 512-bits of digest output)

RFC 6234 contains sha256

**Comment by mei23** [comment]
Currently, if it is sent by hs2019, it can only be treated as sha256.
See also the Mastodon implementation below.

https://github.com/mastodon/mastodon/pull/14556
> add support for the hs2019 signature algorithm (assumed to be equivalent to RSA-SHA256, since we do not have a mechanism to specify the algorithm within the key metadata yet)

**Comment by Johann150** [comment]
Okay, I think we do not have to fork the entire library, we just have to replace `hs2019` algorithm with `rsa-sha256` between parsing and validation. This means we still have to change out the library because the old one will throw an error for `hs2019`.

I would personally still want to avoid forking the library entirely because of the maintenance that may be necessary.

**Comment by Johann150** [comment]
[`@peertube/http-signature`](https://www.npmjs.com/package/@peertube/http-signature) has been updated and now includes @mei23's changes as of https://github.com/Chocobozzz/node-http-signature/commit/369aa7588fb8807dff219425e0a7be953c036181
So I think we can now use that instead of our own fork?

**Comment by gabek** [comment]
Thanks, everyone!
