### ISSUE TITLE
モバイル版(Android)での新規投稿画面の動作

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#82]
新規投稿をやめて戻りたい場合、左上の✕だけでなくBackキーを押しても戻れるようにしてほしい

----

* Android Firefox / Chrome
* モバイル版Misskey

**Comment by syuilo** [comment]
Backきー？

**Comment by syuilo** [comment]
キーボードのことかな？

**Comment by syuilo** [comment]
あーブラウザ由来のか

**Comment by tamaina** [comment]
取得するのは結局ブラウザ由来の戻るになると思います...

**Comment by tamaina** [comment]
Android PieでBackキーが廃止されたのでもうなしで
