### ISSUE TITLE
モバイル版メニューについて

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#83]
- 味気ないのでにゅっと出てくるアニメーションが欲しいです
- 画面端からスワイプで出せるといいと思います

----

* Android Firefox Beta / Chrome
* モバイル版Misskey

**Comment by syuilo** [comment]
にゅっと出てくるアニメーションは実装された

**Comment by syuilo** [comment]
スワイプはブラウザのジェスチャと競合しそう

**Comment by tamaina** [comment]
- アニメーション←できた
- スワイプは…切れるようにすればよさそう → #4606
