### ISSUE TITLE
Large gap for remote post

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#8617]
## 💡 Summary

Large gap for remote post

![misskeyextraspace](https://user-images.githubusercontent.com/60059665/130887294-7fb3702e-f718-4a29-8f2f-34679cb8f08f.jpg)

## 🙂 Expected Behavior

Normal gap like other posts

## ☹️ Actual Behavior

When viewing the timeline, some posts have large gap

## 📝 Steps to Reproduce

1. you can see this post: https://cliq.social/notes/8pi91yb4qk

## 📌 Environment

misskey 12.89.0 - nginx 1.21.1 - node 12.22.5 - postgresql v13.4

**Comment by nullobsi** [comment]
the activity from pixelfed has \<br/> \n \<br>\n in the source

this isnt so much a misskey bug, it's just interpreting the source data as it should

**Comment by cliqsocial** [comment]
> the activity from pixelfed has <br/> \n <br>\n in the source
> 
> this isnt so much a misskey bug, it's just interpreting the source data as it should

Are you sure it's not Misskey? Pleroma, Mastodon and Pixelfed **does not** have this problem

**Comment by syuilo** [comment]
> > the activity from pixelfed has  \n \n in the source
> > this isnt so much a misskey bug, it's just interpreting the source data as it should
> 
> Are you sure it's not Misskey? Pleroma, Mastodon and Pixelfed **does not** have this problem

Misskey is just interpreting it as is, so it could rather be Mastodon, Pleroma, or Pixelfedi that is the problem.

**Comment by syuilo** [comment]
I don't think Misskey can collapse line breaks, as users may want to intentionally create such line spacing.

**Comment by nullobsi** [comment]
Misskey tries to parse the activity content as MFM, first by parsing the HTML it recieves...
https://github.com/misskey-dev/misskey/blob/develop/src/mfm/from-html.ts
Mastodon doesn't add return characters to its content, and neither does misskey (it uses a BR tag, or in Mastodon's case, seperate P tags)
Technically HTML parsers are supposed to ignore newlines. But, I don't know how removing newlines could affect certain formattings from other Misskey instances.

**Comment by Johann150** [comment]
I think it could be sensible to replace `<br>` tags followed by newlines with just a newline.

**Comment by marihachi** [comment]
おそらく、改行を省略する処理はHTMLパースのレイヤーで行うべきです。
HTMLを使用していないソフトウェアでは、MFMパーサーが改行を削除する必要はありません。

MisskeyのHTML->MFM変換をしている部分に処理を追加すべきな気がします。

**Comment by marihachi** [comment]
Misskeyの改行の解釈を変更するのかどうかについては特に考えはありません。
変更されるとしてもMFMパーサー側の責務ではないだろうということです。
