### ISSUE TITLE
デスクトップでの通知が遅延する

### ISSUE THREAD

**Issue by otofune** [misskey-dev/misskey#87]
おそらく次の通知が来た段階でその前の通知が表示されている (次の通知は表示されない)

**Comment by syuilo** [comment]
通知というと

**Comment by otofune** [comment]
これですね (通知が2つあるのでどっちかわかりにくくて申し訳ない)
問題の通知:
![image](https://cloud.githubusercontent.com/assets/15062473/22364504/590e5160-e4b5-11e6-959e-74e14c62ae89.png)
正常に動く通知:
![image](https://cloud.githubusercontent.com/assets/15062473/22364514/662f5a42-e4b5-11e6-9141-f90c06e52ad9.png)

**Comment by syuilo** [comment]
ふぅ〜む

**Comment by syuilo** [comment]
もしかしたらこれに関連してるかも
https://github.com/riot/riot/issues/2205 および https://github.com/riot/riot/issues/2228

**Comment by syuilo** [comment]
(頭の中で)デバッグしてみた感じでは問題なさそうだし通知関連のコード最近いじってないしやったことといえばRiotをアップデートしたくらいなので可能性はある

**Comment by syuilo** [comment]
タイムラインの投稿が消失する現象も確認しました おそらく関連してそうです
