### ISSUE TITLE
設定でデバッグモードの有効/無効を切り替えられるようにする

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#937]

**Comment by otofune** [comment]
ビルド時のNODE_ENVからだとだめなのか？デバッグというとログが出るのだと思うけれど

**Comment by syuilo** [comment]
それだとやっぱりサーバーごとにビルドしないといけなくなりそう それでもいいんだけど

**Comment by otofune** [comment]
そもそもサーバーでビルドするのは悪いことじゃないし、リリースビルドとして出すのは production 向け！って記載してしまえばいいんじゃないか、と思います
