### ISSUE TITLE
連続して$を入力すると、$が消える

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#948]
**入力**
```
$
$$
$$$
$$$$
$$$$$
$$$$$$
$$$$$$$
$$$$$$$$
```

↓

**表示**
```
$
$
$$
$$
$$$
$$$
$$$$
$$$$
```

連続するn個の$が、タイムラインにおいてn/2(小数点以下繰り上げ)個として表示される。

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/33240795-4bd00f1e-d2ff-11e7-9a00-0ca5ddbd77db.png)

**Comment by syuilo** [comment]
コンパイラまわりを一から書き直した影響で意図せず直ってた(結局原因は謎のまま)
