### ISSUE TITLE
長いファイル名やユーザー名が突き抜ける

### ISSUE THREAD

**Issue by otofune** [misskey-dev/misskey#97]
モバイル。デスクトップでも起きうると思うけど未確認。
ファイル名での例です
![screenshot_20170130-132107 2](https://cloud.githubusercontent.com/assets/15062473/22412231/84ad8c1e-e6ef-11e6-8805-0533a2a68c0f.png)

**Comment by tamaina** [comment]
長いのは名前なのであまり問題ない気がします

**Comment by syuilo** [comment]
技術的なことを言うと、表示可能領域の幅があらかじめわかっている場合は ... と省略することができる
逆に表示可能な領域の幅が動的な場合(その画像だと右にパーセンテージやKB表示がある)、省略のしようがない

**Comment by otofune** [comment]
~~rightでネガティブマージン指定してから省略指定すればよさそうじゃないか？~~

**Comment by otofune** [comment]
脳無しなコメントをしてしまって申し訳ない
アップロード画面であれば、可変なKB表示を無くしてしまえば被らないように隠せる為モバイルだけ変更するというのはどうでしょう
TL上のユーザー名が突き抜けるのははユーザー名(ID)、名前、時間とすべて可変なのでどうにもならない感じですが

**Comment by syuilo** [comment]
もしくはKB部分も固定幅にするとか

**Comment by otofune** [comment]
現在のドライブの実装ではアップロードサイズ制限が無いようなので、幅を固定にしたらサイズが大きいファイルだと隠れそうだ、サイズに合わせてMBやGB表示になるようにして常時"3桁 / 3桁 単位"になるようにしたらあるいは
