### ISSUE TITLE
画像を圧縮する

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#984]
全てWebPで配信したり、jpegならプログレッシブjpegにしたりmozjpegをかけたり、pngならpngquantをかけたり、大きさに制限をかける、など

ドライブの役割との矛盾もあると思いますが…

とりあえずfile.himasaku.netのthumbnailをプログレッシブjpegかwebpへ変換することを強く希望します

**Comment by syuilo** [comment]
やり方がわからない

**Comment by tamaina** [comment]
http://aheckmann.github.io/gm/docs.html みて

**Comment by tamaina** [comment]
|操作|gm/npm|
|-----|----------|
|jpegをプログレッシブに|`.interlace('line')`|
|webpに|`.setFormat('webp')`?|
|pngquant|https://www.npmjs.com/package/pngquant|
|mozjpeg|https://www.npmjs.com/package/mozjpeg-stream|

**Comment by syuilo** [comment]
webpはiOS対応してないらしい

**Comment by acid-chicken** [comment]
FirefoxがWebPに対応し残るはiOSのみとなったので、通信量削減のためにもpolyfill入れてでも対応したさがある。
FYI: https://github.com/FallingSnow/webp-polyfill

**Comment by syuilo** [comment]
jpegと大して変わらないという話を聞いたことがあるので、わざわざ不便なwebpを使う必要があるのか疑問

**Comment by acid-chicken** [comment]
高画質な配信では大差ないが、サムネイルなどではWebPが効率良さそうではある。また、ドライブからの添付というのを考えると高画質版はオリジナルのMIMEタイプで配信するべきかもしれない。（Related to <https://github.com/syuilo/misskey/issues/4091#issuecomment-459958303>）
