### ISSUE TITLE
投稿に画像が複数枚添付されているとき、画像ダイアログに前の画像 / 次の画像に切り替えられるボタンをつける

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#993]
~~ただ、Twitterみたいに投稿も一緒に表示するのはやめてほしいです~~

**Comment by tamaina** [comment]
いやむしろ投稿も一緒に表示してほしいんだけど  
（Twitterが今のような右端に表示するものではなかったからこういうことを言った可能性？）

**Comment by Johann150** [comment]
solved by e52a9e0a6529a9c739c5237c165b68861a9390dc
